src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterDetalhamentoFechamentoConselhoClasseAlunoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ObterComponentesFechamentoConsolidadoPorTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterDisciplinasTurmasEol/ObterDisciplinasTurmasEolQueryHandler.cs, src/SME.SGP.Infra/Dtos/RetornoDisciplinaDto.cs
[AB#64370](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64370)
=> fix/64370 -> release-r2

src/SME.SGP.Aplicacao/Commands/PlanoAula/MigrarPlanoAula/MigrarPlanoAulaCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs, src/SME.SGP.Infra/Dtos/Turma/TurmaNaoHistoricaDto.cs
[AB#76274](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76274) - Erro ao migrar turma para outro ano(Regência de Classe)
=> Fix/76274 - Erro ao migrar turma para outro ano(Regência de Classe)

src/SME.SGP.Dados/Repositorios/RepositorioFechamentoConsolidado.cs
[AB#76083](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76083)
=> fix/76083 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#76241](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76241)
=> fix/76241 -> master

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterDetalhamentoFechamentoConselhoClasseAlunoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ObterComponentesFechamentoConsolidadoPorTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterDisciplinasTurmasEol/ObterDisciplinasTurmasEolQueryHandler.cs, src/SME.SGP.Infra/Dtos/RetornoDisciplinaDto.cs
[AB#64370](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64370)
=> Fix/64370 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterComponentesCurricularesPorUeAnosModalidadeUseCase/ObterComponentesCurricularesPorUeAnosModalidadeUseCase.cs
[AB#76104](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76104)
=> Fix/76104 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasConselhoClasseAlunoTeste.cs
[AB#76218](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76218)
=> Conselho de classe - Não está mostrando os dados de frequência para território do saber

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs
[AB#76224](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76224)
=> Fix/76224 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
[AB#76355](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76355) 
[AB#74395](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74395)
=> Erro ao filtrar turma

src/SME.SGP.Aplicacao/CasosDeUso/Turma/VerificarPendenciasFechamentoTurmaDisciplinaUseCase.cs, src/SME.SGP.Aplicacao/Commands/PendenciaFechamento/VerificaPendenciasFechamento/VerificaPendenciasFechamentoCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciaFechamento/VerificaPendenciasFechamento/VerificaPendenciasFechamentoCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaFechamento.cs, src/SME.SGP.Dominio.Interfaces/Servicos/IServicoPendenciaFechamento.cs, src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs, src/SME.SGP.Infra/Dtos/PendenciaFechamentoCompletoDto.cs
[AB#76098](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76098)
=> Inclusão da fila de consolidação de fechamento componente turma  na aprovação manual de pendências

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterComponentesCurricularesPorUeAnosModalidadeUseCase/ObterComponentesCurricularesPorUeAnosModalidadeUseCase.cs
[AB#76104](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76104)
=> fix/76104 -> master

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs
[AB#75113](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75113)
=> Correção do bug 75113

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs
[AB#76224](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76224)
=> fix/76224 -> master

src/SME.SGP.Dados/Repositorios/RepositorioFechamentoConsolidado.cs
[AB#76083](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76083)
=> fix/76083 -> master

scripts manutencao/76098 - Atualizar consolidações/76098 - Script - atualizacao consolidacao.sql
[AB#76098](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76098)
=> Incluído script que foi atualizado em prod

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs
[AB#76243](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76243)
=> Fix do bug 76243

scripts manutencao/72529 - Exclusão Diário de Bordo/diario_bordo_exclusao.txt
[AB#72529](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72529)
[AB#76453](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76453)
[AB#75105](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75105)
=> Criação do script que remove os diários de bordos duplicados - mantendo mais recente

scripts manutencao/72529 - Exclusão Diário de Bordo/diario_bordo_exclusao.txt
[AB#72529](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72529)
=> Script remove diários de bordos duplicados --> MASTER

src/SME.SGP.Aplicacao/Comandos/ComandosConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorTurmasCodigo/ObterComponentesCurricularesPorTurmasCodigoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQuery.cs, src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasComMatriculasValidas/ObterTurmasComMatriculasValidasQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasComMatriculasValidas/ObterTurmasComMatriculasValidasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasComMatriculasValidas/ObterTurmasComMatriculasValidasQueryValidator.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioAluno.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioFechamentoNota.cs
[AB#76376](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76376)
=> Conselho de classe - Existe(m) componente(s) curriculares sem a nota informada.

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
[AB#76491](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76491) - Turmas duplicadas no ambiente de automação
[AB#76577](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76577)
=> Fix/76491 - Turmas duplicadas no ambiente de automação

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs, src/SME.SGP.Infra/Dtos/Turma/RetornoConsultaListagemTurmaComponenteDto.cs
[AB#76571](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76571)
=> 76571 - erro deserialização json

src/SME.SGP.Aplicacao/Commands/Notificacao/ExcluirNotificacao/ExcluirNotificacaoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Notificacoes/NotificarExclusaoNotificacao/NotificarExclusaoNotificacaoCommand.cs, src/SME.SGP.Aplicacao/Commands/Notificacoes/NotificarExclusaoNotificacao/NotificarExclusaoNotificacaoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Notificacoes/NotificarLeituraNotificacao/NotificarLeituraNotificacaoCommandHandler.cs, src/SME.SGP.Dados/Mapeamentos/NotificacaoMap.cs, src/SME.SGP.Dominio/Entidades/Notificacao.cs, src/SME.SGP.Notificacoes.Hub.Interface/Dtos/MensagemExclusaoNotificacaoDto.cs, src/SME.SGP.Notificacoes.Hub.Interface/Dtos/MensagemLeituraNotificacaoDto.cs, src/SME.SGP.Notificacoes.Hub/Eventos/EventoNotificacaoExcluida.cs, src/SME.SGP.Notificacoes.Hub/Eventos/EventoNotificacaoLida.cs
nas notificações do HUB para controle do contador de notificaçãoes no front
[AB#75994](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75994)
=> 75994 Enviar atributo AnoAnterior

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ObterAcompanhamentoAlunoUseCase.cs
[AB#76604](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76604)
=> Correção do bug 76604

src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/SalvarConselhoClasseAlunoNotaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAula/ExcluirPlanoAulaUseCase.cs, src/SME.SGP.Aplicacao/Comandos/ComandosAtividadeAvaliativa.cs, src/SME.SGP.Aplicacao/Comandos/ComandosPlanoAnual.cs, src/SME.SGP.Aplicacao/Comandos/ComandosPlanoAnualTerritorioSaber.cs, src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaRecorrente/AlterarAulaRecorrenteCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Aulas/ValidarComponentesDoProfessor/ValidarComponentesDoProfessorCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/InserirFrequenciasAula/InserirFrequenciasAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQueryHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioFechamentoNota.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagensNegocioFrequencia.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagensNegocioLancamentoNota.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_registrar_aula_normal_repetir_bimestre_atual_excecoes_basicas.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_registrar_aula_normal_repetir_bimestre_atual_sem_permissao.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_registrar_aula_professor_cj.cs, teste/SME.SGP.TesteIntegracao/Avaliacao/Ao_registrar_avaliacao_pelo_professor_permissao_encerrada.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_inserir_nota_pos_conselho_professor_regente_anterior.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Ao_alterar_frequencia_pelo_professor_cj.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Ao_inserir_frequencia_com_inconsistencias.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Ao_inserir_frequencia_professor_cj.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Base/FrequenciaTesteBase.cs, teste/SME.SGP.TesteIntegracao/Nota/Ao_registrar_nota_gera_excecao_para_atribuicao_encerrada.cs, teste/SME.SGP.TesteIntegracao/NotaFechamentoFinal/Ao_lancar_nota_professor_sem_atribuicao.cs
[AB#76589](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76589)
=> Correção da alteração de atividades avaliativas

src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterAbrangenciaTurmasPorUeModalidadePeriodoHistoricoAnoLetivoTipos/ObterAbrangenciaTurmasPorUeModalidadePeriodoHistoricoAnoLetivoTiposQuery.cs
[AB#76519](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76519)
=> fix/76519 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
[AB#76814](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76814)
=> 76814 - Ajuste busca de abrangencias históricas turma

src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaPlanoAulaUseCase.cs, src/SME.SGP.Aplicacao/Commands/PendenciasGerais/ExcluirPendenciasPorIds/ExcluirPendenciasPorIdsCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciasGerais/ExcluirPendenciasPorIds/ExcluirPendenciasPorIdsQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciaPlanoAulaPorDreIdUeIdModalidade/ObterPendenciaPlanoAulaPorDreIdUeIdModalidadeQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciaPlanoAulaPorDreIdUeIdModalidade/ObterPendenciaPlanoAulaPorDreIdUeIdModalidadeQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs
[AB#76256](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76256)
=> Fix/76256 -> r2

teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_alterar_plano_aula.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_cp_diretor.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/ServicosFakes/ObterAbrangenciaTurmaQueryFake.cs
=> Bug: 76266

src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaPlanoAulaUseCase.cs, src/SME.SGP.Aplicacao/Commands/PendenciasGerais/ExcluirPendenciasPorIds/ExcluirPendenciasPorIdsCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciasGerais/ExcluirPendenciasPorIds/ExcluirPendenciasPorIdsQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciaPlanoAulaPorDreIdUeIdModalidade/ObterPendenciaPlanoAulaPorDreIdUeIdModalidadeQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciaPlanoAulaPorDreIdUeIdModalidade/ObterPendenciaPlanoAulaPorDreIdUeIdModalidadeQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs
[AB#76256](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76256)
=> fix/76256 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesQuePodeVisualizar/ObterComponentesCurricularesQuePodeVisualizarHojeQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/EOL/ComponentesCurriculares/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfilQuery.cs, src/SME.SGP.Aplicacao/Queries/EOL/ComponentesCurriculares/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfilQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfilQuery.cs, src/SME.SGP.Aplicacao/Queries/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfilQueryHandler.cs
[AB#75359](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75359)
=> fix/75359 -> r2

src/SME.SGP.Dados/Mapeamentos/ConsolidacaoRegistroIndividualMediaMap.cs
[AB#77070](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77070)
=> fix/77070 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterAulaPorIdUseCase.cs
[AB#75196](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75196)
=> Fix/75196 -> release-r2

scripts/V569__INSERT_PARAMETRO_SISTEMA_EXECUCAO_CONSOLIDACAO_DIARIO_BORDO_2022.sql
[AB#77071](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77071)
=> fix/77071 -> r2

src/SME.SGP.Api/Filtros/PermissaoAttribute.cs, src/SME.SGP.Aplicacao/Comandos/ComandosUsuario.cs, src/SME.SGP.Aplicacao/Commands/Autenticacao/DeslogarSuporteUsuario/DeslogarSuporteUsuarioCommandHandler.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosUsuario.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Aplicacao/Servicos/ServicoAutenticacao.cs, src/SME.SGP.Infra/Dtos/RetornoDadosAcessoUsuarioSgpDto.cs, teste/SME.SGP.Aplicacao.Teste/Comandos/ComandosUsuarioTeste.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
[AB#76601](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76601)
=> Alterar Autenticação SGP

src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterAulaPorIdUseCase.cs
[AB#75196](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75196)
=> fix/75196 -> master

src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
[AB#75961](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75961)
=> Validar todas as queries do repositório

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseUseCase.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoConselhoClasse/ExcluirConsolidacaoConselhoPorIdBimestre/ExcluirConsolidacaoConselhoPorIdBimestreCommand.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoConselhoClasse/ExcluirConsolidacaoConselhoPorIdBimestre/ExcluirConsolidacaoConselhoPorIdBimestreCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/ConsolidacaoConselhoClasse/ObterConsolidacoesConselhoClasseAtivasIdPorAlunoETurma/ObterConsolidacoesConselhoClasseAtivasIdPorAlunoETurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/ConsolidacaoConselhoClasse/ObterConsolidacoesConselhoClasseAtivasIdPorAlunoETurma/ObterConsolidacoesConselhoClasseAtivasIdPorAlunoETurmaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ConsolidacaoConselhoClasse/ObterConsolidacoesConselhoClasseNotaPorConsolidacaoAlunoIdsBimestre/ObterConsolidacoesConselhoClasseNotaPorConsolidacaoAlunoIdsBimestreQuery.cs, src/SME.SGP.Aplicacao/Queries/ConsolidacaoConselhoClasse/ObterConsolidacoesConselhoClasseNotaPorConsolidacaoAlunoIdsBimestre/ObterConsolidacoesConselhoClasseNotaPorConsolidacaoAlunoIdsBimestreQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidado.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidadoNota.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseConsolidado.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseConsolidadoNota.cs
[AB#77073](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77073)
=> fix/77073 -> r2

scripts/V569__INSERT_PARAMETRO_SISTEMA_EXECUCAO_CONSOLIDACAO_DIARIO_BORDO_2022.sql
[AB#77071](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77071)
=> fix/77071 -> master

teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
[AB#76084](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76084)
=> Correção no teste

scripts/V569__INSERT_PARAMETRO_SISTEMA_EXECUCAO_CONSOLIDACAO_DIARIO_BORDO_2022.sql, src/SME.SGP.Aplicacao/Queries/Aula/ObterPodeCadastrarAulaPorData/ObterPodeCadastrarAulaPorDataQueryHandler.cs
[AB#77173](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77173)
=> Fix/77173 -> release-r2

src/SME.SGP.Infra/Dtos/Relatorios/AcompanhamentoFrequencia/FiltroAcompanhamentoFrequenciaJustificativaDto.cs
[AB#65257](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65257)
=> 65257 - Alterar consulta do relatório de frequência

src/SME.SGP.Api/Filtros/PermissaoAttribute.cs, src/SME.SGP.Aplicacao/Comandos/ComandosUsuario.cs, src/SME.SGP.Aplicacao/Commands/Autenticacao/DeslogarSuporteUsuario/DeslogarSuporteUsuarioCommandHandler.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosUsuario.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Aplicacao/Servicos/ServicoAutenticacao.cs, src/SME.SGP.Infra/Dtos/RetornoDadosAcessoUsuarioSgpDto.cs, teste/SME.SGP.Aplicacao.Teste/Comandos/ComandosUsuarioTeste.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
[AB#75112](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75112)
[AB#77111](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77111)
=> Story/75112 --> RELEASE

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RegistrarEncaminhamentoAEEUseCase.cs
[AB#76799](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76799)
=> Correção do bug 76799

src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/ObterListaSemestresUseCase.cs, src/SME.SGP.Aplicacao/Comandos/ComandosRelatorioSemestralPAPAluno.cs, src/SME.SGP.Aplicacao/Queries/FechamentoReabertura/ObterFechamentoReaberturaBimestrePorFechamentoReaberturaId/ObterFechamentoReaberturaBimestrePorFechamentoReaberturaIdQuery.cs, src/SME.SGP.Aplicacao/Queries/FechamentoReabertura/ObterFechamentoReaberturaBimestrePorFechamentoReaberturaId/ObterFechamentoReaberturaBimestrePorFechamentoReaberturaIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterSemestresComReaberturaAtivaPAP/ObterSemestresComReaberturaAtivaPAPQuery.cs, src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterSemestresComReaberturaAtivaPAP/ObterSemestresComReaberturaAtivaPAPQueryHandler.cs, src/SME.SGP.Infra/Dtos/SemestreAcompanhamentoDto.cs
[AB#77269](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77269)
=> Fix/77269 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/ObterListaSemestresUseCase.cs
[AB#77269](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77269)
=> fix/77269 (pt.2) -> r2

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
[AB#77279](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77279)
=> fix/77279 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/ObterListaSemestresUseCase.cs, src/SME.SGP.Aplicacao/Comandos/ComandosRelatorioSemestralPAPAluno.cs, src/SME.SGP.Aplicacao/Queries/FechamentoReabertura/ObterFechamentoReaberturaBimestrePorFechamentoReaberturaId/ObterFechamentoReaberturaBimestrePorFechamentoReaberturaIdQuery.cs, src/SME.SGP.Aplicacao/Queries/FechamentoReabertura/ObterFechamentoReaberturaBimestrePorFechamentoReaberturaId/ObterFechamentoReaberturaBimestrePorFechamentoReaberturaIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterSemestresComReaberturaAtivaPAP/ObterSemestresComReaberturaAtivaPAPQuery.cs, src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterSemestresComReaberturaAtivaPAP/ObterSemestresComReaberturaAtivaPAPQueryHandler.cs, src/SME.SGP.Infra/Dtos/SemestreAcompanhamentoDto.cs
[AB#77269](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77269)
=> Fix/77269 -> master

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseUseCase.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoConselhoClasse/ExcluirConsolidacaoConselhoPorIdBimestre/ExcluirConsolidacaoConselhoPorIdBimestreCommand.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoConselhoClasse/ExcluirConsolidacaoConselhoPorIdBimestre/ExcluirConsolidacaoConselhoPorIdBimestreCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/ConsolidacaoConselhoClasse/ObterConsolidacoesConselhoClasseAtivasIdPorAlunoETurma/ObterConsolidacoesConselhoClasseAtivasIdPorAlunoETurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/ConsolidacaoConselhoClasse/ObterConsolidacoesConselhoClasseAtivasIdPorAlunoETurma/ObterConsolidacoesConselhoClasseAtivasIdPorAlunoETurmaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ConsolidacaoConselhoClasse/ObterConsolidacoesConselhoClasseNotaPorConsolidacaoAlunoIdsBimestre/ObterConsolidacoesConselhoClasseNotaPorConsolidacaoAlunoIdsBimestreQuery.cs, src/SME.SGP.Aplicacao/Queries/ConsolidacaoConselhoClasse/ObterConsolidacoesConselhoClasseNotaPorConsolidacaoAlunoIdsBimestre/ObterConsolidacoesConselhoClasseNotaPorConsolidacaoAlunoIdsBimestreQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidado.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidadoNota.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseConsolidado.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseConsolidadoNota.cs
[AB#77073](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77073)
=> fix/77073 -> master

src/SME.SGP.Aplicacao/Queries/Aula/ObterPodeCadastrarAulaPorData/ObterPodeCadastrarAulaPorDataQueryHandler.cs
[AB#77173](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77173)
=> Fix/77173 -> master

src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs, src/SME.SGP.Infra/Dtos/PlanoAulaDto.cs
[AB#76130](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76130)
=> Correção do bug 76130

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseUseCase.cs
=> Bug: 69378

src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/AtribuirResponsavelPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/AtribuirResponsavelPlanoAEE/AtribuirResponsavelPlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/AtribuirResponsavelPlanoAEE/AtribuirResponsavelPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarParecerCP/CadastrarParecerCPCommandHandler.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioPlanoAee.cs
[AB#66327](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66327)
=> Feature/66327 - Alterar Endpoint de Parecer da Gestão

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
[AB#77279](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77279)
=> Fix/77279 -> master

src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ExcluirPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/ExcluirPlanoAEE/ExcluirPlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/ExcluirPlanoAEE/ExcluirPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IExcluirPlanoAEEUseCase.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#66410](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66410)
=> 66410 - End point exclusão de plano AEE com exclusão de pendencias e obs

src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterConselhoClasseAlunoPorConselhoFechamentoAlunoCodigo/ObterConselhoClasseAlunoPorConselhoFechamentoAlunoCodigoQueryHandler.cs
[AB#77247](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77247)
=> Correção do bug 77247

src/SME.SGP.Aplicacao/Queries/ObterPerfilDoToken/ObterPerfilDoTokenQuery.cs, src/SME.SGP.Aplicacao/Queries/ObterPerfilDoToken/ObterPerfilDoTokenQueryHandler.cs
[AB#75112](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75112)
=> Correção dos namespaces para net 5

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommandHandler.cs
[AB#76101](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76101)
=> fix/76101 -> r2

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUsuarioECodigoTurma/ObterComponentesCurricularesPorUsuarioECodigoTurmaQueryHandler.cs
[AB#77405](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77405)
=> Fix/77405 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/Notificacoes/ObterUltimasNotificacoesNaoLidasNotificacoesNaoLidasPorUsuarioUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioNotificacao.cs, src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoConsulta.cs
Ajustes ao resgatar informações de notificação para login que não possui código RF.
=> Bug: 77402

teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/Base/RelatorioAcompanhamentoAprendizagemTesteBase.cs, teste/SME.SGP.TesteIntegracao/SME.SGP.TesteIntegracao.csproj, teste/SME.SGP.TesteIntegracao/ServicosFakes/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfilQueryHandlerFakeOutras.cs
[AB#74027](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74027)
=> Configuração da base

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUsuarioECodigoTurma/ObterComponentesCurricularesPorUsuarioECodigoTurmaQueryHandler.cs
[AB#77405](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77405)
=> fix/77405 -> master

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommandHandler.cs
[AB#76101](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76101)
=> fix/76101 -> master

src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/AlterarAnotacaoFrequenciaAlunoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/ExcluirAnotacaoFrequenciaAlunoUseCase.cs
ao deletar ocorre erro mas o registro é deletado
[AB#77211](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77211)
=> ao deletar ocorre erro mas o registro é deletado

src/SME.SGP.Dominio.Servicos/ServicoUsuario.cs, src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#77329](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77329)
=> Ajuste da permissão de relatórios sondagem

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RegistrarEncaminhamentoAEEUseCase.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_cadastrar_encaminhamento_nao_nao_sei.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_cadastrar_encaminhamento_sim.cs
[AB#77411](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77411)
=> Correção do bug 77411

src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/AlterarAnotacaoFrequenciaAlunoUseCase.cs
[AB#7200](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/7200)
=> Correção validação Teste de integração

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#77194](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77194)
=> fix/77194 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConsolidacaoTurmaFechamento/ExecutarConsolidacaoTurmaFechamentoUseCase.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/GerarPendenciasFechamento/GerarPendenciasFechamentoCommandHandler.cs
[AB#77552](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77552)
=> fix/77552 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#77194](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77194)
=> fix/77194 -> master

src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/ObterListaSemestresUseCase.cs
[AB#77534](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77534)
=> fix/77534 -> master

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConsolidacaoTurmaFechamento/ExecutarConsolidacaoTurmaFechamentoUseCase.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/GerarPendenciasFechamento/GerarPendenciasFechamentoCommandHandler.cs
[AB#77552](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77552)
=> fix/77552 -> master

src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/AlterarAnotacaoFrequenciaAlunoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/ExcluirAnotacaoFrequenciaAlunoUseCase.cs
Correção do bug [AB#77200](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77200)
=> Erros na modal de justificativa (HOM2, HOM e ambiente de automação)

src/SME.SGP.Aplicacao/Comandos/ComandosAtividadeAvaliativa.cs
[AB#77599](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77599)
=> 77599 - Cadastro de avalição "Interdisciplinar" está permitindo cadastrar com apenas um componente

src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs
[AB#77615](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77615)
=> fix/77615 -> master

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoTurma/SalvarAcompanhamentoTurmaUseCase.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemAcompanhamentoTurma.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/Ao_salvar_percurso_coletivo_imagens.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/Base/RelatorioAcompanhamentoAprendizagemTesteBase.cs
Percurso coletivo não deve permitir + imagens
[AB#74030](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74030)
=> Feature/74030 - Percurso coletivo não deve permitir + imagens

src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/RemoverResponsavelPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/RemoverResponsavelPlanoAEE/RemoverResponsavelPlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/RemoverResponsavelPlanoAEE/RemoverResponsavelPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IRemoverResponsavelPlanoAEEUseCase.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs, src/SME.SGP.Dominio/Enumerados/SituacaoPlanoAEE.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#64614](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64614)
[AB#77111](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77111)
=> BACK 64614 --> RELEASE_POS

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/Ao_registrar_percurso_individual.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/Base/RelatorioAcompanhamentoAprendizagemTesteBase.cs
[AB#74032](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74032)
=> Percurso individual

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Dominio/Entidades/Turma.cs
[AB#77846](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77846)
=> Correção do bug 77846

src/SME.SGP.Dados/Repositorios/RepositorioRegistroIndividual.cs
[AB#77964](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77964)
=> fix/77964 ->r2

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterInformacoesDeFrequenciaAlunoPorSemestreUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioOcorrencia.cs, src/SME.SGP.Dominio/Entidades/Ocorrencia.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/Ao_Validar_informacoes_Ocorrencias_frequencia.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/Ao_salvar_percurso_coletivo_imagens.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/Base/RelatorioAcompanhamentoAprendizagemTesteBase.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/ServicosFake/ObterAcompanhamentoPorAlunoTurmaESemestreAcompanhamentoQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/ServicosFake/ObterAlunoPorCodigoEAnoRelAcompanhamentoQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/ServicosFake/ObterFrequenciaBimestresQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/ServicosFake/ObterPeriodosFechamentoTurmaInfantilCalendarioIdBimestreQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/ServicosFake/ObterTipoCalendarioIdPorTurmaQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/SME.SGP.TesteIntegracao.csproj
Feature/74031 - Validar informações
[AB#74031](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74031)
=> Feature/74031 - Validar informações

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RegistrarEncaminhamentoAEEUseCase.cs
[AB#77826](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77826)
=> Correção do bug 77826

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/AtribuirResponsavelPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/AtribuirResponsavelPlanoAEE/AtribuirResponsavelPlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/AtribuirResponsavelPlanoAEE/AtribuirResponsavelPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/AtribuirResponsavelPlanoAEE/AtribuirResponsavelPlanoAEECommandValidator.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarParecerCP/CadastrarParecerCPCommandHandler.cs
[AB#78172](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78172)
=> Correção da atualização do plano

src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
[AB#78044](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78044)
=> Fix/78044 -> r2

src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
[AB#78044](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78044)
=> fix/78044 -> r2 (pt.2)

src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#78059](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78059)
=> Fix/78059 ->r2

src/SME.SGP.Aplicacao/CasosDeUso/PendenciaDiarioBordo/TratarPendenciaDiarioBordoPorTurmaAulaComponenteUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#77204](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77204)
=> Correção do bug 77204

src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#78059](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78059)
=> Fix/78059 -> master

scripts/V571__ADICIONAR_UE_ID_NA_TABELA_OCORRENCIA.sql, src/SME.SGP.Dados/Mapeamentos/OcorrenciaMap.cs, src/SME.SGP.Dominio/Entidades/Ocorrencia.cs
[AB#78005](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78005)
=> 788005 - Alterações BD - Tabela ocorrencias

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
=> Bug: 73644

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorTurmasCodigo/ObterComponentesCurricularesPorTurmasCodigoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
[AB#78044](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78044)
=> Fix/78044 -> master

scripts/V574__INCLUSAO_TIPO_OCORRENCIA.sql
[AB#78008](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78008)
=> 78008 - Novos tipos de ocorrência

src/SME.SGP.Aplicacao/CasosDeUso/Ocorrencia/AlterarOcorrenciaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Ocorrencia/InserirOcorrenciaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Ocorrencia/AlterarOcorrencia/AlterarOcorrenciaCommand.cs, src/SME.SGP.Aplicacao/Commands/Ocorrencia/AlterarOcorrencia/AlterarOcorrenciaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Ocorrencia/ExcluirOcorrencia/ExcluirOcorrenciaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Ocorrencia/InserirOcorrencia/InserirOcorrenciaCommand.cs, src/SME.SGP.Aplicacao/Commands/Ocorrencia/InserirOcorrencia/InserirOcorrenciaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/OcorrenciaServidor/ExcluirOcorrenciaServidor/ExcluirOcorrenciaServidorPorIdOcorrencia/ExcluirOcorrenciaServidorPorIdOcorrenciaCommand.cs, src/SME.SGP.Aplicacao/Commands/OcorrenciaServidor/ExcluirOcorrenciaServidor/ExcluirOcorrenciaServidorPorIdOcorrencia/ExcluirOcorrenciaServidorPorIdOcorrenciaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Ocorrencia/OcorrenciaServidor/ObterOcorrenciasServidorPorIdOcorrencia/ObterOcorrenciasServidorPorIdOcorrenciaQuery.cs, src/SME.SGP.Aplicacao/Queries/Ocorrencia/OcorrenciaServidor/ObterOcorrenciasServidorPorIdOcorrencia/ObterOcorrenciasServidorPorIdOcorrenciaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioOcorrencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioOcorrenciaServidor.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioOcorrenciaServidor.cs, src/SME.SGP.Dominio/Entidades/Ocorrencia.cs, src/SME.SGP.Dominio/Entidades/OcorrenciaServidor.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Alteracoes/AlterarOcorrenciaDto.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Persistencias/InserirOcorrenciaDto.cs
Endpoints de Cadastrar/Alterar/Excluir
[AB#78012](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78012)
[AB#78026](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78026)
[AB#78027](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78027)
=> Endpoints de Cadastrar/Alterar/Excluir

src/SME.SGP.Api/Controllers/FuncionarioController.cs, src/SME.SGP.Aplicacao/Queries/EOL/Funcionario/ObterFuncionariosPorUe/ObterFuncionariosPorUeQuery.cs, src/SME.SGP.Aplicacao/Queries/EOL/Funcionario/ObterFuncionariosPorUe/ObterFuncionariosPorUeQueryHandler.cs
[AB#78446](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78446)
=> 78446 - Endpoint retorno dos servidores

scripts manutencao/Bug 76094 - Exclusão Lógica consolidado_conselho_classe_aluno_turma/ScriptExclusaoLogicaConsolidadoConselhoTurmas2022.sql, src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterConselhoClasseConsolidadoPorTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterFechamentoConselhoClasseAlunosPorTurmaUseCase.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseAcompanhamento/ObterAlunoEStatusConselhoClasseConsolidadoPorTurmaEBimestre/ObterAlunoEStatusConselhoClasseConsolidadoPorTurmaEBimestreQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseAcompanhamento/ObterAlunoEStatusConselhoClasseConsolidadoPorTurmaEBimestre/ObterAlunoEStatusConselhoClasseConsolidadoPorTurmaEBimestreQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseAcompanhamento/ObterConselhoClasseConsolidadoPorTurmaBimestre/ObterConselhoClasseConsolidadoPorTurmaBimestreQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidado.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseConsolidado.cs, src/SME.SGP.Infra/Dtos/ConsolidacaoConselhoClasseAluno/AlunoSituacaoConselhoDto.cs
[AB#76094](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76094)
=> Fix/76094 -> r2

src/SME.SGP.Aplicacao/Commands/Aulas/ValidarComponentesDoProfessor/ValidarComponentesDoProfessorCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesDoProfessorNaTurma/ObterComponentesCurricularesDoProfessorNaTurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesDoProfessorNaTurma/ObterComponentesCurricularesDoProfessorNaTurmaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesQuePodeVisualizar/ObterComponentesCurricularesQuePodeVisualizarHojeQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/EOL/ComponentesCurriculares/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfilQuery.cs, src/SME.SGP.Aplicacao/Queries/EOL/ComponentesCurriculares/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfilQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfilQuery.cs, src/SME.SGP.Aplicacao/Queries/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfilQueryHandler.cs
[AB#75359](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75359)
=> Fix/75359 -> master

src/SME.SGP.Api/Controllers/FuncionarioController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Ocorrencia/ListarOcorrenciasUseCase.cs, src/SME.SGP.Aplicacao/Commands/Ocorrencia/ExcluirOcorrencia/ExcluirOcorrenciaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Ocorrencia/ListarOcorrencias/ListarOcorrenciasQuery.cs, src/SME.SGP.Aplicacao/Queries/Ocorrencia/ListarOcorrencias/ListarOcorrenciasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Ocorrencia/ObterOcorrenciaPorId/ObterOcorrenciaPorIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Ocorrencia/OcorrenciaServidor/ObterOcorrenciasServidorPorIdOcorrencia/ObterOcorrenciasServidorPorIdOcorrenciaQuery.cs, src/SME.SGP.Aplicacao/Queries/Ocorrencia/OcorrenciaServidor/ObterOcorrenciasServidorPorIdOcorrencia/ObterOcorrenciasServidorPorIdOcorrenciaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioOcorrencia.cs, src/SME.SGP.Dados/Utils/GeradorDeCondicoes.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioOcorrencia.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Detalhes/OcorrenciaDto.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Detalhes/OcorrenciaServidorDto.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Listagens/FiltroOcorrenciaListagemDto.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Listagens/OcorrenciaListagemDto.cs
[AB#78011](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78011)
=> 78011 - Endpoint de listagem e retorno/edição por id

src/SME.SGP.Aplicacao/Commands/Ocorrencia/InserirOcorrencia/InserirOcorrenciaCommand.cs, src/SME.SGP.Aplicacao/Commands/Ocorrencia/InserirOcorrencia/InserirOcorrenciaCommandHandler.cs, src/SME.SGP.Dados/Mapeamentos/OcorrenciaServidorMap.cs, src/SME.SGP.Dominio/Entidades/Ocorrencia.cs, src/SME.SGP.Dominio/Entidades/OcorrenciaAluno.cs, src/SME.SGP.Dominio/Entidades/OcorrenciaServidor.cs, teste/SME.SGP.TesteIntegracao/Ocorrencia/Ao_Incluir_ocorrencia_com_turma.cs, teste/SME.SGP.TesteIntegracao/Ocorrencia/Base/OcorrenciaTesteBase.cs
[AB#78020](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78020)
=> 78020 -  Teste Inclusão de Ocorrencia com turma

scripts manutencao/Bug 76094 - Exclusão Lógica consolidado_conselho_classe_aluno_turma/ScriptExclusaoLogicaConsolidadoConselhoTurmas2022.sql, src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterConselhoClasseConsolidadoPorTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterFechamentoConselhoClasseAlunosPorTurmaUseCase.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseAcompanhamento/ObterAlunoEStatusConselhoClasseConsolidadoPorTurmaEBimestre/ObterAlunoEStatusConselhoClasseConsolidadoPorTurmaEBimestreQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseAcompanhamento/ObterAlunoEStatusConselhoClasseConsolidadoPorTurmaEBimestre/ObterAlunoEStatusConselhoClasseConsolidadoPorTurmaEBimestreQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseAcompanhamento/ObterConselhoClasseConsolidadoPorTurmaBimestre/ObterConselhoClasseConsolidadoPorTurmaBimestreQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidado.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseConsolidado.cs, src/SME.SGP.Infra/Dtos/ConsolidacaoConselhoClasseAluno/AlunoSituacaoConselhoDto.cs
[AB#76094](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76094)
=> Fix/76094 -> master

src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ImpressaoPlanoAeeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IImpressaoPlanoAeeUseCase.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioPlanoAeeDto.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpRelatorios.cs
[AB#77514](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77514)
=> Endpoint de impressão SGP

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterQuantidadeAulasNaSemanaPorProfessorComponenteCurricular/ObterQuantidadeAulasNaSemanaPorProfessorComponenteCurricularQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQuery.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Grade/ObterGradeAulasPorTurmaEProfessor/ObterGradeAulasPorTurmaEProfessorQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAulaConsulta.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
[AB#78188](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78188)
=> Fix/78188 -> r2

src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs, teste/SME.SGP.TesteIntegracao/Ocorrencia/Ao_Incluir_ocorrencia_com_turma.cs, teste/SME.SGP.TesteIntegracao/Ocorrencia/Ao_Incluir_ocorrencia_sem_turma.cs, teste/SME.SGP.TesteIntegracao/Ocorrencia/Base/OcorrenciaTesteBase.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/Ao_Validar_informacoes_Ocorrencias_frequencia.cs
[AB#78031](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78031)
=> 78031 - Testes Automatizados para Inclusão de Ocorrencia - sem turma

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ImpressaoPlanoAeeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IImpressaoPlanoAeeUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEAlunoTurmaDto.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEResumoDto.cs
[AB#77515](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77515)
=> Colocar o id da versão do plano no endpoint listagem

teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
[AB#78188](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78188)
=> 78188 Ajuste de testes

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommandHandler.cs
[AB#78570](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78570)
=> Fix/78570 -> r2

src/SME.SGP.Aplicacao/Commands/Ocorrencia/AlterarOcorrencia/AlterarOcorrenciaCommand.cs, src/SME.SGP.Aplicacao/Commands/Ocorrencia/InserirOcorrencia/InserirOcorrenciaCommand.cs, src/SME.SGP.Aplicacao/Queries/Ocorrencia/ObterOcorrenciaPorId/ObterOcorrenciaPorIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioOcorrencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioOcorrenciaServidor.cs, src/SME.SGP.Dominio/Entidades/Ocorrencia.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Alteracoes/AlterarOcorrenciaDto.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Detalhes/OcorrenciaDto.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Persistencias/InserirOcorrenciaDto.cs, teste/SME.SGP.TesteIntegracao/Ocorrencia/Ao_alterar_ocorrencia.cs, teste/SME.SGP.TesteIntegracao/Ocorrencia/Base/OcorrenciaTesteBase.cs, teste/SME.SGP.TesteIntegracao/Ocorrencia/ServicosFakes/ObterAlunosEolPorCodigosQueryFake.cs, teste/SME.SGP.TesteIntegracao/Ocorrencia/ServicosFakes/ObterFuncionariosPorUeQueryFake.cs
Testes Automatizados para Alteração de Ocorrência
[AB#78634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78634)
=> Feature/78634 - Testes Automatizados para Alteração de Ocorrência

src/SME.SGP.Dados/Repositorios/RepositorioRegistroIndividual.cs
[AB#77964](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77964)
=> fix/77964 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Boletim/BoletimUseCase.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioBoletim.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioBoletimDto.cs
Endpoint Boletim (SGP)
[AB#77249](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77249)
=> Feature/77249 - Endpoint Boletim (SGP)

teste/SME.SGP.TesteIntegracao/Frequencia/Ao_calcular_frequencia.cs, teste/SME.SGP.TesteIntegracao/TesteBase.cs
Ajuste nos testes de integração relacionados a cálculo de frequência.
=> Bug: 77882

src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs
[AB#78741](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78741)
=> fix/78741 -> r2

src/SME.SGP.Aplicacao/Queries/Ocorrencia/ObterOcorrenciaPorId/ObterOcorrenciaPorIdQueryHandler.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Detalhes/OcorrenciaDto.cs
[AB#78749](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78749)
=> Alterar endpoint obter ocorrência por id

src/SME.SGP.Aplicacao/CasosDeUso/Bimestres/ObterBimestreAtualPorTurmaIdUseCase.cs
[AB#78706](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78706)
=> fix/78706 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs, src/SME.SGP.Aplicacao/Queries/AulasPrevistas/ObterAulasPrevistasPorCodigoUe/ObterAulasPrevistasPorCodigoUeQuery.cs, src/SME.SGP.Aplicacao/Queries/AulasPrevistas/ObterAulasPrevistasPorCodigoUe/ObterAulasPrevistasPorCodigoUeQueryHandler.cs
=> fix/78739 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioRegistroIndividual.cs
[AB#77964](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77964)
=> Fix/77964 -> master

scripts/V575__ADICIONAR_COLUNAS_AUDITORIA_TABELA_WF_APROVACAO_NOTA_CONSELHO.sql
[AB#62125](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62125)
=> 62125 - Modelagem tabela de wf_aprovacao_nota_conselho

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarAprovacaoDeNotaConselhoUseCase.cs, src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/AprovacaoNotaConselhoClasse/AprovacaoNotaConselhoClasseCommand.cs, src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/AprovacaoNotaConselhoClasse/AprovacaoNotaConselhoClasseCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Fechamento/INotificarAprovacaoDeNotaConselhoUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioPorIdsSemPerfil/ObterUsuarioPorIdsSemPerfilQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioPorIdsSemPerfil/ObterUsuarioPorIdsSemPerfilQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioUsuario.cs, src/SME.SGP.Dados/Repositorios/RepositorioWFAprovacaoNotaConselho.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioUsuario.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioWFAprovacaoNotaConselho.cs, src/SME.SGP.Fechamento.Worker/WorkerRabbitFechamento.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpFechamento.cs
[AB#62111](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62111)
=> 62111 - Worker de aprovação de conselho classe

src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/AprovacaoNotaConselhoClasse/AprovacaoNotaConselhoClasseCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/AprovacaoNotaConselhoCommandBase.cs, src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/AprovarWorkflowAlteracaoNotaConselho/AprovarWorkflowAlteracaoNotaConselhoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/NotificarAprovacaoNotaConselho/NotificarAprovacaoNotasConselhoCommand.cs, src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/NotificarAprovacaoNotaConselho/NotificarAprovacaoNotasConselhoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/RecusarAprovacaoNotaConselho/RecusarAprovacaoNotaConselhoCommand.cs, src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/RecusarAprovacaoNotaConselho/RecusarAprovacaoNotaConselhoCommandHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
[AB#78885](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78885)
=> 78885 - Alterações mensagem e notificações recusa

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/Ao_registrar_percurso_individual.cs, teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/ServicosFake/ObterAlunoPorCodigoEolQueryHandlerAlunoAtivoFake.cs
=> Ajustes nos Teste de Integração

src/SME.SGP.Api/Controllers/FuncionarioController.cs
[AB#78921](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78921)
=> Bug/78921 - Não carrega a lista do campo de Servidores 

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommandHandler.cs
[AB#78570](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78570)
=> fix/78570 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs, src/SME.SGP.Aplicacao/Queries/AulasPrevistas/ObterAulasPrevistasPorCodigoUe/ObterAulasPrevistasPorCodigoUeQuery.cs, src/SME.SGP.Aplicacao/Queries/AulasPrevistas/ObterAulasPrevistasPorCodigoUe/ObterAulasPrevistasPorCodigoUeQueryHandler.cs
[AB#78739](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78739)
=> fix/78739 -> master

src/SME.SGP.Dados/Repositorios/RepositorioOcorrencia.cs
[AB#78967](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78967)
=> Bug/78967 - Filtro de ano anterior resulta em resultados do ano atual.

src/SME.SGP.Dados/Repositorios/RepositorioOcorrencia.cs
[AB#78932](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78932)
[AB#78963](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78963)
=> 78932, 78963 - Aluno sem turma não apresentando e paginação incorreta

src/SME.SGP.Aplicacao/CasosDeUso/Bimestres/ObterBimestreAtualPorTurmaIdUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterPeriodoEscolarPorTurmaUseCase.cs
[AB#78706](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78706)
=> fix/78706 -> release-r2

src/SME.SGP.Dados/Repositorios/RepositorioOcorrencia.cs
[AB#78932](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78932)
=> 78932 - Ajuste na query de ocorrência

src/SME.SGP.Infra/Dtos/Turma/TurmaNaoHistoricaDto.cs
[AB#79102](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79102)
=> 79102 - AnoTurma com tipo modificado de int para string em DTO

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs
[AB#79031](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79031)
=> fix/79031 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#79025](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79025)
=> Fix/79025 -> master

src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEConsulta.cs
[AB#78961](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78961)
=> Correção para permitir a visualização de todos os planos da UE quando o usuário estiver acessando como PAEE

src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoConsulta.cs
[AB#77853](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77853)
=> fix/77853 -> r2

src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Queries/AtribuicaoCJ/ObterAtribuicoesCJAtivas/ObterAtribuicoesCJAtivasQuery.cs, src/SME.SGP.Aplicacao/Queries/AtribuicaoCJ/ObterAtribuicoesCJAtivas/ObterAtribuicoesCJAtivasQueryHandler.cs
[AB#78572](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78572)
=> Fix/78572 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs
[AB#79031](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79031)
=> fix/79031 -> master

src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEConsulta.cs
[AB#78961](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78961)
=> Correção para permitir a visualização de todos os planos da UE quando o usuário estiver acessando como PAEE.

src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoConsulta.cs
[AB#77853](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77853)
=> 77853 incluindo filtro na query

src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoConsulta.cs
[AB#77853](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77853)
=> Fix/77853 -> master

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaAlunosComAusencia/ObterListaAlunosComAusenciaQueryHandler.cs
[AB#78660](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78660)
=> fix/78660 -> r2

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaAlunosComAusencia/ObterListaAlunosComAusenciaQueryHandler.cs
[AB#78660](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78660)
=> fix/78660 -> master (revert)

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs
[AB#79032](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79032)
=> fix/79032 -> master

scripts/V579__CARGA_QUESTIONARIO_ENCAMINHAMENTO_NAAPA_ETAPA_1.sql
[AB#78826](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78826)
=> 78831 - Publicação de questões Seção 1 NAAPA

teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_gerar_parecer_conclusivo.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_validar_situacao_do_parecer_conclusivo.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs
[AB#78608](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78608)
=> 78608 - Ajustes nos testes de integração

src/SME.SGP.Aplicacao/CasosDeUso/Aluno/ObterAlunoPorCodigoEolEAnoLetivoUseCase.cs
[AB#78851](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78851)
=> 78851 - Campo Turno em Turma Formatada Object Card

scripts/V578__ADICIONAR_CONSELHO_DE_CLASSE_PARECER_ANO.sql
[AB#78606](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78606)
=> 78606 - Adicionar novos conselho de classe parecer ano

teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_validar_situacao_do_parecer_conclusivo.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs
[AB#78608](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78608)
=> 78608 - Ajustando teste de parecer conclusivo para novas regras de ano

src/SME.SGP.Api/Controllers/EstudanteController.cs, src/SME.SGP.Dominio/Enumerados/GrauParentesco.cs
[AB#78860](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78860)
=> 78860 - End point graus de parentesco no estudante

scripts/V580__ADICIONAR_ARQUIVOID_TABELA_ITINERANCIA_ALUNO_QUESTAO.sql, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciasUseCase.cs, src/SME.SGP.Dados/Mapeamentos/ItineranciaAlunoQuestaoMap.cs, src/SME.SGP.Dados/Mapeamentos/ItineranciaQuestaoMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioItinerancia.cs, src/SME.SGP.Dominio/Entidades/ItineranciaAlunoQuestao.cs, src/SME.SGP.Dominio/Entidades/ItineranciaQuestao.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaResumoDto.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaRetornoQueryDto.cs
[AB#66339](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66339) - Inclusão do Tipo da Questão
=> Feature/66339 - Inclusão do Tipo da Questão

src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ObterPrioridadeEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IObterPrioridadeEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterPrioridadeEncaminhamentoNAAPA/ObterPrioridadeEncaminhamentoNAAPAQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterPrioridadeEncaminhamentoNAAPA/ObterPrioridadeEncaminhamentoNAAPAQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioQuestaoEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioQuestaoEncaminhamentoNAAPA.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/PrioridadeEncaminhamentoNAAPADto.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#79511](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79511)
=> 79511 - Criar endpoint de retorno de situação e prioridade do naapa

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#78706](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78706)
=> Fix/78706 -> master

src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ObterEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IObterEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosAee/ObterEncaminhamentosNAAPAQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosAee/ObterEncaminhamentosNAAPAQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoNAAPA.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/EncaminhamentoNAAPAResumoDto.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/FiltroEncaminhamentoNAAPADto.cs, src/SME.SGP.Infra/Enumerados/Permissao.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#78862](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78862)
=> Endpoint de listar

scripts/V581__REMOVER_ALUNO_NUMERO_TABELA_ENCAMINHAMENTO_NAAPA.txt, src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs, src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterAbrangenciaTurmasPorUeModalidadePeriodoHistoricoAnoLetivoTipos/ObterAbrangenciaTurmaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosAee/ObterEncaminhamentosNAAPAQueryHandler.cs, src/SME.SGP.Dados/Mapeamentos/EncaminhamentoNAAPAMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio/Entidades/EncaminhamentoNAAPA.cs, src/SME.SGP.Dominio/Enumerados/TipoQuestionario.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/FiltroEncaminhamentoNAAPADto.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_listar_com_filtros.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/ServicosFake/ObterAbrangenciaTurmasPorUeModalidadePeriodoHistoricoAnoLetivoTiposQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/ServicosFake/ObterTurmasAlunoPorFiltroQueryHandlerFake.cs
[AB#78862](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78862)
=> Removendo campo aluno_numero e testes de integração de listar

src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs, src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#78842](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78842)
=> 78842 - Permissionamento encaminhamento NAAPA

src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#79383](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79383)
=> fix/79383 -> r2

src/SME.SGP.Api/Controllers/ItineranciaController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/AlterarItineranciaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciaPorIdUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciasUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/SalvarItineranciaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/Upload/UploadDeArquivoItineranciaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/UploadArquivo/UploadArquivoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/Salvar/SalvarItineranciaQuestao/SalvarItineranciaQuestaoCommand.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/Salvar/SalvarItineranciaQuestao/SalvarItineranciaQuestaoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/UploadArquivo/UploadArquivoItineranciaCommand.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/UploadArquivo/UploadArquivoItineranciaCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Itinerancia/Upload/IUploadDeArquivoItineranciaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Itinerancia/ObterTipoDaQuestaoItinerancia/ObterTipoDaQuestaoItineranciaQuery.cs, src/SME.SGP.Aplicacao/Queries/Itinerancia/ObterTipoDaQuestaoItinerancia/ObterTipoDaQuestaoItineranciaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioItinerancia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioItinerancia.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs, src/SME.SGP.Dominio/Entidades/Itinerancia.cs, src/SME.SGP.Dominio/Enumerados/TipoArquivo.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ArquivoArmazenadoItineranciaDto.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaDto.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaQuestaoDto.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaResumoDto.cs, src/SME.SGP.Infra/Dtos/Itinerancia/QuestaoTipoDto.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#66343](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66343)
[AB#78518](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78518)
=> Back - Salvar/Upload anexos

teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/Ao_editar_registrar_percurso_observacoes.cs
[AB#74034](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74034)
=> 74034 - Demais cenários

src/SME.SGP.Aplicacao/Commands/Itinerancia/Notificacao/NotificacaoSalvarItineranciaAlunos/NotificacaoSalvarItineranciaAlunosCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Itinerancia/ObterQuantidadeDeAnexosNaItinerancia/ObterQuantidadeDeAnexosNaItineranciaQuery.cs, src/SME.SGP.Aplicacao/Queries/Itinerancia/ObterQuantidadeDeAnexosNaItinerancia/ObterQuantidadeDeAnexosNaItineranciaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioItinerancia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioItinerancia.cs
[AB#66404](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66404)
=> Feature/66404 - Alterar texto da notificação

src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#79383](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79383)
=> fix/79383 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#79478](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79478)
=> fix/79478 -> master

src/SME.SGP.Api/Controllers/EstudanteController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Aluno/ObterInformacoesAlunoPorCodigoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/IObterInformacoesAlunoPorCodigoUseCase.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/ObterAlunoEnderecoEol/ObterAlunoEnderecoEolQuery.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/ObterAlunoEnderecoEol/ObterAlunoEnderecoEolQueryHandler.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioEOL.cs, src/SME.SGP.Infra/Dtos/AlunoEnderecoRespostaDto.cs, src/SME.SGP.Infra/Dtos/EnderecoRespostaDto.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#78837](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78837)
=> 78837 - End point informações aluno com endereço EOL

src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ExcluirArquivoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/ExcluirReferenciaArquivoEncaminhamentoNAAPA/ExcluirReferenciaArquivoNAAPAPorArquivoIdCommand.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/ExcluirReferenciaArquivoEncaminhamentoNAAPA/ExcluirReferenciaArquivoNAAPAPorArquivoIdCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IExcluirArquivoNAAPAUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioRespostaEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRespostaEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs, src/SME.SGP.Dominio/Enumerados/TipoArquivo.cs
[AB#79659](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79659)
=> 79659 - Upload e Exclusão de arquivos/anexo encaminhamento NAAPA

src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesQuePodeVisualizar/ObterComponentesCurricularesQuePodeVisualizarHojeQueryHandler.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCaseTeste.cs
[AB#79491](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79491)
=> Fix/79491 -> release-r2

teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_excluir_encaminhamento_naapa_rascunho.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs
=> 78858 - Testes de integração exclusão NAAPA

src/SME.SGP.Api/Controllers/MenuController.cs, src/SME.SGP.Aplicacao/Interfaces/Servicos/IServicoMenu.cs, src/SME.SGP.Aplicacao/Queries/AjudaDoSistema/ObterAjudasDoSistema/ObterAjudasDoSistemaQuery.cs, src/SME.SGP.Aplicacao/Queries/AjudaDoSistema/ObterAjudasDoSistema/ObterAjudasDoSistemaQueryHandler.cs, src/SME.SGP.Aplicacao/Servicos/ServicoMenu.cs, src/SME.SGP.Infra/Dtos/AjudaDoSistema/AjudaDoSistemaDto.cs, src/SME.SGP.Infra/Dtos/MenuPermissaoDto.cs
[AB#78616](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78616)
=> Alteração do endpoint de menus no SGP

src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosNAAPA/ObterEncaminhamentosNAAPAQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_listar_com_filtros.cs
[AB#79597](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79597)
=> Correção do filtro de encaminhamentos - agrupamento

src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs
[AB#79480](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79480)
=> fix/79480 -> r2

src/SME.SGP.Aplicacao/Workers/WorkerRabbitMQBase.cs, src/SME.SGP.Fechamento.Worker/WorkerRabbitFechamento.cs, src/SME.SGP.Frequencia.Worker/WorkerRabbitFrequencia.cs, src/SME.SGP.Infra.Mensageria/Exchange/ExchangeSgpRabbit.cs, src/SME.SGP.Infra/Fila/ComandoRabbit.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#79522](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79522)
=> 79522 - Alterar a declaração das filas com ttl

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs, src/SME.SGP.Aplicacao/Commands/Arquivos/MoverArquivosTemporarios/MoverArquivosTemporariosCommandHandler.cs, src/SME.SGP.Dominio/Constantes/ArmazenamentoObjetos.cs
[AB#79670](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79670)
=> fix/79670 -> r2

src/SME.SGP.IoC/RegistrarDependencias.cs, teste/SME.SGP.TesteIntegracao/Itinerancia/Ao_excluir_arquivo.cs, teste/SME.SGP.TesteIntegracao/Itinerancia/Ao_realizar_upload_do_arquivo.cs, teste/SME.SGP.TesteIntegracao/Itinerancia/Base/ItineranciaBase.cs, teste/SME.SGP.TesteIntegracao/Itinerancia/ServicosFake/ArmazenarArquivoFisicoCommandHandlerFake.cs, teste/SME.SGP.TesteIntegracao/Itinerancia/ServicosFake/ExcluirArquivoMinioCommandHandlerFakeTrue.cs
[AB#79821](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79821)
=> Registro de itinerância - Anexos Teste de Integração

scripts/V581__CRIACAO_CAMPO_NOME_COMPONENTE_QUESTAO.sql, scripts/V582__CARGA_CAMPO_NOME_COMPONENTE_QUESTAO.sql
[AB#78832](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/78832)
=> 79832 criação de nome do componente para as questões dinamicas

teste/SME.SGP.TesteIntegracao/Frequencia/Ao_calcular_frequencia.cs
=> Bug: 79358

scripts/V583__CRIACAO_QUESTAO_FLUXO_ALERTA_NAAPA.sql
[AB#79836](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79836)
=> 79836 criação da questão fluxo de alerta

src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEAno/ObterAlunoPorCodigoEAnoQueryHandler.cs, src/SME.SGP.Infra/Dtos/AlunoReduzidoDto.cs
[AB#79789](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79789)
=> Story/64234 --> DEV

src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs
[AB#79789](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79789)
=> Tratando o nome da prioridade

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Infra.Mensageria/RabbitModelPooledObjectPolicy.cs
[AB#79799](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79799)
=> Fix/79799 -> master

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs, src/SME.SGP.Aplicacao/Commands/Arquivos/MoverArquivosTemporarios/MoverArquivosTemporariosCommandHandler.cs, src/SME.SGP.Dominio/Constantes/ArmazenamentoObjetos.cs
[AB#79670](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79670)
=> Fix/79670 -> master

src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
[AB#79707](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79707)
=> fix/79707 -> master

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ObterEncaminhamentoNAAPAPorIdUseCase.cs
[AB#79904](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79904)
=> 79904 - Ajuste nome UE concatenando tipo escola

src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs
[AB#79480](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79480)
=> fix/79480 -> master

src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs
[AB#79926](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79926)
=> Correção da paginação do filtro NAAPA

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaQueryHandler.cs
[AB#76154](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76154)
=> Buscar modalidades do filtro de boletim por abrangência.

src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciaPorIdUseCase.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaQuestaoDto.cs
[AB#79961](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79961)
=> Remoção de campo arquivoCodigo

scripts/V578__ADICIONAR_CONSELHO_DE_CLASSE_PARECER_ANO.sql
[AB#80000](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80000)
=> 80000 - Ano 7 e ano 8 não ficam mais retidos em ano anterior

src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs
[AB#80175](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80175)
=> 80175 - Ordenação desc pela data queixa story 64234

src/SME.SGP.Infra/Dtos/EnderecoRespostaDto.cs
[AB#80149](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80149)
=> 80149 - Ajuste retorno endereço nas informações do aluno

src/SME.SGP.Aplicacao/CasosDeUso/Responsavel/ObterResponsaveisPorDreUseCase.cs
[AB#79811](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79811)
=> fix/79811 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#68880](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68880)
=> fix/68880 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/Responsavel/ObterResponsaveisPorDreUseCase.cs
[AB#79811](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79811)
=> fix/79811 -> master

src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoFinal.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/InserirOuAtualizarCacheFechamentoNotaConceito/InserirOuAtualizarCacheFechamentoNotaConceitoCommandHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
[AB#80508](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80508)
=> Correção do uso da cache ao salvar o fechamento de bimestre.

src/SME.SGP.Aplicacao/Commands/Itinerancia/Notificacao/NotificacaoSalvarItineranciaAlunos/NotificacaoSalvarItineranciaAlunosCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioItinerancia.cs
[AB#80493](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80493)
=> 80493 - Ajuste notificação criação de itinerancia com anexo

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#68880](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68880)
=> bug 68880 ajuste para obter quantidade de frequencia

src/SME.SGP.Aplicacao/Commands/DiarioBordo/InserirDiarioBordo/InserirDiarioBordoCommandHandler.cs
[AB#80168](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80168)
=> Fix/80168 -> master

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ObterEncaminhamentoNAAPAPorIdUseCase.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/EncaminhamentoNAAPARespostaDto.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_obter_encaminhamento.cs
[AB#80220](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80220)
=> Status do Encaminhamento NAAPA

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/PesquisaResponsavelEncaminhamentoPorDreUEUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/PesquisaResponsavelPlanoPorDreUEUseCase.cs
[AB#80627](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80627)
=> Aplicando suporte para não depender somente da turma para alimentação da UE e DRE

src/SME.SGP.Api/Controllers/RelatorioController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/PlanoAEE/RelatorioPlanosAeeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IRelatorioPlanosAEEUseCase.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs, src/SME.SGP.Infra/Dtos/Relatorios/PlanoAEE/FiltroRelatorioPlanoAEEDto.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpRelatorios.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#79746](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79746)
=> Criação do endpoint SGP

src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ObterSecoesPorEtapaDeEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IObterSecoesPorEtapaDeEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterSecoesPorEtapaDeEncaminhamento/ObterSecoesPorEtapaDeEncaminhamentoNAAPAQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterSecoesPorEtapaDeEncaminhamento/ObterSecoesPorEtapaDeEncaminhamentoNAAPAQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioSecaoEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSecaoEncaminhamentoNAAPA.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/FiltroSecoesPorEtapaDeEncaminhamento.cs
[AB#80648](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80648)
=> Mudança endpoint de busca de seções para possibilitar query param CodigoModalidade (da seção)

src/SME.SGP.Dominio.Servicos/ServicoUsuario.cs
[AB#80409](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80409)
=> Fix/80409 -> r2

src/SME.SGP.Aplicacao/Commands/Notificacoes/NotificarCriacaoNotificacao/NotificarCriacaoNotificacaoCommandHandler.cs
[AB#80636](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80636)
=> Correção da data da notificação

src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterEncaminhamentosAee/ObterEncaminhamentosAEEQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs
[AB#79710](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79710)
=> Obter dados dos encaminhamentos históricos

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/EncaminhamentoNAAPADto.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/EncaminhamentoNAAPASecaoDto.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_cadastrar_editar_encaminhamento_naapa_rascunho.cs
[AB#80193](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80193)
=> Preenchimento do campo "Concluído" da seção

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaFechamentoComponenteUseCase.cs
[AB#80844](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80844)
=> Tratamento para turmas sem professores titulares na consolidação.

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
[AB#80839](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80839)
=> fix/80839 - correção para não houver duplicidade de fechamentos a serem consolidados

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#80837](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80837)
=> BUG 80837 formatando parametro de data para a consulta

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
[AB#80839](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80839)
=> Fix/80839 -> master

src/SME.SGP.Dominio.Servicos/ServicoUsuario.cs
[AB#80409](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80409)
=> Fix/80409 -> master

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ObterSecoesPorEtapaDeEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterSecoesPorEtapaDeEncaminhamento/ObterSecoesPorEtapaDeEncaminhamentoNAAPAQueryHandler.cs
[AB#80886](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80886)
=> Preenchimento campo "Concluído" no GET da seções quando for um novo encaminhamento

scripts/V589__ADICIONAR_CONSELHO_DE_CLASSE_PARECER_ANO_EJA.sql
[AB#80862](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80862)
=> 80862  - Não foram encontrados pareceres conclusivos para a turma eja

src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
testes ok [AB#80839](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80839)
=> fix/80839 - ajuste para verificar duplicidade ao salvar fechamento no listão

src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/ObterListaSemestresUseCase.cs
[AB#80941](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80941)
=> Verificar reabertura para habilitar relatório PAP.

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#80837](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80837)
=> Fix/80837 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
[AB#80892](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80892)
=> fix/80892 -> r2

src/SME.SGP.Aplicacao/Queries/Aula/PodeCadastrarAulaNoDia/PodeCadastrarAulaNoDiaQueryHandler.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_registrar_aula_verifica_se_pode_cadastrar_aula.cs
[AB#79660](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79660)
=> Fix/79660 -> master

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs
[AB#80843](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80843)
=> fix/80843 -> r2

src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs
[AB#81081](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81081)
=> Correção da geração do parecer conclusivo

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs
[AB#80843](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80843)
=> fix/80843 -> master

src/SME.SGP.Aplicacao/Commands/ConselhoClasse/AlterarConselhoClasse/AlterarConselhoClasseCommadHandler.cs
[AB#80839](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80839)
=> Removido Consolidação de Conselho de Classe por turma

src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
[AB#80839](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80839)
=> Ajuste Query para permitir reprocessar Conselho do Ano Atual

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#81135](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81135)
=> fix/81135 -> release-r2

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#81134](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81134)
=> Correção para obter os componentes das turmas de itinerário e regular na tela de conselho

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/ObterListaSemestresUseCase.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#81084](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81084)
=> Identificar desistentes transferidos de UE e com matrículas ativas para o encerramento aut. plano AEE.

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterDetalhamentoFechamentoConselhoClasseAlunoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasse/InserirTurmasComplementares/InserirTurmasComplementaresCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasseAluno/SalvarConselhoClasseAluno/SalvarConselhoClasseAlunoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoConselhoClasse/ConsolidarTurmaConselhoClasseAluno/ConsolidarTurmaConselhoClasseAlunoCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurma/ObterFechamentoTurmaPorIdAlunoCodigo/ObterFechamentoTurmaPorIdAlunoCodigoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAluno/ObterConsultaFrequenciaGeralAlunoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs, src/SME.SGP.Dados.ElasticSearch/RepositorioElasticBase.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioFechamentoTurma.cs, teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasConselhoClasseTeste.cs
[AB#81137](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81137)
=> Conselho de classe - Já existe um conselho de classe gerado

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
[AB#80892](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80892)
=> Fix/80892 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
[AB#81231](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81231)
=> Fix/81231 -> r2

src/SME.SGP.Infra/Dtos/Relatorios/PlanoAEE/FiltroRelatorioPlanoAEEDto.cs
[AB#81404](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81404)
=> Ajuste dos filtros e geração do relatório

src/SME.SGP.Aplicacao/Commands/ConselhoClasse/AlterarConselhoClasse/AlterarConselhoClasseCommadHandler.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasse/GravarConselhoClasse/GravarConselhoClasseCommadHandler.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasConceitosFechamentoPorTurmasCodigosEBimestre/ObterNotasConceitosFechamentoPorTurmasCodigosEBimestreQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasConceitosFechamentoPorTurmasCodigosEBimestre/ObterNotasConceitosFechamentoPorTurmasCodigosEBimestreQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasFinaisBimestresAluno/ObterNotasFinaisBimestresAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNotaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseNotaConsulta.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs, src/SME.SGP.Dominio/Constantes/NomeChaveCache.cs
[AB#81221](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81221)
=> Revert commit Bug: 81221

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/VerificaSePodeEditarNota/VerificaSePodeEditarNotaQueryHandler.cs
[AB#81083](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81083)
=> fix/81083 -> r2

src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosNAAPA/ObterEncaminhamentosNAAPAQueryHandler.cs
[AB#81522](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81522)
=> 81522 - Ajuste nome da situação NAAPA para listagem front

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoConselhoClasse/ConsolidarTurmaConselhoClasseAluno/ConsolidarTurmaConselhoClasseAlunoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesComNotaDeFechamentoOuConselhoPorAluno/ObterComponentesComNotaDeFechamentoOuConselhoQuery.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesComNotaDeFechamentoOuConselhoPorAluno/ObterComponentesComNotaDeFechamentoOuConselhoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioComponenteCurricularConsulta.cs
[AB#81494](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81494)
=> Correção para verificar componentes com nota de fechamento ou conselho a partir das suas turmas.

scripts/V590__AJUSTES_CONSELHO_DE_CLASSE_PARECER_ANO_2022.sql
[AB#80876](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80876)
=> Produção Story/80876

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
[AB#80912](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80912)
=> fix/80912 -> r2

src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoFinal.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasse/AlterarConselhoClasse/AlterarConselhoClasseCommadHandler.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasse/GravarConselhoClasse/GravarConselhoClasseCommadHandler.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterConselhoClasseAlunosNotaPorFechamentoId/ObterConselhoClasseAlunosNotaPorFechamentoIdQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterConselhoClasseAlunosNotaPorFechamentoId/ObterConselhoClasseAlunosNotaPorFechamentoIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasConceitosFechamentoPorTurmasCodigosEBimestre/ObterNotasConceitosFechamentoPorTurmasCodigosEBimestreQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasse.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasse.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs, src/SME.SGP.Dominio/Constantes/NomeChaveCache.cs, src/SME.SGP.Infra/Dtos/ConselhoClasse/ConselhoClasseAlunosNotaPorFechamentoIdDto.cs
[AB#81211](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81211)
=> Fix/81211 v2 -> master

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoConselhoClasse/ConsolidarTurmaConselhoClasseAluno/ConsolidarTurmaConselhoClasseAlunoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesComNotaDeFechamentoOuConselhoPorAluno/ObterComponentesComNotaDeFechamentoOuConselhoQuery.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesComNotaDeFechamentoOuConselhoPorAluno/ObterComponentesComNotaDeFechamentoOuConselhoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioComponenteCurricularConsulta.cs
[AB#81494](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81494)
=> Fix/81494 -> master

src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterUltimoBimestreAlunoTurma/ObterUltimoBimestreAlunoTurmaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseConsulta.cs
[AB#81231](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81231)
=> fix/81231 -> master

src/SME.SGP.Aplicacao/Comandos/ComandosNotasConceitos.cs, src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/AtividadeAvaliativaPorTurma/AtualizaCacheDeAtividadeAvaliativaPorTurmaCommand.cs, src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/AtividadeAvaliativaPorTurma/AtualizaCacheDeAtividadeAvaliativaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/AtividadeAvaliativaPorTurma/CriarCacheDeAtividadeAvaliativaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/NotaConceito/SalvarListaNotaConceito/SalvarListaNotaConceitoCommand.cs, src/SME.SGP.Dados.Cache/RepositorioCache.cs, src/SME.SGP.Dados.Cache/SME.SGP.Dados.Cache.csproj, src/SME.SGP.Dados/Repositorios/RepositorioNotasConceitos.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotasConceitos.cs, src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs
[AB#80911](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80911)
=> Fix/80911 -> master

src/SME.SGP.Aplicacao/Comandos/ComandosConselhoClasseAluno.cs
[AB#81236](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81236)
=> fix/81236 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
[AB#81211](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81211)
=> Correção do cache para regência --> master

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
[AB#80912](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80912)
=> Fix/80912 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/VerificaSePodeEditarNota/VerificaSePodeEditarNotaQueryHandler.cs
[AB#81083](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81083)
=> fix/81083 -> master

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
[AB#81549](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81549)
=> Fix/81549 -> master (validação nas exceções encontradas na fila de frequencia deadletter)

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
[AB#81549](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81549)
=> Fix/81549 -> master

src/SME.SGP.Aplicacao/Commands/ConselhoClasse/AtualizaSituacaoConselhoClasse/AtualizaSituacaoConselhoClasseCommand.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasse/AtualizaSituacaoConselhoClasse/AtualizaSituacaoConselhoClasseCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasse/GravarConselhoClasse/GravarConselhoClasseCommadHandler.cs
[AB#81234](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81234)
=> fix/81234 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoComponentePorTurmas/ObterFrequenciasAlunoComponentePorTurmasQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoComponentePorTurmas/ObterFrequenciasAlunoComponentePorTurmasQueryHandler.cs
[AB#81587](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81587)
=> fix/81587 -> master

src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#81162](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81162)
=> fix/81162 -> master

src/SME.SGP.Aplicacao/Commands/ConsolidacaoConselhoClasse/ConsolidarTurmaConselhoClasseAluno/ConsolidarTurmaConselhoClasseAlunoCommandHandler.cs
[AB#81694](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81694)
=> Fix/81694 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotaConselhoEmAprovacao/ObterNotaConselhoEmAprovacaoQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotaConselhoEmAprovacao/ObterNotaConselhoEmAprovacaoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNotaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseNotaConsulta.cs
[AB#81668](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81668)
=> 81668 - Não apresenta notificação para nota "Zero"

scripts/V591__EXCLUSAO_LOGICA_PENDENCIAS_FECHAMENTO_ANO_2022.sql, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaFechamento.cs
[AB#79976](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79976)
=> Fix/79976 -> master

src/SME.SGP.Dados/Repositorios/RepositorioOcorrencia.cs
[AB#81797](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81797)
=> fix/81797 -> master

src/SME.SGP.Aplicacao/Commands/ConselhoClasse/AlterarConselhoClasse/AlterarConselhoClasseCommadHandler.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasse/GravarConselhoClasse/GravarConselhoClasseCommadHandler.cs
[AB#81653](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81653)
=> fix/81653 -> r2

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs, src/SME.SGP.Infra/Dtos/AulasPrevistas/TurmaDataAulaComponenteQtdeAulasDto.cs
Ajuste no cálculo de frequência considerando mais de um período do aluno na turma. No percentual de frequência global também consideramos os períodos do aluno na turma e considerar o percentual mínimo quando houver quantidade de aulas.
=> Bug: 81571

scripts/V594__CLASSIFICACAO_DOCUMENTO_E_DOCUMENTO_TURMA_COMPONENTE_CURRICULAR.sql
[AB#81851](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81851)
=> Criação de nova classificação, campo múltipls documentos e turma e componente em documento

scripts/V593__CARGA_QUESTIONARIO_ENCAMINHAMENTO_NAAPA_ETAPA_3_ITINERANCIA.sql
[AB#81471](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81471)
=> 81471 - Carga do questionario naapa etapa 3 itinerância

scripts/V591__EXCLUSAO_LOGICA_PENDENCIAS_FECHAMENTO_ANO_2022.sql, src/SME.SGP.Api/Controllers/ProfessorController.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasProfessorTurma.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Dados/Repositorios/RepositorioOcorrencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaFechamento.cs
[AB#81915](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81915)
=> Documentos - É necessario informar o codigoRF Dre, UE e o ano letivo

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs, src/SME.SGP.Aplicacao/Workers/WorkerRabbitMQBase.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs, src/SME.SGP.Infra/Dtos/AulasPrevistas/TurmaDataAulaComponenteQtdeAulasDto.cs
=> master -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
[AB#81560](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81560)
=> fix/81560 -> r2

scripts/V593__CARGA_QUESTIONARIO_ENCAMINHAMENTO_NAAPA_ETAPA_3_ITINERANCIA.sql, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs
[AB#81489](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81489)
=> 81489 - Criação da base de testes Itinerância

scripts/V594__CLASSIFICACAO_DOCUMENTO_E_DOCUMENTO_TURMA_COMPONENTE_CURRICULAR.sql, src/SME.SGP.Dados/Mapeamentos/ClassificacaoDocumentoMap.cs, src/SME.SGP.Dados/Mapeamentos/DocumentoMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioDocumento.cs, src/SME.SGP.Dominio/Entidades/ClassificacaoDocumento.cs, src/SME.SGP.Dominio/Entidades/Documento.cs, src/SME.SGP.Dominio/Enumerados/ClassificacaoDocumento.cs, src/SME.SGP.Infra/Dtos/Armazenamento/DocumentoDto.cs, src/SME.SGP.Infra/Dtos/Armazenamento/ObterDocumentoDto.cs, teste/SME.SGP.TesteIntegracao/Documento/Ao_listar_documentos.cs, teste/SME.SGP.TesteIntegracao/Documento/Base/DocumentoTesteBase.cs, teste/SME.SGP.TesteIntegracao/Documento/Base/FiltroDocumentoDto.cs, teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#81856](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81856)
=> Adicionando campos de turma e componente na entidade documento

src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ObterQuestionarioItinerarioEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IObterQuestionarioItinerarioEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterQuestionarioItinerarioEncaminhamentoNAAPA/ObterQuestionarioItinerarioEncaminhamentoNAAPAQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterQuestionarioItinerarioEncaminhamentoNAAPA/ObterQuestionarioItinerarioEncaminhamentoNAAPAQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioQuestaoEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioQuestaoEncaminhamentoNAAPA.cs, src/SME.SGP.IoC/RegistrarDependencias.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_obter_encaminhamento_itinerancia.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs
[AB#81478](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81478)
=> 81478 - Questionário da seção de encaminhamento itinerário

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RegistrarEncaminhamentoAEEUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Queries/Questionario/ObterQuestoesObrigatoriasNaoRespondidas/ObterQuestoesObrigatoriasNaoRespondidasQuery.cs, src/SME.SGP.Aplicacao/Queries/Questionario/ObterQuestoesObrigatoriasNaoRespondidas/ObterQuestoesObrigatoriasNaoRespondidasQueryHandler.cs, src/SME.SGP.Infra/Dtos/Questionario/QuestaoObrigatoriaNaoRespondidaDto.cs, src/SME.SGP.Infra/Dtos/Questionario/RespostaQuestaoObrigatoriaDto.cs
[AB#82206](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82206)
=> 82206 - Questões obrigatórias não preenchidas

src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoItinerarioNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/AlterarEncaminhamentoNAAPASecaoQuestao/AlterarEncaminhamentoNAAPASecaoQuestaoCommand.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/AlterarEncaminhamentoNAAPASecaoQuestao/AlterarEncaminhamentoNAAPASecaoQuestaoCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IRegistrarEncaminhamentoItinerarioNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterQuestoesObrigatoriasNaoPreechidas/ObterQuestoesObrigatoriasNaoPreechidasQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterQuestoesObrigatoriasNaoPreechidas/ObterQuestoesObrigatoriasNaoPreechidasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterSecaoQuestionarioEncaminhamentoNAAPAPorId/ObterSecaoQuestionarioEncaminhamentoNAAPAPorIdQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterSecaoQuestionarioEncaminhamentoNAAPAPorId/ObterSecaoQuestionarioEncaminhamentoNAAPAPorIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioSecaoEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSecaoEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioEncaminhamentoNAAPA.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoAEE/QuestaoObrigatoriaDto.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/EncaminhamentoNAAPAItineranciaDto.cs, src/SME.SGP.IoC/RegistrarDependencias.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_cadastrar_editar_encaminhamento_naapa_itinerancia.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs
[AB#81480](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81480)
=> 81480 - Inclusão/alteração de questões itinerância

src/SME.SGP.Aplicacao/CasosDeUso/Armazenamento/Documento/ListarTiposDeDocumentosUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioTipoDocumento.cs, src/SME.SGP.Infra/Dtos/Armazenamento/TipoDocumentoCompletoDto.cs
[AB#81859](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81859)
=> Alterar listagem de tipos e classificações

src/SME.SGP.Api/Controllers/DocumentoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Armazenamento/Documento/AlterarDocumentoUseCase.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/AlterarDocumento/AlterarDocumentoCommand.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/AlterarDocumento/AlterarDocumentoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/ExcluirArquivoRepositorioPorId/ExcluirArquivoRepositorioPorIdCommand.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/ExcluirArquivoRepositorioPorId/ExcluirArquivoRepositorioPorIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/ExcluirReferenciaArquivoDocumentoPorArquivoId/ExcluirReferenciaArquivoDocumentoPorArquivoIdCommand.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/ExcluirReferenciaArquivoDocumentoPorArquivoId/ExcluirReferenciaArquivoDocumentoPorArquivoIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/SalvarDocumento/SalvarDocumentoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/ObterArquivosPorCodigos/ObterArquivosPorCodigosQuery.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/ObterArquivosPorIds/ObterArquivosPorIdsQuery.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/ObterArquivosPorIds/ObterArquivosPorIdsQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/ObterArquivosPorIds/ObterArquivosPorIdsQueryValidator.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/ObterDocumentosArquivosPorDocumentoId/ObterDocumentosArquivosPorDocumentoIdQuery.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/ObterDocumentosArquivosPorDocumentoId/ObterDocumentosArquivosPorDocumentoIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/ObterDocumentosArquivosPorDocumentoId/ObterDocumentosArquivosPorDocumentoIdQueryValidator.cs, src/SME.SGP.Aplicacao/Queries/ClassificacaoDocumento/ObterClassificacaoDocumentoPorId/ObterClassificacaoDocumentoPorIdQueryHandler.cs, src/SME.SGP.Dados/Mapeamentos/DocumentoArquivoMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioArquivo.cs, src/SME.SGP.Dados/Repositorios/RepositorioDocumento.cs, src/SME.SGP.Dados/Repositorios/RepositorioDocumentoArquivo.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioArquivo.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDocumentoArquivo.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioDocumento.cs, src/SME.SGP.Dominio/Entidades/DocumentoArquivo.cs, src/SME.SGP.Infra/Dtos/Armazenamento/AlterarDocumentoDto.cs, src/SME.SGP.IoC/RegistrarDependencias.cs, teste/SME.SGP.TesteIntegracao/Documento/Ao_salvar_documento.cs
[AB#82189](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82189)
=> Inserir e Alterar com múltiplos arquivos

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoItinerarioNAAPAUseCase.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/EncaminhamentoNAAPAItineranciaDto.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_cadastrar_editar_encaminhamento_naapa_itinerancia.cs
[AB#81480](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81480)
=> 81480 - Inclusão de teste de alteração

src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs
[AB#82157](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82157)
=> Ajuste para obter os fechamentos turma disciplina dos bimestres finais.

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#82197](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82197)
=> fix/82197 -> r2

src/SME.SGP.Api/Controllers/DocumentoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Armazenamento/Documento/ExcluirDocumentoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Armazenamento/Documento/UploadDocumentoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Armazenamento/IUploadDocumentoUseCase.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/ObterArquivosPorIds/ObterArquivosPorIdsQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/ObterArquivosPorIds/ObterArquivosPorIdsQueryValidator.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/ObterDocumentosArquivosPorDocumentoId/ObterDocumentosArquivosPorDocumentoIdQueryHandler.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/Armazenamento/Documentos/ExcluirDocumentoUseCaseTeste.cs, teste/SME.SGP.TesteIntegracao/Documento/Ao_excluir_documento.cs, teste/SME.SGP.TesteIntegracao/Documento/Base/DocumentoTesteBase.cs
[AB#82200](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82200)
=> Exclusão de documentos

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoItinerarioNAAPAUseCase.cs, src/SME.SGP.Dominio/Enumerados/SituacaoNAAPA.cs
[AB#81480](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81480)
=> 81480 - Adicionando alteração da situação

src/SME.SGP.Aplicacao/CasosDeUso/Armazenamento/Documento/ObterDocumentoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Armazenamento/Documento/IObterDocumentoUseCase.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/Documentos/ObterDocumentoPorIdCompleto/ObterDocumentoPorIdCompletoQuery.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/Documentos/ObterDocumentoPorIdCompleto/ObterDocumentoPorIdCompletoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioDocumento.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDocumento.cs, src/SME.SGP.Infra/Dtos/Armazenamento/ObterDocumentoCompletoDto.cs, src/SME.SGP.Infra/Dtos/Armazenamento/ObterDocumentoResumidoDto.cs
[AB#82200](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82200)
=> Obter documento

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
[AB#82161](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82161)
=> Ajuste para gerar parecer conclusivo, considerando o tipo de calendário de acordo com o semestre selecionado no filtro.

src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Armazenamento/Documento/IObterDocumentoUseCase.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/Documentos/ObterDocumentoPorIdCompleto/ObterDocumentoPorIdCompletoQuery.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/Documentos/ObterDocumentoPorIdCompleto/ObterDocumentoPorIdCompletoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioDocumento.cs, src/SME.SGP.Infra/Dtos/Armazenamento/ObterDocumentoCompletoDto.cs, src/SME.SGP.Infra/Dtos/Armazenamento/ObterDocumentoResumidoDto.cs
[AB#82245](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82245)
=> Carregar informações para evitar requisições do front no back

src/SME.SGP.Dados/Repositorios/RepositorioDocumento.cs
=> Ajustando a ordem de exibição de forma decrescente por data e alfabética por turma e componente

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#82197](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82197)
=> fix/82197 -> master

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaAlunosComAusencia/ObterListaAlunosComAusenciaQueryHandler.cs
[AB#82159](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82159)
=> fix/82159 -> master

src/SME.SGP.Api/Controllers/AulaPrevistaController.cs, src/SME.SGP.Aplicacao/Comandos/ComandosAulaPrevista.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs, src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosAulaPrevista.cs, src/SME.SGP.Aplicacao/Queries/AulaPrevistaBimestre/ObterAulaPrevistaBimestrePorAulaPrevistaIdBimestre/ObterAulaPrevistaBimestrePorAulaPrevistaIdBimestreQuery.cs, src/SME.SGP.Aplicacao/Queries/AulaPrevistaBimestre/ObterAulaPrevistaBimestrePorAulaPrevistaIdBimestre/ObterAulaPrevistaBimestrePorAulaPrevistaIdBimestreQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAulaPrevistaBimestre.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAulaPrevistaBimestre.cs
[AB#81913](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81913)
=> fix/81913 -> r2

src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs
Ajuste na funcionalidade de salvar e excluir compensação incluindo um delay ao disparar a fila de cálculo de frequência, com intuíto de aguardar os tempo de finalização da transação do banco.
=> Bug: 82158

src/SME.SGP.Aplicacao/Commands/ConselhoClasse/AlterarConselhoClasse/AlterarConselhoClasseCommadHandler.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasse/GravarConselhoClasse/GravarConselhoClasseCommadHandler.cs
[AB#81653](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81653)
=> Fix/81653 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#82198](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82198)
=> Fix/82198 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#81927](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81927)
=> fix/81927 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterPeriodoEscolarPorTurmaUseCase.cs
[AB#82208](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82208)
=> Correção ao obter os períodos dos planos de aula.

src/SME.SGP.Aplicacao/Commands/Aulas/ValidarComponentesDoProfessor/ValidarComponentesDoProfessorCommandHandler.cs
[AB#82162](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82162)
=> Ajuste para validar os componentes de regência do professor.

src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNotaConsulta.cs
[AB#80499](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80499)
=> Fix/80499 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasPorPeriodoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQueryHandler.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/Armazenamento/Documentos/ExcluirDocumentoUseCaseTeste.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/BoletimSimples/BoletimSimplesUseCaseTeste.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_inserir_nota_numerica_pos_conselho_bimestre.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs, teste/SME.SGP.TesteIntegracao/Documento/Ao_excluir_documento.cs, teste/SME.SGP.TesteIntegracao/Documento/Ao_salvar_documento.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_obter_encaminhamento.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Ao_apresentar_os_alunos_na_tela.cs, teste/SME.SGP.TesteIntegracao/Listao/Ao_validar_apresentacao_dos_alunos.cs, teste/SME.SGP.TesteIntegracao/NotaFechamentoBimestre/Ao_validar_exibicao_alunos.cs, teste/SME.SGP.TesteIntegracao/NotaFechamentoFinal/Ao_lancar_nota_aluno_inativo_ano_anterior.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_acessar_tela_de_listagem.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Base/PlanoAEETesteBase.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_copiar_plano_de_aula.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Base/PlanoAulaTesteBase.cs, teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
Correção dos testes de integração
=> Story/81811 --> RELEASE - Correção dos testes de integração

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
Ajuste no cálculo de frequência tratando um lista onde se esperava um registro, porém retorna mais itens e ocorria erro.
=> Bug: 82477

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
[AB#81560](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81560)
=> fix/81560 -> master

src/SME.SGP.Aplicacao/CasosDeUso/PendenciaDiarioBordo/TratarPendenciaDiarioBordoPorTurmaAulaComponenteUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#77204](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77204)
=> Removendo filtro na query genérica para uso do NAAPA

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs, src/SME.SGP.Infra/Dtos/NotasConceitosBimestreRetornoDto.cs
[AB#82755](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82755)
=> 82755 - Alterar dto para receber regras de arredondamento

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoItinerarioNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/AlterarEncaminhamentoNAAPASecao/AlterarEncaminhamentoNAAPASecaoCommand.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/AlterarEncaminhamentoNAAPASecaoQuestao/AlterarEncaminhamentoNAAPASecaoQuestaoCommand.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/AlterarEncaminhamentoNAAPASecaoQuestao/AlterarEncaminhamentoNAAPASecaoQuestaoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentoNAAPAPorId/ObterEncaminhamentoNAAPAPorIdQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentoNAAPAPorId/ObterEncaminhamentoNAAPAPorIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentoNAAPAPorIdESecao/ObterEncaminhamentoNAAPAPorIdESecaoQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentoNAAPAPorIdESecao/ObterEncaminhamentoNAAPAPorIdESecaoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoNAAPA.cs
[AB#82538](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82538)
[AB#82688](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82688)
=> Exclusão do campo não é gravada. Eventualmente atendimento não fica gravado

src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
[AB#82873](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82873)
=> Erro ao utilizar Diretor: "Não foram encontrados professor com o perfil X"

src/SME.SGP.Dados/Repositorios/RepositorioDocumento.cs
[AB#82865](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82865)
=> Ordenação não está adequada

src/SME.SGP.Api/Controllers/ArmazenamentoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Armazenamento/ExcluirArquivosUseCase.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/ExcluirArquivosRepositorioPorIds/ExcluirArquivosRepositorioPorIdsCommand.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/ExcluirArquivosRepositorioPorIds/ExcluirArquivosRepositorioPorIdsCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Armazenamento/IExcluirArquivosUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioArquivo.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioArquivo.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#82871](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82871)
[AB#82889](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82889)
=> Endpoint para exclusão de multiplos arquivos da tela de Anexar Documentos

src/SME.SGP.Api/Controllers/DocumentoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Armazenamento/Documento/ListarDocumentosUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Armazenamento/IListarDocumentosUseCase .cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/Documentos/ObterDocumentosPorUeETipoEClassificacaoQuery/ObterDocumentosPorUeETipoEClassificacaoQuery.cs, src/SME.SGP.Aplicacao/Queries/Armazenamento/Documentos/ObterDocumentosPorUeETipoEClassificacaoQuery/ObterDocumentosPorUeETipoEClassificacaoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioDocumento.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDocumento.cs, teste/SME.SGP.TesteIntegracao/Documento/Ao_listar_documentos.cs
[AB#82880](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82880)
=> Filtro de ano histórico não é obedecido

src/SME.SGP.Api/Controllers/FiltroRelatorioController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PendenciaDiarioBordo/TratarPendenciaDiarioBordoPorTurmaAulaComponenteUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterFiltroRelatoriosUesPorAbrangencia/ObterFiltroRelatoriosUesPorAbrangenciaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IObterFiltroRelatoriosUesPorAbrangenciaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosUesPorAbrangencia/ObterFiltroRelatoriosUesPorAbrangenciaQuery.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosUesPorAbrangencia/ObterFiltroRelatoriosUesPorAbrangenciaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#83004](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83004)
=> Fix/83004 -> r2

scripts/V595__AJUSTE_FUNCAO_ABRANGENCIA_MODALIDADES_INCLUINDO_CODIGO_UE.sql, src/SME.SGP.Api/Controllers/FiltroRelatorioController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IObterFiltroRelatoriosModalidadesPorUeAbrangenciaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaQuery.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAbrangencia.cs
Ajuste na listagem de modalidades para o boletim, alterando a chamada para a proc de abrangência passando o código da UE.
=> Bug: 81561

scripts/V598__INSERT_QUESTOES_PLANO_AEE_AVE_ESTAGIARIO_SRM_PAEE_COLABORATIVO.sql, src/SME.SGP.Dominio/Enumerados/TipoQuestao.cs
[AB#82284](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82284)
=> Criar questões AVE, Estagiário Turma e SRM

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/AtualizarInformacoesDoEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IAtualizarInformacoesDoEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosComSituacaoDiferenteDeEncerrado/ObterEncaminhamentosComSituacaoDiferenteDeEncerradoQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosComSituacaoDiferenteDeEncerrado/ObterEncaminhamentosComSituacaoDiferenteDeEncerradoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio/Enumerados/SituacaoNAAPA.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgp.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#82427](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82427)
=> 82427 - Criar processo no Worker

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/AtualizarTurmaDoEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IAtualizarTurmaDoEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosComSituacaoDiferenteDeEncerrado/ObterEncaminhamentosComSituacaoDiferenteDeEncerradoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs, src/SME.SGP.Infra/Dtos/TurmasDoAlunoDto.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarUseCaseRabbitSgp.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_atualizar_turma_encaminhamento_naapa_para_aluno_ano_posterior.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_atualizar_turma_encaminhamento_naapa_para_aluno_transferido.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/ServicosFake/ObterAlunosEolPorCodigosQueryHandlerFake_AnoPosterior.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/ServicosFake/ObterAlunosEolPorCodigosQueryHandlerFake_Transferido.cs, teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#82428](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82428)
=> 82428 - Criar worker de consumo para as fila - Alterar turma

src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterSrmPaeeColaborativoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IObterSrmPaeeColaborativoUseCase.cs, src/SME.SGP.Aplicacao/Queries/EOL/SRM/ObterDadosSrmPaeeColaborativoEolQuery.cs, src/SME.SGP.Aplicacao/Queries/EOL/SRM/ObterDadosSrmPaeeColaborativoEolQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUesComDrePorCodigoUes/ObterUesComDrePorCodigoUesQuery.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUesComDrePorCodigoUes/ObterUesComDrePorCodigoUesQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioUeConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioUeConsulta.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/DadosSrmPaeeColaborativoEolDto.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/FiltroSrmPaeeColaborativoDto.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/SrmPaeeColaborativoSgpDto.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#82286](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82286)
=> Endpoint de consulta de SRM/PAEE Colaborativo

src/SME.SGP.Api/Controllers/RelatorioController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/EncaminhamentoAEE/RelatorioEncaminhamentoAeeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IRelatorioEncaminhamentoAEEUseCase.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs, src/SME.SGP.Infra/Dtos/Relatorios/EncaminhamentoAEE/FiltroRelatorioEncaminhamentoAEEDto.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpRelatorios.cs
[AB#79757](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79757)
=> 79757 - Endpoint de solicitação do relatório

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
[AB#81813](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81813)
=> Fix/81813 -> r2

src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#79757](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79757)
=> 79757 - Inclusão no registro de dependencia

src/SME.SGP.Api/Controllers/AutenticacaoController.cs
This reverts commit 2f9bb49aa5be3c2c46d29d963493f3c970094210.
=> Revert "implementação para identificar o problema de timeout em HOM2"

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQueryHandler.cs
[AB#81813](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81813)
=> BUG 81813 -> r2

scripts/V598__INSERT_QUESTOES_PLANO_AEE_AVE_ESTAGIARIO_SRM_PAEE_COLABORATIVO.sql, src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterSrmPaeeColaborativoUseCase.cs, src/SME.SGP.Aplicacao/Queries/EOL/SRM/ObterDadosSrmPaeeColaborativoEolQuery.cs, src/SME.SGP.Aplicacao/Queries/EOL/SRM/ObterDadosSrmPaeeColaborativoEolQueryHandler.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/FiltroPesquisaQuestoesPlanoAEEDto.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_atribuir_responsavel_plano_aee.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_editar_plano_aee.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_realizar_devolucao.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_remover_atribuicao_responsavel.cs
[AB#82288](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82288)
=> Manutenção no endpoint de perguntas/respostas - Listagem

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQueryHandler.cs
[AB#81813](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81813)
=> Fix/81813 -> master

src/SME.SGP.Api/Controllers/RelatorioController.cs, src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#83360](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83360)
=> 83360 - Criação do menu de permisionamento

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEAnoPlanoAee/ObterAlunoPorCodigoEAnoPlanoAeeQuery.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEAnoPlanoAee/ObterAlunoPorCodigoEAnoPlanoAeeQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasAlunoPorFiltroPlanoAee/ObterTurmasAlunoPorFiltroPlanoAeeQuery.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasAlunoPorFiltroPlanoAee/ObterTurmasAlunoPorFiltroPlanoAeeQueryHandler.cs, teste/SME.SGP.Aplicacao.Teste/Queries/Aluno/ObterAlunoPorCodigoEAnoPlanoAee/ObterAlunoPorCodigoEAnoPlanoAeeQueryHandlerTeste.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_atribuir_responsavel_plano_aee.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_editar_plano_aee.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_realizar_devolucao.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_remover_atribuicao_responsavel.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/ServicosFakes/ObterAlunoPorCodigoEAnoPlanoAeeQueryHandlerFake.cs
[82741 R8 - Liberação 2] Plano AEE - Erro ao acessar os registros de planos de 2022: "Não foram encontradas turmas para o aluno"
[AB#83345](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83345)
[AB#83400](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83400) 
[AB#83413](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83413)
=> Fix-83345 Correção do Erro Não foram encontradas turmas para o aluno

src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs
[AB#83215](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83215)
=> fix/83215 -> master

src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoAulaPrevista.cs
[AB#80511](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80511)
=> Correção do envio de notificações de divergências entre aulas dadas x previstas.

src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoAulaPrevista.cs
[AB#80511](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/80511)
=> Correção dos envios de notificações de aulas previstas x dadas.

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/AtualizarTurmaDoEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosEolPorCodigos/ObterAlunosEolPorCodigosQuery.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosEolPorCodigos/ObterAlunosEolPorCodigosQueryHandler.cs
[AB#83959](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83959)
=> 83959 - Ajuste busca matrículas aluno do EOL (n~]ao trazer somente a ultima situação)

src/SME.SGP.Dominio/Entidades/FrequenciaAluno.cs
[AB#82811](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82811)
=> Arredondar percentual de frequência para parecer conclusivo.

src/SME.SGP.Aplicacao/Queries/Notificacoes/ObterUltimasNotificacoesNaoLidasPorUsuario/ObterUltimasNotificacoesNaoLidasPorUsuarioQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioNotificacao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotificacao.cs
[AB#83939](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83939)
=> fix/83939 -> r2

src/SME.SGP.Aplicacao/Queries/Notificacoes/ObterUltimasNotificacoesNaoLidasPorUsuario/ObterUltimasNotificacoesNaoLidasPorUsuarioQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioNotificacao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotificacao.cs
[AB#83939](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83939)
=> fix/83939 -> master

teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_cadastrar_editar_encaminhamento_naapa_rascunho.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs
[AB#84138](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84138)
=> 84138 - Teste nova questão Turmas Programa Encaminhamento NAAPA

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#84107](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84107)
=> fix/84107 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#84107](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84107)
=> fix/84107 -> master

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
Complemento do ajuste, incluindo uma validação de objeto nulo.
=> Bug: 82155

src/SME.SGP.Aplicacao/Queries/UE/ObterUeComDrePorCodigo/ObterUeComDrePorCodigoQueryHandler.cs, src/SME.SGP.Dominio/Enumerados/TipoEscola.cs
[AB#84050](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84050)
=> 84050 - Alterar sincronização institucional

src/SME.SGP.Api/Controllers/AulaIntegracaoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterAulasPorTurmaComponenteDataUseCase.cs, src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaUnica/InserirAulaUnicaCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/IObterAulasPorTurmaComponenteDataUseCase.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterAulasPorDataTurmaComponenteCurricular/ObterAulasPorDataTurmaComponenteCurricularQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterAulasPorDataTurmaComponenteCurricularCJ/ObterAulasPorDataTurmaComponenteCurricularCJQuery.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterAulasPorDataTurmaComponenteCurricularCJ/ObterAulasPorDataTurmaComponenteCurricularCJQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAulaConsulta.cs, src/SME.SGP.Infra/Dtos/AulaConsultaDto.cs, src/SME.SGP.Infra/Dtos/AulaQuantidadeTipoDto.cs, src/SME.SGP.Infra/Dtos/FiltroObterAulasPorTurmaComponenteDataDto.cs, src/SME.SGP.IoC/RegistrarDependencias.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_obter_aulas_por_turma_componente_data.cs, teste/SME.SGP.TesteIntegracao/Aula/Base/AulaTeste.cs
[AB#84209](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84209)
=> Criação do endpoint de consulta de aulas no SGP para SGA

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#84379](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84379)
=> Tratamento para alunos que estão sem matrículas ativas.

src/SME.SGP.Aplicacao/Comandos/ComandosAtividadeAvaliativa.cs, src/SME.SGP.Dados/Repositorios/RepositorioTipoCalendarioConsulta.cs
[AB#84387](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84387)
=> Correção do formato da data para obter os períodos da avaliação.

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs
[AB#84213](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84213)
=> fix/84213 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Notificacao/LancarFrequenciaAulaSgaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/InserirFrequenciasAula/InserirFrequenciasAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Notificacao/ILancarFrequenciaAulaSgaUseCase.cs, src/SME.SGP.Frequencia.Worker/WorkerRabbitFrequencia.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpFrequencia.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarFrequenciaUseCaseRabbitSgp.cs
[AB#84211](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84211)
=> Persistência de frequência pela integração GSA - 84211

src/SME.SGP.Aplicacao/Consultas/ConsultaDres.cs
[AB#84366](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84366)
=> Fix/84366 -> master

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQueryHandler.cs
[AB#84213](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84213)
=> fix/84213 -> r2 - retirando IServicoEol para query mediator

src/SME.SGP.Api/Controllers/EncaminhamentoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RelatorioEncaminhamentoAeeDetalhadoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/EncaminhamentoAEE/RelatorioEncaminhamentoAeeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoAEE/IRelatorioEncaminhamentoAeeDetalhadoUseCase.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioEncaminhamentoAeeDetalhadoDto.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpRelatorios.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#83460](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83460)
=> Criação do endpoint de relatório detalhado de encaminhamento aee - 83460

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQueryHandler.cs
[AB#84213](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84213)
=> fix/84213 -> master  / retirada de IServicoEol da consulta para query mediator.

src/SME.SGP.Aplicacao/CasosDeUso/AtividadeAvaliativa/ObterAtividadesNotasAlunoPorTurmaPeriodoUseCase.cs, src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterAtividadesNotasAlunoPorTurmaPeriodo/ObterAtividadesNotasAlunoPorTurmaPeriodoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterAusenciasDaAtividadesAvaliativasPorAluno/ObterAusenciasDaAtividadesAvaliativasPorAlunoQuery.cs, src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterAusenciasDaAtividadesAvaliativasPorAluno/ObterAusenciasDaAtividadesAvaliativasPorAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaConsulta.cs, src/SME.SGP.Infra/Dtos/AtividadeAvaliativa/AvaliacaoNotaAlunoDto.cs
[AB#63939](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63939)
=> Incluir indicativo de ausência na avaliação

src/SME.SGP.Aplicacao/CasosDeUso/AtividadeAvaliativa/ObterAtividadesNotasAlunoPorTurmaPeriodoUseCase.cs, src/SME.SGP.Aplicacao/Queries/Disciplina/ObterComponentesCurricularesPorProfessorETurmaParaPlanejamento/ObterComponentesCurricularesPorProfessorETurmaParaPlanejamentoQuery.cs, src/SME.SGP.Aplicacao/Queries/Disciplina/ObterComponentesCurricularesPorProfessorETurmaParaPlanejamento/ObterComponentesCurricularesPorProfessorETurmaParaPlanejamentoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioEOL.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioTurma.cs, src/SME.SGP.Infra/Dtos/AtividadeAvaliativa/AvaliacaoNotaAlunoDto.cs, teste/SME.SGP.TesteIntegracao/NotaFechamentoBimestre/Ao_listar_notas_avaliacoes_por_turma.cs
[AB#63937](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63937)
=> 63937 - Incluir os componentes das atividades de notas

src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoDiariosBordo.cs
[AB#77503](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77503)
=> Fix/77503 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConsolidacaoTurmaFechamento/ExecutarConsolidacaoTurmaFechamentoUseCase.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoFechamentoComponenteTurma/ExcluirConsolidacaoPorTurmaIdEBimestre/ExcluirConsolidacaoFechamentoPorTurmaIdEBimestreCommand.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoFechamentoComponenteTurma/ExcluirConsolidacaoPorTurmaIdEBimestre/ExcluirConsolidacaoFechamentoPorTurmaIdEBimestreCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoConsolidado.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoConsolidado.cs
[AB#77533](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77533)
=> Fix/77533 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/SincronizacaoInstitucional/Turma/ExecutarSincronizacaoInstitucionalTurmaExcluirTurmaExtintaUseCase.cs, src/SME.SGP.Aplicacao/Commands/SincronizacaoInstituicional/Turmas/TrataSincronizacaoInstitucionalTurma/TrataSincronizacaoInstitucionalTurmaCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs, src/SME.SGP.Infra/Dtos/FiltroTurmaCodigoTurmaIdDto.cs
Ajuste para detalhamento do erro de exclusão de turma extinta no log.
=> Bug: 83432

src/SME.SGP.Aplicacao/Consultas/ConsultasNotificacao.cs, src/SME.SGP.Dominio/Entidades/Notificacao.cs, src/SME.SGP.Infra.Mensageria/RabbitModelPooledObjectPolicy.cs
[AB#84822](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84822)
=> fix/84822 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/AtividadeAvaliativa/ObterAtividadesNotasAlunoPorTurmaPeriodoUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs, src/SME.SGP.Infra/Dtos/AtividadeAvaliativa/AvaliacaoNotaAlunoDto.cs
[AB#84940](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84940)
=> Adicionando a propriedade ehInterdisciplinar

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs
[AB#85020](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85020)
=> fix/85020 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
[AB#84833](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84833)
=> fix/84833 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
[AB#84833](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84833)
=> fix/84833 -> master

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs
[AB#85020](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85020)
=> fix/85020 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasNotificacao.cs, src/SME.SGP.Dominio/Entidades/Notificacao.cs, src/SME.SGP.Infra.Mensageria/RabbitModelPooledObjectPolicy.cs
[AB#84822](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84822)
=> fix/84822 -> master

src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoAcompanhamentoAprendizagemAluno/ConsolidacaoAcompanhamentoAprendizagemAlunoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoAcompanhamentoAprendizagemAluno/ConsolidacaoAcompanhamentoAprendizagemAlunosPorUEUseCase.cs, src/SME.SGP.Infra/Dtos/ConsolidacaoAcompanhamentoAprendizagemAluno/FiltroUEDto.cs
[AB#85367](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85367)
=> fix/85367 -> r2

src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/AtividadeAvaliativaPorTurma/AtualizaCacheDeAtividadeAvaliativaPorTurmaCommandHandler.cs
[AB#84959](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84959)
=> Tratar possíveis valores nulos ao salvar avaliações em cache.

src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
[AB#85019](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85019)
=> Fix/85019 -> master

src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoAcompanhamentoAprendizagemAluno/ConsolidacaoAcompanhamentoAprendizagemAlunoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoAcompanhamentoAprendizagemAluno/ConsolidacaoAcompanhamentoAprendizagemAlunosPorUEUseCase.cs, src/SME.SGP.Infra/Dtos/ConsolidacaoAcompanhamentoAprendizagemAluno/FiltroUEDto.cs
[AB#85367](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85367)
=> fix/85367 -> master

src/SME.SGP.Aplicacao/Comandos/ComandosAtividadeAvaliativa.cs
[AB#84934](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84934)
=> fix/84934 -> master

src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/AtividadeAvaliativaPorTurma/AtualizaCacheDeAtividadeAvaliativaPorTurmaCommandHandler.cs
[AB#84959](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84959)
=> Tratar inserção no cache para atividades novas

scripts/V599__ALTERAR_TAMANHO_DO_CAMPO_PROFESSOR_RF.sql
[AB#84720](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84720)
=> Alterar tamanho do campo professor_rf

src/SME.SGP.Api/Controllers/AtribuicaoCJIntegracaoController.cs, src/SME.SGP.Api/Controllers/AulaIntegracaoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/ListarAtribuicoesCJPorFiltroUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterAulasPorTurmaComponenteDataUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoAcompanhamentoAprendizagemAluno/ConsolidacaoAcompanhamentoAprendizagemAlunoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoAcompanhamentoAprendizagemAluno/ConsolidacaoAcompanhamentoAprendizagemAlunosPorUEUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Notificacao/LancarFrequenciaAulaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaUnica/InserirAulaUnicaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/InserirFrequenciasAula/InserirFrequenciasAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/IObterAulasPorTurmaComponenteDataUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Notificacao/ILancarFrequenciaAulaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterAulasPorDataTurmaComponenteCurricular/ObterAulasPorDataTurmaComponenteCurricularQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterAulasPorDataTurmaComponenteCurricularCJ/ObterAulasPorDataTurmaComponenteCurricularCJQuery.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterAulasPorDataTurmaComponenteCurricularCJ/ObterAulasPorDataTurmaComponenteCurricularCJQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanejamentoAnual.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAulaConsulta.cs, src/SME.SGP.Frequencia.Worker/WorkerRabbitFrequencia.cs, src/SME.SGP.Infra/Dtos/AtribuicaoCJListaRetornoDto.cs, src/SME.SGP.Infra/Dtos/AulaQuantidadeTipoDto.cs, src/SME.SGP.Infra/Dtos/ConsolidacaoAcompanhamentoAprendizagemAluno/FiltroUEDto.cs, src/SME.SGP.Infra/Dtos/FiltroObterAulasPorTurmaComponenteDataDto.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpFrequencia.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarFrequenciaUseCaseRabbitSgp.cs, src/SME.SGP.IoC/RegistrarDependencias.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_obter_aulas_por_turma_componente_data.cs, teste/SME.SGP.TesteIntegracao/Aula/Base/AulaTeste.cs
[AB#85696](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85696)
=> Fix/85696 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioPlanejamentoAnualPeriodoEscolar.cs
[AB#85810](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85810)
=> Obter bimestres do tipo de calendário da turma selecionada

src/SME.SGP.Dados/Repositorios/RepositorioPlanejamentoAnual.cs
[AB#85696](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85696)
=> Fix/85696 -> master

src/SME.SGP.Aplicacao/Queries/ObjetivoAprendizagem/ListarObjetivoAprendizagemPorAnoEComponenteCurricular/ListarObjetivoAprendizagemPorAnoEComponenteCurricularQueryHandler.cs
[AB#85833](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85833)
=> Fix/85833 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/AtualizarTurmaDoEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/NotificarSobreTransferenciaUeDreAlunoTurmaDoEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/INotificarSobreTransferenciaUeDreAlunoTurmaDoEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgp.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarUseCaseRabbitSgp.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#82807](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/82807)
=> 82807 - Criação e disparo fila notificação transferencia de Ue ou Dre

src/SME.SGP.Aplicacao/Queries/ObjetivoAprendizagem/ListarObjetivoAprendizagemPorAnoEComponenteCurricular/ListarObjetivoAprendizagemPorAnoEComponenteCurricularQueryHandler.cs
[AB#85833](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85833)
=> fix/85833 -> master

src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs
[AB#84986](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84986)
=> Correção na consolidação do fechamento turma componente

src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/ListarAtribuicoesCJPorFiltroUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/ObterAnosLetivosAtribuicaoCJUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/ObterProfessoresTitularesECjsUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/SalvarAtribuicaoCJUseCase.cs, src/SME.SGP.Infra/Dtos/AtribuicaoCJListaFiltroDto.cs
[AB#84710](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84710)
=> Alteração de endpoints de atribuição de CJ

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#85798](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85798)
=> fix/85798 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesUseCase.cs
[AB#85809](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85809)
=> Ajuste para professores visualizarem aulas de anos anteriores

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesUseCase.cs
[AB#85809](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85809)
=> Correção de merge-conflitos

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#85798](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85798)
=> fix/85798 -> master

scripts/V601__ALTERAR_TAMANHO_DO_CAMPO_PROFESSOR_RF_TABELA_ATRIBUICAO_EXPORADICA.sql, src/SME.SGP.Infra/Dtos/FiltroAtribuicaoEsporadicaDto.cs
[AB#84719](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84719)
=> Alteraração endpoints de atribuição esporádica

src/SME.SGP.Aplicacao/CasosDeUso/SincronizacaoInstitucional/Turma/ExecutarSincronizacaoInstitucionalTurmaTratarUseCase.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaPorCodigo/ObterTurmaPorCodigoQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaPorCodigo/ObterTurmaPorCodigoQueryHandler.cs
[AB#85760](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85760)
[AB#85543](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85543)
=> SGP - story/85760 --> MASTER

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesUseCase.cs
[AB#85809](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85809)
=> Complemento da correção para exibir o detalhamento das aulas anos anteriores

src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterAbrangenciaTurmasPorUeModalidadePeriodoHistoricoAnoLetivoTipos/ObterAbrangenciaTurmaQueryHandler.cs
[AB#86171](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86171)
=> fix/86171 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/SalvarAtribuicaoCJUseCase.cs, src/SME.SGP.Aplicacao/Commands/AtribuicaoCJ/InserirAtribuicaoCJ/InserirAtribuicaoCJCommandHandler.cs
[AB#86210](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86210)
[AB#86270](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86270)
=> Exclusão de atribuição esporádica com divergências de comportamento entre tela principal e tela de edição.

src/SME.SGP.Api/Controllers/AtribuicaoResponsaveisIntegracaoController.cs, src/SME.SGP.Api/Properties/launchSettings.json, src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoDeResponsaveis/ListarAtribuicoesResponsaveisPorFiltroUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AtribuicaoDeResponsaveis/IListarAtribuicoesResponsaveisPorFiltroUseCase.cs, src/SME.SGP.Aplicacao/Queries/AtribuicaoDeResponsaveis/ObterAtribuicaoResponsaveisPorUeTipo/ObterAtribuicaoResponsaveisPorUeTipoQuery.cs, src/SME.SGP.Aplicacao/Queries/AtribuicaoDeResponsaveis/ObterAtribuicaoResponsaveisPorUeTipo/ObterAtribuicaoResponsaveisPorUeTipoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSupervisorEscolaDre.cs, src/SME.SGP.Infra/Dtos/AtribuicaoResponsaveisFiltroDto.cs, src/SME.SGP.Infra/Dtos/Funcionario/AtribuicaoResponsavelDto.cs, src/SME.SGP.Infra/Dtos/Supervisor/SupervisorEscolasDreDto.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#86078](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86078)
[AB#85760](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85760)
=> Criado endpoint para a consulta de supervisores

scripts/V603__ALTERAR_NOME_QUESTOES_NAAPA.sql
[AB#86121](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86121)
=> Alteração do campo nome e nomecomponente das questões

src/SME.SGP.Infra/Dtos/AlunoEnderecoRespostaDto.cs
[AB#86122](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86122)
=> 86122 - Novos campos NIS e CNS consulta de informações do aluno

src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterAbrangenciaTurmasPorUeModalidadePeriodoHistoricoAnoLetivoTipos/ObterAbrangenciaTurmaQueryHandler.cs
[AB#86171](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86171)
=> fix/86171 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultaDres.cs
[AB#86423](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86423)
=> 86423 - Ajuste para busca de Ues sem atribuição por tipo responsavel

src/SME.SGP.Aplicacao/CasosDeUso/SincronizacaoInstitucional/Turma/ExecutarSincronizacaoInstitucionalTurmaSyncUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoRegistrosPedagogicos.cs
[AB#86232](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86232)
=> Fix/86232 

src/SME.SGP.Aplicacao/Comandos/ComandosUsuario.cs, src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosUsuario.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs, src/SME.SGP.Dominio/Constantes/Perfis.cs, src/SME.SGP.Dominio/Entidades/SuporteUsuario.cs, teste/SME.SGP.TesteIntegracao/Autenticar/Ao_realizar_suporte_com_perfil_adm_dre.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs, teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#86133](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86133)
=> 86133 - Alteração na autenticação via suporte

src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs, src/SME.SGP.Dominio/Enumerados/TipoResponsavelAtribuicao.cs
[AB#86300](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86300)
=> 86300 - Melhoria legibilidade codigo

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/NotificarSobreInativacaoAlunoTurmaDoEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/NotificarSobreTransferenciaUeDreAlunoTurmaDoEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs, src/SME.SGP.Infra/Dtos/Supervisor/SupervisorEscolasDreDto.cs
[AB#86300](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86300)
=> 86300 - Ajuste bug nome usuário/supervisor atribuição

scripts/V605__ALTERAR_PLACEHOLDERS_QUESTOES_NAAPA.sql
[AB#86534](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86534)
=> 86534 - Ajuste placeholder campo filiação 1

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterQuestoesPlanoAEEPorVersao/ObterQuestoesPlanoAEEPorVersaoQueryHandler.cs
[AB#86275](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86275)
=> fix/86275 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasEvento.cs
[AB#86302](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86302)
=> fix/86302 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasEvento.cs
[AB#86302](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86302)
=> fix/86302 -> master

src/SME.SGP.Infra/Dtos/AbrangenciaUeRetorno.cs
[AB#86809](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86809)
=> fix/86809 -> r2

src/SME.SGP.Infra/Dtos/AbrangenciaUeRetorno.cs
[AB#86809](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86809)
=> fix/86809 -> master

src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/AtividadeAvaliativaPorTurma/AtualizaCacheDeAtividadeAvaliativaPorTurmaCommandHandler.cs
[AB#85989](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85989)
=> Obter ID da nota conceito da atividade avaliativa ao incluir novo registro na cache.

src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
[AB#86922](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86922)
=> fix/86922 pt.2 -> r2

scripts/V606__INSERIR_PARAMETRO_SISTEMA_TIPOS_UE_IGNORADAS_PENDENCIA.sql, src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaDreUeUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordoPendenciaDevolutiva/ReprocessarDiarioBordoPendenciaDevolutivaPorUeUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PendenciaRegistroIndividual/Jobs/GerarPendenciaAusenciaRegistroIndividualUseCase.cs, src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterTipoUeIgnoraGeracaoPendencias/ObterTipoUeIgnoraGeracaoPendenciasQuery.cs, src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterTipoUeIgnoraGeracaoPendencias/ObterTipoUeIgnoraGeracaoPendenciasQueryHandler.cs, src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
[AB#83337](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/83337)
=> 83337 - Ignorar geração de pendencias tipo escola CEI Direta

src/SME.SGP.Aplicacao/CasosDeUso/ParametrosAnoAnterior/ReplicarParametrosAnoAnteriorUseCase.cs, src/SME.SGP.Aplicacao/Commands/ParametroSistema/ReplicarParametrosAnoAnterior/ReplicarParametrosAnoAnteriorCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ParametrosAnoAnterior/IReplicarParametrosAnoAnteriorUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioParametrosSistema.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioParametrosSistema.cs, src/SME.SGP.Infra/Dtos/ParametrosAnoAnterior/FiltroInclusaoParametrosAnoAnterior.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpPendencias.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarPendenciasUseCaseRabbitSgp.cs, src/SME.SGP.Pendencias.Worker/WorkerRabbitPendencias.cs
[AB#61874](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61874)
=> Criar um worker para ReplicarParametrosAnoAnteriorCommand

src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
[AB#86922](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86922)
=> Fix/86922 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverPendenciasDiarioDeClasseNoFinalDoAnoLetivoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverPendenciasNoFinalDoAnoLetivoPorAnoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverPendenciasNoFinalDoAnoLetivoPorUeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Pendencias/IRemoverPendenciasDiarioDeClasseNoFinalDoAnoLetivoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Pendencias/IRemoverPendenciasNoFinalDoAnoLetivoPorAnoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Pendencias/IRemoverPendenciasNoFinalDoAnoLetivoPorUeUseCase.cs, src/SME.SGP.Infra/Dtos/Pendencia/FiltroRemoverPendenciaFinalAnoLetivoDto.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpPendencias.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarPendenciasUseCaseRabbitSgp.cs, src/SME.SGP.Pendencias.Worker/WorkerRabbitPendencias.cs
[AB#61875](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61875)
=> 61875 - Criar um worker para remover pendências

src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosPorCodigoEolNome/ObterAlunosPorCodigoEolNomeQueryHandler.cs, src/SME.SGP.Infra/Dtos/AlunoSimplesDto.cs
[AB#86832](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86832)
[AB#87031](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87031)
=> R2 BACK - fix/86832

src/SME.SGP.Api/Controllers/PlanoAulaController.cs, src/SME.SGP.Aplicacao/Commands/PlanoAula/MigrarPlanoAula/MigrarPlanoAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAula.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasPlanoAula.cs
[AB#86250](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86250)
=> Tratar código de componentes do território do saber ao copiar plano aula

src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverPendenciasDiarioDeClasseNoFinalDoAnoLetivoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverPendenciasNoFinalDoAnoLetivoPorUeUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverPendenciasNoFinalDoAnoLetivoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Pendencias/IRemoverPendenciasNoFinalDoAnoLetivoUseCase.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterIdsPendenciaAulaPorAnoLetivo/ObterIdsPendenciaAulaPorAnoLetivoQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterIdsPendenciaAulaPorAnoLetivo/ObterIdsPendenciaAulaPorAnoLetivoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaDiarioBordo/ObterIdsPendenciaDiarioBordoPorAnoLetivo/ObterIdsPendenciaDiarioBordoPorAnoLetivoQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaDiarioBordo/ObterIdsPendenciaDiarioBordoPorAnoLetivo/ObterIdsPendenciaDiarioBordoPorAnoLetivoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaRegistroIndividual/ObterIdsPendenciaIndividualPorAnoLetivo/ObterIdsPendenciaIndividualPorAnoLetivoQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaRegistroIndividual/ObterIdsPendenciaIndividualPorAnoLetivo/ObterIdsPendenciaIndividualPorAnoLetivoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaDiarioBordoConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaRegistroIndividual.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaDiarioBordoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaRegistroIndividual.cs, src/SME.SGP.Infra/Dtos/Pendencia/FiltroRemoverPendenciaFinalAnoLetivoDto.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpPendencias.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarPendenciasUseCaseRabbitSgp.cs, src/SME.SGP.Pendencias.Worker/WorkerRabbitPendencias.cs
[AB#79271](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79271)
=> 79271 - Criar os comands de exclusão de pendências por assunto

scripts/V607__ENCAMINHAMENTO_NAAPA_CRIAR_CAMPO_MOTIVO_ENCERRAMENTO.sql, src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/EncerrarEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ObterEncaminhamentoNAAPAPorIdUseCase.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/EncerrarEncaminhamentoNAAPA/EncerrarEncaminhamentoNAAPACommand.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/EncerrarEncaminhamentoNAAPA/EncerrarEncaminhamentoNAAPACommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IEncerrarEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Dados/Mapeamentos/EncaminhamentoNAAPAMap.cs, src/SME.SGP.Dominio/Entidades/EncaminhamentoNAAPA.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/EncaminhamentoNAAPARespostaDto.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/EncerramentoEncaminhamentoDto.cs, src/SME.SGP.IoC/RegistrarDependencias.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_encerrar_encaminhamento_editar_para_encerramento.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_obter_encaminhamento.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs, teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#85860](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85860)
=> Criação do endpoint de encerramento, criação do campo na base e testes de integração

src/SME.SGP.Aplicacao/CasosDeUso/PendenciaCalendarioUe/ExcluirPendenciaCalendarioAnoAnteriorCalendarioPoUeUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PendenciaCalendarioUe/ExcluirPendenciaCalendarioAnoAnteriorCalendarioUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PendenciaCalendarioUe/RemoverPendenciasCalendarioNoFinalDoAnoLetivoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PendenciaCalendarioUe/IExcluirPendenciaCalendarioAnoAnteriorCalendarioPoUeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PendenciaCalendarioUe/IExcluirPendenciaCalendarioAnoAnteriorCalendarioUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PendenciaCalendarioUe/IRemoverPendenciasCalendarioNoFinalDoAnoLetivoUseCase.cs, src/SME.SGP.Aplicacao/Queries/PendenciaCalendarioUe/ObterPendenciasCalendarioUeEAnoLetivoParaEncerramentoAutomatico/ObterPendenciasCalendarioUeEAnoLetivoParaEncerramentoAutomaticoQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaCalendarioUe/ObterPendenciasCalendarioUeEAnoLetivoParaEncerramentoAutomatico/ObterPendenciasCalendarioUeEAnoLetivoParaEncerramentoAutomaticoQueryHandler.cs, src/SME.SGP.Aplicacao/SME.SGP.Aplicacao.csproj, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaCalendarioUe.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaCalendarioUe.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpPendencias.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarPendenciasUseCaseRabbitSgp.cs, src/SME.SGP.Pendencias.Worker/WorkerRabbitPendencias.cs
[AB#61884](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61884)
=> Criar worker para remover pendências - Tipo Calendário

src/SME.SGP.Api/Controllers/PlanoAulaController.cs, src/SME.SGP.Aplicacao/Commands/PlanoAula/MigrarPlanoAula/MigrarPlanoAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAula.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasPlanoAula.cs
[AB#86250](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86250)
=> Tratar código de componentes do território do saber ao copiar plano aula.

src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosPorCodigoEolNome/ObterAlunosPorCodigoEolNomeQueryHandler.cs, src/SME.SGP.Infra/Dtos/AlunoSimplesDto.cs
[AB#86832](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86832)
=> MASTER BACK - fix/86832

src/SME.SGP.Api/Controllers/FrequenciaAcompanhamentoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaDiariaAlunoUseCase.cs, src/SME.SGP.Aplicacao/Queries/FrequenciaDiariaAluno/ObterFrequenciaDiariaAlunoQuery.cs, src/SME.SGP.Aplicacao/Queries/FrequenciaDiariaAluno/ObterFrequenciaDiariaAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaDiariaAluno.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaDiariaAluno.cs, src/SME.SGP.Infra/Dtos/Frequencia/FiltroFrequenciaDiariaAlunoDto.cs, teste/SME.SGP.TesteIntegracao/Frequencia/FrequenciaDiariaAlunoTeste.cs
[AB#87059](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87059)
=> fix/87059 -> r2

src/SME.SGP.Api/Controllers/FrequenciaAcompanhamentoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaDiariaAlunoUseCase.cs, src/SME.SGP.Aplicacao/Queries/FrequenciaDiariaAluno/ObterFrequenciaDiariaAlunoQuery.cs, src/SME.SGP.Aplicacao/Queries/FrequenciaDiariaAluno/ObterFrequenciaDiariaAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaDiariaAluno.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaDiariaAluno.cs, src/SME.SGP.Infra/Dtos/Frequencia/FiltroFrequenciaDiariaAlunoDto.cs, teste/SME.SGP.TesteIntegracao/Frequencia/FrequenciaDiariaAlunoTeste.cs
[AB#87059](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87059)
=> fix/87059 -> master

src/SME.SGP.Dominio/Entidades/PendenciaRegistroIndividual.cs, src/SME.SGP.Infra/Dtos/Pendencia/FiltroRemoverPendenciaFinalAnoLetivoDto.cs, teste/SME.SGP.TesteIntegracao/PendenciaGeral/Ao_remover_pendencia_diario_classe_final_do_ano_letivo.cs, teste/SME.SGP.TesteIntegracao/PendenciaGeral/ServicosFake/PublicarFilaSgpCommandHandlerFakeRemoverPendencia.cs
[AB#79272](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/79272)
=> 79272 - Criar os comands de exclusão de pendências por assunto

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs
[AB#86237](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86237)
=> Corrigindo erro interno ao obter dados das aulas.

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoComponentePorTurmas/ObterFrequenciasAlunoComponentePorTurmasQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs, src/SME.SGP.Infra/Dtos/AulasPrevistas/TurmaComponenteQntAulasDto.cs, teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasPlanoAulaTeste.cs
[AB#85581](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85581)
=> Fix/85581 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs
[AB#87156](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87156)
=> fix/87156 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoComponentePorTurmas/ObterFrequenciasAlunoComponentePorTurmasQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs, src/SME.SGP.Infra/Dtos/AulasPrevistas/TurmaComponenteQntAulasDto.cs, teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasPlanoAulaTeste.cs
[AB#85581](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85581)
=> fix/85581 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs
[AB#87156](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87156)
=> fix/87156 -> master

teste/SME.SGP.TesteIntegracao/PendenciaFechamento/Base/PendenciaFechamentoBase.cs, teste/SME.SGP.TesteIntegracao/PendenciaFechamento/ServicosFakes/ObterProfessoresTitularesDasTurmasQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/PendenciaFechamento/ServicosFakes/ProfessoresTurmaDisciplinaQueryHandlerFakeProfessorPortugues.cs
[AB#76390](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76390)
=> 76390 - Criação da base de testes

src/SME.SGP.Aplicacao/Commands/Fechamento/GerarPendenciasFechamento/GerarPendenciasFechamentoCommandHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs, src/SME.SGP.Dominio/Entidades/PendenciaFechamento.cs, teste/SME.SGP.TesteIntegracao/PendenciaFechamento/Ao_gerar_pendencia_fechamento_plano_aula.cs
=> 76389 - Pendência de plano de aula

src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs, src/SME.SGP.Infra/Dtos/ComponenteCurricular/ComponenteCurricularTipoDto.cs
[AB#87165](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87165)
=> fix/87165 -> r2

scripts/V608__CRIACAO_TABELA_PENDENCIA_FECHAMENTO_AULA.sql, src/SME.SGP.Aplicacao/Commands/PendenciaFechamentoAula/SalvarPendenciaFechamentoAula/PendenciaFechamentoAulaCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciaFechamentoAula/SalvarPendenciaFechamentoAula/PendenciaFechamentoAulaCommandHandler.cs, src/SME.SGP.Dados/Mapeamentos/PendenciaFechamentoAulaMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaFechamentoAula.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaFechamentoAula.cs, src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs, src/SME.SGP.Dominio/Entidades/PendenciaFechamentoAula.cs, src/SME.SGP.IoC/RegistrarDependencias.cs, teste/SME.SGP.TesteIntegracao/PendenciaFechamento/Ao_salvar_pendencia_fechamento_aula.cs, teste/SME.SGP.TesteIntegracao/PendenciaFechamento/Base/PendenciaFechamentoBase.cs
[AB#87250](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87250)
=> 87250 - Criação tabela e repositório pendencia_fechamento_aula

src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs, src/SME.SGP.Infra/Dtos/ComponenteCurricular/ComponenteCurricularTipoDto.cs
[AB#87165](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87165)
=> Fix/87165 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverPendenciasCalendarioNoFinalDoAnoLetivoUseCase.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_gerar_parecer_conclusivo.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_validar_situacao_do_parecer_conclusivo.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/ServicosFakes/ObterDisciplinasPorCodigoTurmaQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/ExcluirTurmaExtinta/Excluir_turma_extinta.cs, teste/SME.SGP.TesteIntegracao/ExcluirTurmaExtinta/ServicosFakes/ObterTurmaEOLParaSyncEstruturaInstitucionalPorTurmaIdQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Ao_obter_frequencia_geral_de_aluno.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Base/FrequenciaTesteBase.cs, teste/SME.SGP.TesteIntegracao/Frequencia/ServicosFakes/ObterDisciplinasPorCodigoTurmaQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/NotaFechamentoBimestre/Ao_gerar_pendencia.cs, teste/SME.SGP.TesteIntegracao/NotaFechamentoFinal/Ao_obter_nota.cs, teste/SME.SGP.TesteIntegracao/NotaFechamentoFinal/Base/NotaFechamentoTesteBase.cs
[AB#87350](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87350)
=> Correção dos Testes de Integração de Release

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Aulas/ValidarComponentesDoProfessor/ValidarComponentesDoProfessorCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdQuery/ObterPendenciasAulaPorAulaIdQueryHandler.cs
[AB#87297](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87297)
=> fix/87297 -> r2

src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
[AB#87422](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87422)
=> Ajuste para obter componentes de usuários CJ

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Aulas/ValidarComponentesDoProfessor/ValidarComponentesDoProfessorCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdQuery/ObterPendenciasAulaPorAulaIdQueryHandler.cs
[AB#87297](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87297)
=> Fix/87297 -> master

src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
[AB#87346](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87346)
=> Substituir erro interno por mensagem informativa.

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
[AB#87733](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87733)
=> Ajustes para obter detalhes da aula

src/SME.SGP.Aplicacao/Commands/Fechamento/AtualizarCacheFechamentoNota/AtualizarCacheFechamentoNotaCommand.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/AtualizarCacheFechamentoNota/AtualizarCacheFechamentoNotaCommandHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs, teste/SME.SGP.TesteIntegracao/NotaFechamentoFinal/Ao_atualizar_cache_fechamento_nota.cs
[AB#87727](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87727)
=> 87727 - Cache não é atualizado após aprovação

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
[AB#87733](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87733)
=> fix/87733 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs
[AB#87735](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87735)
=> Corrigindo a verificação de aulas para visualizar, quando não há aulas.

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasPorPeriodoUseCase.cs
[AB#87634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87634)
=> Obter aulas para registro de frequência na tela do listão.

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/PendenciaAulaFechamentoUseCase.cs, src/SME.SGP.Aplicacao/Commands/PendenciaAula/ExcluirPendenciasAulaDiarioClasseFechamento/ExcluirPendenciasAulaDiarioClasseFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterAulasPendenciaSemFechamentoTurmaDiscplinaProcessado/ObterAulasPendenciaSemFechamentoTurmaDiscplinaProcessadoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAtividadeAvaliativa/ObterPendenciasAtividadeAvaliativaQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAtividadeAvaliativa/ObterPendenciasAtividadeAvaliativaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAulasPorTipo/ObterPendenciasAulasPorTipoQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAulasPorTipo/ObterPendenciasAulasPorTipoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarFechamentoEmAberto/ObterPeriodoEscolarFechamentoEmAbertoQuery.cs, src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarFechamentoEmAberto/ObterPeriodoEscolarFechamentoEmAbertoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEventoFechamentoConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEventoFechamentoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs
[AB#87764](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87764)
[AB#87767](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87767)
=> Não gerou pendência de diário de classe para plano de aula

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaDiariaAluno.cs
[AB#87765](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87765)
=> fix/87765 -> r2

src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
[AB#87901](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87901)
=> Obter aulas a partir da tela de diário bordo

src/SME.SGP.Aplicacao/CasosDeUso/Aula/ExcluirAulaUseCase.cs
[AB#87978](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87978)
=> Ajustes nos testes de exclusão de aula.

src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaFechamento/ObterTurmaDaPendenciaFechamentoCompleto/ObterTurmaDaPendenciaFechamentoCompletoQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaFechamento/ObterTurmaDaPendenciaFechamentoCompleto/ObterTurmaDaPendenciaFechamentoCompletoQueryHandler.cs
[AB#87897](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87897)
=> Obter bimestre pelo fechamento da turma e não pela data de criação pendência de fechamento

src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
[AB#87874](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87874)
=> 87874 - Pendência de Plano de Aula não está sendo resolvida

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaDiariaAluno.cs
[AB#87765](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87765)
=> fix/87765 -> master

scripts/V611__EXCLUIR_NOTIFICACOES_INCORRETAS_ALUNOS_EXCESSO_FALTA.sql, src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
[AB#87850](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87850)
=> fix/87850 -> r2

scripts/V611__EXCLUIR_NOTIFICACOES_INCORRETAS_ALUNOS_EXCESSO_FALTA.sql, src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
[AB#87850](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87850)
=> fix/87850 -> master

src/SME.SGP.Api/Controllers/RelatorioController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/EncaminhamentoNaapa/RelatorioEncaminhamentoNaapaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IRelatorioEncaminhamentoNaapaUseCase.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs, src/SME.SGP.Infra/Dtos/Relatorios/EncaminhamentoNaapa/FiltroRelatorioEncaminhamentoNaapaDto.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpRelatorios.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#87563](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87563)
=> API SGP - End Point Solicitação Relatório

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterDetalhamentoFechamentoConselhoClasseAlunoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterFechamentoConselhoClasseAlunosPorTurmaUseCase.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs
[AB#88110](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88110)
=> fix/88110 -> master

src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#88301](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88301)
=> Tratar anos nulos na recuperação de turmas

src/SME.SGP.Aplicacao/CasosDeUso/Aula/ExcluirAulaUseCase.cs
[AB#88373](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88373)
=> Tratar componentes sem pai para exclusão de aulas.

src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#88401](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88401)
=> 88401 - Permissão Relatório NAAPA SGP

src/SME.SGP.Aplicacao/Consultas/ConsultaAtividadeAvaliativa.cs, src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterAbrangenciaTurmasCPParaCopiaAvaliacao/ObterAbrangenciaTurmasCPParaCopiaAvaliacaoQuery.cs, src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterAbrangenciaTurmasCPParaCopiaAvaliacao/ObterAbrangenciaTurmasCPParaCopiaAvaliacaoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAbrangencia.cs, src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#86274](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86274)
=> fix/86274 -> r2

src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaFechamento.cs
[AB#88465](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88465)
=> Erro interno ao logar com o Professor RF: 6781799 e carregar a área de notificações

src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs
[AB#88126](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88126)
=> Desconsiderar planos excluídos

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaFechamentoComponenteUseCase.cs
[AB#88123](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88123)
=> fix/88123 -> r2

src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoParecerConclusivo/NotificacaoNotaFechamentoCommandBase.cs
[AB#88481](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88481)
=> Realizado o agrupamento de componentes para notas conceito

src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoParecerConclusivo/NotificacaoNotaFechamentoCommandBase.cs, src/SME.SGP.Dados/Repositorios/RepositorioWfAprovacaoNotaFechamento.cs, src/SME.SGP.Infra/Dtos/FechamentoNota/WfAprovacaoNotaFechamentoTurmaDto.cs, teste/SME.SGP.TesteIntegracao/NotaFechamentoBimestre/ServicosFakes/ObterAlunosEolPorCodigosEAnoQueryHandlerFake.cs
[AB#88481](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88481)
=> Correção da busca de alunos para exibição das alterações de notas cceitos e numéricas

scripts/V614__INSERIR_TIPOS_CICLOS_ANOS_TURMAS_NAO_NUMERICAS_EM.sql
=> fix/88274 -> r2

src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs
[AB#88377](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88377)
=> Objetivos de aprendizagem não permite cadastrar o plano

src/SME.SGP.Aplicacao/Commands/DiarioBordo/InserirDiarioBordo/InserirDiarioBordoCommandHandler.cs
[AB#88628](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88628)
=> 88628 correção passando os parametros faltantes para o objeto

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/HistoricoEscolar/HistoricoEscolarUseCase.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
Ajuste no tipo de relatório de histórico escolar para não considerar jasper para o fundamental.
=> Ajuste no tipo de relatório de histórico.

src/SME.SGP.Aplicacao/Consultas/ConsultaAtividadeAvaliativa.cs, src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterAbrangenciaTurmasCPParaCopiaAvaliacao/ObterAbrangenciaTurmasCPParaCopiaAvaliacaoQuery.cs, src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterAbrangenciaTurmasCPParaCopiaAvaliacao/ObterAbrangenciaTurmasCPParaCopiaAvaliacaoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAbrangencia.cs, src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#86274](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/86274)
=> fix/86274 -> master

src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoDevolutivas/ConsolidarDevolutivasPorTurmaInfantilUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoDevolutivas/ConsolidarDevolutivasPorUeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConsolidacaoDevolutivas/IConsolidarDevolutivasPorUeUseCase.cs, src/SME.SGP.Aplicacao/Queries/Devolutiva/ObterTurmasComDevolutivaPorModalidadeInfantilEAno/ObterTurmasComDevolutivaPorModalidadeInfantilEAnoQuery.cs, src/SME.SGP.Aplicacao/Queries/Devolutiva/ObterTurmasComDevolutivaPorModalidadeInfantilEAno/ObterTurmasComDevolutivaPorModalidadeInfantilEAnoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUEsPorModalidadeCalendario/ObterUEsPorModalidadeCalendarioQuery.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUEsPorModalidadeCalendario/ObterUEsPorModalidadeCalendarioQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUesIdsPorModalidadeCalendario/ObterUesIdsPorModalidadeCalendarioQuery.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUesIdsPorModalidadeCalendario/ObterUesIdsPorModalidadeCalendarioQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioDevolutiva.cs, src/SME.SGP.Dados/Repositorios/RepositorioUeConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDevolutiva.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioUeConsulta.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgp.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarUseCaseRabbitSgp.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#88323](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88323)
=> 88323 correção timeout consolidação devolutivas

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaFechamentoComponenteUseCase.cs
[AB#88123](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88123)
=> fix/88123 pt.2 -> r2

src/SME.SGP.Aplicacao/Commands/DiarioBordo/InserirDiarioBordo/InserirDiarioBordoCommandHandler.cs
[AB#88628](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88628)
=> Fix/88628 -> master

src/SME.SGP.Infra/Dtos/AbrangenciaUeRetorno.cs
[AB#88651](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88651)
=> fix/88651 -> r2 

src/SME.SGP.Api/Controllers/AbrangenciaController.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasAbrangencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAbrangencia.cs
[AB#88607](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88607)
=> Filtro do relatório não traz ano corretamente

src/SME.SGP.Infra/Dtos/AbrangenciaUeRetorno.cs
[AB#88651](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88651)
=> fix/88651 -> master

src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#88552](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88552)
=> Usuários com perfil CJ só visualizam aulas CJ no calendário.

src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
[AB#88901](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88901)
=> Texto e título da notificação do relatório não está completa de acordo com o sugerido na história

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/EncaminhamentoNAAPA/RelatorioEncaminhamentoNAAPAUseCase.cs, src/SME.SGP.Aplicacao/Commands/Relatorios/GerarRelatorio/GerarRelatorioCommand.cs, src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#88995](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88995)
=> Corrigindo quando usuário logado não tem CodigoRf

src/SME.SGP.Aplicacao/Commands/ConsolidacaoConselhoClasse/ConsolidarTurmaConselhoClasseAluno/ConsolidarTurmaConselhoClasseAlunoCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#89008](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89008)
=> Ajustando a tela de conselho de classe para obter os dados das disciplinas.

src/SME.SGP.Dados/Repositorios/RepositorioNotasConceitosConsulta.cs
[AB#88617](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88617)
=> Label de "Aguardando Aprovação" no Listão aplicado para todos os alunos

src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/AtividadeAvaliativaPorTurma/AtualizaCacheDeAtividadeAvaliativaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/NotaConceito/SalvarListaNotaConceito/SalvarListaNotaConceitoCommand.cs, src/SME.SGP.Aplicacao/Commands/NotaConceito/SalvarListaNotaConceito/SalvarListaNotaConceitoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioDevolutiva.cs, src/SME.SGP.Dados/Repositorios/RepositorioNotasConceitos.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotasConceitos.cs, src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs, src/SME.SGP.Infra/Dtos/AbrangenciaUeRetorno.cs
[AB#88797](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88797)
=> Fix/88797 -> r2

src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
[AB#89119](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89119)
=> 89119 - Ajuste nota nula em aprovação/recusa nota final fechamento

src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
[AB#89164](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89164)
=> Título e corpo do texto da notificação não está de acordo com o sugerido

src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
[AB#89047](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89047)
=> Notas incorretas na notificação quando regente de classe altera nota final pelo Listão

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
Inclusão de validação de objeto nulo.
=> Bug: 86555

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs
=> Bug: 88689

src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
[AB#89218](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89218)
=> 89218 - Ajuste na msg de aprovação em 24 hroas erroneamente para CP

src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
=> 89142 - Ajustes listão sobre wf aprovação nota fechamento

src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
[AB#89273](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89273)
=> Correção do histórico de notas quando realiza aprovação

src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
[AB#88901](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88901)
=> Correção na descrição e nome do Relátorio

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs
[AB#89150](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89150)
=> fix/89150 -> r2  : retirando lista não utilizada no retorno de disciplinas

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUsuarioECodigoTurma/ObterComponentesCurricularesPorUsuarioECodigoTurmaQueryHandler.cs
Ajuste na funcionalidade para obter informações do filtro do relatório de acompanhamento diário.
=> Bug: 89303

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterDisciplinasTurmasEol/ObterDisciplinasTurmasEolQueryHandler.cs
[AB#89313](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89313)
=> Fix/89313 ->r2

src/SME.SGP.Aplicacao/CasosDeUso/Aula/ExcluirAulaUseCase.cs, src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#89297](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89297)
[AB#89335](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89335)
Obter componentes para exclusão de aulas e tratamento para visualização de aulas pelo professor.
=> Correção para os bugs 89297 e 89335.

src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs, src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
[AB#89325](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89325)
=> Correção do usuário do histórico de notas

src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/AtividadeAvaliativaPorTurma/AtualizaCacheDeAtividadeAvaliativaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/NotaConceito/SalvarListaNotaConceito/SalvarListaNotaConceitoCommand.cs, src/SME.SGP.Aplicacao/Commands/NotaConceito/SalvarListaNotaConceito/SalvarListaNotaConceitoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioNotasConceitos.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotasConceitos.cs, src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs
[AB#88797](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88797)
=> Fix/88797 -> master

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterDisciplinasTurmasEol/ObterDisciplinasTurmasEolQueryHandler.cs
[AB#89313](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89313)
=> ajustes testes em r2

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterDisciplinasTurmasEol/ObterDisciplinasTurmasEolQueryHandler.cs
[AB#89313](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89313)
=> Fix/89313 -> master

src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs
[AB#88641](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88641)
=> Fix/88641 -> r2

src/SME.SGP.Aplicacao/Comandos/ComandosAtividadeAvaliativa.cs, src/SME.SGP.Aplicacao/Consultas/ConsultaAtividadeAvaliativa.cs
[AB#88659](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88659)
=> Correção para permitir a cópia de avaliações para usuários CP

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs
[AB#88182](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88182)
=> fix/88182 -> r2

src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs
[AB#88641](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88641)
=> fix/88641 -> master

src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#88952](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88952)
=> criado permissão no menu sgp

src/SME.SGP.Api/Controllers/RelatorioAnaliticoSondagemController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Sondagem/RelatorioAnaliticoSondagemUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/IRelatorioAnaliticoSondagemUseCase.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs, src/SME.SGP.Dominio/Enumerados/TipoSondagem.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioAnaliticoSondagemDto.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpRelatorios.cs
[AB#88954](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88954)
=> 88954 - Emissão relatório - EndPoint

src/SME.SGP.Aplicacao/Commands/DeletarArquivo/RemoverArquivosExcluidosCommandHandler.cs
[AB#89491](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89491)
=> fix/89491 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs
[AB#88182](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88182)
=> fix/88182 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterAnosLetivosItineranciaUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs
[AB#88684](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88684)
=> Ordenando o retorno dos anos de forma decrescente.

src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAnualTerritorioSaber.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAnualTerritorioSaber.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAnualTerritorioSaber.cs
[AB#89482](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89482)
=> Tratamento para planejamentos com códigos dos territórios antigos e novos.

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#88708](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88708)
=> fix/88708 -> master

src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#88098](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88098)
=> fix/88098 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/AlterarItineranciaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/SalvarItineranciaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/CriarEventoItineranciaPAAI/CriarEventoItineranciaPAAICommand.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/Notificacao/AprovarItinerancia/AprovarItineranciaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/Notificacao/NotificacaoRegistroItineranciaRecusado/NotificacaoRegistroItineranciaRecusadoCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioItinerancia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioItinerancia.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaNomeDescricaoDto.cs
[AB#88598](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88598)
=> Correção no fluxo de aprovação - reprovação de registros de itinerância.

src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaUnica/AlterarAulaUnicaCommandHandler.cs
[AB#88532](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88532)
=> Verificar aula CJ já existente, quando usuário estiver com perfil CJ.

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterDisciplinasTurmasEol/ObterDisciplinasTurmasEolQueryHandler.cs
[AB#89660](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89660)
=> fix/89660 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs
[AB#87974](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87974)
=> Fix/87974 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterDisciplinasTurmasEol/ObterDisciplinasTurmasEolQueryHandler.cs
[AB#89660](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89660)
=> fix/89660 -> master

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs
[AB#87974](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87974)
=> Fix/87974 -> master

src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
=> Fix/89697 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
=> Correção dos testes

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#89634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89634)
=> Ajustes para tratar disciplinas do território.

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#89634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89634)
=> Corrigindo código do território para professor.

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
=> Complemento das correções do território

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
[AB#89742](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89742)
=> Fix/89742 -> r2

src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#89716](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89716)
=> fix/89716 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterInformacoesDeFrequenciaAlunoPorSemestreUseCase.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaAlunosComAusencia/ObterListaAlunosComAusenciaQueryHandler.cs, src/SME.SGP.Infra/Dtos/AcompanhamentoFrequencia/FrequenciaAlunoBimestreDto.cs, src/SME.SGP.Infra/Dtos/AlunoAusenteDto.cs
[AB#89289](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89289)
=> 89289 - Ajuste retorno de frequencia com tipo string formatado 2 casas

src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
=> fix/89697 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
[AB#89742](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89742)
=> fix/89742 -> master

src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#89716](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89716)
=> fix/89716 -> master

src/SME.SGP.Infra/Enumerados/Permissao.cs
=> Correção no nome do Menu

src/SME.SGP.Api/Controllers/RelatorioAnaliticoSondagemController.cs
[AB#88604](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88604)
=> API SGP - Story/88604

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
[AB#89371](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89371)
=> Correção da busca de anos para supervisor

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ObterEncaminhamentoNAAPAPorIdUseCase.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/AlterarSituacaoNAAPA/AlterarSituacaoNAAPACommand.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/AlterarSituacaoNAAPA/AlterarSituacaoNAAPACommandHandler.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/VerificaSituacaoEncaminhamentoNAAPASeEstaAguardandoAtendimentoIndevidamente/VerificaSituacaoEncaminhamentoNAAPASeEstaAguardandoAtendimentoIndevidamenteQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/VerificaSituacaoEncaminhamentoNAAPASeEstaAguardandoAtendimentoIndevidamente/VerificaSituacaoEncaminhamentoNAAPASeEstaAguardandoAtendimentoIndevidamenteQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoNAAPA.cs
[AB#89879](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89879)
=> Fix/89879 -> r2

src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#89634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89634)
=> Visualizar aulas por professores com atribuição no componente do território

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterComponentesCurricularesPorUeAnosModalidadeUseCase/ObterComponentesCurricularesPorUeAnosModalidadeUseCase.cs
[AB#89371](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89371)
=> Correção da busca de componentes curriculares

src/SME.SGP.AEE.Worker/WorkerRabbitAEE.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IEncerrarPlanosAEEEstudantesInativosTratarUseCase.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpAEE.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarAEEUseCaseRabbitSgp.cs
[AB#87974](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87974)
=> fix/87974 pt.2 -> r2

teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_encerrar_automaticamente.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Base/PlanoAEETesteBase.cs
=> fix 87974 ajuste nos testes 

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
[AB#89648](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89648)
=> Trata duplicidades de componentes do enriquecimento curricular.

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasPorPeriodoUseCase.cs
[AB#89744](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89744)
=> Correção para obter aulas pela disciplina

src/SME.SGP.AEE.Worker/WorkerRabbitAEE.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IEncerrarPlanosAEEEstudantesInativosTratarUseCase.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpAEE.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarAEEUseCaseRabbitSgp.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_encerrar_automaticamente.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Base/PlanoAEETesteBase.cs
[AB#87974](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87974)
=> Fix/87974 pt.2 ->  master

src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
[AB#89816](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89816)
=> Obter código do território do saber para professor CJ

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesUseCase.cs
[AB#90040](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90040)
=> Obter componentes de usuários não CJ para visualização de aulas do calendário

src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/SalvarAnotacaoFrequenciaAlunoUseCase.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEol/ObterAlunoPorCodigoEolQuery.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEol/ObterAlunoPorCodigoEolQueryHandler.cs, src/SME.SGP.Dominio/Entidades/Turma.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/SalvarAnotacaoFrequenciaAlunoUseCaseTeste.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Ao_inserir_frequencia_com_inconsistencias.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Ao_realizar_lancamento_de_justificativa.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Base/FrequenciaTesteBase.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
[AB#90048](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90048)
=> Fix/90048 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Sondagem/RelatorioAnaliticoSondagemUseCase.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioAnaliticoSondagemDto.cs
[AB#90353](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90353)
=> API SGP - O numero total da turma está vindo incorreto no relatório do Excel

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#90456](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90456)
=> Adição das turmas de programa na consulta de frequência geral

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasPorPeriodoUseCase.cs
[AB#89816](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89816)
=> Verificar se aulas com os dois tipos de código do território.

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterDetalhamentoFechamentoConselhoClasseAlunoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasCompensacaoAusencia.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasRecuperacaoParalela.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAluno/ObterFrequenciaGeralAlunoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmaEComponente/ObterFrequenciaGeralAlunoPorTurmaEComponenteQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaFrequenciaAulas/ObterListaFrequenciaAulasQueryHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs, src/SME.SGP.Dominio/Entidades/FrequenciaAluno.cs
[AB#90534](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90534)
=> Removendo 100% quando não tem frequencia

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#90512](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90512)
=> Fix/90512 -> master

teste/SME.SGP.TesteIntegracao/Frequencia/Ao_obter_lista_de_alunos_ausentes.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Base/FrequenciaTesteBase.cs
[AB#89816](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89816)
=> Refact teste frequência - Deve_obter_lista_de_alunos_ausentes

teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_encerrar_automaticamente.cs
=> ajustes testes de integração - plano aee encerrados automaticamente

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
[AB#90567](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90567)
=> Correção da porcentagem da frequência

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
[AB#90119](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90119)
=> Fix/90119 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/SalvarAnotacaoFrequenciaAlunoUseCase.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEol/ObterAlunoPorCodigoEolQuery.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEol/ObterAlunoPorCodigoEolQueryHandler.cs, src/SME.SGP.Dominio/Entidades/Turma.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/SalvarAnotacaoFrequenciaAlunoUseCaseTeste.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Ao_inserir_frequencia_com_inconsistencias.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Ao_realizar_lancamento_de_justificativa.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Base/FrequenciaTesteBase.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
[AB#90048](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90048)
=> Fix/90048 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
[AB#90567](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90567)
=> Correção da frequência quando não tem frequência no componente/bimestre

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#90657](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90657)
=> Ajustando para que a frequência global do aluno contemple outras turmas

src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#90429](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90429)
=> Visualizar aulas cadastradas com os dois tipos de código de território pelo professor.

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs
[AB#90452](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90452)
=> Exibir nome componente infantil na tela de atribuição CJ

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs
[AB#90543](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90543)
=> fix/90543 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasPorPeriodoUseCase.cs
Ajuste na funcionalidade para obter dados do listão, tratando quando o componente de regência não tem o código pai.
=> Bug: 90868

src/SME.SGP.Aplicacao/CasosDeUso/Aula/ExcluirAulaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAnualTerritorioSaber.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdQuery/ObterPendenciasAulaPorAulaIdQueryHandler.cs
[AB#90908](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90908)
=> fix/90908 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
[AB#90119](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90119)
=> Fix/90119 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Aula/ExcluirAulaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAnualTerritorioSaber.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdQuery/ObterPendenciasAulaPorAulaIdQueryHandler.cs
[AB#90908](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90908)
=> fix/90908 -> master

src/SME.SGP.Aplicacao/CasosDeUso/ListaoAvaliacoes/ObterNotasParaAvaliacoesListaoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs, teste/SME.SGP.TesteIntegracao/NotaFechamentoBimestre/Ao_lancar_nota_ano_anterior.cs, teste/SME.SGP.TesteIntegracao/NotaFechamentoBimestre/Ao_validar_exibicao_alunos.cs
[AB#89759](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89759)
=> Fix/89759 -> r2

src/SME.SGP.Aplicacao/Commands/SincronizacaoInstituicional/Turmas/TrataSincronizacaoInstitucionalTurma/TrataSincronizacaoInstitucionalTurmaCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurma.cs
[AB#90907](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90907)
=> Verifica se necessário atualizar a modalidade da turma, com base no EOL, para sinc. institucional.

scripts/V617__ALTERAR_VIEW_V_ABRANGENCIA.sql
[AB#89483](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89483)
=> Altera view v_abrangencia para não recuperar turmas que não esteja na abrangência do usuário.

src/SME.SGP.Aplicacao/CasosDeUso/ListaoAvaliacoes/ObterNotasParaAvaliacoesListaoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs, teste/SME.SGP.TesteIntegracao/NotaFechamentoBimestre/Ao_lancar_nota_ano_anterior.cs, teste/SME.SGP.TesteIntegracao/NotaFechamentoBimestre/Ao_validar_exibicao_alunos.cs
[AB#89759](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89759)
=> Fix/89759 -> master

src/SME.SGP.Api/Controllers/FrequenciaAcompanhamentoController.cs, src/SME.SGP.Api/Controllers/FrequenciaController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFaltasNaoCompensadaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Frequencia/IObterFaltasNaoCompensadaUseCase.cs, src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterAusenciaParaCompensacao/ObterAusenciaParaCompensacaoQuery.cs, src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterAusenciaParaCompensacao/ObterAusenciaParaCompensacaoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusencia.cs, src/SME.SGP.Infra/Dtos/Frequencia/FiltroFaltasNaoCompensadasDto.cs, src/SME.SGP.Infra/Dtos/Frequencia/RegistroFaltasNaoCompensadaDto.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#89253](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89253)
[AB#91076](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91076)
=> faltas a serem compensadas

src/SME.SGP.Aplicacao/Consultas/ConsultasCompensacaoAusencia.cs, src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterAusenciaParaCompensacaoPorAlunos/ObterAusenciaParaCompensacaoPorAlunosQuery.cs, src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterAusenciaParaCompensacaoPorAlunos/ObterAusenciaParaCompensacaoPorAlunosQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusencia.cs, src/SME.SGP.Infra/Dtos/AlunoAusenteDto.cs, src/SME.SGP.Infra/Dtos/CompensacaoAusencia/CompensacaoDataAlunoDto.cs
[AB#89300](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89300)
=> Alteração endpoint de consulta de compensação na edição

src/SME.SGP.Aplicacao/Queries/ComponenteCurricular/ObterComponenteCurricularGrupoMatrizPorComponenteId/ObterComponenteCurricularGrupoMatrizPorComponenteIdQuery.cs, src/SME.SGP.Aplicacao/Queries/ComponenteCurricular/ObterComponenteCurricularGrupoMatrizPorComponenteId/ObterComponenteCurricularGrupoMatrizPorComponenteIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioComponenteCurricularConsulta.cs, src/SME.SGP.Infra/Dtos/ComponenteGrupoMatriz/ComponenteGrupoMatrizDto.cs
[AB#90362](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90362)
=> Fix/90362 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterComponentesCurricularesPorUeAnosModalidadeUseCase/ObterComponentesCurricularesPorUeAnosModalidadeUseCase.cs
[AB#89776](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89776)
=> fix/89776 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFaltasNaoCompensadaUseCase.cs, src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterCompensacaoAusenciaPorAnoTurmaENome/ObterCompensacaoAusenciaPorAnoTurmaENomeQuery.cs, src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterCompensacaoAusenciaPorAnoTurmaENome/ObterCompensacaoAusenciaPorAnoTurmaENomeQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusenciaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusenciaConsulta.cs, src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs
[AB#89312](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89312)
O componente não pode ter duas atividades com o mesmo nome
=> O componente não pode ter duas atividades com o mesmo nome - Feature/89312

src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
[AB#90756](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90756)
=> fix/90756 -> r2

src/SME.SGP.Aplicacao/Queries/ComponenteCurricular/ObterComponenteCurricularGrupoMatrizPorComponenteId/ObterComponenteCurricularGrupoMatrizPorComponenteIdQuery.cs, src/SME.SGP.Aplicacao/Queries/ComponenteCurricular/ObterComponenteCurricularGrupoMatrizPorComponenteId/ObterComponenteCurricularGrupoMatrizPorComponenteIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIds/ObterComponentesCurricularesPorIdsQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioComponenteCurricularConsulta.cs, src/SME.SGP.Infra/Dtos/ComponenteGrupoMatriz/ComponenteGrupoMatrizDto.cs
[AB#90362](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90362)
=> fix/90362 -> master

src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaFrequenciaTratar/AlterarAulaFrequenciaTratarCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Aulas/AlterarCompensacaoAusenciaAlunoEAula/AlterarCompensacaoAusenciaAlunoEAulaCommand.cs, src/SME.SGP.Aplicacao/Commands/Aulas/AlterarCompensacaoAusenciaAlunoEAula/AlterarCompensacaoAusenciaAlunoEAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/CompensacaoAusencia/ExcluirCompensacaoAusenciaAlunoAulaPorIds/ExcluirCompensacaoAusenciaAlunoAulaPorIdsCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/CompensacaoAusencia/ExcluirCompensacaoAusenciaAlunoPorId/ExcluirCompensacaoAusenciaAlunoPorIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/ExcluirRegistroFrequenciaAlunoPorId/ExcluirRegistroFrequenciaAlunoPorIdCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterCompensacoesAusenciasAlunoEAulaPorAulaIdEQuantidade/ObterCompensacoesAusenciasAlunoEAulaPorAulaIdEQuantidadeQuery.cs, src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterCompensacoesAusenciasAlunoEAulaPorAulaIdEQuantidade/ObterCompensacoesAusenciasAlunoEAulaPorAulaIdEQuantidadeQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioBase.cs, src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusenciaAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusenciaAlunoAula.cs, src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusenciaAlunoAulaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusenciaAlunoConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioBase.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusenciaAluno.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusenciaAlunoAula.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusenciaAlunoAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusenciaAlunoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroFrequenciaAluno.cs, src/SME.SGP.Infra/Dtos/CompensacaoAusenciaAlunoAulaDto.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_alterar_aula_com_recorrencia.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_alterar_aula_unica.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_excluir_aula_com_recorrencia.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_excluir_aula_unica.cs
[AB#89310](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89310)
=> Alteração de aula e manutenção de compensações

src/SME.SGP.Api/Controllers/ObjetivoAprendizagemController.cs, src/SME.SGP.Aplicacao/CasosDeUso/ObjetivoAprendizagem/ListarObjetivoAprendizagemPorAnoEComponenteCurricularUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ObjetivoAprendizagem/IObterObjetivoAprendizagemPorAnoEComponenteCurricularUseCase.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#90454](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90454)
=> Verificar se a turma é EM para obter ou exigir o objetivos de aprendizagem.

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterComponentesCurricularesPorUeAnosModalidadeUseCase/ObterComponentesCurricularesPorUeAnosModalidadeUseCase.cs
[AB#89776](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89776)
=> fix/89776 -> master

src/SME.SGP.Api/Controllers/ObjetivoAprendizagemController.cs, src/SME.SGP.Aplicacao/CasosDeUso/ObjetivoAprendizagem/ListarObjetivoAprendizagemPorAnoEComponenteCurricularUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ObjetivoAprendizagem/IObterObjetivoAprendizagemPorAnoEComponenteCurricularUseCase.cs
[AB#90454](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90454)
=> Correção dos testes de caso de uso.

src/SME.SGP.Dominio/Enumerados/TipoSondagem.cs
[AB#90009](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90009)
=> 90009 - Adição tipos de relatório Sondagem Matemática

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/GerarPendenciaValidadePlanoAEEUseCase.cs
[AB#90354](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90354)
=> Verificar pendencias existentes antes de gerar novas.

src/SME.SGP.Api/Controllers/CompensacaoAusenciaController.cs, src/SME.SGP.Aplicacao/CasosDeUso/CompensacaoAusencia/ExcluirCompensacaoAusenciaUseCase.cs, src/SME.SGP.Aplicacao/Comandos/ComandosCompensacaoAusencia.cs, src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosCompensacaoAusencia.cs, src/SME.SGP.Dominio.Interfaces/Servicos/IServicoCompensacaoAusencia.cs, src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs, teste/SME.SGP.TesteIntegracao/CompensacaoDeAusencia/Ao_alterar_compensacao_ausencia_pelo_professor_titular.cs, teste/SME.SGP.TesteIntegracao/CompensacaoDeAusencia/Ao_excluir_compensacao_de_ausencia.cs
[AB#89315](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89315)
=> Criado UseCase de ExcluirCompensacaoAusenciaUseCase.cs

src/SME.SGP.Aplicacao/Queries/ComponenteCurricular/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurma/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurmaQueryHandler.cs
Ajuste na definição de componente curricular quando não se trata de território do saber.
=> Bug: 91275

src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
[AB#90756](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90756)
=> Fix/90756 -> master

src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoFrequenciaAluno/ConsolidarFrequenciaAlunoPorTurmaEMesUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs, src/SME.SGP.Infra/Dtos/ConsolidacaoFrequenciaAluno/RegistroFrequenciaAlunoPorTurmaEMesDto.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#89319](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89319)
=> Task 89319: Revisar relatório de frequência mensal

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
[AB#90495](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90495)
=> Fix/90495 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasEventosAulasCalendario.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasDisciplina.cs, src/SME.SGP.Dados/Repositorios/RepositorioAtribuicaoCJ.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtribuicaoCJ.cs, src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs
[AB#91081](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91081)
=> Fix/91081 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#91077](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91077)
=> Visualizar aulas de outros componentes criadas pelo CJ

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#84823](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/84823)
=> Corrigir a verificação de nota em aprovação no conselho de classe

teste/SME.SGP.TesteIntegracao/NotaFechamentoBimestre/Ao_validar_exibicao_alunos.cs
[AB#91077](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91077)
=> Correção dos testes validar exibição de alunos

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_alterar_nota_conceito_pos_conselho_bimestre_final.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_inserir_nota_conceito_pos_conselho_bimestre.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_inserir_nota_conceito_pos_conselho_bimestre_final.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/ServicosFakes/ObterComponentesRegenciaPorAnoQueryHandlerFake.cs
[AB#90495](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90495)
=> Fix/90495 -> master

teste/SME.SGP.TesteIntegracao/NotaFechamentoBimestre/Ao_lancar_nota_ano_anterior.cs
[AB#91077](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91077)
=> Ajustes testes pt2

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
[AB#91523](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91523)
=> Complemento para considerar alunos com duas matrículas.

src/SME.SGP.Aplicacao/Queries/ComponenteCurricular/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurma/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurmaQueryHandler.cs
[AB#90420](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90420)
=> fix/90420 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasWorkflowAprovacao.cs, src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs, src/SME.SGP.Dominio/Entidades/WorkflowAprovacao.cs
[AB#88789](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88789)
=> fix/88789 -> r2

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
[AB#91805](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91805)
=> Correção da atualização do cálculo de frequência por disciplina

scripts/V619__GERAR_COMPENSACAO_AUSENCIA_ALUNO_AULA_2023.sql
[AB#89316](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89316)
=> Gerar as compensações de ausência de aluno aula para 2023

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/GerarPendenciasFechamentoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/GerarPendenciasFechamento/GerarPendenciasFechamentoCommand.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/GerarPendenciasFechamento/GerarPendenciasFechamentoCommandHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs
[AB#90355](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90355)
=> Fix/90355 -> r2

src/SME.SGP.Aplicacao/Commands/Fechamento/IncluirFilaGeracaoPendenciasFechamento/IncluirFilaGeracaoPendenciasFechamentoCommandHandler.cs
[AB#90355](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90355)
=> Fix/90355 Ajuste

src/SME.SGP.Aplicacao/Queries/ComponenteCurricular/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurma/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurmaQueryHandler.cs
Ajuste complementar para o erro ao criar aula e acessar frequência de território do saber.
=> Bug: 89957

src/SME.SGP.Aplicacao/Queries/ComponenteCurricular/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurma/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurmaQueryHandler.cs
[AB#90420](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90420)
=> fix/90420 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#90486](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90486)
=> Fix/90486 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasWorkflowAprovacao.cs, src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs, src/SME.SGP.Dominio/Entidades/WorkflowAprovacao.cs
[AB#88789](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88789)
=> fix/88789 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
[AB#92047](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92047)
=> 92047 - O ícone de anotações do estudante não está habilitando antes do estudante ter ficado inativo na turma

src/SME.SGP.Aplicacao/Consultas/ConsultasCompensacaoAusencia.cs
[AB#89656](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89656)
=> fix/89656 -> master

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
[AB#92079](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92079)
=> 92079 - Pendências exibindo a qtde de páginas superior ao necessário

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs, src/SME.SGP.Aplicacao/Queries/ComponenteCurricular/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurma/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/ComponenteCurricular/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurma/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurmaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Professores/ObterProfessoresTitularesPorTurmaId/ObterProfessoresTitularesPorTurmaIdQueryHandler.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagensNegocioFrequencia.cs
Tela de Frequência - Erro interno ao selecionar um componente território do saber que tem aula criada (Perfil de Gestão da UE) 
[AB#92099](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92099)
[AB#92131](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92131)
=> Erro interno ao selecionar um componente território do saber

src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterAusenciaParaCompensacao/ObterAusenciaParaCompensacaoQueryHandler.cs
[AB#92124](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92124)
=> 92124 - Não carrega a data das aulas dentro da nova modal de compensação para Território do Saber

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/Regencia/ObterComponentesCurricularesRegenciaPorTurmaCodigo/ObterComponentesCurricularesRegenciaPorTurmaCodigoQueryHandler.cs
[AB#92098](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92098)
=> Tratar turmas com anos alfanuméricos.

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs, src/SME.SGP.Infra/Dtos/FechamentoTurmaDisciplinaBimestreDto.cs
[AB#92103](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92103)
=> fix/92103 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#92176](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92176)
=> Não atribuir componentes CJ para usuários CP.

src/SME.SGP.Aplicacao/Commands/Fechamento/GerarPendenciasFechamento/GerarPendenciasFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaAula/ExcluirPendenciasAulaDiarioClasseFechamento/ExcluirPendenciasAulaDiarioClasseFechamentoCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciaAula/ExcluirPendenciasAulaDiarioClasseFechamento/ExcluirPendenciasAulaDiarioClasseFechamentoCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs
[AB#92107](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92107)
=> Tratamento de exclusão de pendência de CJ

src/SME.SGP.Api/Controllers/ConselhoClasseController.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioConselhoClasseAlunoDto.cs
[AB#92160](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92160)
=> 92160 -  Frequência global do estudante está incorreta

teste/SME.SGP.TesteIntegracao/PendenciaFechamento/Ao_gerar_pendencia_fechamento_plano_aula.cs
[AB#92358](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92358)
=> Ao_gerar_pendencia_fechamento_com_plano_aula

src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
[AB#91979](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91979)
=> fix/91979 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs, src/SME.SGP.Infra/Dtos/FechamentoTurmaDisciplinaBimestreDto.cs
[AB#92103](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92103)
=> fix/92103 -> master

scripts/V621__UPDATE_E_DELETE_CLASSIFICACAO_DOCUMENTO_DUPLICADO_CARTA_PEDAGOGICA.sql
[AB#90045](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90045)
=> fix/90045 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/HistoricoEscolar/ExecutarGravarHistoricoEscolarObservacaoUseCase.cs, src/SME.SGP.Aplicacao/Commands/HistoricoEscolar/RemoverHistoricoEscolarObservacao/RemoverHistoricoEscolarObservacaoCommad.cs, src/SME.SGP.Aplicacao/Commands/HistoricoEscolar/RemoverHistoricoEscolarObservacao/RemoverHistoricoEscolarObservacaoCommadHandler.cs
[AB#91456](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91456)
=> 91456 - Ajustar Relatório para receber mais de uma observação e imprimir

src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
[AB#91979](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91979)
=> fix/91979 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
[AB#92212](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92212)
=> fix/92212 -> r2

src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#92356](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92356)
=> Permitir visualizações de aulas pelo professor quando este tem a disciplina

src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/SalvarAnotacaoFrequenciaAlunoUseCase.cs
[AB#92569](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92569)
=> fix/92569 -> r2

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterCodigosComponentesCurricularesRegenciaAulasAutomaticas/ObterCodigosComponentesCurricularesRegenciaAulasAutomaticasQueryHandler.cs
Ajuste complementar para não ocorrer erro de nulo.
=> Bug: 92351

scripts/V621__UPDATE_E_DELETE_CLASSIFICACAO_DOCUMENTO_DUPLICADO_CARTA_PEDAGOGICA.sql
[AB#90045](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90045)
=> fix/90045 -> master

teste/SME.SGP.TesteIntegracao/Frequencia/Ao_realizar_lancamento_de_justificativa.cs, teste/SME.SGP.TesteIntegracao/Frequencia/ServicosFakes/ObterAlunoPorTurmaAlunoCodigoFrequenciaQueryHandlerFake.cs
[AB#92569](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92569)
=> fix/92569 -> r2 (correção de testes de integração)

teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_validar_secao_de_informacoes_escolares.cs, teste/SME.SGP.TesteIntegracao/Listao/Ao_alterar_frequencia.cs
=> Correção dos testes que estavam se baseando em DateTime.Now ao invés de DateTimeExtension.HorarioBrasilia

src/SME.SGP.Dados/Repositorios/RepositorioUsuarioConsulta.cs
=> Fix/Busca usuário

src/SME.SGP.Aplicacao/Queries/ComponenteCurricular/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurma/ObterCodigosComponentesCurricularesTerritorioSaberEquivalentesPorTurmaQueryHandler.cs
Ajuste no cálculo de frequência verificando se o componente é de território para considerar o professor atribuído a disciplina.
=> Bug: 92585

src/SME.SGP.Dados/Repositorios/RepositorioUsuarioConsulta.cs
=> fix/Busca de usuário

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
=> Fix/Calculo frequência

src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/SalvarAnotacaoFrequenciaAlunoUseCase.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Ao_realizar_lancamento_de_justificativa.cs, teste/SME.SGP.TesteIntegracao/Frequencia/ServicosFakes/ObterAlunoPorTurmaAlunoCodigoFrequenciaQueryHandlerFake.cs
[AB#92569](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92569)
=> Fix/92569 ->  master

src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterDadosDashboardFrequenciaPorAnoTurmaUseCase.cs, src/SME.SGP.Dominio/Enumerados/TipoFrequenciaDashboard.cs
[AB#88736](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88736)
=> fix/88736 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioDashBoardFrequencia.cs
[AB#88780](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88780)
=> fix/88780 -> master

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
[AB#92944](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92944)
=> Lentidão conselho - Remoção de consultas não utilizadas

src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterDadosDashboardFrequenciaPorAnoTurmaUseCase.cs, src/SME.SGP.Dominio/Enumerados/TipoFrequenciaDashboard.cs
[AB#88736](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88736)
=> fix/88736 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
[AB#92212](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92212)
=> Fix/92212 -> master

Jenkinsfile, src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterCodigosComponentesCurricularesRegenciaAulasAutomaticas/ObterCodigosComponentesCurricularesRegenciaAulasAutomaticasQueryHandler.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_validar_secao_de_informacoes_escolares.cs, teste/SME.SGP.TesteIntegracao/Frequencia/Ao_obter_frequencia_geral_de_aluno.cs, teste/SME.SGP.TesteIntegracao/Listao/Ao_alterar_frequencia.cs
[AB#92449](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92449)
=> Fix/92449 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterDadosDashboardFrequenciaPorAnoTurmaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/RecalcularFrequenciaPorTurma/RecalcularFrequenciaPorTurmaCommandHandler.cs
[AB#88772](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88772)
=> Executar consolidação dashboard frequência ao excluir aulas

scripts/V622__AJUSTE_FUNCAO_F_OBTERNOTASFECHAMENTOOUCONSELHO.sql, src/SME.SGP.Aplicacao/CasosDeUso/DashboardFechamento/ObterNotasFinaisUseCases.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs, src/SME.SGP.Infra/Dtos/DashboardFechamento/FechamentoConselhoClasseNotaFinalDto.cs
[AB#93065](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93065)
=> Alterar dash notas finais para exibir por ano, caso seja para todas as DREs e UEs
