prefeiturasp/SME-NovoSGP

- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFechamento/ObterNotasFinaisUseCases.cs
[AB#93065](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93065)
> Incluindo a opção de DRE selecionada e UE todas para agrupar por ano

- src/SME.SGP.Dados/Repositorios/RepositorioDashBoardFrequencia.cs
[AB#88743](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88743)
> fix/88743 -> master

- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFechamento/ObterFechamentoSituacaoPorEstudanteUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterTodosAlunosNasTurmas/ObterTodosAlunosNasTurmasQuery.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterTodosAlunosNasTurmas/ObterTodosAlunosNasTurmasQueryHandler.cs
[AB#92966](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92966)
> Fix/92966 -> r2

- src/SME.SGP.Api/Controllers/RelatorioController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Itinerancia/RelatorioListagemItineranciasUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IRelatorioListagemItineranciasUseCase.cs
- src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
- src/SME.SGP.Infra/Dtos/Relatorios/Itinerancias/FiltroRelatorioListagemItineranciasDto.cs
- src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpRelatorios.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#87590](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87590)
> 87590 - Use case e end point solicitação relatório listagem itinerancias

- scripts/V623__CRIACAO_TABELA_ENCAMINHAMENTO_NAAPA_AUDITORIA.sql
- src/SME.SGP.Dados/Mapeamentos/EncaminhamentoNAAPAAuditoriaMap.cs
- src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPAAuditoria.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoNAAPAAuditoria.cs
- src/SME.SGP.Dominio/Entidades/EncaminhamentoNAAPAAuditoria.cs
- src/SME.SGP.Dominio/Enumerados/TipoAuditoriaEncaminhamentoNAAPA.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#85897](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/85897)
> 88919 - Modelagem

- scripts/V624__CRIACAO_TABELA_ENCAMINHAMENTO_NAAPA_OBSERVACAO.sql
- src/SME.SGP.Dados/Mapeamentos/EncaminhamentoNAAPAObservacaoMap.cs
- src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
- src/SME.SGP.Dados/Repositorios/RepositorioObservacaoEncaminhamentoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioObservacaoEncaminhamentoNAAPA.cs
- src/SME.SGP.Dominio/Entidades/EncaminhamentoNAAPAObservacao.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#88926](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88926)
> Observações:  Modelagem (Script DB, Repositório, Entidades e Mapeamento)

- src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIdsUsuarioLogado/ObterComponentesCurricularesPorIdsUsuarioLogadoQueryHandler.cs
[AB#92889](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92889)
> fix/92889 -> r2

- src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIdsUsuarioLogado/ObterComponentesCurricularesPorIdsUsuarioLogadoQueryHandler.cs
[AB#92889](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92889)
> fix/92889 -> master

- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFechamento/ObterFechamentoSituacaoPorEstudanteUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterTodosAlunosNasTurmas/ObterTodosAlunosNasTurmasQuery.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterTodosAlunosNasTurmas/ObterTodosAlunosNasTurmasQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIdsUsuarioLogado/ObterComponentesCurricularesPorIdsUsuarioLogadoQueryHandler.cs
[AB#92523](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92523)
> Fix/92523 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs
[AB#92523](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92523)
> Fix/92523 -> master

- teste/SME.SGP.TesteIntegracao/TurmaEvasaoFrequencia/Ao_obter_frequencia_turma_evasao.cs
[AB#77535](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77535)
> Ajustes nos testes de evasão para a opção acumulado.

- src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoFrequenciaTurma/ConsolidarFrequenciaPorTurmaUseCase.cs
[AB#93485](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93485)
> 93485 Ajuste listagem de alunos e calculo de percentual de frequencia na consolidação

- src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#93497](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93497)
> 93497 - Permissionamento relatório registro itinerancia SGP

- src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/EncaminhamentoNaapa/RelatorioEncaminhamentoNaapaDetalhadoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/RegistrarHistoricoDeAlteracaoDeImpressaoDoEncaminhamentoNAAPA/RegistrarHistoricoDeAlteracaoDeImpressaoDoEncaminhamentoNAAPACommand.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/RegistrarHistoricoDeAlteracaoDeImpressaoDoEncaminhamentoNAAPA/RegistrarHistoricoDeAlteracaoDeImpressaoDoEncaminhamentoNAAPACommandHandler.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_cadastrar_historico_alteracao_encaminhamento_naapa.cs
[AB#88921](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88921)
> 88921 - Gravação de histórico de impressão

- src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs
[AB#77535](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/77535)
> Ajuste para obter o tipo de escola corretamente

- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs
[AB#92523](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92523)
> ajuste fix/92523 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterAulaPorIdUseCase.cs
[AB#93464](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93464)
> fix/93464 -> r2

- src/SME.SGP.Aplicacao/Consultas/ConsultasCompensacaoAusencia.cs
[AB#93363](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93363)
> Verificar se a compensação cadastrada é território.

- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs
[AB#92523](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92523)
> Ajuste Fix/92523 -> master

- src/SME.SGP.Aplicacao/Queries/Ocorrencia/ListarOcorrencias/ListarOcorrenciasQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosModalidadesPorUe/ObterFiltroRelatoriosModalidadesPorUeQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioOcorrencia.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioOcorrencia.cs
- src/SME.SGP.Infra/Dtos/Ocorrencias/Listagens/OcorrenciaListagemDto.cs
- src/SME.SGP.Infra/Dtos/Ocorrencias/Listagens/UesOcorreciaDto.cs
- teste/SME.SGP.TesteIntegracao/Ocorrencia/Ao_filtrar_ocorrencia.cs
- teste/SME.SGP.TesteIntegracao/Ocorrencia/ServicosFakes/ObterPerfilAtualQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/Ocorrencia/ServicosFakes/ObterUEsPorDREQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/Ocorrencia/ServicosFakes/ObterUEsPorDREQueryHandlerFiltroTodasUesFake.cs
- teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#91769](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91769)
> API - Story/91769

- src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciasRegistradasPorTurmasComponentesPeriodo/ObterFrequenciasRegistradasPorTurmasComponentesPeriodoQuery.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciasRegistradasPorTurmasComponentesPeriodo/ObterFrequenciasRegistradasPorTurmasComponentesPeriodoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
- src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaRegistradaDto.cs
[AB#92357](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92357)
> Obter quantidade de presenças pelas frequencias registradas para o aluno.

- src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
[AB#93721](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93721)
> fix/93721 -> r2

- src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
[AB#93721](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93721)
> fix/93721 -> master

- src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#89964](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89964)
> 89964 - Menu e permissionamento

- src/SME.SGP.Api/Controllers/RelatorioController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Frequencia/RelatorioControleFrequenciaMensalUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IRelatorioControleFrequenciaMensalUseCase.cs
- src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
- src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioControleFrenquenciaMensalDto.cs
- src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpRelatorios.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#89963](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89963)
> 89963 - End Point Solicitação Relatório no SGP

- src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioPorCodigoRfLogin/ObterUsuarioPorCodigoRfLoginQueryHandler.cs
[AB#93538](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93538)
> 93538 Corrigido consulta de cache de usuario

- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#93951](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93951)
> Separar etapas EJA para exibição no dash de fechamento

- src/SME.SGP.Aplicacao/CasosDeUso/Aula/InserirAulaUseCase.cs
- src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#93528](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93528)
> Fix/93528 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFechamento/ObterPendenciaParecerConclusivoUseCases.cs
[AB#93783](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93783)
> Fix/93783 -> r2

- src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSupervisorEscolaDre.cs
[AB#94023](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94023)
> Obter modalidades supervisor para relatório freq mensal.

- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFechamento/ObterPendenciaParecerConclusivoUseCases.cs
[AB#93783](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93783)
> fix/93783 -> master

- src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs
- src/SME.SGP.Aplicacao/Queries/PeriodoFechamento/ObterPeriodoFechamentoAnoAnteriorPorTurmaBimestre/ObterPeriodoFechamentoAnoAnteriorPorTurmaBimestreQuery.cs
- src/SME.SGP.Aplicacao/Queries/PeriodoFechamento/ObterPeriodoFechamentoAnoAnteriorPorTurmaBimestre/ObterPeriodoFechamentoAnoAnteriorPorTurmaBimestreQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/PeriodoFechamento/ObterPeriodoFechamentoVigentePorTurmaDataBimestre/ObterPeriodoFechamentoVigentePorTurmaDataBimestreQuery.cs
- src/SME.SGP.Aplicacao/Queries/PeriodoFechamento/ObterPeriodoFechamentoVigentePorTurmaDataBimestre/ObterPeriodoFechamentoVigentePorTurmaDataBimestreQueryHandler.cs
[AB#91312](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91312)
> Fix/91312 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFechamento/ObterFechamentoConselhoClasseSituacaoUseCase.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
- src/SME.SGP.Infra/Dtos/DashboardFechamento/ConselhoClasseSituacaoQuantidadeDto.cs
[AB#93825](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93825)
> fix/93825 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs
- src/SME.SGP.Aplicacao/Queries/PeriodoFechamento/ObterPeriodoFechamentoAnoAnteriorPorTurmaBimestre/ObterPeriodoFechamentoAnoAnteriorPorTurmaBimestreQuery.cs
- src/SME.SGP.Aplicacao/Queries/PeriodoFechamento/ObterPeriodoFechamentoAnoAnteriorPorTurmaBimestre/ObterPeriodoFechamentoAnoAnteriorPorTurmaBimestreQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/PeriodoFechamento/ObterPeriodoFechamentoVigentePorTurmaDataBimestre/ObterPeriodoFechamentoVigentePorTurmaDataBimestreQuery.cs
- src/SME.SGP.Aplicacao/Queries/PeriodoFechamento/ObterPeriodoFechamentoVigentePorTurmaDataBimestre/ObterPeriodoFechamentoVigentePorTurmaDataBimestreQueryHandler.cs
[AB#91312](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/91312)
> Fix/91312 -> master

- src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#93528](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93528)
> Ajuste fix/93528 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
[AB#92970](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92970)
> fix/92970 -> r2

- src/SME.SGP.Infra/Enumerados/Permissao.cs
> 94475 - Código permissão incorreto

- src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/SalvarObservacaoNAAPA/SalvarObservacaoNAAPACommand.cs
[AB#94523](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94523)
> 94523 - Mensagem de alerta sem acentuação na palavra "Observação"

- src/SME.SGP.Aplicacao/CasosDeUso/Aula/InserirAulaUseCase.cs
[AB#93528](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93528)
> Fix/93528 -> master

- scripts/V626__INCLUIR_PRIORIDADE_PERFIL_ASS_COO_NAAPA.sql
- src/SME.SGP.Dominio/Enumerados/PerfilUsuario.cs
[AB#93892](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93892)
> 93892 - Script insert prioridade_perfil SGP

- src/SME.SGP.Aplicacao/Commands/Fechamento/GerarPendenciasFechamento/GerarPendenciasFechamentoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/PendenciaAula/ExcluirPendenciasAulaDiarioClasseFechamento/ExcluirPendenciasAulaDiarioClasseFechamentoCommand.cs
- src/SME.SGP.Aplicacao/Commands/PendenciaAula/ExcluirPendenciasAulaDiarioClasseFechamento/ExcluirPendenciasAulaDiarioClasseFechamentoCommandHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs
Reverts prefeiturasp/SME-NovoSGP#12364
> Revert "Tratamento de exclusão de pendência de CJ"

- teste/SME.SGP.TesteIntegracao/Aula/Base/AulaTeste.cs
- teste/SME.SGP.TesteIntegracao/Frequencia/Ao_excluir_ou_alterar_aula_com_frequencia.cs
- teste/SME.SGP.TesteIntegracao/ServicosFakes/RecalcularFrequenciaPorTurmaCommandHandlerFake.cs
… e registrado fake para ObterTodosAlunosNaTurmaQuery
> Removido Calculo de Frequencia dos testes de alteração de quantidade de aula

- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterHistoricosDeAlteracoesEncaminhamentoNAAPA/ObterHistoricosDeAlteracoesEncaminhamentoNAAPAQueryHandler.cs
[AB#94689](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94689)
> 94689 - Campo está apresentando como alterado incorretamente

- src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#94510](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94510)
> fix/94510 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
[AB#92970](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92970)
> fix/92970 -> master

- src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterEncaminhamentosAee/ObterEncaminhamentosAEEQuery.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoAee/FiltroPesquisaEncaminhamentosAEEDto.cs
[AB#90289](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90289)
> 90289 - Alterar Dto do Endpoint de Listagem

- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanos/ObterPlanosAEEUseCase.cs
- src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQuery.cs
- src/SME.SGP.Infra/Dtos/PlanoAEE/FiltroPlanosAEEDto.cs
[AB#88938](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/88938)
> 90269 - Alterar Dto do Endpoint de Listagem

- src/SME.SGP.Aplicacao/CasosDeUso/CartaIntencoes/Observacao/Notificacao/ObterUsuarioNotificarCartaIntencoesObservacaoUseCase.cs
- src/SME.SGP.Aplicacao/Queries/CartaIntencoes/ObterCartaIntencoesNotificacao/ObterCartaIntencoesNotificacaoQuery.cs
- src/SME.SGP.Aplicacao/Queries/CartaIntencoes/ObterCartaIntencoesNotificacao/ObterCartaIntencoesNotificacaoQueryHandler.cs
- src/SME.SGP.Infra/Dtos/CartaIntencoes/Observacao/CartaIntencoesObservacaoDto.cs
- src/SME.SGP.Infra/Dtos/CartaIntencoes/Observacao/Notificacao/ObterUsuarioNotificarCartaIntencoesObservacaoDto.cs
[AB#74916](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74916)
> Ajustes obter usuário a notificar carta intenções

- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterConselhoClasseAlunoNota/ObterConselhoClasseAlunoNotaQuery.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterConselhoClasseAlunoNota/ObterConselhoClasseAlunoNotaQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasse.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasse.cs
- src/SME.SGP.Infra/Dtos/ConselhoClasse/ConselhoClasseAlunoNotaDto.cs
[AB#93318](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93318)
> Query que retorne as notas

- src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
- src/SME.SGP.Infra/Dtos/NotaConceitoAlunoBimestreDto.cs
[AB#94770](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94770)
> fix/94770 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ListaoAvaliacoes/ObterNotasParaAvaliacoesListaoUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIdsUsuarioLogado/ObterComponentesCurricularesPorIdsUsuarioLogadoQueryHandler.cs
[AB#94745](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94745)
> fix/94745 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/ListarAtribuicoesCJPorFiltroUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/ObterProfessoresTitularesECjsUseCase.cs
- src/SME.SGP.Aplicacao/Commands/AtribuicaoCJ/InserirAtribuicaoCJ/InserirAtribuicaoCJCommandHandler.cs
[AB#94605](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94605)
> fix/94605 -> master

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentosAEEUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterEncaminhamentosAee/ObterEncaminhamentosAEEQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoAEE.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoAee/EncaminhamentoAEEAlunoTurmaDto.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoAee/EncaminhamentoAEEResumoDto.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_listar_com_filtros.cs
- teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#90292](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90292)
> 90292 - Alterar Query para buscar por Todas UEs

- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFechamento/ObterFechamentoConselhoClasseSituacaoUseCase.cs
[AB#93825](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93825)
> fix/93825 -> r2 (ajuste)

- src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
[AB#94925](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94925)
> fix/94925 -> r2

- src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEConsulta.cs
- src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEAlunoTurmaDto.cs
- src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEResumoDto.cs
- teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_acessar_tela_de_listagem.cs
[AB#90281](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90281)
> 90281 - Plano AEE alterar filtro para retornar todas ue

- src/SME.SGP.Aplicacao/Commands/Frequencia/ConciliacaoFrequenciaTurmas/ConciliacaoFrequenciaTurmasCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Frequencia/IncluirFilaConciliacaoFrequenciaTurma/IncluirFilaConciliacaoFrequenciaTurmaCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterTodosAlunosNaTurma/ObterTodosAlunosNaTurmaQueryHandler.cs
- src/SME.SGP.Dominio/Constantes/NomeChaveCache.cs
[AB#93844](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93844)
> 95022 Incluso tratamento de erro ao obter alunos da turma para não abortar a conciliação

- src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ObterAcompanhamentoAlunoUseCase.cs
[AB#94739](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94739)
> Correção no obter dados da turma RAA

- src/SME.SGP.Aplicacao/Commands/Frequencia/IncluirFilaConciliacaoFrequenciaTurma/IncluirFilaConciliacaoFrequenciaTurmaCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosDentroPeriodo/ObterAlunosDentroPeriodoQuery.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterTodosAlunosNaTurma/ObterTodosAlunosNaTurmaQuery.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterTodosAlunosNaTurma/ObterTodosAlunosNaTurmaQueryHandler.cs
Reduzido o tempo de cache para 5 minutos no processo de conciliação para reduzir o volume de memória do Redis
> Parametrizado o tempo de Cache de Alunos da turma.

- src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#94510](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94510)
> fix/94510 -> master

- src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
[AB#94770](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94770)
> fix/94770 -> r2 (pt.2)

- src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
[AB#94925](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94925)
> fix/94925 -> master

- scripts/V629__ADICIONAR_CAMPOS_WF_APROVACAO_PARECER.sql
- src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacao/PublicarExlusaoWfAprovacaoSemWorkflowsVinculados/PublicarExlusaoWfAprovacaoSemWorkflowsVinculadosCommand.cs
- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacao/PublicarExlusaoWfAprovacaoSemWorkflowsVinculados/PublicarExlusaoWfAprovacaoSemWorkflowsVinculadosCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/ExcluirWfAprovacaoNotaConselhoPorNotaId/ExcluirWfAprovacaoNotaConselhoPorNotaIdCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaFechamento/ExcluirWFAprovacaoNotaFechamentoPorNota/ExcluirWFAprovacaoNotaFechamentoPorNotaCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoParecerConclusivo/ExcluirWFAprovacaoParecerPorAluno/ExcluirWFAprovacaoParecerPorAlunoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoParecerConclusivo/ExcluirWfAprovacaoParecerConclusivo/ExcluirWfAprovacaoParecerConclusivoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivoCommand.cs
- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivoCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/Workflow/ObterIdsWorkflowPorWfAprovacaoId/ObterIdsWorkflowPorWfAprovacaoIdQuery.cs
- src/SME.SGP.Aplicacao/Queries/Workflow/ObterIdsWorkflowPorWfAprovacaoId/ObterIdsWorkflowPorWfAprovacaoIdQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Workflow/ObterIdsWorkflowPorWfAprovacaoId/ObterIdsWorkflowPorWfAprovacaoIdQueryValidator.cs
- src/SME.SGP.Dados/Mapeamentos/WFAprovacaoParecerConclusivoMap.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseParecerConclusivoConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioWFAprovacaoParecerConclusivo.cs
- src/SME.SGP.Dados/Repositorios/RepositorioWorkflowAprovacao.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioWFAprovacaoParecerConclusivo.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioWorkflowAprovacao.cs
- src/SME.SGP.Dominio/Entidades/WFAprovacaoParecerConclusivo.cs
[AB#62116](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62116)
> Feature/62116 

- src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
- src/SME.SGP.Infra/Dtos/NotaConceitoAlunoBimestreDto.cs
[AB#94770](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/94770)
> Fix/94770 -> master

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterDetalhamentoFechamentoConselhoClasseAlunoUseCase.cs
- src/SME.SGP.Aplicacao/Queries/AreaDoConhecimento/ObterAreasConhecimento/ObterAreasConhecimentoQueryHandler.cs
[AB#95046](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95046)
> Fix/95046 -> master

- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/AprovarWorkflowAlteracaoNotaConselho/AprovarWorkflowAlteracaoNotaConselhoCommandHandler.cs
[AB#81687](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/81687)
> 81687 - Ajuste de limpeza cache ao utilizar workflow

- src/SME.SGP.Api/Controllers/DashboardNaapaController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardNaapa/ObterQuantidadeEncaminhamentoEmAbertoPorDreUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardNaapa/IObterQuantidadeEncaminhamentoNAAPAEmAbertoPorDreUseCase.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterQuantidadeEncaminhamentoNAAPAEmAberto/ObterQuantidadeEncaminhamentoNAAPAEmAbertoQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterQuantidadeEncaminhamentoNAAPAEmAberto/ObterQuantidadeEncaminhamentoNAAPAEmAbertoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConsolidadoAtendimentoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidadoAtendimentoNAAPA.cs
- src/SME.SGP.Infra/Dtos/Grafico/Naapa/FiltroQuantidadeEncaminhamentoNAAPAEmAbertoDto.cs
- src/SME.SGP.Infra/Dtos/Grafico/Naapa/QuantidadeEncaminhamentoNAAPAEmAbertoDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/DashboardEncaminhamentoNAAPA/Ao_obter_quantidade_encaminhamento_em_aberto.cs
[AB#64239](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64239)
> 89340 - Criar endpoint Gráfico de quantidade de encaminhamento em aberto por dre.

- scripts/V633__AJUSTE_PLANOS_MIGRADOS.sql
[AB#89980](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89980)
> Fix/89980 -> r2

- scripts/V632__CRIAR_PARAMETRO_86_LAYOUT_RELATORIO_DEVOLUTIVAS.sql
[AB#95115](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95115)
> Inclusão do parâmetro tipo 86 - Devolutivas

- src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
[AB#95338](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95338)
> Relatório de pendência de diário de bordo para infantil gera com os campos em branco

- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs
[AB#95493](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95493)
> 95493 - Ordenação ue

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ConsultaConselhoClasseRecomendacaoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterAlunosSemNotasRecomendacoesUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/VerificarSeExisteRecomandacaoPorTurma/VerificarSeExisteRecomendacaoPorTurmaQuery.cs
- src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaEmPeriodoDeFechamento/ObterTurmaEmPeriodoDeFechamentoQuery.cs
- teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_obter_recomendacoes_notas.cs
[AB#95489](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95489)
[AB#95491](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95491)
[AB#95492](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95492)
> Correção das mensagens das abas e validações dos queries

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterAlunosSemNotasRecomendacoesUseCase.cs
[AB#95510](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95510)
> 95510 - Conselho de classe ao validar apresenta mensagem inconsistência

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterAlunosSemNotasRecomendacoesUseCase.cs
[AB#95513](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95513)
[AB#95512](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95512)
> Validar recomendações de alunos inativos e Exibir duas vezes a mesma aluna

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterAlunosSemNotasRecomendacoesUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterConselhoClasseAlunoNota/ObterConselhoClasseAlunoNotaQuery.cs
[AB#95529](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95529)
> Erro interno ao validar aba final

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterAlunosSemNotasRecomendacoesUseCase.cs
[AB#95531](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95531)
> Evitando duplicações de componentes

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterAlunosSemNotasRecomendacoesUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ExisteConselhoClasseUltimoBimestre/ExisteConselhoClasseUltimoBimestreQueryHandler.cs
[AB#95596](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95596)
> Erro interno na tela de conselho de classe (ao selecionar aba final, e ao selecionar aluno)

- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ExisteConselhoClasseParaTurma/ExisteConselhoClasseParaTurmaQuery.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterConselhoClasseAlunoNota/ObterConselhoClasseAlunoNotaQuery.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/VerificarSeExisteRecomandacaoPorTurma/VerificarSeExisteRecomendacaoPorTurmaQuery.cs
- src/SME.SGP.Aplicacao/Queries/FechamentoTurma/ObterFechamentoTurmaComConselhoDeClassePorTurmaCodigoSemestre/ObterFechamentoTurmaComConselhoDeClassePorTurmaCodigoSemestreTipoCalendarioQuery.cs
[AB#95636](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95636)
> Ao validar selecionado FINAL apresenta msg de erro 'Bimestre' deve ser informado.

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterDetalhamentoFechamentoConselhoClasseAlunoUseCase.cs
[AB#92248](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92248)
> 92248 - Não atualizou o % de frequência do estudante nos componentes curriculares

- src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
[AB#95613](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95613)
> 95613 - Notas lançadas no Fechamento

- src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoAluno .cs
- src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasFechamentoAluno.cs
[AB#95290](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95290)
> fix/95290 -> r2

- src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs
[AB#95498](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95498)
> Correção da query de componentes que estava considerando sempre com conselho, mas tem que ser fechamento tbém

- src/SME.SGP.Aplicacao/CasosDeUso/DashboardNaapa/ObterQuantidadeEncaminhamentoPorSituacaoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ExecutarCargaConsolidadoEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterDataUltimaConsolicacaoDashboardNaapa/ObterDataUltimaConsolicacaoDashboardNaapaQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterDataUltimaConsolicacaoDashboardNaapa/ObterDataUltimaConsolicacaoDashboardNaapaQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterQuantidadeAtendimentoNAAPAPorProfissionalMes/ObterQuantidadeAtendimentoNAAPAPorProfissionalMesQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterQuantidadeEncaminhamentoNAAPAEmAberto/ObterQuantidadeEncaminhamentoNAAPAEmAbertoQueryHandler.cs
[AB#95698](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95698)
> 95698 - Ajuste na "Data da última atualização/Consolidado"

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ExecutarBuscarConsolidadoAtendimentosProfissionalEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ExecutarBuscarUesConsolidadoEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ExecutarExcluirConsolidadoAtendimentoProfissionalEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ExecutarExcluirConsolidadoEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/ExcluirConsolidadoAtendimentoProfissionalEncaminhamentoNAAPAPorId/ExcluirConsolidadoAtendimentoProfissionalEncaminhamentoNAAPAPorIdCommand.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/ExcluirConsolidadoAtendimentoProfissionalEncaminhamentoNAAPAPorId/ExcluirConsolidadoAtendimentoProfissionalEncaminhamentoNAAPAPorIdCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/ExcluirConsolidadoEncaminhamentoNAAPAPorId/ExcluirConsolidadoEncaminhamentoNAAPAPorIdCommand.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/ExcluirConsolidadoEncaminhamentoNAAPAPorId/ExcluirConsolidadoEncaminhamentoNAAPAPorIdCommandHandler.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IExecutarExcluirConsolidadoAtendimentoProfissionalEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IExecutarExcluirConsolidadoEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosNAAPAIdConsolidadoExclusao/ObterEncaminhamentosNAAPAIdConsolidadoExclusaoQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosNAAPAIdConsolidadoExclusao/ObterEncaminhamentosNAAPAIdConsolidadoExclusaoQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterProfissionaisAtendimentoEncaminhamentosNAAPAIdConsolidadoExclusao/ObterProfissionaisAtendimentoEncaminhamentosNAAPAIdConsolidadoExclusaoQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterProfissionaisAtendimentoEncaminhamentosNAAPAIdConsolidadoExclusao/ObterProfissionaisAtendimentoEncaminhamentosNAAPAIdConsolidadoExclusaoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConsolidadoAtendimentoNAAPA.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConsolidadoEncaminhamentoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidadoAtendimentoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidadoEncaminhamentoNAAPA.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/FiltroExcluirAtendimentosProfissionalConsolidadoEncaminhamentoNAAPADto.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/FiltroExcluirUesConsolidadoEncaminhamentoNAAPADto.cs
- src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpNAAPA.cs
- src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarNAAPAUseCaseRabbitSgp.cs
- src/SME.SGP.NAAPA.Worker/WorkerRabbitNAAPA.cs
[AB#95681](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95681)
> 95681 - Exclusão de consolidado naapa por profissionais e por situacao

- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaConsulta.cs
[AB#95708](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95708)
> Considerar fechamentos não excluídos

- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasse.cs
[AB#95804](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95804)
> 95804 - Aba Final - Não considera nota nota pós-conselho

- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
[AB#95802](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95802)
> Revert "Incrementar timeout para execução da query dash fechamento"

- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasse.cs
[AB#95850](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95850)
> 95850 - Recomendações conselho fechamento final

- src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs
[AB#96125](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96125)
> 96125 - Mesmo sem fazer alterações ao recalcular o parecer fica como aguardando aprovação

- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterHistoricosDeAlteracoesEncaminhamentoNAAPA/ObterHistoricosDeAlteracoesEncaminhamentoNAAPAQueryHandler.cs
[AB#96115](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96115)
> 96115 - Ajuste geração histórico para tipo combo multiseleção e upload

- src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoAluno .cs
- src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasFechamentoAluno.cs
[AB#95290](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95290)
> fix/95290 -> master

- src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#95508](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95508)
> fix/95508 -> master

- src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs
- src/SME.SGP.Dados/Repositorios/RepositorioWorkflowAprovacao.cs
[AB#96172](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96172)
> Fix/96172 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/HistoricoEscolar/HistoricoEscolarUseCase.cs
- src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
[AB#87717](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/87717)
> 87717 - Tipo relatório e geração historico escolar EJA

- src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs
[AB#96327](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96327)
> fix/96327 -> r2

- src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs
[AB#90268](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/90268)
> 90268 - Ajuste tipo nota da turma ed fisica pela turma regular

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#96723](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96723)
> 96723 - Ajustes componentes complementares turma ed fisica

- src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs
[AB#96327](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96327)
> Fix/96327 -> master

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#96874](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96874)
> 96874 - Ajuste busca notas fechamento default Turma Itinerario EM

- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNotaConsulta.cs
[AB#95507](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95507)
> fix/95507 -> master

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/AtualizaEncaminhamentoAEETurmaAlunoSyncUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/AtualizaPlanoAEETurmaAlunoSyncUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/ObterEncaminhamentoAEEVigente/ObterEncaminhamentoAEEVigenteQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/ObterEncaminhamentoAEEVigente/ObterEncaminhamentoAEEVigenteQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosComSituacaoDiferenteDeEncerrado/ObterPlanosComSituacaoDiferenteDeEncerradoQuery.cs
- src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosComSituacaoDiferenteDeEncerrado/ObterPlanosComSituacaoDiferenteDeEncerradoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoAEE.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEConsulta.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/ObterEncaminhamentoAEEVigenteQueryHandlerTeste.cs
correção para atualizar em segundo plano somente ano atual
> fix/Atualizar Segundo Plano Ano Atual

- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasse.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidadoConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidadoNota.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#97154](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97154)
> Consolidado conselho classe aluno turma nota bimestre null

- src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioConselhoClasseAtaFinalDto.cs
> 61083 - Incluir prop componentes que não lançam nota

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConsolidacaoTurmaConselhoClasseAlunoAnosAnterioresAlunoUseCase.cs
Complemento do bug incluindo o repositório de escrita para gravação do consolidado de conselho de classe de anos anteriores.
> Bug: 97274

- src/SME.SGP.Api/Controllers/EventoController.cs
Ajuste no endpoint de liberação do boletim alterando para considerar a chave de integração ao invés do token.
> Bug: 94472

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ObterComponentesFechamentoConsolidadoPorTurmaBimestreUseCase.cs
[AB#96193](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96193)
> Fix/96193 -> r2

- src/SME.SGP.Api/Controllers/FrequenciaIntegracaoController.cs
Inclusão da controller frequência integração para possibilitar a integração através do escola aqui utilizando a chave de integração.
> Bug: 95723

- src/SME.SGP.Api/Controllers/AutenticacaoIntegracaoController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Autenticacao/ObterGuidAutenticacaoFrequenciaSGA.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Autenticacao/IObterGuidAutenticacaoFrequenciaSGA.cs
- src/SME.SGP.Dominio/Constantes/NomeChaveCache.cs
- src/SME.SGP.Infra/Dtos/AutenticacaoFrequenciaSGADto.cs
- src/SME.SGP.Infra/Dtos/SolicitacaoGuidAutenticacaoFrequenciaSGADto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#97487](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97487)
> 97487 - Geração de Guid autenticaçãof requencia SGA

- src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
[AB#97838](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97838)
> Fix/97838 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ObterComponentesFechamentoConsolidadoPorTurmaBimestreUseCase.cs
[AB#96193](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96193)
> fix/96193 -> master

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#97741](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97741)
> 97741 - Notas de fechamento não estava apresentando da turma incorreta.

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
Reverts prefeiturasp/SME-NovoSGP#12868
> Revert "97741 - Notas de fechamento não estava apresentando da turma incorreta."

- src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
[AB#97838](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97838)
> fix/97838 pt.2 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
[AB#98331](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98331)
> 98331 - Consolidado ao retornar nota vazia do conselho não busca nota do fechamento

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorTurmasCodigo/ObterComponentesCurricularesPorTurmasCodigoQueryHandler.cs
[AB#97844](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97844)
> fix/97844 -> r2

- src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
[AB#97838](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97838)
> Fix/97838 -> master

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorTurmasCodigo/ObterComponentesCurricularesPorTurmasCodigoQueryHandler.cs
[AB#97844](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97844)
> Fix/97844 -> master

- src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDiarioDeBordoPorId/ObterDiarioDeBordoPorIdQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDiarioBordo.cs
- src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoDetalhesDto.cs
- teste/SME.SGP.TesteIntegracao/DiarioBordo/Ao_obter_diario_bordo_por_id.cs
- teste/SME.SGP.TesteIntegracao/DiarioBordo/Base/DiarioBordoTesteBase.cs
[AB#92374](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92374)
> 92374 - Adicionar campos para retornar os planejamento irmão

- src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#98426](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98426)
> Fix/98426 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/SalvarAtribuicaoCJUseCase.cs
[AB#97567](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97567)
> fix/97567 -> r2

- src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#98426](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98426)
> fix/98426 -> master

- teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_alterar_nota_conceito_pos_conselho_bimestre_final.cs
- teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_inserir_nota_numerica_pos_conselho_bimestre_final.cs
- teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs
[AB#98429](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98429)
> 98429 - Ajuste testes integrados

- src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/SalvarAtribuicaoCJUseCase.cs
[AB#97567](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97567)
> fix/97567 -> master

- src/SME.SGP.Api/Controllers/AcompanhamentoAlunoController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ObterValidacaoPercusoRAAUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AcompanhamentoAluno/IObterValidacaoPercusoRAAUseCase.cs
- src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterAlunosQueContemPercursoIndividalPreenchido/ObterAlunosQueContemPercursoIndividalPreenchidoQuery.cs
- src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterAlunosQueContemPercursoIndividalPreenchido/ObterAlunosQueContemPercursoIndividalPreenchidoQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterDadosAlunosFechamento/ObterDadosAlunosFechamentoQuery.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterDadosAlunosFechamento/ObterDadosAlunosFechamentoQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterDadosAlunosTurma/ObterDadosAlunosTurmaQuery.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterDadosAlunosTurma/ObterDadosAlunosTurmaQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioAcompanhamentoAlunoConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAcompanhamentoAlunoConsulta.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioAcomponhamentoAluno.cs
- src/SME.SGP.Infra/Dtos/AcompanhamentoAluno/AlunosComInconsistenciaPercursoIndividualRAADto.cs
- src/SME.SGP.Infra/Dtos/AcompanhamentoAluno/FiltroInconsistenciaPercursoRAADto.cs
- src/SME.SGP.Infra/Dtos/AcompanhamentoAluno/InconsistenciaPercursoIndividualRAADto.cs
- src/SME.SGP.Infra/Dtos/AcompanhamentoAluno/InconsistenciaPercursoRAADto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/Ao_validar_percurso.cs
- teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/Base/RelatorioAcompanhamentoAprendizagemTesteBase.cs
- teste/SME.SGP.TesteIntegracao/RelatorioAcompanhamentoAprendizagem/ServicosFake/ObterAlunosAtivosPorTurmaCodigoQueryHandlerFake.cs
[AB#93939](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/93939)
> 93939 - Criar endpoint Validar RAA

- src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs
[AB#98563](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98563)
> fix/98563 -> r2

- src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs
[AB#98563](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98563) [AB#98439](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98439)
> fix/98563 -> master

- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaAlunosComAusencia/ObterListaAlunosComAusenciaQueryHandler.cs
[AB#98239](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98239)
> fix/98239 -> master

- src/SME.SGP.Api/Controllers/RelatorioPAPController.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorPeriodosEscolares/ObterFrequenciaGeralAlunoPorPeriodosEscolaresQuery.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorPeriodosEscolares/ObterFrequenciaGeralAlunoPorPeriodosEscolaresQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterFrequenciaTurmaPAP/ObterFrequenciaTurmaPAPQuery.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterFrequenciaTurmaPAP/ObterFrequenciaTurmaPAPQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
- src/SME.SGP.Dominio/Enumerados/TipoQuestao.cs
- teste/SME.SGP.TesteIntegracao/RelatorioPAP/Ao_obter_frequencia_aluno_turma_pap.cs
- teste/SME.SGP.TesteIntegracao/RelatorioPAP/Base/RelatorioPAPTesteBase.cs
- teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#95245](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95245)
> 95254 - Criação do novo tipo de questão e end point de busca

- src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
[AB#98622](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98622)
> fix/98622 -> master

- src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciasPorAlunosTurma/ObterFrequenciasPorAlunosTurmaQuery.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciasPorAlunosTurma/ObterFrequenciasPorAlunosTurmaQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#95297](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95297)
> Fix/95297 -> master

- scripts/V638__CRIAR_TABELAS_CONFIGURACAO_RELATORIO_PERIODICO_PAP.sql
- scripts/V640__CARGA_QUESTIONARIO_RELATORIO_PAP.sql
- src/SME.SGP.Dominio/Entidades/SecaoRelatorioPeriodicoPAP.cs
- src/SME.SGP.Dominio/Enumerados/TipoQuestionario.cs
- src/SME.SGP.Dominio/SecaoConfigRelatorioPeriodicoPap.cs
[AB#95241](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95241)
> 95241 - Publicação das questões, seções e configurações

- scripts/V640__CARGA_QUESTIONARIO_RELATORIO_PAP.sql
- src/SME.SGP.Api/Controllers/RelatorioPAPController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/ObterPeriodosPAPUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/RelatoriosPAP/IObterPeriodosPAPUseCase.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterPeriodosPAP/ObterPeriodosPAPQuery.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterPeriodosPAP/ObterPeriodosPAPQueryHandler.cs
- src/SME.SGP.Dados/Mapeamentos/SecaoRelatorioPeriodicoPAPMAp.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPeriodoRelatorioPAP.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoRelatorioPAP.cs
- src/SME.SGP.Dominio/Entidades/SecaoRelatorioPeriodicoPAP.cs
- src/SME.SGP.Infra/Dtos/RelatoriosPAP/PeriodosPAPDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/RelatorioPAP/Ao_obter_periodos_pap.cs
[AB#95243](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95243)
> 95243 - End point busca de períodos configurados para ano turma

- src/SME.SGP.Dominio/SecaoConfigRelatorioPeriodicoPAP.cs
- teste/SME.SGP.TesteIntegracao/RelatorioPAP/Base/RelatorioPAPTesteBase.cs
- teste/SME.SGP.TesteIntegracao/RelatorioPAP/ConstantesTestePAP.cs
[AB#95337](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95337)
> Criação da base de testes do PAP

- scripts/V640__CARGA_QUESTIONARIO_RELATORIO_PAP.sql
- src/SME.SGP.Api/Controllers/RelatorioPAPController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/ObterQuestionarioPAPUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/ObterSecoesPAPUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/RelatoriosPAP/IObterQuestionarioPAPUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/RelatoriosPAP/IObterSecoesPAPUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Questionario/ObterQuestoesPorQuestionarioPorId/ObterQuestoesPorQuestionarioPorIdQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterQuestionarioPAP/ObterQuestionarioPAPQuery.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterQuestionarioPAP/ObterQuestionarioPAPQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterSecoesPAP/ObterSecoesPAPQuery.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterSecoesPAP/ObterSecoesPAPQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRelatorioPeriodicoPAPResposta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioSecaoRelatorioPeriodicoPAP.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRelatorioPeriodicoPAPResposta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSecaoRelatorioPeriodicoPAP.cs
- src/SME.SGP.Dominio/Constantes/NomeChaveCache.cs
- src/SME.SGP.Infra/Dtos/RelatoriosPAP/FiltroObterSecoesDto.cs
- src/SME.SGP.Infra/Dtos/RelatoriosPAP/SecaoPAPDto.cs
- src/SME.SGP.Infra/Dtos/RelatoriosPAP/SecaoTurmaAlunoPAPDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/RelatorioPAP/Ao_obter_secoes_questionario.cs
- teste/SME.SGP.TesteIntegracao/RelatorioPAP/Base/RelatorioPAPTesteBase.cs
- teste/SME.SGP.TesteIntegracao/RelatorioPAP/ConstantesTestePAP.cs
[AB#95246](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95246)
> 95246 - End points busca seções PAP

- src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasPorPeriodoUseCase.cs
[AB#97287](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97287)
> fix/97287 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#98955](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98955)
> fix/98955 -> r2

- src/SME.SGP.Api/Controllers/RelatorioPAPController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/ObterQuestionarioPAPUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/RelatoriosPAP/IObterQuestionarioPAPUseCase.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterPeriodoRelatorioPAP/PeriodoRelatorioPAPQuery.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterPeriodoRelatorioPAP/PeriodoRelatorioPAPQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterQuestionarioPAP/ObterQuestionarioPAPQuery.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterQuestionarioPAP/ObterQuestionarioPAPQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPeriodoRelatorioPAP.cs
- src/SME.SGP.Dados/Repositorios/RepositorioQuestao.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoRelatorioPAP.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioQuestao.cs
- src/SME.SGP.Dominio/Entidades/PeriodoRelatorioPAP.cs
- teste/SME.SGP.TesteIntegracao/RelatorioPAP/Ao_obter_secoes_questionario.cs
[AB#99242](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99242)
> 99242 - Adicionar retorno de resposta por tipo

- src/SME.SGP.Aplicacao/Queries/Aluno/ObterMarcadorAluno/ObterMarcadorAlunoQueryHandler.cs
- src/SME.SGP.Dominio.Servicos/ServicoAluno.cs
[AB#99024](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99024)
> fix/99024 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#98955](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98955)
> fix/98955 -> master

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioTurma.cs
[AB#99026](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99026)
> 99026 - Não permitir consolidar notas em turmas não regulares

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterAlunosSemNotasRecomendacoesUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasComMatriculaValidasParaValidarConselho/ObterTurmasComMatriculaValidasParaValidarConselhoQuery.cs
- src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasComMatriculaValidasParaValidarConselho/ObterTurmasComMatriculaValidasParaValidarConselhoQueryHandler.cs
[AB#99025](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99025)
> fix/99025 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterAlunosSemNotasRecomendacoesUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasComMatriculaValidasParaValidarConselho/ObterTurmasComMatriculaValidasParaValidarConselhoQuery.cs
- src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasComMatriculaValidasParaValidarConselho/ObterTurmasComMatriculaValidasParaValidarConselhoQueryHandler.cs
[AB#99025](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99025)
> Fix/99025 -> master

- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/VerificaSePodeEditarNota/VerificaSePodeEditarNotaQueryHandler.cs
[AB#97744](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97744)
> fix/97744 -> r2

- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidadoConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidadoNota.cs
[AB#99275](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99275)
> 99275 - Buscando ultimo registro para edição em casos de duplicidade

- src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaUnica/AlterarAulaUnicaCommandHandler.cs
[AB#99253](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99253)
> fix/99253 -> r2

- src/SME.SGP.Aplicacao/Queries/Aluno/ObterMarcadorAluno/ObterMarcadorAlunoQueryHandler.cs
- src/SME.SGP.Dominio.Servicos/ServicoAluno.cs
[AB#99024](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99024)
> fix/99024 -> master

- src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaUnica/AlterarAulaUnicaCommandHandler.cs
[AB#99253](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99253)
> Fix/99253 -> master

- scripts/V641__PARAMETRO_DIAS_APOS_INICIO_PERIODO_LETIVO_COMPONENTE_SEM_AULA.sql
- src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterDiasAposInicioPeriodoLetivoComponenteSemAula/DiasAposInicioPeriodoLetivoComponenteSemAulaQuery.cs
- src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterDiasAposInicioPeriodoLetivoComponenteSemAula/DiasAposInicioPeriodoLetivoComponenteSemAulaQueryHandler.cs
- src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
[AB#92331](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92331)
> 92331 - Script criação parâmetro Dias Após Início Período Letivo Pendência para Turma/Componente Sem Aula

- scripts/V642__PARAMETRO_EXECUTA_PENDENCIA_COMPONENTE_SEM_AULA.sql
- src/SME.SGP.Aplicacao/Queries/ParametroSistema/PodeExecutarPendenciaComponenteSemAula/PodeExecutarPendenciaComponenteSemAulaQuery.cs
- src/SME.SGP.Aplicacao/Queries/ParametroSistema/PodeExecutarPendenciaComponenteSemAula/PodeExecutarPendenciaComponenteSemAulaQueryHandler.cs
- src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
[AB#92334](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92334)
> 92334 - Criação parâmetro Controle de geração de pendências de componentes sem aula

- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/VerificaSePodeEditarNota/VerificaSePodeEditarNotaQueryHandler.cs
[AB#97744](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97744)
> fix/97744 -> master

- src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaUnica/InserirAulaUnicaCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/PendenciaProfessor/ExecutarExclusaoPendenciaProfessorComponenteSemAula/ExecutarExclusaoPendenciaProfessorComponenteSemAulaCommand.cs
- src/SME.SGP.Aplicacao/Commands/PendenciaProfessor/ExecutarExclusaoPendenciaProfessorComponenteSemAula/ExecutarExclusaoPendenciaProfessorComponenteSemAulaCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarIdPorTurmaId/ObterPeriodoEscolarIdPorTurmaIdQuery.cs
- src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarIdPorTurmaId/ObterPeriodoEscolarIdPorTurmaIdQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendenciaProfessor.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolarConsulta.cs
- src/SME.SGP.Dominio/Enumerados/TipoPendencia.cs
- teste/SME.SGP.TesteIntegracao/Aula/Ao_registrar_aula_excluir_pendencia_professor.cs
[AB#92344](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92344)
> 92344 - Resolver/excluir a pendencia ao lançar aula para o componente

- src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasPorPeriodoUseCase.cs
[AB#97287](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97287)
> fix/97287 -> master

- src/SME.SGP.Aplicacao/Queries/Professores/ObterProfessoresTitularesDaTurmaCompletos/ObterProfessoresTitularesDaTurmaCompletosQuery.cs
- src/SME.SGP.Aplicacao/Queries/Professores/ObterProfessoresTitularesDaTurmaCompletos/ObterProfessoresTitularesDaTurmaCompletosQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDia/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDiaQueryHandler.cs
[AB#95861](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95861)
> Fix/95861 -> master

- src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#95314](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95314)
> Fix/95314 -> master

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
[AB#99359](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99359)
> fix/99359 -> master

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
Ajuste conselho de classe
Ajuste para exibição de notas para o conselho de classe na validação para converter a nota de fechamento numerica
> fix/98634 -> r2

- src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#99977](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99977)
> Fix/99977 -> r2

- src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#99977](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99977)
> fix/99977 -> pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
[AB#99588](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99588)
> fix/99588 -> pre-prod

- src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs
[AB#99115](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99115)
> fix/99115 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
- src/SME.SGP.Dominio/Entidades/Turma.cs
- src/SME.SGP.Dominio/Enumerados/TipoTurma.cs
> fix/97323 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ConsultaConselhoClasseRecomendacaoUseCase.cs
> Fix/99083 -> pre-prod

- src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#99977](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99977)
> fix/99977 -> r2 (pt.2)

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#98634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98634)
> fix/98634-master -> master

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
[AB#100355](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/100355)
> fix/100355 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterDadosDashboardFrequenciaSemanalMensalPorAnoTurmaUseCase.cs
- src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterFrequenciasConsolidadasPorTurmaMensalSemestral/ObterFrequenciasConsolidadasPorTurmaMensalSemestralQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterFrequenciasConsolidadasPorTurmaMensalSemestral/ObterFrequenciasConsolidadasPorTurmaMensalSemestralQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaTurmaConsulta.cs
[AB#100360](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/100360)
> Correção na busca mensal

- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterFiltroSemanaUseCase.cs
[AB#100361](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/100361)
> 100361 - Retorno do filtro semanal incorreto

- src/SME.SGP.Aplicacao/Queries/Funcionario/ObterFuncionariosPorDreECargo/ObterFuncionariosPorDreECargoQueryHandler.cs
[AB#100137](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/100137)
> fix/100137 -> r2

- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAluno/ObterConsultaFrequenciaGeralAlunoQueryHandler.cs
[AB#96348](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96348)
> fix/96348 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ExisteEncaminhamentoNAAPAAtivoParaAluno/ExisteEncaminhamentoNAAPAAtivoParaAlunoQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ExisteEncaminhamentoNAAPAAtivoParaAluno/ExisteEncaminhamentoNAAPAAtivoParaAlunoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoNAAPA.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioEncaminhamentoNAAPA.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_cadastrar_editar_encaminhamento_naapa_rascunho.cs
[AB#96753](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96753)
> 96753 - Está permitindo inserir vários encaminhamento para o mesmo aluno

- scripts/V643__ADICIONAR_CAMPO_TIPO_CONSOLIDADO_TABELA_CONSOLIDACAO_FREQUENCIA_TURMA.sql
- src/SME.SGP.Api/Controllers/DashboardFrequenciaController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoFrequenciaTurma/ConsolidarFrequenciaPorTurmaAbstractUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterDadosDashboardFrequenciaSemanalMensalPorAnoTurmaUseCase.cs
- src/SME.SGP.Aplicacao/Commands/ConsolidacaoFrequenciaTurma/RegistraConsolidacaoFrequenciaTurma/RegistraConsolidacaoFrequenciaTurmaCommand.cs
- src/SME.SGP.Aplicacao/Commands/ConsolidacaoFrequenciaTurma/RegistraConsolidacaoFrequenciaTurma/RegistraConsolidacaoFrequenciaTurmaCommandHandler.cs
- src/SME.SGP.Dados/Mapeamentos/ConsolidacaoFrequenciaTurmaMap.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaTurmaConsulta.cs
- src/SME.SGP.Dominio/Entidades/ConsolidacaoFrequenciaTurma.cs
- src/SME.SGP.Infra/Dtos/FrequenciaGlobalMensalSemanalDto.cs
- teste/SME.SGP.TesteIntegracao/ConsolidacaoDashboardFrequenciaTurma/Ao_obter_consolidacao_dashboard_diaria_semanal_mensal_frequencia.cs
- teste/SME.SGP.TesteIntegracao/ConsolidacaoFrequenciaMensal/Ao_consolidar_frequencia_turma_mensal.cs
[AB#100533](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/100533)
> Inclusão da coluna de total de alunos na consolidação

- scripts/V643__ADICIONAR_CAMPO_TIPO_CONSOLIDADO_TABELA_CONSOLIDACAO_FREQUENCIA_TURMA.sql
- src/SME.SGP.Api/Controllers/DashboardFrequenciaController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoFrequenciaTurma/ConsolidarFrequenciaPorTurmaAbstractUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterDadosDashboardFrequenciaSemanalMensalPorAnoTurmaUseCase.cs
- src/SME.SGP.Aplicacao/Commands/ConsolidacaoFrequenciaTurma/RegistraConsolidacaoFrequenciaTurma/RegistraConsolidacaoFrequenciaTurmaCommand.cs
- src/SME.SGP.Aplicacao/Commands/ConsolidacaoFrequenciaTurma/RegistraConsolidacaoFrequenciaTurma/RegistraConsolidacaoFrequenciaTurmaCommandHandler.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFrequencia/IObterDadosDashboardFrequenciaSemanalMensalPorAnoTurmaUseCase.cs
- src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterFrequenciasConsolidadasPorTurmaMensalSemestral/ObterFrequenciasConsolidadasPorTurmaMensalSemestralQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterFrequenciasConsolidadasPorTurmaMensalSemestral/ObterFrequenciasConsolidadasPorTurmaMensalSemestralQueryHandler.cs
- src/SME.SGP.Dados/Mapeamentos/ConsolidacaoFrequenciaTurmaMap.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaTurmaConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoFrequenciaTurmaConsulta.cs
- src/SME.SGP.Dominio/Entidades/ConsolidacaoFrequenciaTurma.cs
- src/SME.SGP.Infra/Dtos/FrequenciaGlobalMensalSemanalDto.cs
- teste/SME.SGP.TesteIntegracao/ConsolidacaoDashboardFrequenciaTurma/Ao_obter_consolidacao_dashboard_diaria_semanal_mensal_frequencia.cs
- teste/SME.SGP.TesteIntegracao/ConsolidacaoFrequenciaMensal/Ao_consolidar_frequencia_turma_mensal.cs
[AB#100534](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/100534)
> O total de alunos já está presente no mínimo e máximo

- src/SME.SGP.Aplicacao/Queries/Funcionario/ObterFuncionariosPorDreECargo/ObterFuncionariosPorDreECargoQueryHandler.cs
[AB#100137](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/100137)
> fix/100137 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
[AB#100355](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/100355)
> fix/100355 -> pre-prod

- src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoConsulta.cs
- src/SME.SGP.Infra/Dtos/NotaConceitoFechamentoConselhoFinalDto.cs
[AB#100075](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/100075)
> Fix/100075 -> pre-prod

- src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ExisteEncaminhamentoNAAPAAtivoParaAlunoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IExisteEncaminhamentoNAAPAAtivoParaAlunoUseCase.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_cadastrar_editar_encaminhamento_naapa_rascunho.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs
[AB#96753](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96753)
> 96753 - Criando endpoint para realizar a inconsistência antes do cadastro.

- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterQuestionarioPAP/ObterQuestionarioPAPQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRelatorioPeriodicoPAPResposta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRelatorioPeriodicoPAPResposta.cs
- teste/SME.SGP.TesteIntegracao/RelatorioPAP/Ao_obter_secoes_questionario.cs
- teste/SME.SGP.TesteIntegracao/RelatorioPAP/Base/RelatorioPAPTesteBase.cs
- teste/SME.SGP.TesteIntegracao/RelatorioPAP/ConstantesTestePAP.cs
[AB#95260](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95260)
> 95260 - Sugerir valores de bimestre anterior em novos bimestres

- src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs
[AB#99587](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99587)
> fix/99587 -> r2

- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/AprovarWorkflowAlteracaoNotaConselho/AprovarWorkflowAlteracaoNotaConselhoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/RecusarAprovacaoNotaConselho/RecusarAprovacaoNotaConselhoCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterConselhoClasseNotasAluno/ObterConselhoClasseNotasAlunoQueryHandler.cs
[AB#100867](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/100867)
> 100867 - Ajuste problema persistencia e limpeza cache nota pos conselho

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
[AB#100867](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/100867)
> 100867 - Ajuste cache consolidação conselho classe

- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterPeriodosPAP/ObterPeriodosPAPQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/PeriodoEstaEmAbertoPAP/PeriodoEstaEmAbertoPAPQuery.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/PeriodoEstaEmAbertoPAP/PeriodoEstaEmAbertoPAPQueryHandler.cs
- src/SME.SGP.Dados/Mapeamentos/ConfiguracaoRelatorioPAPMap.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPeriodoRelatorioPAP.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoRelatorioPAP.cs
- src/SME.SGP.Dominio/Entidades/ConfiguracaoRelatorioPAP.cs
- src/SME.SGP.Infra/Dtos/RelatoriosPAP/PeriodosPAPDto.cs
[AB#95265](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95265)
> 95265 - Não permitir salvar PAP fora do período

- src/SME.SGP.Api/Controllers/RelatorioPAPController.cs
- src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#95278](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95278)
> 95278 - Novo permissionamento

- src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs
[AB#99587](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99587)
> fix/99587 -> pre-prod

- src/SME.SGP.Api/Controllers/RelatorioPAPController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/ExcluirArquivoPAPUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/SalvarRelatorioPAPUseCase.cs
- src/SME.SGP.Aplicacao/Commands/RelatorioPAP/ExcluirReferenciaArquivoPAPPorArquivoId/ExcluirReferenciaArquivoPAPPorArquivoIdCommand.cs
- src/SME.SGP.Aplicacao/Commands/RelatorioPAP/ExcluirReferenciaArquivoPAPPorArquivoId/ExcluirReferenciaArquivoPAPPorArquivoIdCommandHandler.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/RelatoriosPAP/IExcluirArquivoPAPUseCase.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRelatorioPeriodicoPAPResposta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRelatorioPeriodicoPAPResposta.cs
- src/SME.SGP.Dominio/Enumerados/TipoArquivo.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#100771](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/100771)
> 100771 - Endpoint upload e delet de arquivos no editor

- scripts/V645__ALTERACAO_CARGA_CONFIGURACAO_PAP.sql
[AB#101141](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101141)
> 101141 - Alteração na carga de configuração pap

- src/SME.SGP.Api/Controllers/ArmazenamentoController.cs
- src/SME.SGP.Api/Controllers/FechamentoTurmaController.cs
- src/SME.SGP.Api/Controllers/NotasConceitosController.cs
- src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
- src/SME.SGP.Dados/Repositorios/RepositorioAcompanhamentoAlunoConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioAcompanhamentoTurma.cs
- src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusencia.cs
- src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricular.cs
- src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoRecomendacaoConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidadoNota.cs
- src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
- src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordoObservacao.cs
- src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoAlunoConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioFrequencia.cs
- src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodo.cs
- src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoAulaPrevista.cs
- src/SME.SGP.Dados/Repositorios/RepositorioOcorrencia.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolarConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAula.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRecuperacaoParalela.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRegistroAusenciaAlunoConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioTipoCalendario.cs
- src/SME.SGP.Dados/Repositorios/RepositorioTipoCalendarioConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
[AB#101106](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101106)
> 101106 - Remoção de try catches e de comentários desnecessários

- src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ExisteEncaminhamentoNAAPAAtivoParaAlunoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IExisteEncaminhamentoNAAPAAtivoParaAlunoUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ExisteEncaminhamentoNAAPAAtivoParaAluno/ExisteEncaminhamentoNAAPAAtivoParaAlunoQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ExisteEncaminhamentoNAAPAAtivoParaAluno/ExisteEncaminhamentoNAAPAAtivoParaAlunoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoNAAPA.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioEncaminhamentoNAAPA.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_cadastrar_editar_encaminhamento_naapa_rascunho.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs
[AB#96753](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96753)
> [BACK] - pre-prod - fix/96753 - NAAPA não permitir registro ativo duplicado para o estudante

- src/SME.SGP.Aplicacao/Comandos/ComandosNotificacao.cs
- teste/SME.SGP.Aplicacao.Teste/Comandos/Armazenamento/UploadArquivoCommandTeste.cs
[AB#101104](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101104)
> Ajuste remoção async void

- src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
- src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs
- src/SME.SGP.Dados/Repositorios/RepositorioWorkflowAprovacao.cs
[AB#101112](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101112)
> 101112 - Remoção de cast AsList em retornos IEnumerable

- src/SME.SGP.Api/Controllers/RelatorioController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/PlanejamentoAnual/RelatorioPlanejamentoAnualUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IRelatorioPlanejamentoAnualUseCase.cs
- src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
- src/SME.SGP.Infra.Mensageria/Rotas/RotasRabbitSgpRelatorios.cs
- src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioPlanejamentoAnualDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
> Criação do relatório

- src/SME.SGP.Aplicacao/Commands/RelatorioPAP/SalvarRelatorioPeriodicoRespostaPAP/SalvarRelatorioPeriodicoRespostaPAPCommand.cs
> 101380 - Ao registrar dados e salvar não está ficando gravado no sistema

- src/SME.SGP.Api/SME.SGP.Api.csproj
- src/SME.SGP.Api/appsettings.json
- src/SME.SGP.Auditoria.Worker/Options/TelemetriaOptions.cs
- src/SME.SGP.Dados.ElasticSearch/SME.SGP.Dados.ElasticSearch.csproj
- src/SME.SGP.Dados/Interceptors/DapperInterceptor.cs
- src/SME.SGP.Infra.Mensageria/SME.SGP.Infra.Mensageria.csproj
- src/SME.SGP.Infra.Telemetria/IoC/RegistrarTelemetria.cs
- src/SME.SGP.Infra.Telemetria/Options/TelemetriaOptions.cs
- src/SME.SGP.Infra.Telemetria/SME.SGP.Infra.Telemetria.csproj
- src/SME.SGP.Infra.Telemetria/ServicoTelemetria.cs
- src/SME.SGP.Infra/Interfaces/IServicoLog.cs
- src/SME.SGP.Infra/SME.SGP.Infra.csproj
- src/SME.SGP.Infra/Servicos/ServicoLog.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- src/SME.SGP.IoC/SME.SGP.IoC.csproj
> 101098 - Remoção AppInsights Telemetry da solução SGP

- src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoMatriculaTurma.cs
> fix/96170 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs
> Fix/99703 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/Arquivos/MoverArquivosTemporarios/MoverArquivosTemporariosCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/DeletarArquivo/DeletarArquivoDeRegistroExcluidoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/DeletarArquivo/RemoverArquivosExcluidosCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Ocorrencia/AlterarOcorrencia/AlterarOcorrenciaCommand.cs
- src/SME.SGP.Aplicacao/Commands/Ocorrencia/InserirOcorrencia/InserirOcorrenciaCommand.cs
- src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDadosDashboardFrequenciaPorDre/ObterDadosDashboardFrequenciaPorDreQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterHistoricosDeAlteracoesEncaminhamentoNAAPA/ObterHistoricosDeAlteracoesEncaminhamentoNAAPAQueryHandler.cs
- src/SME.SGP.Dominio/Constantes/ArmazenamentoObjetos.cs
- src/SME.SGP.Dominio/Entidades/Ocorrencia.cs
- src/SME.SGP.Infra.Consts/RegexConstants.cs
- src/SME.SGP.Infra.Utilitarios/UtilRegex.cs
- teste/SME.SGP.Aplicacao.Teste/CasosDeUso/DashboardDiarioBordo/ObterQuantidadeTotalDeDiariosPreenchidosEPendentesPorAnoTurmaUseCaseTeste.cs
[AB#101113](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101113)
> 101113 - Regex pre compilados para nao criar sempre em tempo de execução

- src/SME.SGP.Dominio.Servicos/ServicoObjetivosAprendizagem.cs
[AB#101940](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101940)
> Ajuste de persistência de objetivos

- src/SME.SGP.Dominio.Servicos/ServicoObjetivosAprendizagem.cs
[AB#101940](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101940)
> PRE-PROD --> Correção dos critérios de manutenção dos objetivos do PAP

- scripts/V648__ALTER_TABLE_FECHAMENTO_TURMA_DISCIPLINA_CAMPO_JUSTIFICATIVA.sql
- src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoTurmaDisciplina.cs
- src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/FechamentoTurmaDisciplina/ObterTamanhoCaracteresJustificativaNota/ObterTamanhoCaracteresJustificativaNotaQuery.cs
- src/SME.SGP.Aplicacao/Queries/FechamentoTurmaDisciplina/ObterTamanhoCaracteresJustificativaNota/ObterTamanhoCaracteresJustificativaNotaQueryHandler.cs
[AB#98950](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98950)
> fix/98950 -> r2

- src/SME.SGP.Aplicacao/Queries/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfilQueryHandler.cs
[AB#102195](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102195)
> Ajuste do retorno da API EOL - NoContent

- src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdQuery/ObterPendenciasAulaPorAulaIdQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMes/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
[AB#102054](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102054)
> fix/102054 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#102402](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102402)
> Ajuste da frequência final do regência de classe

- src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdQuery/ObterPendenciasAulaPorAulaIdQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMes/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
[AB#102054](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102054) 
Bug: 102054
> Fix/102054 -> pre prod

- src/SME.SGP.Aplicacao/Consultas/ConsultasPendenciaFechamento.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendenciaFechamento.cs
- src/SME.SGP.Infra/Dtos/PendenciaFechamentoCompletoDto.cs
[AB#95288](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95288)
> fix/95288 -> r2

- src/SME.SGP.Dados/Repositorios/RepositorioPlanoCiclo.cs
- src/SME.SGP.Infra/Dtos/PlanoCicloCompletoDto.cs
[AB#102179](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102179)
> fix/102179 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ObterValidacaoPercusoRAAUseCase.cs
[AB#102440](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102440)
> 102440 - RAA Conferir - Está acusando pendência para crianças inativas

- src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterComponentesCurricularesPorUeAnosModalidadeUseCase/ObterComponentesCurricularesPorUeAnosModalidadeUseCase.cs
[AB#101642](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101642)
> fix/101642 -> pre-prod

- src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#102455](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102455)
> fix/102455 -> r2

- src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
[AB#102312](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102312)
> fix/102312 -> pre-prod

- src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAnualTerritorioSaber.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAnualTerritorioSaber.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAnualTerritorioSaber.cs
[AB#102187](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102187)
> fix/102187 -> r2

- src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#102515](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102515)
> 102515 - Está exigindo objetivos de aprendizagem para turmas de programa

- src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#99649](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99649)
> fix/99649 -> r2

- src/SME.SGP.Aplicacao/Queries/EOL/Aluno/ObterAlunosAtivosTurmaProgramaPapEol/ObterAlunosAtivosTurmaProgramaPapEolQuery.cs
[AB#102359](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102359)
> 102359 - Erro ao selecionar avaliação na tela de listão

- src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#99649](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99649)
> fix/99649 -> pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs
[AB#99647](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99647)
> fix/99647 -> pre-prod

- src/SME.SGP.Aplicacao/Consultas/ConsultasPendenciaFechamento.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendenciaFechamento.cs
- src/SME.SGP.Infra/Dtos/PendenciaFechamentoCompletoDto.cs
[AB#95288](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95288)
> Fix/95288 -> pre-prod 

- src/SME.SGP.Infra/Constantes/ConstantesMenuPermissao.cs
- src/SME.SGP.Infra/Enumerados/Permissao.cs
> Ajustando nomes dos menus

- src/SME.SGP.Infra/Constantes/ConstantesMenuPermissao.cs
- src/SME.SGP.Infra/Enumerados/Permissao.cs
> Removendo menu não utilizado

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#102893](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102893)
> fix/102893 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Abrangencia/VerificarUsuarioLogadoPertenceMesmaUE/VerificarUsuarioLogadoPertenceMesmaUEQuery.cs
- src/SME.SGP.Aplicacao/Queries/Abrangencia/VerificarUsuarioLogadoPertenceMesmaUE/VerificarUsuarioLogadoPertenceMesmaUEQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAbrangencia.cs
[AB#102908](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102908)
> Ajustando para a pesquisa do usuário logado na abrangência da turma do encaminhamento e plano

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/AtualizarTurmaDoEncaminhamentoNAAPAUseCase.cs
Bug 103091
[AB#103091](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103091)
Adicionado foreach para validar todas as turmas que o aluno já foi matriculado, assim garantindo o encaminhamento correto do naapa.
> fix/103091 -> r2

- src/SME.SGP.Aplicacao/Consultas/ConsultasCompensacaoAusencia.cs
[AB#95331](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95331)
> fix/95331 -> r2 (pt.2)

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/NotificarInatividadeDoAtendimentoNAAPAInformacaoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/NotificarInatividadeDoAtendimentoNAAPAPorUeUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/NotificarInatividadeDoAtendimentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/INotificarInatividadeDoAtendimentoNAAPAInformacaoUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/INotificarInatividadeDoAtendimentoNAAPAPorUeUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/INotificarInatividadeDoAtendimentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosNAAPAComInatividadeDeAtendimento/ObterEncaminhamentosNAAPAComInatividadeDeAtendimentoQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosNAAPAComInatividadeDeAtendimento/ObterEncaminhamentosNAAPAComInatividadeDeAtendimentoQueryHandler.cs
- src/SME.SGP.Infra.Mensageria/Rotas/RotasRabbitSgpNAAPA.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/EncaminhamentoNAAPAInformacoesNotificacaoInatividadeAtendimentoDto.cs
- src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarNAAPAUseCaseRabbitSgp.cs
- src/SME.SGP.NAAPA.Worker/WorkerRabbitNAAPA.cs
[AB#102701](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102701)
> 102701 - Criar processo no Worker do agendamento

- src/SME.SGP.Api/Controllers/UsuarioEscolaAquiController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/ObterUsuarioPorCpf/ObterUsuarioPorCpfUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/ObterUsuarioPorCpf/IObterUsuarioPorCpfUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Usuario/ObterUsuarioPorCpfQuery.cs
[AB#101227](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101227)
> fix/101227 -> master

- src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#102980](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102980)
> Fix/102980 -> pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAulaConsulta.cs
- src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
- teste/SME.SGP.TesteIntegracao/WorkfflowAprovacaoNotaFechamento/Ao_aprovar_wf_ultimo_nivel_reposicao_aula.cs
[AB#102727](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102727)
Testes Realizados para consultar se retornava AulaCJ, conforme print abaixo: 
Checklist realizado pelo dev
> fix/102727 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/NotificarInatividadeDoAtendimentoNAAPAInformacaoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/NotificarInatividadeDoAtendimentoNAAPAPorUeUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterResponsaveisPorDreUeNAAPA/ObterResponsaveisPorDreUeNAAPAQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterResponsaveisPorDreUeNAAPA/ObterResponsaveisPorDreUeNAAPAQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/EncaminhamentoNAAPAInformacoesNotificacaoInatividadeAtendimentoDto.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_notificar_responsaveis_por_inatividade_atendimento_naapa.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs
[AB#102712](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102712)
> 102712 - Criar worker de consumo da fila de notificação

- src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasComMatriculasValidas/ObterTurmasComMatriculasValidasQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/ObterTurmasComMatriculasValidasQueryHandlerTeste.cs
[AB#103388](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103388)
> fix/103388 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/CompensacaoAusencia/SalvarCompensacaoAusenciaUseCase.cs
[AB#95331](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95331)
> Fix/95331 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
[AB#95096](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95096)
> Fix/95096 -> pre-prod

- src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAnualTerritorioSaber.cs
[AB#103820](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103820)
> 103820 - Ajuste edição plano anual territorio saber

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasConsideradasNoConselho/ObterTurmasConsideradasNoConselhoQuery.cs
- src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasConsideradasNoConselho/ObterTurmasConsideradasNoConselhoQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/ObterTurmasConsideradasNoConselhoQueryHandlerFake.cs
[AB#103388](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103388)
> fix/103388 pt.2 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/SalvarAtribuicaoCJUseCase.cs
- src/SME.SGP.Aplicacao/Commands/AtribuicaoCJ/InserirAtribuicaoCJ/InserirAtribuicaoCJCommand.cs
- src/SME.SGP.Aplicacao/Commands/AtribuicaoCJ/InserirAtribuicaoCJ/InserirAtribuicaoCJCommandHandler.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/Ao_remover_uma_atribuicao_cj_nao_deve_remover_abrangencia_da_turma.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/ServicosFake/AtribuirPerfilCommandHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/ServicosFake/ObterAtribuicoesPorTurmaEProfessorQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/ServicosFake/PublicarFilaGoogleClassroomCommandHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/ServicosFake/RemoverPerfisUsuarioAtualCommandHandlerFake.cs
[AB#101727](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101727)
> Fix/101727 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasComMatriculasValidas/ObterTurmasComMatriculasValidasQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasConsideradasNoConselho/ObterTurmasConsideradasNoConselhoQuery.cs
- src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasConsideradasNoConselho/ObterTurmasConsideradasNoConselhoQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/ObterTurmasComMatriculasValidasQueryHandlerTeste.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/ObterTurmasConsideradasNoConselhoQueryHandlerFake.cs
[AB#103388](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103388)
> Fix/103388 -> pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAulaConsulta.cs
- src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
- teste/SME.SGP.TesteIntegracao/WorkfflowAprovacaoNotaFechamento/Ao_aprovar_wf_ultimo_nivel_reposicao_aula.cs
[AB#102727](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102727)
> Fix/102727 -> pre-prod

- src/SME.SGP.Aplicacao/Consultas/ConsultasProfessorTurma.cs
- src/SME.SGP.Aplicacao/Queries/AulasPrevistas/ObterAulasPrevistasPorCodigoUe/ObterAulasPrevistasPorCodigoUeQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/FechamentoNota/ObterPorFechamentosTurma/ObterPorFechamentosTurmaQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Github/UltimaVersao/ObterUltimaVersaoQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Notas/ObterNotasPorAlunosAtividadesAvaliativas/ObterNotasPorAlunosAtividadesAvaliativasQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterValorParametroSistemaTipoEAnoQuery/ObterValorParametroSistemaTipoEAnoQueryHandler.cs
[AB#101114](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101114)
> 101114 - Melhoria no uso do cache

- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/SalvarEncaminhamentoAEETurmaAluno/SalvarEncaminhamentoAEETurmaAlunoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/PlanoAEE/SalvarPlanoAEETurmaAluno/SalvarPlanoAEETurmaAlunoCommandHandler.cs
[AB#103821](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103821)
> 103821 -  Plano AEE - Apresentando o aluno na UE antiga

- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs
[AB#103336](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103336)
> 103336 - Plano AEE - Registros duplicados na listagem

- docker-compose.yml
[AB#102956](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102956)
> 104014 Incluso todas as dependencias do SGP

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/NotificarInatividadeDoAtendimentoNAAPAInformacaoUseCase.cs
- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/EncaminhamentoNAAPAInformacoesNotificacaoInatividadeAtendimentoDto.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_notificar_responsaveis_por_inatividade_atendimento_naapa.cs
[AB#104422](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/104422)
> 104422 - Está faltando a sigla da UE na descrição da notificação.

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#104057](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/104057)
> 104057 - Ajuste conversão nota fechamento ed fisica EJA

- src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/SalvarAtribuicaoCJUseCase.cs
- src/SME.SGP.Aplicacao/Commands/AtribuicaoCJ/InserirAtribuicaoCJ/InserirAtribuicaoCJCommand.cs
- src/SME.SGP.Aplicacao/Commands/AtribuicaoCJ/InserirAtribuicaoCJ/InserirAtribuicaoCJCommandHandler.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/Ao_remover_uma_atribuicao_cj_nao_deve_remover_abrangencia_da_turma.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/ServicosFake/AtribuirPerfilCommandHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/ServicosFake/ObterAtribuicoesPorTurmaEProfessorQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/ServicosFake/PublicarFilaGoogleClassroomCommandHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/ServicosFake/RemoverPerfisUsuarioAtualCommandHandlerFake.cs
[AB#101727](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/101727)
> Fix/101727 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ConsultaConselhoClasseRecomendacaoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterDetalhamentoFechamentoConselhoClasseAlunoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/ConselhoClasse/InserirTurmasComplementares/InserirTurmasComplementaresCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs
- src/SME.SGP.Aplicacao/Queries/FechamentoTurma/ObterFechamentoTurmaPorIdAlunoCodigo/ObterFechamentoTurmaPorIdAlunoCodigoQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAluno/ObterConsultaFrequenciaGeralAlunoQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipo/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQuery.cs
- src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipo/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQueryHandler.cs
[AB#104047](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/104047)
> Fix/104047 para Release 2

- src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs
- teste/SME.SGP.TesteIntegracao/ConsolidacaoFrequenciaMensal/Ao_registrar_consolidacao_frequencia_aluno_mensal.cs
> Bug: 104718

- src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
Ajuste na exclusão de turma extinta da sync institucional considerando a tabela de "frequencia_turma_evasao".
> Bug: 104788

- src/SME.SGP.Dados.ElasticSearch/RepositorioElasticBase.cs
- src/SME.SGP.Dados/Interceptors/DapperInterceptor.cs
- src/SME.SGP.Infra.Telemetria/IServicoTelemetria.cs
- src/SME.SGP.Infra.Telemetria/ServicoTelemetria.cs
- teste/SME.SGP.TesteIntegracao/ServicosFakes/TelemetriaFake.cs
[AB#103985](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103985)
> 103985 - Ajustes ServicoTelemetria

- src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
[AB#104047](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/104047)
> Fix/104047 para Release 2 [Lançamento listão não reflete tela de notas] 

- src/SME.SGP.Auditoria.Worker/WorkerRabbitAuditoria.cs
[AB#103983](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103983)
> Clean code na classe de auditoria

- src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs
[AB#95495](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95495)
> Fix/95495 -> r2

- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAluno/ObterConsultaFrequenciaGeralAlunoQueryHandler.cs
[AB#96348](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96348)
> fix/96348 -> r2 (pt.2)

- teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/ServicosFake/ObterTurmaRegularESrmPorAlunoQueryHandlerFake.cs
[AB#103868](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103868)
> 103868 - Ajuste teste integrado

- src/SME.SGP.IoC/Extensions/RegistrarHttpClients.cs
[AB#103987](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103987)
> Adicionando timeout as chamadas HttpClient

- src/SME.SGP.Dominio/Entidades/Turma.cs
- src/SME.SGP.Dominio/Enumerados/Modalidade.cs
- src/SME.SGP.Dominio/Enumerados/ModalidadeTipoCalendario.cs
[AB#104250](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/104250)
> 104250 - Modalidade Nova - CELP

- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs
- teste/SME.SGP.TesteIntegracao/Frequencia/Ao_obter_frequencia_geral_de_aluno.cs
[AB#103941](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103941)
> Fix/103941 pt.2 -> r2

- scripts/V651__ATUALIZAR_PARAMETRO_SISTEMA_NovosTiposUE.sql
[AB#104252](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/104252)
> 104252 - Atualização do parametro para celp

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterTotalAlunosSemFrequenciaPorTurmaBimestreUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConselhoClasse/IObterTotalAlunosSemFrequenciaPorTurmaBimestreUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQuery/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQuery.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQuery/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseConsulta.cs
- teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/RetornarTotalAulasNaoRealizamFrequenciaPorBimestre.cs
[AB#105051](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105051)
> fix/105051 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs
[AB#95495](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95495)
> Fix/95495 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterTotalAlunosSemFrequenciaPorTurmaBimestreUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConselhoClasse/IObterTotalAlunosSemFrequenciaPorTurmaBimestreUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQuery/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQuery.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQuery/ObterTotalAlunosSemFrequenciaPorTurmaBimestreQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseConsulta.cs
- teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/RetornarTotalAulasNaoRealizamFrequenciaPorBimestre.cs
[AB#105051](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105051)
> fix/105051 -> pre-prod

- src/SME.SGP.Dados.ElasticSearch/RepositorioElasticBase.cs
- src/SME.SGP.Dados/Interceptors/DapperInterceptor.cs
- src/SME.SGP.Infra.Telemetria/IServicoTelemetria.cs
- src/SME.SGP.Infra.Telemetria/ServicoTelemetria.cs
- teste/SME.SGP.TesteIntegracao/ServicosFakes/TelemetriaFake.cs
Reverts prefeiturasp/SME-NovoSGP#13460
> Revert "Teste telemetria"

- src/SME.SGP.Infra/Constantes/ConstantesMenuPermissao.cs
- src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#102824](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102824)
> 102824 - Permissionamento relatório dinâmico NAAPA

- scripts/V652__CARGA_QUESTIONARIO_RELATORIO_DINAMICO_ENCAMINHAMENTO_NAAPA.sql
- src/SME.SGP.Dominio/Enumerados/TipoQuestionario.cs
[AB#102830](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102830)
> 102830 - Publicação novo questionário e seções NAAPA

- src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ObterQuestoesRelatorioDinamicoEncaminhamentoNaapaPorModalidadesUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ObterSecoesEncaminhamentosSecaoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoNAAPA/IObterQuestoesRelatorioDinamicoEncaminhamentoNAAPAPorModalidadesUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterQuestoesEncaminhamentoNAAPAPorModalidades/ObterQuestoesRelatorioDinamicoEncaminhamentoNAAPAPorModalidadesQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterQuestoesEncaminhamentoNAAPAPorModalidades/ObterQuestoesRelatorioDinamicoEncaminhamentoNAAPAPorModalidadesQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterSecoesEncaminhamentosSecaoNAAPA/ObterSecoesEncaminhamentosSecaoNAAPAQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterSecoesEncaminhamentosSecaoNAAPA/ObterSecoesEncaminhamentosSecaoNAAPAQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioSecaoEncaminhamentoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSecaoEncaminhamentoNAAPA.cs
- src/SME.SGP.Dominio/Enumerados/TipoQuestionario.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoAee/SecaoQuestionarioDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#102826](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102826)
> End Point SGP busca de questões/opções resposta NAAPA (para filtro avançado)

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterDetalhamentoFechamentoConselhoClasseAlunoUseCase.cs
- src/SME.SGP.Dominio/Entidades/FrequenciaAluno.cs
- src/SME.SGP.Infra/Dtos/FechamentoAcompanhamentoTurmas/DetalhamentoComponentesCurricularesAlunoDto.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/ObterFrequenciasAlunosPorCodigoAlunoCodigoComponentesTurmaQueryHandlerTeste.cs
[AB#99582](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99582)
> Fix/99582 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/DevolverEncaminhamentoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/AtualizarEncaminhamentoAEEEncerrarAutomatico/AtualizarEncaminhamentoAEEEncerrarAutomaticoCommand.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/AtualizarEncaminhamentoAEEEncerrarAutomatico/AtualizarEncaminhamentoAEEEncerrarAutomaticoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaCPEncaminhamentoAEE/GerarPendenciaCPEncaminhamentoAEECommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaProfessorEncaminhamentoAEEDevolvido/GerarPendenciaProfessorEncaminhamentoAEEDevolvidoCommand.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaProfessorEncaminhamentoAEEDevolvido/GerarPendenciaProfessorEncaminhamentoAEEDevolvidoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaProfessorEncaminhamentoAEEDevolvido/GerarPendenciaProfessorEncaminhamentoAEEDevolvidoCommandValidator.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/RegistrarEncaminhamentoAEE/RegistrarEncaminhamentoAeeCommandHandler.cs
[AB#103439](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103439)
> fix/103439 -> r2

- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_obter_questoes_relatorio_dinamico_naapa_por_modalidades.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs
[AB#102826](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102826)
> Adicionando testes

- src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#105423](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105423)
> fix/105423 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#105727](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105727)
> fix/105727 -> r2

- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/PeriodoEstaEmAbertoPAP/PeriodoEstaEmAbertoPAPQueryHandler.cs
[AB#105627](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105627)
> fix/105627 -> pre-prod

- src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#105423](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105423)
> fix/105423 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#105727](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105727)
> fix/105727 -> pre-prod

- scripts/V652__CARGA_QUESTIONARIO_RELATORIO_DINAMICO_ENCAMINHAMENTO_NAAPA.sql
- src/SME.SGP.Api/Controllers/EncaminhamentoNAAPAController.cs
- src/SME.SGP.Api/Controllers/RelatorioDinamicoNAAPAController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/RelatorioDinamicoNAAPA/RelatorioDinamicoObterEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/RelatorioDinamicoNAAPA/IRelatorioDinamicoObterEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Queries/RelatorioDinamicoNAAPA/ObterEncaminhamentoNAAPAParaRelatorioDinamico/ObterEncaminhamentoNAAPAParaRelatorioDinamicoQuery.cs
- src/SME.SGP.Aplicacao/Queries/RelatorioDinamicoNAAPA/ObterEncaminhamentoNAAPAParaRelatorioDinamico/ObterEncaminhamentoNAAPAParaRelatorioDinamicoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRelatorioDinamicoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRelatorioDinamicoNAAPA.cs
- src/SME.SGP.Infra/Dtos/RelatorioDinamicoNAAPA/EncaminhamentoNAAPARelatorioDinamico.cs
- src/SME.SGP.Infra/Dtos/RelatorioDinamicoNAAPA/FiltroComponenteRelatorioDinamicoNAAPA.cs
- src/SME.SGP.Infra/Dtos/RelatorioDinamicoNAAPA/FiltroRelatorioDinamicoNAAPADto.cs
- src/SME.SGP.Infra/Dtos/RelatorioDinamicoNAAPA/RelatorioDinamicoNAAPADto.cs
- src/SME.SGP.Infra/Dtos/RelatorioDinamicoNAAPA/TotalRegistroPorModalidadeRelatorioDinamicoNAAPA.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_obter_encaminhamento_para_relatorio_dinamico_naapa.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs
[AB#102827](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102827)
> 102827 - End Point SGP busca de Encaminhamentos NAAPA filtro avançado

- src/SME.SGP.Dados/Repositorios/RepositorioRelatorioDinamicoNAAPA.cs
- src/SME.SGP.Infra/Dtos/RelatorioDinamicoNAAPA/RelatorioDinamicoNAAPADto.cs
- src/SME.SGP.Infra/Dtos/RelatorioDinamicoNAAPA/TotalRegistroPorModalidadeRelatorioDinamicoNAAPA.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/RelatorioDinamico/Ao_obter_encaminhamento_para_relatorio_dinamico_naapa.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/RelatorioDinamico/Ao_obter_questoes_relatorio_dinamico_naapa_por_modalidades.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/RelatorioDinamico/Ao_obter_total_registros_encaminhamento_para_relatorio_dinamico_naapa.cs
[AB#102828](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102828)
> 102828 - Retornar Totais encaminhamentos, total modalidade e ano

- src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs
[AB#105920](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105920)
> 105920 - Ajuste bug ordenação bimestres am eulas dadas x previstas

- scripts/V654__ADICIONAR_CONFIGURACAO_SEMESTRAL_PAP.sql
[AB#103744](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103744)
> 103744 - Criar script de carga das configurações

- src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorIdsUsuarioLogado/ObterComponentesCurricularesPorIdsUsuarioLogadoQueryHandler.cs
> ajustes no teste de obter aulas do calendário por mês infantil agrup.

- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterRelatorioSemestralTurmaPAPPorAnoSemestre/ObterRelatorioSemestralTurmaPAPPorAnoSemestreQuery.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterRelatorioSemestralTurmaPAPPorAnoSemestre/ObterRelatorioSemestralTurmaPAPPorAnoSemestreQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRelatorioSemestralTurmaPAP.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRelatorioSemestralTurmaPAP.cs
[AB#103762](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103762)
> Criação do query mediator para pesquisa dos ids dos relatórios

- teste/SME.SGP.TesteIntegracao.Aula/Aula/Ao_registrar_aula_recorrente.cs
> ajustes teste aula recorrente para pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/InserirDiarioBordoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/ObterDiarioBordoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/DiarioBordo/AlterarDiarioBordo/AlterarDiarioBordoCommandHandler.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
- src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasDisciplina.cs
- src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDiarioDeBordoPorId/ObterDiarioDeBordoPorIdQueryHandler.cs
- teste/SME.SGP.TesteIntegracao.AEE/EncaminhamentoAEE/Ao_devolver_encaminhamento_cp.cs
- teste/SME.SGP.TesteIntegracao/ComponenteCurricular/Ao_obter_componente_curricular.cs
- teste/SME.SGP.TesteIntegracao/ConsultaDisciplina/Ao_consultar_disciplina.cs
- teste/SME.SGP.TesteIntegracao/ConsultaDisciplina/ServicosFake/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfilQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/ConsultaDisciplina/ServicosFake/ObterParametroSistemaPorTipoEAnoQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/ConsultaDisciplina/ServicosFake/ObterParametrosSistemaHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/ConsultaDisciplina/ServicosFake/ObterTurmaComUeEDrePorCodigoQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/ConsultaDisciplina/ServicosFake/ObterUsuarioLogadoHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/ServicosFakes/ObterAlunosPorTurmaEAnoLetivoQueryHandlerFake.cs
[AB#105992](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105992)
> Fix/105992 -> r2

- teste/SME.SGP.TesteIntegracao/ConsultaDisciplina/Ao_consultar_disciplina.cs
[AB#105992](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105992)
> fix/105992 -> r2 pt2

- teste/SME.SGP.Aplicacao.Teste/CasosDeUso/InserirDiarioBordoUseCaseTeste.cs
- teste/SME.SGP.Aplicacao.Teste/Handlers/AlterarDiarioBordoCommandHandlerTeste.cs
[AB#105992](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105992)
> fix/105992 -> r2 pt3

- src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
> fix/105773 pt.2 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs
[AB#105433](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105433)
> fix/105433 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterDetalhamentoFechamentoConselhoClasseAlunoUseCase.cs
- src/SME.SGP.Infra/Dtos/FechamentoAcompanhamentoTurmas/DetalhamentoComponentesCurricularesAlunoDto.cs
[AB#99582](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99582)
> fix/99582 ->pre-prod

- teste/SME.SGP.TesteIntegracao/ConsultaDisciplina/Ao_consultar_disciplina.cs
[AB#105992](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105992)
> fix/105992 Ajuste de testes -> pre-prod

- src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
- teste/SME.SGP.TesteIntegracao/ServicosFakes/ObterUsuarioLogadoPaai4444444QueryHandlerFake.cs
> ajustes nos testes integração diario de bordo para pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#105761](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105761)
> fix/105761 -> r2

- src/SME.SGP.Dados/Repositorios/RepositorioRelatorioDinamicoNAAPA.cs
[AB#106584](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106584)
> 106584 - Filtro não estava retornando quando o resultado tinha vários valores

- scripts/V657__AJUSTE_OPCIONAIS_QUESTAO_RELATORIO_DINAMICO_NAAPA.sql
[AB#106609](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106609)
[AB#106620](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106620)
> Ajustando obrigatoriedade de campos e ajuste de opcionais

- src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/InserirDiarioBordoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/ObterDiarioBordoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/DiarioBordo/AlterarDiarioBordo/AlterarDiarioBordoCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDiarioDeBordoPorId/ObterDiarioDeBordoPorIdQueryHandler.cs
[AB#105490](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105490)
> fix/105490 -> r2

- scripts/V658__CRIAR_PERFIL_MANUAL_COORDENADOR_CELP.sql
- src/SME.SGP.Dominio/Enumerados/PerfilUsuario.cs
[AB#104254](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/104254)
> Adicionando permissão de Coordenador CELP

- src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilERegenciaAutomaticamente/CriarAulasInfantilERegenciaAutomaticamenteCommandHandler.cs
- teste/SME.SGP.TesteIntegracao.Aula/Aula/Ao_registrar_aula_verifica_se_pode_cadastrar_aula.cs
- teste/SME.SGP.TesteIntegracao.Aula/Aula/ServicosFake/ObterAulasDaTurmaPorTipoCalendarioQueryHandlerFake.cs
[AB#106429](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106429)
> Fix/106429 -> r2

- src/SME.SGP.Dados/Repositorios/RepositorioAulaPrevistaBimestreConsulta.cs
[AB#106707](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106707)
> 106407 - Ajuste componente território aulas dadas x previstas

- src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilERegenciaAutomaticamente/CriarAulasInfantilERegenciaAutomaticamenteCommandHandler.cs
- teste/SME.SGP.TesteIntegracao.Aula/Aula/Ao_registrar_aula_verifica_se_pode_cadastrar_aula.cs
- teste/SME.SGP.TesteIntegracao.Aula/Aula/ServicosFake/ObterAulasDaTurmaPorTipoCalendarioQueryHandlerFake.cs
[AB#106429](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106429)
> Fix/106429 -> pre-prod

- scripts/V670__CRIAR_TABELAS_INFORMATIVO.sql
- src/SME.SGP.Dados/Mapeamentos/InformativoMap.cs
- src/SME.SGP.Dados/Mapeamentos/InformativoPerfilMap.cs
- src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
- src/SME.SGP.Dados/Repositorios/RepositorioInformativo.cs
- src/SME.SGP.Dados/Repositorios/RepositorioInformativoPerfil.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioInformativo.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioInformativoPerfil.cs
- src/SME.SGP.Dominio/Entidades/Informativo.cs
- src/SME.SGP.Dominio/Entidades/InformativoPerfil.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#103960](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103960)
> 103960 - Criar de script BD

- src/SME.SGP.Infra/Constantes/ConstantesMenuPermissao.cs
- src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#103945](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103945)
> 103945 - Menu e permissionamento

- src/SME.SGP.Api/Controllers/InformesController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ObterGruposDeUsuariosUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Informes/IObterGruposDeUsuariosUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EOL/ObterGruposDeUsuarios/ObterGruposDeUsuariosQuery.cs
- src/SME.SGP.Aplicacao/Queries/EOL/ObterGruposDeUsuarios/ObterGruposDeUsuariosQueryHandler.cs
- src/SME.SGP.Aplicacao/SME.SGP.Aplicacao.csproj
- src/SME.SGP.Infra.Consts/ServicosEolConstants.cs
- src/SME.SGP.Infra/Dtos/Informes/GruposDeUsuariosDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/Informes/Ao_obter_grupos_usuarios.cs
- teste/SME.SGP.TesteIntegracao/Informes/Base/InformesBase.cs
- teste/SME.SGP.TesteIntegracao/Informes/ServicosFake/ObterGruposDeUsuariosQueryHandlerFake.cs
[AB#103961](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103961)
> 103961 - Endpoint obter todos os perfis

- scripts/V672__CRIAR_TABELA_CADASTRO_ACESSO_ABAE.sql
- src/SME.SGP.Dados/Mapeamentos/CadastroAcessoABAEMap.cs
- src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
- src/SME.SGP.Dados/Repositorios/RepositorioCadastroAcessoABAE.cs
- src/SME.SGP.Dados/Repositorios/RepositorioCadastroAcessoABAEConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCadastroAcessoABAE.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCadastroAcessoABAEConsulta.cs
- src/SME.SGP.Dominio/Entidades/CadastroAcessoABAE.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#105125](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105125)
> Modelagem (Script DB, Repositório, Entidades e Mapeamento)

- scripts/V671__CRIAR_PERFIL_MANUAL_ABAE.sql
- src/SME.SGP.Dominio/Enumerados/PerfilUsuario.cs
- src/SME.SGP.Infra/Constantes/ConstantesMenuPermissao.cs
- src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#105096](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105096)
[AB#105098](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105098)
> Criação do perfil ABAE

- src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/ExecutarMigracaoRelatorioPAPPorIdUseCase.cs
[AB#106831](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106831)
> 106831 - Retirar o titulo da migração de relatório pap

- src/SME.SGP.Api/Controllers/CEPController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/BuscaCep/BuscaCepUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConselhoClasse/IBuscaCepUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Cep/BuscaCep/ObterCepQuery.cs
- src/SME.SGP.Aplicacao/Queries/Cep/BuscaCep/ObterCepQueryHandler.cs
- src/SME.SGP.Infra/Dtos/CepDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#105341](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105341)
> Criando a busca de cEP

- scripts/V670__CRIAR_TABELAS_INFORMATIVO.sql
- src/SME.SGP.Api/Controllers/InformesController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ObterGruposDeUsuariosUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Informes/SalvarInformesUseCase.cs
- src/SME.SGP.Aplicacao/Commands/Informes/SalvarInformes/SalvarInformesCommand.cs
- src/SME.SGP.Aplicacao/Commands/Informes/SalvarInformes/SalvarInformesCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Informes/SalvarInformesPerfils/SalvarInformesPerfilsCommand.cs
- src/SME.SGP.Aplicacao/Commands/Informes/SalvarInformesPerfils/SalvarInformesPerfilsCommandHandler.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Informes/IObterGruposDeUsuariosUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Informes/ISalvarInformesUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EOL/ObterGruposDeUsuarios/ObterGruposDeUsuariosQuery.cs
- src/SME.SGP.Aplicacao/Queries/EOL/ObterGruposDeUsuarios/ObterGruposDeUsuariosQueryHandler.cs
- src/SME.SGP.Dados/Mapeamentos/InformativoMap.cs
- src/SME.SGP.Dominio/Entidades/Informativo.cs
- src/SME.SGP.Infra.Consts/ServicosEolConstants.cs
- src/SME.SGP.Infra/Dtos/Informes/InformesDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_obter_grupos_usuarios.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_salvar_informes.cs
- teste/SME.SGP.TesteIntegracao/Informe/Base/InformesBase.cs
- teste/SME.SGP.TesteIntegracao/Informe/ServicosFake/ObterGruposDeUsuariosQueryHandlerFake.cs
[AB#103962](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103962)
> 103962 - Endpoint de cadastro

- src/SME.SGP.Aplicacao/Commands/SincronizacaoInstituicional/Turmas/TrataSincronizacaoInstitucionalTurma/TrataSincronizacaoInstitucionalTurmaCommandHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurma.cs
[AB#106929](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106929)
> 106929 - Tratamento atualização semestre turmas canceladas

- src/SME.SGP.Api/Controllers/InformesController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ExcluirInformesUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ObterInformeUseCase.cs
- src/SME.SGP.Aplicacao/Commands/Informes/ExcluirInformes/ExcluirInformesCommand.cs
- src/SME.SGP.Aplicacao/Commands/Informes/ExcluirInformes/ExcluirInformesCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Informes/ExcluirInformesPerfilsPorIdInformes/ExcluirInformesPerfilsPorIdInformesCommad.cs
- src/SME.SGP.Aplicacao/Commands/Informes/ExcluirInformesPerfilsPorIdInformes/ExcluirInformesPerfilsPorIdInformesCommandHandler.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Informes/IExcluirInformesUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Informes/IObterInformeUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Informes/ExisteInformePorId/ExisteInformePorIdQuery.cs
- src/SME.SGP.Aplicacao/Queries/Informes/ExisteInformePorId/ExisteInformePorIdQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Informes/ObterInformesPorId/ObterInformesPorIdQuery.cs
- src/SME.SGP.Aplicacao/Queries/Informes/ObterInformesPorId/ObterInformesPorIdQueryHandler.cs
- src/SME.SGP.Aplicacao/SME.SGP.Aplicacao.csproj
- src/SME.SGP.Dados/Repositorios/RepositorioInformativo.cs
- src/SME.SGP.Dados/Repositorios/RepositorioInformativoPerfil.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioInformativo.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioInformativoPerfil.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioInformes.cs
- src/SME.SGP.Infra/Dtos/Informes/InformesRespostaDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_excluir_informes.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_obter_informe.cs
- teste/SME.SGP.TesteIntegracao/Informe/Base/InformesBase.cs
[AB#103660](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103660)
> 103966 - Endpoint Exclusão

- src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/InserirDiarioBordoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/ObterDiarioBordoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/DiarioBordo/AlterarDiarioBordo/AlterarDiarioBordoCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDiarioDeBordoPorId/ObterDiarioDeBordoPorIdQueryHandler.cs
Bug 107041
[AB#107041](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107041)
> fix/107041 -> r2

- src/SME.SGP.Api/Controllers/InformesController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ObterInformesPorFiltroUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Informes/IObterInformesPorFiltroUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Informes/ObterInformesPorFiltro/ObterInformesPorFiltroQuery.cs
- src/SME.SGP.Aplicacao/Queries/Informes/ObterInformesPorFiltro/ObterInformesPorFiltroQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioInformativo.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioInformativo.cs
- src/SME.SGP.Infra/Dtos/Informes/InformeFiltroDto.cs
- src/SME.SGP.Infra/Dtos/Informes/InformeResumoDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_obter_infomes_filtro.cs
- teste/SME.SGP.TesteIntegracao/Informe/Base/InformesBase.cs
[AB#103967](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103967)
> 103967 - Endpoint de Listagem

- src/SME.SGP.Aplicacao/Comandos/ComandosEvento.cs
- teste/SME.SGP.TesteIntegracao.Aula/Evento/Ao_excluir_um_evento.cs
- teste/SME.SGP.TesteIntegracao.Aula/Evento/ServicosFakes/ObterUsuarioLogadoEventoQueryHandlerFake.cs
[AB#107062](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107062)
> fix/107062 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
[AB#107384](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107384)
> 107384 - Modalidade CELP erro listão

- src/SME.SGP.Aplicacao/Queries/CartaIntencoes/ObterCartaIntencoesNotificacao/ObterCartaIntencoesNotificacaoQueryHandler.cs
[AB#107072](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107072)
> 107072 - Erro interno ao acessar Carta de Intenções

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#105761](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105761)
> Fix/105761 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
- teste/SME.SGP.TesteIntegracao.Aula/Nota/Base/NotaTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Aula/Nota/ServicosFakes/ObterTodosAlunosNaTurmaQueryHandlerFake.cs
[AB#106810](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106810)
> fix/106810 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCase.cs
- teste/SME.SGP.TesteIntegracao.AEE/EncaminhamentoAEE/Ao_editar_Encaminhamento.cs
[AB#106454](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106454)
> fix/106454 -> pre-prod

- src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilERegenciaAutomaticamente/CriarAulasInfantilERegenciaAutomaticamenteCommandHandler.cs
[AB#107410](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107410)
> fix/107410 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterConselhoClasseConsolidadoPorTurmaBimestreUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasseAcompanhamento/ObterAlunosEStatusConselhoClasseConsolidadoPorTurmaEbimestre/ObterAlunosEStatusConselhoClasseConsolidadoPorTurmaEbimestreQueryHandler.cs
[AB#99745](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99745)
> Fix/99745 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
[AB#99745](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/99745)
> Fix/99745 -> preprod

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs
[AB#105433](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105433)
> Fix/105433 -> preprod

- src/SME.SGP.Aplicacao/Comandos/ComandosUsuario.cs
- src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/Ao_logar_com_usuario_professor_infantil.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/ServicosFakes/ObterAbrangenciaCompactaVigenteEolPorLoginEPerfilAutenticacaoQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/ServicosFakes/ObterLoginAtualAutenticacaoQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/ServicosFakes/ObterPerfisPorLoginAutenticacaoQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/ServicosFakes/ObterUsuarioLogadoAutenticacaoQueryHandlerFake.cs
[AB#107447](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107447)
> Fix/107447 -> r2

- src/SME.SGP.Aplicacao/Comandos/ComandosUsuario.cs
- src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/Ao_logar_com_usuario_professor_infantil.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/ServicosFakes/ObterAbrangenciaCompactaVigenteEolPorLoginEPerfilAutenticacaoQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/ServicosFakes/ObterLoginAtualAutenticacaoQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/ServicosFakes/ObterPerfisPorLoginAutenticacaoQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/ServicosFakes/ObterUsuarioLogadoAutenticacaoQueryHandlerFake.cs
[AB#107447](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107447)
> Fix/107447 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/InserirDiarioBordoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/ObterDiarioBordoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/DiarioBordo/AlterarDiarioBordo/AlterarDiarioBordoCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDiarioDeBordoPorId/ObterDiarioDeBordoPorIdQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioAula.cs
[AB#107041](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107041)
> fix/107041 -> pre prod

- src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
[AB#107384](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107384)
> 107384 - Tratamento de erro, para período não encontrado.

- src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterInfoComponentesCurricularesESPorTurmasCodigo/ObterInfoComponentesCurricularesESPorTurmasCodigoQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQueryHandler.cs
[AB#107634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107634)
> Fix/107634 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/SalvarConselhoClasseAlunoNotaUseCase.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioConselhoClasse.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_inserir_nota_numerica_pos_conselho_bimestre.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs
[AB#107474](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107474)
> fix/107474 -> r2

- src/SME.SGP.Aplicacao/Queries/AreaDoConhecimento/ObterAreasConhecimento/ObterAreasConhecimentoQueryHandler.cs
[AB#107666](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107666)
> fix/107666 -> pre-prod

- src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#107932](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107932)
> fix/107932 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#106735](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106735)
> fix/106735 -> r2

- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs
[AB#107922](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107922)
> Fix/107922 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#106735](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106735)
> fix/106735 -> pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioInformativo.cs
- src/SME.SGP.Infra/Dtos/Informes/GruposDeUsuariosDto.cs
[AB#105024](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105024)
> 105024 - guid perfil em busca eol

- src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#107932](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107932)
> fix/107932 -> pre-prod

- src/SME.SGP.Api/Controllers/ConsultaCriancasEstudanteAusentesController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ConsultaCriancasEstudantesAusentes/ObterTurmasAlunosAusentesUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConsultaCriancasEstudantesAusentes/IObterTurmasAlunosAusentesUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Notificacao/INotificarUsuarioUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ConsultaCriancasEstudantesAusentes/ObterTurmasAlunosAusentes/ObterTurmasAlunosAusentesQuery.cs
- src/SME.SGP.Aplicacao/Queries/ConsultaCriancasEstudantesAusentes/ObterTurmasAlunosAusentes/ObterTurmasAlunosAusentesQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConsultaCriancasEstudantesAusentes.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsultaCriancasEstudantesAusentes.cs
- src/SME.SGP.Dominio/Enumerados/EnumAusencias.cs
- src/SME.SGP.Infra/Constantes/ConstantesMenuPermissao.cs
- src/SME.SGP.Infra/Dtos/ConsultaCriancasEstudantesAusentes/AlunosAusentesDto.cs
- src/SME.SGP.Infra/Dtos/ConsultaCriancasEstudantesAusentes/FiltroObterAlunosAusentesDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/ConsultaCriancasEstudantesAusentes/Ao_obter_alunos_ausentes.cs
- teste/SME.SGP.TesteIntegracao/ConsultaCriancasEstudantesAusentes/Base/ConsultaAlunosAusentesBase.cs
- teste/SME.SGP.TesteIntegracao/ConsultaCriancasEstudantesAusentes/ServicosFake/ObterAlunoPorTurmaAlunoCodigoFrequenciaGlobalQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/ConsultaCriancasEstudantesAusentes/ServicosFake/ObterTodosAlunosNaTurmaQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/ConsultaCriancasEstudantesAusentes/ServicosFake/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaFreqGeralQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/ConsultaCriancasEstudantesAusentes/ServicosFake/ObterTurmaItinerarioEnsinoMedioQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#105977](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105977)
> 105977 - End point busca de alunos ausentes

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/SalvarConselhoClasseAlunoNotaUseCase.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioConselhoClasse.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_inserir_nota_numerica_pos_conselho_bimestre.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs
[AB#107474](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107474)
> fix/107474 -> pre-prod

- src/SME.SGP.Api/Controllers/EstudanteController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Aluno/ObterAlunoPorCodigoEolEAnoLetivoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/ObterAnotacaoFrequenciaAlunoPorIdUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasTurma.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/IObterAlunoPorCodigoEolEAnoLetivoUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterDadosAlunos/ObterDadosAlunosQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterDadosAlunosTurma/ObterDadosAlunosTurmaQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterDadosResponsaveisAlunoEol/ObterDadosResponsaveisAlunoEolQuery.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterDadosResponsaveisAlunoEol/ObterDadosResponsaveisAlunoEolQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaFrequenciaAulas/ObterListaFrequenciaAulasQueryHandler.cs
- src/SME.SGP.Dominio/Enumerados/EnumTipoTelefone.cs
- src/SME.SGP.Dominio/Enumerados/TipoResponsavel.cs
- src/SME.SGP.Infra.Consts/ServicosEolConstants.cs
- src/SME.SGP.Infra/Dtos/Aluno/DadosResponsavelAlunoDto.cs
- src/SME.SGP.Infra/Dtos/Aluno/DadosResponsavelFiliacaoAlunoDto.cs
- src/SME.SGP.Infra/Dtos/AlunoReduzidoDto.cs
- src/SME.SGP.Infra/Dtos/TelefonesDto.cs
- teste/SME.SGP.TesteIntegracao/ConsultaCriancasEstudantesAusentes/Ao_obter_dados_responsaveis_filiacao_aluno.cs
- teste/SME.SGP.TesteIntegracao/ConsultaCriancasEstudantesAusentes/ServicosFake/ObterDadosResponsaveisAlunoEolQueryHandlerFake.cs
[AB#105978](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105978)
> 105978 - End point busca de dados adicionais das filiações do aluno

- src/SME.SGP.Aplicacao/Queries/EOL/TurmaDisciplina/PodePersistirTurmaDisciplina/PodePersistirTurmaDisciplinaQueryHandler.cs
[AB#107876](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107876)
> Fix/107876 -> pre-prod

- src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs
[AB#107876](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107876)
> fix/107876 -> pre-prod (pt.2)

- scripts/V681__ATUALIZAR_QUESTOES_ENCAMINHAMENTO_NAAPA.sql
[AB#107645](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107645)
> 107645 - Criar script de alterações das questões

- Jenkinsfile
Integrado Jenkins com Werbhook Teams
> Integrado Jenkins com Werbhook Teams

- src/SME.SGP.Aplicacao/Queries/Questionario/ObterQuestoesPorQuestionarioPorId/ObterQuestoesPorQuestionarioPorIdQueryHandler.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_obter_encaminhamento_itinerancia.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs
[AB#107646](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107646)
> 107646 - Tratar impacto na apresentação de opções de respostas excluídos

- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs
[AB#107922](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107922)
> fix/107922 -> pre-prod

- src/SME.SGP.Aplicacao/Queries/Aula/ObterPodeCadastrarAulaPorData/ObterPodeCadastrarAulaPorDataQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterInfoComponentesCurricularesESPorTurmasCodigo/ObterInfoComponentesCurricularesESPorTurmasCodigoQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterFimPeriodoRecorrencia/ObterFimPeriodoRecorrenciaQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/ComponentesTurmas/ObterInfoComponentesCurricularesESPorTurmasCodigoQueryHandlerTeste.cs
[AB#107634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107634)
> Fix/107634 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ExecutarNotificacaoInformativoUsuariosUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Usuario/ObterRfsUsuariosPorPerfisDreUe/ObterRfsUsuariosPorPerfisDreUeQuery.cs
- src/SME.SGP.Aplicacao/Queries/Usuario/ObterRfsUsuariosPorPerfisDreUe/ObterRfsUsuariosPorPerfisDreUeQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioInformativo.cs
- src/SME.SGP.Infra.Consts/ServicosEolConstants.cs
[AB#105024](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105024)
> 105024 - Busca de usuarois por perfil eol - utilizando carga elastic

- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ExecutarNotificacaoInformativoUsuarioUseCase.cs
- src/SME.SGP.Aplicacao/Commands/Notificacao/NotificarUsuario/NotificarUsuarioCommandHandler.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_executar_notificacao_Informes_usuario.cs
- teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#105056](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105056)
> 105056 - Ajuste no codigo da notificação para informes

- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ExecutarNotificacaoInformativoUsuarioUseCase.cs
[AB#108403](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/108403)
> 108403 - Tratamento busca de id usuário

- src/SME.SGP.Dominio/Entidades/Notificacao.cs
[AB#108403](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/108403)
> 108403 - Ajuste marcar msg como lida com tipo informe

- src/SME.SGP.Aplicacao/Commands/FechamentoAcompanhamentoTurmas/ConsolidacaoTurmaConselhoClasseAlunoAnoAnterior/ConsolidacaoTurmaConselhoClasseAlunoAnosAnterioresCommandHandler.cs
[AB#107928](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107928)
> fix/107928 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Fechamento/ObterFechamentosPorTurmaPeriodoCC/ObterFechamentoPorTurmaPeriodoCCQuery.cs
- src/SME.SGP.Aplicacao/Queries/Fechamento/ObterFechamentosPorTurmaPeriodoCC/ObterFechamentoPorTurmaPeriodoCCQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoTurmaConsulta.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Ao_obter_nota.cs
[AB#107981](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107981)
> Fix/107981 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ExecutarNotificacaoInformativoUsuarioUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Informes/InformeFoiExcluido/InformeFoiExcluidoQuery.cs
- src/SME.SGP.Aplicacao/Queries/Informes/InformeFoiExcluido/InformeFoiExcluidoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioInformativo.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioInformativo.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_executar_notificacao_Informes_usuario.cs
[AB#108698](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/108698)
> 108698 - Ao excluir informes não está sumindo as notificações que foi enviada para o usuário.

- teste/SME.SGP.TesteIntegracao.Aula/DiarioBordo/ServicosFakes/ObterProfessoresTitularesDasTurmasQueryHandlerFakeCartaIntencoes.cs
- teste/SME.SGP.TesteIntegracao/CartaIntencoes/Ao_abrir_a_carta_de_intencoes.cs
- teste/SME.SGP.TesteIntegracao/CartaIntencoes/ServicosFakes/ObterFuncionariosPorUeECargoQueryHandlerFakeCartaIntencoes.cs
- teste/SME.SGP.TesteIntegracao/CartaIntencoes/ServicosFakes/ObterProfessorTitularPorTurmaEComponenteQueryHandlerFakeCartaIntencoes.cs
- teste/SME.SGP.TesteIntegracao/CartaIntencoes/ServicosFakes/ObterProfessoresTitularesDasTurmasQueryHandlerFakeCartaIntencoes.cs
- teste/SME.SGP.TesteIntegracao/CartaIntencoes/ServicosFakes/ObterUsuarioLogadoHandlerFakeCartaIntencoes.cs
- teste/SME.SGP.TesteIntegracao/CartaIntencoes/ServicosFakes/ObterUsuariosNotificarCartaIntencoesObservacaoQueryHandlerFake.cs
> Fix/108273 -> r2

- scripts/V682__REGISTRO_BUSCA_ATIVA_CREATE.sql
- scripts/V683__CARGA_QUESTIONARIO_REGISTRO_ACAO_BUSCA_ATIVA.sql
[AB#106554](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106554)
> 106554 - Publicação de seção, questionário e questões busca ativa

- teste/SME.SGP.TesteIntegracao/ConsolidacaoConselhoDeClasse/Ao_consolidar_turma_conselho_classe.cs
- teste/SME.SGP.TesteIntegracao/ConsolidacaoConselhoDeClasse/ServicosFakes/ObterMatriculasAlunoNaTurmaQueryHandlerFakeConslidacaoConselho.cs
Renomeando classe fake para corrigir o erro de ambiguidade.
> Bug: 107921

- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/Ao_cadastrar_editar_registro_acao_busca_ativa.cs
- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/Base/RegistroAcaoBuscaAtivaTesteBase.cs
[AB#106555](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106555)
> 106555 - Teste base para novas questões/questionário

- src/SME.SGP.Api/Controllers/BuscaAtivaController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/BuscaAtiva/ObterSecoesRegistroAcaoSecaoUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/BuscaAtiva/IObterSecoesRegistroAcaoSecaoUseCase.cs
- src/SME.SGP.Aplicacao/Queries/BuscaAtiva/ObterSecoesRegistroAcaoSecao/ObterSecoesRegistroAcaoSecaoQuery.cs
- src/SME.SGP.Aplicacao/Queries/BuscaAtiva/ObterSecoesRegistroAcaoSecao/ObterSecoesRegistroAcaoSecaoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioSecaoRegistroAcaoBuscaAtiva.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/Ao_listar_registros_acao_busca_ativa.cs
- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/Base/RegistroAcaoBuscaAtivaTesteBase.cs
[AB#106569](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106569)
> 106569 - Busca de seções registro ação

- src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasNotasConceitos.cs
- src/SME.SGP.Aplicacao/Queries/TipoNota/ObterTipoNotaPorTurmaData/ObterTipoNotaPorTurmaQueryHandler.cs
- src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs
- src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_inserir_nota_conceito_pos_conselho_bimestre.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_inserir_nota_conceito_pos_conselho_bimestre_final.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoBimestre/Ao_alterar_nota_conceito.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Ao_lancar_nota_conceito.cs
[AB#104256](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/104256)
> 104256 - Permitir cadastro de nota tipo conceito para turma celp.

- src/SME.SGP.Api/Controllers/BuscaAtivaController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/BuscaAtiva/ExcluirRegistroAcaoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/BuscaAtiva/ExcluirRegistroAcao/ExcluirRegistroAcaoCommand.cs
- src/SME.SGP.Aplicacao/Commands/BuscaAtiva/ExcluirRegistroAcao/ExcluirRegistroAcaoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/BuscaAtiva/ExcluirRegistroAcaoPorSecaoId/ExcluirRegistroAcaoPorSecaoIdCommand.cs
- src/SME.SGP.Aplicacao/Commands/BuscaAtiva/ExcluirRegistroAcaoPorSecaoId/ExcluirRegistroAcaoPorSecaoIdCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/BuscaAtiva/ExcluirRespostaRegistroAcaoPorQuestaoId/ExcluirRespostaRegistroAcaoPorQuestaoIdCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/BuscaAtiva/ExcluirSecoesRegistroAcaoPorRegistroAcaoId/ExcluirSecoesRegistroAcaoPorRegistroAcaoIdCommand.cs
- src/SME.SGP.Aplicacao/Commands/BuscaAtiva/ExcluirSecoesRegistroAcaoPorRegistroAcaoId/ExcluirSecoesRegistroAcaoPorRegistroAcaoIdCommandHandler.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/BuscaAtiva/IExcluirRegistroAcaoUseCase.cs
- src/SME.SGP.Dados/Repositorios/RepositorioQuestaoRegistroAcaoBuscaAtiva.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRegistroAcaoBuscaAtiva.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRegistroAcaoBuscaAtivaSecao.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRespostaRegistroAcaoBuscaAtiva.cs
- src/SME.SGP.Dados/Repositorios/RepositorioSecaoRegistroAcaoBuscaAtiva.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroAcaoBuscaAtiva.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroAcaoBuscaAtivaSecao.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRespostaRegistroAcaoBuscaAtiva.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSecaoRegistroAcaoBuscaAtiva.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/Ao_excluir_registro_acao_busca_ativa.cs
- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/Base/RegistroAcaoBuscaAtivaTesteBase.cs
[AB#106576](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106576)
> 106576 - Exclusao de Registro de Ação com teste integrado

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/SalvarConselhoClasseAlunoRecomendacaoUseCase.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs
- src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
- src/SME.SGP.Dominio/Entidades/Turma.cs
[AB#104259](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/104259)
> 104259 - Tratar emissão de relatório de boletim simples e detalhado

- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ExecutarNotificacaoInformativoUsuarioUseCase.cs
- src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoConsulta.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_executar_notificacao_Informes_usuario.cs
[AB#109308](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109308)
> 109308 - Turma Celp não deve apresentar parecer conclusivo.

- src/SME.SGP.Aplicacao/CasosDeUso/TipoCalendario/BuscarTiposCalendarioPorDescricaoUseCase.cs
[AB#109520](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109520)
> 109520 - Lista de Calendário escolar habilitar para perfil celp

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCase.cs
- teste/SME.SGP.TesteIntegracao.AEE/EncaminhamentoAEE/Ao_editar_Encaminhamento.cs
[AB#109314](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109314)
> fix/109314 -> r2

- src/SME.SGP.Aplicacao/Queries/CartaIntencoes/ObterCartaIntencoesNotificacao/ObterCartaIntencoesNotificacaoQueryHandler.cs
- teste/SME.SGP.TesteIntegracao.Aula/DiarioBordo/ServicosFakes/ObterProfessoresTitularesDasTurmasQueryHandlerFakeCartaIntencoes.cs
- teste/SME.SGP.TesteIntegracao/CartaIntencoes/Ao_abrir_a_carta_de_intencoes.cs
- teste/SME.SGP.TesteIntegracao/CartaIntencoes/ServicosFakes/ObterFuncionariosPorUeECargoQueryHandlerFakeCartaIntencoes.cs
- teste/SME.SGP.TesteIntegracao/CartaIntencoes/ServicosFakes/ObterProfessorTitularPorTurmaEComponenteQueryHandlerFakeCartaIntencoes.cs
- teste/SME.SGP.TesteIntegracao/CartaIntencoes/ServicosFakes/ObterProfessoresTitularesDasTurmasQueryHandlerFakeCartaIntencoes.cs
- teste/SME.SGP.TesteIntegracao/CartaIntencoes/ServicosFakes/ObterUsuarioLogadoHandlerFakeCartaIntencoes.cs
- teste/SME.SGP.TesteIntegracao/CartaIntencoes/ServicosFakes/ObterUsuariosNotificarCartaIntencoesObservacaoQueryHandlerFake.cs
[AB#108273](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/108273)
> Fix/108273 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCase.cs
- teste/SME.SGP.TesteIntegracao.AEE/EncaminhamentoAEE/Ao_editar_Encaminhamento.cs
[AB#109314](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109314)
> fix/109314 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ObterValidacaoPercusoRAAUseCase.cs
[AB#109677](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109677)
> fix/109677 -> r2

- src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
- src/SME.SGP.Dominio/Entidades/Turma.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Ao_lancar_nota_aluno_inativo_ano_anterior.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/ServicosFakes/ObterPeriodoFechamentoPorCalendarioIdEBimestreQueryHandlerFake.cs
[AB#109285](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109285)
> Fix/109285 -> r2

- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Ao_obter_nota.cs
> ajuste nos testes de integração "Ao_obter_nota" para r2

- src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ObterValidacaoPercusoRAAUseCase.cs
[AB#109677](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109677)
> Fix/109677 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaFrequenciaUseCase.cs
[AB#105191](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105191)
> 105191 -  Tratar relatórios celp

- src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/NotasEConceitosFinais/RelatorioNotasEConceitosFinaisUseCase.cs
[AB#105193](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105193)
> 105193 - Ajuste relatório notas e conceitos finais

- src/SME.SGP.Api/Controllers/BuscaAtivaController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/BuscaAtiva/AtualizarDadosUsuarioUseCase.cs
- src/SME.SGP.Aplicacao/Commands/Aluno/AtualizarDadosResponsavelAlunoEol/AtualizarDadosResponsavelAlunoEolCommand.cs
- src/SME.SGP.Aplicacao/Commands/Aluno/AtualizarDadosResponsavelAlunoEol/AtualizarDadosResponsavelAlunoEolCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Aluno/AtualizarDadosResponsavelAlunoProdam/AtualizarDadosResponsavelAlunoProdamCommand.cs
- src/SME.SGP.Aplicacao/Commands/Aluno/AtualizarDadosResponsavelAlunoProdam/AtualizarDadosResponsavelAlunoProdamCommandHandler.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/BuscaAtiva/IAtualizarDadosUsuarioUseCase.cs
- src/SME.SGP.Aplicacao/Queries/EOL/Aluno/ObterDadosResponsavel/ObterDadosResponsavelQuery.cs
- src/SME.SGP.Aplicacao/Queries/EOL/Aluno/ObterDadosResponsavel/ObterDadosResponsavelQueryHandler.cs
- src/SME.SGP.Infra.Consts/ServicosEolConstants.cs
- src/SME.SGP.Infra.Consts/ServicosProdamConstants.cs
- src/SME.SGP.Infra/Dtos/Aluno/DadosResponsavelAlunoBuscaAtivaDto.cs
- src/SME.SGP.Infra/Dtos/Aluno/DadosResponsavelAlunoEolDto.cs
- src/SME.SGP.Infra/Dtos/Aluno/DadosResponsavelAlunoProdamDto.cs
- src/SME.SGP.Infra/Dtos/RegistroAcaoBuscaAtiva/AtualizarDadosUsuarioDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/Ao_atualizar_dados_usuario.cs
- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/ServicosFakes/ObterDadosResponsavelQueryHandlerFake.cs
[AB#109582](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109582)
> 109582 - Criar end point busca ativa para atualização de dados responsáveis

- src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
- src/SME.SGP.Dominio/Entidades/Turma.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Ao_lancar_nota_aluno_inativo_ano_anterior.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Ao_obter_nota.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/ServicosFakes/ObterPeriodoFechamentoPorCalendarioIdEBimestreQueryHandlerFake.cs
[AB#109285](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109285)
> Fix/109285 -> pre-prod

- src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs
[AB#109046](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109046)
> Fix/109046 -> pre-prod

- src/SME.SGP.Aplicacao/Commands/Aluno/AtualizarDadosResponsavelAlunoEol/AtualizarDadosResponsavelAlunoEolCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Aluno/AtualizarDadosResponsavelAlunoProdam/AtualizarDadosResponsavelAlunoProdamCommandHandler.cs
- src/SME.SGP.Infra.Consts/ServicosProdamConstants.cs
- src/SME.SGP.Infra.Mensageria/Options/ConfiguracaoProdamOptions.cs
- src/SME.SGP.Infra/Utilitarios/NullToEmptyStringResolver.cs
- src/SME.SGP.Infra/Utilitarios/NullToEmptyStringValueProvider.cs
- src/SME.SGP.IoC/Extensions/RegistrarHttpClients.cs
[AB#109575](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109575)
> 109575 - Registrar config http Client PRODAM

- src/SME.SGP.Aplicacao/CasosDeUso/Aluno/ObterAlunoPorCodigoEolEAnoLetivoUseCase.cs
- src/SME.SGP.Infra/Dtos/Aluno/DadosResponsavelAlunoDto.cs
- src/SME.SGP.Infra/Dtos/Aluno/DadosResponsavelFiliacaoAlunoDto.cs
[AB#109600](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109600)
> 109600 - Adicionar CPF no retorno end point de responsável

- src/SME.SGP.Aplicacao/Queries/DashBoard/ObterDashBoardPorPerfil/ObterDashBoardPorPerfilQueryHandler.cs
- src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#105359](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/105359)
> 105359 - Adição casos de uso ABAE Dash SGP

- src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
[AB#110229](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110229)
> Fix/110229 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/SalvarConselhoClasseAlunoNotaUseCase.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/ServicosFakes/ObterAlunosAtivosPorTurmaCodigoQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/ServicosFakes/ObterTodosAlunosNaTurmaQueryHandlerFake.cs
[AB#110225](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110225)
> Fix/110225 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/BuscaAtiva/RegistrarRegistroAcaoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/CompensacaoAusencia/SalvarCompensacaoAusenciaUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterSinteseConselhoDeClasseUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ExecutaConsolidacaoDiariaDashBoardFrequenciaPorTurmaUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RegistrarEncaminhamentoAEEUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciaPorIdUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciasUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAula/ExcluirPlanoAulaUseCase.cs
- src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaRecorrente/AlterarAulaRecorrenteCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Fechamento/GerarPendenciasFechamento/GerarPendenciasFechamentoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Itinerancia/CriarEventoItineranciaPAAI/CriarEventoItineranciaPAAICommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Notificacao/NotificarPeriodoFechamentoDre/NotificarPeriodoFechamentoDreCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/PendenciaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivosCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/NotificarEncerramentoPlanoAEE/NotificarEncerramentoPlanoAEECommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/PlanoAEE/PlanoAEEResposta/SalvarPlanoAEERespostaCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/AprovacaoNotaConselhoCommandBase.cs
- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/AprovarWorkflowAlteracaoNotaConselho/AprovarWorkflowAlteracaoNotaConselhoCommandHandler.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasAtribuicoes.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAnualTerritorioSaber.cs
[AB#110438](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110438)
> 110438 - Remove this unused method parameter

- src/SME.SGP.Aplicacao/CasosDeUso/Aula/PodeCadastrarAulaUseCase.cs
- src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaUnica/AlterarAulaUnicaCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/Aula/PodeCadastrarAulaNoDia/PodeCadastrarAulaNoDiaQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/Aulas/PodeCadastrarAulaNoDia/PodeCadastrarAulaNoDiaQueryHandlerTeste.cs
[AB#108732](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/108732)
> Fix/108732 -> r2

- src/SME.SGP.Api/Controllers/DashboardFrequenciaController.cs
- src/SME.SGP.Api/Controllers/RecuperacaoParalelaController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterDadosDashboardFrequenciaDiariaPorAnoTurmaUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterDadosDashboardFrequenciaSemanalMensalPorAnoTurmaUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentosAEEUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ObterEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterComunicadosParaFiltro/ObterComunicadosParaFiltroDaDashboardUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ObterTurmasFechamentoAcompanhamentoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasPorPeriodoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativa/ImportarAtividadeGsa/ImportarAtividadeGsaCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/SalvarAtividadeInfantil/SalvarAtividadeInfantilCommand.cs
- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivoCommand.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasRecuperacaoParalela.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFrequencia/IObterDadosDashboardFrequenciaDiariaPorAnoTurmaUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFrequencia/IObterDadosDashboardFrequenciaSemanalMensalPorAnoTurmaUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultaRecuperacaoParalela.cs
- src/SME.SGP.Aplicacao/Queries/Abrangencia/VerificarUsuarioLogadoPertenceMesmaUE/VerificarUsuarioLogadoPertenceMesmaUEQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDadosDashboardFrequenciaPorAnoTurma/ObterDadosDashboardFrequenciaDiariaPorAnoTurmaQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterFrequenciasConsolidadasPorTurmaMensalSemestral/ObterFrequenciasConsolidadasPorTurmaMensalSemestralQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterEncaminhamentosAee/ObterEncaminhamentosAEEQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosNAAPA/ObterEncaminhamentosNAAPAQuery.cs
- src/SME.SGP.Aplicacao/Queries/EscolaAqui/ObterComunicadosParaFiltro/ObterComunicadosParaFiltroDaDashboardQuery.cs
- src/SME.SGP.Aplicacao/Queries/FechamentoAcompanhamentoTurmas/ObterTurmasFechamentoAcompanhamento/ObterTurmasFechamentoAcompanhamentoQuery.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaFrequenciaAulas/ObterListaFrequenciaAulasQuery.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRecuperacaoParalela.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRecuperacaoParalela.cs
- src/SME.SGP.Infra/Dtos/Frequencia/FiltroFrequenciaAulasDto.cs
- src/SME.SGP.Infra/Dtos/Grafico/Frequencia/FrequenciasConsolidadacaoPorTurmaEAnoDto.cs
[AB#110636](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110636)
> 110636 - Constructor has x parameters, which is greater than the 7 authorized.

- src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciasUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasNotificacao.cs
- src/SME.SGP.Aplicacao/Queries/Itinerancia/ObterItinerancias/ObterItineranciasQuery.cs
- src/SME.SGP.Aplicacao/Queries/Notificacoes/ObterNotificacoes/ObterNotificacoesQuery.cs
- src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterIndicativoPendenciasAulasPorTipo/ObterIndicativoPendenciasAulasPorTipoQuery.cs
- src/SME.SGP.Aplicacao/Queries/PlanoAula/ObterPlanoAulasPorTurmaEComponentePeriodo/ObterPlanoAulasPorTurmaEComponentePeriodoQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/Listao/ObterIndicativoPendenciasAulasPorTipoQueryHandlerTeste.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/ConsolidacaoDashboardFrequenciaTurma/Ao_obter_consolidacao_dashboard_diaria_semanal_mensal_frequencia.cs
[AB#110688](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110688)
> 110688 - Method has X parameters, which is greater than the 7 authorized.

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterSinteseConselhoDeClasseUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoComponentePorTurmas/ObterFrequenciasAlunoComponentePorTurmasQuery.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoComponentePorTurmas/ObterFrequenciasAlunoComponentePorTurmasQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
[AB#110487](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110487)
> Fix/110487 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/ListarAtribuicoesCJPorFiltroUseCase.cs
- src/SME.SGP.Infra/Dtos/AtribuicaoCJListaRetornoDto.cs
[AB#110722](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110722)
> 110722 - Ajuste busca de prof cjs integração SGP

- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoConsulta.cs
[AB#110635](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110635)
> fix/110635 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/Aula/PodeCadastrarAulaUseCase.cs
- src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaUnica/AlterarAulaUnicaCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/Aula/PodeCadastrarAulaNoDia/PodeCadastrarAulaNoDiaQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/Aulas/PodeCadastrarAulaNoDia/PodeCadastrarAulaNoDiaQueryHandlerTeste.cs
[AB#108732](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/108732)
> Fix/108732 -> pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoConsulta.cs
[AB#110635](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110635)
> fix/110635 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterSinteseConselhoDeClasseUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoComponentePorTurmas/ObterFrequenciasAlunoComponentePorTurmasQuery.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoComponentePorTurmas/ObterFrequenciasAlunoComponentePorTurmasQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
[AB#110487](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110487)
> Fix/110487 -> pre-prod

- src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoConsulta.cs
[AB#110970](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110970)
> Fix/110970 -> pre-prod

- src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoConsulta.cs
[AB#110970](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110970)
> fix/110970 -> master

- src/SME.SGP.Dados/Repositorios/RepositorioAcompanhamentoTurma.cs
Ajuste ao obter o percurso da turma desconsiderando os registros excluídos.
> Bug: 111019

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ObterQuestoesRelatorioDinamicoEncaminhamentoNaapaPorModalidadesUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/RelatorioDinamicoNAAPA/RelatorioDinamicoObterEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Queries/RelatorioDinamicoNAAPA/ObterEncaminhamentoNAAPAParaRelatorioDinamico/ObterEncaminhamentoNAAPAParaRelatorioDinamicoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRelatorioDinamicoNAAPA.cs
[AB#110405](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110405)
> 110405 - Ajustes filtro lista modalidades -99

- src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
- src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
[AB#111046](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111046)
> Fix/111046 -> r2

- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/RelatorioDinamico/Ao_obter_encaminhamento_para_relatorio_dinamico_naapa.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/RelatorioDinamico/Ao_obter_total_registros_encaminhamento_para_relatorio_dinamico_naapa.cs
[AB#110405](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110405)
> 110405 - Ajustes teste integrado

- src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasComMatriculaValidasParaValidarConselho/ObterTurmasComMatriculaValidasParaValidarConselhoQueryHandler.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_verificar_turmas_com_matriculas_validas_para_conselho_de_classe.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/ServicosFakes/ObterMatriculasAlunoNaTurmaQueryHandlerFakeSituacaoVinculoIndevido.cs
[AB#111018](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111018)
> Fix/111018 -> pre-prod

- src/SME.SGP.Metrica.Worker/Entidade/RegistrosFrequenciaDiario.cs
- src/SME.SGP.Metrica.Worker/Repositorios/Interfaces/IRepositorioRegistrosFrequencia.cs
- src/SME.SGP.Metrica.Worker/Repositorios/Interfaces/IRepositorioSGPConsulta.cs
- src/SME.SGP.Metrica.Worker/Repositorios/RepositorioRegistrosFrequencia.cs
- src/SME.SGP.Metrica.Worker/Repositorios/RepositorioSGPConsulta.cs
- src/SME.SGP.Metrica.Worker/Rotas/RotasRabbitMetrica.cs
- src/SME.SGP.Metrica.Worker/Startup.cs
- src/SME.SGP.Metrica.Worker/UseCases/Interfaces/IRegistrosFrequenciaEfetuadosUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/RegistrosFrequenciaEfetuadosUseCase.cs
- src/SME.SGP.Metrica.Worker/WorkerRabbitMetrica.cs
[AB#108468](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/108468)
> 108468 - Geração de metricas registros frequencia

- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoConsulta.cs
[AB#111144](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111144)
> fix/111144 -> pre-prod

- src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
- src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoBimestre/Ao_lancar_nota_ano_anterior.cs
[AB#111046](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111046)
> Fix/111046 -> master

- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoConsulta.cs
[AB#111144](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111144)
> fix/111144 -> master

- src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#110227](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110227)
> Ajuste fix/110227 -> r2

- src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#110227](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110227)
> fix/110227 -> r2

- src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/Nota/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandlerTeste.cs
[AB#110227](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110227)
> Fix/110227 -> pre-prod

- src/SME.SGP.Infra.Mensageria/Worker/WorkerRabbitSGP.cs
- src/SME.SGP.Metrica.Worker/Entidade/AulasCJMensal.cs
- src/SME.SGP.Metrica.Worker/Repositorios/Interfaces/IRepositorioAulasCJMensal.cs
- src/SME.SGP.Metrica.Worker/Repositorios/Interfaces/IRepositorioSGPConsulta.cs
- src/SME.SGP.Metrica.Worker/Repositorios/RepositorioAulasCJMensal.cs
- src/SME.SGP.Metrica.Worker/Repositorios/RepositorioSGPConsulta.cs
- src/SME.SGP.Metrica.Worker/Rotas/RotasRabbitMetrica.cs
- src/SME.SGP.Metrica.Worker/Startup.cs
- src/SME.SGP.Metrica.Worker/UseCases/AulasCJMensalUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/DevolutivasDiarioBordoMensalUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/DiariosBordoDiarioUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/Interfaces/IAulasCJMensalUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/RegistrosFrequenciaDiarioUseCase.cs
- src/SME.SGP.Metrica.Worker/WorkerRabbitMetrica.cs
[AB#108477](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/108477)
> 108477 - Geração de métricas qdade aulas cj mes

- src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/Nota/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandlerTeste.cs
[AB#110227](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110227)
> Fix/110227 -> master

- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarAtualPorTurma/ObterPeriodoEscolarAtualPorTurmaQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolarConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoEscolarConsulta.cs
Ajuste para obter o período desconsiderando o GMT na comparação da data atual com os períodos escolares.
> Bug: 111220

- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_validar_informacoes_card_aluno.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/Frequencia/Ao_inserir_frequencia_professor_cj.cs
[AB#111336](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111336)
> 111336 - Correção teste integrados

- src/SME.SGP.Infra/Dtos/FiltroDataDto.cs
- src/SME.SGP.Metrica.Worker/Entidade/AcessosDiario.cs
- src/SME.SGP.Metrica.Worker/Entidade/AulasCJMensal.cs
- src/SME.SGP.Metrica.Worker/Entidade/DevolutivasDiarioBordoMensal.cs
- src/SME.SGP.Metrica.Worker/Entidade/DiariosBordoDiario.cs
- src/SME.SGP.Metrica.Worker/Entidade/EncaminhamentosAEEMensal.cs
- src/SME.SGP.Metrica.Worker/Entidade/PlanosAEEMensal.cs
- src/SME.SGP.Metrica.Worker/Entidade/PlanosAulaDiario.cs
- src/SME.SGP.Metrica.Worker/Entidade/RegistrosFrequenciaDiario.cs
- src/SME.SGP.Metrica.Worker/UseCases/AcessosDiarioSGPUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/AulasCJMensalUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/DevolutivasDiarioBordoMensalUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/DiariosBordoDiarioUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/EncaminhamentosAEEMensalUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/PlanosAEEMensalUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/PlanosAulaDiarioUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/RegistrosFrequenciaDiarioUseCase.cs
[AB#109141](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109141)
> 109141 - Ajustes para noa receber param data do agendador

- src/SME.SGP.Metrica.Worker/UseCases/AcessosDiarioSGPUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/AulasCJMensalUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/DevolutivasDiarioBordoMensalUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/DiariosBordoDiarioUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/EncaminhamentosAEEMensalUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/PlanosAEEMensalUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/PlanosAulaDiarioUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/RegistrosFrequenciaDiarioUseCase.cs
[AB#109141](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109141)
> 109141 - Ajuste data UTC 0

- src/SME.SGP.Aplicacao/CasosDeUso/Abrangencia/ObterUEsPorDreUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Comunicados/ObterComunicadosPaginados/ObterComunicadosPaginadosEscolaAquiUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterInfoComponentesCurricularesESPorTurmasCodigo/ObterInfoComponentesCurricularesESPorTurmasCodigoQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Ocorrencia/ListarOcorrencias/ListarOcorrenciasQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQuery.cs
- src/SME.SGP.Aplicacao/Queries/UE/ObterUEsPorDRE/ObterUEsPorDREQuery.cs
- src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Comunicados/ObterCuminicadosPaginados/ObterComunicadosPaginadosQuery.cs
- src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
[AB#111779](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111779)
> 111779 - Constructor has x parameters, which is greater than the 7 authorized.

- src/SME.SGP.Aplicacao/Comandos/ComandosTipoCalendario.cs
[AB#111810](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111810)
> fix/111810 -> r2

- src/SME.SGP.Aplicacao/Comandos/ComandosTipoCalendario.cs
[AB#111810](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111810)
> Fix/111810 -> pre-prod

- src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasComMatriculaValidasParaValidarConselho/ObterTurmasComMatriculaValidasParaValidarConselhoQueryHandler.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_verificar_turmas_com_matriculas_validas_para_conselho_de_classe.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/ServicosFakes/ObterMatriculasAlunoNaTurmaQueryHandlerFakeSituacaoVinculoIndevido.cs
[AB#111018](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111018)
> Fix/111018 -> master

- src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDiariosDeBordoPorPeriodo/ObterDiariosDeBordoPorPeriodoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDiarioBordo.cs
- src/SME.SGP.Infra/Dtos/Devolutiva/DiarioBordoDevolutivaDto.cs
[AB#92184](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92184)
> 92184 - Alterar endpoint de consulta das devolutivas para retornar as duas disciplinas

- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosNAAPA/ObterEncaminhamentosNAAPAQueryHandler.cs
Ajuste na listagem de encaminhamento NAAPA considerando o ano letivo selecionado no filtro para obter as turmas correspondentes.
> Bug: 111968

- src/SME.SGP.Metrica.Worker/Entidade/DevolutivaDuplicado.cs
- src/SME.SGP.Metrica.Worker/Entidade/DevolutivaMaisDeUmaNoDiario.cs
- src/SME.SGP.Metrica.Worker/Entidade/DevolutivaSemDiario.cs
- src/SME.SGP.Metrica.Worker/Repositorios/Interfaces/IRepositorioDevolutivaDuplicado.cs
- src/SME.SGP.Metrica.Worker/Repositorios/Interfaces/IRepositorioDevolutivaMaisDeUmaNoDiario.cs
- src/SME.SGP.Metrica.Worker/Repositorios/Interfaces/IRepositorioDevolutivaSemDiario.cs
- src/SME.SGP.Metrica.Worker/Repositorios/Interfaces/IRepositorioSGPConsulta.cs
- src/SME.SGP.Metrica.Worker/Repositorios/RepositorioDevolutivaDuplicado.cs
- src/SME.SGP.Metrica.Worker/Repositorios/RepositorioDevolutivaMaisDeUmaNoDiario.cs
- src/SME.SGP.Metrica.Worker/Repositorios/RepositorioDevolutivaSemDiario.cs
- src/SME.SGP.Metrica.Worker/Repositorios/RepositorioSGPConsulta.cs
- src/SME.SGP.Metrica.Worker/Rotas/RotasRabbitMetrica.cs
- src/SME.SGP.Metrica.Worker/Startup.cs
- src/SME.SGP.Metrica.Worker/UseCases/DevolutivaDuplicadoUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/DevolutivaMaisDeUmaNoDiarioUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/DevolutivaSemDiarioUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/Interfaces/IDevolutivaDuplicadoUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/Interfaces/IDevolutivaMaisDeUmaNoDiarioUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/Interfaces/IDevolutivaSemDiarioUseCase.cs
- src/SME.SGP.Metrica.Worker/WorkerRabbitMetrica.cs
[AB#92632](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/92632)
> 92632 - Criar script de monitoramento BD

- src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasComMatriculaValidasParaValidarConselho/ObterTurmasComMatriculaValidasParaValidarConselhoQueryHandler.cs
> Ajuste de teste -> release

- src/SME.SGP.Metrica.Worker/Repositorios/RepositorioSGPConsulta.cs
- src/SME.SGP.Metrica.Worker/Startup.cs
[AB#110223](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110223)
> 110223 - Ajuste verificado durante monitoramento

- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/CompensacaoDeAusencia/Ao_obter_total_compensacoes.cs
[AB#111496](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111496)
> Fix/111496 -> pre-prod

- src/SME.SGP.Aplicacao/Consultas/ConsultasRegistroPoa.cs
[AB#111023](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111023)
> fix/111023 -> r2

- src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioParecerConclusivoDto.cs
[AB#111148](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111148)
> fix/111148 -> r2

- src/SME.SGP.Aplicacao/Comandos/ComandosPlanoAnualTerritorioSaber.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAnualTerritorioSaber.cs
- teste/SME.SGP.TesteIntegracao/PlanoAnualTerritorio/Ao_obter_plano_anual_do_territorio.cs
- teste/SME.SGP.TesteIntegracao/PlanoAnualTerritorio/ServicoFake/ObterComponenteCurricularPorIdQueryHandlerFakePlanoAnual.cs
- teste/SME.SGP.TesteIntegracao/PlanoAnualTerritorio/ServicoFake/ObterComponentesCurricularesDoProfessorNaTurmaQueryHandlerPlanoAnualTerritorio.cs
- teste/SME.SGP.TesteIntegracao/PlanoAnualTerritorio/ServicoFake/ObterProfessorTitularPorTurmaEComponenteCurricularQueryHandlerFakePlanoAnual.cs
[AB#111035](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111035)
> fix/111035 -> r2

- teste/SME.SGP.TesteIntegracao/Documento/Ao_listar_documentos.cs
[AB#109592](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109592)
> 109592 - Ajuste testes integrados

- src/SME.SGP.Dados/Repositorios/RepositorioDocumento.cs
- teste/SME.SGP.TesteIntegracao/Documento/Ao_listar_documentos.cs
- teste/SME.SGP.TesteIntegracao/Documento/Base/DocumentoTesteBase.cs
- teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#109592](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109592)
> 109592 - Adição testes integrados para todos/todos ue/dre

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#110954](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110954)
> fix/110954 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseUseCase.cs
[AB#112922](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/112922)
> fix/112922 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterNotasFrequenciaUseCase.cs
[AB#110954](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110954)
> fix/110954 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseUseCase.cs
[AB#112922](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/112922)
> fix/112922 -> pre-prod

- src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioParecerConclusivoDto.cs
[AB#111148](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111148)
> fix/111148 -> pre-prod

- src/SME.SGP.Dominio/Entidades/ComponenteCurricularEol.cs
Complemento do bug ajustando o carregamento de informações pedagógicas diminuindo o tempo de definição das informações.
> Bug: 111185

- src/SME.SGP.Aplicacao/Comandos/ComandosPlanoAnualTerritorioSaber.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAnualTerritorioSaber.cs
- teste/SME.SGP.TesteIntegracao/PlanoAnualTerritorio/Ao_obter_plano_anual_do_territorio.cs
- teste/SME.SGP.TesteIntegracao/PlanoAnualTerritorio/ServicoFake/ObterComponenteCurricularPorIdQueryHandlerFakePlanoAnual.cs
- teste/SME.SGP.TesteIntegracao/PlanoAnualTerritorio/ServicoFake/ObterComponentesCurricularesDoProfessorNaTurmaQueryHandlerPlanoAnualTerritorio.cs
- teste/SME.SGP.TesteIntegracao/PlanoAnualTerritorio/ServicoFake/ObterProfessorTitularPorTurmaEComponenteCurricularQueryHandlerFakePlanoAnual.cs
[AB#111035](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111035)
> fix/111035 -> pre-prod

- src/SME.SGP.Aplicacao/Consultas/ConsultasRegistroPoa.cs
[AB#111023](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111023)
> fix/111023 -> pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioObjetivoAprendizagemPlano.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAula.cs
- teste/SME.SGP.TesteIntegracao.Aula/PlanoAula/Ao_carregar_objetivos_plano_aula.cs
[AB#110830](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110830)
> fix/110830 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ObterGruposDeUsuariosUseCase.cs
[AB#113196](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/113196)
> 113196 - registro duplicado na listagem do campo Perfil

- scripts/V690__AJUSTE_OPCOES_RESPOSTA_NAAPA.sql
[AB#113178](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/113178)
> 113178 - Ajuste nos itens de opções de resposta naapa

- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Ao_obter_nota.cs
[AB#113154](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/113154)
> Fix/113154 -> Pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioObjetivoAprendizagemPlano.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAula.cs
- teste/SME.SGP.TesteIntegracao.Aula/PlanoAula/Ao_carregar_objetivos_plano_aula.cs
[AB#110830](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110830)
> fix/110830 -> master

- src/SME.SGP.Dominio/Entidades/Notificacao.cs
[AB#113868](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/113868)
> 113868 - Usuário não consegue excluir a notificação

- src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/ParecerConclusivo/ObterParecerConclusivoAlunoQueryHandlerTeste.cs
Ajuste ao obter parecer conclusivo incluíndo a verificação de itens na lista retornada ao obter códigos de turma por aluno, ano letivo e tipos de turma na integração no EOL. Teste unitário relativo.
> Bug: 113741

- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioObjetivoAprendizagemPlano.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAula.cs
- src/SME.SGP.Metrica.Worker/Repositorios/RepositorioSGPConsulta.cs
- teste/SME.SGP.TesteIntegracao.Aula/PlanoAula/Ao_carregar_objetivos_plano_aula.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Ao_obter_nota.cs
> master -> pre-prod

- src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
[AB#114072](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/114072)
> 114072 - Nota do fechamento final não exibe no Conselho de Classe

- src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
- src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
- src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagensNegocioLancamentoNota.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Ao_lancar_nota_numerica.cs
[AB#113265](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/113265)
> Fix/113265 -> pre-prod

- src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
- src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
- src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagensNegocioLancamentoNota.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Ao_lancar_nota_numerica.cs
[AB#113265](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/113265)
> Fix/113265 -> master

- teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasConselhoClasseTeste.cs
[AB#113702](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/113702)
> fix/113702 pt.2 -> pre-prod

- src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/ParecerConclusivo/ObterParecerConclusivoAlunoQueryHandlerTeste.cs
[AB#114308](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/114308)
> fix/114308 -> r2

- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_validar_situacao_do_parecer_conclusivo.cs
[AB#114308](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/114308)
> fix/114308 -> r2 ajuste de testes

- src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs
- teste/SME.SGP.TesteIntegracao/Abrangencia/Ao_carregar_abrangencia_professor_infantil.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/Ao_remover_uma_atribuicao_cj_nao_deve_remover_abrangencia_da_turma.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/Ao_logar_com_usuario_professor_infantil.cs
- teste/SME.SGP.TesteIntegracao/ItensBasicosBuilder.cs
[AB#114441](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/114441)
> fix/114441 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ConsultaConselhoClasseRecomendacaoUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterPorConselhoClasseAlunoPorTurmaAlunoBimestre/ObterPorConselhoClasseAlunoPorTurmaAlunoBimestre.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_validar_anotacoes_nota_fechamento.cs
[AB#112841](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/112841)
> Fix/112841 -> r2

- scripts/V691__CARGA_QUESTIONARIO_ATENDIMENTO_RELATORIO_DINAMICO_NAAPA.sql
[AB#110399](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110399)
> 110399 - Publicação de questionário e seção Itinerancia para relatório dinamico 

- src/SME.SGP.Api/Controllers/DashboardBuscaAtivaController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardBuscaAtiva/ObterQuantidadeBuscaAtivaPorMotivosAusenciaUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardBuscaAtiva/IObterQuantidadeBuscaAtivaPorMotivosAusenciaUseCase.cs
- src/SME.SGP.Dados/Repositorios/RepositorioDashBoardBuscaAtiva.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDashBoardBuscaAtiva.cs
- src/SME.SGP.Infra/Dtos/Grafico/BuscaAtiva/DadosGraficoMotivoAusenciaBuscaAtivaDto.cs
- src/SME.SGP.Infra/Dtos/Grafico/BuscaAtiva/FiltroGraficoBuscaAtivaDto.cs
- src/SME.SGP.Infra/Dtos/Grafico/BuscaAtiva/GraficoBuscaAtivaDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/DashboardBuscaAtiva/Ao_obter_grafico_busca_ativa_por_motivo_ausencia.cs
[AB#110410](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110410)
> 110410 - End point grafico motivos de ausencia Busca Ativa

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ConsultaConselhoClasseRecomendacaoUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterPorConselhoClasseAlunoPorTurmaAlunoBimestre/ObterPorConselhoClasseAlunoPorTurmaAlunoBimestre.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_validar_anotacoes_nota_fechamento.cs
[AB#112841](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/112841)
> Fix/112841 -> pre-prod

- src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
- teste/SME.SGP.TesteIntegracao.Aula/Nota/Base/NotaTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Aula/Nota/LancarNotaBimestreTeste.cs
- teste/SME.SGP.TesteIntegracao.Aula/PlanoAula/Base/PlanoAulaTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Base/NotaFechamentoTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/CompensacaoDeAusencia/Base/CompensacaoDeAusenciaTesteBase.cs
- teste/SME.SGP.TesteIntegracao/Abrangencia/Ao_carregar_abrangencia_professor_infantil.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/Ao_remover_uma_atribuicao_cj_nao_deve_remover_abrangencia_da_turma.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/Ao_logar_com_usuario_professor_infantil.cs
- teste/SME.SGP.TesteIntegracao/ItensBasicosBuilder.cs
[AB#114441](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/114441)
> Fix/114441 -> pre-prod

- src/SME.SGP.Aplicacao/Consultas/ConsultasCompensacaoAusencia.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/CompensacaoDeAusencia/Ao_carregar_compensacoes.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/CompensacaoDeAusencia/Base/CompensacaoDeAusenciaTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/CompensacaoDeAusencia/ServicosFake/ObterAlunosDentroPeriodoCompensacaoQueryHandlerFake.cs
[AB#114461](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/114461)
> Fix/114461 -> r2

- src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
- teste/SME.SGP.TesteIntegracao.Aula/Nota/Base/NotaTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Aula/Nota/LancarNotaBimestreTeste.cs
- teste/SME.SGP.TesteIntegracao.Aula/PlanoAula/Base/PlanoAulaTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Base/NotaFechamentoTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/CompensacaoDeAusencia/Base/CompensacaoDeAusenciaTesteBase.cs
- teste/SME.SGP.TesteIntegracao/Abrangencia/Ao_carregar_abrangencia_professor_infantil.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/Ao_remover_uma_atribuicao_cj_nao_deve_remover_abrangencia_da_turma.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/Ao_logar_com_usuario_professor_infantil.cs
- teste/SME.SGP.TesteIntegracao/ItensBasicosBuilder.cs
[AB#110782](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110782)
> fix/110782 -> master

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ConsultaConselhoClasseRecomendacaoUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterPorConselhoClasseAlunoPorTurmaAlunoBimestre/ObterPorConselhoClasseAlunoPorTurmaAlunoBimestre.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_validar_anotacoes_nota_fechamento.cs
[AB#112841](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/112841)
> Fix/112841 -> master

- src/SME.SGP.Aplicacao/Queries/RelatorioDinamicoNAAPA/ObterEncaminhamentoNAAPAParaRelatorioDinamico/ObterEncaminhamentoNAAPAParaRelatorioDinamicoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioQuestionario.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRelatorioDinamicoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioQuestionario.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRelatorioDinamicoNAAPA.cs
- src/SME.SGP.Dominio/Enumerados/TipoQuestao.cs
- src/SME.SGP.Infra/Dtos/RelatorioDinamicoNAAPA/RelatorioDinamicoNAAPADto.cs
- src/SME.SGP.Infra/Dtos/RelatorioDinamicoNAAPA/TotalAtendimentoQuestaoDto.cs
- src/SME.SGP.Infra/Dtos/RelatorioDinamicoNAAPA/TotalComponenteValorDto.cs
- src/SME.SGP.Infra/Dtos/RelatorioDinamicoNAAPA/TotalDeAtendimentoDto.cs
- src/SME.SGP.Infra/Dtos/RelatorioDinamicoNAAPA/TotalDeAtendimentoQuestaoPorRespostaDto.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_listar_secoes_itinerancia.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Base/EncaminhamentoNAAPATesteBase.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/RelatorioDinamico/Ao_obter_encaminhamento_atendimento_para_relatorio_dinamico_naapa.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/RelatorioDinamico/Ao_obter_questoes_relatorio_dinamico_naapa_por_modalidades.cs
[AB#110400](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110400)
> 110400 - Tratar busca/filtro de encaminhamentos por questões seção itinerancia

- src/SME.SGP.Infra/Constantes/ConstantesMenuPermissao.cs
- src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#98800](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98800)
> 98800 - Criar menu permissão

- src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConsolidadoEncaminhamentoNAAPA.cs
- teste/SME.SGP.TesteIntegracao.Aula/Nota/Base/NotaTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Aula/Nota/LancarNotaBimestreTeste.cs
- teste/SME.SGP.TesteIntegracao.Aula/PlanoAula/Base/PlanoAulaTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Base/NotaFechamentoTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/CompensacaoDeAusencia/Base/CompensacaoDeAusenciaTesteBase.cs
- teste/SME.SGP.TesteIntegracao/Abrangencia/Ao_carregar_abrangencia_professor_infantil.cs
- teste/SME.SGP.TesteIntegracao/AtribuicaoCJs/Ao_remover_uma_atribuicao_cj_nao_deve_remover_abrangencia_da_turma.cs
- teste/SME.SGP.TesteIntegracao/Autenticar/Ao_logar_com_usuario_professor_infantil.cs
- teste/SME.SGP.TesteIntegracao/DashboardNAAPA/Ao_obter_quantidade_encaminhamento_em_aberto.cs
- teste/SME.SGP.TesteIntegracao/ItensBasicosBuilder.cs
[AB#114748](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/114748)
> Fix/114748 -> r2

- src/SME.SGP.Infra.Consts/EncaminhamentoNAAPAConstants.cs
[AB#114951](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/114951)
> fix/114951 -> r2

- scripts/V693__CRIAR_REGISTRO_COLETIVO_NAAPA.sql
- src/SME.SGP.Api/Controllers/RegistroColetivoController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/RegistroColetivoNAAPA/ObterTiposDeReuniaoUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/RegistroColetivoNAAPA/IObterTiposDeReuniaoUseCase.cs
- src/SME.SGP.Aplicacao/Queries/RegistroColetivoNAAPA/ObterTiposReuniaoNAAPA/ObterTiposReuniaoNAAPAQuery.cs
- src/SME.SGP.Aplicacao/Queries/RegistroColetivoNAAPA/ObterTiposReuniaoNAAPA/ObterTiposReuniaoNAAPAQueryHandler.cs
- src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
- src/SME.SGP.Dados/Mapeamentos/TipoReuniaoNAAPAMap.cs
- src/SME.SGP.Dados/Repositorios/RepositorioTipoReuniaoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTipoReuniaoNAAPA.cs
- src/SME.SGP.Dominio/Entidades/TipoReuniaoNAAPA.cs
- src/SME.SGP.Infra/Dtos/RegistroColetivoNAAPA/TipoReuniaoDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/RegistroColetivoNAAPA/Ao_obter_tipo_reuniao_naapa.cs
- teste/SME.SGP.TesteIntegracao/RegistroColetivoNAAPA/Base/RegistroColetivoTesteBase.cs
- teste/SME.SGP.TesteIntegracao/RegistroColetivoNAAPA/Base/TipoReuniaoConstants.cs
[AB#98801](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98801)
> 98801 - Criar Tabela Tipo de reunião e endpoint get

- scripts/V693__CRIAR_REGISTRO_COLETIVO_NAAPA.sql
- src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
- src/SME.SGP.Dados/Mapeamentos/RegistroColetivoAnexoMap.cs
- src/SME.SGP.Dados/Mapeamentos/RegistroColetivoMap.cs
- src/SME.SGP.Dados/Mapeamentos/RegistroColetivoUeMap.cs
- src/SME.SGP.Dados/Mapeamentos/TipoReuniaoNAAPAMap.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRegistroColetivo.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRegistroColetivoAnexo.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRegistroColetivoUe.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroColetivo.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroColetivoAnexo.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroColetivoUe.cs
- src/SME.SGP.Dominio/Entidades/RegistroColetivo.cs
- src/SME.SGP.Dominio/Entidades/RegistroColetivoAnexo.cs
- src/SME.SGP.Dominio/Entidades/RegistroColetivoUe.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#98802](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98802)
> 98802 - Criação do mapeamento

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/ConsolidacaoNotaAlunoCommand/ConsolidacaoNotaAlunoCommandHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Handlers/ConsolidacaoNotaAlunoCommandHandlerTeste.cs
[AB#109778](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/109778)
> Fix/109778 -> pre-prod

- src/SME.SGP.Metrica.Worker/UseCases/ConselhoClasseNaoConsolidadoUEUseCase.cs
- src/SME.SGP.Metrica.Worker/UseCases/ConselhoClasseNaoConsolidadoUseCase.cs
[AB#112629](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/112629)
> 112629 - publicação fila reconsolidação conselho classe

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/EncerrarEncaminhamentoAEEAutomaticoSyncUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ValidarEncerrarEncaminhamentoAEEAutomaticoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs
- src/SME.SGP.ComprimirArquivos.Worker/Commands/SalvarLogViaRabbit/SalvarLogViaRabbitCommandHandler.cs
[AB#110992](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/110992)
> fix/110992 -> master

- src/SME.SGP.Dados/Repositorios/RepositorioConsolidadoEncaminhamentoNAAPA.cs
- teste/SME.SGP.TesteIntegracao/DashboardNAAPA/Ao_obter_quantidade_encaminhamento_em_aberto.cs
[AB#114748](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/114748)
> fix/114748 -> pre-prod

- src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/ParecerConclusivo/ObterParecerConclusivoAlunoQueryHandlerTeste.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_validar_situacao_do_parecer_conclusivo.cs
[AB#114308](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/114308)
> Fix/114308 -> pre-prod

- src/SME.SGP.Aplicacao/Consultas/ConsultasCompensacaoAusencia.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/CompensacaoDeAusencia/Ao_carregar_compensacoes.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/CompensacaoDeAusencia/Base/CompensacaoDeAusenciaTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/CompensacaoDeAusencia/ServicosFake/ObterAlunosDentroPeriodoCompensacaoQueryHandlerFake.cs
[AB#114461](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/114461)
> Fix/114461 -> pre-prod

- scripts/V694__ALTERACAO_CAMPO_REGISTRO_COLETIVO_NAAPA.sql
[AB#98813](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98813)
> Alteração tipo do campo descrição da tabela regitro_coletivo

- src/SME.SGP.Dados/Repositorios/RepositorioRegistroColetivo.cs
- src/SME.SGP.Infra/Dtos/RegistroColetivoNAAPA/RegistroColetivoListagemDto.cs
- src/SME.SGP.Infra/Dtos/RegistroColetivoNAAPA/UeRegistroColetivoDto.cs
[AB#98813](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98813)
> 98813 - Ajuste listagem paginada

- scripts/V695__ALTERACAO_CAMPO_OBS_REGISTRO_COLETIVO_NAAPA.sql
[AB#115406](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115406)
> 115406 - Campo observações quantidade incorreta de caracteres

- src/SME.SGP.Infra/Dtos/RegistroColetivoNAAPA/RegistroColetivoListagemDto.cs
[AB#115412](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115412)
> 115412 - Ajuste rf do criado por com espaçamento entre o nome

- src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseUseCase.cs
[AB#115435](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115435)
> fix/115435 -> r2

- src/SME.SGP.Aplicacao/Commands/Aulas/ValidarComponentesDoProfessor/ValidarComponentesDoProfessorCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Frequencia/InserirFrequenciasAula/InserirFrequenciasAulaCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/Turma/VerificaPodePersistirTurmaDisciplina/VerificaPodePersistirTurmaDisciplinaQuery.cs
- src/SME.SGP.Aplicacao/Queries/Turma/VerificaPodePersistirTurmaDisciplina/VerificaPodePersistirTurmaDisciplinaQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Turma/VerificaPodePersistirTurmaDisciplinaEOL/VerificaPodePersistirTurmaDisciplinaEOLQuery.cs
- src/SME.SGP.Aplicacao/Queries/Turma/VerificaPodePersistirTurmaDisciplinaEOL/VerificaPodePersistirTurmaDisciplinaEOLQueryHandler.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComponentesCurriculares.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs
- teste/SME.SGP.Aplicacao.Teste/Commands/ValidarComponentesDoProfessorCommandHandlerTeste.cs
[AB#111266](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111266)
> Fix/111266 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs
- src/SME.SGP.Aplicacao/Commands/PlanoAEE/Pendencias/ReaverPendenciaPlanoAEE/ReaverPendenciaPlanoAeeQuery.cs
- src/SME.SGP.Aplicacao/Commands/PlanoAEE/Pendencias/ReaverPendenciaPlanoAEE/ReaverPendenciaPlanoAeeQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterMatriculasAlunoPorCodigoEAno/ObterMatriculasAlunoPorCodigoEAnoQuery.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterMatriculasAlunoPorCodigoEAno/ObterMatriculasAlunoPorCodigoEAnoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendencia.cs
- src/SME.SGP.Infra.Consts/ServicosEolConstants.cs
- teste/SME.SGP.Aplicacao.Teste/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCaseTeste.cs
Ajuste na funcionalidade de encerramento de plano AEE acertando a URL do endpoint de integração com a API/EOL para obter as matrículas do aluno incluíndo o parâmetro de tipo turma.
Criação da funcionalidade para reaver planos encerrados que não se encaixam nos critérios de encerramento e que forma encerrados indevidamente.
> Bug: 115568

- src/SME.SGP.Aplicacao/Commands/Aulas/ValidarComponentesDoProfessor/ValidarComponentesDoProfessorCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Frequencia/InserirFrequenciasAula/InserirFrequenciasAulaCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/Turma/VerificaPodePersistirTurmaDisciplina/VerificaPodePersistirTurmaDisciplinaQuery.cs
- src/SME.SGP.Aplicacao/Queries/Turma/VerificaPodePersistirTurmaDisciplina/VerificaPodePersistirTurmaDisciplinaQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Turma/VerificaPodePersistirTurmaDisciplinaEOL/VerificaPodePersistirTurmaDisciplinaEOLQuery.cs
- src/SME.SGP.Aplicacao/Queries/Turma/VerificaPodePersistirTurmaDisciplinaEOL/VerificaPodePersistirTurmaDisciplinaEOLQueryHandler.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComponentesCurriculares.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs
- teste/SME.SGP.Aplicacao.Teste/Commands/ValidarComponentesDoProfessorCommandHandlerTeste.cs
[AB#111266](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111266)
> Fix/111266 -> pre-prod

- src/SME.SGP.Dominio/Enumerados/EnumImprimirAnexosNAAPA.cs
- src/SME.SGP.Infra/Dtos/Relatorios/EncaminhamentoNaapa/FiltroRelatorioEncaminhamentoNaapaDetalhadoDto.cs
[AB#112342](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/112342)
> 112342 - Tratar DTOs geração relatório

- src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/ServicosFakes/ObterAlunosDentroPeriodoQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoBimestre/Base/NotaFechamentoBimestreTesteBase.cs
[AB#115013](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115013)
> Fix/115013 -> Pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoItinerarioNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/AlterarEncaminhamentoNAAPASecaoQuestao/AlterarEncaminhamentoNAAPASecaoQuestaoCommandHandler.cs
[AB#115790](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115790)
> 115790 - Ajuste questoes duplicadas nos anexos itinerancia

- src/SME.SGP.Api/Controllers/ConselhoClasseController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterPareceresConclusivosTurmaUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConselhoClasse/IObterPareceresConclusivosTurmaUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterPareceresConclusivosTurma/ObterPareceresConclusivosTurmaQuery.cs
- src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterPareceresConclusivosTurma/ObterPareceresConclusivosTurmaQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseParecerConclusivoConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseParecerConclusivo.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_obter_pareceres_conclusivos_turma.cs
[AB#111255](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/111255)
> 112963 - Criar Endpoint para obter os parecer conclusivos

- src/SME.SGP.Aplicacao/Queries/ConsultaCriancasEstudantesAusentes/ObterTurmasAlunosAusentes/ObterTurmasAlunosAusentesQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/ConsultaCriancasEstudantesAusentes/ObterTurmasAlunosAusentes/ObterTurmasAlunosAusentesQueryHandlerTeste.cs
[AB#115796](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115796)
> Fix/115796 -> r2

- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Ao_obter_nota.cs
[AB#115192](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115192)
> fix/115192 -> r2

- src/SME.SGP.Aplicacao/Queries/ConsultaCriancasEstudantesAusentes/ObterTurmasAlunosAusentes/ObterTurmasAlunosAusentesQueryHandler.cs
[AB#115796](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115796)
> Ajuste de teste fix/115796 -> r2

- src/SME.SGP.Aplicacao/Queries/BuscaAtiva/ObterRegistrosAcao/ObterRegistrosAcaoQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosNAAPA/ObterEncaminhamentosNAAPAQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosNAAPA/ObterEncaminhamentosNAAPAQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRegistroAcaoBuscaAtiva.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoNAAPA.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/FiltroEncaminhamentoNAAPADto.cs
- src/SME.SGP.Infra/Dtos/RegistroAcaoBuscaAtiva/FiltroRegistrosAcaoDto.cs
- src/SME.SGP.Infra/Dtos/RegistroAcaoBuscaAtiva/FiltroRespostaRegistrosAcaoDto.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_listar_com_filtros.cs
- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/Ao_listar_registros_acao_busca_ativa_filtro.cs
[AB#115341](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115341)
> 115341 - mudança filtro nome aluno com codigo NAAPA e Busca Ativa

- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterEncaminhamentosNAAPA/ObterEncaminhamentosNAAPAQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/EncaminhamentoNAAPAResumoDto.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_listar_com_filtros.cs
- teste/SME.SGP.TesteIntegracao/TesteBase.cs
[AB#115042](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115042)
> 115042 - Disponibilização campos listagem paginada NAAPA

- src/SME.SGP.Aplicacao/Queries/ConsultaCriancasEstudantesAusentes/ObterTurmasAlunosAusentes/ObterTurmasAlunosAusentesQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/ConsultaCriancasEstudantesAusentes/ObterTurmasAlunosAusentes/ObterTurmasAlunosAusentesQueryHandlerTeste.cs
[AB#115796](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115796)
> Fix/115796 -> pre-prod

- src/SME.SGP.Api/Controllers/ConselhoClasseController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/AlterarParecerConclusivoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/AlterarParecerConclusivo/AlterarParecerConclusivoCommand.cs
- src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/AlterarParecerConclusivo/AlterarParecerConclusivoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/PersistirParecerConclusivoCommand/PersistirParecerConclusivoCommand.cs
- src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/PersistirParecerConclusivoCommand/PersistirParecerConclusivoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivoCommand.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConselhoClasse/IAlterarParecerConclusivoUseCase.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioConselhoClasse.cs
- src/SME.SGP.Infra/Dtos/AlterarParecerConclusivoDto.cs
- src/SME.SGP.Infra/Dtos/PersistirParecerConclusivoDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_alterar_parecer_conclusivo.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs
[AB#112656](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/112656)
> 112656 - Criar endpoint de alteração do parecer conclusivo

- src/SME.SGP.Aplicacao/CasosDeUso/Notificacao/LancarFrequenciaAulaUseCase.cs
- src/SME.SGP.Aplicacao/Commands/Frequencia/InserirFrequenciasAula/InserirFrequenciasAulaCommand.cs
- src/SME.SGP.Aplicacao/Commands/Frequencia/InserirFrequenciasAula/InserirFrequenciasAulaCommandHandler.cs
- src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagensNegocioFrequencia.cs
- teste/SME.SGP.Aplicacao.Teste/Commands/Frequencia/InserirFrequenciasAula/InserirFrequenciasAulaCommandHandlerTeste.cs
Ajuste na funcionalidade de lançar frequência do worker, alterando a funcionalidade de obter o usuário logado pelo contido na mensagem e caso não tenha definido considerar o usuário do sistema.
> Bug: 95165

- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoFinal/Ao_obter_nota.cs
[AB#115192](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115192)
> fix/115192 -> pre-prod

- scripts/V700__CRIAR_NOVOS_PERFIL_POA.sql
- src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/TratarAtribuicaoPendenciasUsuariosUseCase.cs
- src/SME.SGP.Dominio/Constantes/Perfis.cs
- src/SME.SGP.Dominio/Entidades/Usuario.cs
- src/SME.SGP.Dominio/Enumerados/PerfilUsuario.cs
[AB#95368](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95368)
> 95368 - Script insert prioridade_perfil SGP

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/DevolverEncaminhamentoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/AtualizarEncaminhamentoAEEEncerrarAutomatico/AtualizarEncaminhamentoAEEEncerrarAutomaticoCommand.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/AtualizarEncaminhamentoAEEEncerrarAutomatico/AtualizarEncaminhamentoAEEEncerrarAutomaticoCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaCPEncaminhamentoAEE/GerarPendenciaCPEncaminhamentoAEECommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaPAEEEncaminhamentoAEE/GerarPendenciaPAEEEncaminhamentoAEECommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/RegistrarEncaminhamentoAEE/RegistrarEncaminhamentoAeeCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/Notificacao/EnviarNotificacaoUsuarios/EnviarNotificacaoUsuariosCommandHandler.cs
- teste/SME.SGP.TesteIntegracao.Pendencia/PendenciaAula/Ao_gerar_pendencia_aula.cs
- teste/SME.SGP.TesteIntegracao.Pendencia/PendenciaCargaAulas/Ao_executar_carga_aulas_na_pendencia.cs
- teste/SME.SGP.TesteIntegracao.Pendencia/PendenciaDevolutiva/Ao_executar_exclusao_pendencias_devolutiva.cs
- teste/SME.SGP.TesteIntegracao.Pendencia/PendenciaDevolutiva/Ao_obter_pendencias.cs
- teste/SME.SGP.TesteIntegracao.Pendencia/PendenciaEncaminhamentoAEE/Ao_gerar_pendencia_encaminhamento_AEE.cs
- teste/SME.SGP.TesteIntegracao.Pendencia/PendenciaFechamento/Ao_disparar_geracao_pendencia_fechamento_para_pendencia_diario_classe_frequencia_existente.cs
- teste/SME.SGP.TesteIntegracao.Pendencia/PendenciaFechamento/Ao_gerar_pendencia_fechamento_aprovado.cs
- teste/SME.SGP.TesteIntegracao.Pendencia/PendenciaFechamento/Ao_gerar_pendencia_fechamento_frequencia.cs
- teste/SME.SGP.TesteIntegracao.Pendencia/PendenciaFechamento/Ao_gerar_pendencia_fechamento_plano_aula.cs
- teste/SME.SGP.TesteIntegracao.Pendencia/PendenciaFechamento/Base/PendenciaFechamentoBase.cs
- teste/SME.SGP.TesteIntegracao.Pendencia/PendenciaGeral/Ao_remover_pendencia_calendario_ano_anterior.cs
- teste/SME.SGP.TesteIntegracao.Pendencia/PendenciaGeral/Ao_remover_pendencia_diario_classe_final_do_ano_letivo.cs
- teste/SME.SGP.TesteIntegracao.Pendencia/PendenciaUsuario/Ao_gerar_pendencia_usuario.cs
[AB#103439](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/103439)
> Fix/103439 -> pre-prod

- src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
- src/SME.SGP.Dominio/Constantes/Perfis.cs
- src/SME.SGP.Dominio/Entidades/Usuario.cs
- src/SME.SGP.Dominio/Enumerados/PerfilUsuario.cs
- src/SME.SGP.Infra/Dtos/AbrangenciaSinteticaDto.cs
[AB#95372](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/95372)
> 95372 - Tratamento busca de abrangencias POA por turmas

- src/SME.SGP.Api/Controllers/ConselhoClasseController.cs
[AB#116635](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/116635)
> 116635 - Erro interno ao alterar o parecer com usuário que tem apenas permissão de consulta

- teste/SME.SGP.TesteIntegracao/Abrangencia/Ao_obter_abrangencia_perfil_poa.cs
- teste/SME.SGP.TesteIntegracao/Abrangencia/Base/AbrangenciaBase.cs
- teste/SME.SGP.TesteIntegracao/Abrangencia/ServicosFake/ObterAbrangenciaCompactaVigenteEolPorLoginEPerfilQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#116817](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/116817)
> 116817 - Teste de abrangência perfil poa

- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/Ao_encerrar_automaticamente.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/ServicosFakes/ObterMatriculasAlunoPorCodigoEAnoQueryHandlerFake.cs
[AB#116058](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/116058)
> Fix/116058 -> r2

- src/SME.SGP.Dados/Repositorios/RepositorioDevolutiva.cs
- teste/SME.SGP.Aplicacao.Teste/CasosDeUso/ObterDevolutivaPorIdUseCaseTeste.cs
- teste/SME.SGP.TesteIntegracao.Aula/DiarioBordo/Ao_inserir_devolutiva.cs
- teste/SME.SGP.TesteIntegracao.Aula/DiarioBordo/Ao_salvar_notificacao_devolutiva.cs
[AB#117020](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117020)
> fix/117020 -> r2

- src/SME.SGP.Api/Controllers/TurmaController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterTurmaSondagemUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Turma/IObterTurmaSondagemUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaSondagem/ObterTurmaSondagemQuery.cs
- src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaSondagem/ObterTurmaSondagemQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurmaConsulta.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/Turma/Ao_obter_turma_sondagem.cs
[AB#115081](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/115081)
> 115081 - Liberar o acesso aos relatórios da Sondagem perfil pap

- src/SME.SGP.Api/Controllers/RelatorioPAPController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/RelatoriosPAP/ObterRelatorioPAPConselhoClasseUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/RelatoriosPAP/IObterRelatorioPAPConselhoClasseUseCase.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterRelatorioPAPAlunoConselhoClasse/ObterRelatorioPAPAlunoConselhoClasseQuery.cs
- src/SME.SGP.Aplicacao/Queries/RelatoriosPAP/ObterRelatorioPAPAlunoConselhoClasse/ObterRelatorioPAPAlunoConselhoClasseQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRelatorioPeriodicoPAPAluno.cs
- src/SME.SGP.Dados/Repositorios/RepositorioSecaoRelatorioPeriodicoPAP.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRelatorioPeriodicoPAPAluno.cs
- src/SME.SGP.Infra/Dtos/RelatoriosPAP/RelatorioPAPAlunoConselhoClasseDto.cs
- src/SME.SGP.Infra/Dtos/RelatoriosPAP/SecaoPAPDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#96930](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/96930)
> 96930 - Relatório PAP no conselho de classe - End point de busca

- src/SME.SGP.Dados/Repositorios/RepositorioDevolutiva.cs
- teste/SME.SGP.Aplicacao.Teste/CasosDeUso/ObterDevolutivaPorIdUseCaseTeste.cs
- teste/SME.SGP.TesteIntegracao.Aula/DiarioBordo/Ao_inserir_devolutiva.cs
- teste/SME.SGP.TesteIntegracao.Aula/DiarioBordo/Ao_salvar_notificacao_devolutiva.cs
[AB#117020](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117020)
> Fix/117020 -> pre-prod

- src/SME.SGP.Aplicacao/Queries/Aula/PodeCadastrarAulaNoDia/PodeCadastrarAulaNoDiaQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/Aulas/PodeCadastrarAulaNoDia/PodeCadastrarAulaNoDiaQueryHandlerTeste.cs
[AB#116851](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/116851)
> fix/116851 -> pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioCadastroAcessoABAEConsulta.cs
- teste/SME.SGP.TesteIntegracao/ABAE/Ao_realizar_manutencao_abae.cs
[AB#117216](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117216)
> 117216 - Ajuste ordenação

- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/Ao_encerrar_automaticamente.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/ServicosFakes/ObterMatriculasAlunoPorCodigoEAnoQueryHandlerFake.cs
[AB#116058](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/116058)
> fix/116058 pt.2 -> r2

- src/SME.SGP.Api/Controllers/DashboardAEEController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardAEE/ObterEncaminhamentoAEESituacoesUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardAEE/IObterEncaminhamentoAEESituacoesUseCase.cs
- src/SME.SGP.Aplicacao/Queries/DashboardAEE/ObterEncaminhamentoAEESituacoes/ObterEncaminhamentoAEESituacoesQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardAEE/ObterEncaminhamentoAEESituacoes/ObterEncaminhamentoAEESituacoesQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoAEE.cs
- src/SME.SGP.Infra/Dtos/DashboardAEE/DashboardAEEEncaminhamentosDto.cs
- teste/SME.SGP.TesteIntegracao.AEE/DashBoardAEE/Ao_obter_dashboard_encaminhamento.cs
[AB#98793](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98793)
> 98793 - Melhoria end point Dashboard AEE (Encaminhamentos)

- src/SME.SGP.Api/Controllers/DashboardAEEController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardAEE/ObterPlanosAEEVigentesUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardAEE/IObterPlanosAEEVigentesUseCase.cs
- src/SME.SGP.Aplicacao/Queries/DashboardAEE/ObterPlanosAEEVigentes/ObterPlanosAEEVigentesQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardAEE/ObterPlanosAEEVigentes/ObterPlanosAEEVigentesQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEConsulta.cs
- src/SME.SGP.Infra/Dtos/DashboardAEE/DashboardAEEPlanosVigentesDto.cs
- teste/SME.SGP.TesteIntegracao.AEE/DashBoardAEE/Ao_obter_dashboard_planos.cs
[AB#98794](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98794)
> 98794 - Dashboard planos vigentes

- src/SME.SGP.Api/Controllers/DashboardRegistroItineranciaController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardItinerancia/ObterDashboardItineranciaVisitasPAAIsUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardItinerancia/IObterDashboardItineranciaVisitasPAAIsUseCase.cs
- src/SME.SGP.Aplicacao/Queries/DashboardItinerancia/ObterDashboardItineranciaVisitasPAAI/ObterDashboardItineranciaVisitasPAAIQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardItinerancia/ObterDashboardItineranciaVisitasPAAI/ObterDashboardItineranciaVisitasPAAIQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioItinerancia.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioItinerancia.cs
- src/SME.SGP.Infra/Dtos/DashboardItinerancia/DashboardItineranciaVisitaPaais.cs
- teste/SME.SGP.TesteIntegracao/Itinerancia/Ao_obter_dashboard_registro_itinerancia.cs
[AB#98795](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98795)
> 98795 - Melhoria end point Dashboard Registro de itinerância

- src/SME.SGP.Api/Controllers/DashboardNaapaController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardNaapa/ObterDashboardFrequenciaTurmaEvasaoAbaixo50PorcentoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardNaapa/ObterDashboardFrequenciaTurmaEvasaoSemPresencaUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardNaapa/IObterDashboardFrequenciaTurmaEvasaoAbaixo50PorcentoUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardNaapa/IObterDashboardFrequenciaTurmaEvasaoSemPresencaUseCase.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterDashboardFrequenciaTurmaEvasaoAbaixo50Porcento/ObterDashboardFrequenciaTurmaEvasaoAbaixo50PorcentoQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterDashboardFrequenciaTurmaEvasaoAbaixo50Porcento/ObterDashboardFrequenciaTurmaEvasaoAbaixo50PorcentoQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterDashboardFrequenciaTurmaEvasaoSemPresenca/ObterDashboardFrequenciaTurmaEvasaoSemPresencaQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterDashboardFrequenciaTurmaEvasaoSemPresenca/ObterDashboardFrequenciaTurmaEvasaoSemPresencaQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaConsulta.cs
- src/SME.SGP.Infra/Dtos/Grafico/Naapa/FrequenciaTurmaEvasaoDto.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/TurmaEvasaoFrequencia/Ao_obter_frequencia_turma_evasao.cs
[AB#98796](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98796)
> 98796 - Total Dashboard NAAPA (Risco de abandono)

- src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoFrequenciaTurmaEvasao/ConsolidarFrequenciaTurmaEvasaoAcumuladoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoFrequenciaTurmaEvasao/ConsolidarFrequenciaTurmaEvasaoUseCase.cs
- src/SME.SGP.Aplicacao/Commands/FrequenciaTurmaEvasao/LimparFrequenciaTurmaEvasaoAlunoPorTurmasEMeses/LimparFrequenciaTurmaEvasaoAlunoPorTurmasEMesesCommand.cs
- src/SME.SGP.Aplicacao/Commands/FrequenciaTurmaEvasao/LimparFrequenciaTurmaEvasaoAlunoPorTurmasEMeses/LimparFrequenciaTurmaEvasaoAlunoPorTurmasEMesesCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/FrequenciaTurmaEvasao/RegistrarFrequenciaTurmaEvasaoAluno/RegistrarFrequenciaTurmaEvasaoAlunoCommand.cs
- src/SME.SGP.Aplicacao/Commands/FrequenciaTurmaEvasao/RegistrarFrequenciaTurmaEvasaoAluno/RegistrarFrequenciaTurmaEvasaoAlunoCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralPorAlunosTurma/ObterFrequenciaGeralPorAlunosTurmaQueryHandler.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/ServicosFake/ObterAlunosEolPorTurmaEvasaoFrequenciaQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/TurmaEvasaoFrequencia/Ao_registrar_frequencia_turma_evasao.cs
[AB#106651](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106651)
> 106651 - Persistencia de alunos de frequencia turma evasão

- src/SME.SGP.Api/Controllers/DashboardNaapaController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardNaapa/ObterQuantidadeEncaminhamentoEmAbertoPorDreUseCase.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterQuantidadeEncaminhamentoNAAPAEmAberto/ObterQuantidadeEncaminhamentoNAAPAEmAbertoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConsolidadoEncaminhamentoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidadoEncaminhamentoNAAPA.cs
- src/SME.SGP.Infra/Dtos/Grafico/Naapa/GraficoEncaminhamentoNAAPADto.cs
- teste/SME.SGP.TesteIntegracao/DashboardNAAPA/Ao_obter_quantidade_encaminhamento_em_aberto.cs
[AB#97211](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/97211)
> 98797 - Total Dashboard NAAPA (Encaminhamento)

- src/SME.SGP.Api/Controllers/DashboardNaapaController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardNaapa/ObterAlunosDashboardFrequenciaTurmaEvasaoAbaixo50PorcentoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardNaapa/ObterAlunosDashboardFrequenciaTurmaEvasaoSemPresencaUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardNaapa/IObterAlunosDashboardFrequenciaTurmaEvasaoAbaixo50PorcentoUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardNaapa/IObterAlunosDashboardFrequenciaTurmaEvasaoSemPresencaUseCase.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterAlunosDashboardFrequenciaTurmaEvasaoAbaixo50Porcento/ObterAlunosDashboardFrequenciaTurmaEvasaoAbaixo50PorcentoQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterAlunosDashboardFrequenciaTurmaEvasaoAbaixo50Porcento/ObterAlunosDashboardFrequenciaTurmaEvasaoAbaixo50PorcentoQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterAlunosDashboardFrequenciaTurmaEvasaoSemPresenca/ObterAlunosDashboardFrequenciaTurmaEvasaoSemPresencaQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterAlunosDashboardFrequenciaTurmaEvasaoSemPresenca/ObterAlunosDashboardFrequenciaTurmaEvasaoSemPresencaQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaConsulta.cs
- src/SME.SGP.Infra/Dtos/Grafico/Naapa/AlunoFrequenciaTurmaEvasaoDto.cs
- src/SME.SGP.Infra/Dtos/Grafico/Naapa/FiltroGraficoFrequenciaTurmaEvasaoAlunoDto.cs
- src/SME.SGP.Infra/Dtos/Grafico/Naapa/GraficoFrequenciaTurmaEvasaoDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#106652](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/106652)
> 106652 - End point consulta de alunos evasao escolar

- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/Ao_encerrar_automaticamente.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/ServicosFakes/ObterMatriculasAlunoPorCodigoEAnoQueryHandlerFake.cs
[AB#116058](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/116058)
> Fix/116058 -> pre-prod

- scripts/V702__ADICIONAR_CAMPO_MODALIDADE_TABELA_CONSOLIDADO_NAAPA.sql
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardNaapa/ObterDashboardFrequenciaTurmaEvasaoAbaixo50PorcentoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ExecutarBuscarConsolidadoAtendimentosProfissionalEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ExecutarBuscarUesConsolidadoEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/ExecutarInserirConsolidadoAtendimentoProfissionalEncaminhamentoNAAPAUseCase.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoNAAPA/SalvarConsolidadoEncaminhamentoNAAPA/SalvarConsolidadoEncaminhamentoNAAPACommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterAtendimentoProfissionalEncaminhamentosNAAPAConsolidado/ObterAtendimentoProfissionalEncaminhamentosNAAPAConsolidadoQuery.cs
- src/SME.SGP.Aplicacao/Queries/EncaminhamentoNAAPA/ObterAtendimentoProfissionalEncaminhamentosNAAPAConsolidado/ObterAtendimentoProfissionalEncaminhamentosNAAPAConsolidadoQueryHandler.cs
- src/SME.SGP.Dados/Mapeamentos/ConsolidadoAtendimentoNAAPAMap.cs
- src/SME.SGP.Dados/Mapeamentos/ConsolidadoEncaminhamentoNAAPAMap.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConsolidadoAtendimentoNAAPA.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConsolidadoEncaminhamentoNAAPA.cs
- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoNAAPA.cs
- src/SME.SGP.Dados/Repositorios/RepositorioSecaoEncaminhamentoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidadoAtendimentoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidadoEncaminhamentoNAAPA.cs
- src/SME.SGP.Dominio/Entidades/ConsolidadoAtendimentoNAAPA.cs
- src/SME.SGP.Dominio/Entidades/ConsolidadoEncaminhamentoNAAPA.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/AtendimentosPorProfissionalEncaminhamentoNAAPADto.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/AtendimentosProfissionalEncaminhamentoNAAPAConsolidadoDto.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/EncaminhamentosNAAPAConsolidadoDto.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_salvar_consolidado_atendimento_encaminhamento_naapa.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_salvar_consolidado_encaminhamento_naapa.cs
[AB#98852](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98852)
> 98852 - Ajuste geração consolidação dash NAAPA

- src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdQuery/ObterPendenciasAulaPorAulaIdQuery.cs
- src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdQuery/ObterPendenciasAulaPorAulaIdQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdsQuery/ObterPendenciasAulaPorAulaIdsQuery.cs
- src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdsQuery/ObterPendenciasAulaPorAulaIdsQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMes/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDia/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDiaQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs
- teste/SME.SGP.TesteIntegracao.Aula/Aula/ServicosFake/ObterPendenciasAulaPorAulaIdsQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/ServicosFakes/ObterPendenciasAulaPorAulaIdsQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/Turma/Ao_obter_aulas_eventos_professor_calendario_por_mes.cs
[AB#117268](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117268)
> Fix/117268 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/DashboardNaapa/ObterQuantidadeAtendimentoNAAPAPorProfissionalMesUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardNaapa/ObterQuantidadeEncaminhamentoEmAbertoPorDreUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/DashboardNaapa/ObterQuantidadeEncaminhamentoPorSituacaoUseCase.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterQuantidadeAtendimentoNAAPAPorProfissionalMes/ObterQuantidadeAtendimentoNAAPAPorProfissionalMesQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterQuantidadeAtendimentoNAAPAPorProfissionalMes/ObterQuantidadeAtendimentoNAAPAPorProfissionalMesQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterQuantidadeEncaminhamentoNAAPAEmAberto/ObterQuantidadeEncaminhamentoNAAPAEmAbertoQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterQuantidadeEncaminhamentoNAAPAEmAberto/ObterQuantidadeEncaminhamentoNAAPAEmAbertoQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConsolidadoAtendimentoNAAPA.cs
- src/SME.SGP.Dados/Repositorios/RepositorioConsolidadoEncaminhamentoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidadoAtendimentoNAAPA.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidadoEncaminhamentoNAAPA.cs
- src/SME.SGP.Infra/Dtos/Grafico/Naapa/FiltroGraficoEncaminhamentoPorSituacaoDto.cs
- src/SME.SGP.Infra/Dtos/Grafico/Naapa/FiltroQuantidadeAtendimentoNAAPAPorProfissionalMesDto.cs
- src/SME.SGP.Infra/Dtos/Grafico/Naapa/FiltroQuantidadeEncaminhamentoNAAPAEmAbertoDto.cs
- teste/SME.SGP.TesteIntegracao/DashboardNAAPA/Ao_obter_quantidade_atendimento_profissional.cs
- teste/SME.SGP.TesteIntegracao/DashboardNAAPA/Ao_obter_quantidade_encaminhamento_em_aberto.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_obter_dados_grafico_por_situacao.cs
[AB#98870](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/98870)
> 98870 - Ajuste end points de busca dash NAAPA com filtro de modalidade

- src/SME.SGP.Dominio/Entidades/Aula.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/Frequencia/Ao_apresentar_os_alunos_na_tela.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/Frequencia/Base/FrequenciaTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/Frequencia/ServicosFakes/ObterComponentesCurricularesPorIdsUsuarioLogadoQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#117366](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117366)
> fix/117366 -> r2

- src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaTurmaConsulta.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/DashboardFrequencia/Ao_obter_dados_dash_frequencia_global_por_ano.cs
[AB#117314](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117314)
> fix/117314 -> pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioConsolidadoEncaminhamentoNAAPA.cs
- teste/SME.SGP.TesteIntegracao/DashboardNAAPA/Ao_obter_quantidade_encaminhamento_em_aberto.cs
[AB#117571](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117571)
> 117571 - Quantidade do grafico não considerando rascunho

- src/SME.SGP.Aplicacao/Consultas/ConsultaAtividadeAvaliativa.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs
- teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasAulasTeste.cs
[AB#117478](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117478)
> fix/117478 -> r2

- src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
- src/SME.SGP.Dominio/Entidades/Aula.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/Frequencia/Ao_apresentar_os_alunos_na_tela.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/Frequencia/Base/FrequenciaTesteBase.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/Frequencia/ServicosFakes/ObterComponentesCurricularesPorIdsUsuarioLogadoQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#117366](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117366)
> Fix/117366 -> pre-prod

- src/SME.SGP.Aplicacao/Comandos/ComandosAtividadeAvaliativa.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultaAtividadeAvaliativa.cs
- src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs
- teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasAulasTeste.cs
- teste/SME.SGP.TesteIntegracao.Aula/Avaliacao/Ao_registrar_avaliacao_pela_gestao_e_cj.cs
- teste/SME.SGP.TesteIntegracao.Aula/Avaliacao/TesteAvaliacao.cs
[AB#117478](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117478)
> fix/117478 -> pre-prod

- scripts/V704__INSERIR_PARAMETRO_EXCLUSAO_NOTIFICACAO.sql
- src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
[AB#107655](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107655)
> 107655 - Criar parâmetros para exclusão de notificações de aviso e alerta

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterAlunosSemNotasRecomendacoesUseCase.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_obter_recomendacoes_notas.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/ServicosFakes/ObterTurmaCodigosAlunoPorAnoLetivoUeTipoTurmaQueryFake.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/ServicosFakes/ObterTurmasFechamentoConselhoPorAlunosQueryHandlerFake.cs
[AB#117546](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117546)
> Fix/117546 -> r2

- src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
[AB#118012](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118012)
> fix/118012 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/Notificacoes/ExecutarExclusaoNotificacaoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Notificacoes/ExecutarExclusaoNotificacoesPeriodicamenteUseCase.cs
- src/SME.SGP.Aplicacao/Commands/Notificacao/ExcluirNotificacaoTotalPorId/ExcluirNotificacaoTotalPorIdCommand.cs
- src/SME.SGP.Aplicacao/Commands/Notificacao/ExcluirNotificacaoTotalPorId/ExcluirNotificacaoTotalPorIdCommandHandler.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Notificacao/Jobs/IExecutarExclusaoNotificacaoUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Notificacao/Jobs/IExecutarExclusaoNotificacoesPeriodicamenteUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Notificacoes/ObterIdsDasNotificacoesParaExclusaoPorDias/ObterIdsDasNotificacoesParaExclusaoPorDiasQuery.cs
- src/SME.SGP.Aplicacao/Queries/Notificacoes/ObterIdsDasNotificacoesParaExclusaoPorDias/ObterIdsDasNotificacoesParaExclusaoPorDiasQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioNotificacao.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotificacao.cs
- src/SME.SGP.Infra.Mensageria/Rotas/RotasRabbitSgp.cs
- src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarUseCaseRabbitSgp.cs
- src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
- teste/SME.SGP.TesteIntegracao/Notificacoes/Ao_excluir_notificacao_periodicamente.cs
- teste/SME.SGP.TesteIntegracao/Notificacoes/ServicosFake/PublicarFilaSgpExcluirNotificacaoCommandHandlerFake.cs
[AB#107657](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107657)
> 107657 - Criar fila de exclusão de notificações

- scripts/V706__CRIAR_INDEX_TABELA_WF_APROVACAO .sql
[AB#107838](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107838)
> 107838 - Criação de index

- src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQuery.cs
- src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterResponsaveisPlanoAEE/ObterResponsaveisPlanoAEEQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEConsulta.cs
- src/SME.SGP.Infra/Dtos/PlanoAEE/FiltroPlanosAEEDto.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/Ao_acessar_tela_de_listagem.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/ServicosFakes/ObterUEsPorDREQueryHandlerFake.cs
[AB#118287](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118287)
> fix/118287 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterAlunosSemNotasRecomendacoesUseCase.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_obter_recomendacoes_notas.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/ServicosFakes/ObterTurmaCodigosAlunoPorAnoLetivoUeTipoTurmaQueryFake.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/ServicosFakes/ObterTurmasFechamentoConselhoPorAlunosQueryHandlerFake.cs
[AB#117546](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117546)
> Fix/117546 -> pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
[AB#118012](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118012)
> fix/118012 -> pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoConsulta.cs
[AB#118324](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118324)
> fix/118324 -> r2

- src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQuery.cs
- src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterResponsaveisPlanoAEE/ObterResponsaveisPlanoAEEQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEConsulta.cs
- src/SME.SGP.Infra/Dtos/PlanoAEE/FiltroPlanosAEEDto.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/Ao_acessar_tela_de_listagem.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/ServicosFakes/ObterUEsPorDREQueryHandlerFake.cs
[AB#118287](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118287)
> fix/118287 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/DashboardNaapa/ObterQuantidadeEncaminhamentoPorSituacaoUseCase.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterDataUltimaConsolicacaoDashboardNaapa/ObterDataUltimaConsolicacaoDashboardNaapaQuery.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterDataUltimaConsolicacaoDashboardNaapa/ObterDataUltimaConsolicacaoDashboardNaapaQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterQuantidadeAtendimentoNAAPAPorProfissionalMes/ObterQuantidadeAtendimentoNAAPAPorProfissionalMesQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterQuantidadeEncaminhamentoNAAPAEmAberto/ObterQuantidadeEncaminhamentoNAAPAEmAbertoQueryHandler.cs
- teste/SME.SGP.TesteIntegracao/DashboardNAAPA/Ao_obter_quantidade_encaminhamento_em_aberto.cs
- teste/SME.SGP.TesteIntegracao/DashboardNAAPA/ServicosFake/ObterDataUltimaConsolidacaoDashboardNAAPAQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/DashboardNAAPA/ServicosFake/ObterParametroSistemaPorTipoEAnoQueryHandlerFakeDashNAAPA.cs
[AB#118338](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118338)
> fix/118338 -> pre-prod

- scripts/V707__ALTERACAO_FORMULARIO_BUSCA_ATIVA.sql
- src/SME.SGP.Aplicacao/Queries/Questionario/ObterQuestoesPorQuestionarioPorId/ObterQuestoesPorQuestionarioPorIdQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioDashBoardBuscaAtiva.cs
- src/SME.SGP.Dados/Repositorios/RepositorioRegistroAcaoBuscaAtiva.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/RegistroAcaoBuscaAtivaNAAPADto.cs
- src/SME.SGP.Infra/Dtos/RegistroAcaoBuscaAtiva/RegistroAcaoBuscaAtivaListagemDto.cs
- teste/SME.SGP.TesteIntegracao/Commands/PublicarQuestionarioBuscaAtiva/PublicarQuestionarioBuscaAtivaComando.cs
- teste/SME.SGP.TesteIntegracao/Constantes/ConstantesQuestionarioBuscaAtiva.cs
- teste/SME.SGP.TesteIntegracao/DashboardBuscaAtiva/Ao_obter_grafico_busca_ativa_por_procedimento_trabalho.cs
- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/Ao_cadastrar_editar_registro_acao_busca_ativa.cs
- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/Ao_listar_registros_acao_busca_ativa.cs
- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/Ao_obter_registros_acao_aluno_para_naapa.cs
- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/Base/RegistroAcaoBuscaAtivaTesteBase.cs
[AB#118399](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118399)
> 118399 - Criar  alterações questões busca ativa

- src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/TurmaEvasaoFrequencia/Ao_obter_alunos_frequencia_turma_evasao.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/TurmaEvasaoFrequencia/Ao_obter_frequencia_turma_evasao.cs
[AB#118400](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118400)
> 118400 - Alterar query quantidade de crianças/estudantes que não frequentaram a UE nenhuma vez

- src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoNAAPA/RegistrarEncaminhamentoNAAPAUseCase.cs
- teste/SME.SGP.TesteIntegracao/EncaminhamentoNAAPA/Ao_cadastrar_editar_encaminhamento_naapa_aguardandoatendimento.cs
[AB#118337](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118337)
> fix/118337 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
- src/SME.SGP.Infra/Dtos/Aluno/AlunoRegistroFrequenciaDto.cs
- src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaAulaDetalheDto.cs
- src/SME.SGP.Infra/Dtos/RegistroFrequenciaAlunoDto.cs
[AB#107603](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/107603)
> 107603 - Remover retorno param PermiteAnotacao

- src/SME.SGP.Api/Controllers/PeriodoEscolarController.cs
[AB#116341](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/116341)
> fix/116341 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/Salvar/SalvarPlanoAEEUseCase.cs
- src/SME.SGP.Aplicacao/Commands/PlanoAEE/PlanoAEEResposta/AtualizarPlanoAEERespostaPeriodoEscolarCommand.cs
- src/SME.SGP.Aplicacao/Commands/PlanoAEE/PlanoAEEResposta/AtualizarPlanoAEERespostaPeriodoEscolarCommandHandler.cs
- src/SME.SGP.Aplicacao/Commands/PlanoAEE/PlanoAEEResposta/AtualizarPlanoAEERespostaPeriodoEscolarValidator.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEResposta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEResposta.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/Ao_editar_plano_aee.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/ServicosFakes/ObterVersaoPlanoAEEPorIdQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/ServicosFakes/ObterVersoesPlanoAEEQueryHandlerFake.cs
[AB#118339](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118339)
> fix/118339 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/ObterFuncionarios/ObterFuncionariosUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ABAE/ObterCadastroAcessoABAEPorDre/ObterCadastroAcessoABAEPorDreQuery.cs
- src/SME.SGP.Aplicacao/Queries/ABAE/ObterCadastroAcessoABAEPorDre/ObterCadastroAcessoABAEPorDreQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioCadastroAcessoABAEConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCadastroAcessoABAEConsulta.cs
- src/SME.SGP.Infra/Dtos/ABAE/NomeCpfABAEDto.cs
- teste/SME.SGP.TesteIntegracao/ABAE/Ao_obter_funcionarios_com_acesso_ABAE.cs
- teste/SME.SGP.TesteIntegracao/ABAE/Base/ABAETesteBase.cs
[AB#117229](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117229)
> 117229 - Tratar busca de funcionários no EOL considerando usuários ABAEs

- src/SME.SGP.Aplicacao/Commands/Usuarios/ReiniciarSenha/ReiniciarSenhaCommandHandler.cs
- src/SME.SGP.Infra/Dtos/Extensoes/StringExtension.cs
[AB#117230](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117230)
> 117230 - Validar reinicio de senha

- src/SME.SGP.Dados/Repositorios/RepositorioCadastroAcessoABAEConsulta.cs
- src/SME.SGP.Infra/Dtos/Extensoes/StringExtension.cs
[AB#117219](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117219)
> 117219 - Ajuste filtro rf e nome abae

- src/SME.SGP.Api/Controllers/PeriodoEscolarController.cs
[AB#116341](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/116341)
> fix/116341 -> pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioRegistroAcaoBuscaAtiva.cs
- src/SME.SGP.Infra/Dtos/EncaminhamentoNAAPA/RegistroAcaoBuscaAtivaNAAPADto.cs
- src/SME.SGP.Infra/Dtos/RegistroAcaoBuscaAtiva/RegistroAcaoBuscaAtivaListagemDto.cs
- teste/SME.SGP.TesteIntegracao/RegistroAcaoBuscaAtiva/Ao_obter_registros_acao_aluno_para_naapa.cs
[AB#119358](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119358)
> 119358 - Ajuste de campos removidos por equivoco na task 118333

- src/SME.SGP.Aplicacao/Commands/Aulas/ValidarComponentesDoProfessor/ValidarComponentesDoProfessorCommandHandler.cs
[AB#119576](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119576)
> Adicionado validação de nulo

- src/SME.SGP.Aplicacao/Consultas/ConsultasAtribuicoes.cs
[AB#119188](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119188)
> fix/119188 -> pre prod

- src/SME.SGP.Metrica.Worker/Startup.cs
[AB#118358](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118358)
> 118358 - Ajuste injeção de dependencia

- src/SME.SGP.Aplicacao/Commands/Aulas/ValidarComponentesDoProfessor/ValidarComponentesDoProfessorCommandHandler.cs
[AB#119576](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119576)
> fix/119576 -> pre-prod

- src/SME.SGP.Dados/Repositorios/RepositorioAtribuicaoCJ.cs
[AB#118358](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/118358)
> 118358 - Ajuste concatenação de query gerava erro na consulta

- src/SME.SGP.Api/Controllers/ConselhoClasseController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterPareceresConclusivosTurmaUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConselhoClasse/IObterPareceresConclusivosTurmaUseCase.cs
- src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterPareceresConclusivosTurma/ObterPareceresConclusivosTurmaQuery.cs
- src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterPareceresConclusivosTurma/ObterPareceresConclusivosTurmaQueryHandler.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Ao_obter_pareceres_conclusivos_turma.cs
- teste/SME.SGP.TesteIntegracao.Fechamento/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs
[AB#119776](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119776)
> 119776 - buscar pareceres conclusivos vigentes ano letivo anterior

- scripts/V710__CARGA_QUESTIONARIO_MAPEAMENTO_ESTUDANTE.sql
- src/SME.SGP.Dominio/Enumerados/TipoQuestao.cs
[AB#119633](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119633)
> 119633 - Publicação de questões, seção e questionário mapeamento

- src/SME.SGP.Api/Controllers/MapeamentoEstudanteController.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/MapeamentoEstudante/IObterSecoesMapeamentoSecaoUseCase.cs
[AB#119732](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119732)
> 119732 - Obtenção seções mapeamento

- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs
[AB#119212](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119212)
> fix/119212 -> r2

- src/SME.SGP.Aplicacao/CasosDeUso/MapeamentoEstudantes/ObterIdentificadorMapeamentoEstudanteUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/MapeamentoEstudante/IObterIdentificadorMapeamentoEstudanteUseCase.cs
- src/SME.SGP.Aplicacao/Queries/MapeamentoEstudantes/ObterIdentificadorMapeamentoEstudante/ObterIdentificadorMapeamentoEstudanteQuery.cs
- src/SME.SGP.Aplicacao/Queries/MapeamentoEstudantes/ObterIdentificadorMapeamentoEstudante/ObterIdentificadorMapeamentoEstudanteQueryHandler.cs
- src/SME.SGP.Dados/Mapeamentos/MapeamentoEstudantes/MapeamentoEstudanteMap.cs
- src/SME.SGP.Dados/Repositorios/MapeamentoEstudantes/RepositorioMapeamentoEstudante.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/MapeamentoEstudante/IRepositorioMapeamentoEstudante.cs
- src/SME.SGP.Dominio/Entidades/MapeamentoEstudantes/MapeamentoEstudante.cs
- teste/SME.SGP.TesteIntegracao/MapeamentoEstudantes/Ao_obter_mapeamento_estudante.cs
- teste/SME.SGP.TesteIntegracao/MapeamentoEstudantes/Base/MapeametoBase.cs
- teste/SME.SGP.TesteIntegracao/MapeamentoEstudantes/Base/NomeComponenteQuestao.cs
- teste/SME.SGP.TesteIntegracao/Setup/CollectionFixture.cs
- teste/SME.SGP.TesteIntegracao/Setup/ConstrutorDeTabelas.cs
- teste/SME.SGP.TesteIntegracao/Setup/InMemoryDatabase.cs
- teste/SME.SGP.TesteIntegracao/Setup/ScriptCarga.cs
- teste/SME.SGP.TesteIntegracao/TesteBase.cs
[AB#119730](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119730)
> 119730 - Criação teste

- src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs
[AB#119212](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119212)
> fix/119212 -> pre-prod

- src/SME.SGP.Infra/Dtos/Relatorios/EncaminhamentoNAAPA/FiltroRelatorioEncaminhamentoNAAPADto.cs
Ajuste no filtro de encaminhamento NAAPA considerando corretamente os filtros enviados pelo front com os ajustes realizados para sereme considerados na impressão.
> Bug: 120361

- src/SME.SGP.Aplicacao/Consultas/ConsultasTurma.cs
- src/SME.SGP.Dominio.Servicos/ServicoAluno.cs
- teste/SME.SGP.Dominio.Servicos.Teste/ServicoAlunoTeste.cs
Ajuste na funcionalidade de obter marcador do aluno, considerando a situação "Transferido SED".
> Bug: 120630

- src/SME.SGP.Aplicacao/Queries/MapeamentoEstudantes/ObterCodigosAlunosSinalizadosPrioridadeMapeamentoEstudante/ObterCodigosAlunosSinalizadosPrioridadeMapeamentoEstudanteQueryHandler.cs
[AB#119627](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119627)
> 119627 - Validação de critérios: ajuste retorno alunos sinalizados

- src/SME.SGP.Aplicacao/CasosDeUso/MapeamentoEstudantes/AtualizarMapeamentoDosEstudantesUseCase.cs
[AB#119627](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119627)
> 119627 - Ajuste mensagem nula job diario

- src/SME.SGP.Aplicacao/Queries/MapeamentoEstudantes/ObterInformacoesTurmasProgramaAlunoMapeamentoEstudante/ObterInformacoesTurmasProgramaAlunoMapeamentoEstudanteQueryHandler.cs
- teste/SME.SGP.TesteIntegracao/MapeamentoEstudantes/Ao_obter_informacoes_atualizadas_mapeamento_estudante.cs
- teste/SME.SGP.TesteIntegracao/MapeamentoEstudantes/ServicosFakes/ObterInformacoesTurmasProgramaAlunoMapeamentoEstudanteQueryFake.cs
[AB#119627](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/119627)
> fix/121039: Ajuste código componente CEFAI

- teste/SME.SGP.TesteIntegracao.Fechamento/NotaFechamentoBimestre/Ao_validar_exibicao_alunos.cs
Ajuste de teste de integração.
> Bug: 121076

- src/SME.SGP.Aplicacao/Queries/MapeamentoEstudantes/ObterRespostasAtualizadasQuestionarioMapeamentoEstudante/ObterRespostasAtualizadasQuestionarioMapeamentoEstudanteQueryHandler.cs
[AB#121156](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/121156)
> 121156 - Tratamento conversão freq string to double

- src/SME.SGP.Dados/Repositorios/RepositorioFechamentoAlunoConsulta.cs
Ajuste na consulta para obter fechamento aluno e fechamento nota considerando o último registro inserido ao salvar para ficar de acordo com o carregamento.
> Bug: 121007

- src/SME.SGP.Infra/Constantes/ConstantesMenuPermissao.cs
- src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#120218](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120218)
> 120218 - Permissionamento Relatório mapeamento estudantes

- src/SME.SGP.Api/Controllers/RelatorioMapeamentoEstudantesController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/MapeamentoEstudantes/ObterFiltrosOpcoesRespostaRelatorioMapeamentoUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/MapeamentoEstudante/IObterFiltrosOpcoesRespostaRelatorioMapeamentoUseCase.cs
- src/SME.SGP.Infra/Dtos/MapeamentoEstudantes/OpcoesRespostaFiltroRelatorioMapeamentoEstudanteDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/MapeamentoEstudantes/Ao_obter_filtros_opcoes_resposta_relatorio_mapeamento_estudante.cs
[AB#121234](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/121234)
> 121234 - End point obtenção de filtros

- src/SME.SGP.Api/Controllers/RelatorioMapeamentoEstudantesController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/MapeamentoEstudantes/ObterFiltrosOpcoesRespostaRelatorioMapeamentoUseCase.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/MapeamentoEstudantes/RelatorioMapeamentoEstudantesUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/MapeamentoEstudante/IObterFiltrosOpcoesRespostaRelatorioMapeamentoUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IRelatorioMapeamentoEstudantesUseCase.cs
- src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
- src/SME.SGP.Infra.Mensageria/Rotas/RotasRabbitSgpRelatorios.cs
- src/SME.SGP.Infra/Dtos/Relatorios/MapeamentoEstudantes/FiltroRelatorioMapeamentoEstudantesDto.cs
- src/SME.SGP.Infra/Dtos/Relatorios/MapeamentoEstudantes/OpcoesRespostaFiltroRelatorioMapeamentoEstudanteDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#120217](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120217)
> 120217 - End point SGP solicitação do relatório

- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs
Complemento do bug considerando o ano atual para identificar a alteração de UE para encerramento do plano AEE.
> Bug: 120993

- src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/Nota/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandlerTeste.cs
Ajuste na funcionalidade de gravação das recomendações, simplificando a verificação de turmas consideradas.
> Bug: 121464

- src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/MapeamentoEstudantes/RelatorioMapeamentoEstudantesUseCase.cs
[AB#121482](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/121482)
> 121482 - Ajuste tipo relatório emitido - excel

- src/SME.SGP.Api/Controllers/RelatorioController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/BuscaAtiva/RelatorioBuscasAtivasUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IRelatorioBuscasAtivasUseCase.cs
- src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
- src/SME.SGP.Infra.Mensageria/Rotas/RotasRabbitSgpRelatorios.cs
- src/SME.SGP.Infra/Dtos/Relatorios/BuscaAtiva/FiltroRelatorioBuscasAtivasDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#117208](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/117208)
> 117208 - End point solicitação relatório

- src/SME.SGP.Api/Controllers/ABAEController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/ABAE/ObterFuncionariosABAEUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ABAE/IObterFuncionariosABAEUseCase.cs
- src/SME.SGP.Infra/Dtos/FiltroFuncionariosDto.cs
- src/SME.SGP.Infra/Dtos/Relatorios/BuscaAtiva/FiltroRelatorioBuscasAtivasDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
- teste/SME.SGP.TesteIntegracao/ABAE/Ao_obter_funcionarios_ABAE.cs
[AB#121235](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/121235)
> 121235 - End point busca de funcionarios abae

- scripts/V715__CRIAR_INFORMATIVO_ANEXO.sql
- src/SME.SGP.Dados/Mapeamentos/InformativoAnexoMap.cs
- src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
- src/SME.SGP.Dados/Repositorios/RepositorioInformativoAnexo.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioInformativoAnexo.cs
- src/SME.SGP.Dominio/Entidades/InformativoAnexo.cs
- src/SME.SGP.Infra/Dtos/Informes/InformativoAnexoDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#120319](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120319)
> 120319 - Modelagem InformativoAnexo

- src/SME.SGP.Api/Controllers/InformesController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ExcluirArquivoInformeUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Informes/IExcluirArquivoInformeUseCase.cs
- src/SME.SGP.Dominio/Enumerados/TipoArquivo.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#120302](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120302)
> 120302 - Upload e exclusao arquivo/anexo informe

- src/SME.SGP.Aplicacao/CasosDeUso/Informes/SalvarInformesUseCase.cs
- src/SME.SGP.Aplicacao/Commands/Informes/SalvarInformesAnexos/SalvarInformesAnexosCommand.cs
- src/SME.SGP.Aplicacao/Commands/Informes/SalvarInformesAnexos/SalvarInformesAnexosCommandHandler.cs
- src/SME.SGP.Infra/Dtos/Informes/InformesDto.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_salvar_informes.cs
[AB#120303](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120303)
> 120303 - Salvar anexo informativo ao salvar informe

- src/SME.SGP.Aplicacao/Commands/Informes/ExcluirAnexosInformativoPorIdInformativo/ExcluirAnexosInformativoPorIdInformativoCommad.cs
- src/SME.SGP.Aplicacao/Commands/Informes/ExcluirAnexosInformativoPorIdInformativo/ExcluirAnexosInformativoPorIdInformativoCommadHandler.cs
- src/SME.SGP.Aplicacao/Commands/Informes/ExcluirInformes/ExcluirInformesCommandHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioInformativoAnexo.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioInformativoAnexo.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_excluir_informes.cs
- teste/SME.SGP.TesteIntegracao/Informe/ServicosFake/PublicarFilaSgpCommandFakeInforme.cs
[AB#120304](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120304)
> 120304 - Exclusao de anexos na exclusao do informativo

- src/SME.SGP.Api/Controllers/InformesController.cs
- src/SME.SGP.Aplicacao/CasosDeUso/Informes/DownloadTodosAnexosInformativoUseCase.cs
- src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Informes/IDownloadTodosAnexosInformativoUseCase.cs
- src/SME.SGP.Dados/Repositorios/RepositorioInformativoAnexo.cs
- src/SME.SGP.Infra/Dtos/Informes/InformativoAnexoDto.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#120318](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120318)
> 120318 - End point compactar todos anexos Informativo

- src/SME.SGP.Aplicacao/Queries/Aluno/ObterDadosAlunos/ObterDadosAlunosQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/Aluno/ObterDadosAlunos/ObterDadosAlunosQueryHandlerTeste.cs
Ajuste na funcionalidade de obter alunos, alternando para o endpoint da API/EOL de obter todos alunos de forma a obter as matrículas de forma correta.
> Bug: 121912

- src/SME.SGP.Aplicacao/Queries/Aluno/ObterTodosAlunosNaTurma/ObterTodosAlunosNaTurmaQueryHandler.cs
Remoção da gravação no cache redis da lista de alunos para monitorar o funcionamento e verificar seo problema de lista incompleta permanece.
> Bug: 122286

- src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs
> 115933 - Ajuste validação criterios nome componente consolidacao

- src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarNAAPAUseCaseRabbitSgp.cs
- src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarUseCaseRabbitSgp.cs
[AB#120276](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/120276)
> 118340 - Ajuste IoC use case

- scripts/V719__CRIAR_TABELA_INFORMATIVO_MODALIDADE.sql
- src/SME.SGP.Dados/Mapeamentos/InformativoModalidadeMap.cs
- src/SME.SGP.Dados/Repositorios/RepositorioInformativoModalidade.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioInformativoModalidade.cs
- src/SME.SGP.Dominio/Entidades/InformativoModalidade.cs
- src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#122027](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122027)
> 122027 - Criar script para adicionar o campo modalidade

- src/SME.SGP.Aplicacao/CasosDeUso/Informes/SalvarInformesUseCase.cs
- src/SME.SGP.Aplicacao/Commands/Informes/SalvarInformesModalidade/SalvarInformesModalidadeCommand.cs
- src/SME.SGP.Aplicacao/Commands/Informes/SalvarInformesModalidade/SalvarInformesModalidadeCommandHandler.cs
- src/SME.SGP.Dados/Mapeamentos/InformativoModalidadeMap.cs
- src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
- src/SME.SGP.Infra/Dtos/Informes/InformesDto.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_salvar_informes.cs
[AB#122031](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122031)
> 122031 - Tratar persistência do informe para persistir a modalidade

- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ObterInformeUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Informes/ObterInformesPorFiltro/ObterInformesPorFiltroQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioInformativo.cs
- src/SME.SGP.Dominio/Entidades/Informativo.cs
- src/SME.SGP.Infra/Dtos/Informes/InformeResumoDto.cs
- src/SME.SGP.Infra/Dtos/Informes/InformesRespostaDto.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_obter_infomes_filtro.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_obter_informe.cs
[AB#122035](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122035)
> 122035 - Tratar consulta do informe para retornar as modalidades

- src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosTratarUseCase.cs
- teste/SME.SGP.TesteIntegracao.AEE/PlanoAEE/Ao_encerrar_automaticamente.cs
[AB#122308](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122308)
> fix/122308 -> pre-prod

- src/SME.SGP.Aplicacao/CasosDeUso/Informes/ExecutarNotificacaoInformativoUsuariosUseCase.cs
- teste/SME.SGP.TesteIntegracao/Informe/Ao_salvar_informes.cs
- teste/SME.SGP.TesteIntegracao/Informe/ServicosFake/ObterGruposDeUsuariosQueryHandlerFake.cs
- teste/SME.SGP.TesteIntegracao/Informe/ServicosFake/ObterRfsUsuariosPorPerfisDreUeQueryHandlerFake.cs
[AB#122052](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122052)
> 122052 - Ajuste para considerar apenas perfis do informativo

- scripts/V721__PREENCHIMENTO_QUESTOES_APRESENTADAS_NAAPA_OBRIGATORIAS_REGISTROS_ANTIGOS.sql
[AB#122696](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122696)
> Ajuste script flyway - pós deploy liberação pre prod

- src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
- src/SME.SGP.Aplicacao/Queries/Abrangencia/UsuarioPossuiSomenteAbrangenciaHistoricaNaTurma/UsuarioPossuiSomenteAbrangenciaHistoricaNaTurmaQuery.cs
- src/SME.SGP.Aplicacao/Queries/Abrangencia/UsuarioPossuiSomenteAbrangenciaHistoricaNaTurma/UsuarioPossuiSomenteAbrangenciaHistoricaNaTurmaQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfilQuery.cs
- src/SME.SGP.Aplicacao/Queries/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfilQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAbrangencia.cs
- teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasDisciplinasTeste.cs
Ajuste na consulta de disciplinas que verifica se o usuário possui somente abrangência histórica. Essa indicação é incluída no endpoint de busca de componentes da API/EOL para que os componentes sejam retornados corretamente.
> Bug: 121313

- src/SME.SGP.Aplicacao/Queries/Professores/ObterProfessorPorRFUeDreAnoLetivo/ObterProfessorPorRFUeDreAnoLetivoQueryHandler.cs
- teste/SME.SGP.Aplicacao.Teste/Queries/Professores/ObterProfessorPorRFUeDreAnoLetivo/ObterProfessorPorRFUeDreAnoLetivoQueryHandlerTeste.cs
Ajuste na funcionalidade de obter professor por RF, DRE, UE e ano letivo removendo algumas validações não necessárias que impossibilitavam a continuidade da listagem e inclusão de atribuição CJ.
> Bug: 119662

- scripts/V724__AJUSTE_ORDEM_QUESTOES_RELATORIO_DINAMICO_NAAPA.sql
- src/SME.SGP.Dados/Repositorios/RepositorioRelatorioDinamicoNAAPA.cs
Reverts prefeiturasp/SME-NovoSGP#14678
> Revert "Revert "123003 - Ajuste totalizador atendimento e total por respostas de aten…""

- src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
Reverts prefeiturasp/SME-NovoSGP#14704
> Revert "120653 - Ajuste teste integrado, busca de alunos pela data a aula e n…"

- src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosDentroPeriodo/ObterAlunosDentroPeriodoQueryHandler.cs
- src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
Reverts prefeiturasp/SME-NovoSGP#14703
> Revert "120653 - Aluno concluido no inicio do ano letivo posterior ao ano let…"

- src/SME.SGP.Aplicacao/CasosDeUso/ObterFuncionarios/ObterFuncionariosUseCase.cs
- src/SME.SGP.Dominio.Servicos/ServicoUsuario.cs
[AB#122992](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122992)
> 122992 - Ajuste reinicio de senha e login usuario abae sem perfis

- src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/AtividadeAvaliativaPorTurma/AtualizaCacheDeAtividadeAvaliativaPorTurmaCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/Notas/ObterNotasPorAlunosAtividadesAvaliativas/ObterNotasPorAlunosAtividadesAvaliativasQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioNotasConceitosConsulta.cs
[AB#123130](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/123130)
> 123130 - Ajuste cache notas avaliações

- src/SME.SGP.Aplicacao/Comandos/ComandosUsuario.cs
[AB#122940](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/122940)
> 122940 - Ajuste limpar cache de perfis ao deslogar (sair)

- src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/NotasEConceitosFinais/RelatorioNotasEConceitosFinaisUseCase.cs
[AB#121975](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/121975) - Ajuste para relatório emitir por Dre quando filtro TODAS
> 121975 - Ajuste para relatório emitir por Dre quando filtro TODAS

- src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Frequencia/GerarRelatorioFrequenciaMensalUseCase.cs
- src/SME.SGP.Infra/Dtos/Extensoes/StringExtension.cs
[AB#123262](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/123262)
> Ajustes performance relatório para segregar por Dre em caso de todas

- src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Frequencia/GerarRelatorioFrequenciaMensalUseCase.cs
[AB#123262](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/123262)
> 123262 - Revert de segregação por dre

- src/SME.SGP.Aplicacao/Commands/Frequencia/VerificaFrequenciaRegistradaParaAlunosInativos/VerificaFrequenciaRegistradaParaAlunosInativosCommandHandler.cs
- src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosPorTurma/ObterAlunosPorTurmaQueryHandler.cs
[AB#123279](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/123279)
> 123279 - Ajuste verificação de freq de alunos inativos

- src/SME.SGP.Aplicacao/Queries/MapeamentoEstudantes/ObterCodigosAlunosSinalizadosPrioridadeMapeamentoEstudante/ObterCodigosAlunosSinalizadosPrioridadeMapeamentoEstudanteQueryHandler.cs
[AB#123301](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/123301)
> 123301 - Ajuste sinalizador hipotese de escrita

- src/SME.SGP.Aplicacao/Queries/Aluno/ObterMatriculasAlunoPorCodigoEAno/ObterMatriculasAlunoPorCodigoEAnoQueryHandler.cs
[AB#123402](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/123402)
> fix(123402): Corrige retorno query ObterMatriculasAlunoPorCodigoEAnoQuery

- src/SME.SGP.Aplicacao/Queries/Aluno/ObterMatriculasAlunoPorCodigoEAno/ObterMatriculasAlunoPorCodigoEAnoQueryHandler.cs
- Corrige retorno querie ObterMatriculasAlunoPorCodigoEAnoQuery para evitar erro no fluxo de encerramento de planos aee em cenário de instabilidade EOL.
> Bug: 123402

- src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs
- Aplica tratamento de palavra 'temp' em salvar plano de aula para os campos descrição e lição de casa.
> Bug: 123420

- src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs
- Corrige método para cenário de descrição nulo
História: [AB#123420](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/123420)
> fix(123420): Corrige método para cenário de descrição nulo

- src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs
- Corrige método para cenário de descrição nulo
> Bug: 123420 v2

- src/SME.SGP.IoC/Extensions/RegistrarHttpClients.cs
Remove RetryPolicy ServicosEol
> Remove RetryPolicy ServicosEol

- teste/SME.SGP.Aplicacao.Teste/Comandos/ComandosFechamentoTurmaDisciplinaTeste.cs
- teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasPlanoAulaTeste.cs
- teste/SME.SGP.Dominio.Servicos.Teste/SME.SGP.Dominio.Servicos.Teste.csproj
- teste/SME.SGP.Dominio.Servicos.Teste/ServicoNotificacaoFrequenciaTeste.cs
Inclui testes unitários para ComandosFechamentoTurmaDisciplina, ConsultasAula e ServicoNotificacaoFrequencia, cobrindo cenários de sucesso e falha. Atualiza ConsultasPlanoAulaTeste para ConsultasAulaTeste com novos métodos de teste. Adiciona dependência Bogus para geração de dados de teste.
> Adiciona testes para comandos, consultas e notificações

- src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs
- src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAulasPorPendenciaIds/ObterPendenciasAulasPorPendenciaIdsQuery.cs
- src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAulasPorPendenciaIds/ObterPendenciasAulasPorPendenciaIdsQueryHandler.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
- src/SME.SGP.Dados/Repositorios/RepositorioPendenciaConsulta.cs
- src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs
- src/SME.SGP.Infra/Dtos/PendenciaAula/PendenciaAulasDto.cs
Reverts prefeiturasp/SME-NovoSGP#14964
> Ajuste na busca por pendencias

- src/SME.SGP.Aplicacao/Queries/EOL/Funcionario/ObterFuncionariosPorFuncaoAtividadeUe/ObterFuncionariosPorCargoUeQuery.cs
- src/SME.SGP.Aplicacao/Queries/EOL/Funcionario/ObterFuncionariosPorFuncaoAtividadeUe/ObterFuncionariosPorCargoUeQueryHandler.cs
- src/SME.SGP.Dominio.Interfaces/Servicos/IServicoNotificacao.cs
- src/SME.SGP.Dominio.Servicos/ServicoNotificacao.cs
- src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
- src/SME.SGP.Dominio/Enumerados/FuncaoAtividade.cs
- src/SME.SGP.Infra.Consts/ServicosEolConstants.cs
Incluir notificação de registro de itinerância de cargo para função atividade na modalidade CIEJA
> Incluir notificação de registro de itinerância de cargo para função atividade na modalidade CIEJA

- scripts/V733__INSERIR_PRIORIDADE_PERFIL_COORD_PEDAGOGICO_CIEJA.sql
- scripts/V734__INSERIR_PRIORIDADE_PERFIL_ASSISTENTE_COORD_GERAL_CIEJA.sql
- scripts/V735__INSERIR_PRIORIDADE_PERFIL_COORD_GERAL_CIEJA.sql
- src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/TratarAtribuicaoPendenciasUsuariosUseCase.cs
- src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/EnviarParaAnaliseEncaminhamentoAEE/EnviarParaAnaliseEncaminhamentoAEECommandHandler.cs
Scripts de prioridade perfil CIEJA e ajuste no tratar pendência por TipoEscola
> Scripts de prioridade perfil CIEJA e ajuste no tratar pendência por TipoEscola

- src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
- src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaFrequenciaAulas/ObterListaFrequenciaAulasQueryHandler.cs
- teste/SME.SGP.TesteIntegracao.Frequencia/Listao/Ao_validar_apresentacao_dos_alunos.cs
Correção de teste unitario para o SonnarQuality
> Correção de teste unitario para o SonnarQuality

- src/SME.SGP.Aplicacao/Queries/Funcionario/ObterFuncionariosPorFuncaoAtividadeHierarquico/ObterFuncionariosPorFuncaoAtividadeHierarquicoQueryHandler.cs
Correcao obter funcionarios por funcao atividade hierarquico query handler
> Correcao ObterFuncionariosPorFuncaoAtividadeHierarquicoQuery

- src/SME.SGP.Api/Controllers/BuscaAtivaController.cs
Ajuste na permissão de consulta aos registros de ações
> Ajuste na permissão de consulta aos registros de ações
