prefeiturasp/SME-NovoSGP

src/SME.SGP.Api/Startup.cs, src/SME.SGP.Api/appsettings.Development.json, src/SME.SGP.Api/appsettings.json, src/SME.SGP.Api/appsettings.teste-integrado.json
[AB#6147](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/6147)
[AB#6146](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/6146)
=> Incluido no swagger a forma de incluir JWT;

teste/SME.SGP.Integracao.Teste/TipoCalendarioTeste.cs
Adicionando espera no teste para evitar de listar os feriados moveis antes do metodo async cadastrar
[AB#7730](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/7730)
=> Adicioanndo espera no testes para evitar falha

src/SME.SGP.WebClient/src/paginas/Principal/listaNotificacoes.js
**Problema**
Ao acessar o sistema com notificações pendentes e trocar seu status, quando retorna ao dashboard a mesma continua no status inicial.
Problema ocorre com o dashboard e pop-up de notificações
**Causa**
Utilizado Redux para cachear as notificações e tanto o dashboard quanto o pop-up carregam as Notificações do cache.
**Solução**
Na renderização da lista de notificações do dashboard foi chamado o metodo para consulta das notificações no backend e atualização do cache. Corrigindo assim também os status no pop-up.
[AB#6446](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/6446)
=> fix/7685 : Status das notificações Incorreto

src/SME.SGP.Api/Controllers/TipoCalendarioController.cs
Inclusão de permissão no endpoint de Tipo de calendario  para usuários que podem acessar a tela de eventos.
Esse pullRequest contempla as seguintes alterações
[AB#7813](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/7813)
=> Inclusão de permissão no endpoint de Tipo de calendario 

src/SME.SGP.Dados/Repositorios/RepositorioAula.cs, src/SME.SGP.Dominio.Servicos/ServicoAula.cs, src/SME.SGP.Dominio/Enumerados/TipoEscola.cs, teste/SME.SGP.Aplicacao.Teste/Comandos/ComandosEventoTipoTeste.cs, teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasEventoTipoTeste.cs, teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasGradeTeste.cs, teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasPeriodoEscolarTeste.cs
Ao incluir uma aula a grade deve ser consultada para que não seja cadastrado mais aulas do que o permitido pela grade;
[AB#6983](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/6983)
=> 7919 - Consistencia da grade no cadastro de aula

src/SME.SGP.Api/Controllers/PlanoAulaController.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAula.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasPlanoAula.cs, src/SME.SGP.Infra/Dtos/PlanoAulaRetornoDto.cs, teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasPlanoAulaTeste.cs
Alterado retorno dos objetivos no plano aula;
Anteriormente era retornado apenas os IDs dos objetivos anuais selecionados para a aula, para que o front filtrasse na lista de objetivos anuais e mostrasse os objetivos da aula;
Verificado que a interação no front não ficaria boa pois os objetivos anuais são carregados apenas das disciplinas selecionadas na tag, então foi incluso o Dto completo dos objetivos selecionados na aula para retorno ao front facilitando a montagem dos objetivos selecionados;
[AB#4507](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/4507)
=> 8159 - Retorno dos Objetivos no plano aula

src/SME.SGP.Aplicacao/Comandos/ComandosPlanoAula.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasObjetivoAprendizagem.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAnual.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAula.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasObjetivoAprendizagem.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasPlanoAnual.cs, src/SME.SGP.Dados/Repositorios/RepositorioObjetivoAprendizagemAula.cs, src/SME.SGP.Dados/Repositorios/RepositorioObjetivoAprendizagemPlano.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioObjetivoAprendizagemPlano.cs, src/SME.SGP.Infra/Dtos/PlanoAulaDto.cs, teste/SME.SGP.Aplicacao.Teste/Comandos/ComandosPlanoAulaTeste.cs
Ao filtrar objetivos do plano aula não estava funcionando pois o Id do objetivo se trata do Id do Jurema e não do Id do objetivo no plano anual;
Realizado alterações para que o filtro ocorra pelo Id do Jurema no objetivo do plano anual;
Alterado também o post do plano aula para que seja enviado a lista de Ids de objetivo do Jurema;
[AB#4507](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/4507)
=> 8159 - Filtro dos objetivos pelo Id do Jurema

src/SME.SGP.Dominio.Servicos/ServicoAula.cs, src/SME.SGP.Dominio/Entidades/Aula.cs, src/SME.SGP.Dominio/Entidades/Evento.cs
No clone estava carregando o Id e fazia com que o Salvar atualizasse a mesma entidade;
Alterado também a logica para buscar o inicio e fim do periodo de recorrencia pois estava gerando a partir do proximo periodo cadatrado ao inves de gerar a partir da data da aula.
Ex: Aula cadastrada dia 15/02 com recorrencia em todos os bimestres.
Estava gerando aulas recorrentes a partir do dia 01/04 (que seria o proximo periodo cadastrado);
[AB#8851](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/8851)
=> 8851 - Corrigido geração da recorrencia de aulas

src/SME.SGP.Api/Controllers/AtribuicaoEsporadicaController.cs, src/SME.SGP.Aplicacao/Comandos/ComandosAtribuicaoEsporadica.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAtribuicaoEsporadica.cs, src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosAtribuicaoEsporadica.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasAtribuicaoEsporadica.cs
Inclusão das informações de auditoria no obter por ID.
Utilizando DTO simplificado no POST, removendo campos desnecessarios.
[AB#8899](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/8899)
=> Inclusão da auditoria no obter por ID

src/SME.SGP.Dados/Repositorios/RepositorioAula.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAula.cs, src/SME.SGP.Dominio.Servicos/ServicoAula.cs
A alteração de aula estava chamando o metodo incorreto para contagem de aulas na semana ultrapassando o limite de aulas cadastrados na grade, considerando aulas de todas as disciplinas da turma;
Incluso parametro de disciplina no metodo chamado e alterado a chamada na validação da alteração da aula;
[AB#9303](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/9303)
=> 9309 - Alteração de Aula consistindo grade

src/Bibliotecas/SME.Background.Hangfire/Startup.cs, src/Bibliotecas/SME.Background.Hangfire/Worker.cs, src/Bibliotecas/SME.SGP.Background/ContextFilterAttribute.cs, src/SME.SGP.Api/Startup.cs, src/SME.SGP.Dominio.Servicos.Teste/ServicoAulaTeste.cs, src/SME.SGP.Infra/Contexto/WorkerContext.cs, src/SME.SGP.Infra/Escopo/WorkerServiceScope.cs, src/SME.SGP.WorkerService/WorkerService.cs
Revisão de diversos controles do WorkerService para mitigar problema de queda dos serviços
Foram incluídos as variáveis de ambiente:
- BackgroundWorkerParallelDegree (determina quantos jobs serão executados ao mesmo tempo)
- BackgroundWorkerQueuePollInterval (de quanto em quanto tempo o Hangfire busca novos jobs)
Outras alterações:
- Aumento para 10s o tempo do Dashboard buscar novidades
- Inclusão do Application Name do Worker Server e do Worker Server - Dashboard para acompanhamento das conexões no PostgreSQL
- Melhorias na identificação da Thread por parte da contexto do serviço
[AB#9531](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/9531)
[AB#9369](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/9369)
=> Revisão de diversos controles do WorkerService

src/SME.SGP.Api/Middlewares/TokenServiceMiddleware.cs, src/SME.SGP.Aplicacao/Servicos/ServicoTokenJwt.cs
No caso de não conseguir buscar o token do cache, a comparação do token atual com o ativo estava retornando falso, fazendo com que o request retornasse 401 fazendo o redirect do front para o login;
[AB#6686](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/6686)
=> 9400 - Tratamento de erro ao consultar cache, assumir que token é valido

src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs
Quando por algum motivo desconhecido o filtro de CodigoRF do registro que vem do EOL não bate com o supervisor_id, ocorria erro de referencia.
Como esse filtro é feito apenas para buscar o nome do supervisor, foi tratado para deixar o nome vazio e não dar erro de referencia.
[AB#9637](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/9637)
=> 9883 - Tratamento no filtro para evitar erro de referencia

src/SME.SGP.Api/Middlewares/TokenServiceMiddleware.cs, src/SME.SGP.Dados/Repositorios/RepositorioCache.cs
Quando ocorrer erro ao tentar acessar o Redis, será logado no Sentry, assim saberemos que estamos com problema no cache
[AB#6686](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/6686)
=> 9400 - Incluso log no sentry quando não Redis offline

src/SME.SGP.Api/Controllers/AutenticacaoController.cs, src/SME.SGP.Aplicacao/Comandos/ComandosUsuario.cs, src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosUsuario.cs, src/SME.SGP.Aplicacao/Interfaces/Servicos/IServicoTokenJwt.cs, src/SME.SGP.Aplicacao/Servicos/ServicoTokenJwt.cs, src/SME.SGP.Infra/Dtos/RevalidacaoTokenDto.cs, src/SME.SGP.Infra/Dtos/TrocaPerfilDto.cs, src/SME.SGP.Infra/Dtos/UsuarioAutenticacaoRetornoDto.cs
- Tratar a validação de token ativo para que se o toquem atual for mais novo que o do cache, atualiza o cache e valida;
- Expor a data e hora de expiração do token para o client;
=> 9400 - Validação de token mais atual do que o Cache

src/SME.SGP.Aplicacao/Consultas/ConsultasGrade.cs
Problema: Não esta considerando as aulas de regencia de classe no dia quando consulta a grade;
Motivo: Estava passando o objeto turma como string para o repositorio filtrar, consequentemente não encontrava aulas com o filtro passado;
Solução: Correção da passagem de parametros para a consulta de aulas no dia
[AB#9602](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/9602)
=> 10181 - Consulta Grade: Corrigido pesquisa de aulas no dia

src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEvento.cs, src/SME.SGP.Dominio.Servicos/ServicoEvento.cs
Corrigido buscar de eventos concomitantes para desconsiderar o evento atual quando estiver salvando uma edição;
[AB#9990](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/9990)
=> 10266 - Corrigido buscar de eventos concomitantes

src/SME.SGP.Api/Controllers/TipoCalendarioController.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/TipoCalendarioEscolar/tipoCalendarioEscolarForm.js
O botão alterar estava chamando o post ao invés do put como esperado para alteração. Por este motivo estava duplicando os registros;
[AB#8330](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/8330)
=> 10274 - Corrigido chamada de api para alteração 

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/componentes-sgp/perfil.js, src/SME.SGP.WebClient/src/componentes-sgp/tempoExpiracaoSessao/tempoExpiracaoSessao.js, src/SME.SGP.WebClient/src/servicos/api.js
Este pull request contempla uma correção para evitar expirar a sessão de forma indevida.
Sempre que trocar de perfil ou renovar a sessão, todas as requisições pendentes serão canceladas, para evitar que elas sejam realizadas com o token antigo gerando um erro 401 indevido.
[AB#10159](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/10159)
=> Correção de expiração de sessão

src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
Ajuste na pesquisa de turmas, para que os registros históricos que não possuem turma sejam ignorados. Já que não será possível montar a mensagem e o problema só ocorrerá em ambiente dev
[AB#11666](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/11666)
=> 11667 - Notificação Frequencia: Ajuste na pesquisa de turmas

src/SME.SGP.WebClient/src/componentes-sgp/filtro/index.js
Alteração temporária para sanar problema com professores que estão conseguindo alterar dados passados no sistema
=> Fix para esconder checkbox de histórico no filtro

scripts/V133__AJUSTE_RECUPERACAO_PARALELA4.SQL
Correção Recuperação paralela Acompanhamento, banco de dados, tabela parametros_sistema, exibe a palavra 'pouco' de maneira incorreto
[AB#11976](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/11976)
=> Correção recuperação paralela

src/SME.SGP.WebClient/src/paginas/DiarioClasse/CompensacaoAusencia/listasAlunos/listaAlunos.js
Quando o percentual é zero não estava exibindo valor no grid
[AB#12128](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/12128)
=> 12578 - Apresentar percentual 0.00 quando não houver valor

src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
Erro ao salvar exclusão de evento pois a propriedade Letivo não era carregada
[AB#12133](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/12133)
=> 12133 - Erro ao salvar exclusão de evento

src/SME.SGP.Dominio.Servicos/ServicoEvento.cs
Remover a validação que bloqueia o cadastro de eventos no sabado sem liberação excepcional
[AB#12857](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/12857)
=> Correção cadastro de evento no sabado

src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosPorCodigoEolNome/ObterAlunosPorCodigoEolNomeQueryHandler.cs
[AB#20074](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20074)
Foi retirado o NumeroAlunoChamada pois não estava sendo utilizado e causava duplicidade nos registros
=> Foi retirado o NumeroAlunoChamada 

src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
Ajuste na funcionalidade de turmas extintas, considerando as novas regras.
Turmas extintas após início do ano letivo, considerando o inicio do 1º bimestre serão marcadas como hisórico. As turmas anteriores a essa data serão excluídas, assim como os dados relacionados.
=> Bug: 20438

src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/CalendarioProfessor/index.js
Ajuste na página de calendário de professor, onde ocorria erro ao clicar no dia do mês retornando que não foi possível buscar dados.
=> Bug: 25973

src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
Vários usuários na base sem RF mas com Login, na hora de inserir da erro de Login já existente.
[AB#30409](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30409)
=> 30409 - Obter usuário por Login ao invés de RF

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/componentes/listaPaginada/listaPaginada.js
[AB#34728](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34728)
=> 34728 - limpar dados da listagem quando o retorno é vazio

src/SME.SGP.WebClient/src/paginas/Gestao/AtribuicaoEsporadica/Form/index.js, src/SME.SGP.WebClient/src/paginas/Gestao/AtribuicaoEsporadica/componentes/DreDropDown.js, src/SME.SGP.WebClient/src/paginas/Gestao/AtribuicaoEsporadica/componentes/UeDropDown.js
Ao cancelar na tela de cadastro de atribuição esporádica os campos DRE e UE são limpos [AB#27588](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27588)
=> R2 - Fix/27588

src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
A chamada do servico da api eol não estava convertendo a enum da modalidade.
[AB#42388](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42388)
=> bug: 42388-  A chamada do servico da api eol

scripts/V471__AJUSTE_RENOMEAR_GRUPOS_COMUNICADOS_CONFORME_MODALIDADES.sql
Conforme os novos nomes das modalidades de EJA, Infantil, Médio e Fundamental, foram renomeados os grupos de comunicados para resolver os problemas das telas que utilizam grupos
[AB#44229](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44229)
=> Fix:44229 rel r2

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorTurmasCodigo/ObterComponentesCurricularesPorTurmasCodigoQueryHandler.cs
Ajuste na funcionalidade de tratar disciplinas da turma retornadas pelo EOL para considerar também as turmas e não somente o código da disciplina. Dessa forma teremos a informação correta para a turma original.
=> Bug: 48257

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
Ajuste ao obter notas do conselho de classe que acionar API/EOL para obter as disciplinas só será informado o ano se a turma for do tipo turno 4, senão será 0 para disciplinas padrões de regência.
=> Bug: 53987

src/SME.SGP.Aplicacao/CasosDeUso/PeriodosEscolares/ObterPeriodosPorComponenteUseCase.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaFrequenciaAulas/ObterListaFrequenciaAulasQueryHandler.cs
Foi ajustado o endpoint de períodos para o diário de bordo, pegando não pelas aulas e sim pelo início e término do bimestre, e reparei também que se por exemplo, na tela de frequências, aquele período selecionado não tiver aula, ele exibe erro interno. Foi feito um tratamento para que isso não acontecesse mais. Segue o teste feito em dev do erro:
=> Ajuste no endpoint de períodos + frequencia listão

src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMes/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesQueryHandler.cs
[AB#56982](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56982)
=> 56982 - Icone de avaliação cadastrada não aparece no calendário

src/SME.SGP.Dominio/Entidades/RelatorioCorrelacao.cs
Removido a vinculação de boletim simples ao jasper (agora é razor)
=> Removido a vinculação de boletim simples ao jasper (agora é razor)

src/SME.SGP.Api/Controllers/AbrangenciaController.cs
Ajuste na listagem e abrangência de turma para o filtro de relatório de frequência para turmas ajustando a condição de verificação de itens na lista.
Aplicação desse ajuste na listagem de semestre, caso não retorne itens na lista sem considerar histórico, faz a busca novamente como histórico.
=> Bug: 62006

scripts/V535__AJUSTE_FUNCAO_F_EVENTOS_CALENDARIO_DIAS_COM_EVENTOS_NO_MES.sql
A funcao retornava eventos relacionados ao mes da data de inicio no caso nesse caso acabou retornando as datas de eventos de bimestre referente a outros meses. 
Por isso foi adicionado uma condição na função filho onde ela valida o mes pela data do evento.
=> Bug 62233 Ajustes na funcao de eventos do mes

src/SME.SGP.Aplicacao/Commands/AtribuicaoCJ/InserirAtribuicaoCJ/InserirAtribuicaoCJCommandHandler.cs
Realizamos a correção comentando a validação atribuída, pois a mesma não será necessária.
=> Atribuição de CJ - Não é possível realizar substituição na turma onde o professor já é o titular.

src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAulaConsulta.cs, src/SME.SGP.Infra/Dtos/AulaPossuiFrequenciaAulaRegistradaDto.cs
Alterado a query ObterDatasAulasPorProfessorEComponenteQuery.
Alterado a carga de PossuiFrequenciaRegistrada, removido a consulta de dentro do loop de aulas 
Criado ObterDatasDeAulasPorAnoTurmaEDisciplinaVerificandoSePossuiFrequenciaAulaRegistrada , para não alterar o ObterDatasDeAulasPorAnoTurmaEDisciplina que já é utilizado em outros lugares e devolve a entidade Aula
e criado AulaPossuiFrequenciaAulaRegistradaDto para retorno do ObterDatasDeAulasPorAnoTurmaEDisciplinaVerificandoSePossuiFrequenciaAulaRegistrada somente com os campos que o ObterAulasNosPeriodos precisa
[AB#68388](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68388)
=> Alterar consulta de Frequencia Registrada para Aula

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#70105](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70105)
=> Inconsistência ao salvar uma nota numérica pós-conselho em branco

src/SME.SGP.Aplicacao/Queries/FechamentoReabertura/ObterNotificacaoParaExcluirPorFechamentoReabertura/ObterNotificacaoParaExcluirPorFechamentoReaberturaIdQuery.cs, src/SME.SGP.Aplicacao/Queries/FechamentoReabertura/ObterNotificacaoParaExcluirPorFechamentoReabertura/ObterNotificacaoParaExcluirPorFechamentoReaberturaIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoReabertura.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoReabertura.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoReabertura.cs
Algumas notificações de ação (que dependem de aprovação ou recusa) estão travadas para o usuário. Ele aceita ou recusa, porém elas continuam aparecendo como se não tivesse tomado nenhuma ação.
[AB#63310](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63310)
[AB#70760](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70760)
=> Notificações travadas para o supervisor

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
Ajuste na listagem de turmas para a abrangência, aplicando a distinção não só pelo nome da turma, mas também pelo código.
=> Bug: 78898

teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
[AB#89870](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/89870)
=> Ajustes para incluir componente 138 do teste de compensação de ausência.

src/SME.SGP.Aplicacao/Commands/Fechamento/IncluirFechamentoFinal/IncluirFechamentoFinalCommandHandler.cs
[AB#102195](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/102195)
=> Command estava com contexto de leitura

src/SME.SGP.Api/Controllers/FechamentoTurmaController.cs, src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoTurmaDisciplina.cs, src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosFechamentoTurmaDisciplina.cs, src/SME.SGP.Dominio.Interfaces/Servicos/IServicoFechamentoTurmaDisciplina.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
Inclusão de verificação ao disparar o processamento de fechamento não aplicar a validação alunos inativos com notas fora do período de fechamento. Essa validação se aplica no lançamento da nota.
=> Bug: 120344

src/SME.SGP.Dominio/Entidades/Aula.cs
Ajuste no processo de registrar frequência removendo a validação se permite substituição de frequência desconsiderando os componentes antigos de PAP de recuperação paralela.
=> Bug: 123387

SME.SGP.Api.Teste/Controllers/BuscaAtivaControllerTeste.cs
O teste unitário verifica se o método ObterRegistrosAcao da classe BuscaAtivaController retorna um OkObjectResult contendo os dados esperados quando chamado com um filtro específico.
=> Adicionado teste do busca ativa controller

src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs, src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs
Introduced a new list, `responsavelEscolaDreDtoComTiposNaoExistente`, in `ConsultasSupervisor.cs` to store supervisor school assignments without certain types. Updated filtering operations to apply to this new list and modified the return statement to order by `TipoEscola` and `Nome`.
In `RepositorioSupervisorEscolaDre.cs`, modified the SQL query to use a `LEFT JOIN` for a more comprehensive retrieval of school and supervisor assignment data, ensuring inclusion of schools without assigned supervisors.
=> Refactor supervisor assignment handling and SQL query

src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs
Code cleanup to correct the filtering operation.
The pull request refines the filtering logic for `responsavelEscolaDreDtoComTiposNaoExistente` to ensure it correctly converts the filtered results into a list. 
- ConsultasSupervisor.cs: Changed the filtering operation to use `ToList()` instead of square brackets for proper list conversion.
=> Correct the filtering operation

teste/SME.SGP.TesteIntegracao/Abrangencia/Ao_obter_abrangencia_perfil_poa.cs, teste/SME.SGP.TesteIntegracao/Setup/CollectionFixture.cs, teste/SME.SGP.TesteIntegracao/Setup/FakeHttpMessageHandler.cs, teste/SME.SGP.TesteIntegracao/Setup/RegistradorDependenciasTeste.cs, teste/SME.SGP.TesteIntegracao/appsettings.json
Introduces FakeHttpMessageHandler to mock HTTP responses in integration tests. Updates dependency registration to use the fake handler for HTTP clients, ensuring test isolation and control over external API calls. Adjusts test setup and appsettings to support the new mocking approach.
=> Add HTTP client mocking for integration tests

scripts/V737__CRIAR_TABELA_CONSOLIDACAO_ALFABETIZACAO_CRITICA_ESCRITA.sql, src/SME.SGP.Aplicacao/CasosDeUso/PainelEducacional/ConsolidarInformacoesAlfabetizacaoCriticaEscritaPainelEducacionalUseCase.cs, src/SME.SGP.Aplicacao/Commands/PainelEducacional/SalvarConsolidacaoAlfabetizacaoCriticaEscrita/SalvarConsolidacaoAlfabetizacaoCriticaEscritaCommand.cs, src/SME.SGP.Aplicacao/Commands/PainelEducacional/SalvarConsolidacaoAlfabetizacaoCriticaEscrita/SalvarConsolidacaoAlfabetizacaoCriticaEscritaCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PainelEducacional/IConsolidarInformacoesAlfabetizacaoCriticaEscritaPainelEducacionalUseCase.cs, src/SME.SGP.Aplicacao/Queries/Sondagem/ObterConsolidacaoAlfabetizacaoCriticaEscrita/ObterConsolidacaoAlfabetizacaoCriticaEscritaQuery.cs, src/SME.SGP.Aplicacao/Queries/Sondagem/ObterConsolidacaoAlfabetizacaoCriticaEscrita/ObterConsolidacaoAlfabetizacaoCriticaEscritaQueryHandler.cs, src/SME.SGP.Dados/Mapeamentos/ConsolidacaoAlfabetizacaoCriticaEscritaMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoAlfabetizacaoCriticaEscrita.cs, src/SME.SGP.Dados/Repositorios/RepositorioDreConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoAlfabetizacaoCriticaEscrita.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDreConsulta.cs, src/SME.SGP.Dominio/Entidades/ConsolidacaoAlfabetizacaoCriticaEscrita.cs, src/SME.SGP.Dominio/Entidades/PainelEducacionalNumeroEstudantesAgrupamentoNivelAlfabetizacao.cs, src/SME.SGP.Infra.Consts/ServicoSondagemConstants.cs, src/SME.SGP.Infra.Mensageria/Rotas/RotasRabbitSgpPainelEducacional.cs, src/SME.SGP.Infra/Dtos/Sondagem/SondagemConsolidacaoAlfabetizacaoCriticaEscritaDto.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarPainelEducacionalUseCaseRabbitSgp.cs, src/SME.SGP.IoC/RegistrarDependencias.cs, src/SME.SGP.PainelEducacional.Worker/WorkerRabbitPainelEducacional.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/PainelEducacional/ConsolidarInformacoesAlfabetizacaoCriticaEscritaPainelEducacionalUseCaseTeste.cs, teste/SME.SGP.Aplicacao.Teste/Commands/PainelEducacional/SalvarConsolidacaoAlfabetizacaoCriticaEscritaCommandHandlerTeste.cs, teste/SME.SGP.Aplicacao.Teste/Queries/Sondagem/ObterConsolidacaoAlfabetizacaoCriticaEscritaQueryHandlerTeste.cs
Implementa o worker para consolidação dos dados do sondagem para os indicadores das 10 ues com estudantes não alfabéticos o painel educacional, incluindo nova tabela SQL, entidade de domínio, repositório, caso de uso, comando, consulta, mapeamento e registro de dependências. Adiciona testes relacionados e integra-se ao RabbitMQ para processamento em segundo plano. Permite a recuperação e o armazenamento de dados de consolidação de alfabetização crítica do serviço Sondagem.
=> Adiciona worker para consolidação dos indicadores de alfabetização critica

src/SME.SGP.Aplicacao/Commands/PainelEducacional/SalvarConsolidacaoAlfabetizacaoCriticaEscrita/SalvarConsolidacaoAlfabetizacaoCriticaEscritaCommandHandler.cs, src/SME.SGP.Dados/Mapeamentos/DreMap.cs, src/SME.SGP.Dominio/Entidades/Dre.cs, teste/SME.SGP.Aplicacao.Teste/Commands/PainelEducacional/SalvarConsolidacaoAlfabetizacaoCriticaEscritaCommandHandlerTeste.cs, teste/SME.SGP.Dominio.Teste/DreTeste.cs
Introduz a propriedade PrefixoDoNomeAbreviado à entidade Dre para gerar nomes abreviados. Atualiza o manipulador de comandos e os testes relacionados para usar a nova propriedade, garantindo que os nomes das escolas sejam formatados com o prefixo correto. Adiciona um teste unitário para a lógica de abreviação.
=> Adicionar lógica de abreviação do nome Dre e atualizar o uso

src/SME.SGP.Dominio/Entidades/Dre.cs, teste/SME.SGP.Dominio.Teste/DreTeste.cs
Dre.PrefixoDoNomeAbreviado foi atualizado para retornar o nome original quando for nulo, vazio ou com espaços em branco. Testes unitários foram adicionados para verificar o comportamento correto nesses casos.
=> Trata nome Dre vazio ou nulo em abreviação
