prefeiturasp/SME-NovoSGP

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs
[AB#16780](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/16780)
=> 16780 - Carregar recomendações iniciais quando null

src/SME.SGP.Aplicacao/Consultas/ConsultasNotasConceitos.cs, src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs
[AB#16705](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16705)
=> Ajuste lançamento notas

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
[AB#16774](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16774)
=> Ajuste busca turma abrangencia login

src/SME.SGP.Aplicacao/Consultas/ConsultasPeriodoFechamento.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoReabertura.cs
[AB#15642](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/15642)
=> 15642 - Corrigido validação de reabertura de periodo considerando WF

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasNotasConceitos.cs, src/SME.SGP.Infra/Dtos/FechamentoNotaRetornoDto.cs, src/SME.SGP.WebClient/src/servicos/Paginas/Fechamento/ServicoFechamentoBimestre.js
=> Fix/16651 

src/SME.SGP.Aplicacao/Consultas/ConsultasTurma.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasTurma.cs, src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs
[AB#15642](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/15642)
=> 15642 - Alterado validação de periodo aberto na inclusão e exclusão

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs
[AB#16780](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/16780)
=> 16780 - Corrigido condição de checagem de valor na propriedade

src/SME.SGP.Aplicacao/Queries/Aula/ObterPodeCadastrarAulaPorData/ObterPodeCadastrarAulaPorDataQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoReabertura.cs, src/SME.SGP.Infra/Dtos/PodeCadastrarAulaPorDataRetornoDto.cs
[AB#16599](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/16599)
=> 16599 - Corrigido habilitação de cadastro de aula

src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
[AB#16599](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/16599)
=> 16599 - Corrigido query de consulta de eventos letivo/não letivo

src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasDisciplina.cs
[AB#15050](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/15050)
=> 15050 - Corrigido liberação de edição de aula histórica

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/componentes-sgp/ListaFrequencia/listaFrequencia.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/FrequenciaPlanoAula/frequenciaPlanoAula.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/PlanoAula/plano-aula.js
[AB#16487](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16487)
=> AB#16877 AB#16916

src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodo.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaAlunoDisciplinaPeriodo.cs, src/SME.SGP.Dominio.Servicos/ServicoCalculoFrequencia.cs
[AB#15810](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/15810)
=> Ajuste busca frequencia

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Relatorios/PAP/RelatorioSemestral/servicoSalvarRelatorioSemestral.js, src/SME.SGP.WebClient/src/redux/modulos/relatorioSemestralPAP/actions.js, src/SME.SGP.WebClient/src/redux/modulos/relatorioSemestralPAP/reducers.js
Correção bug dados desatualizados relatorio semestral PAP
[AB#16909](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16909)
=> Correção bug dados desatualizados

src/SME.SGP.Aplicacao/Queries/Aula/ObterPodeCadastrarAulaPorData/ObterPodeCadastrarAulaPorDataQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTipoCalendario.cs, src/SME.SGP.Dominio.Servicos/ServicoAula.cs, src/SME.SGP.Infra/Dtos/PodeCadastrarAulaPorDataRetornoDto.cs
[AB#15050](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/15050)
=> 15050 - Corrigido condições para Habilitar cadastro de Aula e Salvamento

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Dominio/Entidades/ComponenteCurricularEol.cs
=> Ajuste disciplina possui objetivos

scripts/V191__EVENTOS_FECHAMENTO_NAO_LETIVO.sql, src/SME.SGP.Dominio.Servicos/ServicoFechamentoReabertura.cs
[AB#16578](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/16578)
=> 16983 - Correção do tipo Letivo nos eventos de reabertura de fechamento

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Dominio/Entidades/ComponenteCurricularEol.cs
[AB#16921](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16921)
=> Ajuste validação possui objetivos disciplina

src/SME.SGP.Dados/Repositorios/RepositorioRecuperacaoParalela.cs
[AB#16883](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16883)
=> Ajuste query recuperação paralela

src/SME.SGP.Dominio.Servicos/ServicoPeriodoFechamento.cs
[AB#16991](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16991)
=> Ajuste período fechamento abertura inicio minimo

src/SME.SGP.Dados/Mapeamentos/PeriodoFechamentoBimestreMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioPeriodoFechamento.cs, src/SME.SGP.Dados/Repositorios/RepositorioPeriodoFechamentoBimestre.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoFechamento.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoFechamentoBimestre.cs, src/SME.SGP.Dominio.Interfaces/Servicos/IServicoPeriodoFechamento.cs, src/SME.SGP.Dominio.Servicos/ServicoPeriodoFechamento.cs, src/SME.SGP.Dominio/Entidades/PeriodoFechamento.cs, src/SME.SGP.Dominio/Entidades/PeriodoFechamentoBimestre.cs, src/SME.SGP.Infra/Dtos/PeriodoFechamentoBimestreUEDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
[AB#16639](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/16639)
=> 16639 - Alteração periodo fechamento hierarquico

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#17019](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17019)
=> Ajuste busca turma fechamento

src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/AnotacoesRecomendacoes/AnotacoesAluno/anotacoesAluno.js, src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/AnotacoesRecomendacoes/AnotacoesPedagogicas/anotacoesPedagogicas.js, src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/AnotacoesRecomendacoes/RecomendacaoAlunoFamilia/recomendacaoAlunoFamilia.js, src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/Sintese/Sintese.js, src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/dadosConselhoClasse.js
[AB#16476](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16476) [AB#16893](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16893)
=> AB#16666 AB#17030

src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoFrequencia.cs
[AB#16926](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16926)
=> Ajuste query busca frequencia notificação

src/SME.SGP.Aplicacao/Consultas/ConsultasNotasConceitos.cs
[AB#17025](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17025)
=> 17041 - trazer alunos ativos mesmo que tenham numero 0 na chamada

src/SME.SGP.Dominio.Servicos/ServicoPeriodoFechamento.cs, src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/PeriodoFechamentoAbertura/periodo-fechamento-abertura.js
[AB#16689](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16689)
=> 17016 - Retirar valores não utilizados do registro pai

src/SME.SGP.Dominio.Servicos/ServicoAula.cs
[AB#16578](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/16578)
=> 17006 - Não permitir criação de aula em feriado

src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/Justificativa/Justificativa.js
[AB#16778](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16778)
=> 17045 - Aplicar validação de podeEditar no campo de Justificativa

src/SME.SGP.Dados/Repositorios/RepositorioEventoFechamento.cs, src/SME.SGP.Dominio.Servicos/ServicoPeriodoFechamento.cs, src/SME.SGP.Dominio/Entidades/EventoFechamento.cs
[AB#16878](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/16878)
=> 16878 - Incluso atualização do evento de fechamento hierarquico

scripts/V195__TIPO_EVENTO_FECHAMENTO_LETIVO.sql
[AB#17115](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/17115)
=> 17115 - Tipo Evento Fechamento - Letivo: Opcional

src/SME.SGP.Aplicacao/Comandos/ComandosDiasLetivos.cs
[AB#17064](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17064)
=> 17091 - Remover eventos para contagem de dias letivos

src/SME.SGP.Aplicacao/Comandos/ComandosDiasLetivos.cs
[AB#17064](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17064)
=> Correção dias letivos

src/SME.SGP.Aplicacao/Queries/RelatorioSemestralPAP/ObterListaSemestresRelatorioPAP/ObterListaSemestresRelatotioPAPQuery.cs
Quando a consulta é realizada fora de período escolar ocorre erro na tela, o correto é consultar sem permissão de edição
[AB#16912](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/16912)
=> 16912 - Removido obrigatoriedade de bimestre atual;

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/componentes/cardCollapse.js, src/SME.SGP.WebClient/src/componentes/cardHeader.js, src/SME.SGP.WebClient/src/paginas/Relatorios/PAP/RelatorioSemestral/DadosRelatorioSemestral/CamposRelatorioSemestral/campoRelatorioSemestral.js
Correção CardHeader onClick
[AB#16909](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16909)
=> Correção CardHeader onClick

src/SME.SGP.WebClient/src/paginas/Login/index.js
[AB#16669](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16669)
=> correção versão mobile login

README.md
=> BREAKING CHANGE v2.0.0

src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAnual.cs
- Alterando de ao invés de pegar o usuário logado completo, apenas o código Rf na função de obter turmas para cópia;
=> plano aula usuário rf

src/SME.SGP.Aplicacao/Queries/RelatorioSemestralPAP/ObterRelatorioSemestralPorTurmaSemestreAluno/ObterRelatorioSemestralPorTurmaSemestreAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioRelatorioSemestralPAPAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioRelatorioSemestralTurmaPAP.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/PAP/RelatorioSemestral/servicoSalvarRelatorioSemestral.js, src/SME.SGP.WebClient/src/redux/modulos/relatorioSemestralPAP/actions.js, src/SME.SGP.WebClient/src/redux/modulos/relatorioSemestralPAP/reducers.js
[AB#16913](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16913)
[AB#16909](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16909)
[AB#16910](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16910)
=> Relatorio semestral - save, edit, auditoria

src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAnual.cs
Alterando de ao invés de pegar o usuário logado completo, apenas o código Rf na função de obter turmas para cópia;
fix: plano-aula-usuario
=> plano aula usuario

src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/PeriodoFechamentoReabertura/periodoFechamentoReaberturaForm.js
[AB#11765](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/11765)
=> 11765 - Loading ao salvar fechamento (Reabertura)

src/SME.SGP.WebClient/src/paginas/DiarioClasse/CompensacaoAusencia/compensacaoAusenciaLista.js
Adicionar mensagem de componente sem frequencia na compensação de ausencia
[AB#16716](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16716)
=> Adicionar mensagem de componente sem frequencia na compensação de ausencia

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Planejamento/PlanoAnual/bimestre.js
Correção objetivos selecionados
[AB#14036](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/14036)
=> Correção objetivos selecionados

teste/SME.SGP.Aplicacao.Teste/Comandos/ComandosEventoTeste.cs, teste/SME.SGP.Aplicacao.Teste/Comandos/ComandosPlanoAulaTeste.cs, teste/SME.SGP.Aplicacao.Teste/Comandos/ComandosRelatorioSemestralAlunoTeste.cs, teste/SME.SGP.Aplicacao.Teste/Servicos/ServicoGithubTeste.cs
- Comentando testes passados para aplicação passar na verificação dos testes
[AB#16667](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16667)
=> Ajustes nos testes unitários.

src/SME.SGP.WebClient/src/paginas/DiarioClasse/CompensacaoAusencia/compensacaoAusenciaLista.js
Adicionar mensagem componente sem frequencia compensação de ausencia
[AB#17283](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17283)
=> Adicionar mensagem componente sem frequencia compensação de ausencia

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Planejamento/PlanoAnual/bimestre.js
Correção remover objetivos selecionados
[AB#17264](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17264)
=> Correção remover objetivos selecionados

src/SME.SGP.Dominio.Servicos/ServicoFechamentoReabertura.cs, src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs, src/SME.SGP.Dominio/Entidades/FechamentoReabertura.cs
[AB#16641](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16641) [AB#17400](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17400)
=> fix:16641 alterações mensagens

src/SME.SGP.Infra/Enumerados/Permissao.cs, src/SME.SGP.WebClient/src/paginas/Planejamento/TerritorioSaber/componentes/DropDownTerritorios.js, src/SME.SGP.WebClient/src/paginas/Planejamento/TerritorioSaber/index.js, src/SME.SGP.WebClient/src/rotas/rotas.js
Confirmação ao salvar;
Ajuste de menu;
=>  Revisão de frontend

src/SME.SGP.WebClient/src/paginas/DiarioClasse/CompensacaoAusencia/compensacaoAusenciaLista.js
Adicionar mesnagem componente sem frequencia compensação de ausencia
[AB#17283](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17283)
=> Adicionar mesnagem componente sem frequencia

src/SME.SGP.Aplicacao/CasosDeUso/AbstractUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/IUseCase.cs
=> Use Case Abstract e Interface base

teste/SME.SGP.Integracao.Teste/PlanoAnualTerritorioSaberTeste.cs
O mesmo está no token porem não existe na base de dados;
=> Comentando teste que utiliza usuário logado;

src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/conselhoClasse.js, src/SME.SGP.WebClient/src/servicos/Paginas/ConselhoClasse/ServicoConselhoClasse.js
[AB#17297](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17297)
=> 17297 - Consumir endpoint de imprimir aluno

src/SME.SGP.WebClient/src/paginas/DiarioClasse/FrequenciaPlanoAula/frequenciaPlanoAula.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/PlanoAula/plano-aula.js
Correção plano de aula professor CJ
[AB#17648](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17648)
=> Correção plano de aula professor CJ

src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasDisciplina.cs
Cadastro de aula - Professor CJ
[AB#17749](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17749)
=> Cadastro de aula - Professor CJ

src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
Frequência - Erro ao salvar frequência com aluno transferido
[AB#17715](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17715)
=> Frequência - Erro ao salvar frequência com aluno transferido

src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json
Frequência - Erro no processo de notificação de alteração
[AB#17251](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17251)
=> Frequência - Erro no processo de notificação de alteração

src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
Adicionando msg para informar quando não encontrar o parametro na tabela.
=> Adicionando msg sentry

src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
Correção não permite lançar frequência no dia que o aluno foi transferido
[AB#17715](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17715)
=> Correção não permite lançar frequência no dia que o aluno foi transferido

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoReabertura.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoReabertura.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoReaberturaBimestre.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoReaberturaBimestre.cs, src/SME.SGP.Dominio/Entidades/FechamentoReabertura.cs, src/SME.SGP.Dominio/Entidades/FechamentoReaberturaBimestre.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/componentes-sgp/UeDropDown/index.js, src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/PeriodoFechamentoReabertura/periodoFechamentoReaberturaLista.js
[AB#16647](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16647)
=> 16647 - Correções período de fechamento reabertura

teste/SME.SGP.Integracao.Teste/ConselhoClasseTeste.cs
[AB#9282](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/9282)
=> Testes integração

src/SME.SGP.Aplicacao/CasosDeUso/Boletim/BoletimUseCase.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioBoletimDto.cs
[AB#18118](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18118)
=> Ajuste DTO filtro relatório boletim

src/SME.SGP.Aplicacao/CasosDeUso/Boletim/BoletimUseCase.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterAlunosSimplesDaTurma/ObterAlunosSimplesDaTurmaQueryHandler.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioBoletimDto.cs
[AB#17909](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17909)
=> Ajustes endpoint relatorio boletim

src/SME.SGP.Aplicacao/Queries/Turma/ObterAlunosSimplesDaTurma/ObterAlunosSimplesDaTurmaQueryHandler.cs
[AB#17909](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17909)
=> Ordenação aluno

src/SME.SGP.Aplicacao/Comandos/ComandosPlanoAnualTerritorioSaber.cs, src/SME.SGP.Infra/Dtos/BimestrePlanoAnualTerritorioSaberDto.cs
[AB#18183](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18183)
=> Ajuste validação desenvolvimento/reflexao do plano território

src/SME.SGP.Aplicacao/Comandos/ComandosPlanoAnualTerritorioSaber.cs
[AB#18183](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18183)
=> Ajustes mapeamento dominio

src/SME.SGP.WebClient/src/paginas/DiarioClasse/PlanoAula/plano-aula.js
[AB#16584](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16584)
=> 16584 - Desabilitar botões "Migrar conteúdo" e "Nova avaliação" quando não houver permissão

src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaRecorrente/AlterarAulaRecorrenteCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaUnica/AlterarAulaUnicaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaUnica/InserirAulaUnicaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Aulas/ValidarGradeAula/ValidarGradeAulaCommand.cs
[AB#18370](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18370)
=> Ajuste quantidade aula CJ

src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaUnica/InserirAulaUnicaCommandHandler.cs
[AB#18353](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18353)
=> Ajuste inserção workflow aprovação

src/SME.SGP.WebClient/src/paginas/Planejamento/TerritorioSaber/index.js
[AB#18350](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18350)
=> territorio do saber - habilitar btn salvar em modo edicao

src/SME.SGP.Aplicacao/CasosDeUso/Aula/AlterarAulaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaRecorrente/AlterarAulaRecorrenteCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/ProcessoExecutando/RemoverProcessoEmExecucao/RemoverProcessoEmExecucaoCommand.cs, src/SME.SGP.Aplicacao/Commands/ProcessoExecutando/RemoverProcessoEmExecucao/RemoverProcessoEmExecucaoCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioProcessoExecutando.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioProcessoExecutando.cs
[AB#18375](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18375)
=> Ajustes mensagem e exclusão em lote de processos em execução

src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaUnica/InserirAulaUnicaCommandHandler.cs
[AB#18385](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18385)
=> Ajuste validação workflow aprovação

src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaUnica/InserirAulaUnicaCommandHandler.cs
[AB#18353](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18353)
=> Ajustes validação reposição aula

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Boletim/BoletimUseCase.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioBoletimDto.cs
[AB#4518](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/4518)
=> Adição usuário relatorio boletim

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ConselhoClasse/ImpressaoConselhoClasseAlunoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ConselhoClasse/ImpressaoConselhoClasseTurmaUseCase.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioConselhoClasseDto.cs
[AB#9282](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/9282)
=> Envio de usuário no dto de relatorio de conselho de classe

src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/BoletimSimples/index.js
=> foi habilitada a permissão podeIncluir para habilitar o botão

src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/ObjectCardConselhoClasse/objectCardConselhoClasse.js
[AB#18541](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18541)
=> 18541-Ajuste mensagem de retorno

Jenkinsfile
Ajustes para melhorar performance dos build e apenas dev deve coletaras métricas do sonar
=> Ajuste jenkins file

Jenkinsfile
=> Correção de identação

scripts/V202__AJUSTE_TITULO_NOTIFICACAO.sql
Ajuste na tabela do banco
[AB#18266](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18266)
=> Ajuste na tabela do banco

src/SME.SGP.Api/Controllers/UnidadesEscolaresController.cs, src/SME.SGP.Aplicacao/CasosDeUso/ObterFuncionarios/ObterFuncionariosUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/ReiniciarSenha/ReiniciarSenhaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/IObterFuncionariosUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/IReiniciarSenhaUseCase.cs, teste/SME.SGP.Aplicacao.Teste/Handlers/ReiniciarSenhaComandHandlerTeste.cs
[AB#18683](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18683)
- Correção no teste de reiniciar senha
- Separação de UseCases (ReiniciarSenha e ObterFuncionarios)
=> Separacao de UseCases

src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/BoletimSimples/componentes/Filtro/index.js
ajuste na exibição do filtro de semestres
=>  correção no filtro de semestre AB#18720

src/SME.SGP.WebClient/src/paginas/CalendarioProfessor/CadastroAula/cadastroAula.js
[AB#18441](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18441)
=> recorrencia aula - desabilitar quando for edicao tipo aula única

src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/PeriodoFechamentoReabertura/periodoFechamentoReaberturaForm.js
[AB#16647](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16647)
=> 18588 - ajsutes tela duplicando campos

src/SME.SGP.Dominio.Servicos/ServicoFechamentoReabertura.cs, src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs, src/SME.SGP.Dominio/Entidades/FechamentoReabertura.cs
[AB#16641](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16641)
=> Ajuste notificação periodo reabertura

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodo.cs
[AB#18821](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18821)
=> Ajustes busca frequência

src/SME.SGP.Aplicacao/CasosDeUso/ObterFuncionarios/ObterFuncionariosUseCase.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Queries/Funcionario/ObterFuncionariosQuery.cs, src/SME.SGP.Aplicacao/Queries/Funcionario/ObterFuncionariosQueryHandler.cs
[AB#18925](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18925)
=> Ajuste filtros pesquisa

src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Aplicacao/Queries/Funcionario/ObterFuncionariosQueryHandler.cs
[AB#18922](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18922)
=> Ajuste busca funcionarios dre ue

src/SME.SGP.WebClient/src/paginas/Configuracoes/Usuarios/reiniciarSenha.js
[AB#18965](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18965)
foi retirado o toast com mensagem de sucesso, que agora é apresentada…… no modal
=> Retirar toast redundante

src/SME.SGP.WebClient/src/paginas/CalendarioProfessor/CadastroAula/cadastroAula.js
[AB#18370](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18370)
=> cadastro aula - ajuste quantidade aulas

src/SME.SGP.Api/Controllers/HistoricoEscolarController.cs, src/SME.SGP.Aplicacao/Queries/Fechamento/ObterFechamentoPorTurmaPeriodo/ObterFechamentoPorTurmaPeriodoQueryHandler.cs, src/SME.SGP.Infra/Dtos/Relatorios/HistoricoEscolar/AlunoDto.cs, src/SME.SGP.Infra/Dtos/Relatorios/HistoricoEscolar/FiltroBuscaAlunosDto.cs, src/SME.SGP.Infra/Dtos/Relatorios/HistoricoEscolar/FiltroRelatorioHistoricoEscolarDto.cs
[AB#19196](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19196)
=> Implementação de endpoints mockados para filtro e geracao do report

src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioBoletimDto.cs
[AB#4518](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/4518)
=> Ajuste filtro

src/Benchmarks/SME.SGP.Benchmarks/Configs/MainConfig.cs, src/Benchmarks/SME.SGP.Benchmarks/Contexto/ContextoBenchmark.cs, src/Benchmarks/SME.SGP.Benchmarks/DapperInterceptorBenchMark.cs, src/Benchmarks/SME.SGP.Benchmarks/Program.cs, src/SME.SGP.Dados/Contexto/DapperInterceptor.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json
=> Interceptor dapper para log das queries no insights

src/SME.SGP.Aplicacao/Commands/Relatorios/GerarRelatorio/GerarRelatorioCommand.cs, src/SME.SGP.Aplicacao/Commands/Relatorios/GerarRelatorio/GerarRelatorioCommandHandler.cs, src/SME.SGP.Infra/Dtos/Relatorios/PublicaFilaRelatoriosDto.cs, src/SME.SGP.Infra/Fila/FilaRabbit.cs, src/SME.SGP.Infra/Fila/MensagemRabbit.cs
[AB#19188](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/19188)
=> 19188 - Passagem do perfil do usuario para o worker de relatorios

src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
[AB#19518](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19518)
=> Ajuste verificação níveis aprovação

src/SME.SGP.Api/Controllers/BoletimController.cs, src/SME.SGP.Api/Controllers/HistoricoEscolarController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Aluno/ObterAlunosPorCodigoEolNomeUseCase.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/IObterAlunosPorCodigoEolNomeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosPorCodigoEolNome/ObterAlunosPorCodigoEolNomeQuery.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosPorCodigoEolNome/ObterAlunosPorCodigoEolNomeQueryHandler.cs, src/SME.SGP.Aplicacao/SME.SGP.Aplicacao.csproj, src/SME.SGP.Infra/Dtos/Relatorios/HistoricoEscolar/FiltroBuscaAlunosDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/componentes/LocalizadorEstudante/index.js, src/SME.SGP.WebClient/src/paginas/Relatorios/HistoricoEscolar/historicoEscolar.js, src/SME.SGP.WebClient/src/redux/modulos/localizadorEstudante/actions.js, src/SME.SGP.WebClient/src/redux/modulos/localizadorEstudante/reducers.js, src/SME.SGP.WebClient/src/redux/modulos/reducers.js
[AB#17415](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/17415)
=> 17415 - Ajustes filtros do relatório

src/SME.SGP.WebClient/src/componentes/loader.js, src/SME.SGP.WebClient/src/paginas/RecuperarSenha/index.js
Inserir loading reset senha
[AB#14903](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/14903)
=> Inserir loading reset senha

scripts/V207__HISTORICO_REINICIO_SENHA_CREATE.sql, src/SME.SGP.Api/Controllers/AutenticacaoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/ReiniciarSenha/ReiniciarSenhaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Usuarios/GravarHistoricoReinicioSenha/GravarHistoricoReinicioSenhaCommand.cs, src/SME.SGP.Aplicacao/Commands/Usuarios/GravarHistoricoReinicioSenha/GravarHistoricoReinicioSenhaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Usuarios/ReiniciarSenha/ReiniciarSenhaCommand.cs, src/SME.SGP.Aplicacao/Commands/Usuarios/ReiniciarSenha/ReiniciarSenhaCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/IReiniciarSenhaUseCase.cs, src/SME.SGP.Dados/Mapeamentos/HistoricoReinicioSenhaMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioHistoricoReinicioSenha.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioHistoricoReinicioSenha.cs, src/SME.SGP.Dominio/Entidades/HistoricoReinicioSenha.cs, src/SME.SGP.Infra/Dtos/DreUeDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs, src/SME.SGP.WebClient/src/paginas/Configuracoes/Usuarios/reiniciarSenha.js
[AB#18176](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/18176)
=> 18176 - Criado histórico de reinicio de senha

ETL/18_Fechamento/18.1 - (SQL) Cria tabela em Manutenção (ETL_SGP_Fechamento).sql, ETL/18_Fechamento/18.2 - (PostgreSQL) Cria tabelas no SGP (etl_sgp_fechamento e etl_sgp_fechamento_acerto).sql, ETL/18_Fechamento/18.3 - (SQL) Processa e popula a tabela em Manutenção.sql, ETL/18_Fechamento/18.4 - (SQL para PostgreSQL) SELECT para gerar CSV + INSERT (etl_sgp_fechamento).sql, ETL/18_Fechamento/18.5 - (PostgreSQL) INSERT na tabela fechamento_turma.sql, ETL/18_Fechamento/18.6 - (PostgreSQL) INSERT na tabela fechamento_turma_disciplina.sql, ETL/18_Fechamento/18.7 - (PostgreSQL) INSERT na tabela fechamento_aluno.sql, ETL/18_Fechamento/18.8 - (PostgreSQL) INSERT na tabela fechamento_nota.sql
(ETL) Fechamento - Testes e Evidências
[AB#16024](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16024)
=> (ETL) Fechamento - Testes e Evidências

src/SME.SGP.Aplicacao/Consultas/ConsultasPeriodoEscolar.cs, src/SME.SGP.Dados/Repositorios/RepositorioTipoCalendario.cs, src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/dadosConselhoClasse.js
Correção no front e back end para buscar/exibir os periodos de acordo com a modalidade
[AB#19154](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19154)
=> Correção conselho de classe EJA

src/SME.SGP.Aplicacao/Commands/Relatorios/EnviaNotificacaoCriador/EnviaNotificacaoCriadorCommandHandler.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
[AB#19607](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19607)
=> Incluindo nome do arquivo no download

src/SME.SGP.WebClient/src/paginas/DiarioClasse/Notas/notas.js
Combo não permite selecionar componente currícular ao mudar de turma.
[AB#16426](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/16426)
=> Combo não permite selecionar componente currícular ao mudar de turma.

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Comuns/CopiarCodigoCorrelacaoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/ICopiarCodigoCorrelacaoUseCase.cs, src/SME.SGP.Dominio/Entidades/RelatorioCorrelacao.cs, src/SME.SGP.Infra/Fila/RotasRabbit.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
Adicionando fila no sgp para copiar comando;
=> Adicionando command para copiar um código de correlação

src/SME.SGP.WebClient/src/paginas/Relatorios/HistoricoEscolar/historicoEscolar.js
[AB#19557](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19557) [AB#19682](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19682)
=> Ajustes para desabilitar campos

src/SME.SGP.Aplicacao/Consultas/ConsultasObjetivoAprendizagem.cs
[AB#19865](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/19865)
=> 19865 - Objetivos de LPS para turma especial

src/SME.SGP.Aplicacao/Consultas/ConsultasObjetivoAprendizagem.cs, src/SME.SGP.Infra/Dtos/FiltroObjetivosAprendizagemDto.cs, src/SME.SGP.Infra/Dtos/ObjetivoAprendizagemDto.cs
[AB#19866](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/19866)
=> 19865 - Turmas Multiseriadas

src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#19831](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19831)
=> Ajuste permissão duplicada

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasObjetivoAprendizagem.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasObjetivoAprendizagem.cs
[AB#19880](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/19880)
=> 19880 - Carregar atributo ObjetivosAprendizagemOpcionais pra CJ

src/SME.SGP.WebClient/src/paginas/DiarioClasse/FrequenciaPlanoAula/frequenciaPlanoAula.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/PlanoAula/plano-aula.js
[AB#19871](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19871)
=> Objetivos Libras e LPS - ajuste regra de exibicao dos objetivos

src/SME.SGP.Aplicacao/Comandos/ComandosPlanoAula.cs
[AB#19860](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/19860)
=> 19860 - Corrigido save do plano aula

src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
[AB#19925](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19925)
=> Ajuste notificação

src/Benchmarks/SME.SGP.Benchmarks/DapperInterceptorBenchMark.cs, src/SME.SGP.Api/Startup.cs, src/SME.SGP.Dados/Interceptors/DapperInterceptor.cs
Adicionando rastreio da requisição completa do postgres
[AB#19817](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19817)
=> Melhorando o uso de memória do dapper interceptor

src/SME.SGP.Aplicacao/Consultas/ConsultasPeriodoEscolar.cs
=> Ajuste dev

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Comuns/ReceberRelatorioComErroUseCase.cs
[AB#19938](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19938)
=> Ajustes mensagem erro relatório

src/SME.SGP.WebClient/src/dtos/rotasDto.js, src/SME.SGP.WebClient/src/paginas/Relatorios/HistoricoEscolar/historicoEscolar.js, src/SME.SGP.WebClient/src/paginas/Relatorios/Pendencias/relatorioPendencias.js, src/SME.SGP.WebClient/src/rotas/rotas.js
[AB#19630](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19630)
=> 19630 - Criação da tela e consumo de endpoints

docker-compose.database.yml, src/SME.SGP.Api/Controllers/RelatorioPendenciasFechamentoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/HistoricoEscolar/HistoricoEscolarUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/PendenciasFechamento/RelatorioPendenciasFechamentoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/IRelatorioPendenciasFechamentoUseCase.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/Comuns/ValidaSeExisteDrePorCodigo/ValidaSeExisteDrePorCodigoQuery.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/Comuns/ValidaSeExisteDrePorCodigo/ValidaSeExisteDrePorCodigoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/Comuns/ValidaSeExisteTurmaPorCodigo/ValidaSeExisteUePorCodigoQuery.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/Comuns/ValidaSeExisteTurmaPorCodigo/ValidaSeExisteUePorCodigoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/Comuns/ValidaSeExisteUePorCodigo/ValidaSeExisteTurmaPorCodigoQuery.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/Comuns/ValidaSeExisteUePorCodigo/ValidaSeExisteTurmaPorCodigoQueryHandler.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioPendenciasFechamentoDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs, teste/SME.SGP.Integracao.Teste/HistoricoEscolarTeste.cs, teste/SME.SGP.Integracao.Teste/RelatorioPendenciasFechamentoTeste.cs
[AB#19640](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19640)
Implementação para controller de geração de relatório de pendências o fechamento
ajuste no docker-compose-database
=> Endpoint Gerar Relatório de penência

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/componentes/LocalizadorEstudante/index.js
[AB#19898](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19898)
=> correção localizador de estudantes, registro duplicado

src/SME.SGP.WebClient/src/paginas/Relatorios/HistoricoEscolar/historicoEscolar.js
[AB#19923](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19923)
=> 19923 - Ajuste histório escolar para habilitar botão gerar ao selecionar aluno por código EOL

src/SME.SGP.WebClient/src/paginas/Relatorios/Pendencias/relatorioPendencias.js, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/Pendencias/ServicoRelatorioPendencias.js
[AB#19631](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19631)
=> consumir endpoint de gerar relatório

src/SME.SGP.Api/Controllers/AbrangenciaController.cs
[AB#19939](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19939)
Ajuste na busca por dres para considerar histórico em caso de anos letivos menores que o ano atual
=> Correção de busca de dres por ano letivo

src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#19635](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19635)
=> Menu e Permissionamento para o relatório de pendências do fechamento

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/PendenciasFechamento/RelatorioPendenciasFechamentoUseCase.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioPendenciasFechamentoDto.cs, src/SME.SGP.WebClient/src/componentes/listaPaginada/listaPaginada.js, src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/conselhoClasse.js, src/SME.SGP.WebClient/src/paginas/Fechamento/PendenciasFechamento/pendenciasFechamentoLista.css.js, src/SME.SGP.WebClient/src/paginas/Fechamento/PendenciasFechamento/pendenciasFechamentoLista.js
[AB#19637](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19637)
=> 19673 - Botão imprimir

src/SME.SGP.Api/Controllers/AbrangenciaController.cs
[AB#20394](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20394)
ajuste no filtro para considerar filtro considerando historico para os endpoints de ues e turmas,
=> Ajuste no Ues e Turmas (ConsideraHistorico)

src/SME.SGP.Aplicacao/Comandos/ComandosAtribuicaoCJ.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Dominio.Servicos/ServicoAtribuicaoEsporadica.cs, src/SME.SGP.Dominio/Constantes/Perfis.cs, src/SME.SGP.Dominio/Entidades/AtribuicaoEsporadica.cs, src/SME.SGP.Dominio/Enumerados/ModalidadeTipoCalendario.cs
[AB#20310](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20310)
=> Ajuste novo endpoint EOL atribuição CJ e esporádica

scripts/V212__PRIORIDADE_PERFIS_INFANTIL.sql, src/SME.SGP.Infra/Enumerados/GrupoSGP.cs
[AB#20025](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20025)
=> Adição grupos SGP e prioridade perfil infantil

src/SME.SGP.Dominio.Servicos/ServicoUsuario.cs, src/SME.SGP.Dominio/Entidades/Usuario.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json
[AB#19581](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/19581)
=> Ajustes na verificação dos perfis

src/SME.SGP.Api/Controllers/ProfessorController.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAtribuicaoEsporadica.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasProfessorTurma.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasProfessorTurma.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs
[AB#20306](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20306)
=> Ajuste regra professor infantil atribuição esporádica

src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs
[AB#20538](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/20538)
=> 20538 - Corrigido ordenação da lista de modalidades

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterListaAlunosDaTurmaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterAlunosSimplesDaTurma/ObterAlunosSimplesDaTurmaQueryHandler.cs, src/SME.SGP.Infra/Dtos/AlunoSimplesDto.cs
[AB#20419](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20419)
=> Inclusão da situação na lista de alunos

src/SME.SGP.Aplicacao/Integracoes/ServicoPerfil.cs, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Dominio/Constantes/Perfis.cs, src/SME.SGP.Dominio/Entidades/PrioridadePerfil.cs, src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#20544](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20544)
=> Ajuste prioridade perfis CJ

src/SME.SGP.Api/Controllers/AbrangenciaController.cs
[AB#20540](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/20540)
=> 20540 - Corrigido condição para consulta de abrangencia histórica

src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/Eventos/eventosForm.js, src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/Eventos/eventosLista.js
[AB#20652](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/20652)
=> 20652 - Removido concatenação do tipo de escola no front

src/SME.SGP.Api/Controllers/RelatorioParecerConclusivoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ParecerConclusivo/RelatorioParecerConclusivoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IRelatorioPareceConclusivoUseCase.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioParecerConclusivoDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#20536](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20536)
=> Implementação de serviço de geração do relatório

src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
[AB#20655](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/20655)
=> 20655 - Corrigido Parametros da função e paginação

src/SME.SGP.WebClient/src/paginas/Relatorios/Frequencia/faltasFrequencia.js
Descomentada a opção disabled do select de formato para possiblidade de gerar relatório no formato excel
=> Inclusão de formato Excel

src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Cadastro/index.js
Correção de cadastro de alunos
[AB#20750](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20750)
=> Correção de cadastro de alunos

src/SME.SGP.Aplicacao/Consultas/ConsultaComunicado.cs, src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs, src/SME.SGP.Infra/Dtos/ComunicadoCompletoDto.cs, src/SME.SGP.Infra/Extensoes/EnumExtensao.cs, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Cadastro/Lista/ListaAlunosSelecionados.js, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Cadastro/index.js, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Filtro/index.js
Ao acessar com usuário UE, apresenta erro em tela
Ajuste na edição de comunicado de UE
[AB#20795](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20795)
[AB#20788](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20788)
=>  Ao acessar com usuário UE, apresenta erro em tela

src/SME.SGP.Aplicacao/Consultas/ConsultaComunicado.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosUesPorAbrangencia/ObterFiltroRelatoriosUesPorAbrangenciaQueryHandler.cs, src/SME.SGP.Infra/Extensoes/EnumExtensao.cs, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Cadastro/index.js, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Filtro/index.js, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Helper/helper.js
Correção visuais e na listagem de comunicados
[AB#20800](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20800) [AB#20806](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20806)
=> Correção visuais e na listagem de comunicados

src/SME.SGP.Aplicacao/Consultas/ConsultaComunicado.cs, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Cadastro/index.js, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Helper/helper.js, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Lista/index.js
Correção cache listagem e semestre
[AB#20827](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20827)
[AB#20782](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20782)
=> Correção cache listagem

src/SME.SGP.Aplicacao/Consultas/ConsultasTipoCalendario.cs, src/SME.SGP.Dados/Repositorios/RepositorioTipoCalendario.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTipoCalendario.cs
[AB#20805](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/20805)
=> 20805 - incluso filtro de modalidades pela abrangencia do usuario

src/SME.SGP.Aplicacao/Consultas/ConsultaComunicado.cs, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Cadastro/Lista/ListaAlunosSelecionados.js, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Cadastro/index.js
Correção alunos e listagem
[AB#20804](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20804)
[AB#20827](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20827)
=> Correção alunos e listagem

src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Cadastro/index.js
Correção comportamental modalidade
[AB#20840](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20840)
=> Correção comportamental modalidade

src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#20529](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20529)
=> implementação de permissão para o relatório de parecer conclusivo

src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/PeriodoFechamentoReabertura/periodoFechamentoReaberturaLista.js
[AB#20760](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/20760)
=> 20760 - removido tratamento de modalidade do filtro

src/SME.SGP.Aplicacao/Consultas/ConsultasAtribuicoes.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs, src/SME.SGP.Dominio.Servicos/ServicoAtribuicaoCJ.cs
[AB#20883](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20883)
=> Ajuste atribuição/abrangencia CJ infantil

src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosAnosEscolaresPorModalidadeUe/ObterFiltroRelatoriosAnosEscolaresPorModalidadeUeQueryHandler.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/Frequencia/faltasFrequencia.js, src/SME.SGP.WebClient/src/paginas/Relatorios/Pendencias/relatorioPendencias.js
[AB#20889](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20889)
=> Ajuste telas de relatórios

src/SME.SGP.WebClient/src/paginas/Gestao/AtribuicaoEsporadica/componentes/UeDropDown.js
[AB#20902](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/20902)
=> 20902 - Corrigido carga do atributo ehInfantil na Escola

src/SME.SGP.WebClient/src/paginas/Relatorios/PAP/RelatorioSemestral/DadosRelatorioSemestral/ObjectCardRelatorioSemestral/objectCardRelatorioSemestral.js, src/SME.SGP.WebClient/src/paginas/Relatorios/PAP/RelatorioSemestral/relatorioSemestral.js
[AB#12006](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/12006)
=> Aplicando condicoes para poder imprimir relatorio

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodo.cs
[AB#20886](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20886)
=> Ajuste calculo frequência

src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#20910](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/20910)
=> 20910 - Ajuste metodo EhProfessor na entidade Usuario

src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs
[AB#20934](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/20934)
=> 20934 - Corrigido condição para filtro de aulas do professor;

src/SME.SGP.Api/Controllers/ConselhoClasseController.cs, src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterPareceresConclusivosUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConselhoClasse/IObterPareceresConclusivosUseCase.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterPareceresConclusivos/ObterPareceresConclusivosQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterPareceresConclusivos/ObterPareceresConclusivosQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseParecerConclusivo.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseParecerConclusivo.cs, src/SME.SGP.Infra/Dtos/ConselhoClasseParecerConclusivoDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs, teste/SME.SGP.Integracao.Teste/ConselhoClasseTeste.cs
[AB#20593](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20593)
=> Endpoint listagem pareceres conclusivos

src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioParecerConclusivoDto.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/ParecerConclusivo/relatorioParecerConclusivo.js, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/ParecerConclusivo/ServicoRelatorioParecerConclusivo.js
[AB#20603](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20603)
=> consumo de endpoints ajustes

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Relatorios/Pendencias/relatorioPendencias.js
[AB#21132](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21132)
[AB#21147](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21147)
=> 21132 - Correção filtro relatório de pendências troca de anos

src/SME.SGP.Api/Controllers/FiltroRelatorioController.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/ParecerConclusivo/relatorioParecerConclusivo.js, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/ParecerConclusivo/ServicoRelatorioParecerConclusivo.js
[AB#21157](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21157)
- Consumo endpoint de ciclo
- ajuste campo de semestre
=> 21157 - ajustes e consumo do endpoint de ciclos

src/SME.SGP.WebClient/src/paginas/Relatorios/Pendencias/relatorioPendencias.js
[AB#21248](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21248) [AB#21209](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21209)
=> 21248 - retirar duplicidade de anos letivos

src/SME.SGP.WebClient/src/paginas/Relatorios/Pendencias/relatorioPendencias.js
[AB#21251](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21251) [AB#21231](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21231)
=> 21251 - Mostrar campo semestre

src/SME.SGP.WebClient/src/paginas/Relatorios/Pendencias/relatorioPendencias.js
[AB#21243](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21243)
[AB#21262](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21262)
=> Resolvendo problemas ao limpar filtros

src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioParecerConclusivoDto.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Relatorios/ParecerConclusivo/relatorioParecerConclusivo.js
[AB#20622](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20622)
=> 20622 -Incluir tipo de arquivo excel no filtro

src/SME.SGP.WebClient/src/paginas/Relatorios/Pendencias/relatorioPendencias.js
[AB#21274](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21274) [AB#21269](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21269)
=> 21274 - Ajuste campo codigosTurma formato errado no front

src/SME.SGP.WebClient/src/paginas/Relatorios/Pendencias/relatorioPendencias.js
[AB#21327](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21327) [AB#21321](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21321)
=> 21327 - Ajuste botão cancelar

src/SME.SGP.Dados/Repositorios/RepositorioCiclo.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/ParecerConclusivo/relatorioParecerConclusivo.js
[AB#21358](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21358) [AB#21342](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21342)
=> 21358 - Adicionar mensagem de restrição ao infantil

src/SME.SGP.WebClient/src/paginas/Relatorios/ParecerConclusivo/relatorioParecerConclusivo.js
[AB#21362](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21362)
[AB#21366](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21366)
=> Resolvendo problema de duplicidade no ano letivo

src/SME.SGP.WebClient/src/paginas/Relatorios/ParecerConclusivo/relatorioParecerConclusivo.js
[AB#21375](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21375) [AB#21370](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21370)
=> 21375 - limpar campo de UE quando alterar a DRE

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Relatorios/ParecerConclusivo/relatorioParecerConclusivo.js, src/SME.SGP.WebClient/src/paginas/Relatorios/Pendencias/relatorioPendencias.js, src/SME.SGP.WebClient/src/servicos/Paginas/FiltroRelatorio/ServicoFiltroRelatorio.js
[AB#21378](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21378) [AB#21377](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21377)
=> 21378 - Ajustar consumo de endpoint de modalidade

src/SME.SGP.Dados/Repositorios/RepositorioCiclo.cs
[AB#21384](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21384) [AB#21383](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21383)
=> 21384 - Correção endpoint de ciclos

src/SME.SGP.WebClient/src/paginas/Relatorios/ParecerConclusivo/relatorioParecerConclusivo.js
[AB#21392](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21392) [AB#21388](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21388)
=> 21392 - Limpar modalidade quando alterar a ue

src/SME.SGP.Api/Controllers/RelatorioRecuperacaoParalelaController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/RecuperacaoParalela/RelatorioRecuperacaoParalelaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/IRelatorioRecuperacaoParalelaUseCase.cs, src/SME.SGP.Infra/Dtos/Relatorios/RecuperacaoParalela/FiltroRelatorioRecuperacaoParalelaDto.cs
[AB#20628](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20628)
=> Ajustes no filtro de relatório de recuperação paralela

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Relatorios/PAP/RelatorioSemestral/DadosRelatorioSemestral/ObjectCardRelatorioSemestral/objectCardRelatorioSemestral.js, src/SME.SGP.WebClient/src/paginas/Relatorios/PAP/RelatorioSemestral/relatorioSemestral.js, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/PAP/RelatorioSemestral/ServicoRelatorioSemestral.js
[AB#21395](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21395)
=> 21395 - consumir endpoint de gerar relatório semestral

src/SME.SGP.Api/Controllers/FiltroRelatorioController.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/ParecerConclusivo/relatorioParecerConclusivo.js, src/SME.SGP.WebClient/src/servicos/Paginas/FiltroRelatorio/ServicoFiltroRelatorio.js, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/ParecerConclusivo/ServicoRelatorioParecerConclusivo.js
[AB#21409](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21409) [AB#21408](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21408)
=> 21409 - Ajustes filtro

src/SME.SGP.Aplicacao/Consultas/ConsultasAtribuicoes.cs, src/SME.SGP.Dados/Repositorios/RepositorioAtribuicaoEsporadica.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtribuicaoEsporadica.cs
[AB#21246](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21246)
=> Ajuste na listagem de ues na tela de atribuição de CJ

src/SME.SGP.WebClient/src/paginas/Relatorios/ParecerConclusivo/relatorioParecerConclusivo.js
[AB#21543](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21543) [AB#21425](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21425)
=> 21543 - ajuste tipo de dado ano

src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioParecerConclusivoDto.cs
[AB#21453](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21453)
=> Ajuste filtro ciclo

src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterPareceresConclusivos/ObterPareceresConclusivosQueryHandler.cs
[AB#21542](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21542)
=> Adicionado filtro sem parecer conclusivo

src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
[AB#20933](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/20933)
=> Ajuste na obtenção da abrangencia do supervisor

src/SME.SGP.Api/Controllers/DiarioBordoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/ObterDiarioBordoUseCase.cs, src/SME.SGP.Aplicacao/Commands/DiarioBordo/AlterarDiarioBordo/AlterarDiarioBordoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/DiarioBordo/InserirDiarioBordo/InserirDiarioBordoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Aula/AulaExiste/AulaExisteQuery.cs, src/SME.SGP.Aplicacao/Queries/Aula/AulaExiste/AulaExisteQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioBase.cs, src/SME.SGP.Dados/Repositorios/RepositorioTestePostgre.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioBase.cs, teste/SME.SGP.Integracao.Teste/DiarioBordoTeste.cs, teste/SME.SGP.Integracao.Teste/FrequenciaTeste.cs
Criação do método Exists no RepositorioBase;
=> 19422 - Correção dos testes de integração;

src/SME.SGP.Api/Controllers/FrequenciaController.cs
[AB#21769](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/21769)
=> 21769 - Incluso permissão do diario de bordo no endpoint 

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Relatorios/ParecerConclusivo/relatorioParecerConclusivo.css.js, src/SME.SGP.WebClient/src/paginas/Relatorios/ParecerConclusivo/relatorioParecerConclusivo.js
[AB#21767](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21767) [AB#21671](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21671)
=> 21767 - Correção campo de anos extrapolando o tamanho

scripts/V219__ETAPA_ENSINO_EJA.sql, src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs, src/SME.SGP.Dados/Mapeamentos/TurmaMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs, src/SME.SGP.Dominio/Entidades/Turma.cs, src/SME.SGP.Infra/Dtos/AbrangenciaTurmaRetornoEolDto.cs
[AB#21508](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21508)
=> Sincronização etapa eja

scripts/V220__PARAMETRO_MUNICIPIO_ATENDIMENTO.sql, src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
[AB#21520](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21520)
=> Parametro de municipio atendimento

src/SME.SGP.Dominio.Servicos/ServicoEvento.cs
[AB#21259](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/21259)
=> 21259 - Corrigido referencia ao TipoCalendario

src/SME.SGP.Aplicacao/Consultas/ConsultasPeriodoEscolar.cs
=> story/18770 - ajustes

src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterDatasAulasPorTurmaEComponenteUseCase.cs
[AB#21888](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/21888)
=> 21888 - Corrigido parametro ehProfessor na query de aulas

src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
[AB#21880](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21880)
=> Ajuste no serviço de sincronização da abrangencia

src/SME.SGP.Aplicacao/Queries/Aula/ObterPodeCadastrarAulaPorData/ObterPodeCadastrarAulaPorDataQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPeriodoFechamento.cs
[AB#21891](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/21891)
=> 21891 - Correção do método de consulta de período de fechamento

src/SME.SGP.WebClient/src/componentes-sgp/UeDropDown/index.js, src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/Calendario/index.js, src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/Eventos/eventosForm.js, src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/Eventos/eventosLista.js, src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/PeriodoFechamentoAbertura/periodo-fechamento-abertura.js, src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/PeriodoFechamentoReabertura/periodoFechamentoReaberturaForm.js, src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/PeriodoFechamentoReabertura/periodoFechamentoReaberturaLista.js, src/SME.SGP.WebClient/src/servicos/Abrangencia/index.js, src/SME.SGP.WebClient/src/servicos/Paginas/Calendario/ServicoCalendarios.js, src/SME.SGP.WebClient/src/servicos/Paginas/Calendario/ServicoEvento.js
[AB#21893](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/21893)
=> endpoint obter ues add parametro modalidade turma

src/SME.SGP.Aplicacao/Comandos/ComandosRelatorioSemestralPAPAluno.cs, src/SME.SGP.Aplicacao/Comandos/ComandosRelatorioSemestralPAPAlunoSecao.cs, src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosRelatorioSemestralAlunoSecao[.cs, src/SME.SGP.Dados/Repositorios/RepositorioRelatorioSemestralPAPAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioRelatorioSemestralPAPAlunoSecao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRelatorioSemestralPAPAlunoSecao.cs
[AB#22196](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22196)
=> Ajuste inserção/alteração secao relatorio semestral pap

src/SME.SGP.Api/Controllers/AbrangenciaController.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasAbrangencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAbrangencia.cs
[AB#22261](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22261)
=> Ajuste endpoint obter anos turma por abrangencia

src/SME.SGP.Api/Controllers/AbrangenciaController.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasAbrangencia.cs
[AB#22261](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22261)
=> Ajuste retorno endpoint anos turma por abrangencia

src/SME.SGP.Api/Startup.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasPeriodoEscolar.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json
=> Ajustes merge master/release

src/SME.SGP.WebClient/src/paginas/Relatorios/HistoricoEscolar/historicoEscolar.js
[AB#22431](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22431) [AB#22552](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22552)
=> 22431 - Correção

src/SME.SGP.Dados/Repositorios/RepositorioDevolutiva.cs
[AB#22717](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/22717)
=> 22717 - incluso RF na coluna CriadoPor na listagem de devolutivas

src/SME.SGP.Aplicacao/CasosDeUso/Devolutiva/InserirDevolutivaUseCase.cs
[AB#22735](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/22735)
=> 22735 - Corrigido carga de turma para validação de período de abertura

README.md
=> BREAKING CHANGES

src/SME.SGP.Aplicacao/CasosDeUso/Aula/CriacaoAutomatica/CriarAulasInfantilAutomaticamenteUseCase.cs, src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommand.cs, src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/DiasLetivos/ObterDiasPorPeriodosEscolaresComEventosLetivosENaoLetivos/ObterDiasPorPeriodosEscolaresComEventosLetivosENaoLetivosQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterDiasForaDoPeriodoEscolar/ObterDiasForaDoPeriodoEscolarQuery.cs, src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterDiasForaDoPeriodoEscolar/ObterDiasForaDoPeriodoEscolarQueryHandler.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#22668](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22668)
=> Ajuste na remoção de aulas fora do periodo escolar

src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs
[AB#21888](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/21888)
=> 21888 - corrigido query de datas da tela de frequencia

src/SME.SGP.WebClient/src/componentes/Alunos/Detalhes/index.js
[AB#22858](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22858)
=>  Object card ajuste exibição botoes impressao e frequencia

src/SME.SGP.Api/Controllers/RelatorioController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Calendario/RelatorioCalendarioUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/IRelatorioCalendarioUseCase.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/Comuns/ValidaSeExisteTipoCalendarioPorId/ValidaSeExisteTipoCalendarioPorIdQuery.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/Comuns/ValidaSeExisteTipoCalendarioPorId/ValidaSeExisteTipoCalendarioPorIdQueryHandler.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioCalendarioDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
[AB#22458](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/22458)
=> Endpoint SGP relatório calendário

src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/Eventos/eventosLista.js
[AB#23126](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23126)
=> lista de eventos - erro ao abrir a tela quando dre ja vem selecionada

scripts/V228__PARAMETRO_PERCENTUAL_FREQUENCIA_MIN_INFANTIL.sql, src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
[AB#22896](https://dev.azure.com/amcomgov/Novo%20SGP/_sprints/taskboard/Novo%20SGP%20Team/Novo%20SGP/Sprint%2031%20(Nogueira)%20-%20OS_XXX_SME_2020%20-%20NOVO%20SGP%20MVP%202?workitem=22896)
=> Criar parametro do % freq. Infantil

src/SME.SGP.WebClient/src/paginas/Relatorios/NotasConceitosFinais/relatorioNotasConceitosFinais.js
[AB#23240](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23240) [AB#23243](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23243)
=> 23240 - Ajuste habilitar gerar  com eja

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.WebClient/src/componentes-sgp/filtro/index.js
Ajuste na funcionalidade de pesquisa de turma no filtro principal de abrangência.
Foi necessário uma ajuste no front-end e no back-end para o método de busca de turmas para o filtro (esse referenciava o código incorreto da turma).
=> Bug: 22973

src/SME.SGP.Api/Configuracoes/RegistraClientesHttp.cs, src/SME.SGP.Api/Controllers/UsuarioEscolaAquiController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/ObterUsuarioPorCpf/ObterUsuarioPorCpfUseCase.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoAcompanhamentoEscolar.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/ObterUsuarioPorCpf/IObterUsuarioPorCpfUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/ObterUsuarioPorCpfQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/ObterUsuarioPorCpfQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/ObterUsuarioPorCpfQueryValidator.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/Usuario/SolicitarReiniciarSenhaDto.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/Usuario/UsuarioEscolaAquiDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
AB#23329
Implementação de endpoint de Reiniciar a senha do usuário no Aplicattvo Escola Aqui
=> Implementação de endpoint de Reiniciar a senha do usuário no App

src/SME.SGP.Api/Controllers/TipoCalendarioController.cs, src/SME.SGP.Aplicacao/CasosDeUso/TipoCalendario/BuscarTiposCalendarioPorDescricaoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/TipoCalendario/IBuscarTiposCalendarioPorDescricaoUseCase.cs, src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTipoCalendarioPorBusca/ObterTipoCalendarioPorBuscaQuery.cs, src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTipoCalendarioPorBusca/ObterTipoCalendarioPorBuscaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTipoCalendario.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTipoCalendario.cs, src/SME.SGP.Infra/Dtos/TipoCalendarioBuscaDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/TipoCalendario/BuscarTiposCalendarioPorDescricaoUseCaseTeste.cs, teste/SME.SGP.Integracao.Teste/TipoCalendarioTeste.cs
[AB#23385](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23385)
=> 23385 - Criação de novo endpoint de busca tipos de calendário

src/SME.SGP.Api/Controllers/UsuarioEscolaAquiController.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/ObterUsuarioPorCpfQueryHandler.cs
=> Ajuste no tratamento de mensagens

src/SME.SGP.Api/Controllers/UsuarioEscolaAquiController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/ObterUsuarioPorCpf/ObterUsuarioPorCpfUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/ObterUsuarioPorCpf/IObterUsuarioPorCpfUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/ObterUsuarioPorCpfQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/ObterUsuarioPorCpfQueryHandler.cs
Ajuste na chamada para obter usuarios por Dre, Ue e Cpf de responsável
=> feat: 20083

src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
Ajuste na query para transformação de turmas histórica na funcionalidade de turmas extintas.
=> Bug: 20438

src/SME.SGP.WebClient/src/paginas/Relatorios/Frequencia/faltasFrequencia.js
[AB#23579](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23579)
=> relatorio de faltas e frequencia - comportamento quando troca ano letivo

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorAnosEModalidade/ObterComponentesCurricularesPorAnosEModalidadeQueryHandler.cs, src/SME.SGP.WebClient/yarn.lock
[AB#23599](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23599)
=> Ajuste Componente curricular

scripts/V237__ABRA_DRE_ID.sql, scripts/V238__ABRA_UE_ID.sql, scripts/V239__ABRA_TURMA_ID.sql, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Infra/Dtos/AbrangenciaDreRetorno.cs, src/SME.SGP.Infra/Dtos/AbrangenciaTurmaRetorno.cs, src/SME.SGP.Infra/Dtos/AbrangenciaUeRetorno.cs, src/SME.SGP.WebClient/src/componentes-sgp/filtro/helper.js
- Alterado functions e views para retornarem os ids de dres, ues e turmas
- Alterado endpoints de abrangencia para retornar os ids
- Alterado helper do front para armazenar os ids
[AB#23745](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23745)
=> Adicionando Ids nos filtros de abrangência

src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/ObterDiarioBordoUseCase.cs, src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoDto.cs, src/SME.SGP.WebClient/src/paginas/DiarioClasse/DiarioBordo/diarioBordo.js
[AB#23484](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23484)
=> Adicionado devolutiva no DTO

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasConselhoClasseAlunoTeste.cs
[AB#23360](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23360)
=> 23360 - Teste unitário

scripts/V233__PARAMETRO_ANO_LETIVO_PAP.sql, src/SME.SGP.Aplicacao/Consultas/ConsultasRecuperacaoParalela.cs, src/SME.SGP.Dados/Repositorios/RepositorioRecuperacaoParalela.cs, src/SME.SGP.Infra/Dtos/FiltroRecuperacaoParalelaDto.cs, src/SME.SGP.WebClient/src/componentes-sgp/filtro/index.js, src/SME.SGP.WebClient/src/paginas/Relatorios/PAP/Acompanhamento/index.js
Ajustes da refatoração do PAP para atender id de abrangencia ao invés de código
[AB#23380](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23380)
=> Refatoração do PAP

scripts/V241__PENDENCIA_AULA.sql, src/SME.SGP.Dados/Mapeamentos/PendenciaAulaMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAula.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAula.cs, src/SME.SGP.Dominio/Entidades/PendenciaAula.cs, src/SME.SGP.Dominio/Enumerados/TipoPendenciaAula.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
[AB#23777](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23777)
=> Criada modelagem e repositório

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodo.cs
Ajuste ao obter conselho e exibição de mensagem de fechamento, caso não possua bimestre.
=> Bug: 22290

scripts/V241__PENDENCIA_AULA.sql, src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs, src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/Pendencia/IPendenciaAulaUseCase.cs, src/SME.SGP.Dados/Mapeamentos/PendenciaAulaMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAula.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAula.cs, src/SME.SGP.Dominio/Entidades/PendenciaAula.cs, src/SME.SGP.Infra/Fila/RotasRabbit.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#23776](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23776)
=> Job criado

src/SME.SGP.WebClient/src/paginas/Relatorios/PAP/ResumosGraficos/componentes/Filtro/index.js, src/SME.SGP.WebClient/src/paginas/Relatorios/PAP/ResumosGraficos/index.js
adicionando parametro para a chamada do endpoint [AB#23376](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23376)
=> enviando parametro anoLetivo para os endpoints

src/SME.SGP.Api/Controllers/RecuperacaoParalelaController.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasRecuperacaoParalela.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultaRecuperacaoParalela.cs, src/SME.SGP.Dados/Repositorios/RepositorioRecuperacaoParalela.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRecuperacaoParalela.cs, src/SME.SGP.Infra/Dtos/FiltroRecuperacaoParalelaResumoDto.cs
Adicionando ano letivo nos filtros dos endpoints de recuperação paralela
[AB#23375](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23375)
=> Alteração de endpoint recuperação paralela

src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/ExcluirPendenciaAulaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/InserirDiarioBordoUseCase.cs, src/SME.SGP.Aplicacao/Commands/Aulas/Pendencia/Excluir/ExcluirPendenciaAulaCommand.cs, src/SME.SGP.Aplicacao/Commands/Aulas/Pendencia/Excluir/ExcluirPendenciaAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/Pendencia/IExcluirPendenciaAulaUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAula.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAula.cs, src/SME.SGP.Infra/Dtos/Aula/Pendencia/ExcluirPendenciaAulaDto.cs
[AB#18032](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/18032)
=> Criado excluir e refatorado listagem

src/SME.SGP.Aplicacao/Comandos/ComandosPlanoAula.cs
[AB#23780](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23780)
=> Adicionada função no salvar

src/SME.SGP.Aplicacao/Comandos/ComandoFrequencia.cs
[AB#23783](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23783)
=> Adicionado método para remover frequencia no CommandoFrequencia

src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaId/ObterPendenciasAulaPorAulaIdQuery.cs, src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaId/ObterPendenciasAulaPorAulaIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMes/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAula.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAula.cs, src/SME.SGP.Infra/Dtos/EventoAulaDiaDto.cs
[AB#23779](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23779)
=> Criada função para obter as pendências das aulas

src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdQuery/ObterPendenciasAulaPorAulaIdQuery.cs, src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdQuery/ObterPendenciasAulaPorAulaIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdsQuery/ObterPendenciasAulaPorAulaIdsQuery.cs, src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdsQuery/ObterPendenciasAulaPorAulaIdsQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMes/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDia/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDiaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAula.cs, src/SME.SGP.Infra/Dtos/EventoAulaDiaDto.cs, src/SME.SGP.Infra/Dtos/EventoAulaDto.cs
[AB#23778](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23778)
=> Realizada alteração nos notificação dias

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAula.cs
[AB#24087](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24087)
=> Alterado script de avaliacao

teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasConselhoClasseAlunoTeste.cs
[AB#23360](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23360)
=> 23360-ajuste testes unitários

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#24183](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24183)
=> 24183 - Corrigir dados de parecer conclusivo

teste/SME.SGP.Aplicacao.Teste/Comandos/ComandosPlanoAulaTeste.cs
=> Bug: 23358

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/PlanoAula/RelatorioPlanoAulaUseCase.cs, src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioPlanoAulaDto.cs
[AB#23806](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23806)
=> alteração DTO

src/SME.SGP.IoC/Extensions/RegistrarRabbit.cs
[AB#23840](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/23840)
=> Adicionando virtualhost à conexão do rabbitMQ

src/SME.SGP.Aplicacao/CasosDeUso/CartaIntencoes/Observacao/AlterarCartaIntencoesObservacaoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/CartaIntencoes/Observacao/Notificacao/SalvarNotificacaoCartaIntencoesObservacaoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordoObservacaoNotificacao/NotificarDiarioBordoObservacaoUseCase.cs, src/SME.SGP.Aplicacao/Commands/CartaIntencoes/Observacao/Alterar/AlterarCartaIntencoesObservacaoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/DiarioBordo/AlterarObservacaoDiarioBordo/AlterarObservacaoDiarioBordoCommandHandler.cs
[AB#24270](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24270)
=> Correção bug 24270

src/SME.SGP.WebClient/src/servicos/ServicoUsuarioDeslogar.js, src/SME.SGP.WebClient/src/servicos/api.js
incluindo serviço responsável para deslogar o usuário
Deslogando usário quando o retorno da api for 401
=> tratamento 401 na api

src/SME.SGP.WebClient/src/paginas/DiarioClasse/PlanoAula/componentes/BotaoGerarRelatorioPlanoAula/botaoGerarRelatorioPlanoAula.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/PlanoAula/plano-aula.css.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/PlanoAula/plano-aula.js, src/SME.SGP.WebClient/src/servicos/Paginas/DiarioClasse/ServicoPlanoAula.js
[AB#24290](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24290)
=> Criado o botão de impressão

src/SME.SGP.Aplicacao/Commands/Devolutiva/Excluir/ExcluirDevolutivaCommandHandler.cs
[AB#24412](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24412)
=> Correção Bug Exclusão devolutiva

src/SME.SGP.Dominio/Constantes/Perfis.cs, src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#24508](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24508)
=> Adicionado admin UE

src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/PeriodoFechamentoReabertura/periodoFechamentoReaberturaForm.js
Ajuste na tela de reabertura ao desabilitar o campo de tipo de calendário.
=> Bug: 24456

src/SME.SGP.Aplicacao/Queries/PlanejamentoAnual/ObterPlanejamentoAnualPorTurmaComponenteQueryHandler.cs, src/SME.SGP.WebClient/src/servicos/Paginas/ServicoPlanoAnual.js
[AB#24627](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24627)
=> Correção no obter planejamento anual

src/SME.SGP.Api/Controllers/ObjetivoAprendizagemController.cs, src/SME.SGP.Aplicacao/CasosDeUso/ObjetivoAprendizagem/ListarObjetivoAprendizagemPorAnoEComponenteCurricularUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ObjetivoAprendizagem/IObterObjetivoAprendizagemPorAnoEComponenteCurricularUseCase.cs, src/SME.SGP.Aplicacao/Queries/ObjetivoAprendizagem/ListarObjetivoAprendizagemPorAnoEComponenteCurricularQuery/ListarObjetivoAprendizagemPorAnoEComponenteCurricularQuery.cs, src/SME.SGP.Aplicacao/Queries/ObjetivoAprendizagem/ListarObjetivoAprendizagemPorAnoEComponenteCurricularQuery/ListarObjetivoAprendizagemPorAnoEComponenteCurricularQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioObjetivoAprendizagem.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioObjetivoAprendizagem.cs, src/SME.SGP.Dominio/Enumerados/AnoTurma.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#24620](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24620)
=> Criado endpoint

src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs
[AB#24695](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24695)
=> Ajuste recalculo frequência exclusão compensação ausência

src/SME.SGP.WebClient/src/paginas/Relatorios/PAP/ResumosGraficos/componentes/Resumos/index.js, src/SME.SGP.WebClient/src/paginas/Relatorios/PAP/ResumosGraficos/styles.js
corrigindo espaço do botão imprimir [AB#24284](https://dev.azure.com/amcomgov/58a564ef-c8bc-40fd-a237-6ac616945f34/_workitems/edit/24284)
=> ajustando botão de gerar relatorio

src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Comunicados/SolicitarAlteracaoComunicados/SolicitarAlteracaoComunicadoEscolaAquiUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Comunicados/SolicitarInclusaoComunicados/SolicitarInclusaoComunicadoEscolaAquiUseCase.cs, src/SME.SGP.Aplicacao/Commands/EscolaAqui/Comunicados/Alteracao/SolicitarAlteracaoComunicadoEscolaAquiCommand.cs, src/SME.SGP.Aplicacao/Commands/EscolaAqui/Comunicados/Inclusao/SolicitarInclusaoComunicadoEscolaAquiCommand.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoAcompanhamentoEscolar.cs
=> Ajustes na criação e edição de comunicados para receber turmas e alunos

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
[AB#24345](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/24345)
=> 24345 - correção repositorio

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.WebClient/src/paginas/Planejamento/Anual/DadosPlanoAnual/BotoesAcoes/botoesAcoesPlanoAnual.js, src/SME.SGP.WebClient/src/paginas/Planejamento/Anual/DadosPlanoAnual/DescricaoPlanejamento/descricaoPlanejamento.js, src/SME.SGP.WebClient/src/paginas/Planejamento/Anual/DadosPlanoAnual/ListaObjetivos/listaObjetivos.js, src/SME.SGP.WebClient/src/paginas/Planejamento/Anual/DadosPlanoAnual/dadosPlanoAnual.js, src/SME.SGP.WebClient/src/paginas/Planejamento/Anual/planoAnual.js, src/SME.SGP.WebClient/src/paginas/Planejamento/Anual/servicoSalvarPlanoAnual.js, src/SME.SGP.WebClient/src/redux/modulos/anual/actions.js, src/SME.SGP.WebClient/src/redux/modulos/anual/reducers.js, src/SME.SGP.WebClient/src/servicos/Paginas/ServicoPlanoAnual.js
[AB#25135](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25135)
=> plano anual - permissao

src/SME.SGP.Api/Controllers/ComunicadoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Comunicados/SolicitarAlteracaoComunicados/SolicitarAlteracaoComunicadoEscolaAquiUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/Comunicados/ISolicitarAlteracaoComunicadoEscolaAquiUseCase.cs, src/SME.SGP.Infra/Dtos/ComunicadoAlterarDto.cs
=> Ajuste na validação de data de envio na alteração de comunicado

scripts/V253__COLUNA_EVENTOESCOLAAQUI_EVENTO_TIPO.sql
=> adicionada coluna flag eventoescolaaqui para a tabela eventotipo

scripts/V253__MIGRACAO_PLANOS_ANUAL_NOT_MIGRADO.sql, scripts/V255__MIGRACAO_PLANOS_ANUAL_MIGRADO.sql
[AB#25413](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/25413)
=> 25413 - Migração de plano anual

scripts/V255__MIGRACAO_PLANOS_ANUAL_MIGRADO.sql
[AB#25867](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/25867)
=> 25867 - removido script de migração de planos anuais do legado

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
=> ajuste para retornar as turmas filtradas por anos

scripts/V261__COMPONENTE_CURRICULAR_UPDATES.sql
[AB#25924](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/25924)
=> 25924 - Atualização componentes curriculares

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
=> Correção na consulta de turmas por anos

src/SME.SGP.Api/Controllers/TipoCalendarioController.cs, src/SME.SGP.Aplicacao/CasosDeUso/TipoCalendario/ObterTiposCalendarioPorAnoLetivoModalidadeoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/TipoCalendario/IObterTiposCalendarioPorAnoLetivoModalidadeoUseCase.cs, src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTiposCalendarioPorAnoLetivoModalidadeo/ObterTiposCalendarioPorAnoLetivoModalidadeoQuery.cs, src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTiposCalendarioPorAnoLetivoModalidadeo/ObterTiposCalendarioPorAnoLetivoModalidadeoQueryHandler.cs, src/SME.SGP.IoC/RegistraDependencias.cs
=> Endpoint lista tipos de calendario por ano-letivo e modalidade

src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Comunicados/SolicitarAlteracaoComunicados/SolicitarAlteracaoComunicadoEscolaAquiUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Comunicados/SolicitarInclusaoComunicados/SolicitarInclusaoComunicadoEscolaAquiUseCase.cs, src/SME.SGP.Aplicacao/Comandos/ComandoComunicado.cs, src/SME.SGP.Aplicacao/Commands/EscolaAqui/Comunicados/Alteracao/SolicitarAlteracaoComunicadoEscolaAquiCommand.cs, src/SME.SGP.Aplicacao/Commands/EscolaAqui/Comunicados/Alteracao/SolicitarAlteracaoComunicadoEscolaAquiCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EscolaAqui/Comunicados/Inclusao/SolicitarInclusaoComunicadoEscolaAquiCommand.cs, src/SME.SGP.Aplicacao/Commands/EscolaAqui/Comunicados/Inclusao/SolicitarInclusaoComunicadoEscolaAquiCommandHandler.cs, src/SME.SGP.Dados/Mapeamentos/ComunicadoMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs, src/SME.SGP.Dominio/Entidades/Comunicado.cs, src/SME.SGP.Infra/Dtos/ComunicadoAlterarDto.cs, src/SME.SGP.Infra/Dtos/ComunicadoCompletoDto.cs, src/SME.SGP.Infra/Dtos/ComunicadoDto.cs, src/SME.SGP.Infra/Dtos/ComunicadoInserirDto.cs
=> Adicionados campos de tipo calendario e evento no comunicado

src/SME.SGP.Api/Controllers/PlanejamentoAnualController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanejamentoAnual/ObterTurmasParaCopia/ObterTurmasParaCopiaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanejamentoAnual/Salvar/SalvarPlanejamentoAnualUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanejamentoAnual/Copiar/MigrarPlanejamentoAnualCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanejamentoAnual/Excluir/ExcluirPlanejamentoAnualPorTurmaIdEComponenteCurricularId/ExcluirPlanejamentoAnualPorTurmaIdEComponenteCurricularIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanejamentoAnual/Salvar/SalvarPlanejamentoAnualCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanejamentoAnual/ObterTurmasParaCopia/IObterTurmasParaCopiaUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanejamentoAnual/ObterTurmasParaCopiaPlanejamentoAnual/ObterTurmasParaCopiaPlanejamentoAnualQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanejamentoAnual/ObterTurmasParaCopiaPlanejamentoAnual/ObterTurmasParaCopiaPlanejamentoAnualQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasEOLParaCopiaPorIdEComponenteCurricularId/ObterTurmasEOLParaCopiaPorIdEComponenteCurricularIdQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasEOLParaCopiaPorIdEComponenteCurricularId/ObterTurmasEOLParaCopiaPorIdEComponenteCurricularIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanejamentoAnual.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanejamentoAnual.cs, src/SME.SGP.Infra/Dtos/PlanejamentoAnual/MigrarPlanejamentoAnualDto.cs, src/SME.SGP.WebClient/src/paginas/Planejamento/Anual/DadosPlanoAnual/dadosPlanoAnual.js
[AB#25991](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25991)
=> 25991 - Correção do bug

src/SME.SGP.WebClient/src/paginas/CalendarioEscolar/CalendarioProfessor/index.js, src/SME.SGP.WebClient/src/servicos/Paginas/CalendarioProfessor/index.js
Ajuste na página de calendário de professor, onde ocorria erro ao clicar no dia do mês retornando que não foi possível buscar dados.
=> Bug: 25973

src/SME.SGP.Api/Controllers/ComunicadoEventoController.cs, src/SME.SGP.Api/Controllers/TipoCalendarioController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/ComunicadoEvento/ListarEventosPorCalendario/ListarEventosPorCalendarioUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/TipoCalendario/ObterTiposCalendarioPorAnoLetivoUEUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/CominicadoEvento/IListarEventosPorCalendarioUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/TipoCalendario/IObterTiposCalendarioPorAnoLetivoModalidadeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/TipoCalendario/IObterTiposCalendarioPorAnoLetivoUEUseCase.cs, src/SME.SGP.Aplicacao/Queries/ComunicadoEvento/ListarEventosPorCalendario/ListarEventosPorCalendarioQuery.cs, src/SME.SGP.Aplicacao/Queries/ComunicadoEvento/ListarEventosPorCalendario/ListarEventosPorCalendarioQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTiposCalendarioPorAnoLetivoUE/ObterTiposCalendarioPorAnoLetivoUEQuery.cs, src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTiposCalendarioPorAnoLetivoUE/ObterTiposCalendarioPorAnoLetivoUEQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs, src/SME.SGP.Dados/Repositorios/RepositorioTipoCalendario.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEvento.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTipoCalendario.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/ComunicadoEvento/ListarEventoPorCalendarioDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
Correcao bugs AB#26051 e AB#26074
=> Correcao bugs AB#26051 e AB#26074

scripts/V264__EA_INCLUSAO_COLUNA_SERIESRESUMIDAS_COMUNICADOS.sql
=> Script de inclusão de coluna series_resumidas na tabela de comunidados

scripts/V264__EA_INCLUSAO_COLUNA_SERIESRESUMIDAS_COMUNICADOS.sql
=> inclusão da coluna series_resumidas na tabela comunicados

src/SME.SGP.Aplicacao/Comandos/ComandoComunicado.cs, src/SME.SGP.Aplicacao/Commands/EscolaAqui/Comunicados/Exclusao/SolicitarExclusaoComunicadosEscolaAquiCommandHandler.cs
=> Corrigido comportamento de excusao com evento vinculado

src/SME.SGP.WebClient/src/paginas/Planejamento/Anual/servicoSalvarPlanoAnual.js
[AB#26272](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26272)
=> Plano anual - não tentar salvar bimestre que não estiver em edição

src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
[AB#26171](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26171)
=> Correção Bug : Todos os Perfils de POA estão com problemas em DEV 

src/SME.SGP.Aplicacao/Queries/PlanejamentoAnual/ObterPlanejamentoAnualPorTurmaComponente/ObterPlanejamentoAnualPorTurmaComponenteQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PlanejamentoAnual/ObterPlanejamentoAnualPorTurmaComponentePeriodoEscolar/ObterPlanejamentoAnualPorTurmaComponentePeriodoEscolarQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioObjetivoAprendizagem.cs
[AB#26305](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/26305)
=> 26305 - Correção Querys planejamento anual

src/SME.SGP.Dados/Repositorios/RepositorioObjetivoAprendizagemPlano.cs
[AB#26306](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/26306)
=> 26306 - ordenação dos objetivos de aprendizagem do plano anual

src/SME.SGP.Dominio/Entidades/PlanejamentoAnual.cs
[AB#26324](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/26324)
=> 26324 - Removido atributo ObjetivosOpcionais

src/SME.SGP.Dados/Repositorios/RepositorioPlanoAula.cs
[AB#26335](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/26335)
=> 26335 - Incluso registro migrado na consulta de plano aula

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAula/ObterPlanoAulaUseCase.cs
[AB#26460](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26460)
=> Correção do bug 26460 -Plano de aula, Está exigindo plano anual para CJ

src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/ControleGrade/controleGrade.js
[AB#26666](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26666)
=> rel controle de grade - opcao todos em componente curricular é o valor default

src/SME.SGP.WebClient/src/componentes/editor/editor.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/FrequenciaPlanoAula/DadosFrequenciaPlanoAula/PlanoAula/DadosPlanoAula/CamposEditorPlanoAula/desenvolvimentoDaAula.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/FrequenciaPlanoAula/DadosFrequenciaPlanoAula/PlanoAula/DadosPlanoAula/CamposEditorPlanoAula/objetivosEspecificosParaAula.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/FrequenciaPlanoAula/servicoSalvarFrequenciaPlanoAula.js, src/SME.SGP.WebClient/src/redux/modulos/frequenciaPlanoAula/actions.js, src/SME.SGP.WebClient/src/redux/modulos/frequenciaPlanoAula/reducers.js
[AB#26467](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26467)
=> validar campos obrigatorios - frequencia plano aula

src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/ControleGrade/controleGrade.js
[AB#26676](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26676)
=> rel controle de grade - Modalidade de EJA setar somente 2 bimestres Para o filtro

src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
[AB#26700](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26700)
=> Correção do bug , ajuste no emum TipoRelatorio

src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs
[AB#26460](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26460)
=> Correção do bug - Erro ao salvar plano aula sem objetivos

scripts/V267__UPDATE_DESCRICAO_SGP_COMPONENTES_REG_INFANTIL.sql
[AB#26794](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/26794)
=> 26794 - Update descricao_sgp componentes Reg. Classe Infantil

src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/ControleGrade/controleGrade.js
[AB#26875](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/26875)
=> 26875 - Incluso parâmetro semestre Rel Controle de Grade Sintético

src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/ControleGrade/controleGrade.js
[AB#26875](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/26875)
=> 26856 - Alterado endpoint de consulta componentes no Rel Controle Grade

src/SME.SGP.Api/Controllers/ComponentesCurricularesController.cs, src/SME.SGP.Api/Controllers/ProfessorController.cs, src/SME.SGP.Aplicacao/CasosDeUso/ComponentesCurriculares/ObterComponentesCurricularesPorProfessorETurmasCodigosUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ComponentesCurriculares/IObterComponentesCurricularesPorProfessorETurmasCodigosUseCase.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUsuarioECodigoTurma/ObterComponentesCurricularesPorUsuarioECodigoTurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUsuarioECodigoTurma/ObterComponentesCurricularesPorUsuarioECodigoTurmaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricular.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#26955](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/26955)
=> 26955 - Criado endpoint de componentes por usuario e lista de turmas

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
[AB#27017](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/27017)
=> Corrigido busca do dropdown para nao voltar repeticoes

src/SME.SGP.Api/Controllers/ProfessorController.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/ControleGrade/controleGrade.js, src/SME.SGP.WebClient/src/servicos/Paginas/ComponentesCurriculares/ServicoComponentesCurriculares.js
[AB#26955](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26955)
=> rel controle de grade - carregar componente curricular para turma que nao tem ano 

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUsuarioECodigoTurma/ObterComponentesCurricularesPorUsuarioECodigoTurmaQueryHandler.cs
[AB#27066](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/27066)
=> 27066 - Corrigido carga de componentes do território do saber

src/SME.SGP.Api/Controllers/DashboardEscolaAquiController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterUltimaAtualizacaoPorProcesso/ObterUltimaAtualizacaoPorProcessoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/Dashboard/ObterUltimaAtualizacaoPorProcesso/IObterUltimaAtualizacaoPorProcessoUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterUltimaAtualizacaoPorProcesso/ObterUltimaAtualizacaoPorProcessoQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterUltimaAtualizacaoPorProcesso/ObterUltimaAtualizacaoPorProcessoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterUltimaAtualizacaoPorProcesso/ObterUltimaAtualizacaoPorProcessoQueryValidator.cs, src/SME.SGP.Infra/Dtos/PrimeiroAcessoDto.cs, src/SME.SGP.Infra/Dtos/UltimaAtualizaoWorkerPorProcessoResultado.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#26802](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/26802)
=> Implementação de chamada para obter a última alteração do worker APP

src/SME.SGP.Aplicacao/Comandos/ComandosTipoCalendario.cs, src/SME.SGP.Aplicacao/Commands/ParametroSistema/ReplicarParametrosAnoAnterior/ReplicarParametrosAnoAnteriorCommand.cs, src/SME.SGP.Aplicacao/Commands/ParametroSistema/ReplicarParametrosAnoAnterior/ReplicarParametrosAnoAnteriorCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasCompensacaoAusencia.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasNotasConceitos.cs, src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosTipoCalendario.cs, src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterChaveEValorPorTipoEAno/ObterChaveEValorPorTipoEAnoQuery.cs, src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterChaveEValorPorTipoEAno/ObterChaveEValorPorTipoEAnoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ParametroSistema/VerficaSeExisteParametroSistemaPorAno/VerificaSeExisteParametroSistemaPorAnoQuery.cs, src/SME.SGP.Aplicacao/Queries/ParametroSistema/VerficaSeExisteParametroSistemaPorAno/VerificaSeExisteParametroSistemaPorAnoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioParametrosSistema.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioParametrosSistema.cs, src/SME.SGP.Dominio.Servicos/ServicoCalculoParecerConclusivo.cs, src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs, src/SME.SGP.Dominio.Servicos/ServicoNotificacaoAulaPrevista.cs, src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs, src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs, src/SME.SGP.Dominio.Servicos/ServicoRecuperacaoParalela.cs, teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasNotasConceitosTeste.cs
Manutenção na geração de calendário
=> Manutenção na geração de calendário

src/SME.SGP.Api/Controllers/DashboardEscolaAquiController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterTotaisAdesaoAgrupadosPorDre/ObterTotaisAdesaoAgrupadosPorDreUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/Dashboard/ObterTotaisAdesaoAgrupadosPorDre/IObterTotaisAdesaoAgrupadosPorDreUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterTotaisAdesaoAgrupadosPorDre/ObterTotaisAdesaoAgrupadosPorDreQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterTotaisAdesaoAgrupadosPorDre/ObterTotaisAdesaoAgrupadosPorDreQueryHandler.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/DashboardAdesao/TotaisAdesaoAgrupadoProDreResultado.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#27103](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/27103)
=> Foi implementado endpoint de chamada de adesão agrupada por dre

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Infra/Dtos/AbrangenciaFiltroRetorno.cs, src/SME.SGP.WebClient/src/componentes-sgp/filtro/index.js
Ajuste no filtro principal de turma, exibindo o texto de resultado com a modalidade + turma + tipo da escola + nome da escola.
Ajuste no combo de turma que desabilitava ao digitar no texto na busca.
Ajuste no combo de turma apresentando o código ao trocar a modalidade.
=> Bug: 26796

src/SME.SGP.Aplicacao/Queries/ComunicadoEvento/ListarEventosPorCalendario/ListarEventosPorCalendarioQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEvento.cs, src/SME.SGP.Infra/Dtos/ComunicadoEvento/ListarEventosPorCalendarioRetornoDto.cs
[AB#27195](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/27195)
=> Inclusao do TipoDeEvento no retorno do endpoint de Eventos Calendario

src/SME.SGP.Infra/Dtos/EscolaAqui/DashboardAdesao/TotaisAdesaoResultado.cs
=> Correção no nome da propriedade

src/SME.SGP.Dados/Repositorios/RepositorioParametrosSistema.cs
[AB#27203](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27203)
Ajuste no repositorio ReplicarParametrosAnoAnteriorAsync, para retirada do campo inativo
=> Ajuste no repositório  

src/SME.SGP.Dominio/Entidades/Comunicado.cs, src/SME.SGP.Dominio/Enumerados/TipoComunicado.cs
[AB#27270](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/27270)
=> correção de envio de comunicados por SME_ANO e DRE_ANO

src/SME.SGP.Api/Controllers/DashboardEscolaAquiController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterTotaisAdesao/ObterTotaisAdesaoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/Dashboard/ObterTotaisAdesao/IObterTotaisAdesaoUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterTotaisAdesao/ObterTotaisAdesaoQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterTotaisAdesao/ObterTotaisAdesaoQueryHandler.cs
[AB#27274](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/27274)
=> Correção no campo codigo UE

src/SME.SGP.Dominio/Entidades/Comunicado.cs
[AB#27270](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/27270)
=> ajuste no tratamento de comunicados por tipo de comunicado (UE_MOD)

src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoConceitoFechamento/SalvarHistoricoConceitoFechamentoCommand.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoConceitoFechamento/SalvarHistoricoConceitoFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoNotaFechamento/SalvarHistoricoNotaFechamentoCommand.cs, src/SME.SGP.Dados/Repositorios/RepositorioHistoricoNotaFechamento.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioHistoricoNotaFechamento.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
=> Feature/26583 Manutenção Fechamento

src/SME.SGP.WebClient/src/componentes/select-autocomplete.js, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Cadastro/index.js, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Filtro/index.js, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Lista/index.js
[AB#27450](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/27450)
=> release - tela de comunicados - ajustes em validacoes listagem e cadastro

src/SME.SGP.WebClient/src/componentes/select-autocomplete.js, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Cadastro/index.js, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Filtro/index.js, src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Lista/index.js
[AB#27450](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/27450)
=> dev - tela de comunicados - ajustes em validacoes listagem e cadastro

src/SME.SGP.Dados/Repositorios/RepositorioAnoEscolar.cs
[AB#27555](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/27555)
=> ajuste na consulta para obter melhor performance

src/SME.SGP.Dados/Repositorios/RepositorioAnoEscolar.cs
[AB#27567](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/27567)
=> ajuste na consulta para melhorar a performance

src/SME.SGP.Dados/Repositorios/RepositorioAnoEscolar.cs
=> Ordenação por ano

src/SME.SGP.WebClient/src/dtos/rotasDto.js, src/SME.SGP.WebClient/src/paginas/Gestao/DocumentosPlanosTrabalho/documentosPlanosTrabalhoLista.js, src/SME.SGP.WebClient/src/rotas/rotas.js
=> Plano de trabalho - Interface de upload de documentos e planos - LISTAGEM

src/SME.SGP.Api/Controllers/DashboardEscolaAquiController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterComunicadosTotais/ObterComunicadosTotaisSmeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/Dashboard/ObterComunicadosTotais/IObterComunicadosTotaisSmeUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Comunicados/ObterComunicadosTotais/ObterComunicadosTotaisQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Comunicados/ObterComunicadosTotais/ObterComunicadosTotaisQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioComunicado.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/Dashboard/ComunicadosTotais/ComunicadosTotaisSmeResultado.cs, src/SME.SGP.Infra/Enumerados/Permissao.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#27424](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/27424)
=> Implementação parcial de total de comunicados vigentes / expirados

scripts/V275__INCLUSAO_PARAMETROS_DE_QUEM_RECEBE_PENDENCIA.sql, src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
Criação Parâmetros de quem recebe a pendência
=> Criação Parâmetros de quem recebe a pendência

scripts/V275__INCLUSAO_PARAMETROS_DE_QUEM_RECEBE_PENDENCIA.sql
Correção de script para gerar mais de um registro por tipo
=> Correção de script para gerar mais de um registro por tipo

src/SME.SGP.Aplicacao/Commands/PendenciaCalendarioUe/SalvarPendenciaCalendarioUe/SalvarPendenciaCalendarioUeCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciaCalendarioUe/SalvarPendenciaCalendarioUe/SalvarPendenciaCalendarioUeCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaCalendarioUe/VerificaPendenciaCalendarioUe/VerificaPendenciaCalendarioUeCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaParametroEvento/VerificaPendenciaParametroEvento/VerificaPendenciaParametroEventoCommandHandler.cs
Ajuste nos parametros do SalvarPendenciaCalendarioUeCommand
=> Ajuste nos parametros do SalvarPendenciaCalendarioUeCommand

src/SME.SGP.Infra/Dtos/EscolaAqui/DashboardAdesao/TotaisAdesaoAgrupadoProDreResultado.cs
[AB#28064](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/28064)
=> Ajuste no nome da propriedade TotalUsuariosPrimeiroAcesso

scripts manutencao/Bug 23128 - ScriptAtualizacaoDisciplinaFechamentoConselhoClasse_2014_2019.sql
Script para acertos de disciplinas para fechamento e conselho de classe dos anos de 2014 a 2019.
=> Bug: 28128

scripts/V286__AJUSTE_PARAMETRO_PENDENCIAS_GERAIS.sql, src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs, src/SME.SGP.Aplicacao/Commands/PendenciaParametroEvento/VerificaExclusaoPendenciasParametroEvento/VerificaExclusaoPendenciasParametroEventoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaParametroEvento/VerificaPendenciaParametroEvento/VerificaPendenciaParametroEventoCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaCalendarioUe.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaParametroEvento.cs
[AB#28175](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28175)
=> Ajustes das regras de "Pendências Cadastro de eventos pendente" 

src/SME.SGP.WebClient/src/paginas/Relatorios/DashboardEscolaAqui/TabsDashboardEscolaAqui/DadosComunicadosTotais/dadosComunicadosTotais.js
[AB#28263](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/28263)
=> ajuste no nome da propriedade que estava invertida

src/SME.SGP.WebClient/src/paginas/Gestao/DocumentosPlanosTrabalho/documentosPlanosTrabalhoCadastro.js
[AB#28256](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28256)
=> Não está exibindo na auditoria o RF de quem inseriu e de quem alterou o documento de UPLOAD 

src/SME.SGP.Api/Controllers/EventoController.cs, src/SME.SGP.Aplicacao/Comandos/ComandosEvento.cs, src/SME.SGP.Aplicacao/Commands/EscolaAqui/Comunicados/Exclusao/SolicitarExclusaoComunicadosEscolaAquiCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosEvento.cs, src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioComunicado.cs
[AB#28267](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/28267)
=> Ajuste para  validar a existencia de eventos associados ao comunicado

src/SME.SGP.WebClient/src/paginas/Principal/Pendencias/pendenciasGerais.js
[AB#28374](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28374)
=> o expandir uma nova pendência caso já exista outra expandida, esta deve ser suprimida

src/SME.SGP.Aplicacao/Commands/PendenciaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivosCommandHandler.cs
[AB#28469](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28469)
=> Correção bug 28469 - Aulas criadas em dias não letivos" 

ETL/Historias/27053/Exclusão de FK indevida entre PlanoAnualObjetivo e ComponenteCurricular.sql
[AB#27053](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/27053)
=> 27053 - Exclusão de FK indevida entre PlanoAnualObjetivo e Componente

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAula.cs
[AB#28556](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28556)
=> Bug - 28556 Minhas pendências - Dias listados estão fora de ordem

src/SME.SGP.Aplicacao/Commands/PendenciaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivosCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs
[AB#28557](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28557)
=> Correção Bug - Minhas pendências - Problemas no texto da pendência

src/SME.SGP.WebClient/src/paginas/Relatorios/Notificacoes/HistoricoNotificacoes/historicoNotificacoes.js
[AB#28787](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28787)
=> botão Cancelar na tela do Relatório de notificações os filtros (Categoria, Tipo e Situação) exibem sem dados

src/SME.SGP.WebClient/src/paginas/Principal/Pendencias/pendenciasGerais.js
[AB#28652](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28652)
=> RELEASE - Ajustar o comportamento da seção ao expandir cada pendência ao mudar de página

src/SME.SGP.WebClient/src/paginas/Relatorios/Notificacoes/HistoricoNotificacoes/historicoNotificacoes.js
[AB#28787](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/28787)
=> 28787 release

src/SME.SGP.Aplicacao/Consultas/ConsultasProfessorTurma.cs, src/SME.SGP.WebClient/src/componentes/Localizador/componentes/InputRF/index.js
[AB#28778](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28778)
=> RELEASE - Relatório de notificações - Campo Localizador de RF não está limitando a qtde de caracteres e a mensagem de alert de erro está incorreta

src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAula.cs
Reverts prefeiturasp/SME-NovoSGP#4476
=> Revert "fix/23631-release"

src/SME.SGP.Aplicacao/Commands/PendenciaCalendarioUe/SalvarPendenciaCalendarioUe/SalvarPendenciaCalendarioUeCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaCalendarioUe/VerificaPendenciaCalendarioUe/VerificaPendenciaCalendarioUeCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivosCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaParametroEvento/VerificaPendenciaParametroEvento/VerificaPendenciaParametroEventoCommandHandler.cs
[AB#28645](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/28645)
=> 28645 - Incluso tratamento de exceção na geração de pendencias 

src/SME.SGP.Aplicacao/Commands/PendenciaCalendarioUe/SalvarPendenciaCalendarioUe/SalvarPendenciaCalendarioUeCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivosCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaUsuario/RelacionaPendenciaUsuario/RelacionaPendenciaUsuarioCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciaUsuario/RelacionaPendenciaUsuario/RelacionaPendenciaUsuarioCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioUsuario.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#28645](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/28645)
=> 28645 - Corrigido problema no vinculo de usuarios com as pendencias

src/SME.SGP.WebClient/src/paginas/Relatorios/Notificacoes/HistoricoNotificacoes/historicoNotificacoes.js
[AB#28881](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28881)
=> RELEASE - Relatório de notificações - ao trocar algum valor o botao gerar nao fica habilitado

src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioFaltasFrequenciaDto.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/Frequencia/faltasFrequencia.js
Manutenção no filtro de condições do relatório
=> inclusão de parametro no dto e ajuste no front

src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasTurma.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Infra/Dtos/AlunoDadosBasicosDto.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs, src/SME.SGP.Infra/Dtos/RegistroFrequenciaAlunoDto.cs
[AB#28520](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/28520)
=> inclusão de campos contato com o responsável

src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
=> Ajustes merge

src/SME.SGP.Api/Controllers/AbrangenciaController.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/BoletimSimples/componentes/Filtro/componentes/TurmasDropDown.js, src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/BoletimSimples/componentes/Filtro/index.js, src/SME.SGP.WebClient/src/servicos/Abrangencia/index.js
Ajustes de front e back-end na funcionalidade de gerar boletim alterando pontos específicos considerando anos históricos.
=> Bug: 28438

src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
[AB#29245](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29245)
=> 29245 - Ajustes no layout

src/SME.SGP.WebClient/src/paginas/Relatorios/Gestao/Usuarios/relatorioUsuarios.js
[AB#29393](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/29393)
=> 29393 - Correção da listagem de usuarios da UE

src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs
[AB#28123](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/28123)
=> Ajuste metodo assincrono

src/SME.SGP.Dados/Repositorios/RepositorioAula.cs
[AB#25034](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/25034)
=> Ajuste comparação disciplina aula atividade avaliativa

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
[AB#29510](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29510)
=> Ajuste inserção auditoria release

src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasTurma.cs, src/SME.SGP.Dominio/Enumerados/TipoResponsavel.cs, src/SME.SGP.Infra/Dtos/AlunoDadosBasicosDto.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs, src/SME.SGP.Infra/Dtos/RegistroFrequenciaAlunoDto.cs
[AB#28520](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/28520)
=> Inclusão da descrição do Tipo de Responsável

scripts/V306__AJUSTE_FUNCOES_ABRANGENCIA_USUARIO_TIPO_SUPERVISOR.sql
Script de ajustes de funções de abrangência, removendo o tratamento específico para usuário do tipo supervisor.
=> Bug: 29514

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
Ajuste no erro ao selecionar aba final de fechamento, tratando registros de fechamento turma disciplina não encontrados.
=> Bug: 29763

src/SME.SGP.WebClient/src/paginas/Principal/Pendencias/pendenciasGerais.js
[AB#29780](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29780)
=> 29780 - Corrigido tamanho do título

src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioIdPorRfOuCria/ObterUsuarioIdPorRfOuCriaQueryHandler.cs
[AB#29783](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29783)
=> 29783 - Correção do modo como busca o usuário

src/SME.SGP.Worker.Rabbbit/Startup.cs
[AB#29811](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29811)
=> 29811 - Correção da startup (duplicação de parametros)

src/SME.SGP.Aplicacao/Commands/Notificacao/ExecutaNotificacaoPeriodoFechamentoIniciando/ExecutaNotificacaoPeriodoFechamentoIniciandoCommandHandler.cs
[AB#29811](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29811)
=> 29811 - Correção da duplicidcade de notificação

src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioFaltasFrequenciaDto.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/Frequencia/faltasFrequencia.js
[AB#29623](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29623)
=> Ajuste no front correção da informação todos estudantes

src/SME.SGP.WebClient/src/paginas/Relatorios/Fechamento/HistoricoAlteracoesNotas/relatorioHistoricoAlteracoesNotas.js
[AB#29809](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29809)
Alterado consulta de DRE , UE, e turma para considerar histórico de anos anteriores
=> Relatorio Alteração de notas - 

src/SME.SGP.Aplicacao/Commands/Notificacao/ExecutaNotificacaoUeFechamentoInsuficientes/ExecutaNotificacaoUeFechamentoInsuficientesCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Supervisores/ObterSupervisoresPorDre/ObterSupervisoresPorDreQuery.cs, src/SME.SGP.Aplicacao/Queries/Supervisores/ObterSupervisoresPorDre/ObterSupervisoresPorDreQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Supervisores/ObterSupervisoresPorUe/ObterSupervisoresPorUeQuery.cs, src/SME.SGP.Aplicacao/Queries/Supervisores/ObterSupervisoresPorUe/ObterSupervisoresPorUeQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSupervisorEscolaDre.cs
[AB#29808](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29808)
=> 29808 - Criada as queries para DRE e UE

src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs
[AB#29486](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/29486)
=> ajuste na consulta

src/SME.SGP.Aplicacao/Commands/Notificacao/ExecutaNotificacaoUeFechamentoInsuficientes/ExecutaNotificacaoUeFechamentoInsuficientesCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Notificacao/NotificarResultadoInsatisfatorio/NotificarResultadoInsatisfatorioCommandHandler.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
[AB#29839](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29839)
=> 29839 - Adicionado o Workflow para CP AD e Diretor

src/SME.SGP.Aplicacao/Commands/Notificacao/ExecutaNotificacaoPeriodoFechamentoEncerrando/ExecutaNotificacaoPeriodoFechamentoEncerrandoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Notificacao/ExecutaNotificacaoPeriodoFechamentoIniciando/ExecutaNotificacaoPeriodoFechamentoIniciandoCommandHandler.cs
[AB#29811](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29811)
=> 29811 - Correção para workflow

src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
[AB#29809](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29809)
=> Retirada de transação do salvar historico nota fechamento

src/SME.SGP.Api/Controllers/RelatorioController.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
[AB#29809](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/29809)
=> Inclusão de bloqueio no controler para turma infantil e ajuste no texto Alterações de notas

src/SME.SGP.Dados/Repositorios/RepositorioPlanejamentoAnualPeriodoEscolar.cs
Ajustre no erro que ocorre ao expandir o 1º bimestre no plano anual.
=> Bug: 30005

src/SME.SGP.WebClient/src/paginas/Relatorios/Fechamento/HistoricoAlteracoesNotas/relatorioHistoricoAlteracoesNotas.js
[AB#3001](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/30001)
=> 30001 - Ajuste ordenação do combo bimestres

src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs
[AB#29999](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/29999)
=> 29999 - Ajuste consulta de turmas sem avaliação no periodo

src/SME.SGP.Aplicacao/Commands/Notificacao/NotificarResultadoInsatisfatorio/NotificarResultadoInsatisfatorioCommandHandler.cs
[AB#30106](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/30106)
=> 30106 - Alterado tipo da notificação de resultado insatisfatorio

src/SME.SGP.Api/Controllers/DashboardEscolaAquiController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorModalidadeETurma/ObterDadosDeLeituraDeComunicadosPorModalidadeETurmaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorModalidade/IObterDadosDeLeituraDeComunicadosPorModalidadeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorModalidadeETurma/IObterDadosDeLeituraDeComunicadosPorModalidadeETurmaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorTurma/ObterDadosDeLeituraDeComunicadosPorModalidadePorTurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorTurma/ObterDadosDeLeituraDeComunicadosPorModalidadePorTurmaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorTurma/ObterDadosDeLeituraDeComunicadosPorModalidadePorTurmaQueryValidator.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/DadosDeLeituraDeComunicados/FiltroDadosDeLeituraDeComunicadosPorModalidadeDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#28549](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/28549)
=> Implementação de endpoint dados de comunicados por turma (parcial)

src/SME.SGP.Aplicacao/CasosDeUso/PendenciaAusenciaFechamento/ExecutarExclusaoPendenciasAusenciaFechamentoUseCase.cs, src/SME.SGP.Aplicacao/Commands/PendenciaAusenciaFechamento/PublicaFilaExcluirPendenciaAusenciaFechamento/PublicaFilaExcluirPendenciaAusenciaFechamentoCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciaAusenciaFechamento/PublicaFilaExcluirPendenciaAusenciaFechamento/PublicaFilaExcluirPendenciaAusenciaFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaAusenciaFechamento/VerificaExclusaoPendenciasAusenciaFechamento/VerificaExclusaoPendenciasAusenciaFechamentoCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciaAusenciaFechamento/VerificaExclusaoPendenciasAusenciaFechamento/VerificaExclusaoPendenciasAusenciaFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaProfessor/VerificaExclusaoPendenciasAusenciaAvaliacao/VerificaExclusaoPendenciasAusenciaAvaliacaoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasProfessorPorTurmaEComponente/ObterPendenciasProfessorPorTurmaEComponenteQuery.cs, src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasProfessorPorTurmaEComponente/ObterPendenciasProfessorPorTurmaEComponenteQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarIdPorTurmaId/ObterPeriodoEscolarIdPorTurmaIdQuery.cs, src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarIdPorTurmaId/ObterPeriodoEscolarIdPorTurmaIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaProfessor.cs, src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolar.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaProfessor.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoEscolar.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
[AB#30095](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/30095)
=> 30095 - Exclusão de Pendencia de Fechamento ao cadastra fechamento final

src/SME.SGP.WebClient/src/paginas/Relatorios/Atas/AtaFinalResultados/ataFinalResultados.js
Ajuste na label da flag de considera histórico no relatório de ata.
=> Bug: 30004

src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioAtribuicaoCJDto.cs
[AB#30367](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30367)
=> Ajuste modalidade opcional

src/SME.SGP.Aplicacao/Commands/PendenciaProfessor/ExecutarVerificacaoPendenciaAvaliacaoProfessor/ExecutarVerificacaoPendenciaAvaliacaoProfessorCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterQuantidadeAvaliacoesTurmaComponentePorUeNoPeriodo/ObterQuantidadeAvaliacoesTurmaComponentePorUeNoPeriodoQuery.cs, src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterQuantidadeAvaliacoesTurmaComponentePorUeNoPeriodo/ObterQuantidadeAvaliacoesTurmaComponentePorUeNoPeriodoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasPorUeModalidadeAno/ObterTurmasPorUeModalidadesAnoQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasPorUeModalidadeAno/ObterTurmasPorUeModalidadesAnoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs, src/SME.SGP.Dados/Repositorios/RepositorioPeriodoFechamento.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtividadeAvaliativa.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurma.cs, src/SME.SGP.Infra/Dtos/AtividadeAvaliativa/AvaliacoesPorTurmaComponenteDto.cs
[AB#30304](https://dev.azure.com/amcomgov/Novo%20SGP/_workitems/edit/30304)
=> 30304 - Alterado Geração de pendencia de ausencia de avaliação 

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/AtribuicaoCJ/RelatorioAtribuicaoCJUseCase.cs
[AB#30365](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30365)
=> Ajuste filtro todas ues e dres

src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorModalidade/ObterDadosDeLeituraDeComunicadosPorModalidadeQueryQueryValidator.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorTurma/ObterDadosDeLeituraDeComunicadosPorModalidadePorTurmaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorTurma/ObterDadosDeLeituraDeComunicadosPorModalidadePorTurmaQueryValidator.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/DadosDeLeituraDeComunicados/FiltroDadosDeLeituraDeComunicadosPorModalidadeDto.cs
[AB#28549](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/28549)
=> Ajustes na chamada de endpoint e campos obrigatórios

src/SME.SGP.WebClient/src/componentes/Localizador/services/LocalizadorService.js
[AB#30400](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30400)
=> 30400 - Ajuste busca de professores por nome

src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs, src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#30307](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30307)
=> Padronização das notificações do relatório

src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolar.cs, src/SME.SGP.Infra/Dtos/PlanoAulaDto.cs, src/SME.SGP.WebClient/src/paginas/DiarioClasse/FrequenciaPlanoAula/servicoSalvarFrequenciaPlanoAula.js
Ajuste na validação para salvar o plano de aula ao selecionar turmas de anos anteriores.
=> Bug: 30266

src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
[AB#30307](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30307)
=> Ajuste no texto da notificação do relatório

src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/ComunicadosFiltro/ComunicadoParaFiltroDaDashboardDto.cs
[AB#30473](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/30473)
=> Inclusão de novos campos e correção de filtro por GruposIds

src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorModalidadeETurma/ObterDadosDeLeituraDeComunicadosPorModalidadeETurmaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorTurma/ObterDadosDeLeituraDeComunicadosPorModalidadePorTurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorTurma/ObterDadosDeLeituraDeComunicadosPorModalidadePorTurmaQueryHandler.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/DadosDeLeituraDeComunicados/DadosDeLeituraDoComunicadoPorModalidadeETurmaDto.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/DadosDeLeituraDeComunicados/FiltroDadosDeLeituraDeComunicadosPorModalidadeDto.cs
[AB#30522](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/30522)
=> Ajuste para retornar a modalidade e filtros

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#30508](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30508)
=> Adicionado turma código no tratamento de regencia

src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoConceito/SalvarHistoricoConceitoCommand.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoConceito/SalvarHistoricoConceitoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoConceitoFechamento/SalvarHistoricoConceitoFechamentoCommand.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoConceitoFechamento/SalvarHistoricoConceitoFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoNota/SalvarHistoricoNotaCommand.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoNota/SalvarHistoricoNotaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoNotaFechamento/SalvarHistoricoNotaFechamentoCommand.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoNotaFechamento/SalvarHistoricoNotaFechamentoCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioBase.cs, src/SME.SGP.Dados/Repositorios/RepositorioHistoricoNota.cs, src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
[AB#30384](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30384)
=> 30384 - Correção do usuario de criação da alteração de nota 

src/SME.SGP.Aplicacao/Queries/EscolaAqui/ObterComunicadosParaFiltro/ObterComunicadosParaFiltroDaDashboardQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioComunicado.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/ComunicadosFiltro/ComunicadoParaFiltroDaDashboardDto.cs
[AB#30579](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/30579)
=> inclusão de turmas no retorno do endpoint

src/SME.SGP.Aplicacao/Commands/PendenciaAusenciaFechamento/PublicaFilaExcluirPendenciaAusenciaFechamento/PublicaFilaExcluirPendenciaAusenciaFechamentoCommand.cs
[AB#30095](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30095)
=> 30095 - Exclusão de pendencias de fechamento em periodo final

scripts manutencao/Bug 30448/ScriptInclusaoUsuario_8414611.sql
Script de inclusão de usuário do banco sgp_sondagem.
=> Bug: 30448

src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs
[AB#30523](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/30523)
=> Ajuste na query, ao passar Dre e UE, tras os comunicados tipo 1 e com dre e UE null na base

scripts/V309__WF_APROVACAO_NOTA_FECHAMENTO.sql, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoConceitoFechamento/SalvarHistoricoConceitoFechamentoCommand.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoConceitoFechamento/SalvarHistoricoConceitoFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoNotaFechamento/SalvarHistoricoNotaFechamentoCommand.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoNotaFechamento/SalvarHistoricoNotaFechamentoCommandHandler.cs, src/SME.SGP.Dados/Mapeamentos/HistoricoNotaFechamentoMap.cs, src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs, src/SME.SGP.Dominio/Entidades/HistoricoNotaFechamento.cs
[AB#30384](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30384)
=> 30384 - Ajuste processo de aprovação de WF alteração de nota

src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs, teste/SME.SGP.Aplicacao.Teste/Queries/ObterDatasAulasPorProfessorEComponenteQueryHandlerTeste.cs
Removendo serviço não utilizado no handler;
Adicionando mocks no teste;
=> r2-build-quebrado

src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoFinal.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaProfessor.cs
[AB#30095](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30095)
=> 30095 - Exclusão de pendencia de fechamento final;

src/SME.SGP.Aplicacao/Commands/Notificacao/NotificaFrequenciaPeriodoUe/NotificaFrequenciaPeriodoUeCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUe/ObterComponentesCurricularesPorUeQuery.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUe/ObterComponentesCurricularesPorUeQueryHandler.cs, src/SME.SGP.Worker.Rabbbit/Startup.cs
[AB#30863](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30863)
=> 30863 - Mensagem com os componentes que a UE possue apenas

src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorModalidadeETurma/ObterDadosDeLeituraDeComunicadosPorModalidadeETurmaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorTurma/ObterDadosDeLeituraDeComunicadosPorModalidadePorTurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorTurma/ObterDadosDeLeituraDeComunicadosPorModalidadePorTurmaQueryHandler.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/DadosDeLeituraDeComunicados/FiltroDadosDeLeituraDeComunicadosPorModalidadeDto.cs
[AB#30739](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/30739)
=> possibilidade de filtrar por mais de uma turma

src/SME.SGP.WebClient/src/paginas/Relatorios/Fechamento/HistoricoAlteracoesNotas/relatorioHistoricoAlteracoesNotas.js
[AB#30894](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30894)
=> Ajuste no front para passar o parâmetro considerar histórico dinamicamente

src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs
[AB#30957](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30957)
=> Ajuste na consulta de comunicados por data

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseRecomendacao/ObterTextoRecomendacoesAlunoFamilia/ObterTextoRecomendacoesAlunoFamiliaQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseRecomendacao/ObterTextoRecomendacoesAlunoFamilia/ObterTextoRecomendacoesAlunoFamiliaQueryHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs
[AB#30314](https://dev.azure.com/amcomgov/aa9c3851-9a64-41b8-8c40-5256b78ccec9/_workitems/edit/30314)
=> 30314 - Criado inclusão de recomendações padrão

src/SME.SGP.WebClient/src/paginas/Relatorios/EscolaAqui/Leitura/relatorioLeitura.js
[AB#30972](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30972)
=> relatorio leitura - ajustes nas validacoes

ETL/21_Fechamento2020_ConselhoClasse/20201217_01_limpa_dados_2020.sql, ETL/21_Fechamento2020_ConselhoClasse/20201217_02_insere_dados_2020.sql
[AB#31037](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31037)
=> 31037 - Criado scripts para execução

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/DiarioClasse/FrequenciaPlanoAula/DadosFrequenciaPlanoAula/PlanoAula/DadosPlanoAula/SwitchInformarObjetivos/switchInformarObjetivos.js
[AB#31191](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31191) [AB#30799](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30799)
=> 31191 - Ajuste salvar ao alterar switch

src/Bibliotecas/SME.Background.Hangfire/Worker.cs, src/Bibliotecas/SME.SGP.Background/ContextFilterAttribute.cs, src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs, src/SME.SGP.Api/Dockerfile, src/SME.SGP.Aplicacao/CasosDeUso/RemoveConexaoIdleUseCase/RemoveConexaoIdleUseCase.cs, src/SME.SGP.Aplicacao/Commands/RemoveConexaoIdle/RemoveConexaoIdleCommand.cs, src/SME.SGP.Aplicacao/Commands/RemoveConexaoIdle/RemoveConexaoIdleCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/RemoveConexaoIdleUseCase/IRemoveConexaoIdleUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoCompensacaoAusencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroAusenciaAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioRemoveConexaoIdle.cs, src/SME.SGP.Dados/SME.SGP.Dados.csproj, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRemoveConexaoIdle.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs, src/SME.SGP.WorkerService/SME.SGP.Worker.Service.csproj
Adicionando serviço de meia em meia hora para limpar os idle;
Removendo try catch para tratar repositório;
=> Removendo redis do dockerfile;

src/SME.SGP.Api/Controllers/DashboardEscolaAquiController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurma/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurmaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosAlunosDaTurma/IObterDadosDeLeituraDeComunicadosPorAlunosDaTurmaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorModalidadeETurma/IObterDadosDeLeituraDeComunicadosPorModalidadeETurmaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurma/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurma/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurmaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurma/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurmaQueryValidator.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/DadosDeLeituraDeComunicados/DadosLeituraAlunosComunicadoPorTurmaDto.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/DadosDeLeituraDeComunicados/FiltroDadosDeLeituraDeComunicadosPorModalidadeDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#31092](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31092)
=> Implementação de enpoint de dados de leitura para alunos de uma turma

src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurma/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurmaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorModalidadeETurma/ObterDadosDeLeituraDeComunicadosPorModalidadeETurmaUseCase.cs, src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterUltimoPeriodoEscolarPorData/ObterUltimoPeriodoEscolarPorDataQuery.cs, src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterUltimoPeriodoEscolarPorData/ObterUltimoPeriodoEscolarPorDataQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterUltimoPeriodoEscolarPorData/ObterUltimoPeriodoEscolarPorDataQueryValidator.cs, src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolar.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoEscolar.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/DadosDeLeituraDeComunicados/DadosDeLeituraDoComunicadoPorModalidadeETurmaDto.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/DadosDeLeituraDeComunicados/DadosLeituraAlunosComunicadoPorTurmaDto.cs
[AB#31398](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31398)
=> ajustes no endpoint para retornar o marcador de situação do aluno

src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicados/ObterDadosDeLeituraDeComunicadosQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosAgrupadosPorDre/ObterDadosDeLeituraDeComunicadosAgrupadosPorDreQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorModalidade/ObterDadosDeLeituraDeComunicadosPorModalidadeQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorTurma/ObterDadosDeLeituraDeComunicadosPorModalidadePorTurmaQueryHandler.cs
[AB#31413](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31413)
=> Ajuste na mensagem de erro

src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurma/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurmaUseCase.cs
[AB#31398](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31398)
=> Inclusão de ordenação pelo Nome Aluno

src/SME.SGP.Aplicacao/Commands/Notificacao/NotificarPeriodoFechamentoUe/NotificarPeriodoFechamentoUeCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPeriodoFechamentoBimestre.cs
[AB#30409](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30409)
=> 30409 - Tratamento de exceção na geração de pendencia de dias letivos

src/SME.SGP.Api/Controllers/ArmazenamentoController.cs, src/SME.SGP.Api/Controllers/UploadController.cs
[AB#31442](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31442)
=> 31442 - Corrigido retorno do upload com a rota dos arquivos

src/SME.SGP.WebClient/src/componentes/jodit-editor/joditEditor.js
[AB#31488](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31488)
=> jodit editor remove fullSize

src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorModalidadeETurma/ObterDadosDeLeituraDeComunicadosPorModalidadeETurmaUseCase.cs
[AB#31500](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31500)
=> Ajuste na ordenação por turma

src/SME.SGP.Api/Controllers/OcorrenciaController.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Detalhes/OcorrenciaAlunoDto.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Detalhes/OcorrenciaDto.cs
[AB#31455](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31455)
=> CM - Adição do endpoint de consulta detalhes da ocorrência (mock)

src/SME.SGP.Api/Controllers/OcorrenciaController.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Persistencias/InserirOcorrenciaDto.cs
[AB#31457](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31457)
=> CM - Adição do endpoint de inserir uma nova ocorrência.

src/SME.SGP.Api/Controllers/OcorrenciaController.cs, src/SME.SGP.Infra/Dtos/Ocorrencias/Alteracoes/AlterarOcorrenciaDto.cs
[AB#26801](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26801)
=> CM - Adição do endpoint de alteração da ocorrência

teste/SME.SGP.Dominio.Teste/AtribuicaoEsporadicaTeste.cs
=> Bug: 16440

src/SME.SGP.WebClient/src/componentes/jodit-editor/joditEditor.js
[AB#31607](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31607)
=> 31607 - Removido o botão que adiciona vídeo do youtube via link

src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/PlanejamentoDiario/relatorioPlanejamentoDiario.js
[AB#31697](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31697)
=> 31697 - Corrigido pesquisa de bimestre do combo

src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/PlanejamentoDiario/relatorioPlanejamentoDiario.js
[AB#31697](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31697)
=> 31697 - corrigido carga do atributo listarDataFutura

src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/PlanejamentoDiario/relatorioPlanejamentoDiario.js
[AB#31697](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31697)
=> 31697 - Corrigido default false ListarDataFutura ao desabilitar o radio

src/SME.SGP.Aplicacao/Commands/Notificacao/NotificarPeriodoFechamentoUe/NotificarPeriodoFechamentoUeCommandHandler.cs
[AB#30409](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/30409)
=> 30409 - Incluso ano do tipo de calendario na notificação

src/SME.SGP.Api/Controllers/UploadController.cs
[AB#31740](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31740)
=> 31740 - Adicionado valor fixo para https

src/SME.SGP.Api/Controllers/OcorrenciaController.cs, src/SME.SGP.Aplicacao/Queries/Ocorrencia/ListarOcorrencias/ListarOcorrenciasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Ocorrencia/ObterOcorrenciaPorId/ObterOcorrenciaPorIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioOcorrencia.cs
[AB#31798](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31798)
=> CM - Ajustes nos filtros e queries levantados no repasse para QA

src/SME.SGP.WebClient/src/paginas/Gestao/Ocorrencia/CadastroOcorrencias.js, src/SME.SGP.WebClient/src/paginas/Gestao/Ocorrencia/ListaOcorrencias.js
[AB#31889](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31889)
=> 31889 - Aplicando permissionamento

src/SME.SGP.Api/Controllers/EncaminhamentoAEEController.cs, src/SME.SGP.Dominio/Enumerados/SituacaoAEE.cs
[AB#32004](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32004)
=> feature/32004 - Criado endpoint para listagem de situacoes

src/SME.SGP.Api/Controllers/EncaminhamentoAeeController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterSecoesPorEtapaDeEncaminhamentoAEEUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoAee/IObterSecoesPorEtapaDeEncaminhamentoAEEUseCase.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterSecoesPorEtapaDeEncaminhamento/ObterSecoesPorEtapaDeEncaminhamentoQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterSecoesPorEtapaDeEncaminhamento/ObterSecoesPorEtapaDeEncaminhamentoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterSecoesPorEtapaDeEncaminhamento/ObterSecoesPorEtapaDeEncaminhamentoQueryValidator.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEESecao.cs, src/SME.SGP.Dados/Repositorios/RepositorioSecaoEncaminhamentoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSecaoEncaminhamentoAEE.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoAee/SecaoQuestionarioDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#31593](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31593)
=> Endpoint para Obter Seções de Encaminhamento por Etapa

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Gestao/Ocorrencia/CadastroOcorrencias.js
[AB#31939](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31939)
[AB#32017](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32017)
=> 31939 - Ajuste validação alunos

ETL/Historias/31921/Criação de indices relacionados a consulta de frequencia.sql
[AB#31921](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31921)
=> 31921 - Criação de indices relacionados ao calculo de frequencia

src/SME.SGP.Api/Controllers/EncaminhamentoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ExcluirEncaminhamentoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/ExcluirArquivoPorId/ExcluirArquivoPorIdCommand.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/ExcluirArquivoPorId/ExcluirArquivoPorIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/ExcluirEncaminhamentoAEE/ExcluirEncaminhamentoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/ExcluirEncaminhamentoAEE/ExcluirEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/ExcluirQuestaoEncaminhamentoAEEPorSecaoId/ExcluirQuestaoEncaminhamentoAEEPorSecaoIdCommand.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/ExcluirQuestaoEncaminhamentoAEEPorSecaoId/ExcluirQuestaoEncaminhamentoAEEPorSecaoIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/ExcluirRespostaEncaminhamentoAEEPorQuestaoId/ExcluirRespostaEncaminhamentoAEEPorQuestaoIdCommand.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/ExcluirRespostaEncaminhamentoAEEPorQuestaoId/ExcluirRespostaEncaminhamentoAEEPorQuestaoIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/ExcluirSecoesEncaminhamentoAEEPorEncaminhamentoId/ExcluirSecoesEncaminhamentoAEEPorEncaminhamentoIdCommand.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/ExcluirSecoesEncaminhamentoAEEPorEncaminhamentoId/ExcluirSecoesEncaminhamentoAEEPorEncaminhamentoIdCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoAEE/IExcluirEncaminhamentoAEEUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEESecao.cs, src/SME.SGP.Dados/Repositorios/RepositorioQuestaoEncaminhamentoAEE.cs, src/SME.SGP.Dados/Repositorios/RepositorioRespostaEncaminhamentoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoAEESecao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioQuestaoEncaminhamentoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRespostaEncaminhamentoAEE.cs, src/SME.SGP.Dominio/Enumerados/SituacaoAEE.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoAee/EncaminhamentoAEEDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#31596](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31596)
=> 31596 - Exclusão de Encaminhamento AEE

src/SME.SGP.WebClient/src/paginas/Gestao/Ocorrencia/ListaOcorrencias.js
[AB#31946](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31946)
[AB#32124](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32124)
=> 31946 - Ajuste ação botão voltar

src/SME.SGP.WebClient/src/componentes/TabelaRetratil/index.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/componentes/TabelaRetratilRegistroIndividual/tabelaRetratilRegistroIndividual.js
[AB#31966](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31966) [AB#32127](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32127)
=> 31966 - Ajuste titulo estudantes

src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/componentes/DadosRegistroIndividual/novoRegistroIndividual/novoRegistroIndividual.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/componentes/DadosRegistroIndividual/registrosAnteriores/registrosAnteriores.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/componentes/DadosRegistroIndividual/registrosAnteriores/registrosAnterioresConteudo/item/item.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/componentes/DadosRegistroIndividual/registrosAnteriores/registrosAnterioresConteudo/registrosAnterioresConteudo.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/registroIndividual.js, src/SME.SGP.WebClient/src/redux/modulos/registroIndividual/actions.js, src/SME.SGP.WebClient/src/redux/modulos/registroIndividual/reducers.js, src/SME.SGP.WebClient/src/servicos/Paginas/DiarioClasse/ServicoRegistroIndividual.js
Adicionando paginação em registros anteriores [AB#32169](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32169) [AB#32213](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32213)
=> fix/32169 

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Gestao/Ocorrencia/CadastroOcorrencias.js
[AB#32141](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32141) [AB#31939](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31939)
=> 32141 - Ajustes validação ocorrências

src/SME.SGP.WebClient/src/componentes-sgp/Paginacao/paginacao.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/componentes/DadosRegistroIndividual/novoRegistroIndividual/novoRegistroIndividual.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/componentes/DadosRegistroIndividual/registrosAnteriores/registrosAnterioresConteudo/item/item.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/componentes/DadosRegistroIndividual/registrosAnteriores/registrosAnterioresConteudo/registrosAnterioresConteudo.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/metodosRegistroIndividual.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/registroIndividual.js, src/SME.SGP.WebClient/src/redux/modulos/registroIndividual/actions.js, src/SME.SGP.WebClient/src/redux/modulos/registroIndividual/reducers.js
Corrigindo erro de filtros de data em registros anteriores e erros diversos [AB#31967](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31967) [AB#32101](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32101)
=> fix/31967 

src/SME.SGP.WebClient/src/paginas/Relatorios/DashboardEscolaAqui/TabsDashboardEscolaAqui/DadosComunicadosLeitura/dadosComunicadosLeitura.js, src/SME.SGP.WebClient/src/paginas/Relatorios/EscolaAqui/Leitura/relatorioLeitura.js
[AB#32237](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32237)
=> Corrigido desabilitar das datas no calendário

src/SME.SGP.WebClient/src/paginas/Relatorios/DashboardEscolaAqui/TabsDashboardEscolaAqui/DadosComunicadosLeitura/dadosComunicadosLeitura.js
[AB#32312](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32312)
=> Corrigido atualização de grupo e modalidades no dashboard dados leitura

src/SME.SGP.WebClient/src/componentes/TabelaRetratil/index.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/componentes/TabelaRetratilRegistroIndividual/tabelaRetratilRegistroIndividual.js
[AB#32279](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32279) [AB#32295](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32295)
=> 32279 - pular alunos desabilitados ao clicar em próximo/anterior

src/SME.SGP.WebClient/src/paginas/Relatorios/DashboardEscolaAqui/TabsDashboardEscolaAqui/DadosComunicadosLeitura/dadosComunicadosLeitura.js
[AB#32352](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32352)
=> limpar o comunicado que estava sendo visualizado anteriormente no grafico

src/SME.SGP.Api/Controllers/DiarioBordoController.cs, src/SME.SGP.Infra/Dtos/DiarioBordo/Notificacao/ObterUsuarioNotificarDiarioBordoObservacaoDto.cs, src/SME.SGP.Infra/Dtos/DiarioBordo/Notificacao/UsuarioNotificarDiarioBordoObservacaoDto.cs
[AB#32146](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32146)
=> CM - Mock do endpoit de busca de usuários para serem notificados.

src/SME.SGP.WebClient/src/paginas/DiarioClasse/Devolutivas/DadosPlanejamentoDiarioBordo/CardPlanejamento/cardPlanejamento.js
[AB#32174](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32174)
=>  32174 - Implementar combobox

src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/RegistrarEncaminhamentoAEESecaoQuestaoResposta/RegistrarEncaminhamentoAEESecaoQuestaoRespostaCommand.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/Encaminhamento/Cadastro/Componentes/IndicativosEstudante/indicativosEstudante.css.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/Encaminhamento/Cadastro/Componentes/IndicativosEstudante/indicativosEstudante.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/Encaminhamento/Cadastro/Componentes/SecaoEncaminhamento/DadosSecaoEncaminhamento/dadosSecaoEncaminhamento.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/Encaminhamento/Cadastro/Componentes/SecaoEncaminhamento/DadosSecaoEncaminhamento/montarDadosPorSecao.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/Encaminhamento/Cadastro/Componentes/botoesAcoesEncaminhamentoAEE.js, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/AEE/ServicoEncaminhamentoAEE.js
=> [SGP AEE] Encaminhamento - consulta encaminhamento por id, add campo InformacoesEscolares

src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#32300](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32300)
=> Ajuste permissão ocorrência

src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/componentes/DadosRegistroIndividual/novoRegistroIndividual/novoRegistroIndividual.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/componentes/DadosRegistroIndividual/registrosAnteriores/registrosAnteriores.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/componentes/DadosRegistroIndividual/registrosAnteriores/registrosAnterioresConteudo/item/item.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/metodosRegistroIndividual.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/RegistroIndividual/registroIndividual.js, src/SME.SGP.WebClient/src/redux/modulos/registroIndividual/reducers.js
Corrigindo erro de registros anteriores [AB#32365](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32365) [AB#32377](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32377)
=> Fix/32365 

src/SME.SGP.WebClient/src/paginas/Relatorios/DashboardEscolaAqui/TabsDashboardEscolaAqui/DadosComunicadosLeitura/leituraDeComunicadosAgrupadosPorDre.js, src/SME.SGP.WebClient/src/paginas/Relatorios/DashboardEscolaAqui/TabsDashboardEscolaAqui/DadosComunicadosLeitura/leituraDeComunicadosPorModalidades.js, src/SME.SGP.WebClient/src/paginas/Relatorios/DashboardEscolaAqui/TabsDashboardEscolaAqui/DadosComunicadosLeitura/leituraDeComunicadosPorModalidadesETurmas.js, src/SME.SGP.WebClient/src/paginas/Relatorios/DashboardEscolaAqui/TabsDashboardEscolaAqui/DadosComunicadosLeitura/leituraDeComunicadosPorTurmas.js
[AB#32418](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32418)
=> [Dashboard - Comunicados leitura] - Visualização por estudantes não apresenta os demais gráficos

src/SME.SGP.Api/Controllers/AcompanhamentoFrequenciaController.cs, src/SME.SGP.Infra/Dtos/AcompanhamentoFrequencia/AlunoFrequenciaDto.cs, src/SME.SGP.Infra/Dtos/AcompanhamentoFrequencia/FrequenciaAlunosPorBimestreDto.cs, src/SME.SGP.Infra/Dtos/AcompanhamentoFrequencia/ObterFrequenciaAlunosPorBimestreDto.cs
[AB#32184](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32184)
=> CM -Endpoint obter frequencia dos alunos por bimestre (Mock)

src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/Atas/AtaFinalResultados/ataFinalResultados.js
Ajuste na nomenclatura do título e do nome do arquivo do relatório de conselho de classe para turma e aluno.
Ajuste de nomenclatura do relatório de ata final para título, nome do arquivo, título da notificação e decrição na tela de filtro.
=> Bug: 32354

src/SME.SGP.WebClient/src/componentes-sgp/LegendaGrafico/legendaGrafico.css.js, src/SME.SGP.WebClient/src/componentes-sgp/LegendaGrafico/legendaGrafico.js, src/SME.SGP.WebClient/src/componentes/Graficos/componentes/Pie.js, src/SME.SGP.WebClient/src/paginas/Relatorios/DashboardEscolaAqui/TabsDashboardEscolaAqui/ComponentesDashboardEscolaAqui/graficoPizzaDashboardEscolaAqui.js, src/SME.SGP.WebClient/src/paginas/Relatorios/DashboardEscolaAqui/TabsDashboardEscolaAqui/DadosComunicadosLeitura/dadosComunicadosLeitura.js
[AB#32480](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32480)
=> Dashboard Leitura gráficos de pizza - valore e porcentagem exibir junto com a legenda

src/SME.SGP.WebClient/src/paginas/DiarioClasse/DiarioBordo/novoDiarioBordo.js
[AB#32150](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32150)
=> 32150 - Persistência observações

src/SME.SGP.Api/Controllers/AcompanhamentoFrequenciaController.cs, src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#32195](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32195)
=> CM - Permissionamento

src/SME.SGP.WebClient/src/componentes/PainelCollapse/styles.js
[AB#32881](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32881) [AB#32884](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32884)
=> 32881 - Ajuste tamanho panel para não cortar conteúdo

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/Encaminhamento/Cadastro/Componentes/botoesAcoesEncaminhamentoAEE.js, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/AEE/ServicoEncaminhamentoAEE.js
[AB#33125](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33125) - Adicionada validação nos botões antes de alterar
=> feature/33125 

src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicados/ObterDadosDeLeituraDeComunicadosUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicados/ObterDadosDeLeituraDeComunicadosQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicados/ObterDadosDeLeituraDeComunicadosQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/ComunicadosFiltro/ComunicadoParaFiltroDaDashboardDto.cs, src/SME.SGP.Infra/Dtos/EscolaAqui/DadosDeLeituraDeComunicados/ObterDadosDeLeituraDeComunicadosDto.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/DashboardEscolaAqui/TabsDashboardEscolaAqui/DadosComunicadosLeitura/dadosComunicadosLeitura.js, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/EscolaAqui/DashboardEscolaAqui/ServicoDashboardEscolaAqui.js
[AB#32450](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32450)
Ajustes na chamada do endpoint de dadosdeleitura, no endpoint dados leitura e inclusão de parâmetro agruparModalidade no endpoint de filtro de comunicados
=> Ajustes na chamada do endpoint de dadosdeleitura

src/SME.SGP.Api/Controllers/EncaminhamentoAEEController.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoAEE/EncarramentoEncaminhamentoDto.cs, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/AEE/ServicoEncaminhamentoAEE.js
[AB#33138](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33138)
=> 33138 Corrigido passagem de parametro motivo para aceitar um texto maior

src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/ObterAnotacaoFrequenciaAlunoPorIdUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterJustificativasAlunoPorComponenteCurricularUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioAnotacaoFrequenciaAluno.cs, src/SME.SGP.Infra/Utilitarios/UtilRegex.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/DiarioClasse/AcompanhamentoFrequencia/Componentes/ListaAlunos/ausenciasAluno.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/AcompanhamentoFrequencia/Componentes/ListaAlunos/modalAnotacoesAcompanhamentoFrequencia.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/AcompanhamentoFrequencia/acompanhamentoFrequencia.js
[AB#33131](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33131)
=> 33131 - Ajustes backend

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCase.cs, src/SME.SGP.Aplicacao/Queries/Professores/ObterTurmasDoProfessor/ObterTurmasDoProfessorQuery.cs, src/SME.SGP.Aplicacao/Queries/Professores/ObterTurmasDoProfessor/ObterTurmasDoProfessorQueryHandler.cs
[AB#33176](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33176)
=> 33176 Permitir edição do encaminhamento para qualquer professor da turma

src/SME.SGP.Api/Controllers/EncaminhamentoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/VerificaPodeCadstrarEncaminhamentoAEEParaEstudanteUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoAEE/IVerificaPodeCadstrarEncaminhamentoAEEParaEstudanteUseCase.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/ObterEncaminhamentoAEEPorEstudante/ObterEncaminhamentoAEEPorEstudanteQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/ObterEncaminhamentoAEEPorEstudante/ObterEncaminhamentoAEEPorEstudanteQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoAEE.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/Encaminhamento/Cadastro/Componentes/SecaoLocalizarEstudante/secaoLocalizarEstudanteDados.js, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/AEE/ServicoEncaminhamentoAEE.js
[AB#33205](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33205)
=> 33205 não permitir cadastro de encaminhamento AEE quando já houver

src/SME.SGP.Aplicacao/Queries/RegistroIndividual/ListarAlunosDaTurmaComAusenciaDeRegistroIndividualPorDias/ListarAlunosTurmaComAusenciaRegistroIndividualPorDiasQueryHandler.cs
[AB#32959](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32959)
=> Ajuste verificação aluno ativo pendencia registro individual

src/SME.SGP.Aplicacao/Commands/EscolaAqui/Comunicados/Inclusao/SolicitarInclusaoComunicadoEscolaAquiCommandValidator.cs, src/SME.SGP.Infra/Dtos/ComunicadoInserirDto.cs
[AB#33450](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33450)
Inclusão de validação para limitar em 1024 caracteres as mensagens do comunicado
=> Validação para cadastro de comunicados

src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
[AB#33547](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33547)
=> Mapeamento registro individual

scripts/V332__REGISTRO_ITINERANCIA.sql, src/SME.SGP.Dominio/Entidades/RegistroItinerancia.cs, src/SME.SGP.Dominio/Entidades/RegistroItineranciaAluno.cs, src/SME.SGP.Dominio/Entidades/RegistroItineranciaAlunoQuestao.cs, src/SME.SGP.Dominio/Entidades/RegistroItineranciaObjetivo.cs, src/SME.SGP.Dominio/Entidades/RegistroItineranciaObjetivoBase.cs, src/SME.SGP.Dominio/Entidades/RegistroItineranciaQuestao.cs, src/SME.SGP.Dominio/Entidades/RegistroItineranciaUe.cs, src/SME.SGP.Dominio/Enumerados/TipoQuestionario.cs
[AB#32922](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32922)
=> 32922 - Modelagem registro de itinerância

src/SME.SGP.Api/Controllers/RegistroItineranciaController.cs, src/SME.SGP.Infra/Dtos/RegistroItinerancia/RegistroItineranciaObjetivoDto.cs
[AB#32925](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32925)
=> 32925 - Mock objetivos

scripts/V334__RENOMEAR_CEFAI.sql
[AB#33192](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33192)
=> 33192 Renomeado CEFAI para Coordenador CEFAI

src/SME.SGP.WebClient/src/componentes/LocalizadorEstudante/componentes/InputCodigo/index.js, src/SME.SGP.WebClient/src/componentes/LocalizadorEstudante/index.js
[AB#33174](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33174)
=> localizador de estudante - digitar somente numero

src/SME.SGP.Dados/Mapeamentos/PlanoAEEMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEE.cs, src/SME.SGP.Dominio/Entidades/PlanoAEE.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#32295](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32295)
=> Criação de entidade PlanoAEE, Mapeamentos e Repositório

scripts/V338__PLANO_AEE.sql, src/SME.SGP.Dados/Mapeamentos/PlanoAEEMap.cs, src/SME.SGP.Dados/Mapeamentos/PlanoAEEQuestaoMap.cs, src/SME.SGP.Dados/Mapeamentos/PlanoAEERespostaMap.cs, src/SME.SGP.Dados/Mapeamentos/PlanoAEEVersaoMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEQuestao.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEResposta.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEVersao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEQuestao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEResposta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEVersao.cs, src/SME.SGP.Dominio/Entidades/PlanoAEE.cs, src/SME.SGP.Dominio/Entidades/PlanoAEEQuestao.cs, src/SME.SGP.Dominio/Entidades/PlanoAEEResposta.cs, src/SME.SGP.Dominio/Entidades/PlanoAEEVersao.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
[AB#33821](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33821)
=> 33821 Modelagem Plano AEE

scripts/V336__OPCAO_RESPOSTA_OBSERVACAO.sql, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterQuestionarioEncaminhamentoAee/ObterQuestionarioEncaminhamentoAeeQueryHandler.cs, src/SME.SGP.Dominio/Entidades/OpcaoResposta.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoAEE/OpcaoRespostaDto.cs
[AB#33304](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33304)
=> 33304 Criado Observacao da Opção Resposta

src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanos/ObterPlanosAEEUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IObterPlanosAEEUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQueryValidator.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEE.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/FiltroPlanosAEEDto.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEAlunoTurmaDto.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEResumoDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#33298](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33298)
=> Implementação de endpoint para retornar Planos AEE paginados

src/SME.SGP.Api/Controllers/EncaminhamentoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterSituacaoEncaminhamentoPorEstudante/ObterSituacaoEncaminhamentoPorEstudanteUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IObterSituacaoEncaminhamentoPorEstudanteUseCase.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/ObterSituacaoEncaminhamentoAEEPorEstudante/ObterSituacaoEncaminhamentoAEEPorEstudanteQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/ObterSituacaoEncaminhamentoAEEPorEstudante/ObterSituacaoEncaminhamentoAEEPorEstudanteQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/ObterSituacaoEncaminhamentoAEEPorEstudante/ObterSituacaoEncaminhamentoAEEPorEstudanteQueryValidator.cs, src/SME.SGP.Dados/Mapeamentos/PlanoAEEMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/SituacaoEncaminhamentoAlunoDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#33299](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33299)
=> Serviço que retorna a situação de um encaminhamento por aluno

src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs, src/SME.SGP.Infra/Dtos/Devolutiva/DiarioBordoDevolutivaDto.cs
[AB#32171](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32171)
=> 32171 criado atributo com texto puro para retorno dos diários de bordo

src/SME.SGP.WebClient/src/dtos/rotasDto.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/CollapseAluno/collapseAluno.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/TabelaLinhaRemovivel/tabelaCampoRemovivel.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js
[AB#32970](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32970)
=> 32970 - permissionamento front

src/SME.SGP.WebClient/src/componentes/jodit-editor/joditEditor.js
[AB#31488](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31488)
=> R2 - FIX 31488

src/SME.SGP.WebClient/src/componentes/jodit-editor/joditEditor.js
[AB#31488](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/31488)
=> MASTER - FIX 31488 

src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/VerificarExistenciaPlanoPorEstudante/VerificarExistenciaPlanoAEEPorEstudanteUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IVerificarExistenciaPlanoAEEPorEstudanteUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/VerificarExistenciaPlanoAEEPorEstudante/VerificarExistenciaPlanoAEEPorEstudanteQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/VerificarExistenciaPlanoAEEPorEstudante/VerificarExistenciaPlanoAEEPorEstudanteQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEE.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#33851](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33851)
=> endpoint para verificar existência de plano por estudante

src/SME.SGP.WebClient/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/CollapseAluno/collapseAluno.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/EditoresTexto/editoresTexto.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js, src/SME.SGP.WebClient/src/redux/modulos/itinerancia/action.js, src/SME.SGP.WebClient/src/redux/modulos/itinerancia/reducers.js, src/SME.SGP.WebClient/src/redux/modulos/reducers.js, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/AEE/ServicoRegistroItineranciaAEE.js
[AB#33844](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33844)
=> 33844 - Questões dinâmicas

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCase.cs
[AB#33965](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33965)
=> 33965 Ajuste checagem de perfis CEFAI na DRE

src/SME.SGP.Aplicacao/CasosDeUso/Aluno/ObterAlunoPorCodigoEolEAnoLetivoUseCase.cs, src/SME.SGP.Infra/Dtos/AlunoReduzidoDto.cs
[AB#33984](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33984)
=> inclusão de campos do responsável aluno

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/EditoresTexto/editoresTexto.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/ModalObjetivos/modalObjetivos.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/ModalUE/modalUE.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js, src/SME.SGP.WebClient/src/redux/modulos/itinerancia/action.js, src/SME.SGP.WebClient/src/redux/modulos/itinerancia/reducers.js, src/SME.SGP.WebClient/src/rotas/rotas.js, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/AEE/ServicoRegistroItineranciaAEE.js
[AB#33669](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33669)
=> 33669 - Finalização consumo de endpoints

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/PesquisaResponsavelEncaminhamentoPorDreUEUseCase.cs
[AB#33965](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33965)
=> 33965 Ajuste Pesquisa de Responsável

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentosAEEUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterResponsaveisEncaminhamentosAEE.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/ObterResponsaveisDosEncaminhamentosAEE/ObterResponsaveisDosEncaminhamentosAEEQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/ObterResponsaveisDosEncaminhamentosAEE/ObterResponsaveisDosEncaminhamentosAEEQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterEncaminhamentosAee/ObterEncaminhamentosAEEQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterEncaminhamentosAee/ObterEncaminhamentosAEEQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoAEE.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoAee/FiltroPesquisaEncaminhamentosAEEDto.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/Encaminhamento/Lista/encaminhamentoAEELista.js, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/AEE/ServicoEncaminhamentoAEE.js
[AB#34012](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34012)
=> 34012 Incluso filtro de ano na listagem de Encaminhamentos AEE

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/Salvar/SalvarPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/PlanoAEEResposta/SalvarPlanoAEERespostaCommandHandler.cs, src/SME.SGP.Infra/Utilitarios/UtilData.cs
[AB#33309](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/33309)-1
=> Feature 33309 1

src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
Alteração de teste para verificação de comportamento do servidor.
=> Bug: 30794

src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/ExcluirEncaminhamentoAEE/ExcluirEncaminhamentoAEECommandHandler.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/Encaminhamento/Cadastro/Componentes/botoesAcoesEncaminhamentoAEE.js
[AB#34013](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34013)
=> encaminhamento AEE regras para habilitar btn excluir

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/Salvar/SalvarPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/SalvarPlanoAeeCommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/SalvarPlanoAeeCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEVersao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEVersao.cs
[AB#34208](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34208)
=> 34208 Transação no Salvar do Plano AEE

scripts/V341__AJUSTE_OBRIGATORIEDADE_HORARIOS_PLANO_AEE.sql, src/SME.SGP.Aplicacao/Commands/PlanoAEE/SalvarPlanoAeeCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Questionario/VerificaObrigatoriedadeQuestao/VerificaObrigatoriedadeQuestaoQuery.cs, src/SME.SGP.Aplicacao/Queries/Questionario/VerificaObrigatoriedadeQuestao/VerificaObrigatoriedadeQuestaoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioQuestao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioQuestao.cs
[AB#34213](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34213)
=> 34213 Alterado obrigatoriedade campo frequencia no AEE

src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNota.cs
Ajuste na exibição de dados de conselho ao obter nota, validando o id de conselho.
=> Bug: 33083

src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterQuestionarioEncaminhamentoAee/ObterQuestionarioEncaminhamentoAeeQueryHandler.cs
[AB#34114](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34114)
=> 34114 Exibir Justificativa de Ausencia apenas quando obrigatório

scripts/V345__UPDATE_QUESTOES_ITINERANCIA.sql, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciaPorIdUseCase.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaAlunoDto.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/ModalAlunos/modalAlunos.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/ModalErrosItinerancia/ModalErrosItinerancia.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/ModalUE/modalUE.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/index.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js
[AB#34313](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34313)
=> 34313 - ajustes pós repasse

scripts/V346__UPDATE_OBSERVACAO_QUESTAO_DIFICULDADES_APRESENTADAS.sql
[AB#34116](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34116)
=> 34116 Atualizada descrição da questão 6 Etapa 1

scripts/V347__UPDATE_DATA_RETORNO_ITINERANCIA_NULLABE.sql, src/SME.SGP.Aplicacao/Commands/Itinerancia/Salvar/SalvarItinerancia/SalvarItineranciaCommand.cs, src/SME.SGP.Dominio/Entidades/Itinerancia.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaDto.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js
[AB#34313](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34313)
=> 34313 - retirar obrigatoriedade do campo data de retorno

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCase.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterSecoesPorEtapaDeEncaminhamento/ObterSecoesPorEtapaDeEncaminhamentoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioSecaoEncaminhamentoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSecaoEncaminhamentoAEE.cs, src/SME.SGP.Dominio/Entidades/SecaoEncaminhamentoAEE.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoAee/EncaminhamentoAEERespostaDto.cs, src/SME.SGP.Infra/Dtos/EncaminhamentoAee/SecaoQuestionarioDto.cs
[AB#34120](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34120)
=> 34120 Incluso auditoria na secao encaminhamento

src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciaPorIdUseCase.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaDto.cs, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/CollapseAluno/collapseAluno.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js, src/SME.SGP.WebClient/src/servicos/servico-navegacao.js
[AB#34432](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34432)
=> Paginacação e permissão somente de quem criou o cadastro

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/CollapseAluno/collapseAluno.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js
[AB#34441](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34441)
=> 34441 - abrir apenas um colapse por vez

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/ModalObjetivos/modalObjetivos.js
[AB#34442](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34442) [AB#34371](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34371)
=> 34442 - limpar campo descricao objetivos

scripts/V349__REESTRUTURACAO_PLANO_AEE_CREATE.sql, src/SME.SGP.Dados/Mapeamentos/PlanoAEEReestruturacaoMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEReestruturacao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEReestruturacao.cs, src/SME.SGP.Dominio/Entidades/PlanoAEEReestruturacao.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
[AB#34149](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34149)
=> 34149 Modelagem Reestruturaçao do Plano AEE

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/ModalUE/modalUE.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js
[AB#34471](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34471)
=> 34471 - limitar datas e mudar nome para criança quando for ue infantil

src/SME.SGP.Api/Controllers/ItineranciaController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciaPorIdUseCase.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaDto.cs
[AB#34460](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34460)
=> Inclusão de retorno de auditoria na busca de itinerância

src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/SalvarReestruturacaoPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/SalvarPlanoAEEReestruturacao/SalvarPlanoAEEReestruturacaoCommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/SalvarPlanoAEEReestruturacao/SalvarPlanoAEEReestruturacaoCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/ISalvarReestruturacaoPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterReestruturacaoPlanoAEEPorId/ObterReestruturacaoPlanoAEEPorIdQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterReestruturacaoPlanoAEEPorId/ObterReestruturacaoPlanoAEEPorIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/VerificaExistenciaReestruturacaoPorVersaoPlanoAEEId/VerificaExistenciaReestruturacaoPorVersaoPlanoAEEIdQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/VerificaExistenciaReestruturacaoPorVersaoPlanoAEEId/VerificaExistenciaReestruturacaoPorVersaoPlanoAEEIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEReestruturacao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEReestruturacao.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEReestrutucacaoPersistenciaDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#34150](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34150)
=> 34150 Salvar da Reestruturação do Plano

src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterRestruturacoesPlanoAEE/ObterRestruturacoesPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IObterRestruturacoesPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterRestruturacoesPlanoAEE/ObterRestruturacoesPlanoAEEQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterRestruturacoesPlanoAEE/ObterRestruturacoesPlanoAEEQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterRestruturacoesPlanoAEE/ObterRestruturacoesPlanoAEEQueryValidator.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEReestruturacao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEReestruturacao.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEReestruturacaoDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#34147](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34147)
=> Implementacao de endpoint para obter restruturações por plano

scripts/V351__PLANO_AEE_DEVOLUTIVAS.sql, src/SME.SGP.Dados/Mapeamentos/PlanoAEEMap.cs, src/SME.SGP.Dominio/Entidades/PlanoAEE.cs
[AB#34154](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34154)
=> Modelagem Devolutivas do PlanoAEE

scripts/V351__PLANO_AEE_DEVOLUTIVAS.sql
[AB#34154](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34154)
=> inclusão do índice para responsavel_id

src/SME.SGP.WebClient/src/servicos/servico-navegacao.js
[AB#34157](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34157)
=> Ordenar submenus

src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterDevolutivaPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IObterDevolutivaPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanoAEEPorId/ObterPlanoAEEPorIdQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanoAEEPorId/ObterPlanoAEEPorIdQueryHandler.cs, src/SME.SGP.Dominio/Entidades/PlanoAEE.cs, src/SME.SGP.Dominio/Enumerados/SituacaoPlanoAEE.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEDevolutivaDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#34158](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34158)
=> 34158 Criado endpoint ObterDevolutivaPlanoAEE

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/ModalObjetivos/modalObjetivos.js, src/SME.SGP.WebClient/src/utils/funcoes/gerais.js
[AB#34458](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34458)
=> 34458 - Ajuste salvar descricao dos objetivos - clone de objetos

src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/CadastrarDevolutivaCPPlanoAEE/CadastrarDevolutivaCPPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarDevolutivaCP/CadastrarDevolutivaCPCommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarDevolutivaCP/CadastrarDevolutivaCPCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarDevolutivaCP/CadastrarDevolutivaCPCommandValidator.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/ICadastrarDevolutivaCPPlanoAEEUseCase.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEECadastroDevolutivaDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#27272](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/27272)
=> 34160 - Implementado endpoint para devolutiva do CP

scripts/V351__PENDENCIAS_ENCAMINHAMENTO_AEE_CREATE.sql, src/SME.SGP.Dados/Mapeamentos/PendenciaEncaminhamentoAEEMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaEncaminhamentoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaEncaminhamentoAEE.cs, src/SME.SGP.Dominio/Entidades/PendenciaEncaminhamentoAEE.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#34548](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34548)
=> Modelagem Pendencia x Encaminhamento AEE

scripts/V351__PLANO_AEE_DEVOLUTIVAS.sql, src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlano/EncerrarPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/EncerrarPlanoAEE/EncerrarPlanoAeeCommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/EncerrarPlanoAEE/EncerrarPlanoAeeCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/EncerrarPlanoAEE/EncerrarPlanoAeeCommandValidator.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IEncerrarPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanoAEEPorId/ObterPlanoAEEPorIdQueryHandler.cs, src/SME.SGP.Dominio/Entidades/PlanoAEE.cs, src/SME.SGP.Dominio/Enumerados/SituacaoPlanoAEE.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/RetornoEncerramentoPlanoAEEDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#34152](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34152)
=> Implementação de endpoint para EncerrarPlano

src/SME.SGP.WebClient/src/componentes/modalConteudoHtml.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/ModalObjetivos/modalObjetivos.js, src/SME.SGP.WebClient/src/utils/funcoes/gerais.js
[AB#34475](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34475) [AB#34448](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34448)
=> 34475 - ajuste validação de campos de objetivo ao fechar

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Lista/registroItineranciaAEELista.js
[AB#34690](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34690) [AB#34669](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34669)
=> 34690 - Validações campos de data

src/SME.SGP.WebClient/src/componentes/listaPaginada/listaPaginada.js
[AB#34678](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34678) [AB#34701](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34701)
=> 34678 - ajuste lista replicando valores

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Lista/registroItineranciaAEELista.js
[AB#34668](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34668) [AB#34721](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34721)
=> 34668 - Mudar localizador de estudante

src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ExecutaEncerramentoPlanoAEEEstudantesInativosUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/PersistirPlanoAEE/PersistirPlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/PersistirPlanoAEE/PersistirPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IEncerrarPlanosAEEEstudantesInativosUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IExecutaEncerramentoPlanoAEEEstudantesInativosUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEEAtivos/ObterPlanosAEEAtivosQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEEAtivos/ObterPlanosAEEAtivosQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEE.cs, src/SME.SGP.Dominio/Enumerados/SituacaoPlanoAEE.cs, src/SME.SGP.Infra/Fila/RotasRabbit.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#34167](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34167)
=> 34046 Worker para Encerramento de Planos de Alunos inativos

src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEReestruturacao.cs
[AB#34736](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34736)
=> Ajuste na ordenação da data

src/SME.SGP.WebClient/src/redux/modulos/planoAEE/reducers.js
[AB#34664](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34664)
=> [Cadastro do Plano] perfis sem permissão edição estão editando

src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciaPorIdUseCase.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaDto.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js
[AB#34460](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34460) [AB#34651](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34651)
=> 34460 - Auditoria

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Lista/registroItineranciaAEELista.js, src/SME.SGP.WebClient/src/servicos/Paginas/Relatorios/AEE/ServicoRegistroItineranciaAEE.js
[AB#34472](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34472) [AB#34683](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34683)
=> 34472 - Consumo de endpoint de ano letivo

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js
[AB#34449](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34449) [AB#34796](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34796)
=> 34449 - perguntar antes de voltar

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js
[AB#34453](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34453) [AB#34797](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34797)
=> 34453 - Correção ao excluir ue de itinerancia salva

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCase.cs
[AB#34779](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34779)
=> Ajuste na chamada para obter professores da turma

src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterQuestionarioEncaminhamentoAee/ObterQuestionarioEncaminhamentoAeeQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterModalidadeTurmaPorCodigo/ObterModalidadeTurmaPorCodigoQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterModalidadeTurmaPorCodigo/ObterModalidadeTurmaPorCodigoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurma.cs
[AB#34758](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34758)
=> 34758 Percentual de frequencia Minimo para Infantil

teste/SME.SGP.Aplicacao.Teste/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCaseTeste.cs
[AB#34779](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34779)-1
=> foi ajustado o teste para nova Query buscando por professor

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js
[AB#34636](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34636) [AB#34801](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34801)
=> 34636 - Ajuste loadings

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ConcluirEncaminhamentoAEEUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/DevolverEncaminhamentoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/EncerrarEncaminhamentoAEEUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ExcluirEncaminhamentoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/AtribuirResponsavelEncaminhamentoAEE/AtribuirResponsavelEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/EnviarParaAnaliseEncaminhamentoAEE/EnviarParaAnaliseEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/Pendencias/ObterPendenciaEncaminhamentoAEEPorIdEUsuarioId/ObterPendenciaEncaminhamentoAEEPorIdEUsuarioIdQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/Pendencias/ObterPendenciaEncaminhamentoAEEPorIdEUsuarioId/ObterPendenciaEncaminhamentoAEEPorIdEUsuarioIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/Pendencias/ObterPendenciaEncaminhamentoAEEPorIdEUsuarioId/ObterPendenciaEncaminhamentoAEEPorIdEUsuarioIdQueryValidator.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/Pendencias/ObterPendenciasDoEncaminhamentoAEEPorId/ObterPendenciasDoEncaminhamentoAEEPorIdQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/Pendencias/ObterPendenciasDoEncaminhamentoAEEPorId/ObterPendenciasDoEncaminhamentoAEEPorIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/Pendencias/ObterPendenciasDoEncaminhamentoAEEPorId/ObterPendenciasDoEncaminhamentoAEEPorIdQueryValidator.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUEPorTurmaId/ObterUEPorTurmaIdQuery.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUEPorTurmaId/ObterUEPorTurmaIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUEPorTurmaId/ObterUEPorTurmaIdQueryValidator.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaEncaminhamentoAEE.cs, src/SME.SGP.Dados/Repositorios/RepositorioUe.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaEncaminhamentoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioUe.cs
[AB#34543](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34543)
=> Implementação de exclusão de pendências de encaminhamento para o CP

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Lista/registroItineranciaAEELista.js
[AB#34857](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34857)
=> 34857 - Colocar o botão considera histórico na tela novamente

src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/AlterarItineranciaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/Salvar/SalvarItineranciaAluno/SalvarItineranciaAlunoCommandHandler.cs
[AB#34743](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34743)
=> Ajuste ao obter o id da turma passando o turma_id

src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciaPorIdUseCase.cs
[AB#34743](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34743)
=> Ajuste no dto de retorno do buscar por id

src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaAtribuirResponsavelEncaminhamentoAEE/GerarPendenciaAtribuirResponsavelEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaCPEncaminhamentoAEE/GerarPendenciaCPEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaPAEEEncaminhamentoAEE/GerarPendenciaPAEEEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Dominio/Entidades/Turma.cs
[AB#34898](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34898)
=> 34898 Incluso turma na mensagem das Pendencias do Encaminhamento AEE

src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciasUseCase.cs, src/SME.SGP.Aplicacao/Queries/Itinerancia/ObterItinerancias/ObterItineranciasQuery.cs, src/SME.SGP.Aplicacao/Queries/Itinerancia/ObterItinerancias/ObterItineranciasQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioItinerancia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioItinerancia.cs, src/SME.SGP.Infra/Dtos/Itinerancia/FiltroPesquisaItineranciasDto.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaResumoDto.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaRetornoQueryDto.cs, src/SME.SGP.WebClient/src/componentes/LocalizadorPadrao/index.js, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Lista/registroItineranciaAEELista.js
[AB#32643](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/32643)
=> 32643 - Filtro criado por

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/componentes/ModalAlunos/modalAlunos.js
[AB#34895](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34895) [AB#34929](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34929)
=> 34895 - Ajuste alunos sendo adicionados novamente

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js
[AB#34966](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34966)
=> 34966 - Ajuste mensagem voltar

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/RegistroItinerancia/Cadastro/registroItineranciaAEECadastro.js
[AB#34966](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/34966)
=> 34966 - Ajuste mensagem

src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEol/ObterAlunoPorCodigoEolQuery.cs
=> Bug: 34802

src/SME.SGP.Api/Controllers/PlanoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterQuestoesPlanoAEEPorVersaoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IObterQuestoesPlanoAEEPorVersaoUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterQuestoesPlanoAEEPorVersao/ObterQuestoesPlanoAEEPorVersaoQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterQuestoesPlanoAEEPorVersao/ObterQuestoesPlanoAEEPorVersaoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObteCodigosDreUePorTurma/ObteCodigosDreUePorTurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObteCodigosDreUePorTurma/ObteCodigosDreUePorTurmaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurma.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/FiltroPesquisaQuestoesPlanoAEEDto.cs, src/SME.SGP.Infra/Dtos/Questionario/FiltroPesquisaQuestoesPlanoAEEDto.cs, src/SME.SGP.Infra/Dtos/Turma/DreUeDaTurmaDto.cs
[AB#35011](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35011)
=> 35011 Removido opção Itinerante do Questionario do PlanoAEE com PAEE

scripts/V353__QUESTIONARIO_PLANO_AEE_JUSTIFIQUE_NAO.sql
[AB#35016](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35016)
=> 35016 Incluso justificativa nas opções "Não" das questões 7, 8, 9 e 10

scripts/V355__PENDENCIA_PLANO_AEE_CREATE.sql, src/SME.SGP.Dados/Mapeamentos/PendenciaPlanoAEEMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaPlanoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaPlanoAEE.cs, src/SME.SGP.Dominio/Entidades/PendenciaPlanoAEE.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
[AB#35029](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35029)
=> 35029 Modelagem Pendencia x Plano AEE

src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ExecutaPendenciaValidadePlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/GerarPendenciaValidadePlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/GerarPendenciaValidadePlanoAEE/GerarPendenciaValidadePlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/GerarPendenciaValidadePlanoAEE/GerarPendenciaValidadePlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IExecutaPendenciaValidadePlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IGerarPendenciaValidadePlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEEPorDataFim/ObterPlanosAEEPorDataFimQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEEPorDataFim/ObterPlanosAEEPorDataFimQueryHandler.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEE.cs, src/SME.SGP.Dominio/Entidades/PendenciaPlanoAEE.cs, src/SME.SGP.Infra/Fila/RotasRabbit.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#35031](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35031)
=> 35031 Worker Geração Pendencia Validade PlanoAEE

scripts/V356__PARAMETROS_GERACAO_PENDENCIA_AEE.sql, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RegistrarEncaminhamentoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/AtribuirResponsavelEncaminhamentoAEE/AtribuirResponsavelEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/EnviarParaAnaliseEncaminhamentoAEE/EnviarParaAnaliseEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
[AB#35074](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35074)
=> 35074 Criados Parametros para ativar/desativar geração de pendencias

src/SME.SGP.Aplicacao/Commands/PlanoAEE/AtribuirResponsavelPlanoAEE/AtribuirResponsavelPlanoAEECommandHandler.cs
[AB#35071](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35071)
=> 35071 Gerar pendência PAAI responsável do plano

src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarDevolutivaPAAI/CadastrarDevolutivaPAAICommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Pendencias/ExcluirPendenciaPlanoAEE/ExcluirPendenciaPlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Pendencias/ExcluirPendenciaPlanoAEE/ExcluirPendenciaPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/PlanoAEEResposta/SalvarPlanoAEERespostaCommandHandler.cs
[AB#35073](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35073)
=> 35073 Exclusão de Pendencia do PAAI responsável

src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarDevolutivaCP/CadastrarDevolutivaCPCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Pendencias/ExcluirPendenciaPlanoAEE/ExcluirPendenciaPlanoAEECommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaPlanoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaPlanoAEE.cs
[AB#35039](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35039)
=> 35039 Exclusão de Pendencias dos CPs ao registrar parecer

src/SME.SGP.WebClient/src/paginas/DiarioClasse/AcompanhamentoFrequencia/acompanhamentoFrequencia.js
=> Troca do nome do componente de Disciplina para Componente curricular

src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
[AB#35218](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35218)
=> 35218 - Alterado para utilizar o endpoint do EOL de alunos-ativos

src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/ExcluirPendenciasEncaminhamentoAEECEFAI/ExcluirPendenciasEncaminhamentoAEECEFAICommandHandler.cs
[AB#35163](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35163)
=> 35163 Tratamento para quando não possuir pendencia

scripts/V358__PARAMETROS_NOTIFICACAO_PLANO_AEE_CREATE.sql, src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
[AB#35076](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35076)
=> Parâmetro para indicar o envio de notificação

src/SME.SGP.WebClient/src/paginas/DiarioClasse/AcompanhamentoFrequencia/acompanhamentoFrequencia.js
[AB#35236](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35236)
=> 35236 - Correção ao selecionar compnente curricular

src/SME.SGP.Aplicacao/CasosDeUso/RegistroIndividual/ListarAlunosDaTurmaRegistroIndividualUseCase.cs
[AB#35242](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35242)
=> endpoint de registro individual para retornar se o aluno é atendido pelo aee

scripts/V359__PARAMETRO_DIAS_NOTIFICACAO_PLANO_AEE_EXPIRADO.sql, src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ExecutaNotificacaoPlanoAEEExpiradoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/NotificarPlanosAEEExpiradosUseCase.cs, src/SME.SGP.Aplicacao/Commands/Notificacao/EnviarNotificacaoUsuarios/EnviarNotificacaoUsuariosCommand.cs, src/SME.SGP.Aplicacao/Commands/Notificacao/EnviarNotificacaoUsuarios/EnviarNotificacaoUsuariosCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/GerarNotificacaoPlanoAEE/GerarNotificacaoPlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/GerarNotificacaoPlanoAEE/GerarNotificacaoPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IExecutaNotificacaoPlanoAEEExpiradoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/INotificarPlanosAEEExpiradosUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEEPorDataFim/ObterPlanosAEEPorDataFimQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEEPorDataFim/ObterPlanosAEEPorDataFimQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEE.cs, src/SME.SGP.Dominio/Entidades/NotificacaoPlanoAEE.cs, src/SME.SGP.Dominio/Enumerados/NotificacaoPlanoAEETipo.cs, src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs, src/SME.SGP.Infra/Fila/RotasRabbit.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#35077](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35077)
=> 35077 Worker Notificação Planos AEE expirados

src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciasUseCase.cs
[AB#35239](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35239)
=> Ajuste na ordenação, por datetime

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/VerificaEstudantePossuiPlanoAEEPorCodigoEAnoQuery/VerificaEstudantePossuiPlanoAEEPorCodigoEAnoQueryHandler.cs
[AB#35254](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35254)
=> Ajuste na verificação se o aluno é atendido pelo AEE

src/SME.SGP.Aplicacao/Consultas/ConsultasRelatorioSemestralPAPAluno.cs
[AB#35261](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35261)
=> Verifica se o estudante tem atendimento AEE

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EnviarNotificacaoReestruturacaoPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/SalvarReestruturacaoPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/EnviarFilaNotificacaoReestruturacaoPlanoAEE/EnviarFilaNotificacaoReestruturacaoPlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/EnviarFilaNotificacaoReestruturacaoPlanoAEE/EnviarFilaNotificacaoReestruturacaoPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/EnviarNotificacaoReestruturacaoPlanoAEE/EnviarNotificacaoReestruturacaoPlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/EnviarNotificacaoReestruturacaoPlanoAEE/EnviarNotificacaoReestruturacaoPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/GerarNotificacaoPlanoAEE/GerarNotificacaoPlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/GerarNotificacaoPlanoAEE/GerarNotificacaoPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IEnviarNotificacaoReestruturacaoPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanoAEEPorReestruturacaoId/ObterPlanoAEEPorReestruturacaoIdQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanoAEEPorReestruturacaoId/ObterPlanoAEEPorReestruturacaoIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanoAEEReestruturacaoPorId/ObterPlanoAEEReestruturacaoPorIdQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanoAEEReestruturacaoPorId/ObterPlanoAEEReestruturacaoPorIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEReestruturacao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEReestruturacao.cs, src/SME.SGP.Dominio/Enumerados/NotificacaoPlanoAEETipo.cs, src/SME.SGP.Infra/Fila/RotasRabbit.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#35079](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35079)
=> 35079 Notifica Reestruturação de PlanoAEE

src/SME.SGP.Dados/Repositorios/RepositorioItinerancia.cs
[AB#35244](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35244)
=> retirada de ueId do retorno

src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/ObterAnotacaoFrequenciaAlunoPorIdUseCase.cs, src/SME.SGP.WebClient/src/paginas/DiarioClasse/AcompanhamentoFrequencia/Componentes/ListaAlunos/listaAlunos.js, src/SME.SGP.WebClient/src/paginas/DiarioClasse/AcompanhamentoFrequencia/Componentes/ListaAlunos/modalAnotacoesAcompanhamentoFrequencia.js
[AB#35187](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35187) [AB#35240](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35240)
=> 35187 - Correções componente de anotações do aluno

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/NotificarPlanosAEEExpiradosUseCase.cs
[AB#35081](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35081)
=> 35081 Notificação de plano AEE encerrado automaticamente

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EnviarNotificacaoEncerramentoPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarDevolutivaPAAI/CadastrarDevolutivaPAAICommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/EnviarFilaNotificacaoEncerramentoPlanoAEE/EnviarFilaNotificacaoEncerramentoPlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/EnviarFilaNotificacaoEncerramentoPlanoAEE/EnviarFilaNotificacaoEncerramentoPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/NotificarEncerramentoPlanoAEE/NotificarEncerramentoPlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/NotificarEncerramentoPlanoAEE/NotificarEncerramentoPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IEnviarNotificacaoEncerramentoPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanoAEEComTurmaPorId/ObterPlanoAEEComTurmaPorIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanoAEEComTurmaUeEDrePorId/ObterPlanoAEEComTurmaUeEDrePorIdQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanoAEEComTurmaUeEDrePorId/ObterPlanoAEEComTurmaUeEDrePorIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEE.cs, src/SME.SGP.Infra/Fila/RotasRabbit.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#35082](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35082)
=> 35082 Notificação Encerramento do Planos

src/SME.SGP.WebClient/src/paginas/DiarioClasse/AcompanhamentoFrequencia/Componentes/ListaAlunos/ausenciasAluno.js
[AB#35188](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35188)
[AB#35274](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35274)
=> 35188 - Ajuste mensagem sem dados colapse

src/SME.SGP.Infra/Dtos/AbrangenciaTurmaRetornoEolDto.cs
=> Bug: 35186

src/SME.SGP.Aplicacao/Commands/Armazenamento/UploadArquivo/UploadArquivoCommandHandler.cs
Teste para detecção de erro no upload de imagem.
=> Bug: 35267

src/SME.SGP.Aplicacao/Commands/PlanoAEE/AtribuirResponsavelPlanoAEE/AtribuirResponsavelPlanoAEECommandHandler.cs
[AB#35316](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35316)
=> 35316 Excluir pendencia do plano AEE mesmo quando não gerar nova

src/SME.SGP.WebClient/src/paginas/DiarioClasse/DiarioBordo/diarioBordo.js
Ajuste na tela completa de diário de bordo para exibição correta da devolutiva.
=> Bug: 35233

src/SME.SGP.WebClient/public/configuracoes/variaveis.json, src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/AnotacoesRecomendacoes/AnotacoesAluno/anotacoesAluno.js, src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/AnotacoesRecomendacoes/RecomendacaoAlunoFamilia/recomendacaoAlunoFamilia.js, src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/conselhoClasse.js, src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/servicoSalvarConselhoClasse.js
[AB#35458](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35458)
=> 35458 - Alterações frontend

src/SME.SGP.Aplicacao/CasosDeUso/RegistroIndividual/ListarAlunosDaTurmaRegistroIndividualUseCase.cs
Removida a validação ao tentar gerar pendência ao acessar a tela de registro individual.
=> Bug: 35603

src/SME.SGP.WebClient/package.json, src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/Plano/Cadastro/Componentes/TabCadastroPlano/tabCadastroPlano.js
[AB#35583](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35583)
=> 35583 - Adicionada flag do AEE no Plano AEE

teste/SME.SGP.Aplicacao.Teste/CasosDeUso/TipoCalendario/BuscarTiposCalendarioPorDescricaoUseCaseTeste.cs
=> Bug: 35001

src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/Plano/Lista/planoAEELista.js
[AB#35644](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35644)
=> 35644 - Corrigida a flag para informar se é atendidoAEE

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterCodigoTurmaRegularPorAnoLetivoAluno/ObterCodigoTurmaRegularPorAnoLetivoAlunoQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterCodigoTurmaRegularPorAnoLetivoAluno/ObterCodigoTurmaRegularPorAnoLetivoAlunoQueryHandler.cs, src/SME.SGP.Dominio/Entidades/Turma.cs, src/SME.SGP.WebClient/public/configuracoes/variaveis.json
[AB#35449](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35449)
=> 35449 - Ajustes obter recomendações

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/GerarPendenciaValidadePlanoAEEUseCase.cs, src/SME.SGP.Dominio/Enumerados/SituacaoPlanoAEE.cs
[AB#35713](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35713)
=> 35713 Alteração da situação para PlanoAEE Expirado

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterCodigoTurmaRegularPorAnoLetivoAluno/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterCodigoTurmaRegularPorAnoLetivoAluno/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQueryHandler.cs, teste/SME.SGP.Aplicacao.Teste/Consultas/ConsultasConselhoClasseTeste.cs
[AB#35764](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35764)
=> 35764 - Ajuste endpoint ObterConselhoClasseTurma

src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
[AB#35823](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35823)
=> 35823 - Correção do mapeamento para ocorrencias

src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs
[AB#35854](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35854)
=> 35854 Filtro de data fim do plano AEE por vigencia do período escolar

src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
[AB#35823](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35823)
=> 35823 - Registro de mapeamentos que estavam faltando

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/NotificarPlanosAEEEmAbertoUseCase.cs, src/SME.SGP.Dados/Contexto/SgpContext.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEReduzidoDto.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/PlanosAEEPorSupervisorDto.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/PlanosAEEPorUEDto.cs
[AB#35753](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35753)
=> 35753 Corrigido agrupamento da notificação de PlanosAEE ativos / Supervisor

src/SME.SGP.Aplicacao/Queries/MotivosAusencia/ObterMotivoPorTurmaAlunoComponenteCurricularBimestre/ObterMotivoPorTurmaAlunoComponenteCurricularBimestreQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAnotacaoFrequenciaAluno.cs
[AB#35899](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35899)
=> 35899 Corrigido paginação dos resultados

src/SME.SGP.Aplicacao/Queries/Questionario/ObterQuestoesPorQuestionarioPorId/ObterQuestoesPorQuestionarioPorIdQueryHandler.cs, src/SME.SGP.Infra/Dtos/Questionario/QuestaoDto.cs
[AB#35934](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35934)
=> 35934 - Adicionado o campo SomenteLeitura no DTO de retorno da questão

scripts/V364__ACOMPANHAMENTO_ALUNO_CREATE.sql, src/SME.SGP.Dados/Mapeamentos/AcompanhamentoAlunoFotoMap.cs, src/SME.SGP.Dados/Mapeamentos/AcompanhamentoAlunoMap.cs, src/SME.SGP.Dados/Mapeamentos/AcompanhamentoAlunoSemestreMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioAcompanhamentoAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioAcompanhamentoAlunoFoto.cs, src/SME.SGP.Dados/Repositorios/RepositorioAcompanhamentoAlunoSemestre.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAcompanhamentoAluno.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAcompanhamentoAlunoFoto.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAcompanhamentoAlunoSemestre.cs, src/SME.SGP.Dominio/Entidades/AcompanhamentoAluno.cs, src/SME.SGP.Dominio/Entidades/AcompanhamentoAlunoFoto.cs, src/SME.SGP.Dominio/Entidades/AcompanhamentoAlunoSemestre.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
[AB#35937](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35937)
=> 35937 Modalagem Acompanhamento Aluno

src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs, src/SME.SGP.Dados/Repositorios/RepositorioUe.cs, src/SME.SGP.Dominio/Entidades/Turma.cs
Ajustando sincronização para tipos de turma
=> Ajustando itens da sincronização instuticional

scripts/V367__ACOMPANHAMENTO_ALUNO_SEMESTRE_OBSERVACOES.sql, src/SME.SGP.Api/Controllers/AcompanhamentoAlunoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs, src/SME.SGP.Aplicacao/Commands/AcompanhamentoAluno/GerarAcompanhamentoAluno/GerarAcompanhamentoAlunoCommand.cs, src/SME.SGP.Aplicacao/Commands/AcompanhamentoAluno/GerarAcompanhamentoAluno/GerarAcompanhamentoAlunoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/AcompanhamentoAluno/GerarAcompanhamentoAlunoSemestre/GerarAcompanhamentoAlunoSemestreCommand.cs, src/SME.SGP.Aplicacao/Commands/AcompanhamentoAluno/GerarAcompanhamentoAlunoSemestre/GerarAcompanhamentoAlunoSemestreCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/AcompanhamentoAluno/SalvarAcompanhamentoAlunoSemestre/SalvarAcompanhamentoAlunoSemestreCommand.cs, src/SME.SGP.Aplicacao/Commands/AcompanhamentoAluno/SalvarAcompanhamentoAlunoSemestre/SalvarAcompanhamentoAlunoSemestreCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AcompanhamentoAluno/ISalvarAcompanhamentoAlunoUseCase.cs, src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterAcompanhamentoAlunoSemestrePorId/ObterAcompanhamentoAlunoSemestrePorIdQuery.cs, src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterAcompanhamentoAlunoSemestrePorId/ObterAcompanhamentoAlunoSemestrePorIdQueryHandler.cs, src/SME.SGP.Infra/Dtos/AcompanhamentoAluno/AcompanhamentoAlunoDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#35945](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35945)
=> 35945 Endpoint Salvar do Acompanhamento Aluno

src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#36090](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36090)
=> fix/36090 - Atualizada a permissão para exibir no menu

scripts/V365__NOVOS_GRUPOS_MATRIZ_AJUSTES_COMPONENTES_CURRICULARES.sql, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#36068](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36068)
=> 36068 - Correções

src/SME.SGP.Api/Controllers/AcompanhamentoAlunoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarFotoAlunoUseCase.cs, src/SME.SGP.Aplicacao/Commands/AcompanhamentoAluno/GerarAcompanhamentoAlunoFoto/GerarAcompanhamentoAlunoFotoCommand.cs, src/SME.SGP.Aplicacao/Commands/AcompanhamentoAluno/GerarAcompanhamentoAlunoFoto/GerarAcompanhamentoAlunoFotoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/AcompanhamentoAluno/SalvarFotoAluno/SalvarFotoAlunoCommand.cs, src/SME.SGP.Aplicacao/Commands/AcompanhamentoAluno/SalvarFotoAluno/SalvarFotoAlunoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/ArmazenarImagemFisica/ArmazenarImagemFisicaCommand.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/ArmazenarImagemFisica/ArmazenarImagemFisicaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/UploadArquivo/UploadArquivoCommand.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/UploadImagem/UploadImagemCommand.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/UploadImagem/UploadImagemCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AcompanhamentoAluno/ISalvarFotoAlunoUseCase.cs, src/SME.SGP.Aplicacao/SME.SGP.Aplicacao.csproj, src/SME.SGP.Dominio/Enumerados/TipoArquivo.cs, src/SME.SGP.Infra/Dtos/Armazenamento/ArquivoArmazenadoDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#35946](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35946)
=> 35946 Endpoint Upload Foto Aluno

scripts/V368__INCLUSAO_GRADES_EMEFM_1_INTEGRAL.sql, scripts/V369__INCLUSAO_GRADES_EMEFM_2_INTEGRAL.sql, scripts/V370__INCLUSAO_GRADES_EMEFM_1_NOTURNO.sql, scripts/V371__INCLUSAO_GRADES_EMEBS_1_INTEGRAL.sql, scripts/V372__INCLUSAO_GRADES_EMEBS_1_NOTURNO.sql
[AB#35960](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35960) - Criado scripts para inserção da nova grade do ensino médio
=> feature/35960 

src/SME.SGP.Api/Controllers/AcompanhamentoAlunoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ObterFotosSemestreAlunoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AcompanhamentoAluno/IObterFotosSemestreAlunoUseCase.cs, src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterMiniaturasFotosSemestreAluno/ObterMiniaturasFotosSemestreAlunoQuery.cs, src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterMiniaturasFotosSemestreAluno/ObterMiniaturasFotosSemestreAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAcompanhamentoAlunoFoto.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAcompanhamentoAlunoFoto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#35947](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35947)
=> 35947 Obter Miniaturas Fotos Aluno

src/SME.SGP.Api/Controllers/AcompanhamentoAlunoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ExcluirFotoAlunoUseCase.cs, src/SME.SGP.Aplicacao/Commands/AcompanhamentoAluno/ExcluirFotoAcompanhamentoAluno/ExcluirFotoAcompanhamentoAlunoCommand.cs, src/SME.SGP.Aplicacao/Commands/AcompanhamentoAluno/ExcluirFotoAcompanhamentoAluno/ExcluirFotoAcompanhamentoAlunoCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AcompanhamentoAluno/IExcluirFotoAlunoUseCase.cs, src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterFotoSemestreAlunoPorCodigo/ObterFotoSemestreAlunoPorCodigoQuery.cs, src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterFotoSemestreAlunoPorCodigo/ObterFotoSemestreAlunoPorCodigoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterFotoSemestreAlunoPorId/ObterFotoSemestreAlunoPorIdQuery.cs, src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterFotoSemestreAlunoPorId/ObterFotoSemestreAlunoPorIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterFotoSemestreAlunoPorMiniaturaId/ObterFotoSemestreAlunoPorMiniaturaIdQuery.cs, src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterFotoSemestreAlunoPorMiniaturaId/ObterFotoSemestreAlunoPorMiniaturaIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAcompanhamentoAlunoFoto.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAcompanhamentoAlunoFoto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#35949](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/35949)
=> 35949 Enpoint Exclusão de Foto Aluno

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ObterAcompanhamentoAlunoUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioParametrosSistema.cs
[AB#36413](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36413)
=> 36413 Corrigido carga de fotos do acompanhamento em anos anteriores

src/SME.SGP.Api/Dockerfile
[AB#36396](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36396)
=> Ajuste no docker file para tratar a biblioteca de imagens

src/SME.SGP.Aplicacao/CasosDeUso/Armazenamento/Editor/UploadArquivoEditorUseCase.cs
[AB#36503](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36503)
=> Alterado o tipo de retorno

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurma/ObterFechamentoTurmaPorIdAlunoCodigo/ObterFechamentoTurmaPorIdAlunoCodigoQuery.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurma/ObterFechamentoTurmaPorIdAlunoCodigo/ObterFechamentoTurmaPorIdAlunoCodigoQueryHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs
[AB#36191](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36191)
=> 36191 - Ajustes anos anteriores

src/SME.SGP.Api/Dockerfile
[AB#36396](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36396)
=> Ajuste no dockerfile para instalar dependências System.Drawing nativas

src/SME.SGP.WebClient/src/paginas/Relatorios/AcompanhamentoAprendizagem/DadosAcompanhamentoAprendizagem/Tabs/RegistrosFotos/RegistrosIndividuais/registrosIndividuais.js
[AB#36533](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36533)
=> 36533 Ajuste permissão

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/servicoSalvarConselhoClasse.js
[AB#36585](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36585)
=> 36585 - Ajustes aba final obter notas

scripts/V378__AJUSTE_PERFIL_ADM_DRE.sql
[AB#36606](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36606) - Criado script para inserir a prioridade_perfil para Comunicados DRE
=> fix/36606 

src/SME.SGP.Aplicacao/Commands/PlanoAEE/SalvarPlanoAeeCommandHandler.cs
Não estava trocando a situação expirado para em andamento
[AB#36605](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36605)
=> 36605 - Ajuste situação do plano AEE ao Salvar.

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs, src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs, src/SME.SGP.Dominio/Entidades/Turma.cs
[AB#36720](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36720) [AB#36721](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36721)
=> 36720 - Ajuste fechamento inexistente

scripts/V379__ACOMPANHAMENTO_TURMA_CREATE.sql, src/SME.SGP.Dados/Mapeamentos/AcompanhamentoTurmaMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioAcompanhamentoTurma.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAcompanhamentoTurma.cs, src/SME.SGP.Dominio/Entidades/AcompanhamentoTurma.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#36757](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36757)
=> Modelagem Acompanhamento Turma

src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNota.cs
[AB#36790](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36790) [AB#36791](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36791)
=> 36790 - ajuste ao acesso da aba final

scripts/V380__ALUNO_FOTO_CREATE.sql, src/SME.SGP.Dados/Mapeamentos/AlunoFotoMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioAlunoFoto.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAlunoFoto.cs, src/SME.SGP.Dominio/Entidades/AlunoFoto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#36704](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36704)
=> 36704 - Criada modelagem da tabela aluno_foto

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodo.cs, src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs
=> Ajustando validação de notas

src/SME.SGP.Api/Controllers/EstudanteController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Estudante/ExcluirEstudanteFotoUseCase.cs, src/SME.SGP.Aplicacao/Commands/Estudante/ExcluirFotoEstudante/ExcluirFotoEstudanteCommand.cs, src/SME.SGP.Aplicacao/Commands/Estudante/ExcluirFotoEstudante/ExcluirFotoEstudanteCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Estudante/ExcluirFotoEstudante/ExcluirFotoEstudanteCommandValidator.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Estudante/IExcluirEstudanteFotoUseCase.cs, src/SME.SGP.Aplicacao/Queries/Estudante/ObterFotoAlunoPorAlunoCodigo/ObterFotoAlunoPorAlunoCodigoQuery.cs, src/SME.SGP.Aplicacao/Queries/Estudante/ObterFotoAlunoPorAlunoCodigo/ObterFotoAlunoPorAlunoCodigoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Estudante/ObterFotoAlunoPorAlunoCodigo/ObterFotoAlunoPorAlunoCodigoQueryValidator.cs, src/SME.SGP.Dados/Repositorios/RepositorioAlunoFoto.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAlunoFoto.cs, src/SME.SGP.Infra/Dtos/Armazenamento/MiniaturaFotoDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#36705](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36705)
=> 36705 - Criado fluxo para excluir foto do aluno

src/SME.SGP.Api/Controllers/DashboardAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/DashboardAEE/ObterPlanoAEESituacoesUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardAEE/IObterPlanoAEESituacoesUseCase.cs, src/SME.SGP.Aplicacao/Queries/DashboardAEE/ObterPlanoAEESituacoes/ObterPlanoAEESituacoesQuery.cs, src/SME.SGP.Aplicacao/Queries/DashboardAEE/ObterPlanoAEESituacoes/ObterPlanoAEESituacoesQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEE.cs, src/SME.SGP.Infra/Dtos/DashboardAEE/AEESituacaoDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#37017](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37017)
=> 37017 - Criado fluxo para obter situacoes do planoAEE na dashboard

src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarPorTurmaBimestre/ObterPeriodoEscolarPorTurmaBimestreQuery.cs, src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs
[AB#36940](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36940)
=> Ajuste no query para passar bimestre final

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorTurmasCodigo/ObterComponentesCurricularesPorTurmasCodigoQuery.cs
[AB#36996](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36996)
=> CM - Deixar a prop como nullable para o defult não ser um valor válido.

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseNota.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasConselhoClasseNota.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNota.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseNota.cs
[AB#36944](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36944)
=> 36944 - Ajuste ao buscar notas de fechamento

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorTurmasCodigo/ObterComponentesCurricularesPorTurmasCodigoQueryHandler.cs
[AB#37023](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37023) [AB#36996](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36996)
=> 37023 - Mostrar todos os componentes curriculares para professor CJ

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs
[AB#37028](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37028)
=> 37028 - Correção bug

src/SME.SGP.Aplicacao/CasosDeUso/Turma/SincronizacaoEstruturaInstitucionalTurmas/EnviarSincronizacaoEstruturaInstitucionalTurmasUseCase.cs, src/SME.SGP.Aplicacao/Commands/Sincronizacao/Ues/EnviarNotificacaoSincronizacaoUesInclusao/EnviarSincronizacaoEstruturaInstitucionalUesCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Turma/SincronizacaoEstruturaInstitucionalTurmas/IEnviarSincronizacaoEstruturaInstitucionalTurmasUseCase.cs, src/SME.SGP.Infra/Fila/RotasRabbit.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#37138](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37138)
=> Criação fila estrutura.institucional.turmas.sync

src/SME.SGP.Aplicacao/CasosDeUso/DashboardAEE/ObterAlunosMatriculadosSRMPAEEUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs, src/SME.SGP.Infra/Dtos/DashboardAEE/AEEAlunosMatriculadosDto.cs, src/SME.SGP.Infra/Dtos/DashboardAEE/AlunosMatriculadosEolDto.cs
[AB#37228](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37228)
=> 37228 Ordenação por modalidade no graficos de SRM e Deferidos

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciasAlunosPorCodigoAlunoCodigoComponentesTurma/ObterFrequenciasAlunosPorCodigoAlunoCodigoComponentesTurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciasAlunosPorCodigoAlunoCodigoComponentesTurma/ObterFrequenciasAlunosPorCodigoAlunoCodigoComponentesTurmaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodo.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaAlunoDisciplinaPeriodo.cs, src/SME.SGP.Dominio.Servicos/ServicoCalculoParecerConclusivo.cs
[AB#37073](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37073) [AB#37072](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37072)
=> 37073 - ajuste parecer conslusivo por frequência

src/SME.SGP.WebClient/src/componentes-sgp/RegistroIndividual/novoRegistroIndividual/novoRegistroIndividual.js
[AB#37246](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37246)
=> Registro individual - ajuste na permissao

src/SME.SGP.Aplicacao/Commands/Estudante/SalvarFotoEstudante/SalvarFotoEstudanteCommandHandler.cs
[AB#37240](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37240)
=> 37240 Removido Validação de Existencia do Aluno

src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/ListasNotasConceito/listasNotasConceitos.js
[AB#37268](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37268) [AB#37273](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37273)
=> 37268 - Ajustes validação somente ao alterar recomendações ou anotações aba final

src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs
[AB#37291](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37291) [AB#37292](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37292)
=> 37291 - ajuste verificar as disciplinas corretas para lançamento de notas

scripts/V383__TIPO_CICLO_ANO_4_E_PARECER_ANO_4.sql
[AB#37195](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37195)
=> CM - Ajuste de registros para trazer o 4º ano para o relatório de parecer conclusivo

src/SME.SGP.Aplicacao/CasosDeUso/DashboardAEE/ObterAlunosMatriculadosSRMPAEEUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DashboardAEE/ObterEncaminhamentosAEEDeferidosUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DashboardAEE/ObterPlanosAEEVigentesUseCase.cs, src/SME.SGP.Aplicacao/Queries/DashboardAEE/ObterPlanosAEEAcessibilidades/ObterPlanosAEEAcessibilidadesQueryHandler.cs
[AB#37278](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37278)
=> 37278 - Correção de agrupamento das modalidades

src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/servicoSalvarConselhoClasse.js
[AB#37300](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37300) [AB#37268](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37268)
=> 37300 - pergunta antes de salvar

src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasFinaisConselhoFechamentoPorAlunoTurmas/ObterNotasFinaisConselhoFechamentoPorAlunoTurmasQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasFinaisConselhoFechamentoPorAlunoTurmas/ObterNotasFinaisConselhoFechamentoPorAlunoTurmasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/FechamentoNota/ObterNotasFinaisPorAlunoTurmas/ObterNotasFinaisPorAlunoTurmasQuery.cs, src/SME.SGP.Aplicacao/Queries/FechamentoNota/ObterNotasFinaisPorAlunoTurmas/ObterNotasFinaisPorAlunoTurmasQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNota.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNota.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseAluno.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseNota.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotaConceitoBimestre.cs, src/SME.SGP.Dominio.Servicos/ServicoCalculoParecerConclusivo.cs, src/SME.SGP.Infra/Dtos/NotaConceitoFechamentoConselhoFinalDto.cs
[AB#37281](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37281) [AB#37283](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37283)
=> 37281 - Ajustes parecer, considerar turmas do tipo 2 e 7

scripts/V384__NOVAS_MODALIDADES.sql, scripts/V385__F_ABRANGENCIA_PARAMETRO_NOVAS_MODALIDADES.sql, src/SME.SGP.Api/Controllers/AbrangenciaController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Abrangencia/ObterModalidadesPorAnoUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Abrangencia/IObterModalidadesPorAnoUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasAbrangencia.cs, src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterModalidadesPorAno/ObterModalidadesPorAnoQuery.cs, src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterModalidadesPorAno/ObterModalidadesPorAnoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterNovasModalidadesPorAno/ObterNovasModalidadesPorAnoQuery.cs, src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterNovasModalidadesPorAno/ObterNovasModalidadesPorAnoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAbrangencia.cs, src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#37179](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37179)
=> CM - Adição do param. novas modalidades e aplicação na abrangência

scripts/V385__F_ABRANGENCIA_PARAMETRO_NOVAS_MODALIDADES.sql, src/SME.SGP.Api/Controllers/FiltroRelatorioController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterFiltroRelatoriosModalidadesPorUe/ObterFiltroRelatoriosModalidadesPorUeUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasTipoCalendario.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IObterFiltroRelatoriosModalidadesPorUeAbrangenciaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IObterFiltroRelatoriosModalidadesPorUeUseCase.cs, src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterNovasModalidadesPorAno/ObterNovasModalidadesPorAnoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosModalidadesPorUe/ObterFiltroRelatoriosModalidadesPorUeQuery.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosModalidadesPorUe/ObterFiltroRelatoriosModalidadesPorUeQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaQuery.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAbrangencia.cs
[AB#37375](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37375)
=> CM - Ajuste dos endpoints de busca de modalidades por filtros de relatórios

src/SME.SGP.Api/Controllers/UeController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterFiltroRelatoriosModalidadesPorUe/ObterFiltroRelatoriosModalidadesPorUeUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/UE/ObterModalidadesPorUe/ObterModalidadesPorUeUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasUe.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/UE/IObterModalidadesPorUeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasUe.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosModalidadesPorUe/ObterFiltroRelatoriosModalidadesPorUeQuery.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaQuery.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterModalidadesPorUeEAnoLetivo/ObterModalidadesPorUeEAnoLetivoQuery.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterModalidadesPorUeEAnoLetivo/ObterModalidadesPorUeEAnoLetivoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioUe.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioUe.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#37474](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37474)
=> CM - Ajuste do Endpoint de consulta modalidades por UE (UeController)

src/SME.SGP.Api/Controllers/RelatorioController.cs, src/SME.SGP.Aplicacao/CasosDeUso/DashboardAEE/ObterEncaminhamentosAEEDeferidosUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DashboardAEE/ObterPlanosAEEVigentesUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Itinerancia/RelatorioItineranciasUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IRelatorioItineranciasUseCase.cs, src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs, src/SME.SGP.Infra/Dtos/Relatorios/Itinerancias/FiltroRelatorioItineranciaDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#37431](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37431)
=> 37431 - Endpoint Relatório de Itinerâncias

src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#36845](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36845)
=> 36845 Ajuste Menu Relatório Devolutivas

src/SME.SGP.Aplicacao/CasosDeUso/Abrangencia/ObterModalidadesPorAnoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterFiltroRelatoriosModalidadesPorUe/ObterFiltroRelatoriosModalidadesPorUeUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/UE/ObterModalidadesPorUe/ObterModalidadesPorUeUseCase.cs, src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterNovasModalidadesPorAno/ObterNovasModalidadesPorAnoQuery.cs, src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterNovasModalidadesPorAno/ObterNovasModalidadesPorAnoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioParametrosSistema.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioParametrosSistema.cs
[AB#36814](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36814)
=> CM - Ajustar a regra de definição do ano apra busca de parâmetros de novas modalidades.

src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAluno.cs, src/SME.SGP.Dominio.Servicos/ServicoCalculoParecerConclusivo.cs
[AB#37532](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37532)
=> 37532 - Ajuste parecer conclusivo conceitos pós conselho

scripts/V387__INCLUSAO_COMUNICADOS_UE_PRIORIDADE_PERFIL.sql
[AB#37571](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37571)
=> 37571 - Inclusão de Comunicados UE no prioridade de perfil

src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs
Removendo a sincronização institucional da lista de rotinas recorrentes por não estar sendo executada e será substituída por uma que será executada através do Rabbit.
=> Bug: 37459

src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAluno.cs, src/SME.SGP.Dominio.Servicos/ServicoCalculoParecerConclusivo.cs, src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/Justificativa/Justificativa.js, src/SME.SGP.WebClient/src/paginas/Fechamento/ConselhoClasse/DadosConselhoClasse/ListasNotasConceito/CamposNotaConceito/campoConceito.js, src/SME.SGP.WebClient/src/paginas/Relatorios/DiarioClasse/BoletimSimples/index.js, src/SME.SGP.WebClient/src/redux/modulos/conselhoClasse/actions.js, src/SME.SGP.WebClient/src/redux/modulos/conselhoClasse/reducers.js
[AB#37532](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37532) [AB#37615](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37615)
=> 37532 - Ajustes parecer conclusivo

src/SME.SGP.WebClient/src/paginas/Dashboard/DashboardEscolaAqui/TabsDashboardEscolaAqui/DadosComunicadosLeitura/dadosComunicadosLeitura.js, src/SME.SGP.WebClient/src/servicos/Paginas/FiltroRelatorio/ServicoFiltroRelatorio.js
[AB#37187](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37187)
=> 37187 -  Ajuste tela de dashboard escola aqui

scripts/V390_PERFIL_EVENTO_TIPO_CREATE.sql, scripts/V391_F_EVENTOS_CALENDARIO_POR_PERFIL.sql, src/SME.SGP.Aplicacao/Consultas/ConsultasEventoTipo.cs, src/SME.SGP.Dados/Mapeamentos/PerfilEventoTipoMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioEventoTipo.cs, src/SME.SGP.Dados/Repositorios/RepositorioPerfilEventoTipo.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEventoTipo.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPerfilEventoTipo.cs, src/SME.SGP.Dominio/Entidades/PerfilEventoTipo.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
[AB#37558](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37558)
=> 37558 Tipo de Evento Itinerância PAAI

src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs
[AB#37502](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37502)
=> Ajuste lançamento nota

src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/SalvarItineranciaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Evento/CriarEventoItineranciaPAAI/CriarEventoItineranciaPAAICommand.cs, src/SME.SGP.Aplicacao/Commands/Evento/CriarEventoItineranciaPAAI/CriarEventoItineranciaPAAICommandHandler.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaUeDto.cs
[AB#37561](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37561)
=> 37561 Criação de Evento Itinerância PAAI automático

scripts/V392_ITINERANCIA_EVENTO.sql, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/SalvarItineranciaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/Salvar/SalvarItinerancia/SalvarItineranciaCommand.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/Salvar/SalvarItinerancia/SalvarItineranciaCommandHandler.cs, src/SME.SGP.Dados/Mapeamentos/ItineranciaMap.cs, src/SME.SGP.Dominio/Entidades/Itinerancia.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaDto.cs
[AB#37564](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37564)
=> 37564 Vincular Evento na Itinerância

src/SME.SGP.Api/Controllers/ItineranciaController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterEventosItinerânciaPorTipoCalendarioUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Itinerancia/IObterEventosItinerânciaPorTipoCalendarioUseCase.cs, src/SME.SGP.Aplicacao/Queries/Evento/ObterEventosItineranciaPAAI/ObterEventosItineranciaPAAIQuery.cs, src/SME.SGP.Aplicacao/Queries/Evento/ObterEventosItineranciaPAAI/ObterEventosItineranciaPAAIQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEvento.cs, src/SME.SGP.Infra/Dtos/EventoDataDto.cs, src/SME.SGP.Infra/Dtos/EventoNomeDto.cs
[AB#37566](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37566)
=> 37566 Listagem de Eventos Itinerância PAAI

scripts/V394__ITINERANCIA_EVENTO_CREATE.sql, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/AlterarItineranciaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciaPorIdUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/SalvarItineranciaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/AtualizarDatasEventosItinerancia/AtualizarDatasEventosItineranciaCommand.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/AtualizarDatasEventosItinerancia/AtualizarDatasEventosItineranciaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/CriarEventoItineranciaPAAI/CriarEventoItineranciaPAAICommand.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/CriarEventoItineranciaPAAI/CriarEventoItineranciaPAAICommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/RemoverEventosItinerancia/RemoverEventosItineranciaCommand.cs, src/SME.SGP.Aplicacao/Commands/Itinerancia/RemoverEventosItinerancia/RemoverEventosItineranciaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUesPorIds/ObterUesPorIdsQueryHandler.cs, src/SME.SGP.Dados/Mapeamentos/ItineranciaEventoMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioItineranciaEvento.cs, src/SME.SGP.Dados/Repositorios/RepositorioUe.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioItineranciaEvento.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioUe.cs, src/SME.SGP.Dominio/Entidades/ItineranciaEvento.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#37984](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37984)
=> 37984 Atualização de Eventos ao mudar data de retorno da Itinerancia

scripts/V395__PERFIL_EVENTO_TIPO_COORD_CEFAI.sql, scripts/V396__F_EVENTOS_CALENDARIO_POR_PERFIL_2.sql, src/SME.SGP.Dados/Repositorios/RepositorioEventoTipo.cs
[AB#38009](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38009)
=> 38009 Acesso ao cadastro de eventos do tipo Itinerancia apenas para PAAI
