prefeiturasp/SME-NovoSGP

src/SME.SGP.Aplicacao/CasosDeUso/TipoCalendario/ObterTiposCalendarioPorAnoLetivoModalidadeoUseCase.cs
src/SME.SGP.Aplicacao/Commands/Itinerancia/CriarEventoItineranciaPAAI/CriarEventoItineranciaPAAICommandHandler.cs
src/SME.SGP.Aplicacao/Queries/Evento/ObterEventosItineranciaPAAI/ObterEventosItineranciaPAAIQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/EventoTipo/ObterEventoTipoIdPorCodigo/ObterEventoTipoIdPorCodigoQuery.cs
src/SME.SGP.Aplicacao/Queries/EventoTipo/ObterEventoTipoIdPorCodigo/ObterEventoTipoIdPorCodigoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTipoCalendarioIdPorAnoLetivoEModalidade/ObterTipoCalendarioIdPorAnoLetivoEModalidadeQuery.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTipoCalendarioIdPorAnoLetivoEModalidade/ObterTipoCalendarioIdPorAnoLetivoEModalidadeQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTipoCalendarioIdPorCodigoUE/ObterTipoCalendarioIdPorCodigoUEQuery.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTipoCalendarioIdPorCodigoUE/ObterTipoCalendarioIdPorCodigoUEQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTiposCalendarioPorAnoLetivoModalidade/ObterTiposCalendarioPorAnoLetivoModalidadeQuery.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTiposCalendarioPorAnoLetivoModalidade/ObterTiposCalendarioPorAnoLetivoModalidadeQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/UE/ObterTipoEscolaPorCodigoUE/ObterTipoEscolaPorCodigoUEQuery.cs
src/SME.SGP.Aplicacao/Queries/UE/ObterTipoEscolaPorCodigoUE/ObterTipoEscolaPorCodigoUEQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
src/SME.SGP.Dados/Repositorios/RepositorioEventoTipo.cs
src/SME.SGP.Dados/Repositorios/RepositorioUe.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEventoTipo.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioUe.cs

Vinculado tipo de calendário e tipo de evento
[AB#38015](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38015)

38015 Ajuste na geração do evento automático

---

scripts/V398__PLANO_AEE_OBSERVACAO_CREATE.sql
src/SME.SGP.Dados/Mapeamentos/NotificacaoPlanoAEEObservacaoMap.cs
src/SME.SGP.Dados/Mapeamentos/PlanoAEEObservacaoMap.cs
src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoPlanoAEEObservacao.cs
src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEObservacao.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotificacaoPlanoAEEObservacao.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEObservacao.cs
src/SME.SGP.Dominio/Entidades/NotificacaoPlanoAEEObservacao.cs
src/SME.SGP.Dominio/Entidades/PlanoAEEObservacao.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs

[AB#37584](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37584)

37584 Modalagem Observação Plano AEE

---

src/SME.SGP.Api/Controllers/PlanoAEEObservacaoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEEObservacao/CriarPlanoAEEObservacaoUseCase.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/CriarPlanoAEEObservacao/CriarPlanoAEEObservacaoCommand.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/CriarPlanoAEEObservacao/CriarPlanoAEEObservacaoCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEEObservacao/ICriarPlanoAEEObservacaoUseCase.cs
src/SME.SGP.Dominio/Entidades/PlanoAEEObservacao.cs
src/SME.SGP.Infra/Dtos/PlanoAEEObservacao/PersistenciaPlanoAEEObservacaoDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#37585](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37585)

37585 enpoint Criar Observação Plano AEE

---

src/SME.SGP.Api/Controllers/PlanoAEEObservacaoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEEObservacao/AlterarPlanoAEEObservacaoUseCase.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/AlterarPlanoAEEObservacao/AlterarPlanoAEEObservacaoCommand.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/AlterarPlanoAEEObservacao/AlterarPlanoAEEObservacaoCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEEObservacao/IAlterarPlanoAEEObservacaoUseCase.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#37587](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37587)

37587 endpoint Alteração de Observação do PlanoAEE

---

scripts/V398__PLANO_AEE_OBSERVACAO_CREATE.sql
src/SME.SGP.Api/Controllers/PlanoAEEObservacaoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEEObservacao/ExcluirPlanoAEEObservacaoUseCase.cs
src/SME.SGP.Aplicacao/Commands/Notificacao/ExcluirNotificacaoPorId/ExcluirNotificacaoPorIdCommand.cs
src/SME.SGP.Aplicacao/Commands/Notificacao/ExcluirNotificacaoPorId/ExcluirNotificacaoPorIdCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/ExcluirNotificacaoPlanoAEEObservacao/ExcluirNotificacaoPlanoAEEObservacaoCommand.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/ExcluirNotificacaoPlanoAEEObservacao/ExcluirNotificacaoPlanoAEEObservacaoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/ExcluirPlanoAEEObservacao/ExcluirPlanoAEEObservacaoCommand.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/ExcluirPlanoAEEObservacao/ExcluirPlanoAEEObservacaoCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEEObservacao/IExcluirPlanoAEEObservacaoUseCase.cs
src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoPlanoAEEObservacao.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotificacaoPlanoAEEObservacao.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#37588](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37588)

37588 endpoint exclusão de observação do planoAEE

---

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEEObservacao/AlterarPlanoAEEObservacaoUseCase.cs
src/SME.SGP.Aplicacao/Commands/Notificacao/EnviarNotificacaoUsuarios/EnviarNotificacaoUsuariosCommand.cs
src/SME.SGP.Aplicacao/Commands/Notificacao/EnviarNotificacaoUsuarios/EnviarNotificacaoUsuariosCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/GerarNotificacaoPlanoAEE/GerarNotificacaoPlanoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/AlterarPlanoAEEObservacao/AlterarPlanoAEEObservacaoCommand.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/AlterarPlanoAEEObservacao/AlterarPlanoAEEObservacaoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/CriarPlanoAEEObservacao/CriarPlanoAEEObservacaoCommand.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/CriarPlanoAEEObservacao/CriarPlanoAEEObservacaoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/NotificarObservacaoPlanoAEE/NotificarObservacaoPlanoAEECommand.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/NotificarObservacaoPlanoAEE/NotificarObservacaoPlanoAEECommandHandler.cs
src/SME.SGP.Dados/Mapeamentos/NotificacaoPlanoAEEObservacaoMap.cs
src/SME.SGP.Dominio/Entidades/NotificacaoPlanoAEEObservacao.cs

[AB#37591](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37591)

37591 notificação de observação no plano AEE

---

src/SME.SGP.Api/Controllers/PlanoAEEObservacaoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEEObservacao/ObterPlanoAEEObservacaoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEEObservacao/IObterPlanoAEEObservacaoUseCase.cs
src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterObservacoesPlanoAEEPorId/ObterObservacoesPlanoAEEPorIdQuery.cs
src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterObservacoesPlanoAEEPorId/ObterObservacoesPlanoAEEPorIdQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEObservacao.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEObservacao.cs
src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEObservacaoDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#37586](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37586)

Listagem de Observações do Plano

---

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs
src/SME.SGP.Infra/Dtos/TurmaAnoDto.cs

[AB#37589](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37589)

37589 carregado codigo da UE para o plano AEE

---

src/SME.SGP.Aplicacao/Commands/Itinerancia/CriarEventoItineranciaPAAI/CriarEventoItineranciaPAAICommandHandler.cs

[AB#38020](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38020)

38020 Substituido a descrição do objetivo por um texto padrão

---

src/SME.SGP.Aplicacao/Commands/Itinerancia/CriarEventoItineranciaPAAI/CriarEventoItineranciaPAAICommandHandler.cs

[AB#38020](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38020)

38020 Ajuste descrição do evento da itinerância

---

src/SME.SGP.Api/Startup.cs
src/SME.SGP.Dominio.Servicos/ServicoUsuario.cs
src/SME.SGP.Infra/Dtos/UsuarioAutenticacaoRetornoDto.cs

[AB#37574](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37574)

37574 - Alterado fluxo para contrato externo

---

scripts/V393_INCLUSAO_GRUPOS_COMUNICADOS.sql
src/SME.SGP.Aplicacao/Commands/EscolaAqui/Comunicados/Inclusao/SolicitarInclusaoComunicadoEscolaAquiCommandHandler.cs

[AB#37915](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37915)

Implementação de relação de grupos x modalidades

---

src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterItineranciaPorIdUseCase.cs

[AB#38164](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38164)

ajuste na funcão pode editar

---

src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs

[AB#38026](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38026)

38026 Listar eventos apenas da abrangência do usuário

---

scripts/V393_INCLUSAO_GRUPOS_COMUNICADOS.sql
src/SME.SGP.Dados/Repositorios/RepositorioGrupoComunicacao.cs

[AB#38212](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38212)

Ajuste na busca de grupos por modalidade

---

src/SME.SGP.WebClient/src/paginas/DiarioClasse/DiarioBordo/componentes/ModalNotificarUsuarios/modalNotificarUsuarios.js
src/SME.SGP.WebClient/src/paginas/Relatorios/AEE/Plano/Cadastro/Componentes/ObservacoesPlanoAEE/montarDadosObservacoesPlanoAEE.js

[AB#38211](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38211)

Plano AEE - Observações  ajuste permissao

---

src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEObservacao.cs

[AB#38221](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38221)

38221 corrigido carga do usuário

---

src/SME.SGP.Aplicacao/Commands/Itinerancia/Notificacao/NotificacaoUsusarioCriadorRegistroItinerancia/NotificacaoUsuarioCriadorRegistroItineranciaCommandHandler.cs

[AB#38077](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38077)

38077 Distinct dos alunos para não repetir na tabela

---

src/SME.SGP.Api/Controllers/TipoCalendarioController.cs

[AB#38263](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38263)

Ajuste de permissão

---

src/SME.SGP.Aplicacao/Queries/Evento/ObterEventosItineranciaPAAI/ObterEventosItineranciaPAAIQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
src/SME.SGP.Infra/Dtos/EventoDataDto.cs

[AB#38246](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38246)

38246 - Incluso tipo escola na seleção de eventos

---

src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/CriarPlanoAEEObservacao/CriarPlanoAEEObservacaoCommand.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/CriarPlanoAEEObservacao/CriarPlanoAEEObservacaoCommandHandler.cs

[AB#38254](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38254)

38254 Não notificar o criador da observação

---

src/SME.SGP.WebClient/src/paginas/Relatorios/Atas/AtaFinalResultados/ataFinalResultados.js

[AB#38073](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38073)

38073 - Criar campo de validação e aplicar regras

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNota.cs
src/SME.SGP.Infra/Dtos/NotaConceitoBimestreComponenteDto.cs

[AB#38265](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38265) [AB#38271](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38271)

38265 - Busca correta das notas pós conselho - histórico escolar EJA

---

src/SME.SGP.Api/Controllers/FiltroRelatorioController.cs
src/SME.SGP.Dominio/Enumerados/AtaFinalTipoVisualizacao.cs

[AB#38092](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38092)

38092 - Implementação do tipo de visualização ata final

---

scripts/V404__SUGESTAO_REGISTRO_INDIVIDUAL.sql

[AB#38560](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38560)

38560 - Script de sugestões

---

src/SME.SGP.WebClient/src/paginas/Relatorios/Planejamento/Devolutivas/relatorioDevolutivas.js

[AB#36845](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36845)

36845 Passar Id da turma para emissão do relatório

---

src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Cadastro/index.js
src/SME.SGP.WebClient/src/paginas/AcompanhamentoEscolar/Comunicados/Filtro/index.js
src/SME.SGP.WebClient/src/servicos/Paginas/AcompanhamentoEscolar/ComunicadoEvento/ServicoComunicadoEvento.js

[AB#38256](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38256)

comunicados - ajuste novos tipos de escolas

---

scripts manutencao/38652 Carga Periodos Fechamento/38652 Carga Periodos Fechamento.sql

[AB#38652](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38652)

38652 Script carga períodos fechamentos

---

src/SME.SGP.Aplicacao/Comandos/ComandosAtribuicaoCJ.cs
src/SME.SGP.Dominio.Servicos/ServicoAtribuicaoCJ.cs
src/SME.SGP.Infra/Fila/GoogleClassroomApi/RotasRabbitGoogleClassroomApi.cs

[AB#38513](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38513)

CM - Aplicação da remoção da atribuição no GCA quando tirar a atribuição CJ

---

scripts/V407__ATUALIZACAO_AREA_CONHECIMENTO_CC_BUG_38802.sql

[AB#38802](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38802)

Script atualização area conhecimento

---

src/SME.SGP.Dados/Mapeamentos/ConsolidacaoFrequenciaTurmaMap.cs
src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoFrequenciaTurma.cs
src/SME.SGP.Dominio/Entidades/ConsolidacaoFrequenciaTurma.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs

[AB#38528](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38528)

Modelagem base para o dashboard

---

scripts/V409__CRIACAO_CONSOLIDACAO_FREQUENCIA_TURMA.sql
src/SME.SGP.Dados/Mapeamentos/ConsolidacaoFrequenciaTurmaMap.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoFrequenciaTurma.cs
src/SME.SGP.Dominio/Entidades/ConsolidacaoFrequenciaTurma.cs

[AB#39012](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39012)

39012 Ajuste na modelagem da consolidação de Frequencia referencia Turma

---

src/SME.SGP.Api/Controllers/DashboardFrequenciaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterDadosDashboardFrequenciaPorDreUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFrequencia/IObterDadosDashboardFrequenciaPorDreUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/DashboardFrequenciaConstants.cs
src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDadosDashboardFrequenciaPorDre/ObterDadosDashboardFrequenciaPorDreQuery.cs
src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDadosDashboardFrequenciaPorDre/ObterDadosDashboardFrequenciaPorDreQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoFrequenciaTurma.cs
src/SME.SGP.Infra/Dtos/FrequenciaGlobalPorDreDto.cs
src/SME.SGP.Infra/Dtos/Grafico/Ferequencia/GraficoFrequenciaGlobalPorDREDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#38532](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38532)

CM - Endpoint de frequência global por DRE

---

src/SME.SGP.Dominio/Constantes/Perfis.cs
src/SME.SGP.Dominio/Entidades/Usuario.cs

[AB#39029](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39029)

Tratamento para priorizar perfil ComunicadoUE

---

src/SME.SGP.Api/Controllers/DashboardFrequenciaController.cs
src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDadosDashboardFrequenciaPorAno/ObterDadosDashboardFrequenciaPorAnoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaTurma.cs
src/SME.SGP.Infra/Dtos/FrequenciaGlobalPorAnoDto.cs

[AB#38531](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38531)

38531 - Ajustes agrupamento

---

src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs
src/SME.SGP.Api/Startup.cs
src/SME.SGP.Aplicacao/CasosDeUso/GoogleClassroom/ExecutaSyncGsaGoogleClassroomUseCase.cs
src/SME.SGP.Infra/GoogleClassroom/GoogleClassroomSyncOptions.cs
src/SME.SGP.Worker.Rabbbit/Startup.cs
src/SME.SGP.WorkerService/Program.cs
src/SME.SGP.WorkerService/WorkerService.cs

[AB#39005](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39005)

CM - Adição do controle da sync GSA por variável de ambiente.

---

src/SME.SGP.Api/Controllers/DashboardFrequenciaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterModalidadesAnoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFrequencia/IObterDashboardFrequenciaPorAnoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFrequencia/IObterModalidadesAnoUseCase.cs
src/SME.SGP.Aplicacao/Queries/ModalidadesPorAnos/ObterModalidadesPorAnosQuery.cs
src/SME.SGP.Aplicacao/Queries/ModalidadesPorAnos/ObterModalidadesPorAnosQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurma.cs
src/SME.SGP.Infra/Dtos/Grafico/Ferequencia/ModalidadesPorAnoDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#38533](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38533)

Endpoint de modalidades por Anos

---

src/SME.SGP.Api/Controllers/DashboardFrequenciaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterDashboardFrequenciaPorAnoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFrequencia/IObterDashboardFrequenciaPorAnoUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDadosDashboardFrequenciaPorAno/ObterDadosDashboardFrequenciaPorAnoQuery.cs
src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDadosDashboardFrequenciaPorAno/ObterDadosDashboardFrequenciaPorAnoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoFrequenciaTurma.cs
src/SME.SGP.Infra/Dtos/FrequenciaGlobalPorAnoDto.cs

[AB#38536](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38536)

38536 - Endpoint de anos e ajuste de agrupamento por anos

---

src/SME.SGP.Api/Controllers/DashboardFrequenciaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterDashboardFrequenciaAusenciasPorMotivoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFrequencia/IObterDashboardFrequenciaAusenciasPorMotivoUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDashboardFrequenciaAusenciasPorMotivo/ObterDashboardFrequenciaAusenciasPorMotivoQuery.cs
src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDashboardFrequenciaAusenciasPorMotivo/ObterDashboardFrequenciaAusenciasPorMotivoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioFrequencia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequencia.cs

[AB#39078](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39078)

39078 - Ajuste endpoint

---

src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaTurma.cs

Ajustes após conflito

---

src/SME.SGP.Aplicacao/CasosDeUso/Notificacoes/ObterQuantidadeNotificacoesNaoLidasPorUsuarioUseCase.cs
src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioLogadoRF/ObterUsuarioLogadoRFQuery.cs
src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioLogadoRF/ObterUsuarioLogadoRFQueryHandler.cs

Otimizando busca de qnt de mensagens não lidas

Adicionando Query para obter usuario RF logado;

---

src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDadosDashboardAusenciasComJustificativa/ObterDadosDashboardAusenciasComJustificativaQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaTurma.cs
src/SME.SGP.Infra/Dtos/Grafico/Ferequencia/GraficoAusenciasComJustificativaDto.cs

[AB#39078](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39078)

correções agrupamento por turma

---

src/SME.SGP.Dados/Repositorios/RepositorioFechamentoAluno.cs

[AB#37820](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/37820)

bug: 37820 - correção

---

src/SME.SGP.Infra/Enumerados/Permissao.cs

[AB#39115](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39115)

CM - Criação do menu AEE

---

src/SME.SGP.Api/Controllers/FechamentoAcompanhamentoTurmasController.cs
src/SME.SGP.Dominio/Enumerados/StatusFechamento.cs
src/SME.SGP.Infra/Dtos/FechamentoAcompanhamentoTurmas/FiltroAcompanhamentoFechamentoStatuDtos.cs
src/SME.SGP.Infra/Dtos/FechamentoAcompanhamentoTurmas/StatusTotalFechamentoDto.cs

[AB#38900](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/38900)

38900 - Criar mock fechamentos/acompanhamentos/turmas/{turmaId}

---

scripts/V411__NOVOS_PARAMETRO_DATA_ULTIMA_ATUALIZACAO_CONSOLIDACAO_FREQUENCIA.sql

[AB#39122](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39122)

ajuste no script com parametros nos anos anteriores

---

src/SME.SGP.Aplicacao/Consultas/ConsultaAtividadeAvaliativa.cs

Ajuste na consulta de atividade avaliativa considerando a data selecionada da avaliação ao invés da data atual fixamente.

Bug: 39071

---

scripts/V413__ORDENACAO_AREA_CONHECIMENTO_ITINERARIO_FORMATIVO.sql

[AB#39098](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39098)

Ajuste ordenacao componentes

---

scripts/V415__CRIACAO_TABELA_CONSOLIDACAO_DEVOLUTIVAS.sql
src/SME.SGP.Dados/Mapeamentos/ConsolidacaoDevolutivasMap.cs
src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoDevolutivas.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoDevolutivas.cs
src/SME.SGP.Dominio/Entidades/ConsolidacaoDevolutivas.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs

[AB#39429](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39429)

Implementação de modelagem de devolutiva

---

scripts/V416__CRIACAO_PARAMETRO_PERIODO_DE_DIAS_DEVOLUTIVA.sql
src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs

[AB#39406](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39406)

Criação de parametro PeriodoDeDiasDevolutiva

---

src/SME.SGP.Dados/Repositorios/RepositorioAula.cs

Ajuste no processamento de pendências de frequência, desconsiderando aulas excluídas.

Bug: 39589

---

src/SME.SGP.Api/Controllers/DashboardDevolutivasController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardDevolutivas/ObterGraficoDiariosDeBordoComDevolutivaEDevolutivaPendenteUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardDevolutivas/IObterGraficoDiariosDeBordoComDevolutivaEDevolutivaPendenteUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardDevolutivas/ObterDiariosDeBordoComDevolutivaEDevolutivaPendente/GraficoDiariosDeBordoComDevolutivaEDevolutivaPendenteConstants.cs
src/SME.SGP.Aplicacao/Queries/DashboardDevolutivas/ObterDiariosDeBordoComDevolutivaEDevolutivaPendente/ObterDiariosDeBordoComDevolutivaEDevolutivaPendenteQuery.cs
src/SME.SGP.Aplicacao/Queries/DashboardDevolutivas/ObterDiariosDeBordoComDevolutivaEDevolutivaPendente/ObterDiariosDeBordoComDevolutivaEDevolutivaPendenteQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDiarioBordo.cs
src/SME.SGP.Infra/Dtos/Grafico/Devolutivas/FiltroGraficoDiariosDeBordoComDevolutivaEDevolutivaPendenteDto.cs
src/SME.SGP.Infra/Dtos/Grafico/Devolutivas/GraficoDiariosDeBordoComDevolutivaEDevolutivaPendenteDto.cs
src/SME.SGP.Infra/Dtos/Grafico/Devolutivas/QuantidadeDiariosDeBordoComDevolutivaEDevolutivaPendentePorTurmaAnoDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#39409](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39409)

CM - Endpoint de quantidade de diarios de bordo com devolutiva e com devolutivas pendentes por turma/ano

---

src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesDoProfessorNaTurma/ObterComponentesCurricularesDoProfessorCJNaTurmaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesDoProfessorNaTurma/ObterComponentesCurricularesDoProfessorNaTurmaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterFimPeriodoRecorrencia/ObterFimPeriodoRecorrenciaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioPossuiPermissaoNaTurmaEDisciplina/ObterUsuarioPossuiPermissaoNaTurmaEDisciplinaQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAtribuicaoCJ.cs
src/SME.SGP.Dados/Repositorios/RepositorioBase.cs
src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusenciaAluno.cs
src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodo.cs
src/SME.SGP.Dados/Repositorios/RepositorioRegistroAusenciaAluno.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtribuicaoCJ.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioBase.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusenciaAluno.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaAlunoDisciplinaPeriodo.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroAusenciaAluno.cs

1. InserirAulaRecorrenteCommandHandler
1. NotificarUsuario
1. Concatenado String de mensagens com LinQ para melhor performance
2. ValidarComponentesProfessor
1. Componentes.Any substituido por componentes.All para simplificação e performance
1. Mais fácil entender “Se não” do que “Se não do não” e quando encontra uma condição errada já sai
2. ObterComponentesCurricularesDoProfessorCJNaTurmaQueryHandler
1. Adicionado encapsulamento de cache na consulta (Calculo quantitativo resultou em ~70k 
2. Alterado para chamada assíncrona de consulta
3. RepositorioAtribuicaoCJ
1. Adicionado consulta assíncrona ObterAtribuicaoCJ
4. ObterFimPeriodoRecorrenciaQueryHandler
1. Adicionado encapsulamento de cache para a chamada ObterPorTipoCalendarioAsync (ver relação de tamanho abaixo)

[WIP] Feature/otimizacao fechamento

---

scripts/V417__CRIACAO_CONSOLIDACAO_MATRICULAS_TURMA.sql
src/SME.SGP.Dados/Mapeamentos/ConsolidacaoMatriculaTurmaMap.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoMatriculaTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoMatriculaTurma.cs
src/SME.SGP.Dominio/Entidades/ConsolidacaoMatriculaTurma.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#39448](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39448)

39448 - Modelagem

---

src/SME.SGP.Api/Controllers/DashboardDevolutivasController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardDevolutivas/ObterDevolutivasEstimadasEConfirmadasUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardDevolutivas/IObterDevolutivasEstimadasEConfirmadasUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardDevolutivas/DashboardDevolutivasConstants.cs
src/SME.SGP.Aplicacao/Queries/DashboardDevolutivas/ObterDevolutivasEstimadasEConfirmadas/ObterDevolutivasEstimadasEConfirmadasQuery.cs
src/SME.SGP.Aplicacao/Queries/DashboardDevolutivas/ObterDevolutivasEstimadasEConfirmadas/ObterDevolutivasEstimadasEConfirmadasQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoDevolutivas.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoDevolutivas.cs
src/SME.SGP.Infra/Dtos/Grafico/Devolutivas/GraficoDevolutivasEstimadasEConfirmadas/FiltroGraficoDevolutivasEstimadasEConfirmadasDto.cs
src/SME.SGP.Infra/Dtos/Grafico/Devolutivas/GraficoDevolutivasEstimadasEConfirmadas/GraficoDevolutivasEstimadasEConfirmadasDto.cs
src/SME.SGP.Infra/Dtos/Grafico/Devolutivas/GraficoDevolutivasEstimadasEConfirmadas/QuantidadeDevolutivasEstimadasEConfirmadasPorTurmaAnoDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#39408](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39408)

CM - Endpoint de consolidação de devolutivas estimadas e registradas

---

src/SME.SGP.Api/Controllers/DashboardInformacoesEscolaresController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardInformacoesEscolares/ObterDashboardMatriculaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardInformacoesEscolares/IObterDashboardMatriculaUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardInformacoesEscolares/ObterDadosDashboardMatricula/ObterDadosDashboardMatriculaQuery.cs
src/SME.SGP.Aplicacao/Queries/DashboardInformacoesEscolares/ObterDadosDashboardMatricula/ObterDadosDashboardMatriculaQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoMatriculaTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoMatriculaTurma.cs
src/SME.SGP.Infra/Dtos/Grafico/Matricula/FiltroGraficoMatriculaDto.cs
src/SME.SGP.Infra/Dtos/TotalMatriculaPorDreEAnoDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#39447](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39447)

39447 - Criar endpoint de matriculas

---

src/SME.SGP.Api/Controllers/DashboardInformacoesEscolaresController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardInformacoesEscolares/ObterDashboardInformacoesEscolaresPorMatriculaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardInformacoesEscolares/ObterDashboardInformacoesEscolaresPorTurmaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardInformacoesEscolares/IObterDashboardInformacoesEscolaresPorMatriculaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardInformacoesEscolares/IObterDashboardInformacoesEscolaresPorTurmaUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDadosDashboardFrequenciaPorAno/ObterDadosDashboardFrequenciaPorAnoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDadosDashboardFrequenciaPorDre/ObterDadosDashboardFrequenciaPorDreQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDashboardFrequenciaAusenciasPorMotivo/ObterDashboardFrequenciaAusenciasPorMotivoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DashboardInformacoesEscolares/ObterDadosDashboardMatricula/ObterDadosDashboardMatriculaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DashboardInformacoesEscolares/ObterDadosDashboardTurma/ObterDadosDashboardMatriculaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DashboardInformacoesEscolares/ObterDadosDashboardTurma/ObterDadosDashboardTurmaQuery.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoMatriculaTurma.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoMatriculaTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurma.cs
src/SME.SGP.Infra/Consts/DashboardConstants.cs
src/SME.SGP.Infra/Dtos/InformacoesEscolaresPorDreEAnoDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#39440](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39440)

39440 - Informações escolares por turma

---

src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/AlterarItineranciaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/SalvarItineranciaUseCase.cs
src/SME.SGP.Aplicacao/Commands/Itinerancia/Notificacao/NotificacaoUsusarioCriadorRegistroItinerancia/NotificacaoUsuarioCriadorRegistroItineranciaCommandHandler.cs

- Não criar evento ao salvar ou alterar Registro de Itinerancia
- Ajuste no fluxo de aprovação do Workflow com ou sem alunos para criação de evento e tratamento das mensagens

Implemetado fluxo de criação de eventos no workflow

---

src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/EncerrarEncaminhamentoAEE/EncerrarEncaminhamentoAEECommandHandler.cs

[AB#40043](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40043)

Alteração da Situação de Encerrado para Indeferido

---

src/SME.SGP.Api/Controllers/ItineranciaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/ObterEventosItinerânciaPorTipoCalendarioUseCase.cs
src/SME.SGP.Aplicacao/Queries/Evento/ObterEventosItineranciaPAAI/ObterEventosItineranciaPAAIQuery.cs
src/SME.SGP.Aplicacao/Queries/Evento/ObterEventosItineranciaPAAI/ObterEventosItineranciaPAAIQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEvento.cs
src/SME.SGP.Infra/Dtos/Itinerancia/FiltroEventosItineranciaDto.cs

[AB#40040](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40040)

filtrar eventos por ue

---

src/SME.SGP.Api/Startup.cs
src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaSgp/PublicarFilaSgpCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/ConciliacaoFrequenciaTurmas/ConciliacaoFrequenciaTurmasCommandHandler.cs
src/SME.SGP.Aplicacao/SME.SGP.Aplicacao.csproj
src/SME.SGP.Infra/Politicas/PoliticaPolly.cs
src/SME.SGP.IoC/Extensions/RegistrarPolicies.cs
src/SME.SGP.IoC/SME.SGP.IoC.csproj
src/SME.SGP.Worker.Rabbbit/Startup.cs
src/SME.SGP.WorkerService/WorkerService.cs

[AB#39688](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39688)

Implementação do Polly no SGP

---

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RegistrarEncaminhamentoAEEUseCase.cs

[AB#40094](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40094)
Tratamento para não permitir que um professor que não é da turma ou gestor da escola realize o encaminhamento AEE

Tratamento permite cadastrar

---

src/SME.SGP.Api/Controllers/DashboardInformacoesEscolaresController.cs
src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoMatriculaTurma/CarregarDresConsolidacaoMatriculaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardInformacoesEscolares/ObterModalidadeAnoItineranciaProgramaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardInformacoesEscolares/IObterModalidadeAnoItineranciaProgramaUseCase.cs
src/SME.SGP.Aplicacao/Queries/ObterModalidadesAnosItineranciaPrograma/ObterModalidadesAnosItineranciaProgramaQuery.cs
src/SME.SGP.Aplicacao/Queries/ObterModalidadesAnosItineranciaPrograma/ObterModalidadesAnosItineranciaProgramaQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoMatriculaTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoMatriculaTurma.cs
src/SME.SGP.Dominio/Enumerados/AnoItinerarioPrograma.cs
src/SME.SGP.Infra/Dtos/InformacoesEscolares/ModalidadesPorAnoItineranciaProgramaDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#40123](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40123)

40123 - Endpoint de anos

---

src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterQuestoesPlanoAEEPorVersao/ObterQuestoesPlanoAEEPorVersaoQueryHandler.cs

[AB#40307](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40307) [AB#40333](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40333)

40307 - Retirar regra de não mostrar todas as opções para PAEE

---

src/SME.SGP.Aplicacao/Consultas/ConsultasBase.cs
src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Comunicados/ObterCuminicadosPaginados/ObterComunicadosPaginadosQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Usuario/ObterLoginAtual/ObterLoginAtualQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Usuario/ObterTokenAtual/ObterTokenAtualQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioLogado/ObterUsuarioLogadoQueryHandler.cs
src/SME.SGP.Aplicacao/Servicos/ServicoTokenJwt.cs
src/SME.SGP.Dados/Contexto/SgpContext.cs
src/SME.SGP.Dados/Repositorios/RepositorioBase.cs
src/SME.SGP.Dominio.Servicos/ServicoUsuario.cs
src/SME.SGP.Dominio/Entidades/Auditoria.cs
src/SME.SGP.Infra/Contexto/ContextoBase.cs
src/SME.SGP.Infra/Contexto/ContextoHttp.cs
src/SME.SGP.Infra/Interfaces/IContextoAplicacao.cs
src/SME.SGP.Infra/Interfaces/ISgpContext.cs

[AB#40345](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40345)

Adicionar o perfil do usuário de gestor ao realizar uma ação crud

---

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs

[AB#40002](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40002)
[AB#39331](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39331)

39331 Consulta de componentes da Regencia por ano da turma

---

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/GerarPendenciasFechamentoUseCase.cs
src/SME.SGP.Aplicacao/Commands/Fechamento/AtualizarSituacaoFechamentoTurmaDisciplina/AtualizarSituacaoFechamentoTurmaDisciplinaCommand.cs
src/SME.SGP.Aplicacao/Commands/Fechamento/AtualizarSituacaoFechamentoTurmaDisciplina/AtualizarSituacaoFechamentoTurmaDisciplinaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Fechamento/GerarPendenciasFechamento/GerarPendenciasFechamentoCommand.cs
src/SME.SGP.Aplicacao/Commands/Fechamento/GerarPendenciasFechamento/GerarPendenciasFechamentoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Fechamento/IncluirFilaGeracaoPendenciasFechamento/IncluirFilaGeracaoPendenciasFechamentoCommand.cs
src/SME.SGP.Aplicacao/Commands/Fechamento/IncluirFilaGeracaoPendenciasFechamento/IncluirFilaGeracaoPendenciasFechamentoCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Fechamento/IGerarPendenciasFechamentoUseCase.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplina.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoTurmaDisciplina.cs
src/SME.SGP.Dominio.Interfaces/Servicos/IServicoFechamentoTurmaDisciplina.cs
src/SME.SGP.Dominio.Interfaces/Servicos/IServicoPendenciaFechamento.cs
src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#40360](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40360)

40360 Envio da Geração de Pendencias de Fechamento para o Rabbit

---

scripts/V423__FREQUENCIA_ALUNO_TURMA_IDX.sql

[AB#40377](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40377)
[AB#39651](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39651)

40377 Indice em turma_id na frequencia_aluno

---

src/SME.SGP.Api/Controllers/FechamentoAcompanhamentoTurmasController.cs
src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterConselhoClasseConsolidadoPorTurmaBimestreUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConselhoClasse/IObterConselhoClasseConsolidadoPorTurmaBimestreUseCase.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
src/SME.SGP.Dominio/Entidades/ConselhoClasseConsolidadoTurmaAluno.cs
src/SME.SGP.Dominio/Entidades/FechamentoTurmaDisciplina.cs
src/SME.SGP.Dominio/Enumerados/StatusConselhoClasse.cs
src/SME.SGP.Dominio/Enumerados/StatusFechamento.cs
src/SME.SGP.Infra/Dtos/FechamentoAcompanhamentoTurmas/StatusTotalConselhoClasseDto.cs

[AB#36917](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/36917)

Ajustado enum e query

---

src/SME.SGP.Api/Controllers/DashboardInformacoesEscolaresController.cs
src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoFrequenciaTurma/ConsolidarFrequenciaTurmasUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoMatriculaTurma/CarregarDresConsolidacaoMatriculaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardInformacoesEscolares/ObterDashboardInformacoesEscolaresPorMatriculaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardInformacoesEscolares/ObterDashboardInformacoesEscolaresPorTurmaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardInformacoesEscolares/ObterDataConsolidacaoInformacoesEscolaresUseCase.cs
src/SME.SGP.Aplicacao/Commands/PendenciaRegistroIndividual/GerarPendenciaAusenciaRegistroIndividualTurma/GerarPendenciaAusenciaRegistroIndividualTurmaCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/DashboardInformacoesEscolares/ObterDadosDashboardMatricula/ObterDadosDashboardMatriculaQuery.cs
src/SME.SGP.Aplicacao/Queries/DashboardInformacoesEscolares/ObterDadosDashboardMatricula/ObterDadosDashboardMatriculaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DashboardInformacoesEscolares/ObterDadosDashboardTurma/ObterDadosDashboardMatriculaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DashboardInformacoesEscolares/ObterDadosDashboardTurma/ObterDadosDashboardTurmaQuery.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoMatriculaTurma.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoMatriculaTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurma.cs
src/SME.SGP.Dominio/Enumerados/AnoItinerarioPrograma.cs
src/SME.SGP.Infra/Dtos/Grafico/Matricula/FiltroGraficoMatriculaDto.cs

[AB#40139](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40139)

40139 - Ajustes queries

---

scripts/V424__AJUSTE_PENDENCIAS_NOVA_ROTA.sql
src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/GerarPendenciaValidadePlanoAEEUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/NotificarPlanosAEEExpiradosUseCase.cs
src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaAtribuirResponsavelEncaminhamentoAEE/GerarPendenciaAtribuirResponsavelEncaminhamentoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaCPEncaminhamentoAEE/GerarPendenciaCPEncaminhamentoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaPAEEEncaminhamentoAEE/GerarPendenciaPAEEEncaminhamentoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Notificacao/NotificacaoConclusaoEncaminhamentoAEE/NotificacaoConclusaoEncaminhamentoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Notificacao/NotificacaoDevolucaoEncaminhamentoAEE/NotificacaoDevolucaoEncaminhamentoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Notificacao/NotificacaoEncerramentoEncaminhamentoAEE/NotificacaoEncerramentoEncaminhamentoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/AtribuirResponsavelPlanoAEE/AtribuirResponsavelPlanoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarDevolutivaCP/CadastrarDevolutivaCPCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/EnviarNotificacaoCriacaoPlanoAEE/EnviarNotificacaoCriacaoPlanoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/EnviarNotificacaoRestruturacaoPlanoAEE/EnviarNotificacaoReestruturacaoPlanoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/NotificarEncerramentoPlanoAEE/NotificarEncerramentoPlanoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/Pendencias/GerarPendenciaCPEncerramentoPlanoAEE/GerarPendenciaCPEncerramentoPlanoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEEObservacao/NotificarObservacaoPlanoAEE/NotificarObservacaoPlanoAEECommandHandler.cs

[AB#40329](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40329) [AB#40442](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40442)

40329 - Ajuste links de pendências de  AEE

---

Jenkinsfile

* Adicionado usuário luiz_araujo
* Removido usuários everton_nogueira, alan_santos

Atualizado arquivo de jenkins

---

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommandHandler.cs

Ajuste na verificação de dias letivos para a criação de aulas automáticas, removendo uma cláusula que analisamos ser desnecessária.

Bug: 39692

---

src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs
src/SME.SGP.Dados/Contexto/SgpContext.cs
src/SME.SGP.Dados/Repositorios/RepositorioBase.cs
src/SME.SGP.Dominio/Entidades/Auditoria.cs
src/SME.SGP.Infra/Interfaces/ISgpContext.cs

[AB#40475](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40475)

fix/40475 - Correção na auditoria pelo sistema de recorrência

---

scripts/V425__FREQUENCIA_ALUNO_ID_IDX.sql
src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodo.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaAlunoDisciplinaPeriodo.cs
src/SME.SGP.Infra/Politicas/PoliticaPolly.cs
src/SME.SGP.IoC/Extensions/RegistrarPolicies.cs

40478 Ajuste exclusão de calculos de frequencia e inclusão de Polly e transação

---

src/SME.SGP.Dados/Repositorios/RepositorioBase.cs

[AB#40521](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40521)

Ajuste no perfil da auditoria.

---

src/SME.SGP.Aplicacao/Comandos/ComandosAtividadeAvaliativa.cs

[AB#40540](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40540)

Ajuste na criação de atividade avaliativa

---

src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs

[AB#40466](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40466)

40466 - trocas de static para const FilasRabbit

---

src/SME.SGP.Infra/Enumerados/Permissao.cs

[AB#40566](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40566)

Ajuste permissionamento

---

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaFechamentoComponenteUseCase.cs

[AB#40569](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40569)

Ajuste sincronização

---

src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs

[AB#40590](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40590)

Inclusão de filtro por modalidade

---

src/SME.SGP.Aplicacao/CasosDeUso/DashboardInformacoesEscolares/ObterModalidadeAnoItineranciaProgramaUseCase.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoMatriculaTurma.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
src/SME.SGP.Dominio/Enumerados/AnoItinerarioPrograma.cs

[AB#40513](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40513) [AB#40591](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40591)

40513 - ajuste ordenação endpoint de anos

---

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RegistrarEncaminhamentoAEEUseCase.cs

[AB#40500](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40500)
Retirada de tratamento para podeEditar e somenter profressor ou gestor da turma

Ajuste regra de permite edição Encaminhamento

---

src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdQuery/ObterPendenciasAulaPorAulaIdQueryHandler.cs

[AB#40567](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40567)

Ajuste busca atividade avaliativa

---

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ObterFechamentoConsolidadoPorTurmaBimestreUseCase.cs

[AB#40625](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40625)

Ajustes envio de status endpoint consolidado fechamento

---

src/SME.SGP.Dados/Repositorios/RepositorioAula.cs

[AB#40633](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40633)

40633 - removido a checagem do rf do professor

---

src/SME.SGP.Aplicacao/Queries/DashboardInformacoesEscolares/ObterDadosDashboardMatricula/ObterDadosDashboardMatriculaQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoMatriculaTurma.cs
src/SME.SGP.Infra/Dtos/InformacoesEscolaresPorDreEAnoDto.cs

[AB#40669](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40669)

40669 - Filtro por turmas

---

scripts/V427__AJUSTE_CALENDARIO_AULAS_2021.sql

[AB#40668](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40668)

40668 Alteração do calendário das aulas em calendário incorreto;

---

src/SME.SGP.Aplicacao/Integracoes/ServicoPerfil.cs
src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAbrangencia.cs

Ajuste na definição de prioridade para usuários com perfil CJ infantil, caso o usuário tenha turma somente para CJ Infantil define esse como prioritário.

Bug: 40684

---

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RegistrarEncaminhamentoAEEUseCase.cs

[AB#40782](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40782)

Tratamento para validar se já existe um EncaminhamentoAEE para o Aluno

---

src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoMatriculaTurma.cs

[AB#40797](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40797) [AB#40799](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40799)

40797 - Ajuste query anos da modalide EJA

---

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RegistrarEncaminhamentoAEEUseCase.cs
src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs

[AB#40782](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40782)

Ajuste no tratamento para identificar se ja existe encaminhamento

---

scripts/V429__CRIACAO_TABELA_FREQUENCIA_NOVA_ESTRUTURA.sql
src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
src/SME.SGP.Dados/Mapeamentos/RegistroFrequenciaAlunoMap.cs
src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAluno.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroFrequenciaAluno.cs
src/SME.SGP.Dominio/Entidades/RegistroFrequenciaAluno.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#40278](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40278)

40278 - Mapeamento

---

src/SME.SGP.Aplicacao/CasosDeUso/Aula/AlterarAulaFrequenciaTratarUseCase.cs
src/SME.SGP.Aplicacao/Commands/Aulas/ExcluirAulaUnica/ExcluirAulaUnicaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/RecalcularFrequenciaPorTurma/RecalcularFrequenciaPorTurmaCommand.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/RecalcularFrequenciaPorTurma/RecalcularFrequenciaPorTurmaCommandHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAula.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAula.cs
src/SME.SGP.Infra/Dtos/PeriodoEscolar/PeriodoEscolarInicioFimDto.cs

[AB#40849](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40849) 
[AB#39688](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39688)

40849 - Não consultar API EOL no calculo frequência ao alterar ou excluir aulas

---

src/SME.SGP.Aplicacao/CasosDeUso/Aula/InserirFrequenciaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterTiposFrequenciasUseCase.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/ExcluirPreDefinicaoFrequencia/ExcluirPreDefinicaoFrequenciaCommand.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/ExcluirPreDefinicaoFrequencia/ExcluirPreDefinicaoFrequenciaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/InserirRegistrosFrequenciasAlunos/InserirRegistrosFrequenciasAlunosCommand.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/InserirRegistrosFrequenciasAlunos/InserirRegistrosFrequenciasAlunosCommandHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaPreDefinida.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaPreDefinida.cs
src/SME.SGP.Infra/Dtos/Funcionario/TipoFrequenciaDto.cs

[AB#40284](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40284)

40284 - Criado nova persistência para as notas predefinidas

---

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs

[AB#40858](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40858)

40858 Removido bulk insert do calculo de frequencia

---

src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplina.cs

Ajuste na consulta para obter as notas do bimestre incluindo os alias dos campos referente a auditoria.

Bug: 40588

---

src/SME.SGP.Aplicacao/CasosDeUso/Aula/InserirFrequenciaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs

[AB#40926](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40926)

40926 - ajuste regra

---

src/SME.SGP.Api/Controllers/FechamentoAcompanhamentoTurmasController.cs
src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ObterComponentesFechamentoConsolidadoPorTurmaBimestreUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/FechamentoAcompanhamentoTurmas/IObterComponentesFechamentoConsolidadoPorTurmaBimestreUseCase.cs
src/SME.SGP.Aplicacao/Queries/FechamentoAcompanhamento/ObterComponentesFechamentoConsolidadoPorTurmaBimestre/ObterComponentesFechamentoConsolidadoPorTurmaBimestreQuery.cs
src/SME.SGP.Aplicacao/Queries/FechamentoAcompanhamento/ObterComponentesFechamentoConsolidadoPorTurmaBimestre/ObterComponentesFechamentoConsolidadoPorTurmaBimestreQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoConsolidado.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoConsolidado.cs
src/SME.SGP.Infra/Dtos/FechamentoAcompanhamentoTurmas/ConsolidacaoTurmaComponenteCurricularDto.cs
src/SME.SGP.Infra/Dtos/FechamentoAcompanhamentoTurmas/FiltroComponentesFechamentoConsolidadoDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#40800](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40800)

feature/40800 - Listar componentes curriculares da turma

---

src/SME.SGP.Aplicacao/Consultas/ConsultasNotasConceitos.cs

[AB#40891](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40891)

40891 Corrigido Auditoria de Alteração de Nota Final

---

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodo.cs
src/SME.SGP.Infra/Dtos/ConselhoClasseComponenteFrequenciaDto.cs
src/SME.SGP.Infra/Dtos/IndicativoFrequenciaDto.cs

[AB#40980](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40980)

40980 - ajustes

---

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RegistrarEncaminhamentoAEEUseCase.cs

[AB#40956](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40956)

Gerar pendência CP ao Enviar EncaminhamentoAEE

---

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterTiposFrequenciasUseCase.cs

[AB#41132](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41132) [AB#41133](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41133)

41132 - Ajuste valores default tipo de frequencia

---

scripts/V433__SCRIPT_MIGRACAO_FREQUENCIA_REGISTROS_EXISTENTES.sql

[AB#40278](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/40278)

40278 - Script migração de dados existentes em ausencias

---

src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/NotificacaoAlunosFaltosos/ExecutaNotificacaoAlunosFaltososUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/NotificacaoAlunosFaltosos/NotificarAlunosFaltososUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/NotificacaoAlunosFaltosos/IExecutaNotificacaoAlunosFaltososUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/NotificacaoAlunosFaltosos/INotificarAlunosFaltososUseCase.cs
src/SME.SGP.Dados/Repositorios/RepositorioFrequencia.cs
src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
src/SME.SGP.Infra/Dtos/AlunosFaltososDto.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#41275](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41275)

37947 Envio da Notificação de Alunos Faltosos para o Rabbit

---

src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs
src/SME.SGP.Infra/Dtos/FechamentoAcompanhamentoTurmas/ConsolidacaoTurmaComponenteCurricularDto.cs

[AB#41460](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41460)

Ajuste no html das pendências

---

Jenkinsfile

atualizações de CI para testes Postman / Newman exibindo cli e continuação de pipeline mesmo em falha

Ebufaino patch 11

---

src/SME.SGP.Api/Controllers/FrequenciaController.cs
src/SME.SGP.Api/Controllers/PlanoAulaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/InserirFrequenciaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/PlanoAula/Salvar/SalvarPlanoAulaUseCase.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/PersistirRegistroFrequencia/PersistirRegistroFrequenciaCommand.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/PersistirRegistroFrequencia/PersistirRegistroFrequenciaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommand.cs
src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasNotasConceitos.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/IInserirFrequenciaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAula/Salvar/ISalvarPlanoAulaUseCase.cs

[AB#41421](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41421)

back fix/41421 

---

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs

Ajuste na rotina de obtenção das notas, onde ao listar as disciplinas relacionadas a regências desconsidera as do tipo território do saber.

Bug: 40935

---

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ObterTurmasFechamentoAcompanhamentoUseCase.cs
src/SME.SGP.Aplicacao/Queries/FechamentoAcompanhamentoTurmas/ObterTurmasFechamentoAcompanhamento/ObterTurmasFechamentoAcompanhamentoQuery.cs
src/SME.SGP.Aplicacao/Queries/FechamentoAcompanhamentoTurmas/ObterTurmasFechamentoAcompanhamento/ObterTurmasFechamentoAcompanhamentoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidado.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoConsolidado.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurma.cs
src/SME.SGP.Infra/Dtos/FechamentoAcompanhamentoTurmas/FiltroAcompanhamentoFechamentoTurmasDto.cs

[AB#41536](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41536)

Ajustes busca contem status informado

---

src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs

[AB#41545](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41545)

Adicionado justificativa do professor

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

[AB#41544](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41544)

Ajuste consolidação fechamento

---

src/SME.SGP.Aplicacao/Commands/Itinerancia/Notificacao/NotificacaoSalvarItineranciaAlunos/NotificacaoSalvarItineranciaAlunosCommandHandler.cs
src/SME.SGP.Dominio.Interfaces/Servicos/IServicoNotificacao.cs
src/SME.SGP.Dominio.Servicos/ServicoNotificacao.cs
src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs

AB#41321 [AB#41629](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41629)

ajuste workflow de aprovação para notificações com ação

---

src/SME.SGP.Api/Controllers/DevolutivaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Devolutiva/ObterPeriodoDeDiasDevolutivaUseCase.cs
src/SME.SGP.Aplicacao/Commands/ConsolidacaoDevolutivas/LimparConsolidacaoDevolutivas/LimparConsolidacaoDevolutivasCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Devolutiva/IObterPeriodoDeDiasDevolutivaUseCase.cs
src/SME.SGP.Infra/Dtos/Devolutiva/FiltroTipoParametroAnoDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#39407](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/39407)

Endpoint Obter Periodo de dias Devolutiva

---

src/SME.SGP.Api/Controllers/FiltroRelatorioController.cs
src/SME.SGP.Aplicacao/Commands/PlanoAula/MigrarPlanoAula/MigrarPlanoAulaCommandHandler.cs

Bug: 40594

---

src/SME.SGP.Aplicacao/Queries/DiasLetivos/ObterDiasPorPeriodosEscolaresComEventosLetivosENaoLetivos/ObterDiasPorPeriodosEscolaresComEventosLetivosENaoLetivosQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEvento.cs

Ajuste na funcionalidade de criação de aula do infantil considerando restritamente os eventos com letivos 1 e 2.

Bug: 41649

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

Ajuste na funcionalidade de salvar notas para permitir a inserção de notas vazias.

Bug: 40937

---

src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/ExecutaPendenciaAulaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaUseCase.cs
src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAtividadeAvaliativa/ObterPendenciasAtividadeAvaliativaQuery.cs
src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAtividadeAvaliativa/ObterPendenciasAtividadeAvaliativaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAulasPorTipo/ObterPendenciasAulasPorTipoQuery.cs
src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAulasPorTipo/ObterPendenciasAulasPorTipoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAula.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAula.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAula.cs
src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs
src/SME.SGP.Dominio/Entidades/Aula.cs

Ajuste nas rotinas de criação e e conclusão de pendência, desconsiderando disciplinas que não registram frequência. Seja pela flag do banco ou regra de tecnologia de aprendizagem com EJA.

Bug: 40911

---

src/SME.SGP.Aplicacao/Consultas/ConsultasNotasConceitos.cs

Ajuste na listagem de alunos para notas, considerando a data da matricula dentro do período do bimestre.

Bug: 40914

---

src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs
src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs

Ajuste na funcionalidade de obter a lista de frequência considerando a data da matricula do aluno para determinar a sua visibilidade no dia selecionado.

Bug: 40915

---

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs

Ajuste na listagem de disciplinas para o componente curricular com regência.

Bug: 39588

---

src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoDevolutivas/ConsolidarDevolutivasPorTurmaInfantilUseCase.cs

correção na formatação da data de última execução

formatação da data

---

src/SME.SGP.Aplicacao/CasosDeUso/Aula/CriacaoAutomatica/CarregarUesTurmasRegenciaAulaAutomaticaUseCase.cs
src/SME.SGP.Aplicacao/Queries/AulaPrevista/ObterDadosComponenteCurricularTurmaPorUeEAnoLetivo/ObterDadosComponenteCurricularTurmaPorUeEAnoLetivoQuery.cs
src/SME.SGP.Aplicacao/Queries/AulaPrevista/ObterDadosComponenteCurricularTurmaPorUeEAnoLetivo/ObterDadosComponenteCurricularTurmaPorUeEAnoLetivoQueryHandler.cs

[AB#42137](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42137)

42137 - ajustes componentes curriculares

---

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ObterTurmasFechamentoAcompanhamentoUseCase.cs
src/SME.SGP.Aplicacao/Queries/FechamentoAcompanhamentoTurmas/ObterTurmasFechamentoAcompanhamento/ObterTurmasFechamentoAcompanhamentoQuery.cs
src/SME.SGP.Aplicacao/Queries/FechamentoAcompanhamentoTurmas/ObterTurmasFechamentoAcompanhamento/ObterTurmasFechamentoAcompanhamentoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurma.cs
src/SME.SGP.Infra/Dtos/FechamentoAcompanhamentoTurmas/FiltroAcompanhamentoFechamentoTurmasDto.cs

[AB#42050](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42050)

42050 - ajustado busca dos fechamentos

---

src/SME.SGP.Api/Controllers/AbrangenciaController.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs
src/SME.SGP.Infra/Dtos/AbrangenciaTurmaRetorno.cs

[AB#42142](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42142)

Correção de filtro de turma retornando nulo para historico 

---

src/SME.SGP.Aplicacao/CasosDeUso/Aula/CriacaoAutomatica/CarregarUesTurmasRegenciaAulaAutomaticaUseCase.cs
src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasAutomaticamente/CriarAulasRegenciaAutomaticamenteCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/DiasLetivos/ObterDiasPorPeriodosEscolaresComEventosLetivosENaoLetivos/ObterDiasPorPeriodosEscolaresComEventosLetivosENaoLetivosQuery.cs
src/SME.SGP.Aplicacao/Queries/DiasLetivos/ObterDiasPorPeriodosEscolaresComEventosLetivosENaoLetivos/ObterDiasPorPeriodosEscolaresComEventosLetivosENaoLetivosQueryHandler.cs

[AB#42154](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42154) [AB#42155](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42155)

42154 - ajuste pra não incluir dias letivos indevidos

---

scripts/V450__CRIACAO_CONSOLIDACAO_REGISTRO_INDIVIDUAL_MEDIA.sql
src/SME.SGP.Api/Controllers/DashboardRegistroIndividualController.cs
src/SME.SGP.Dados/Mapeamentos/ConsolidacaoRegistroIndividualMediaMap.cs
src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoRegistroIndividualMedia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/RepositorioConsolidacaoRegistroIndividualMedia.cs
src/SME.SGP.Dominio/Entidades/ConsolidacaoRegistroIndividualMedia.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#41200](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41200)

41200 - Modelagem consolidacao registro individual média

---

src/SME.SGP.Api/Controllers/DashboardRegistroIndividualController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardRegistroIndividual/ObterDashboardInformacoesEscolaresPorMatriculaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardRegistroIndividual/IObterQuantidadeRegistrosIndividuaisPorAnoTurmaUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardRegistroIndividual/ObterQuantidadeRegistrosIndividuaisPorAnoTurma/ObterQuantidadeRegistrosIndividuaisPorAnoTurmaQuery.cs
src/SME.SGP.Aplicacao/Queries/DashboardRegistroIndividual/ObterQuantidadeRegistrosIndividuaisPorAnoTurma/ObterQuantidadeRegistrosIndividuaisPorAnoTurmaQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioRegistroIndividual.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroIndividual.cs
src/SME.SGP.Infra/Consts/DashboardConstants.cs
src/SME.SGP.Infra/Dtos/Grafico/RegistroIndividual/FiltroDasboardRegistroIndividualDTO.cs
src/SME.SGP.Infra/Dtos/Grafico/RegistroIndividual/GraficoTotalRegistrosIndividuaisDTO.cs
src/SME.SGP.Infra/Dtos/Grafico/RegistroIndividual/QuantidadeRegistrosIndividuaisPorAnoTurmaDTO.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#41197](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41197)

endpoint para retornar a quantidade de registros individuais

---

scripts/V451__PARAMETRO_DATA_ULTIMA_ATUALIZACAO_MEDIA_REGISTRO_INDIVIDUAL.sql
src/SME.SGP.Api/Controllers/DashboardRegistroIndividualController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardRegistroIndividual/ObterUltimaConsolidacaoMediaRegistrosIndividuaisUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardRegistroIndividual/IObterUltimaConsolidacaoMediaRegistrosIndividuaisUseCase.cs
src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#41202](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41202)

Endpoint para obter a última consolidação

---

scripts/V452__CRIACAO_PERCURSO_INDIVIDUAL.sql
src/SME.SGP.Dados/Mapeamentos/AcompanhamentoAlunoSemestreMap.cs
src/SME.SGP.Dominio/Entidades/AcompanhamentoAlunoSemestre.cs

[AB#42067](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42067)

42067 Criado Percurso Individual do estudante

---

src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs

Ajuste na listagem de alunos no fechamento considerando o status de concluído para permitir ou não a anotação.

Bug: 14770

---

scripts/V453__CRIACAO_PARAMETRO_IMAGENS_PERCURSO_TURMA.sql
src/SME.SGP.Api/Controllers/AcompanhamentoTurmaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoTurma/ObterParametroQuantidadeImagensPercursoColetivoTurmaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AcompanhamentoTurma/IObterParametroQuantidadeImagensPercursoColetivoTurmaUseCase.cs
src/SME.SGP.Aplicacao/SME.SGP.Aplicacao.csproj
src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs

[AB#42068](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42068)

42068 Parametro Quantidade de Imagens permitidas no percurso comum da turma

---

scripts/V451__PARAMETRO_DATA_ULTIMA_ATUALIZACAO_MEDIA_REGISTRO_INDIVIDUAL.sql
scripts/V454__PARAMETRO_DIAS_SEM_REGISTRO_INDIVIDUAL.sql
src/SME.SGP.Api/Controllers/DashboardRegistroIndividualController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardRegistroIndividual/ObterDashboardQuantidadeDeAlunosSemRegistroPorPeriodoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardRegistroIndividual/ObterParametroDiasSemRegistroIndividualUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardRegistroIndividual/IObterParametroDiasSemRegistroIndividualUseCase.cs
src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#41201](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41201)

41201 - parametro quantidade de dias sem registro individual

---

src/SME.SGP.Aplicacao/CasosDeUso/DashboardRegistroIndividual/ObterQuantidadeRegistrosIndividuaisPorAnoTurmaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardRegistroIndividual/IObterQuantidadeRegistrosIndividuaisPorAnoTurmaUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardRegistroIndividual/ObterQuantidadeRegistrosIndividuaisPorAnoTurma/ObterQuantidadeRegistrosIndividuaisPorAnoTurmaQuery.cs
src/SME.SGP.Aplicacao/Queries/DashboardRegistroIndividual/ObterQuantidadeRegistrosIndividuaisPorAnoTurma/ObterQuantidadeRegistrosIndividuaisPorAnoTurmaQueryHandler.cs
src/SME.SGP.Infra/Consts/DashboardConstants.cs
src/SME.SGP.Infra/Dtos/Grafico/RegistroIndividual/GraficoTotalRegistrosIndividuaisDTO.cs

[AB#42527](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42527)

42527 - Ajuste endpoint totais

---

src/SME.SGP.Api/Controllers/AcompanhamentoAlunoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ObterAcompanhamentoAlunoUseCase.cs
src/SME.SGP.Aplicacao/Queries/RegistroIndividual/ObterDescricoesRegistrosIndividuaisPorPeriodo/ObterDescricoesRegistrosIndividuaisPorPeriodoQuery.cs
src/SME.SGP.Aplicacao/Queries/RegistroIndividual/ObterDescricoesRegistrosIndividuaisPorPeriodo/ObterDescricoesRegistrosIndividuaisPorPeriodoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioRegistroIndividual.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroIndividual.cs
src/SME.SGP.Infra/Dtos/AcompanhamentoAluno/AcompanhamentoAlunoTurmaSemestreDto.cs
src/SME.SGP.Infra/Dtos/AcompanhamentoAluno/FiltroAcompanhamentoTurmaAlunoSemestreDto.cs
src/SME.SGP.Infra/Dtos/RegistroIndividual/RegistroIndividualResumoDto.cs

[AB#42069](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42069)

42069 Carga do Percurso Individual do Aluno

---

src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
src/SME.SGP.Infra/Dtos/Devolutiva/DiarioBordoDevolutivaDto.cs
src/SME.SGP.Infra/Utilitarios/UtilRegex.cs

[AB#42073](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42073)

42073 Carregar Planejamento x Reflexoes juntos na tela

---

src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs
src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoMediaRegistrosIndividuais/ConsolidacaoMediaRegistrosIndividuaisTurmaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoMediaRegistrosIndividuais/ConsolidacaoMediaRegistrosIndividuaisUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoMediaRegistrosIndividuais/ExecutarSincronizacaoMediaRegistrosIndividuaisSyncUseCase.cs
src/SME.SGP.Aplicacao/Commands/ConsolidacaoRegistroIndividual/LimparConsolidacaoRegistroIndividual/LimparConsolidacaoMediaRegistroIndividualCommand.cs
src/SME.SGP.Aplicacao/Commands/ConsolidacaoRegistroIndividual/LimparConsolidacaoRegistroIndividual/LimparConsolidacaoMediaRegistroIndividualCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/ConsolidacaoRegistroIndividual/RegistraConsolidacaoMediaRegistroIndividual/RegistraConsolidacaoMediaRegistroIndividualCommand.cs
src/SME.SGP.Aplicacao/Commands/ConsolidacaoRegistroIndividual/RegistraConsolidacaoMediaRegistroIndividual/RegistraConsolidacaoMediaRegistroIndividualCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConsolidacaoMediaRegistrosIndividuais/IConsolidacaoMediaRegistrosIndividuaisTurmaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConsolidacaoMediaRegistrosIndividuais/IConsolidacaoMediaRegistrosIndividuaisUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConsolidacaoMediaRegistrosIndividuais/IExecutarSincronizacaoMediaRegistrosIndividuaisSyncUseCase.cs
src/SME.SGP.Aplicacao/Queries/RegistroIndividual/ObterAlunosInfantilComRegistrosIndividuaisPorTurmaAno/ObterAlunosInfantilComRegistrosIndividuaisPorTurmaAnoQuery.cs
src/SME.SGP.Aplicacao/Queries/RegistroIndividual/ObterAlunosInfantilComRegistrosIndividuaisPorTurmaAno/ObterAlunosInfantilComRegistrosIndividuaisPorTurmaAnoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/RegistroIndividual/ObterRegistrosIndividuaisPorTurmaAluno/ObterRegistrosIndividuaisPorTurmaAlunoQuery.cs
src/SME.SGP.Aplicacao/Queries/RegistroIndividual/ObterRegistrosIndividuaisPorTurmaAluno/ObterRegistrosIndividuaisPorTurmaAlunoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/RegistroIndividual/ObterTurmasComRegistrosIndividuaisPorModalidadeEAno/ObterTurmasComRegistrosIndividuaisPorModalidadeEAnoQuery.cs
src/SME.SGP.Aplicacao/Queries/RegistroIndividual/ObterTurmasComRegistrosIndividuaisPorModalidadeEAno/ObterTurmasComRegistrosIndividuaisPorModalidadeEAnoQueryHandler.cs
src/SME.SGP.Dados/Mapeamentos/ConsolidacaoRegistroIndividualMediaMap.cs
src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoRegistroIndividualMedia.cs
src/SME.SGP.Dados/Repositorios/RepositorioRegistroIndividual.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoRegistroIndividualMedia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroIndividual.cs
src/SME.SGP.Infra/Dtos/ConsolidacaoRegistrosIndividuais/FiltroMediaRegistroIndividualTurmaDTO.cs
src/SME.SGP.Infra/Dtos/ConsolidacaoRegistrosIndividuais/RegistroIndividualAlunoDTO.cs
src/SME.SGP.Infra/Dtos/ConsolidacaoRegistrosIndividuais/RegistroIndividualDTO.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#41199](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/41199)

Criação de Worker para Consolidar Media de Registros Individuais

---

src/SME.SGP.Dados/Repositorios/RepositorioRegistroIndividual.cs

[AB#42658](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42658)

Correção na descrição da turma

---

src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoMediaRegistrosIndividuais/ConsolidacaoMediaRegistrosIndividuaisUseCase.cs

[AB#42680](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42680)

Correção n o cálculo da média geral por turma

---

src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Comunicados/ObterComunicadosPaginados/ObterComunicadosPaginadosEscolaAquiUseCase.cs
src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Comunicados/ObterCuminicadosPaginados/ObterComunicadosPaginadosQuery.cs
src/SME.SGP.Aplicacao/Queries/Usuario/EscolaAqui/Comunicados/ObterCuminicadosPaginados/ObterComunicadosPaginadosQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs
src/SME.SGP.Infra/Dtos/ComunicadoDto.cs
src/SME.SGP.Infra/Dtos/FiltroComunicadoDto.cs

Feature/42617 - Remoção de grupos tela de comunicados

---

scripts/V464__MURAL_AVISOS_CREATE.sql
src/SME.SGP.Dados/Mapeamentos/AvisoMap.cs
src/SME.SGP.Dados/Repositorios/RepositorioAviso.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAviso.cs
src/SME.SGP.Dominio/Entidades/Aviso.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs

[AB#42880](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42880)

42880 Modelagem Mural de Avisos

---

src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs
src/SME.SGP.Aplicacao/CasosDeUso/Avisos/ImportarAvisoDoMuralGsaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/RotasAgendamentoSync/RotasAgendamentoSyncUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/RotasAgendamentoSync/RotasAgendamentoTratarUseCase.cs
src/SME.SGP.Aplicacao/Commands/Avisos/ImportarAvisoDoMuralGsa/ImportarAvisoDoMuralGsaCommand.cs
src/SME.SGP.Aplicacao/Commands/Avisos/ImportarAvisoDoMuralGsa/ImportarAvisoDoMuralGsaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Avisos/IncluirAvisoGsaNoMural/SalvarAvisoGsaNoMuralCommand.cs
src/SME.SGP.Aplicacao/Commands/Avisos/IncluirAvisoGsaNoMural/SalvarAvisoGsaNoMuralCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Avisos/IImportarAvisoDoMuralGsaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/RotasAgendamentoSync/IRotasAgendamentoSyncUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/RotasAgendamentoSync/IRotasAgendamentoTratarUseCase.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterAulaPorCodigoTurmaComponenteEData/ObterAulaPorCodigoTurmaComponenteEDataQuery.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterAulaPorCodigoTurmaComponenteEData/ObterAulaPorCodigoTurmaComponenteEDataQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAula.cs
src/SME.SGP.Dados/Repositorios/RepositorioAviso.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAula.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAviso.cs
src/SME.SGP.Infra/Dtos/Aviso/AvisoMuralGsaDto.cs
src/SME.SGP.Infra/Dtos/RotasAgendamentoSync/MensagemAgendamentoSyncDto.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgpAgendamento.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

- Worker importação Mural de Avisos
- Worker para execução rabbit Agendado
[AB#42881](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42881)

42881 Worker importação Mural de Avisos

---

scripts manutencao/42171 - Extração de Frequencia - Estudantes no presencial/1-Alunos Presentes por Dia.sql
scripts manutencao/42171 - Extração de Frequencia - Estudantes no presencial/2-Alunos Faltosos por Bimestre.sql
scripts manutencao/42171 - Extração de Frequencia - Estudantes no presencial/3-Frequencia Alunos por Bimestre.sql
scripts manutencao/42171 - Extração de Frequencia - Estudantes no presencial/4_1-Participação turmas.sql
scripts manutencao/42171 - Extração de Frequencia - Estudantes no presencial/4_2-Participação turmas.sql
scripts manutencao/42171 - Extração de Frequencia - Estudantes no presencial/4_3-Participação turmas.sql
scripts manutencao/42171 - Extração de Frequencia - Estudantes no presencial/5-PresentesxAusentesPorUE.sql

[AB#42171](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42171)

42171 Scripts de Extração de dados da Frequencia

---

src/SME.SGP.Api/Controllers/DashboardFrequenciaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterFiltroSemanaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFrequencia/IObterFiltroSemanaUseCase.cs
src/SME.SGP.Infra/Dtos/DashBboardFrequencia/FiltroSemanaDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#43568](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43568)

Criado endpoint para listar as datas da semana

---

scripts/V466__PARAMETRO_ATIVIDADE_AVALIATIVA.sql
src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs

[AB#42904](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42904)

42904 criando paramentros de atividades avaliativas.

---

scripts/V466__PARAMETRO_ATIVIDADE_AVALIATIVA.sql
scripts/V467__ATIVIDADE_AVALIATIVA_CLASSROOM_ID.sql
src/SME.SGP.Aplicacao/CasosDeUso/AtividadeAvaliativa/ImportarAtividadesGsaUseCase.cs
src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativa/ImportarAtividadeGsa/ImportarAtividadeGsaCommand.cs
src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativa/ImportarAtividadeGsa/ImportarAtividadeGsaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativa/SalvarAtividadeAvaliativaGsa/SalvarAtividadeAvaliativaGsaCommand.cs
src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativa/SalvarAtividadeAvaliativaGsa/SalvarAtividadeAvaliativaGsaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativaDisciplina/SalvarAtividadeAvaliativaDisciplina/SalvarAtividadeAvaliativaDisciplinaCommand.cs
src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativaDisciplina/SalvarAtividadeAvaliativaDisciplina/SalvarAtividadeAvaliativaDisciplinaCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AtividadeAvaliativa/IImportarAtividadesGsaUseCase.cs
src/SME.SGP.Aplicacao/Queries/TipoAvaliacao/ObterTipoAvaliacaoPorCodigo/ObterTipoAvaliacaoPorCodigoQuery.cs
src/SME.SGP.Aplicacao/Queries/TipoAvaliacao/ObterTipoAvaliacaoPorCodigo/ObterTipoAvaliacaoPorCodigoQueryHandler.cs
src/SME.SGP.Dados/Mapeamentos/AtividadeAvaliativaMap.cs
src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs
src/SME.SGP.Dados/Repositorios/RepositorioTipoAvaliacao.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtividadeAvaliativa.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTipoAvaliacao.cs
src/SME.SGP.Dominio/Entidades/AtividadeAvaliativa.cs
src/SME.SGP.Dominio/Entidades/AtividadeAvaliativaDisciplina.cs
src/SME.SGP.Dominio/Enumerados/TipoAvaliacaoCodigo.cs
src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
src/SME.SGP.Infra/Dtos/AtividadeAvaliativa/AtividadeGsaDto.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgpAgendamento.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#42910](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42910)

42910 Worker importação atividades GSA

---

src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasFrequencia.cs
src/SME.SGP.Dominio.Servicos/ServicoCalculoParecerConclusivo.cs

[AB#43490](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43490)

Apresentar em branco quando não existe frenquencia global do aluno 

---

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterPeriodosParaConsultaNotasUseCase.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDia/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDiaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterPeriodoCalendarioBimestrePorAnoLetivoModalidade/ObterPeriodoCalendarioBimestrePorAnoLetivoModalidadeQuery.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterPeriodoCalendarioBimestrePorAnoLetivoModalidade/ObterPeriodoCalendarioBimestrePorAnoLetivoModalidadeQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioTipoCalendario.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTipoCalendario.cs
src/SME.SGP.Infra/Dtos/Notas/ObterPeriodosParaConsultaNotasFiltroDto.cs

[AB#43468](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43468) [AB#43696](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43696)

Fix:43468 - [Back] Ajuste na busca de atividades avaliativas e notas para EJA

---

src/SME.SGP.Api/Controllers/DashboardCompensacaoAusenciaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardCompensacaoAusencia/ObterDadosDashboardTotalAtividadesCompensacaoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardCompensacaoAusencia/IObterDadosDashboardTotalAtividadesCompensacaoUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardCompensacaoAusencia/ObterDadosDashboardTotalAtividadesCompensacao/ObterDadosDashboardTotalAtividadesCompensacaoQuery.cs
src/SME.SGP.Aplicacao/Queries/DashboardCompensacaoAusencia/ObterDadosDashboardTotalAtividadesCompensacao/ObterDadosDashboardTotalAtividadesCompensacaoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusencia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusencia.cs
src/SME.SGP.Infra/Dtos/DashboardCompensacaoAusencia/TotalCompensacaoAusenciaDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#43412](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43412)

Criado endpoint para obter as atividades compensadas

---

src/SME.SGP.Dados/Repositorios/RepositorioTipoCalendario.cs

[AB#43468](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43468)

ajuste considerar data final

---

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

telas de fechamento , notas, conselho de classe e acompanhamento de frequência.

Alterações ao carregar frequências

---

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/FaltasFrequencia/GerarRelatorioFaltasFrequenciaUseCase.cs
src/SME.SGP.Aplicacao/Commands/Notificacao/NotificaFrequenciaPeriodoUe/NotificaFrequenciaPeriodoUeCommandHandler.cs
src/SME.SGP.Dominio/Enumerados/TipoRelatorioFaltasFrequencia.cs
src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioFaltasFrequenciaDto.cs
src/SME.SGP.Infra/Enumerados/Permissao.cs

[AB#43473](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43473)

Alteração para nova chamada de relátorio

---

src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs

[AB#43918](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43918)

Retirando alunos com frequencia 100% da compesação de ausencia

---

src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterDadosDashboardFrequenciaPorAnoTurmaUseCase.cs
src/SME.SGP.Infra/Dtos/DashBboardFrequencia/FrequenciaAlunoDashboardDto.cs
src/SME.SGP.Infra/Dtos/DashBboardFrequencia/TotalFrequenciaEAulasPorPeriodoDto.cs

[AB#43937](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43937)

Correção para o filtor todos

---

src/SME.SGP.Aplicacao/Consultas/ConsultaAtividadeAvaliativa.cs
src/SME.SGP.Dominio/Entidades/AtividadeAvaliativa.cs
src/SME.SGP.Infra/Dtos/AtividadeAvaliativaCompletaDto.cs

[AB#44054](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44054)

44054 Incluso atributo Importado no retorno da atividade avaliativa

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs
src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAluno.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNota.cs
src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs

[AB#43954](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43954)

Fix:43954 - [Back] rel r2 - ajuste componentes sem lançamento de notas

---

scripts/V463__CRIACAO_INDICE_CODIGO_ALUNO_CONSELHO_CLASSE_ALUNO.sql

Script para criação do indice de código de aluno da tabela conselho de classe aluno, para otimização de consultas relativas.
[AB#43043](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43043)

Fix:43043 - [Back] - Master

---

src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs

[AB#43918](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43918)

fix/43918 master Compensação de ausência - Alunos com quantidade de faltas negativa

---

src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioFrequenciaDto.cs

Alterado CodigoTurma para List

---

scripts/V470__AJUSTE_REMOVER_PENDENCIAS_FECHAMENTO_INDEVIDAS_EJA.sql
src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs

Ajuste feito para não considerar como "registraFrequencia" os componentes curriculares 1060 e 1061 quando a turma for EJA

Fix:42148 [Back] rel r2

---

scripts/V463__CRIACAO_INDICE_CODIGO_ALUNO_CONSELHO_CLASSE_ALUNO.sql

Script para criação do indice de código de aluno da tabela conselho de classe aluno, para otimização de consultas relativas.
[AB#43043](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43043)

Bug: 43043 [Back] rel

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs
src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAluno.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNota.cs
src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs

[AB#43954](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/43954)

Fix:43954 [Back] rel

---

src/SME.SGP.Api/Controllers/MuralAvisosController.cs
src/SME.SGP.Aplicacao/CasosDeUso/MuralAviso/AlterarAvisoMuralUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/MuralAviso/ObterMuralAvisosUseCase.cs
src/SME.SGP.Aplicacao/Commands/Avisos/AlterarAvisoDoMural/AlterarAvisoDoMuralCommand.cs
src/SME.SGP.Aplicacao/Commands/Avisos/AlterarAvisoDoMural/AlterarAvisoDoMuralCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/MuralAviso/IAlterarAvisoMuralUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/MuralAviso/IObterMuralAvisosUseCase.cs
src/SME.SGP.Dados/Repositorios/RepositorioAviso.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAviso.cs
src/SME.SGP.Infra/Dtos/MuralAviso/MensagemAvisoDto.cs
src/SME.SGP.Infra/Dtos/MuralAviso/MuralAvisosRetornoDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#44146](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44146)

44146 Alteração de Avisos do Mural

---

scripts/V470__AJUSTE_REMOVER_PENDENCIAS_FECHAMENTO_INDEVIDAS_EJA.sql
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMes/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesQueryHandler.cs

Fix:42148 rel r2 - 2

---

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs

[AB#44452](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44452)
Corrigindo erro interno para componentes que não lançam notas
Incluindo verificação de frequencia registrada para turma

Corrigindo erro interno para componentes que não lançam notas

---

scripts/V471__AJUSTE_RENOMEAR_GRUPOS_COMUNICADOS_CONFORME_MODALIDADES.sql

[AB#44229](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44229)

Fix:44229 - [Back] Master - Ajustes nos grupos de comunicados conforme novos nomes das modalidades

---

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurmaOld/CalcularFrequenciaPorTurmaOldCommandHandler.cs

[AB#44474](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44474)

adicionado frequencia = 0

---

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurmaOld/CalcularFrequenciaPorTurmaOldCommandHandler.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterTotalAulasTurmaEBimestreEComponenteCurricular/ObterTotalAulasTurmaEBimestreEComponenteCurricularQuery.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterTotalAulasTurmaEBimestreEComponenteCurricular/ObterTotalAulasTurmaEBimestreEComponenteCurricularQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodo.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaAlunoDisciplinaPeriodo.cs

[AB#44474](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44474)

correção no formato de obter o total de aulas

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

[AB#42686](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42686)

Fix/42686 Corrigindo erro ao reprocessar fechamend quando é sintese

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs

[AB#44474](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44474)

ajuste para quando é eja

---

src/SME.SGP.Aplicacao/Consultas/ConsultasEvento.cs

[AB#44260](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44260)

Fix:44260 [Back] rel r2

---

src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterTotalAulasTurmaEBimestreEComponenteCurricular/ObterTotalAulasTurmaEBimestreEComponenteCurricularQuery.cs
src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodo.cs

[AB#44501](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44501)

Ajustes para exibição da frequencia global

---

scripts/V470__AJUSTE_REMOVER_PENDENCIAS_FECHAMENTO_INDEVIDAS_EJA.sql
src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMes/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesQueryHandler.cs

Fix:42148 [Back] master

---

scripts/V470__AJUSTE_REMOVER_PENDENCIAS_FECHAMENTO_INDEVIDAS_EJA.sql
src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMes/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesQueryHandler.cs

Fix:42148 [Back] dev

---

scripts/V470__AJUSTE_REMOVER_PENDENCIAS_FECHAMENTO_INDEVIDAS_EJA.sql
src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMes/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesQueryHandler.cs

Fix:42148 [Back] rel

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

[AB#44373](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44373)

Fix:44373 [Back] master - ajuste para salvar conceitos

---

scripts/V470__AJUSTE_REMOVER_PENDENCIAS_FECHAMENTO_INDEVIDAS_EJA.sql

Fix:42148 - [Back] - Master - 2 

---

scripts/V470__AJUSTE_REMOVER_PENDENCIAS_FECHAMENTO_INDEVIDAS_EJA.sql

42148 - DEV -ajuste no script

---

scripts/V470__AJUSTE_REMOVER_PENDENCIAS_FECHAMENTO_INDEVIDAS_EJA.sql

42148 - REL - ajuste no script

---

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterInformacoesDeFrequenciaAlunoPorSemestreUseCase.cs
src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaBimestres/ObterFrequenciaBimestresQueryHandler.cs

[AB#44501](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44501)

Ajustes para exibir o valor zero na frequencia

---

src/SME.SGP.Dados/Repositorios/RepositorioAtribuicaoCJ.cs

Ajuste consulta de atribuição cj [AB#45076](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/45076)

fix/45076 

---

src/SME.SGP.Api/Properties/launchSettings.json
src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommandHandler.cs

[AB#44266](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44266)

Fix:44266 [Back] rel r2

---

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs

[AB#44452](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44452)

Fix:44452 master

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Infra/Dtos/ConselhoDeClasseComponenteSinteseDto.cs

[AB#45128](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/45128)

Correção no conselho de classe

---

scripts/V470__AJUSTE_REMOVER_PENDENCIAS_FECHAMENTO_INDEVIDAS_EJA.sql
src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs

Fix:42148 [Back] rel r2 - 3

---

scripts/V470__AJUSTE_REMOVER_PENDENCIAS_FECHAMENTO_INDEVIDAS_EJA.sql

Ajuste para excluir pendencias de usuarios

FIX:42148 - [Back] Master 3

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

Corrigindo erro ao buscar sintese 
[AB#42686](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42686)

Fix/42686 - master

---

src/SME.SGP.Aplicacao/CasosDeUso/Aula/PodeCadastrarAulaUseCase.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Aula/PodeCadastrarAulaNoDia/PodeCadastrarAulaNoDiaQuery.cs
src/SME.SGP.Aplicacao/Queries/Aula/PodeCadastrarAulaNoDia/PodeCadastrarAulaNoDiaQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAula.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAula.cs
src/SME.SGP.Infra/Dtos/Aula/AulaSimplesDto.cs
src/SME.SGP.Infra/Dtos/DataAulasProfessorDto.cs

[AB#46103](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46103)

Fix:46103 [Back] release r2

---

src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/SalvarAtribuicaoCJUseCase.cs
src/SME.SGP.Aplicacao/Commands/AtribuicaoCJ/InserirAtribuicaoCJ/InserirAtribuicaoCJCommand.cs
src/SME.SGP.Aplicacao/Commands/AtribuicaoCJ/InserirAtribuicaoCJ/InserirAtribuicaoCJCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/AtribuicaoCJ/RemoverAtribuicaoCJ/RemoverAtribuicaoCJCommand.cs
src/SME.SGP.Aplicacao/Commands/AtribuicaoCJ/RemoverAtribuicaoCJ/RemoverAtribuicaoCJCommandHandler.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs
src/SME.SGP.Dados/Repositorios/RepositorioAtribuicaoCJ.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtribuicaoCJ.cs

[AB#45702](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/45702)

Ajustes para funcionamento

---

src/SME.SGP.Aplicacao/CasosDeUso/Aula/PodeCadastrarAulaUseCase.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Aula/PodeCadastrarAulaNoDia/PodeCadastrarAulaNoDiaQuery.cs
src/SME.SGP.Aplicacao/Queries/Aula/PodeCadastrarAulaNoDia/PodeCadastrarAulaNoDiaQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAula.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAula.cs
src/SME.SGP.Infra/Dtos/Aula/AulaSimplesDto.cs
src/SME.SGP.Infra/Dtos/DataAulasProfessorDto.cs

[AB#46103](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46103)
Ajuste para considerar o tipo da aula na validação de criação

Fix:46103 - [Back] Master

---

src/SME.SGP.Aplicacao/Consultas/ConsultasEvento.cs

[AB#44260](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44260)
Ajustes para validar outros perfis além de AD para alterar eventos

Fix:44260 - [Back] Master 

---

src/SME.SGP.Api/Controllers/AtribuicaoCJController.cs
src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/ObterProfessoresTitularesECjsUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasAtribuicaoCJ.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AtribuicaoCJ/IObterProfessoresTitularesECjsUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasAtribuicaoCJ.cs
src/SME.SGP.Dados/Repositorios/RepositorioAtribuicaoCJ.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#44949](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44949)

Adicionado ano letivo ao obter listagem

---

src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs

[AB#44790](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44790)

Ajuste na query do classroom

---

src/SME.SGP.Api/Controllers/UeController.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasUe.cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasUe.cs
src/SME.SGP.Dados/Repositorios/RepositorioUe.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioUe.cs

[AB#44952](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44952)
[AB#44952](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44952)

ajustes para funcionamento dos filtros

---

src/SME.SGP.Api/Controllers/AtribuicaoEsporadicaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoEsporadica/ExcluirAtribuicaoEsporadicaUseCase.cs
src/SME.SGP.Aplicacao/Comandos/ComandosAtribuicaoEsporadica.cs
src/SME.SGP.Aplicacao/Commands/AtribuicaoEsporadica/SalvarAtribuicaoEsporadica/SalvarAtribuicaoEsporadicaCommand.cs
src/SME.SGP.Aplicacao/Commands/AtribuicaoEsporadica/SalvarAtribuicaoEsporadica/SalvarAtribuicaoEsporadicaCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AtribuicaoEsporadica/IExcluirAtribuicaoEsporadicaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosAtribuicaoEsporadica.cs
src/SME.SGP.Aplicacao/Queries/AtribuicaoEsporadica/ObterAtribuicaoEsporadicaPorId/ObterAtribuicaoEsporadicaPorIdQuery.cs
src/SME.SGP.Aplicacao/Queries/AtribuicaoEsporadica/ObterAtribuicaoEsporadicaPorId/ObterAtribuicaoEsporadicaPorIdQueryHandler.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#44949](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44949)

Ajuste na regra de exclusão

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs

[AB#44464](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44464)

Fix44464 rel r2

---

src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#44983](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44983)

Criado filas de erro

---

src/SME.SGP.Api/Controllers/EncaminhamentoAEEController.cs

[AB#46273](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46273)

46273 Ajuste permissão de consulta de responsavel

---

src/SME.SGP.Dados/Repositorios/RepositorioTipoCalendario.cs

[AB#46235](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46235)

46235 Ajuste condição de Identificação de Calendario EJA

---

src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs
src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
src/SME.SGP.Infra/Dtos/AtribuicaoProfessorTurmaEOLDto.cs
src/SME.SGP.Infra/Dtos/PeriodoDto.cs

[AB#46118](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46118)

46118 Permitir fechamento até o final do periodo

---

src/SME.SGP.Api/Controllers/ConselhoClasseController.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasConselhoClasseAluno.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipo/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipo/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQueryHandler.cs

[AB#46232](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46232)

Fix:46232 [Back] rel r2

---

src/SME.SGP.Api/Controllers/ComunicadoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Comunicados/SolicitarInclusaoComunicados/SolicitarInclusaoComunicadoEscolaAquiUseCase.cs
src/SME.SGP.Aplicacao/Commands/Comunicado/Inserir/InserirComunicado/InserirComunicadoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Comunicado/Inserir/InserirComunicado/InserirComunicadoCommandValidator.cs
src/SME.SGP.Infra/Dtos/ComunicadoInserirDto.cs

[AB#42610](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42610)

Ajustes no salvar

---

src/SME.SGP.Aplicacao/CasosDeUso/RabbitDeadletter/RabbitDeadletterSrSyncUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/RabbitDeadletter/RabbitDeadletterSrTratarUseCase.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgpRelatorios.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#46678](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46678)

Ajuste nas rotas dos relatórios

---

src/SME.SGP.Api/Controllers/ComunicadoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Comunicados/ObterQuantidadeCriancaUseCase/ObterQuantidadeCriancaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/Comunicados/IObterQuantidadeCriancaUseCase.cs
src/SME.SGP.Aplicacao/Queries/Comunicado/ObterQuantidadeCrianca/ObterQuantidadeCriancaQuery.cs
src/SME.SGP.Aplicacao/Queries/Comunicado/ObterQuantidadeCrianca/ObterQuantidadeCriancaQueryHandler.cs
src/SME.SGP.Infra/Dtos/DashBboardFrequencia/QuantidadeCriancaDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#42606](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/42606)

Criado endpoint para retornar quantidade de crianças

---

src/SME.SGP.Api/Controllers/ComunicadoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Comunicados/ObterQuantidadeCriancaUseCase/ObterQuantidadeCriancaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EscolaAqui/Comunicados/IObterQuantidadeCriancaUseCase.cs
src/SME.SGP.Aplicacao/Queries/Comunicado/ObterQuantidadeCrianca/ObterQuantidadeCriancaQuery.cs
src/SME.SGP.Aplicacao/Queries/Comunicado/ObterQuantidadeCrianca/ObterQuantidadeCriancaQueryHandler.cs

[AB#46798](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46798)

Alterado parametros do endpoint

---

src/SME.SGP.Api/Controllers/ComunicadoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Abrangencia/ObterTurmasPorAnoLetivoUeModalidadeSemestreEAnosEscolaresUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Abrangencia/IObterTurmasPorAnoLetivoUeModalidadeSemestreEAnosEscolaresUseCase.cs
src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterTurmasPorAnoLetivoUeModalidadeSemestreEAnosEscolares/ObterTurmasPorAnoLetivoUeModalidadeSemestreEAnosEscolaresQuery.cs
src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterTurmasPorAnoLetivoUeModalidadeSemestreEAnosEscolares/ObterTurmasPorAnoLetivoUeModalidadeSemestreEAnosEscolaresQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAbrangencia.cs

[AB#46839](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46839)

Adicionado considera historico para buscar a turma

---

src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Anos/ObterAnosPorCodigoUeModalidadeEscolaAquiUseCase.cs
src/SME.SGP.Infra/Dtos/EscolaAqui/Anos/AnosPorCodigoUeModalidadeEscolaAquiResult.cs

[AB#46834](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46834)

Correção de turmas

---

src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs

[AB#46890](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46890)

Ajuste na query

---

src/SME.SGP.Api/Controllers/RelatorioPendenciasFechamentoController.cs

[AB#46929](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46929)

tipo pendencias

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorTurmasCodigo/ObterComponentesCurricularesPorTurmasCodigoQuery.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorTurmasCodigo/ObterComponentesCurricularesPorTurmasCodigoQueryHandler.cs

[AB#46662](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46662)

Fix:46662 [Back] rel r2

---

src/SME.SGP.Infra/Enumerados/Permissao.cs

[AB#46937](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46937)

Alterado breadcrumb

---

src/SME.SGP.Api/Properties/launchSettings.json
src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommandHandler.cs

[AB#44266](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44266)

Fix:44266 [Back] master

---

src/SME.SGP.Infra/Enumerados/Permissao.cs

[AB#46937](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46937)

Alterado url

---

scripts/V474__COMUNICADO_TIPO_ESCOLA_INSERIR_TODOS.sql

criado script para inserir tipo_escola para todos os comunicados que ja existem

criado script para inserir tipo_escola

---

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/CalculoFrequenciaTurmaDisciplinaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ValidacaoAusenciaConcolidacaoFrequenciaTurmaUseCase.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/IncluirFilaCalcularFrequenciaPorTurma/IncluirFilaCalcularFrequenciaPorTurmaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/IncluirFilaConciliacaoFrequenciaTurma/IncluirFilaConciliacaoFrequenciaTurmaCommandHandler.cs

[AB#47254](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47254)

Retornado rotina com melhor performance no calculo de frequencia para avaliação de uso em produção

---

src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipo/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQuery.cs

[AB#46232](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46232)

46232 - ajuste para considerar histórico na busca de turmas

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

[AB#47011](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47011)  Correção de busca de calendario por semestre.

47011 - Notas - Não está salvando as notas finais informadas na EJA 

---

src/SME.SGP.Api/Controllers/RelatorioPendenciasFechamentoController.cs
src/SME.SGP.Dominio/Enumerados/TipoPendencia.cs
src/SME.SGP.Dominio/Enumerados/TipoPendenciaGrupo.cs
src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioPendenciasFechamentoDto.cs

[AB#46930](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46930)

Adicionado parâmetro para filtrar se a pendência é resolvida ou não

---

src/SME.SGP.Api/Controllers/DashboardFechamentoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardFechamento/ObterFechamentoSituacaoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFechamento/IObterFechamentoSituacaoUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardFechamento/ObterFechamentoSituacao/ObterFechamentoSituacaoQuery.cs
src/SME.SGP.Aplicacao/Queries/DashboardFechamento/ObterFechamentoSituacao/ObterFechamentoSituacaoQueryHandler.cs
src/SME.SGP.Dados/Contexto/SgpContext.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplina.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoTurmaDisciplina.cs
src/SME.SGP.Infra/Dtos/DashboardFechamento/FechamentoSituacaoDto.cs
src/SME.SGP.Infra/Dtos/DashboardFechamento/FechamentoSituacaoQuantidadeDto.cs
src/SME.SGP.Infra/Dtos/DashboardFechamento/FiltroDashboardFechamentoDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#46951](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46951)

46951 criando endpoint de listagem de situação fechamento

---

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/PendenciasFechamento/RelatorioPendenciasFechamentoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/IRelatorioPendenciasFechamentoUseCase.cs
src/SME.SGP.Infra/Dtos/FiltroTipoPendenciaDto.cs
src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioPendenciasFechamentoDto.cs

[AB#47418](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47418)
[AB#46934](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46934)

Ajustes no Dto e no endpoint de tipos pendencia

---

src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs
src/SME.SGP.Api/Startup.cs
src/SME.SGP.Aplicacao/CasosDeUso/SerapEstudantes/ExecutarSyncSerapEstudantesProvasUseCase.cs
src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaSerapEstudantes/PublicarFilaSerapEstudantesCommand.cs
src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaSerapEstudantes/PublicarFilaSerapEstudantesCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/SerapEstudantes/IExecutarSyncSerapEstudantesProvasUseCase.cs
src/SME.SGP.Infra/Fila/SerapEstudantes/RotasRabbitSerapEstudantes.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs

Inclusão de disparo via hangfire diário para sincronização de provas
Inclusão de exchange e fila rabbits do Serap estudantes
AB#42255

Atualização de provas SERAp Estudantes

---

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs

[AB#44215](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44215)

Ajuste no retorno do percentual de frequência das telas de acompanhamento frequência e fechamento bimestre

---

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IExecutaEncerramentoPlanoAEEEstudantesInativosUseCase.cs
src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEol/ObterAlunoPorCodigoEolQueryHandler.cs

[AB#47504](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47504)

Correção de bug: Encerrar plano de aluno que migrou de turma

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

[AB#47011](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47011)

47011 -Notas - Não está salvando as notas finais informadas na EJA

---

src/SME.SGP.Api/Controllers/DashboardFechamentoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardFechamento/ObterFechamentoPendenciasUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFechamento/IObterFechamentoPendenciaUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardFechamento/ObterFechamentoPendencias/ObterFechamentoPendenciasQuery.cs
src/SME.SGP.Aplicacao/Queries/DashboardFechamento/ObterFechamentoPendencias/ObterFechamentoPendenciasQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplina.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoTurmaDisciplina.cs
src/SME.SGP.Infra/Dtos/DashboardFechamento/FechamentoPendenciaDto.cs
src/SME.SGP.Infra/Dtos/DashboardFechamento/FechamentoPendenciaQuantidadeDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#46953](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46953)

46953 criando endpoint para listar pendencia do fechamento

---

src/Bibliotecas/SME.SGP.Background/RegistraServicosRecorrentes.cs
src/SME.SGP.Api/Startup.cs
src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Comunicados/SolicitarInclusaoComunicados/SolicitarInclusaoComunicadoEscolaAquiUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/SerapEstudantes/ExecutarSyncSerapEstudantesProvasUseCase.cs
src/SME.SGP.Aplicacao/Commands/Comunicado/Inserir/InserirComunicado/InserirComunicadoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaSerapEstudantes/PublicarFilaSerapEstudantesCommand.cs
src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaSerapEstudantes/PublicarFilaSerapEstudantesCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/SerapEstudantes/IExecutarSyncSerapEstudantesProvasUseCase.cs
src/SME.SGP.Infra/Fila/SerapEstudantes/RotasRabbitSerapEstudantes.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs

sprint 3 - serap estudantes

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs

Ajuste para mostrar componentes sem frequencia, mas que lançam nota (Língua Inglesa Compartilhada)
[AB#44464](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44464)

Fix:44464 [Back] Master

---

src/SME.SGP.Api/Controllers/DashboardFechamentoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardFechamento/ObterFechamentoPendenciasUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardFechamento/ObterFechamentoSituacaoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFechamento/IObterFechamentoPendenciaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFechamento/IObterFechamentoSituacaoUseCase.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplina.cs
src/SME.SGP.Infra/Dtos/DashboardFechamento/FechamentoPendenciaQuantidadeDto.cs
src/SME.SGP.Infra/Dtos/DashboardFechamento/FechamentoSituacaoDto.cs
src/SME.SGP.Infra/Dtos/DashboardFechamento/FiltroDashboardFechamentoDto.cs

[AB#46951](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46951)

46951 ajustando o tipo de retorno para o padrao e ajustand namespace

---

src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs

Ajuste no login para o perfil de supervisor incluindo o tratamento ao consumir o endpoint da API/EOL que não retorna detalhes da abrangência.

Bug: 47694

---

src/SME.SGP.Api/Controllers/ProfessorController.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasProfessorTurma.cs
src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasProfessorTurma.cs
src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs

[AB#47723](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47723)

pesquisa por nome com dre e ue

---

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
src/SME.SGP.Dados/Repositorios/RepositorioAtribuicaoCJ.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtribuicaoCJ.cs
src/SME.SGP.Dominio.Servicos/ServicoAtribuicaoCJ.cs
src/SME.SGP.Dominio/Entidades/Abrangencia.cs
src/SME.SGP.Infra/Dtos/AbrangenciaSinteticaDto.cs

[AB#47283](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47283) Release2

Bug47283 - rel-2 Atribuição de CJ - Não está criando abrangência para turma concluída 

---

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/PendenciasFechamento/RelatorioPendenciasFechamentoUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasProfessorTurma.cs
src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs

[AB#47723](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47723)

adicionado ueId no parametro

---

src/SME.SGP.Api/Controllers/ProfessorController.cs
src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs

[AB#47723](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47723)

Ajustado endpoint de pesquisa do professor

---

src/SME.SGP.Infra/Enumerados/Permissao.cs

[AB#46954](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46954)

46954 criando permisao

---

src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioPendenciasFechamentoDto.cs

[AB#47824](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47824)

Ajustes exibir historico

---

src/SME.SGP.Aplicacao/Consultas/ConsultasAtribuicoes.cs

Ajuste na listagem de UEs para atribuição CJ, onde foi incluída a funcionalidade para desconsiderar as novas escolas conforme nova regra de negócio.

Bug: 47119

---

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
src/SME.SGP.Dados/Repositorios/RepositorioAtribuicaoCJ.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtribuicaoCJ.cs
src/SME.SGP.Dominio.Servicos/ServicoAtribuicaoCJ.cs
src/SME.SGP.Dominio/Entidades/Abrangencia.cs
src/SME.SGP.Infra/Dtos/AbrangenciaSinteticaDto.cs

[AB#47283](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47283)

BUG: 47283 master

---

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs

[AB#47984](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47984)

47984 Desconsiderar registros sem a informação de tipo de frequencia

---

src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs

[AB#47768](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47768)

Ajuste no espaçamento do título da pendência

---

src/SME.SGP.Aplicacao/Comandos/ComandosAulaPrevista.cs

Considerando período da turma ao salvar aulas previstas bimestre

Fix/48019 - Aula prevista X aula dada - Não está "salvando" as informações da EJA 1º semestre

---

src/SME.SGP.Dados/Repositorios/RepositorioAtribuicaoEsporadica.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtribuicaoEsporadica.cs
src/SME.SGP.Dominio.Servicos/ServicoAtribuicaoEsporadica.cs

[AB#47471](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/47471)  Adicionado parametro de ue e mudança de retorno da query e mensagem de erro

 - Atribuição esporadica

---

src/SME.SGP.Aplicacao/Queries/Aula/ObterPodeCadastrarAulaPorData/ObterPodeCadastrarAulaPorDataQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Aula/PodeCadastrarAulaNoDia/PodeCadastrarAulaNoDiaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Aula/ValidarSeEhDiaLetivo/ValidarSeEhDiaLetivoQuery.cs
src/SME.SGP.Aplicacao/Queries/Aula/ValidarSeEhDiaLetivo/ValidarSeEhDiaLetivoQueryHandler.cs
src/SME.SGP.Dados/Contexto/SgpContext.cs
src/SME.SGP.Dominio.Servicos/ServicoEvento.cs

[AB#48189](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48189)

Correção no tratamento de evento e aula de reposição (FDS)

---

scripts/V479__ADICIONAR_COLUNA_STATUSGSA_NOTAS_CONCEITO.sql
src/SME.SGP.Aplicacao/CasosDeUso/NotaAtividadeAvaliativa/ImportarAtividadesGsaUseCase.cs
src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativa/ImportarNotaAtividadeGsa/ImportarNotaAtividadeGsaCommand.cs
src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativa/ImportarNotaAtividadeGsa/ImportarNotaAtividadeGsaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativa/SalvarNotaAtividadeAvaliativaGsa/SalvarNotaAtividadeAvaliativaGsaCommand.cs
src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativa/SalvarNotaAtividadeAvaliativaGsa/SalvarNotaAtividadeAvaliativaGsaCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/NotaAtividadeAvaliativa/IImportarAtividadesGsaUseCase.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterAtividadeNotaConseitoPorAtividadeGoogleClassId/ObterAtividadePorAtividadeGoogleClassIdHandler.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterAtividadeNotaConseitoPorAtividadeGoogleClassId/ObterAtividadePorAtividadeGoogleClassIdQuery.cs
src/SME.SGP.Dados/Repositorios/RepositorioNotasConceitos.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotasConceitos.cs
src/SME.SGP.Dominio/Enumerados/StatusGSA.cs
src/SME.SGP.Infra/Dtos/AtividadeAvaliativa/NotaAtividadeGsaDto.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#46702](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46702)

46702 criando worker para importadar os dados do gsa

---

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
src/SME.SGP.Infra/Dtos/NotasConceitosNotaAvaliacaoRetornoDto.cs

[AB#46706](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46706)

46706 criando campo de statusGCA

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoAluno .cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasFechamentoAluno.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoAluno.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAnotacaoAlunoFechamento.cs
src/SME.SGP.Infra/Dtos/ConsultasConselhoClasseRecomendacaoConsultaDto.cs

[AB#45098](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/45098)

Bug/45098 release-r2 - Correção anotações do aluno e situação conselho

---

src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs
src/SME.SGP.Dados/Repositorios/RepositorioAulaPrevistaBimestre.cs
src/SME.SGP.Dominio/Entidades/AulaPrevistaBimestreQuantidade.cs

Considerar aulas datas para disciplinas sem frequencia.

Considerar aulas datas para disciplinas sem frequencia.

---

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorTurmasCodigo/ObterComponentesCurricularesPorTurmasCodigoQueryHandler.cs

Ajuste na funcionalidade de salvar conselho aplicando o tratamento de verificação de código de turma nulo ao definir as disciplinas.

Bug: 48723

---

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAula.cs

[AB#48751](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48751)

Ajuste na consulta para considerar pendência apenas componentes que permitem registro de frequencia

---

src/SME.SGP.Api/Controllers/CalendarioIntegracoesController.cs

troca de controller

---

src/SME.SGP.Api/Controllers/ComponenteCurricularIntegracaoController.cs
src/SME.SGP.Api/Controllers/PeriodoEscolarIntegracaoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/ComponentesCurriculares/ObterComponenteCurricularLancaNotaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/PeriodosEscolares/ObterPeriodoEscolarAtualPorTurmaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ComponentesCurriculares/IObterComponenteCurricularLancaNotaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ComponentesCurriculares/IObterPeriodoEscolarAtualPorTurmaUseCase.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#48794](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48794)

48794 - Endpoint integração

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorTurmasCodigo/ObterComponentesCurricularesPorTurmasCodigoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DashboardFechamento/ObterNotasFinaisFechamento/ObterNotasFinaisFechamentoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasse.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasse.cs

[AB#48826](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48826)

Ajuste na query de notas finais e conselho de classe

---

src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativa/ImportarNotaAtividadeGsa/ImportarNotaAtividadeGsaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativa/SalvarNotaAtividadeAvaliativaGsa/SalvarNotaAtividadeAvaliativaGsaCommand.cs
src/SME.SGP.Aplicacao/Commands/AtividadeAvaliativa/SalvarNotaAtividadeAvaliativaGsa/SalvarNotaAtividadeAvaliativaGsaCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterNotaPorAtividadeGoogleClassIdQuery/ObterNotaPorAtividadeGoogleClassIdQuery.cs
src/SME.SGP.Infra/Dtos/AtividadeAvaliativa/NotaAtividadeGsaDto.cs

[AB#48804](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48804)

48804 Ajuste importação de nota

---

src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasse.cs

Correção no gráfico de notas finais

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs

Ajuste ao obter notas de conselho para não exibir o % de frequência quando não houver aulas e ausências.

Bug: 48541

---

src/SME.SGP.Aplicacao/Queries/Aula/ValidarSeEhDiaLetivo/ValidarSeEhDiaLetivoQueryHandler.cs

[AB#49086](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49086)

tratamento para dias sem eventos ou dias não letivos

---

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs

[AB#48695](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48695)

48695 Alterado para consulta de matriculas no ano atual para considerar o encerramento

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs

Inclusão de tratamento de período escolar nulo ao obter os códigos das turmas na obtenção de dados finais do conselho.

Bug: 49106

---

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/Regencia/ObterComponentesCurricularesRegenciaPorTurmaCodigo/ObterComponentesCurricularesRegenciaPorTurmaCodigoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioCiclo.cs

Ajuste na funcionalidade cadastrar de compensação de ausência para tratar turma com o ano "S" considerar "1".
Ajuste no plano de ciclo tratando a turma da mesma forma que foi feito para compensação de ausência.

Bug: 43917

---

src/SME.SGP.Aplicacao/Commands/Aulas/ExcluirAulaUnica/ExcluirAulaUnicaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaSgp/PublicarFilaEmLoteSgpCommand.cs
src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaSgp/PublicarFilaEmLoteSgpCommandHandler.cs

Ajuste na funcionalidade de exclusão de aula para publicação de mensagens no rabbit ser feita em lote e não individualmente com intuíto de tornar mais rápida a execução.

Bug: 48785

---

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesComNotaFechamentoOuConselhoPorAluno/ObterComponentesComNotaDeFechamentoOuConselhoQuery.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesComNotaFechamentoOuConselhoPorAluno/ObterComponentesComNotaDeFechamentoOuConselhoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricular.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioComponenteCurricular.cs

[AB#45098](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/45098) r2 Consolidado status conselho

bug/45098-r2  - Consolidado Status conselho

---

src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdQuery/ObterPendenciasAulaPorAulaIdQuery.cs
src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdQuery/ObterPendenciasAulaPorAulaIdQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdsQuery/ObterPendenciasAulaPorAulaIdsQuery.cs
src/SME.SGP.Aplicacao/Queries/Aula/Pendencias/ObterPendenciasAulaPorAulaIdsQuery/ObterPendenciasAulaPorAulaIdsQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAula.cs

[AB#48456](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48456)

Apresentar a pendência da aula no dia do calendário

---

src/SME.SGP.Aplicacao/Commands/PlanoAEE/SalvarPlanoAee/SalvarPlanoAeeCommandHandler.cs

[AB#49312](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49312)

resolvendo pendência do professor

---

src/SME.SGP.Aplicacao/Commands/PlanoAEE/AtribuirResponsavelPlanoAEE/AtribuirResponsavelPlanoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarParecerCP/CadastrarParecerCPCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/SalvarPlanoAee/SalvarPlanoAeeCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterUltimaVersaoPlanoAEE/ObterUltimaVersaoPlanoAEEQuery.cs
src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterUltimaVersaoPlanoAEE/ObterUltimaVersaoPlanoAEEQueryHandler.cs

[AB#49310](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49310)

Correção Pendências duplicadas ao alterar o plano

---

src/SME.SGP.Aplicacao/Commands/PlanoAEE/SalvarPlanoAee/SalvarPlanoAeeCommandHandler.cs

[AB#49363](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49363)

Ajuste no resolver pendência ao editar um plano

---

src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterNotaTipoPorAnoModalidadeDataReferenciaQuery/ObterNotaTipoPorAnoModalidadeDataReferenciaQueryHandler.cs

[AB#49399](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49399)

49399 Corrigido tratamento do ano da turma de alfabetização

---

src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs

[AB#48637](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48637)
Ajuste na pesquisa de aulas possibilitando visualização de aulas por professores regentes.

fix/48637 

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoAluno .cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasFechamentoAluno.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipo/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQuery.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoAluno.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAnotacaoAlunoFechamento.cs
src/SME.SGP.Infra/Dtos/ConsultasConselhoClasseRecomendacaoConsultaDto.cs

[AB#45098](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/45098) anotações alunos

Fix/45098 dev - Anotações dos alunos 

---

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs

[AB#49477](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49477)

Ajuste listagem de pendências

---

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/NotificarPlanosAEEExpiradosUseCase.cs
src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaAtribuirResponsavelEncaminhamentoAEE/GerarPendenciaAtribuirResponsavelEncaminhamentoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarParecerCP/CadastrarParecerCPCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/EnviarNotificacaoCriacaoPlanoAEE/EnviarNotificacaoCriacaoPlanoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/Notificacoes/EnviarNotificacaoRestruturacaoPlanoAEE/EnviarNotificacaoReestruturacaoPlanoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/SalvarPlanoAee/SalvarPlanoAeeCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/ObtemUsuarioCEFAIDaDre/ObtemUsuarioCEFAIDaDreQuery.cs
src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/ObtemUsuarioCEFAIDaDre/ObtemUsuarioCEFAIDaDreQueryHandler.cs

[AB#49585](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49585)

Ajuste nas pendências do CEFAI

---

src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDia/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDiaQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
src/SME.SGP.Dominio/Entidades/Evento.cs
src/SME.SGP.Infra/Dtos/EventoAulaDto.cs

[AB#48998](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48998)

48998 - Ajuste EndPoint de eventos - Calendário Professor

---

scripts/V483__ALTERADO_REGRA_VISUALIZACAO_EVENTOS_SME.sql

[AB#48996](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48996)

48996 Alterado regra de visualização de eventos da SME/UE

---

scripts/V482__AJUSTE_VIEW_CALENDARIO_POR_DATA.sql
src/SME.SGP.Api/Controllers/EventoController.cs
src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
src/SME.SGP.Infra/Dtos/CalendarioEventosNoDiaRetornoDto.cs

[AB#48997](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48997)

48997 adicionando DreNome UeNome e descriçao no retorno do endpoint

---

src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosPorCodigoEolNome/ObterAlunosPorCodigoEolNomeQueryHandler.cs

Acrescentado código de turma na pesquisa de alunos

Acrescentado código de turma na pesquisa de alunos

---

scripts/V483__AJUSTE_VIEW_CALENDARIO_POR_DATA2.sql
src/SME.SGP.Api/Controllers/EventoController.cs
src/SME.SGP.Api/Controllers/EventosAulasCalendarioController.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasEvento.cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasEvento.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDia/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDiaQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEvento.cs
src/SME.SGP.Infra/Dtos/CalendarioEventosFiltroDto.cs
src/SME.SGP.Infra/Dtos/CalendarioEventosNoDiaRetornoDto.cs

- Trocar o tipo "SME"/"UE" no calendario escolar para o tipo no cadastro do evento
- Remover o (inicio) e (fim) da descrição
- Exibir o evento em todos os dias da recorrencia
- Evento de suspensão no dia 25 não carregou as datas inicio e fim
- Incluir o Tipo de Escola na descrição
[AB#50009](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50009)

37033 Ajustes identificados no repasse

---

src/SME.SGP.Aplicacao/CasosDeUso/TipoCalendario/BuscarTiposCalendarioPorDescricaoUseCase.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTiposCalendariosPorAnosLetivoModalidades/ObterTiposCalendariosPorAnosLetivoModalidadesQuery.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterTiposCalendariosPorAnosLetivoModalidades/ObterTiposCalendariosPorAnosLetivoModalidadesQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
src/SME.SGP.Dados/Repositorios/RepositorioTipoCalendario.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTipoCalendario.cs

[AB#49920](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49920)

49967 Filtro de tipo calendario por nome para gestão

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs

Ajuste na funcionalidade de obter notas finais do conselho para turmas de anos anteriores, validando se o período escolar foi definido.

Bug: 49883

---

scripts/V484__PARAMETRO_APROVACAO_NOTA.sql
src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs

[AB#49949](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49949)

49949 Parametro de Aprovação de Alteração de Nota Fechamento e Parecer

---

scripts/V485__WF_APROVACAO_NOTA_CONSELHO.sql
src/SME.SGP.Aplicacao/Commands/Notificacao/EnviarNotificacao/EnviarNotificacaoCommand.cs
src/SME.SGP.Aplicacao/Commands/Notificacao/EnviarNotificacao/EnviarNotificacaoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/GerarWFAprovacaoNotaConselhoClasse/GerarWFAprovacaoNotaConselhoClasseCommand.cs
src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/GerarWFAprovacaoNotaConselhoClasse/GerarWFAprovacaoNotaConselhoClasseCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterDescricaoComponenteCurricularPorId/ObterDescricaoComponenteCurricularPorIdQuery.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterDescricaoComponenteCurricularPorId/ObterDescricaoComponenteCurricularPorIdQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/ConceitoValores/ObterConceitosValores/ObterConceitosValoresQuery.cs
src/SME.SGP.Aplicacao/Queries/ConceitoValores/ObterConceitosValores/ObterConceitosValoresQueryHandler.cs
src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
src/SME.SGP.Dados/Mapeamentos/WfAprovacaoNotaConselhoMap.cs
src/SME.SGP.Dados/Mapeamentos/WfAprovacaoNotaFechamentoMap.cs
src/SME.SGP.Dados/Repositorios/RepositorioBase.cs
src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricular.cs
src/SME.SGP.Dados/Repositorios/RepositorioConceito.cs
src/SME.SGP.Dados/Repositorios/RepositorioWFAprovacaoNotaConselho.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioBase.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioComponenteCurricular.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConceito.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioWFAprovacaoNotaConselho.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioWfAprovacaoNotaFechamento.cs
src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs
src/SME.SGP.Dominio/Entidades/WFAprovacaoNotaConselho.cs
src/SME.SGP.Dominio/Enumerados/WorkflowAprovacaoTipo.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#49943](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49943)

49943 -  WF Aprovação de alteração de nota do conselho

---

src/SME.SGP.Api/Controllers/EventosIntegracaoController.cs
src/SME.SGP.Api/Controllers/NotasConceitosIntegracaoController.cs
src/SME.SGP.Api/Controllers/TurmaIntegracaoController.cs

[AB#50209](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50209)

Criado controller de integração

---

scripts/V487__RECRIAR_COLUNA_STATUSGSA_NOTAS_CONCEITO.sql

Recriando coluna status_gsa com default nulo.

Fix/50089 release-r2

---

src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ObterDadosDashboardFrequenciaPorAnoTurmaUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterDadosDashboardFrequenciaPorAnoTurma/ObterDadosDashboardFrequenciaPorAnoTurmaQueryHandler.cs
src/SME.SGP.Dados/Contexto/SgpContext.cs
src/SME.SGP.Dados/Contexto/SgpContextConsultas.cs
src/SME.SGP.Dados/Repositorios/RepositorioDashBoardFrequencia.cs
src/SME.SGP.Dados/Repositorios/RepositorioFrequencia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDashBoardFrequencia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequencia.cs
src/SME.SGP.Infra/Dtos/DashBboardFrequencia/FrequenciaAlunoDashboardDto.cs
src/SME.SGP.Infra/Interfaces/ISgpContextConsultas.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#49770](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49770)

Ajuste informações dashboard de total frequência

---

scripts/V489__WF_APROVACAO_PARECER_CONCLUSIVO.sql
src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/GerarWFAprovacaoNotaConselhoClasse/GerarWFAprovacaoNotaConselhoClasseCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivoCommand.cs
src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivoCommandHandler.cs
src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs
src/SME.SGP.Dados/Mapeamentos/WFAprovacaoParecerConclusivoMap.cs
src/SME.SGP.Dados/Repositorios/RepositorioWFAprovacaoParecerConclusivo.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioWFAprovacaoParecerConclusivo.cs
src/SME.SGP.Dominio/Entidades/WFAprovacaoParecerConclusivo.cs
src/SME.SGP.Dominio/Enumerados/WorkflowAprovacaoTipo.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#49944](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49944)

49944 WF Aprovação Parecer Conclusivo

---

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotaConselhoEmAprovacao/ObterNotaConselhoEmAprovacaoQuery.cs
src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotaConselhoEmAprovacao/ObterNotaConselhoEmAprovacaoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Frequencia/ObterNotaEmAprovacao/ObterNotaEmAprovacaoQuery.cs
src/SME.SGP.Aplicacao/Queries/Frequencia/ObterNotaEmAprovacao/ObterNotaEmAprovacaoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNota.cs
src/SME.SGP.Dados/Repositorios/RepositorioNotasConceitos.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseNota.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotasConceitos.cs
src/SME.SGP.Infra/Dtos/FechamentoNotaRetornoDto.cs
src/SME.SGP.Infra/Dtos/NotaPosConselhoDto.cs

[AB#50202](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50202)

50202 - Alterar retorno de endpoint de Notas no Conselho de Classe

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterSePossuiParecerEmAprovacao/ObterSePossuiParecerEmAprovacaoQuery.cs
src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterSePossuiParecerEmAprovacao/ObterSePossuiParecerEmAprovacaoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseParecerConclusivo.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseParecerConclusivo.cs
src/SME.SGP.Infra/Dtos/ParecerConclusivoDto.cs

[AB#50358](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50358)

50358 - Ajuste - EndPoint "Em Aprovacao" de  Parecer Conclusivo

---

scripts/V488__AJUSTE_AJUSTE_PROCEDURE_CALENDARIO_EVENTO.sql
src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs

[AB#49968](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49968)

49968 ajustando procedure para respeitar o filtro

---

scripts/V486__ATUALIZACAO_PARAMETROS_QUANTIDADE_IMAGENS.sql

[AB#49915](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49915)

Ajuste nos parâmetros de quantidades de imagens

---

scripts/V488__AJUSTE_AJUSTE_PROCEDURE_CALENDARIO_EVENTO.sql
src/SME.SGP.Aplicacao/Consultas/ConsultasEvento.cs
src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEvento.cs
src/SME.SGP.Infra/Dtos/FiltroEventosDto.cs

[AB#50624](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50624)

50624 validando se lista todos os eventos

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs

[AB#50637](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50637)

50626 Ajustes mensagens de WF aprovação fechamento

---

src/SME.SGP.Api/Configuracoes/RegistraClientesHttp.cs
src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Comuns/ReceberRelatorioProntoUseCase.cs
src/SME.SGP.Aplicacao/Commands/Comunicado/Inserir/InserirComunicadoBoletimEscolaAqui/InserirComunicadoBoletimEscolaAquiCommand.cs
src/SME.SGP.Aplicacao/Commands/Comunicado/Inserir/InserirComunicadoBoletimEscolaAqui/InserirComunicadoBoletimEscolaAquiCommandHendler.cs
src/SME.SGP.Aplicacao/Commands/Comunicado/Notificacao/CriarNotificacaoEscolaAqui/CriarNotificacaoEscolaAquiCommandHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs
src/SME.SGP.Dominio/Enumerados/TipoComunicado.cs
src/SME.SGP.Infra/Fila/MensagemRelatorioBoletimAppDto.cs
src/SME.SGP.Infra/Fila/MensagemRelatorioProntoDto.cs
src/SME.SGP.Worker.Rabbbit/Startup.cs

[AB#49999](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49999)
[AB#50000](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50000)
[AB#50633](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50633)

Ajustes na notficação

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

[AB#50626](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50626)

50626 Incluso componente da regência no WF aprovação nota fechamento

---

scripts/V488__AJUSTE_AJUSTE_PROCEDURE_CALENDARIO_EVENTO.sql
src/SME.SGP.Aplicacao/Consultas/ConsultasEvento.cs
src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
src/SME.SGP.Infra/Dtos/EventoCompletoDto.cs

[AB#50624](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50624)

50624 criando a descricao de ue e dre

---

src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/GerarWFAprovacaoNotaConselhoClasse/GerarWFAprovacaoNotaConselhoClasseCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/NotificarAprovacaoNotaConselho/NotificarAprovacaoNotaConselhoCommandHandler.cs

[AB#50642](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50642)

50642 Ajuste mensagem WF nota pos conselho

---

src/SME.SGP.Api/Controllers/DashboardDiarioBordoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DashboardDiarioBordo/ObterQuantidadeTotalDeDiariosPendentesPorDREUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardDiarioBordo/IObterQuantidadeTotalDeDiariosPendentesPorDREUseCase.cs
src/SME.SGP.Aplicacao/Queries/DashboardDiarioBordo/ObterQuantidadeTotalDeDiariosPendentesPorDre/ObterQuantidadeTotalDeDiariosPendentesPorDreQuery.cs
src/SME.SGP.Aplicacao/Queries/DashboardDiarioBordo/ObterQuantidadeTotalDeDiariosPendentesPorDre/ObterQuantidadeTotalDeDiariosPendentesPorDreQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDiarioBordo.cs
src/SME.SGP.Infra/Dtos/DashboardDiarioBordo/GraficoTotalDiariosEDevolutivasPorDreDTO.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#49981](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49981)

49981 Dash Diario Bordos por DRE

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

[AB#50626](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50626)

50626 Correção Nome Componente

---

src/SME.SGP.Api/Controllers/FeriadoCalendarioController.cs
src/SME.SGP.Api/Controllers/TipoCalendarioController.cs

[AB#50700](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50700)

50700 adicionando permissao

---

src/SME.SGP.Aplicacao/CasosDeUso/Aula/CriacaoAutomatica/CriarAulasInfantilAutomaticamenteUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/ExecutaPendenciaAulaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/ComponentesCurriculares/Sincronismo/ExecutaSincronismoComponentesCurricularesEolUseCase.cs
src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasAutomaticamente/CriarAulasRegenciaAutomaticamenteCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Log/SalvarLogViaRabbit/SalvarLogViaRabbitCommandHandler.cs
src/SME.SGP.Dominio/Enumerados/Logs/LogContexto.cs

removido e substituido comentários

removendo using de nova versão para anterior, até up do c#

---

src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs
src/SME.SGP.Infra/Dtos/ConselhoClasseNotaRetornoDto.cs

[AB#50717](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50717)

BACK: Incluso atributo EmAprovacao no retorno do POST de notas do conselho

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
src/SME.SGP.Infra/Dtos/AuditoriaPersistenciaDto.cs

[AB#50730](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50730)

50730 Atribuito EmAprovacao no lançamento de nota bimestral

---

src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaFechamento/ExcluirWFAprovacaoNotaFechamentoPorNota/ExcluirWFAprovacaoNotaFechamentoPorNotaCommand.cs
src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaFechamento/ExcluirWFAprovacaoNotaFechamentoPorNota/ExcluirWFAprovacaoNotaFechamentoPorNotaCommandHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioNotasConceitos.cs
src/SME.SGP.Dados/Repositorios/RepositorioWfAprovacaoNotaFechamento.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioWfAprovacaoNotaFechamento.cs
src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

[AB#50729](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50729)

50729 Exclusão do WF Aprovação existente na criação de um novo

---

src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/NotificarAprovacaoNotaConselho/NotificarAprovacaoNotaConselhoCommandHandler.cs

[AB#50706](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50706)

50706 Ajuste notificação aprovação WF Nota Conselho

---

src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/ExcluirWfAprovacaoNotaConselhoPorNotaId/ExcluirWfAprovacaoNotaConselhoPorNotaIdCommandHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioWFAprovacaoNotaConselho.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioWFAprovacaoNotaConselho.cs

[AB#50720](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50720)

50720 Correção Exclusão WF Aprovação Conselho

---

src/SME.SGP.Api/Controllers/AcompanhamentoTurmaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ObterAcompanhamentoAlunoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ObterFotosSemestreAlunoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoTurma/ObterParametroQuantidadeImagensPercursoColetivoTurmaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AcompanhamentoTurma/IObterParametroQuantidadeImagensPercursoColetivoTurmaUseCase.cs
src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
src/SME.SGP.Infra/Dtos/ParametroQuantidadeUploadImagemDto.cs

[AB#49918](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/49918)

49918 adicionando campo de quantidade imagem percurso individual

---

src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/NotificarAprovacaoNotaConselho/NotificarAprovacaoNotaConselhoCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterBimestreDoPeriodoEscolar/ObterBimestreDoPeriodoEscolarQuery.cs
src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterBimestreDoPeriodoEscolar/ObterBimestreDoPeriodoEscolarQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolar.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoEscolar.cs

[AB#50706](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50706)

50706 Alterado metodo de obtenção do bimestre

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Infra/Dtos/NotaConceitoBimestreComponenteDto.cs

[AB#50720](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50720)

50720 Não carregar nota zero quando recusado o WF

---

src/SME.SGP.Aplicacao/Queries/Aula/ObterPodeCadastrarAulaPorData/ObterPodeCadastrarAulaPorDataQueryHandler.cs

Tratamento caso o periodo de fechamento não exista ainda.

Tratamento caso o periodo de fechamento não exista ainda.

---

src/SME.SGP.Api/Controllers/FeriadoCalendarioController.cs
src/SME.SGP.Api/Controllers/TipoCalendarioController.cs
src/SME.SGP.Dominio/Entidades/Usuario.cs

[AB#50791](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50791)
[AB#50788](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50788)

50791 adicionando permissao e ajustando validaçao de perfil

---

scripts/V486__ATUALIZACAO_PARAMETROS_QUANTIDADE_IMAGENS.sql

[AB#50823](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50823)

Corrigido script de numero de imagens

---

scripts manutencao/50848 - Script DB para substituir o caminho dos arquivos/script_para_substituir_caminho_dos_arquivos.sql

[AB#50848](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50848)

50848 criando script para substituir caminho dos arquivos

---

src/SME.SGP.Api/Controllers/UploadController.cs

[AB#50856](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50856)

50856 ajustando caminho do upload

---

src/SME.SGP.Api/Controllers/FechamentoTurmaController.cs
src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoTurmaDisciplina.cs
src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosFechamentoTurmaDisciplina.cs

Criação do enpoint para reprocessar fechamentos em lote.

Bug: 50991

---

src/SME.SGP.Aplicacao/Commands/DeletarArquivo/RemoverArquivosExcluidosCommandHandler.cs

[AB#51752](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/51752)

Adicionado replace para alterar as barras do caminho

---

src/SME.SGP.Aplicacao/Commands/DeletarArquivo/RemoverArquivosExcluidosCommandHandler.cs

Adicionado SetAttributes

---

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoReabertura/NotificacaoPeriodoFechamentoReaberturaEncerrandoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/FechamentoReabertura/NotificacaoPeriodoFechamentoReaberturaIniciandoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/FechamentoReabertura/INotificacaoPeriodoFechamentoReaberturaEncerrando.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/FechamentoReabertura/INotificacaoPeriodoFechamentoReaberturaIniciando.cs
src/SME.SGP.Infra/Dtos/FechamentoReabertura/FiltroPeriodoFechamentoBimestreDto.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#52451](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52451)

fix/52451 - Ajustar processamento de notificações em filas Rabbit

---

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RegistrarEncaminhamentoAEEUseCase.cs
src/SME.SGP.Aplicacao/Commands/Armazenamento/ExcluirArquivoFisico/ExcluirArquivoFisicoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Armazenamento/ExcluirArquivoPorId/ExcluirArquivoPorIdCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/ExcluirRespostaEncaminhamentoAEE/ExcluirRespostaEncaminhamentoAEECommandHandler.cs

Adicionado SentrySdk

---

src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs

[AB#52584](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52584)

52584 - [44029 - Relatório de acompanhamento dos registros pedagógicos] - Não é gerado notificação

---

src/SME.SGP.Aplicacao/CasosDeUso/Notificacao/NotificacaoFimPeriodoFechamentoUEUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Notificacao/NotificacaoInicioFimPeriodoFechamentoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Notificacao/NotificacaoInicioPeriodoFechamentoUEUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Notificacao/INotificacaoFimPeriodoFechamentoUEUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Notificacao/INotificacaoFimPeriodoFechamentoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Notificacao/INotificacaoInicioFimPeriodoFechamentoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Notificacao/INotificacaoInicioPeriodoFechamentoUEUseCase.cs
src/SME.SGP.Infra/Dtos/Fechamento/FiltroFechamentoPeriodoAberturaDto.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#52451](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52451)

fix/52451 - Criação de novas filas para processamento de ues

---

src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs

[AB#52257](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52257)

52257 - Remover os eventos inclusive do ano anterior

---

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/AcompanhamentoAprendizagem/RelatorioAcompanhamentoAprendizagemUseCase.cs

[AB#52389](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52389)

52389 ajustando o download do gsp

---

src/SME.SGP.Aplicacao/Consultas/ConsultasEventosAulasCalendario.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasPeriodoFechamento.cs
src/SME.SGP.Aplicacao/Queries/Turma/TurmaEmPeriodoAberto/TurmaEmPeriodoAbertoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioEventoFechamento.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoReabertura.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEventoFechamento.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoReabertura.cs
src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

50715 - Correções da story após merge from DEV

50715 - Correções da story após merge from DEV

---

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoReabertura.cs

50715 - Tratamento de problema com jenkins

50715 - Tratamento de problema com jenkins

---

src/SME.SGP.Dados/Repositorios/RepositorioFechamentoReabertura.cs

[AB#52618](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52618)

fix/52618 - correção query reabertura

---

src/SME.SGP.Dados/Repositorios/RepositorioFechamentoReabertura.cs

[AB#52620](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52620)

52620 - Ajuste de pesquisa de períodos de reabertua (com ou sem dre/ue)

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoReabertura.cs

[AB#52624](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52624)

fix/52624 - Correção de TipoCalendario - null reference

---

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/NotificarFechamentoReaberturaUseCase.cs

[AB#50715](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50715)

50715 - Correção do group by de DRE´s

---

src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs

Ajuste no mapeamento de DTO para domínio ao salvar o plano de aula.

Bug: 52689

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs

Ajuste na funcionalidade de obter notas e frequência com tratamento para dados finais.

Bug: 52805

---

src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoRegistrosPedagogicos.cs

[AB#52603](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52603)

52603 - Correção da query de consolidação, faltava um join para trazer a quantidade correta

---

scripts/V503__PENDENCIA_PERFIL_E_PENDENCIA_PERFIL_USUARIO_CREATE.sql
src/SME.SGP.Dados/Mapeamentos/PendenciaPerfilMap.cs
src/SME.SGP.Dados/Mapeamentos/PendenciaPerfilUsuarioMap.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendenciaPerfil.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendenciaPerfilUsuario.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaPerfil.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaPerfilUsuario.cs
src/SME.SGP.Dominio/Entidades/PendenciaPerfil.cs
src/SME.SGP.Dominio/Entidades/PendenciaPerfilUsuario.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#52751](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52751)

52751 - Modelagem DB

---

src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs

[AB#52751](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52751)

52751 - ajuste de dependências

---

src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs

[AB#52352](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52352)

Ajuste nas validações das datas da criação da aula

---

src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs

Ajuste na funcionalidade de reprocessar situação do conselho de classe dos alunos, removendo a obrigatoriedade de conselho nota.

Bug: 50114

---

src/SME.SGP.Aplicacao/CasosDeUso/Devolutiva/InserirDevolutivaUseCase.cs

[AB#52938](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52938)

fix/52938 - Ajustado a mensagem

---

src/SME.SGP.Aplicacao/Consultas/ConsultasPeriodoFechamento.cs
src/SME.SGP.Aplicacao/Queries/PeriodoFechamento/ObterPeriodoFechamentoPorTurmaBimestrePeriodoEscolar/ObterPeriodoFechamentoPorTurmaBimestrePeriodoEscolarQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioPeriodoFechamento.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoFechamento.cs

[AB#52926](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52926)

fix/52926 - Correção do retorno se pode editar ou não

---

src/SME.SGP.Aplicacao/Commands/Notificacao/ExecutaNotificacaoPeriodoFechamentoEncerrando/ExecutaNotificacaoPeriodoFechamentoEncerrandoCommandHandler.cs
src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs
src/SME.SGP.Aplicacao/Queries/Professores/ObterProfessoresTitularesDasTurmas/ObterProfessoresTitularesDasTurmasQuery.cs
src/SME.SGP.Aplicacao/Queries/Professores/ObterProfessoresTitularesDasTurmas/ObterProfessoresTitularesDasTurmasQueryHandler.cs

[AB#52926](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52926)

52926 Melhoria de Performance na execução das notificações de Fim do Periodo de Fechamento

---

scripts/V504__INCLUSAO_CAMPO_UEID_TABELA_PENDENCIA.sql
src/SME.SGP.Aplicacao/Commands/PendenciaAusenciaFechamento/SalvarPendenciaAusenciaFechamento/SalvarPendenciaAusenciaFechamentoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciaCalendarioUe/SalvarPendenciaCalendarioUe/SalvarPendenciaCalendarioUeCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivosCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciaProfessor/ExecutarVerificacaoPendenciaAvaliacaoCP/ExecutarVerificacaoPendenciaAvaliacaoCPCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciaProfessor/SalvarPendenciaAusenciaDeAvaliacaoProfessor/SalvarPendenciaAusenciaDeAvaliacaoProfessorCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciaUsuario/RelacionaPendenciaUsuario/RelacionaPendenciaUsuarioCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciaUsuario/SalvarPendenciaUsuario/SalvarPendenciaUsuarioCommand.cs
src/SME.SGP.Aplicacao/Commands/PendenciaUsuario/SalvarPendenciaUsuario/SalvarPendenciaUsuarioCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciasGerais/SalvarPendencia/SalvarPendenciaCommand.cs
src/SME.SGP.Aplicacao/Commands/PendenciasGerais/SalvarPendencia/SalvarPendenciaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarParecerCP/CadastrarParecerCPCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/Pendencias/GerarPendenciaPlanoAEE/GerarPendenciaPlanoAEECommand.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/Pendencias/GerarPendenciaPlanoAEE/GerarPendenciaPlanoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/Pendencias/GerarPendenciaValidacaoPlanoAEE/GerarPendenciaValidacaoPlanoAEECommandHandler.cs
src/SME.SGP.Dados/Mapeamentos/PendenciaMap.cs
src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs
src/SME.SGP.Dominio/Entidades/Pendencia.cs
src/SME.SGP.Dominio/Enumerados/PerfilUsuario.cs

[AB#52754](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52754)

52754 - Manutenção no cadastro de pendência

---

scripts/V505__FREQUENCIA_ALUNO_CALCULO_TOTALPRESENCAS

[AB#51759](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/51759)

Atualização da coluna 'total_presencas' 

---

scripts/V503__PENDENCIA_PERFIL_E_PENDENCIA_PERFIL_USUARIO_CREATE.sql
scripts/V504__INCLUSAO_CAMPO_UEID_TABELA_PENDENCIA.sql
src/SME.SGP.Aplicacao/Commands/PendenciaCalendarioUe/SalvarPendenciaCalendarioUe/SalvarPendenciaCalendarioUeCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivosCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciaPerfil/SalvarPendenciaPerfilCommand.cs
src/SME.SGP.Aplicacao/Commands/PendenciaPerfil/SalvarPendenciaPerfilCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciaUsuario/SalvarPendenciaUsuario/SalvarPendenciaUsuarioCommandHandler.cs
src/SME.SGP.Dados/Mapeamentos/PendenciaPerfilMap.cs
src/SME.SGP.Dados/Mapeamentos/PendenciaPerfilUsuarioMap.cs
src/SME.SGP.Dominio/Entidades/PendenciaPerfil.cs
src/SME.SGP.Dominio/Entidades/PendenciaPerfilUsuario.cs

[AB#52997](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52997)

Ajustes script, command, entidades de pendencia_perfil e pendencia_perfil_usuario

---

scripts manutencao/27128 - Frequencia - Impressao Justificativa/FREQUENCIA_ALUNO_CALCULO_TOTALPRESENCAS
scripts/V505__FREQUENCIA_ALUNO_CALCULO_TOTALPRESENCAS

[AB#51759](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/51759)

feature/51759 - Script de carga do campo total_presencas

---

src/SME.SGP.Dominio/Enumerados/TipoArquivo.cs

[AB#52977](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52977)

Ajuste no enum de tipo arquivo

---

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs

[AB#52753](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52753)

52753 - Alterar listagem de pendências

---

src/SME.SGP.Aplicacao/Commands/PendenciaPerfil/SalvarPendenciaPerfilCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/Pendencias/GerarPendenciaPlanoAEE/GerarPendenciaPlanoAEECommandHandler.cs
src/SME.SGP.Dominio/Entidades/PendenciaPerfil.cs

[AB#52973](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52973)

52973 Ajuste salvamento Perfil Pendencia

---

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs

[AB#53029](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53029)

Ajuste no filtro de alunos de turmas históricas

---

src/SME.SGP.Aplicacao/Commands/PendenciaAusenciaFechamento/SalvarPendenciaAusenciaFechamento/SalvarPendenciaAusenciaFechamentoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivos/VerificarPendenciaAulaDiasNaoLetivosCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciaProfessor/ExecutarVerificacaoPendenciaAvaliacaoCP/ExecutarVerificacaoPendenciaAvaliacaoCPCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciaProfessor/SalvarPendenciaAusenciaDeAvaliacaoProfessor/SalvarPendenciaAusenciaDeAvaliacaoProfessorCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PendenciasGerais/SalvarPendencia/SalvarPendenciaCommand.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/Pendencias/GerarPendenciaPlanoAEE/GerarPendenciaPlanoAEECommandHandler.cs
src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQueryHandler.cs
src/SME.SGP.Dominio.Servicos/ServicoPendenciaFechamento.cs
src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEAlunoTurmaDto.cs

[AB#53160](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53160)

53160 - ajustando salvar pendências e listagem

---

src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs

[AB#53310](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53310)

SGP Bugfix criar fila

---

src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs

[AB#53317](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53317)

Alterar  Description do relatório

---

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs
src/SME.SGP.Infra/Dtos/AcompanhamentoFrequencia/AlunoFrequenciaDto.cs

[AB#53309](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53309)

Retornar presenças e remotos para tela de acompanhamento de frequencia

---

src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaSgp/PublicarFilaSgpCommandHandler.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#53187](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53187)

53187 Corrigido injeção de usuario na publicação de mensagem na fila

---

src/SME.SGP.Aplicacao/CasosDeUso/PendenciasGerais/ExecutaVerificacaoPendenciasGeraisAulaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/PendenciasGerais/ExecutaVerificacaoPendenciasGeraisCalendarioUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/PendenciasGerais/ExecutaVerificacaoPendenciasGeraisEventosUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/PendenciasGerais/ExecutaVerificacaoPendenciasGeraisUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PendenciasGerais/IExecutaVerificacaoPendenciasGeraisAulaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PendenciasGerais/IExecutaVerificacaoPendenciasGeraisCalendarioUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PendenciasGerais/IExecutaVerificacaoPendenciasGeraisEventosUseCase.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#53187](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53187)

53187 melhoria de performance da execução das pendencias Gerais

---

src/SME.SGP.Aplicacao/Commands/PendenciaProfessor/ExecutarVerificacaoPendenciaAvaliacaoProfessor/ExecutarVerificacaoPendenciaAvaliacaoProfessorCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterQuantidadeAvaliacoesTurmaComponentePorUeNoPeriodo/ObterQuantidadeAvaliacoesTurmaComponentePorUeNoPeriodoQuery.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterQuantidadeAvaliacoesTurmaComponentePorUeNoPeriodo/ObterQuantidadeAvaliacoesTurmaComponentePorUeNoPeriodoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasPorUeModalidadeAno/ObterTurmasPorUeModalidadesAnoQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasPorUeModalidadeAno/ObterTurmasPorUeModalidadesAnoQueryHandler.cs
src/SME.SGP.Dados/Contexto/SgpContext.cs
src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtividadeAvaliativa.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurma.cs

[AB#53187](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53187)

53187 Pendencia Fechamento não faz mais referencia a UE

---

src/SME.SGP.Infra/Dtos/Relatorios/AcompanhamentoFrequencia/FiltroAcompanhamentoFrequenciaJustificativaDto.cs

Adicionado Atributo no dto
[AB#53332](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53332)

Ajustes no cabeçalho do relatório

---

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs

[AB#53187](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53187)

53187 Corrigido paginação da listagem de pendencias

---

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs

[AB#53394](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53394)

Correção da pesquisa do Período Escolar

---

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs

[AB#53405](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53405)

Ajustando o retorno de Presenças e Remotos da Aba Final (todos os bimestres)

---

src/SME.SGP.Api/Controllers/RelatorioController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/RelatorioOcorrencia/RelatorioOcorrenciasUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IRelatorioOcorrenciasUseCase.cs
src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
src/SME.SGP.Infra/Dtos/Relatorios/RelatorioOcorrencias/FiltroImpressaoOcorrenciaDto.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgpRelatorios.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#46906](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46906)

SGP - Endpoint chamada do relatório

---

src/SME.SGP.Infra/Dtos/Relatorios/RelatorioOcorrencias/FiltroImpressaoOcorrenciaDto.cs

[AB#46908](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/46908)

SGP - Alterado Atributo do DTO

---

scripts/V507__INSERT_PENDENCIA_PERFIL.sql

[AB#50651](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50651)

52764 - Criação de script para perfil de Pendencia_Perfil

---

scripts/V508__UPDATE_PENDENCIA_VINCULO_UEID.sql

[AB#53716](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53716)

53716 - Script Atualização de Pendencias, vinculando a uma UE

---

src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/CargaAtribuicaoPendenciasPerfilUsuarioUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Pendencias/ICargaAtribuicaoPendenciasPerfilUsuarioUseCase.cs
src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciaCarga/ObterPendenciaCargaQuery.cs
src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciaCarga/ObterPendenciaCargaQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendencia.cs
src/SME.SGP.Infra/Dtos/PendenciaPendente/PendenciaPendenteDto.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#52764](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52764)

Worker para carga de pendencia perfil usuário

---

scripts/V509__DELETE_PENDENCIA_USUARIO_EXISTINDO_PENDENCIA_PERFIL_USUARIO.sql

[AB#53618](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53618)

53618 - Exclusão de dados na Pendencia_Usuario após vinculo de Pendencia_Perfil_Usuario

---

src/SME.SGP.Api/Controllers/RelatorioController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/RelatorioOcorrencia/RelatorioOcorrenciasUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IRelatorioOcorrenciasUseCase.cs
src/SME.SGP.Dominio/Enumerados/TipoRelatorio.cs
src/SME.SGP.Infra/Dtos/Relatorios/RelatorioOcorrencias/FiltroImpressaoOcorrenciaDto.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgpRelatorios.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#26880](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/26880)

SGP Back 26880

---

src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterPodeCadastrarAulaPorData/ObterPodeCadastrarAulaPorDataQueryHandler.cs

[AB#52024](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52024)

Ajuste na montagem da mensagem de validação

---

scripts/V510__ADICIONAR_COLUNA_PERMITE_COMPENSACAO_FORA_PERIODO.sql
src/SME.SGP.Dados/Mapeamentos/CompensacaoAusenciaMap.cs
src/SME.SGP.Dominio/Entidades/CompensacaoAusencia.cs
src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs

[AB#53772](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53772)

53772 - Criar parâmetro de lançamento fora do período

---

src/SME.SGP.Aplicacao/CasosDeUso/Itinerancia/Notificacao/NotificacaoSalvarItineranciaUseCase.cs
src/SME.SGP.Dados/Repositorios/RepositorioTesteLog.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTesteLog.cs
src/SME.SGP.IoC/RegistraDependencias.cs

Implementação para tentar detectar o problema da mensagem cair no deadletter ao executar a notificação de salvar itinerancia.

Bug: 53043

---

src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs

[AB#53774](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53774)
[AB#53775](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53775)

Notificação de Compensação Extemporânea e alterado o salvar

---

src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverAtribuicaoPendenciasUsuariosUeFuncionarioUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverAtribuicaoPendenciasUsuariosUeUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/TratarAtribuicaoPendenciasUsuariosUseCase.cs
src/SME.SGP.Aplicacao/Queries/PendenciaPerfilUsuario/VerificaExistenciaDePendenciaPerfilUsuario/VerificaExistenciaDePendenciaPerfilUsuarioQuery.cs
src/SME.SGP.Aplicacao/Queries/PendenciaPerfilUsuario/VerificaExistenciaDePendenciaPerfilUsuario/VerificaExistenciaDePendenciaPerfilUsuarioQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendenciaPerfilUsuario.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaPerfilUsuario.cs
src/SME.SGP.Infra/Dtos/Pendencia/FiltroPendenciaPerfilUsuarioCefaiAdmUeDto.cs

[AB#53759](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53759)

53759 - ajustes pós alinhamento e validação

---

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioRegistroAusenciaAluno.cs
src/SME.SGP.Infra/Dtos/DisciplinaTotalDto.cs

[AB#53908](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53908)

Turmas do Território do Saber não está atualizando os dados

---

src/SME.SGP.Aplicacao/Commands/DiarioBordo/InserirDiarioBordo/InserirDiarioBordoCommandHandler.cs

52112 Corrigindo erro de ortografia

---

src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverAtribuicaoPendenciasUsuariosUeUseCase.cs

[AB#53998](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53998)

53998 - ajustes após repasse

---

src/SME.SGP.Infra/Enumerados/Permissao.cs

[AB#53878](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53878)

Inclusão de Enum de permissões Listão

---

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterComponentesCurricularesPorUeAnosModalidadeUseCase/ObterComponentesCurricularesPorUeAnosModalidadeUseCase.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUeAnosModalidade/ObterComponentesCurricularesPorUeAnosModalidadeQueryHandler.cs

[AB#50915](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50915)

Ajuste na ordenação e no agrupamento dos componentes

---

src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs

[AB#52024](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52024)

Ajuste na validação de aulas já cadastradas para a data solicitada

---

src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs

Altera consulta de turma por código para turma por id no método de notificação de compensação de ausência da classe ServicoNotificacaoFrequencia.

AB#53773 - altera consulta de turma por código para turma por id

---

src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs
src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs

- Remove consultas desnecessárias no serviço de notificação de compensação de ausência.
- Adiciona verificação do parâmetro de sistema no serviço de compensação de ausência.

AB#53773 - realiza ajustes compensação de ausência

---

src/SME.SGP.Api/Controllers/TurmaController.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarParecerCP/CadastrarParecerCPCommandHandler.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasTurma.cs
src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasTurma.cs
src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs
src/SME.SGP.Dominio/Enumerados/TipoTurnoEOL.cs
src/SME.SGP.Infra/Dtos/Turma/FiltroTurmaDto.cs
src/SME.SGP.Infra/Dtos/Turma/ListaTurmasComComponenteDto.cs
src/SME.SGP.Infra/Dtos/Turma/RetornoConsultaListagemTurmaComponenteDto.cs

[AB#52860](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52860)

53879 - Endpoint de Turmas

---

src/SME.SGP.Api/Controllers/TurmaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasTurma.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Turma/IListarTurmasComComponentesUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasTurma.cs
src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ListagemTurmasComComponenteQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ListagemTurmasComComponenteQueryHandler.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#53879](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/53879)

53879 - Endpoint de Turmas (ajustes)

---

src/SME.SGP.Aplicacao/Commands/DeletarArquivo/RemoverArquivosExcluidosCommandHandler.cs

Ajuste na rotina de remover arquivos, onde é feita uma verificação específica no caso de acompanhamento para tentar excluir no diretório antigo.

Bug: 54056

---

src/SME.SGP.Aplicacao/Commands/PendenciaCalendarioUe/SalvarPendenciaCalendarioUe/SalvarPendenciaCalendarioUeCommandHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendenciaPerfilUsuario.cs

[AB#54112](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54112)

54112 - Ajustes Pendencias sem UE 

---

src/SME.SGP.Aplicacao/CasosDeUso/CompensacaoAusencia/PeriodoDeCompensacaoAbertoUseCase.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoReabertura.cs

Ajusta query ObterReaberturaFechamentoBimestrePorDataReferencia, para considerar o período de fechamento geral que contempla todas as Dre's e Ue's.

AB#53773 - Ajusta query de reabertura de fechamento

---

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseUseCase.cs
src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasse.cs
src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAluno.cs
src/SME.SGP.Infra/Dtos/ComponenteCurricularDto.cs

Ajuste na rotina de consolidação de conselho ajustando o processo para determinar a situação.

Bug: 53987

---

scripts/V508__UPDATE_PENDENCIA_VINCULO_UEID.sql

[AB#54212](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54212)

ajuste query de atribuição ue_id em pendencia

---

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaPerfilUsuario.cs

[AB#54278](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54278)

54278 - ajuste query obter por situação

---

src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverAtribuicaoPendenciasUsuariosUeUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverAtribuicaoPendenciasUsuariosUseCase.cs
src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciaSemPendenciaPerfilUsuario/ObterPendenciaSemPendenciaPerfilUsuarioQuery.cs
src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciaSemPendenciaPerfilUsuario/ObterPendenciaSemPendenciaPerfilUsuarioQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendenciaUsuario.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendencia.cs

[AB#54304](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54304)

54304 - ajustes aprovação encaminhamento aee e plano aee

---

scripts/V511__ADICIONAR_COLUNA_COMPONENTE_CURRICULAR_TABELA_DIARIO_BORDO.sql
src/SME.SGP.Api/Controllers/ProfessorController.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasDisciplina.cs
src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs
src/SME.SGP.Dados/Mapeamentos/DiarioBordoMap.cs
src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricular.cs
src/SME.SGP.Dominio/Entidades/DiarioBordo.cs
src/SME.SGP.Infra/Dtos/DisciplinaDto.cs

[AB#54377](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54377)
[AB#54376](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54376)

SGP Backend - Alteração API  e Modelagem de Dados

---

src/SME.SGP.Api/Controllers/DiarioBordoController.cs
src/SME.SGP.Api/Controllers/ProfessorController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/AlterarDiarioBordoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/InserirDiarioBordoUseCase.cs
src/SME.SGP.Aplicacao/Commands/DiarioBordo/AlterarDiarioBordo/AlterarDiarioBordoCommand.cs
src/SME.SGP.Aplicacao/Commands/DiarioBordo/AlterarDiarioBordo/AlterarDiarioBordoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/DiarioBordo/InserirDiarioBordo/InserirDiarioBordoCommand.cs
src/SME.SGP.Aplicacao/Commands/DiarioBordo/InserirDiarioBordo/InserirDiarioBordoCommandHandler.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasDisciplina.cs
src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs
src/SME.SGP.Aplicacao/Queries/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfilQuery.cs
src/SME.SGP.Aplicacao/Queries/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesEolPorCodigoTurmaLoginEPerfilQueryHandler.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/AlterarDiarioBordoDto.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/InserirDiarioBordoDto.cs

[AB#54378](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54378)

SGP Backend - Manutenção na Persistência do DiarioBordo

---

scripts/V512__MOVER_DESENVOLVIMEN TO_AULA_PARA_DESCRICAO_TABELA_PLANO_AULA.sql

[AB#54402](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54402)

Script SGP para migração dos dados

---

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAula/ObterPlanoAulaUseCase.cs
src/SME.SGP.Aplicacao/Commands/Aulas/ExcluirAulaRecorrente/ExcluirAulaRecorrenteCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Aulas/ExcluirAulaUnica/ExcluirAulaUnicaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAula/MigrarPlanoAula/MigrarPlanoAulaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasPlanoAula.cs
src/SME.SGP.Dados/Mapeamentos/PlanoAulaMap.cs
src/SME.SGP.Dominio/Entidades/PlanoAula.cs
src/SME.SGP.Infra/Dtos/PlanoAulaDto.cs
src/SME.SGP.Infra/Dtos/PlanoAulaRetornoDto.cs

[AB#54403](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54403)

Alterar endpoints de plano de aula para não salvar ou alterar o campo desenvolvimento_aula 

---

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs

[AB#54376](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54376)

Correção do campo pai de componente curricular

---

src/SME.SGP.Api/Controllers/FrequenciaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/PlanoAula/ObterPlanoAulaUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
src/SME.SGP.Aplicacao/Pipelines/ValidacoesPipeline.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAula.cs
src/SME.SGP.Dominio.Servicos/ServicoUsuario.cs
src/SME.SGP.Dominio/Entidades/Usuario.cs
src/SME.SGP.Infra/Contexto/ContextoBase.cs
src/SME.SGP.Infra/Dtos/Aula/AulaSimplesDto.cs

Altera endpoint de datas, cria parâmetro para validar se o professor titular tem permissão para editar frequência e plano de aula do professor CJ, realiza limpeza de código.

AB#54394 - altera endpoint e cria parametro

---

src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Comunicados/SolicitarInclusaoComunicados/SolicitarInclusaoComunicadoEscolaAquiUseCase.cs

Ajuste para tentar capturar os detalhes da exceção.

Bug: 35892

---

src/SME.SGP.Aplicacao/CasosDeUso/CompensacaoAusencia/NotificarCompensacaoAusenciaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/CompensacaoAusencia/INotificarCompensacaoAusenciaUseCase.cs
src/SME.SGP.Dominio.Interfaces/Servicos/IServicoNotificacaoFrequencia.cs
src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs
src/SME.SGP.Dominio.Servicos/ServicoNotificacaoFrequencia.cs
src/SME.SGP.Infra/Dtos/CompensacaoAusencia/FiltroNotificacaoCompensacaoAusenciaDto.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#54898](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54898)

54898 Movido notificação de compensação de Ausência para o Worker Rabbit

---

src/SME.SGP.Api/Controllers/FrequenciaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/InserirFrequenciaListaoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/IInserirFrequenciaListaoUseCase.cs
src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaAulasDoDiaDto.cs
src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaSalvarDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#54417](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54417)

54417 - Endpoint salvar frequência listão

---

src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioLogado/ObterUsuarioLogadoQueryHandler.cs

[AB#48442](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/48442)

Ajuste na query de obter usuario logado

---

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
src/SME.SGP.Dominio/Entidades/ComponenteCurricularEol.cs

Correção para exibir componentes curriculares (CP/AD)

Correção para exibir componentes curriculares (CP/AD)

---

src/SME.SGP.Infra/Dtos/Turma/RetornoConsultaListagemTurmaComponenteDto.cs

[AB#55082](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55082)

Correção do complemento da turma

---

src/SME.SGP.Api/Controllers/ProfessorController.cs
src/SME.SGP.Aplicacao/CasosDeUso/ComponentesCurriculares/ObterComponentesCurricularesPorProfessorETurmasCodigosUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ComponentesCurriculares/IObterComponentesCurricularesPorProfessorETurmasCodigosUseCase.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUsuarioECodigoTurma/ObterComponentesCurricularesPorUsuarioECodigoTurmaQuery.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUsuarioECodigoTurma/ObterComponentesCurricularesPorUsuarioECodigoTurmaQueryHandler.cs

[AB#55115](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55115)

Correção do componente curricular

---

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ConciliacaoFrequenciaTurmasPorPeriodoUseCase.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/ConciliacaoFrequenciaTurmas/ConciliacaoFrequenciaTurmasCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/ValidaAusenciaParaConciliacaoFrequenciaTurma/ValidaAusenciaParaConciliacaoFrequenciaTurmaCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Frequencia/IConciliacaoFrequenciaTurmasPorPeriodoUseCase.cs
src/SME.SGP.Infra/Dtos/FrequenciaCalculo/ConciliacaoFrequenciaTurmaPorPeriodoDto.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.IoC/RegistraDependenciasWorkerServices.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

Fragmentando a publicação de mensagens de conciliação de turmas por períodos criamos processos menores e com isso a diminuição de incidencia de restarts e acumulo de mensagens
[AB#55141](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55141)

55141 Separado processo de conciliação com a fila por periodos

---

src/SME.SGP.Api/Controllers/AulaController.cs
src/SME.SGP.Api/Controllers/EventosAulasCalendarioController.cs
src/SME.SGP.Api/Controllers/FrequenciaController.cs
src/SME.SGP.Api/Controllers/PendenciasController.cs
src/SME.SGP.Aplicacao/CasosDeUso/PendenciasGerais/ObterPendenciasUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PendenciasGerais/IObterPendenciasUseCase.cs
src/SME.SGP.Aplicacao/Pipelines/ValidacoesPipeline.cs
src/SME.SGP.Aplicacao/Queries/Bimestre/ObterModalidadePorPendencia/ObterModalidadePorPendenciaQuery.cs
src/SME.SGP.Aplicacao/Queries/Bimestre/ObterModalidadePorPendencia/ObterModalidadePorPendenciaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesQuePodeVisualizar/ObterComponentesCurricularesQuePodeVisualizarHojeQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/EOL/ComponentesCurriculares/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfil/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfilQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQuery.cs
src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolar.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendencia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoEscolar.cs
src/SME.SGP.Dominio/Enumerados/TipoPendenciaGrupo.cs
src/SME.SGP.Dominio/Extensoes/EnumExtension.cs
src/SME.SGP.Infra/Dtos/AcompanhamentoFrequencia/FiltroTurmaAlunoSemestreDto.cs
src/SME.SGP.Infra/Dtos/Pendencia/FiltroPendenciasUsuarioDto.cs
src/SME.SGP.Infra/Dtos/Pendencia/PendenciaTelaInicialDto.cs
src/SME.SGP.Infra/Dtos/PendenciaPerfilUsuario/PendenciaPerfilUsuarioDto.cs

[AB#54434](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54434)

54434 - endpoint de pendencias

---

src/SME.SGP.Api/Controllers/FrequenciaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasDetalhadasPorDataUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Frequencia/IObterFrequenciasDetalhadasPorDataUseCase.cs
src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciasDetalhadasPorData/ObterFrequenciasDetalhadasPorDataQuery.cs
src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciasDetalhadasPorData/ObterFrequenciasDetalhadasPorDataQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioFrequencia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequencia.cs
src/SME.SGP.Infra/Dtos/Frequencia/FiltroFrequenciaDetalhadaDto.cs
src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaDetalhadaDto.cs
src/SME.SGP.Infra/Dtos/FrequenciaDetalhadaPorDataDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#54416](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54416)

Inclusão de Endpoint Detalhar Pendencia

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQueryHandler.cs
src/SME.SGP.Infra/Dtos/Turma/FiltroTurmaDto.cs

[AB#55085](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55085)

Incluir filtro de histórico de Turmas

---

src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendencia.cs

[AB#55235](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55235)

55235 - Ajustes paginação e filtros

---

src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDia/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDiaQueryHandler.cs
src/SME.SGP.Dominio/Entidades/Usuario.cs

[AB#55250](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55250)
[AB#55297](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55297)

AB#55250 - corrige objeto de retorno para calendário do professor.

---

src/SME.SGP.Aplicacao/Queries/AreaDoConhecimento/ObterAreasConhecimento/ObterAreasConhecimentoQueryHandler.cs

[AB#50614](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50614)

50614 adicionando filtra para nao deixar passar valor nullo

---

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasDetalhadasPorDataUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasPorPeriodoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/PeriodosEscolares/ObterPeriodosPorComponenteUseCase.cs
src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaAulaPorDataPeriodoDto.cs
src/SME.SGP.Infra/Dtos/Frequencia/RegistroFrequenciaPorDataPeriodoDto.cs

[AB#55265](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55265)

Ajuste endpoint de frequências - agrupar com detalhes

---

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasAutomaticamente/CriarAulasRegenciaAutomaticamenteCommandHandler.cs

[AB#52025](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52025)

52025 ajustando as buscas das aulas bilingue

---

src/SME.SGP.Aplicacao/Consultas/ConsultaAtividadeAvaliativa.cs
src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDia/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDiaQueryHandler.cs
src/SME.SGP.Dominio/Entidades/Usuario.cs
src/SME.SGP.Infra/Dtos/AtividadeAvaliativaCompletaDto.cs

[AB#55253](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55253)

SGP Back - fix/55253

---

src/SME.SGP.Aplicacao/CasosDeUso/Aula/InserirFrequenciaListaoUseCase.cs
src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaAulasDoDiaDto.cs
src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaSalvarDto.cs

[AB#54417](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/54417)

54417 - Ajustes Endpoint salvar

---

src/SME.SGP.Aplicacao/Comandos/ComandosSupervisor.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasTurma.cs
src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs

Ajuste na funcionalidade de obter dados de aluno para conselho adicionando o parâmetro para considerar alunos inativos.

Bug: 55183

---

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs

[AB#55437](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55437)

55437 - Ajuste validação na query de pendências

---

src/SME.SGP.Aplicacao/Queries/RegistroIndividual/ListarAlunosDaTurmaPorComponenteRegistroIndividual/ListarAlunosDaTurmaPorComponenteRegistroIndividualQueryHandler.cs
src/SME.SGP.Infra/Dtos/AlunoDadosBasicosDto.cs

[AB#55378](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55378)

Ajuste na logica de obter a situação dos alunos

---

src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoFinal.cs

[AB#55267](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55267)
Permitida a edição de notas nulas

Fix/55267 - master

---

src/SME.SGP.Infra/Dtos/Frequencia/AulaFrequenciaDto.cs
src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaAulaDetalheDto.cs
src/SME.SGP.Infra/Dtos/Frequencia/RegistroFrequenciaPorDataPeriodoDto.cs

[AB#55536](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55536)

55536 - ajustes flag de aula reposição

---

src/SME.SGP.Dominio.Servicos/ServicoCalculoParecerConclusivo.cs

Ajuste na funcionalidade de validar parecer da frequência no conselho de classe definindo a turma ao obter os componentes necessários.

Bug: 55538

---

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasAutomaticamente/CriarAulasRegenciaAutomaticamenteCommandHandler.cs
src/SME.SGP.Dominio/Entidades/Turma.cs

Ajuste na rotina de criação de aulas para regência ajustando duplicidades e substituição de frequência.

Bug: 54593

---

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasPorPeriodoUseCase.cs
src/SME.SGP.Infra/Dtos/Aluno/AlunoRegistroFrequenciaDto.cs
src/SME.SGP.Infra/Dtos/Frequencia/FiltroFrequenciaPorPeriodoDto.cs

[AB#55634](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55634)

Corrigido carga de Componentes do Territorio

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs

[AB#55497](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55497) 
[AB#55608](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55608)

Fix/55497 - Situação do conselho não está sendo atualizada

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQueryHandler.cs

[AB#55618](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55618)

Correção dos componentes curriculares de professores CJ

---

src/SME.SGP.Api/Controllers/PeriodoEscolarController.cs
src/SME.SGP.Aplicacao/CasosDeUso/PeriodosEscolares/ObterPeriodosPorComponenteUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PeriodosEscolares/IObterPeriodosPorComponenteUseCase.cs

[AB#55677](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55677)

Frequencia não deve retornar data futuras, já Plano de Aula sim

---

src/SME.SGP.Api/Controllers/DiarioBordoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/ObterDatasDiarioBordoPorPeriodoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DiarioBordo/IObterDatasDiarioBordoPorPeriodoUseCase.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterCodigoComponentePai/ObterCodigoComponentePaiQuery.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterCodigoComponentePai/ObterCodigoComponentePaiQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDatasDiarioBordoPorPeriodo/ObterDatasDiarioBordoPorPeriodoQuery.cs
src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDatasDiarioBordoPorPeriodo/ObterDatasDiarioBordoPorPeriodoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAula.cs
src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricular.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAula.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioComponenteCurricular.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoPorPeriodoDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#55666](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55666)

55666 - 4 e 5: Endpoint Listagem

---

src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs

[AB#55808](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55808)

55808 adicionando a situação do concluido

---

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasAutomaticamente/CriarAulasRegenciaAutomaticamenteCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommandHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs

[AB#55684](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55684)

55684 listando todas as aulas

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

[AB#55531](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55531)

Correção no FechamentoTurma

---

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
src/SME.SGP.Aplicacao/Queries/AreaDoConhecimento/ObterAreasConhecimento/ObterAreasConhecimentoQueryHandler.cs

[AB#55443](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55443)

Ajuste na busca dos componentes de regência para cj

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

[AB#55531](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55531)

Transação usava contexto de consulta

---

src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterCompensacaoAusenciaPorAnoTurmaENome/ObterCompensacaoAusenciaPorAnoTurmaENomeQuery.cs
src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusenciaConsulta.cs

[AB#55903](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55903)

Ajuste no obter compensações de ausência

---

src/SME.SGP.Dados/Repositorios/RepositorioUeConsulta.cs

Ajuste da pesquisa de UE

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasFrequencia.cs
src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterBimestresPorTipoCalendario/ObterBimestresPorTipoCalendarioQuery.cs
src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterBimestresPorTipoCalendario/ObterBimestresPorTipoCalendarioQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolarConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoEscolarConsulta.cs

[AB#55889](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55889)

55889 Correção Calculo Frequência Global do object card

---

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs

[AB#55889](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55889)

55889 Corrigido calculo de frequencia final do acompanhamento de frequencia

---

src/SME.SGP.Aplicacao/Comandos/ComandosWorkflowAprovacao.cs
src/SME.SGP.Aplicacao/Queries/Notificacoes/ObterNotificacaoUltimoCodigoPorAno/ObterNotificacaoUltimoCodigoPorAnoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioNotificacaoConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotificacaoConsulta.cs
src/SME.SGP.Dominio.Interfaces/Servicos/IServicoWorkflowAprovacao.cs
src/SME.SGP.Dominio.Servicos/ServicoNotificacao.cs
src/SME.SGP.Dominio.Servicos/ServicoUsuario.cs
src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs

Fazer o tratamento da persistência para evitar problemas com pods

Fazer o tratamento da persistência para evitar problemas com pods

---

src/SME.SGP.Aplicacao/CasosDeUso/Devolutiva/Notificacao/SalvarNotificacaoDevolutivaUseCase.cs
src/SME.SGP.Aplicacao/Commands/Relatorios/Devolutivas/SolicitaRelatorioDevolutivasCommand.cs
src/SME.SGP.Aplicacao/Commands/Relatorios/Devolutivas/SolicitaRelatorioDevolutivasCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesDoProfessorNaTurma/ObterComponentesCurricularesDoProfessorNaTurmaQuery.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesDoProfessorNaTurma/ObterComponentesCurricularesDoProfessorNaTurmaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Professores/ObterProfessoresTitularesDaTurmaCompletos/ObterProfessoresTitularesDaTurmaCompletosQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricular.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioComponenteCurricular.cs
src/SME.SGP.Infra/Dtos/Relatorios/Devolutivas/FiltroRelatorioDevolutivasSincrono.cs

[AB#55658](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55658)

Alteração da Notificação de Devolutiva

---

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasAutomaticamente/CriarAulasRegenciaAutomaticamenteCommandHandler.cs

54593 ajustando filtro de dias úteis

---

src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoAluno.cs

Ajustando repositório de leitura x escrita

---

src/SME.SGP.Api/Controllers/DiarioBordoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/InserirAlterarDiarioBordoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/ObterDatasDiarioBordoPorPeriodoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DiarioBordo/IInserirAlterarDiarioBordoUseCase.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoListaoDto.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/InserirAlterarDiarioBordoDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#56032](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56032)

56032 - Novo endpoint salvar/alterar de diário de bordo (listão)

---

src/SME.SGP.Api/Controllers/DiarioBordoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/InserirAlterarDiarioBordoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/ObterDatasDiarioBordoPorPeriodoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DiarioBordo/IInserirAlterarDiarioBordoUseCase.cs
src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterListagemDiariosDeBordoPorPeriodo/ObterListagemDiariosDeBordoPorPeriodoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
src/SME.SGP.Infra/Dtos/AuditoriaDiarioBordoDto.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoResumoDto.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoTituloDto.cs

[AB#55945](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55945)

55945 - ajustes alinhamento back e front (diário de bordo - listão)

---

src/SME.SGP.Aplicacao/CasosDeUso/Devolutiva/Notificacao/SalvarNotificacaoDevolutivaUseCase.cs
src/SME.SGP.Aplicacao/Commands/Log/SalvarLogViaRabbit/SalvarLogViaRabbitCommandHandler.cs
src/SME.SGP.Infra/Dtos/Devolutiva/Notificacao/SalvarNotificacaoDevolutivaDto.cs
src/SME.SGP.Infra/Dtos/Relatorios/Devolutivas/FiltroRelatorioDevolutivasSincrono.cs

[AB#55657](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55657)

SGP - Feature/55657

---

src/SME.SGP.Aplicacao/Consultas/ConsultasNotificacao.cs

[AB#56008](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56008)

56008 removendo links das notificações

---

scripts/V515__ADICIONAR_COLUNA_INSERIDOCJ_TABELA_DIARIO_BORDO.sql
src/SME.SGP.Dados/Mapeamentos/DiarioBordoMap.cs
src/SME.SGP.Dominio/Entidades/DiarioBordo.cs

[AB#55713](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55713)

55713 - (Modelagem DB) novo campo "inserido_cj" em diario de bordo

---

src/SME.SGP.Aplicacao/Commands/DiarioBordo/InserirDiarioBordo/InserirDiarioBordoCommandHandler.cs

55714 - ajustes endpoint salvar diário de bordo, com o indicativo de CJ

---

src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
src/SME.SGP.Infra/Dtos/Devolutiva/DiarioBordoDevolutivaDto.cs

[AB#56104](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56104)
[AB#56107](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56107)

SGP  Backend - Correção - Não está salvando o texto da devolutiva

---

src/SME.SGP.Aplicacao/CasosDeUso/Devolutiva/Notificacao/SalvarNotificacaoDevolutivaUseCase.cs
src/SME.SGP.Aplicacao/Commands/Relatorios/Devolutivas/SolicitaRelatorioDevolutivasCommandHandler.cs

[AB#56108](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56108)
[AB#56122](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56122)

SGP Backend - Erro interno ao fazer download do Relatório de Devolutivas

---

src/SME.SGP.Aplicacao/Queries/PlanoAula/ObterPlanoAulasPorTurmaEComponentePeriodo/ObterPlanoAulasPorTurmaEComponentePeriodoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioPlanoAula.cs
src/SME.SGP.Dominio/Entidades/Aula.cs
src/SME.SGP.Infra/Dtos/PlanoAula/PlanoAulaObjetivosAprendizagemDto.cs
src/SME.SGP.Infra/Dtos/PlanoAulaRetornoDto.cs

[AB#55681](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55681)

Retornar se a aula EhReposicao ou Normal - Validação de plano de aula

---

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterInformacoesDeFrequenciaAlunoPorSemestreUseCase.cs
src/SME.SGP.Infra/Dtos/AcompanhamentoFrequencia/FrequenciaAlunoBimestreDto.cs

[AB#55760](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55760)

55760 - Alterar endpoint de Frequencias no RAA

---

src/SME.SGP.Dados/Repositorios/RepositorioAula.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoPorPeriodoDto.cs

[AB#55715](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55715)

55715 - Inclusão indicativo CJ no endpoint do diário de bordo listão

---

src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDiarioDeBordoPorId/ObterDiarioDeBordoPorIdQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoDetalhesDto.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoResumoDto.cs

[AB#55716](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55716)

55716 - ajuste obter diário de bordo, com a informação de "inseridoCJ"

---

src/SME.SGP.Aplicacao/CasosDeUso/Devolutiva/Notificacao/SalvarNotificacaoDevolutivaUseCase.cs
src/SME.SGP.Aplicacao/Commands/Devolutiva/Inserir/InserirDevolutivaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Relatorios/Devolutivas/SolicitaRelatorioDevolutivasCommandHandler.cs

Alterado fluxo de inserir devolutiva
[AB#56122](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56122)

Alterado fluxo de inserir devolutiva

---

src/SME.SGP.Dados/Repositorios/RepositorioPlanoAula.cs

[AB#55681](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55681)

Correção do retorno do TipoAula de PlanoAula

---

src/SME.SGP.Dominio.Servicos/ServicoCalculoParecerConclusivo.cs

[AB#55885](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55885)

55885 Correção carga de ano dos parâmetros para rodar o reprocessamento de todos os pareceres conclusivos

---

src/SME.SGP.Api/Controllers/PlanoAulaController.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/PlanoAula/ObterPlanoAulasPorTurmaEComponentePeriodo/ObterPlanoAulasPorTurmaEComponentePeriodoQueryHandler.cs

Correções do PR #8473

---

src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/ObterProfessoresTitularesECjsUseCase.cs

[AB#56332](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56332)

56332 - ajuste endpoint atribuição CJ 

---

src/SME.SGP.Aplicacao/Queries/TipoCalendario/VerificarRegistroExistenteTipoCalendario/VerificarRegistroExistenteTipoCalendarioQuery.cs

[AB#56413](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56413)

Correção validação no cadastro de calendário

---

src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/AlterarAnotacaoFrequenciaAlunoUseCase.cs
src/SME.SGP.Aplicacao/Comandos/ComandosPlanoAnual.cs
src/SME.SGP.Aplicacao/Comandos/ComandosPlanoAnualTerritorioSaber.cs
src/SME.SGP.Aplicacao/Comandos/ComandosPlanoCiclo.cs
src/SME.SGP.Aplicacao/Comandos/ComandosRelatorioSemestralPAPAluno.cs
src/SME.SGP.Aplicacao/Commands/Ocorrencia/AlterarOcorrencia/AlterarOcorrenciaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Ocorrencia/InserirOcorrencia/InserirOcorrenciaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanejamentoAnual/Salvar/SalvarPlanejamentoAnualCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosPlanoAnual.cs
src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs

[AB#56407](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56407)

Alterando o caminho do arquivo com base no command que os move

---

src/SME.SGP.Aplicacao/CasosDeUso/CompensacaoAusencia/PeriodoDeCompensacaoAbertoUseCase.cs

Ajuste na verificação de período aberto ao lançar compensação de ausência.

Bug: 56458

---

src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/ObterProfessoresTitularesECjsUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/ObterDiarioBordoUseCase.cs
src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs
src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoDto.cs

[AB#51916](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/51916)

51916 - ajuste endpoint de atribuição cj + label de inseridoCJ

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesUseCase.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesQuePodeVisualizar/ObterComponentesCurricularesQuePodeVisualizarHojeQuery.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesQuePodeVisualizar/ObterComponentesCurricularesQuePodeVisualizarHojeQueryHandler.cs

[AB#56374](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56374)

Educação infantil deverá agrupar componentes

---

src/SME.SGP.Api/Controllers/ConselhoClasseController.cs
src/SME.SGP.Aplicacao/CasosDeUso/ParecerConclusivo/ReprocessarParecerConclusivoAlunoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/ParecerConclusivo/ReprocessarParecerConclusivoPorAnoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/ParecerConclusivo/ReprocessarParecerConclusivoPorDreUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/ParecerConclusivo/ReprocessarParecerConclusivoPorTurmaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/ParecerConclusivo/ReprocessarParecerConclusivoPorUeUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ParecerConclusivo/IReprocessarParecerConclusivoAlunoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ParecerConclusivo/IReprocessarParecerConclusivoPorAnoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ParecerConclusivo/IReprocessarParecerConclusivoPorDreUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ParecerConclusivo/IReprocessarParecerConclusivoPorTurmaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ParecerConclusivo/IReprocessarParecerConclusivoPorUeUseCase.cs
src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterConselhoClasseAlunosPorAno/ObterConselhoClasseAlunosPorTurmaQuery.cs
src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterConselhoClasseAlunosPorAno/ObterConselhoClasseAlunosPorTurmaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterCodigosTurmasPorUeAno/ObterCodigosTurmasPorUeAnoQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterCodigosTurmasPorUeAno/ObterCodigosTurmasPorUeAnoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAluno.cs
src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoConsulta.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseAluno.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseAlunoConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurmaConsulta.cs
src/SME.SGP.Infra/Dtos/ConselhoClasseFechamentoAlunoDto.cs
src/SME.SGP.Infra/Dtos/Ue/FiltroDreUeTurmaDto.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#55885](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55885)

55885 Criado recalculo do parecer conclusivo por Ano pelo Rabbit

---

src/SME.SGP.Api/Controllers/ProfessorController.cs
src/SME.SGP.Aplicacao/CasosDeUso/ComponentesCurriculares/ObterComponentesCurricularesPorProfessorETurmasCodigosUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ComponentesCurriculares/IObterComponentesCurricularesPorProfessorETurmasCodigosUseCase.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUsuarioECodigoTurma/ObterComponentesCurricularesPorUsuarioECodigoTurmaQuery.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUsuarioECodigoTurma/ObterComponentesCurricularesPorUsuarioECodigoTurmaQueryHandler.cs

[AB#56483](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56483)
[AB#56484](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56484)

Componente Curricular fixo para o ano de 2022

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs

[AB#56515](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56515)
[AB#56374](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56374)

Correção - Detalhes da Aula não aparece para professor de componente curricular EMEI 2H

---

scripts/V517__ADICIONAR_PARAMETRO_PLANEJAMENTODIARIO_COM_COMPONENTE.sql
src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs

[AB#56553](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56553)

SGP Back - Criado parametro para utilização de novo Layout

---

scripts/V517__ADICIONAR_PARAMETRO_PLANEJAMENTODIARIO_COM_COMPONENTE.sql

adicionado public

---

scripts/V517__ADICIONAR_PARAMETRO_PLANEJAMENTODIARIO_COM_COMPONENTE.sql

removido public

---

scripts/V517__ADICIONAR_PARAMETRO_PLANEJAMENTODIARIO_COM_COMPONENTE.sql

corrigido erro do flayer

---

src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoConsulta.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs

[AB#56541](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56541)

56541 Não considerar registros de Fechamento Excluidos

---

scripts/V516__ADICIONANDO_PARAMETRO_SISTEMA_CJ_EDITA_REGISTROS_TITULAR.sql
src/SME.SGP.Api/Controllers/EventosAulasCalendarioController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesUseCase.cs
src/SME.SGP.Aplicacao/Commands/DiarioBordo/InserirDiarioBordo/InserirDiarioBordoCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Turma/IObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Turma/IObterAulasEventosProfessorCalendarioPorMesUseCase.cs
src/SME.SGP.Aplicacao/Queries/AtribuicaoCJ/ObterAtribuicaoCJPorDreUeTurmaRF/ObterAtribuicaoCJPorDreUeTurmaRFQuery.cs
src/SME.SGP.Aplicacao/Queries/AtribuicaoCJ/ObterAtribuicaoCJPorDreUeTurmaRF/ObterAtribuicaoCJPorDreUeTurmaRFQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAtribuicaoCJ.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtribuicaoCJ.cs
src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
src/SME.SGP.Dominio/Extensoes/DateTimeExtension.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#56488](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56488)

56488 - Ajuste na visualização de aulas para o CJ 

---

src/SME.SGP.Api/Controllers/PlanoAEEController.cs
src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/SalvarAnotacaoFrequenciaAlunoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurma/ObterDadosDeLeituraDeComunicadosPorAlunosDaTurmaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs
src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEol/ObterAlunoPorCodigoEolQuery.cs
src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEol/ObterAlunoPorCodigoEolQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosPorCodigoEolNome/ObterAlunosPorCodigoEolNomeQuery.cs
src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosPorCodigoEolNome/ObterAlunosPorCodigoEolNomeQueryHandler.cs
src/SME.SGP.Infra/Dtos/PlanoAEE/FiltroPesquisaQuestoesPlanoAEEDto.cs
src/SME.SGP.Infra/Dtos/Relatorios/HistoricoEscolar/FiltroBuscaAlunosDto.cs

[AB#56479](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56479)

56479 adicionando a flag historico

---

src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs

50090 ajustando a query para validar somente a data

50090 ajustando query

---

src/SME.SGP.Aplicacao/CasosDeUso/ListaoAvaliacoes/ObterNotasParaAvaliacoesListaoUseCase.cs

[AB#52520](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/52520)

SGP Back - story/52520

---

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
src/SME.SGP.Aplicacao/Integracoes/Respostas/DisciplinaResposta.cs

[AB#56611](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56611)

Componentes curriculares de CJ Infantil estão duplicados

---

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs

[AB#56611](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56611)

Agrupamento de componentes em CJ

---

src/SME.SGP.Aplicacao/CasosDeUso/ListaoAvaliacoes/ObterNotasParaAvaliacoesListaoUseCase.cs

[AB#56607](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56607)

Inclusão das disciplinas de regencia

---

src/SME.SGP.Aplicacao/CasosDeUso/ListaoAvaliacoes/ObterNotasParaAvaliacoesListaoUseCase.cs

[AB#56653](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56653)

fix/56610 Validação atendido AEE

---

src/SME.SGP.Api/Controllers/AulaController.cs
src/SME.SGP.Api/Controllers/EventosAulasCalendarioController.cs
src/SME.SGP.Aplicacao/CasosDeUso/ListaoAvaliacoes/ObterNotasParaAvaliacoesListaoUseCase.cs
src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaUnica/InserirAulaUnicaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Aulas/ValidarComponentesDoProfessor/ValidarComponentesDoProfessorCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterPodeCadastrarAulaPorData/ObterPodeCadastrarAulaPorDataQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesDoProfessorNaTurma/ObterComponentesCurricularesDoProfessorNaTurmaQueryHandler.cs
src/SME.SGP.Dominio/Entidades/Usuario.cs

[AB#56622](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56622)

SGP Back - Fix/56622: Corrige erro de cadastro de aula por professor Ed. Infantil atribuído ao componente diferente de 512

---

src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs

[AB#56687](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56687)

fix/56634 Correção de aulas duplicadas

---

src/SME.SGP.Api/Controllers/EventosAulasCalendarioController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesUseCase.cs
src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesQuePodeVisualizar/ObterComponentesCurricularesQuePodeVisualizarHojeQueryHandler.cs

[AB#56622](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56622): Corrige erro de visualização de aulas únicas para professores da educação infantil de componentes curriculares distintos.

SGP Back - Corrige erro de visualização de aulas únicas

---

src/SME.SGP.Api/Controllers/NotasConceitosController.cs

[AB#56699](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56699)
[AB#56600](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56600)

Ajustes  nas permissões do enpoint

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs

[AB#56622](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56622)

Correção do detalhamento de aulas

---

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs

[AB#56602](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56602)

Correção somente para as turmas de 2022

---

src/SME.SGP.Aplicacao/Commands/PendenciasGerais/ExcluirPendenciaPorId/ExcluirPendenciaPorIdCommandHandler.cs

[AB#56632](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56632)

56632 - ajuste validação no encaminhamento AEE

---

src/SME.SGP.Dominio.Servicos/ServicoEvento.cs

[AB#55669](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/55669)

Ajuste na regra de cadastro de evento aos domingos

---

src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs

Ajustes no formato de Data Api EOL

Ajustes no formato de Data Api EOL

---

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs

[AB#56602](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56602)

Correção da abrangência sem turmas

---

src/SME.SGP.Aplicacao/Commands/Relatorios/Devolutivas/SolicitaRelatorioDevolutivasCommandHandler.cs

Adicionado throw new NegocioException para teste

Adicionado throw new NegocioException

---

src/SME.SGP.Aplicacao/Commands/Relatorios/Devolutivas/SolicitaRelatorioDevolutivasCommandHandler.cs

Adicionado catch

---

src/SME.SGP.Aplicacao/CasosDeUso/Devolutiva/Notificacao/SalvarNotificacaoDevolutivaUseCase.cs
src/SME.SGP.Aplicacao/Commands/Relatorios/Devolutivas/SolicitaRelatorioDevolutivasCommand.cs
src/SME.SGP.Aplicacao/Commands/Relatorios/Devolutivas/SolicitaRelatorioDevolutivasCommandHandler.cs

Correção da autenticação no endpoint

Correção da autenticação no endpoint

---

scripts/V518__ADICIONAR_TABELA_TIPO_TURMA_ITINERARIO.sql
src/SME.SGP.Dados/Mapeamentos/TipoTurmaItinerarioMap.cs
src/SME.SGP.Dados/Repositorios/RepositorioTipoTurmaItinerario.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTipoTurmaItinerario.cs
src/SME.SGP.Dominio/Entidades/TipoTurmaItinerario.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#56875](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56875)

Criar entidade db tipos_turma_itinerario, Entidade Back, Repositorio e registro de dependencias

---

src/SME.SGP.Aplicacao/CasosDeUso/SincronizacaoInstitucional/Turma/ExecutarSincronizacaoInstitucionalTurmaSyncUseCase.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterAnoLetivoTurmasVigentes/ObterAnoLetivoTurmasVigentesQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterAnoLetivoTurmasVigentes/ObterAnoLetivoTurmasVigentesQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterCodigosTurmasEOLPorUeIdParaSyncEstruturaInstitucional/ObterCodigosTurmasEOLPorUeIdParaSyncEstruturaInstitucionalQuery.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurma.cs

[AB#56863](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56863)

56863 - Alterar SincronizaçãoInstitucional

---

src/SME.SGP.Infra/Dtos/Relatorios/LeituraComunicados/FiltroRelatorioPlanejamentoDiario.cs

[AB#56923](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56923)

Adicionar os componentes curriculares disponíveis

---

src/SME.SGP.Aplicacao/CasosDeUso/PeriodosEscolares/ObterPeriodosPorComponenteUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasAula.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
src/SME.SGP.Aplicacao/Integracoes/Respostas/DisciplinaResposta.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarAulaCj/ObterPeriodoEscolaresPorTurmaBimestresAulaCjQuery.cs
src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarAulaCj/ObterPeriodoEscolaresPorTurmaBimestresAulaCjQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarPorTurmaBimestre/ObterPeriodoEscolarPorTurmaBimestreQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodosEscolaresPorComponenteBimestreTurma/ObterPeriodosEscolaresPorComponenteBimestreTurmaQuery.cs
src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodosEscolaresPorComponenteBimestreTurma/ObterPeriodosEscolaresPorComponenteBimestreTurmaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/PlanoAula/ObterPlanoAulasPorTurmaEComponentePeriodo/ObterPlanoAulasPorTurmaEComponentePeriodoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAula.cs
src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolar.cs
src/SME.SGP.Dados/Repositorios/RepositorioPlanoAula.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAula.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoEscolar.cs
src/SME.SGP.Infra/Dtos/PeriodoEscolar/PeriodoEscolarBimestreDto.cs
src/SME.SGP.Infra/Dtos/PeriodoEscolar/PeriodoEscolarComponenteDto.cs
src/SME.SGP.Infra/Dtos/PeriodoEscolar/PeriodoEscolarVerificaRegenciaDto.cs
src/SME.SGP.Infra/Dtos/PlanoAula/PlanoAulaObjetivosAprendizagemDto.cs
src/SME.SGP.Infra/Dtos/PlanoAulaRetornoDto.cs

[AB#56779](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56779)
[AB#56780](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56780)

Adequação de endpoint

---

src/SME.SGP.Aplicacao/CasosDeUso/SincronizacaoInstitucional/Turma/ExecutarSincronizacaoInstitucionalTurmaSyncUseCase.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterCodigosTurmasEOLPorUeIdParaSyncEstruturaInstitucional/ObterCodigosTurmasEOLPorUeIdParaSyncEstruturaInstitucionalQueryHandler.cs
src/SME.SGP.Worker.Rabbbit/SME.SGP.Worker.Rabbbit.csproj

[AB#56864](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56864)

56864 - Alterar Listagem de Turmas EOL

---

src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEol/ObterAlunoPorCodigoEolQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoConsulta.cs
src/SME.SGP.Dominio.Servicos/ServicoCalculoParecerConclusivo.cs

Ajuste na funcionalidade de cálculo de parecer, ajustando alguns pontos de verificação de aluno ativo, consulta para obter notas finais e o tratamento de conceito para determinar aprovado ou não.

Bug: 56596

---

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaFrequenciaAulas/ObterListaFrequenciaAulasQueryHandler.cs
src/SME.SGP.Infra/Dtos/Frequencia/AulaFrequenciaDto.cs
src/SME.SGP.Infra/Dtos/Frequencia/RegistroFrequenciaPorDataPeriodoDto.cs

[AB#56781](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56781)

Trazer a informação se é Aula CJ

---

src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#56988](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56988)

Adicionando informações de erro

---

src/SME.SGP.Dominio.Servicos/ServicoUsuario.cs

[AB#56983](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56983)

56983 - Erro interno no lançamento de notas

---

src/SME.SGP.Aplicacao/Commands/Aulas/ExcluirAulaRecorrente/ExcluirAulaRecorrenteCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs

[AB#56988](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56988)

Removido serviço e adicionado command

---

src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#56988](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56988)

Removendo stacktrace

---

src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaRecorrente/AlterarAulaRecorrenteCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Aulas/InserirAulaRecorrente/InserirAulaRecorrenteCommandHandler.cs

[AB#56988](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56988)

Ajuste de injeção do mediator

---

src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasAlunoPorFiltro/ObterTurmasAlunoPorFiltroQueryHandler.cs

[AB#57062](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57062)
[AB#57100](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57100)
Realizado debug na API do SGP e API EOL ,  quando não existe um registro na base a API EOL retorna 404 e uma mensagem  para o SGP , e o SGP estava devolvendo para o front o erro sem a mensagem tratada explicando o por que do erro para o usuário

Tela Conselho de Classe - erro ao lançar nota pós-conselho

---

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

[AB#57052](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57052)

Correção da verificação se pode persistir turma

---

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs
src/SME.SGP.Infra/Dtos/FrequenciaCalculo/RegistroFrequenciaPorDisciplinaAlunoDto.cs

[AB#57238](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57238)

57238 Corrigido calculo de total de aulas para frequencia

---

src/SME.SGP.Aplicacao/Queries/PlanoAula/ObterPlanoAulasPorTurmaEComponentePeriodo/ObterPlanoAulasPorTurmaEComponentePeriodoQueryHandler.cs

Ordenar Registros por data da Aula

Ordenar Registros por data da Aula

---

src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/GerarWFAprovacaoNotaConselhoClasse/GerarWFAprovacaoNotaConselhoClasseCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivo/GerarWFAprovacaoParecerConclusivoCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigo/ObterAlunoPorCodigoEAnoHistoricoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigo/ObterAlunoPorCodigoQuery.cs
src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmaAlunoPorCodigoAluno/ObterTurmaAlunoPorCodigoAlunoQuery.cs
src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmaAlunoPorCodigoAluno/ObterTurmaAlunoPorCodigoAlunoQueryHandler.cs

[AB#57159](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57159)
[AB#57062](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57062)

Ajuste aluno sem turma no EOL

---

src/SME.SGP.Aplicacao/Commands/Notificacao/ExecutaNotificacaoCadastroFechamentoReabertura/ExecutaNotificacaoCadastroFechamentoReaberturaCommandHandler.cs
src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs

[AB#57214](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57214)

57214 - ajuste para notificações não enviadas

---

src/SME.SGP.Aplicacao/Commands/Itinerancia/Notificacao/AprovarItinerancia/AprovarItineranciaCommandHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioItinerancia.cs
src/SME.SGP.Dominio/Entidades/Itinerancia.cs

[AB#57247](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57247)

Correção da consulta de DRE e UE

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs

[AB#57286](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57286)

57286 Liberado acesso a aba final sem o conselho do ultimo Bimestre para anos anteriores

---

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs

[AB#57251](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57251)

57251 - otimização query para filtrar turmas (pendências)

---

src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs

[AB#57214](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57214) [AB#57272](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57272)

57272 - ajuste para receber notificação de recusa

---

src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendencia.cs

[AB#57273](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57273)

57273 - ajuste para pendencias sem filtro

---

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs

[AB#57268](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57268)

57268 - ajuste na query para não trazer at. avaliativa excluída

---

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterAulasDadasPorTurmaDisciplinaEPeriodoEscolar/ObterAulasDadasPorTurmaDisciplinaEPeriodoEscolarQuery.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterAulasDadasPorTurmaDisciplinaEPeriodoEscolar/ObterAulasDadasPorTurmaDisciplinaEPeriodoEscolarQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAulaConsulta.cs

[AB#57276](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57276)

57276 - ajuste query de acompanhamento da frequência

---

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs

[AB#56644](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56644)

Ajuste na validação de perfil SME e Dre para buscar atribuição do professor

---

scripts/V515__ADICIONAR_COLUNA_TURMAID_TABELA_DIARIO_BORDO.sql
src/SME.SGP.Aplicacao/Commands/DiarioBordo/InserirDiarioBordo/InserirDiarioBordoCommandHandler.cs
src/SME.SGP.Dados/Mapeamentos/DiarioBordoMap.cs
src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
src/SME.SGP.Dominio/Entidades/DiarioBordo.cs

[AB#57204](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57204)

fix/57204 Dashboard Diario de Bordo Informações Incoerentes

---

src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/NotificarAprovacaoNotaConselho/NotificarAprovacaoNotaConselhoCommandHandler.cs

[AB#57262](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57262)

57262 - ajuste para notificar nota pós conselho e aprovar somente uma vez a notificação

---

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs

[AB#57251](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57251)
[AB#57322](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57322)

57251 - ajuste nos filtros da tela de pendência

---

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs

[AB#57251](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57251)

57251 - ajuste filtro AEE com turma

---

src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs

[AB#57249](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57249)

Ajuste na consulta de aulas para CJ

---

src/SME.SGP.Api/Controllers/ConselhoClasseController.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs
src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasConselhoClasse.cs

[AB#57286](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57286)

Obter conselho de classe final

---

src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs

[AB#57350](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57350)

57350 - ajuste query para obterporid em diario de bordo

---

src/SME.SGP.Aplicacao/CasosDeUso/ComponentesCurriculares/Sincronismo/SincronizarComponentesCurricularesUseCase.cs
src/SME.SGP.Aplicacao/Commands/ComponentesCurriculares/Alterar/AtualizarComponenteCurricularCommand.cs
src/SME.SGP.Aplicacao/Commands/ComponentesCurriculares/Alterar/AtualizarComponenteCurricularCommandHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricular.cs
src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioComponenteCurricular.cs
src/SME.SGP.Infra/Dtos/ComponenteCurricularDto.cs

[AB#57255](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57255)

Correção da rotina de atualização de componentes curriculares

---

src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs

[AB#57232](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57232)

57232 Incluso Atribuito "EmAprovacao" para o Parecer Conclusivo

---

src/SME.SGP.Api/Controllers/FechamentoFinalController.cs
src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoFinal.cs
src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaFechamento/EnviarNotasFechamentoParaAprovacao/EnviarNotasFechamentoParaAprovacaoCommand.cs
src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaFechamento/EnviarNotasFechamentoParaAprovacao/EnviarNotasFechamentoParaAprovacaoCommandHandler.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosFechamentoFinal.cs
src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosPorTurma/ObterAlunosPorTurmaQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotaConceitoBimestreConsulta.cs
src/SME.SGP.Dominio.Interfaces/Servicos/IServicoFechamentoFinal.cs
src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
src/SME.SGP.Infra/Dtos/AuditoriaPersistenciaDto.cs
src/SME.SGP.Infra/Dtos/FechamentoFinalConsultaRetornoAlunoNotaConceitoDto.cs
src/SME.SGP.Infra/Dtos/FechamentoNota/FechamentoNotaAlunoAprovacaoDto.cs

[AB#57231](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57231)

57231 Implementado WF de Aprovação para Notas de Fechamento Final

---

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs

[AB#57238](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57238)

57238 Corrigido calculo de aulas por componente

---

src/SME.SGP.Aplicacao/CasosDeUso/SincronizacaoInstitucional/Turma/ExecutarSincronizacaoInstitucionalTurmaSyncUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/SincronizacaoInstitucional/Turma/ExecutarSincronizacaoInstitucionalTurmaTratarUseCase.cs
src/SME.SGP.Aplicacao/Commands/SincronizacaoInstituicional/Abrangencia/TrataAbrangenciaHistoricaTurmaCommand.cs
src/SME.SGP.Aplicacao/Commands/SincronizacaoInstituicional/Abrangencia/TrataAbrangenciaHistoricaTurmaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/SincronizacaoInstituicional/Turmas/TrataSincronizacaoInstitucionalTurma/TrataSincronizacaoInstitucionalTurmaCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterUsuarioPossuiAbrangenciaAcessoSondagem/ObterUsuarioPossuiAbrangenciaAcessoSondagemQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasAbrangenciaHistoricaEOLAnoProfessor/ObterTurmasAbrangenciaHistoricaEOLAnoProfessorQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Turma/VerificaSeTurmaVirouHistorica/VerificaSeTurmaVirouHistoricaQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/VerificaSeTurmaVirouHistorica/VerificaSeTurmaVirouHistoricaQueryHandler.cs
src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAbrangencia.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurma.cs

[AB#56865](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56865) [AB#56866](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56866)

56865 - Atualizar abrangência para histórico

---

src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs
src/SME.SGP.Infra/Dtos/PlanoAulaDto.cs

Inclusão de informações de cópia

---

src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaAvaliacaoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaDiarioBordoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaFrequenciaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaPlanoAulaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaUseCase.cs
src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommand.cs
src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommandHandler.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/Pendencia/IPendenciaAulaAvaliacaoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/Pendencia/IPendenciaAulaDiarioBordoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/Pendencia/IPendenciaAulaFrequenciaUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/Pendencia/IPendenciaAulaPlanoAulaUseCase.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAula.cs
src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs
src/SME.SGP.IoC/RegistraDependencias.cs
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#57452](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57452)

57452 Separação de Filas de geração de Pendencias Aula

---

src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDiarioBordoNotificacao/ObterDiarioBordoNotificacaoQueryHandler.cs

[AB#57419](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57419)

Task 57419 Bugs 1,3

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterIndicativoPendenciasAulasPorTipo/ObterIndicativoPendenciasAulasPorTipoQuery.cs
src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterIndicativoPendenciasAulasPorTipo/ObterIndicativoPendenciasAulasPorTipoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/PendenciaFechamento/ObterIndicativoPendenciaFechamentoTurmaDisciplina/ObterIndicativoPendenciaFechamentoTurmaDisciplinaQuery.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAula.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAula.cs

[AB#57487](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57487)

57487 Corrigido consulta de Pendencias para o Listão

---

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAula.cs

[AB#57487](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57487)

57487 Considerar pendencias apenas de aulas normais

---

src/SME.SGP.Aplicacao/Commands/DiarioBordo/AdicionarObservacaoDiarioBordo/AdicionarObservacaoDiarioBordoCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/DiarioBordo/ListarObservacaoDiarioBordo/ListarObservacaoDiarioBordoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDiarioBordoNotificacao/ObterDiarioBordoNotificacaoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDiarioDeBordoPorId/ObterDiarioDeBordoPorIdQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordoObservacao.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDiarioBordoObservacao.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/ListarObservacaoDiarioBordoDto.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/ObservacaoNotificacoesDiarioBordoDto.cs

[AB#57521](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57521)
[AB#57419](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57419)

Fix/57419 - Bug 5

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs

[AB#57557](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57557)
[AB#57529](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57529)

Ajuste na regra de "Fechamento" para exibir a "flag de pendência" no listão

---

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaItinerarioEnsinoMedio/ObterTurmaItinerarioEnsinoMedioQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaItinerarioEnsinoMedio/ObterTurmaItinerarioEnsinoMedioQueryHandler.cs
src/SME.SGP.Infra/Dtos/Turma/TurmaItinerarioEnsinoMedioDto.cs

[AB#57559](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57559)

Pesquisa de turmas itinerário do ensino médio

---

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ConselhoClasse/ObterDetalhamentoFechamentoConselhoClasseAlunoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
src/SME.SGP.Aplicacao/Commands/ConselhoClasse/InserirTurmasComplementares/InserirTurmasComplementaresCommandHandler.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs
src/SME.SGP.Aplicacao/Queries/FechamentoTurma/ObterFechamentoTurmaPorIdAlunoCodigo/ObterFechamentoTurmaPorIdAlunoCodigoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipo/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipo/ObterTurmaCodigosAlunoPorAnoLetivoAlunoTipoTurmaQueryHandler.cs
src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs
src/SME.SGP.Dominio/Entidades/Turma.cs

[AB#57559](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57559)

Inclusão dos tipos itinerários do ensino médio

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
src/SME.SGP.Aplicacao/Comandos/ComandosNotasConceitos.cs
src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterAulaIdPorComponenteCurricularIdTurmaIdEDataProfessor/ObterAulaIdPorComponenteCurricularIdTurmaIdEDataProfessorQuery.cs
src/SME.SGP.Aplicacao/Queries/Aula/ObterAulaIdPorComponenteCurricularIdTurmaIdEDataProfessor/ObterAulaIdPorComponenteCurricularIdTurmaIdEDataProfessorQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DiarioBordo/ListarObservacaoDiarioBordo/ListarObservacaoDiarioBordoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDiarioBordoNotificacao/ObterDiarioBordoNotificacaoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDiarioDeBordoPorId/ObterDiarioDeBordoPorIdQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterIndicativoPendenciasAulasPorTipo/ObterIndicativoPendenciasAulasPorTipoQuery.cs
src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterIndicativoPendenciasAulasPorTipo/ObterIndicativoPendenciasAulasPorTipoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs
src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtividadeAvaliativa.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAulaConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs

[AB#57564](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57564)
[AB#57487](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57487)

Correção  funcionando o fluxo para Avaliações

---

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosAtivosPorTurmaCodigo/ObterAlunosAtivosPorTurmaCodigoQueryHandler.cs

[AB#57118](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57118)

Troca de endpoint para busca dos alunos no eol

---

src/SME.SGP.Dados/Repositorios/RepositorioPlanoAula.cs

[AB#57603](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57603)
[AB#57617](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57617)

 Erro interno ao copiar conteúdo de plano novo para plano já com dados.

---

src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs

[AB#57562](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57562)

Inclusão das turmas itinerárias do ensino médio

---

src/SME.SGP.Api/Controllers/AutenticacaoController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaAvaliacaoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaDiarioBordoUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaFrequenciaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaPlanoAulaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverAtribuicaoPendenciasUsuariosUeFuncionarioUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/RemoverAtribuicaoPendenciasUsuariosUeUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Pendencias/TratarAtribuicaoPendenciasUsuariosUseCase.cs
src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAtividadeAvaliativa/ObterPendenciasAtividadeAvaliativaQuery.cs
src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAtividadeAvaliativa/ObterPendenciasAtividadeAvaliativaQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAulasPorTipo/ObterPendenciasAulasPorTipoQuery.cs
src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAulasPorTipo/ObterPendenciasAulasPorTipoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/UE/ObterCodigoUEDREPorId/ObterCodigoUEDREPorIdQuery.cs
src/SME.SGP.Aplicacao/Queries/UE/ObterCodigoUEDREPorId/ObterCodigoUEDREPorIdQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
src/SME.SGP.Dados/Repositorios/RepositorioUeConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioUeConsulta.cs
src/SME.SGP.Infra/Dtos/DreUeCodigoDto.cs
src/SME.SGP.Infra/Dtos/DreUeDto.cs

[AB#57529](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57529)

57529 Segregação da geração de pendencias de aula por DRE para melhora de performance

---

src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs

This reverts commit 5495d26de2f8ce8e1bd4719e053166233c1d547e.

Revert "Inclusão das turmas itinerárias do ensino médio"

---

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
src/SME.SGP.Infra/Dtos/Relatorios/LeituraComunicados/FiltroRelatorioPlanejamentoDiario.cs

[AB#51798](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/51798)

BACK - Story/51798

---

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUsuarioECodigoTurma/ObterComponentesCurricularesPorUsuarioECodigoTurmaQueryHandler.cs

[AB#57590](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57590)

Ajuste do componente curricular

---

src/SME.SGP.Aplicacao/CasosDeUso/PeriodosEscolares/ObterPeriodosPorComponenteUseCase.cs
src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarAulaCj/ObterPeriodoEscolaresPorTurmaBimestresAulaCjQuery.cs
src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolarConsulta.cs

[AB#57830](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57830)
[AB#57869](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57869)

Looping infinito para carregar os períodos de anos anteriores

---

src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/ObterDatasDiarioBordoPorPeriodoUseCase.cs
src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDatasDiarioBordoPorPeriodo/ObterDatasDiarioBordoPorPeriodoQuery.cs
src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDatasDiarioBordoPorPeriodo/ObterDatasDiarioBordoPorPeriodoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAulaConsulta.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoPorPeriodoDto.cs

[AB#57864](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57864)

Correção da informação de aula de reposição

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQueryHandler.cs

[AB#57592](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57592)

 Adicionando filtro por início do ano letivo

---

src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordo/ObterDatasDiarioBordoPorPeriodoUseCase.cs
src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDatasDiarioBordoPorPeriodo/ObterDatasDiarioBordoPorPeriodoQuery.cs
src/SME.SGP.Aplicacao/Queries/DiarioBordo/ObterDatasDiarioBordoPorPeriodo/ObterDatasDiarioBordoPorPeriodoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAulaConsulta.cs

[AB#57951](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57951)

Retornado o filtro do componente cirricular filho que é selecionado na tela

---

src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs

[AB#57864](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57864)

Correção da consulta de diário de bordo para trazer reposição

---

src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoPorPeriodoDto.cs

[AB#57967](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57967)

Regra da exibição da pendência de diário de bordo parou de funcionar

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs

[AB#57948](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57948)
[AB#58048](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58048)

Erro ao acessar o atalho Avaliações quando o componente não lança nota

---

src/SME.SGP.Aplicacao/CasosDeUso/PeriodosEscolares/ObterPeriodosPorComponenteUseCase.cs

[AB#58045](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58045)

Retornar períodos somente com aula (não regência)

---

src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs

[AB#58047](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58047)

Validação para acesso a aba final em turmas de anos anteriores

---

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs

[AB#57951](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57951)

A busca das pendências não estava levando em consideração a data da aula

---

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs

[AB#57591](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57591)

Correção do cache de componentes curriculares infantil

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasNomeFiltroPorTurmasCodigos/ObterTurmasNomeFiltroPorTurmasCodigosQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasNomeFiltroPorTurmasCodigos/ObterTurmasNomeFiltroPorTurmasCodigosQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurmaConsulta.cs
src/SME.SGP.Infra/Dtos/Turma/RetornoConsultaListagemTurmaComponenteDto.cs
src/SME.SGP.Infra/Dtos/Turma/RetornoConsultaTurmaNomeFiltroDto.cs

[AB#58057](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58057)
[AB#57555](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57555)

Fix/58057 - Ajustar nome da turma

---

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaFrequenciaAulas/ObterListaFrequenciaAulasQueryHandler.cs
teste/SME.SGP.Aplicacao.Teste/CasosDeUso/ObterFrequenciaPorAulaUe/ObterFrequenciaPorAulaUeUseCaseTeste.cs

[AB#57926](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57926)

Correção da pesquisa de ativos

---

src/SME.SGP.Aplicacao/Commands/Arquivos/MoverArquivo/MoverArquivoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs

[AB#58101](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58101)
[AB#58120](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58120)

Plano de aula - Não está permitindo inserir imagens e vídeos dentro do campo "Objetivos específicos e desenvolvimento da aula" 

---

src/SME.SGP.Api/Controllers/FechamentoAcompanhamentoTurmasController.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs

[AB#58196](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58196)
[AB#57587](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57587)

Turmas não são listadas na tela

---

src/SME.SGP.Aplicacao/Queries/DashBoard/ObterDashBoardPorPerfil/ObterDashBoardPorPerfilQueryHandler.cs
src/SME.SGP.Infra/Enumerados/Permissao.cs

[AB#56242](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56242)
[AB#58191](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58191)

story/56242 - Exibir menu Listão na tela inicial para Professor, Professor CJ, Professor Ed. Infantil e Professor CJ Ed. Infantil 

---

src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs

add coalesce para tratar nome filtro null

add coalesce para tratar nome filtro null

---

src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs

[AB#58128](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58128)

58128 - ajuste na listagem de diário de bordo para itens pendentes

---

src/SME.SGP.Aplicacao/Commands/Frequencia/ExcluirFrequenciasPorRegistroFrequenciaId/ExcluirFrequenciasAlunoPorRegistroFrequenciaIdCommand.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/ExcluirFrequenciasPorRegistroFrequenciaId/ExcluirFrequenciasAlunoPorRegistroFrequenciaIdCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/ExcluirPreDefinicaoFrequencia/ExcluirPreDefinicaoFrequenciaCommand.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/ExcluirPreDefinicaoFrequencia/ExcluirPreDefinicaoFrequenciaCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Frequencia/InserirRegistrosFrequenciasAlunos/InserirRegistrosFrequenciasAlunosCommandHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaPreDefinida.cs
src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAluno.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaPreDefinida.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroFrequenciaAluno.cs

[AB#57553](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57553)

Excluir somente os alunos afetados pela frequencia e não todos

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs

[AB#58261](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58261)

58261 - BUG 1 -  ajuste no filtro do listão para perfis de professor. 

---

src/SME.SGP.Aplicacao/Queries/PlanoAula/ObterPlanoAulasPorTurmaEComponentePeriodo/ObterPlanoAulasPorTurmaEComponentePeriodoQueryHandler.cs

[AB#58249](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58249)

Identificar objetivos opcionais de acordo com componente curricular

---

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs

Inclusão de funcionalidade para capturar exceção.

Bug: 57117

---

src/SME.SGP.Aplicacao/Queries/PeriodoFechamento/PeriodoFechamentoTurmaIniciado/PeriodoFechamentoTurmaIniciadoQueryHandler.cs

Correção do período de fechamento

Correção do período de fechamento

---

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterAvaliacoesBimestrais/ObterAvaliacoesBimestraisQuery.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterAvaliacoesBimestrais/ObterAvaliacoesBimestraisQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterAvaliacoesBimestraisRegencia/ObterAvaliacoesBimestraisRegenciaQuery.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterAvaliacoesBimestraisRegencia/ObterAvaliacoesBimestraisRegenciaQueryHandler.cs
src/SME.SGP.Infra/Dtos/FechamentoNota/AlunosFechamentoNotaConceitoTurmaDto.cs
src/SME.SGP.Infra/Dtos/FechamentoNota/FechamentoConsultaNotaConceitoTurmaListaoDto.cs
src/SME.SGP.Infra/Dtos/FechamentoNota/FechamentoNotaConceitoTurmaDto.cs

[AB#57723](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57723)

57723 - ajustes de observações e listagem de alunos do listão fechamento

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQueryHandler.cs
src/SME.SGP.Dominio/Entidades/Usuario.cs

[AB#58310](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58310)
[AB#58309](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58309)

Correção das turmas da modalidade infantil

---

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs
src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaFechamento/EnviarNotasFechamentoParaAprovacao/EnviarNotasFechamentoParaAprovacaoCommandHandler.cs
src/SME.SGP.Aplicacao/Queries/FechamentoTurmaDisciplina/ObterFechamentosTurmaComponentes/ObterFechamentosTurmaComponentesQuery.cs
src/SME.SGP.Infra/Dtos/FechamentoNota/FechamentoNotaConceitoTurmaDto.cs

[AB#58459](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58459)

52864 - ajustes listão fechamento pós repasse

---

src/SME.SGP.Aplicacao/Commands/Aulas/ValidarComponentesDoProfessor/ValidarComponentesDoProfessorCommandHandler.cs

[AB#58238](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58238)

Adequar pesquisa de componentes do território do saber

---

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
teste/SME.SGP.Aplicacao.Teste/CasosDeUso/ObterFrequenciaPorAulaUe/ObterFrequenciaPorAulaUeUseCaseTeste.cs

[AB#58350](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58350)

Correção do tratamento de exibiçaõ de alunos (removido critério de número de chamada)

---

src/SME.SGP.Aplicacao/Queries/PlanoAula/ObterPlanoAulasPorTurmaEComponentePeriodo/ObterPlanoAulasPorTurmaEComponentePeriodoQueryHandler.cs

[AB#58485](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58485)
[AB#58498](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58498)

 Listão Plano de aula - Erro interno

---

scripts manutencao/58221 - Aceite Automatico WF Aprovacao Notas e Conceitos/Aprovacao Conceitos.sql
scripts manutencao/58221 - Aceite Automatico WF Aprovacao Notas e Conceitos/Aprovacao Notas Conselho.sql
scripts manutencao/58221 - Aceite Automatico WF Aprovacao Notas e Conceitos/Aprovacao Notas Fechamento.sql
src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs

[AB#58221](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58221)

58221 Scripts de Aprovação automatico

---

src/SME.SGP.Aplicacao/CasosDeUso/PeriodosEscolares/ObterPeriodosPorComponenteUseCase.cs

[AB#58288](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58288)

Tratamento dos períodos de aulas

---

src/SME.SGP.Aplicacao/Commands/Comunicado/Notificacao/CriarNotificacaoEscolaAqui/CriarNotificacaoEscolaAquiCommandHandler.cs
src/SME.SGP.Aplicacao/Commands/Log/SalvarLogViaRabbit/SalvarLogViaRabbitCommand.cs
src/SME.SGP.Aplicacao/Commands/Log/SalvarLogViaRabbit/SalvarLogViaRabbitCommandHandler.cs

[AB#58348](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58348)

58348 - Incluso retorno da API do App Aluno no log de erro

---

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQuery.cs
src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQueryHandler.cs

[AB#58282](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58282)

Correção da exibição de turmas para CJ

---

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs
src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs

[AB#58496](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58496)
[AB#58493](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58493)

Tratamento de exibição de alunos conforme critério unificado

---

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs

[AB#58562](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58562)

58562 - ajuste permissão de edição para componentes que não lançam nota (listão fechamento)

---

src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs

Removido campo de outra consulta

---

scripts/V521__ADICIONAR_NOVAS_GRADES_ENSINO_MEDIO_2022.sql

[AB#57713](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57713)

57713 - script novas grades EM 2022

---

scripts/V522__ATUALIZAR_COMPONENTES_NOVAS_GRADES_ENSINO_MEDIO_2022.sql

[AB#57714](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57714)

feature/57714 Script de Normalização Nomes Componentes

---

src/SME.SGP.Api/Controllers/AulaInfantilController.cs

Alterando o endpoint de sincronização de aulas, tornando a informação de turma opcional.

Bug: 56747

---

src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs

[AB#58630](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58630)

Adequação da disciplina da pesquisa

---

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs

[AB#58246](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58246)

Correção das pendências de CJ

---

scripts/V523__ATUALIZAR_QTD_AULA_NOVAS_GRADES_ENSINO_MEDIO_2022.sql

[AB#58637](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58637)

Fix/58637 correção de quantidade de aulas

---

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs

[AB#58590](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58590)

Adicionado Valor Periodo Fim

---

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs

[AB#57351](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/57351)

Evitar que validação de período aberto seja feito para cada usuário

---

scripts/V524__CORRECAO_HISTORICO_F_ABRANGENCIA_TURMAS_TIPOS.sql
src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs

[AB#58630](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58630)

Correção da função histórica da f_abrangencia_turmas_tipos

---

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs

[AB#58646](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58646)

Retorno do tratamento do componente de educação física

---

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs

[AB#58646](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58646)

Removendo o componente da educação infantil

---

src/SME.SGP.Api/Controllers/FechamentoTurmaController.cs
src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ObterFechamentoIdPorTurmaBimestreUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Fechamento/IObterFechamentoIdPorTurmaBimestreUseCase.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/TurmaPossuiAvaliacaoNoPeriodo/TurmaPossuiAvaliacaoNoPeriodoQuery.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/TurmaPossuiAvaliacaoNoPeriodo/TurmaPossuiAvaliacaoNoPeriodoQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/Fechamento/ObterFechamentoTurmaComPeriodoEscolar/ObterFechamentoTurmaComPeriodoEscolarQuery.cs
src/SME.SGP.Aplicacao/Queries/Fechamento/ObterFechamentoTurmaComPeriodoEscolar/ObterFechamentoTurmaComPeriodoEscolarQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtividadeAvaliativa.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoTurma.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoTurmaConsulta.cs
src/SME.SGP.Infra/Dtos/Fechamento/FechamentoTurmaPeriodoEscolarDto.cs
src/SME.SGP.Infra/Dtos/Turma/TurmaBimestreDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs
teste/SME.SGP.Aplicacao.Teste/Queries/Fechamento/ObterFechamentoTurmaComPeriodoEscolarQueryTest.cs

[AB#58719](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58719)

58719 Criado consulta de fechamentos e avaliacoes por turma

---

src/SME.SGP.Api/Controllers/NotasConceitosController.cs
src/SME.SGP.Aplicacao/CasosDeUso/AtividadeAvaliativa/ObterAtividadesNotasAlunoPorTurmaPeriodoUseCase.cs
src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AtividadeAvaliativa/IObterAtividadesNotasAlunoPorTurmaPeriodoUseCase.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterAtividadesNotasAlunoPorTurmaPeriodo/ObterAtividadesNotasAlunoPorTurmaPeriodoQuery.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/ObterAtividadesNotasAlunoPorTurmaPeriodo/ObterAtividadesNotasAlunoPorTurmaPeriodoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs
src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaConsulta.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtividadeAvaliativa.cs
src/SME.SGP.Infra/Dtos/AtividadeAvaliativa/AvaliacaoNotaAlunoDto.cs
src/SME.SGP.Infra/Dtos/AtividadeAvaliativa/FiltroTurmaAlunoPeriodoEscolarDto.cs
src/SME.SGP.IoC/RegistraDependencias.cs

[AB#58720](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58720)

58720 Endpoint listagem de avaliações e notas

---

src/SME.SGP.Aplicacao/Commands/Aulas/ExcluirAulaRecorrente/ExcluirAulaRecorrenteCommandHandler.cs

Ajuste na rotina de exclusão de aula, incluíndo o repositório de aula para executar as operações de escrita.

Bug: 59036

---

src/SME.SGP.Infra/Dtos/Relatorios/Devolutivas/FiltroRelatorioDevolutivas.cs

[AB#56796](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56796)

Incluir filtro de componente curricular

---

scripts/V525__ADICIONAR_PARAMETRO_DEVOLUTIVA.sql

[AB#51821](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/51821)

Criação de parâmetros de devolutiva

---

src/SME.SGP.Aplicacao/Integracoes/ServicoPerfil.cs

[AB#44948](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/44948)

Bug 44948 - Logins 7232331, 7942974, 8045640, 8431612 ao logar o perfil padrão será Professor. 

---

src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs

[AB#59083](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59083)

ajuste na query de obter disciplinas por ids

---

src/SME.SGP.Aplicacao/Commands/Fechamento/GerarPendenciasFechamento/GerarPendenciasFechamentoCommandHandler.cs
src/SME.SGP.Dominio/Enumerados/SituacaoFechamento.cs

[AB#59446](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59446)

Back Bug2: Controle de excessao no calculo da Situação

---

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/TurmaPossuiAvaliacaoNoPeriodo/TurmaPossuiAvaliacaoNoPeriodoQuery.cs
src/SME.SGP.Aplicacao/Queries/AtividadeAvaliativa/TurmaPossuiAvaliacaoNoPeriodo/TurmaPossuiAvaliacaoNoPeriodoQueryHandler.cs
src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs
src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAtividadeAvaliativa.cs

[AB#59446](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59446)

59446 6: Considerar apenas avaliações do componente curricular

---

src/SME.SGP.Aplicacao/Commands/Comunicado/Inserir/InserirComunicado/InserirComunicadoCommandHandler.cs

Inclusão de log para identificar o erro ao inserir comunicado,

Bug: 59351

---

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs

[AB#59446](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59446)

59446 Corrigido carga de componentes da regencia para EJA

---

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarAtual/ObterPeriodoEscolarIdQueryHandler.cs
src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarAtualPorTurma/ObterPeriodoEscolarAtualPorTurmaQueryHandler.cs

Adicionado "null check".

---

src/SME.SGP.Dominio/Entidades/Usuario.cs

Ajuste para usuário logar com perfil AD ao invés de Professor CJ Infantil. Ambiente release-2.

Ajuste para usuário logar com perfil AD ao invés de Professor CJ Infantil. Ambiente release-2.

---

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
src/SME.SGP.Aplicacao/Commands/PlanoAEE/SalvarPlanoAee/SalvarPlanoAeeCommandHandler.cs

Ajustado para carregar a turma e a UE ao obter o plano AEE. Pois, pode ter havido mudança de turma.
Ajustado mapeamento ao salvar o plano para atualizar com a turma adequada.

Carregamento e mapeamento da turma no plano. AB#57098

---

src/SME.SGP.Dominio/Entidades/Usuario.cs

Ao logar carregar Perfil AD ao invés de Perfil Professor CJ Infantil

Ao logar carregar Perfil AD ao invés de Perfil Professor CJ Infantil

---

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs
src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolarConsulta.cs
src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs

[AB#58309](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58309)
[AB#58336](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58336)

Adicionado QueryName
