prefeiturasp/SME-NovoSGP

src/SME.SGP.Api/Controllers/FrequenciaController.cs, src/SME.SGP.Api/Controllers/RelatorioController.cs
[AB#59439](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59439)
=> Adicionado Chave API

src/SME.SGP.Api/Controllers/RelatorioIntegracaoController.cs
[AB#59440](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59440)
=> criado controller de relatorios integracao

src/SME.SGP.Aplicacao/Integracoes/ServicoPerfil.cs, src/SME.SGP.Dominio/Entidades/Usuario.cs
Incluído regra ao logar com prioridade PerfilAD e PerfilCJ.
=> Incluído regra ao logar com prioridade PerfilAD e PerfilCJ.

src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoRegistrosPedagogicos.cs
[AB#60484](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60484)
=> Ajustado critério para validar a data da aula até o dia atual -1.

src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
Correção na busca por turmas histórica na função de Acompanhamento do fechamento.
=> Correção na busca por turmas histórica na função de Acompanhamento do fechamento.

scripts/V530__INCLUSAO_PARAMETRO_EXECUCAOCONSOLIDACAOREGISTROSPEDAGOGICOS_2022.sql
[AB#59041](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/59041)
=> Inclusão parâmetro ExecucaoConsolidacaoRegistrosPedagogicos para o ano de 2022

src/SME.SGP.Aplicacao/Queries/Aula/ObterAulasPorIds/ObterAulasPorIdsQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
[AB#60826](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60826)
=> Ajuste nos parâmetros da query

src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
Ajuste ao salvar o fechamento, gravando histórico para notas de alunos que já haviam sido gravadas previamente.
=> Bug: 60729

src/SME.SGP.Dados/Mapeamentos/PeriodoFechamentoBimestreMap.cs
=> Ajuste no mapeamento de fechamento_bimestre

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterParecerPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioCoreSSO/ObterUsuarioCoreSSOQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioCoreSSO/ObterUsuarioCoreSSOQueryHandler.cs
[AB#60907](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60907)
=> Ajuste no nome do usuario

src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs
[AB#60865](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60865)
=> Ajuste na query de busca de componente curricular

src/SME.SGP.Aplicacao/Commands/Armazenamento/DownloadArquivo/DownloadArquivoCommandHandler.cs
=> Correção do operador para validar o conteúdo do arquivo.

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#60673](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60673)
=> Correção de parecer conclusivo para bimestres menores que 4

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs, src/SME.SGP.Dominio/Entidades/FechamentoAluno.cs, src/SME.SGP.Infra/Dtos/FechamentoNota/FechamentoNotaAlunoAprovacaoDto.cs
[AB#60963](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60963)
=> Correção de notas não formatados

teste/SME.SGP.Aplicacao.Teste/Queries/Fechamento/ObterFechamentoTurmaComPeriodoEscolarQueryTest.cs
=> Bug: 56753

src/SME.SGP.Dados/Mapeamentos/ConsolidacaoDiariosBordoMap.cs
=> fix/61052 - ajustando propriedades no campo "id" da entidade ConsolidacaoDiariosBordo

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterTotalCompensacoesAlunosETurmaPorPeriodo/ObterTotalCompensacoesAlunosETurmaPorPeriodoQuery.cs, src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterTotalCompensacoesAlunosETurmaPorPeriodo/ObterTotalCompensacoesAlunosETurmaPorPeriodoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterAusenciasAlunosPorAlunosETurmaId/ObterRegistroFrequenciaAlunosPorAlunosETurmaIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusenciaAlunoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusenciaAlunoConsulta.cs
Removidos deletes e transações que causavam locks no banco
AB#61061
=> 61061 Refactory Calculo Frequencia;

src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioBoletimDto.cs
[AB#60168](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60168)
=> incluir param ConsideraInativo no endpoint do boletim

src/SME.SGP.Api/Configuracoes/RegistrarMvc.cs
Correção para Fazer parse de string json para int
=> API SGP Release - Correção para Fazer parse de string json para int 

src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterAulaPorIdUseCase.cs, src/SME.SGP.Dominio/Entidades/Aula.cs
[AB#61167](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61167)
=> Correção do BUG 61167

src/SME.SGP.Aplicacao/Commands/ConsolidacaoConselhoClasse/ConsolidarTurmaConselhoClasseAluno/ConsolidarTurmaConselhoClasseAlunoCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs
Ajuste na consulta para obter os componentes curriculares.
Ajuste na definição das turmas para salvar nota pós-conselho.
=> Bug: 61082

src/SME.SGP.Dominio.Servicos/ServicoPeriodoFechamento.cs
[AB#61211](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61211)
=> Correção do bug 61211

src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
[AB#61217](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61217)
[AB#61315](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61315)
=> API SGP BUG  -  Erro ao tentar salvar nota para estudante remanejado

src/SME.SGP.Dados/Mapeamentos/TurmaMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
[AB#61213](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61213)
=> No tratamento de abrangência no login, erro ao cadastrar turma

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/AcompanhamentoAprendizagem/RelatorioRaaEscolaAquiUseCase.cs, src/SME.SGP.Aplicacao/Commands/Comunicado/Notificacao/CriarNotificacaoEscolaAqui/CriarNotificacaoEscolaAquiCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterSemestreAtualRelatorio/ObterSemestreAtualRelatorioQuery.cs, src/SME.SGP.Aplicacao/Queries/AcompanhamentoAluno/ObterSemestreAtualRelatorio/ObterSemestreAtualRelatorioQueryHandler.cs, src/SME.SGP.Dados/Mapeamentos/ComunicadoModalidadeMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioAcompanhamentoAlunoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAcompanhamentoAlunoConsulta.cs
[AB#60138](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60138)
=> Criação query para obter o semestre 

src/SME.SGP.Aplicacao/Commands/Comunicado/Inserir/InserirComunicadoBoletimEscolaAqui/InserirComunicadoMensagemAutomaticaCommandHandler.cs
[AB#60138](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60138)
=> ajustes url de downalod

src/SME.SGP.Dados/Mapeamentos/DiarioBordoMap.cs
[AB#61076](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61076)
=> Erro ao salvar diário

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs
[AB#61327](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61327)
=> fix/61327 

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
[AB#61435](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61435)
[AB#61436](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61436)
=> SGP API BUG 61435 - Erro ao acessar a ABA final para alguns componentes curriculares

src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoDiariosBordo.cs
[AB#61466](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61466)
=> 61466 - ajuste na query de consolidação do diário de bordo

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
Atualização de consolidação quando existir
=> Atualização de consolidação quando existir

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
[AB#61293](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61293)
=> Correção do bug 61293

src/SME.SGP.Dados/Mapeamentos/FrequenciaAlunoMap.cs
Erro de merge, colunas duplicadas
=> Correção de colunas duplicadas

src/SME.SGP.Api/Controllers/AutenticacaoController.cs
[AB#61550](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61550)
=> Correção do bug 61550

src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
[AB#61057](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61057)
=> Ajuste verificação de objeto nulo

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IEncerrarPlanosAEEEstudantesInativosUseCase.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosEolPorCodigos/ObterAlunosEolPorCodigosQuery.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosEolPorCodigos/ObterAlunosEolPorCodigosQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs, src/SME.SGP.Dominio/Enumerados/SituacaoPlanoAEE.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEAlunoTurmaDto.cs, src/SME.SGP.Infra/Dtos/TurmasDoAlunoDto.cs
[AB#61400](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61400)
=> Ajuste no obter aluno

src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaFrequenciaTratar/AlterarAulaFrequenciaTratarCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAluno.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroFrequenciaAluno.cs
[AB#61411](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61411)
=> Correção na exclusão de frequência

scripts/V532__CREATE_TABLE_PENDENCIA_DIARIO_BORDO.sql, src/SME.SGP.Dados/Mapeamentos/PendenciaDiarioBordoMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaDiarioBordo.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaDiarioBordo.cs, src/SME.SGP.Dominio/Entidades/PendenciaDiarioBordo.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#60911](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60911)
=> feature/60911 - 4.3) Pendências Diário Bordo - 1 Modelagem

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
…icular definido se apresenta ou não os percentuais.
=> Ajustada para avaliar se existe frequência lançada no componente curricular

src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidado.cs
Correção da consolidação de notas (conselho de classe e fechamento nota)
=> Correção da consolidação de notas (conselho de classe e fechamento nota)

src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs
[AB#61937](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61937)
=> Ajustada validação se existe encaminhado encerrado automaticamente.

scripts manutencao/SCRIPT MIGRACAO_PENDENCIA_DIARIO_BORDO.sql
[AB#60923](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60923)
=> feature/60923 - script de migração dos dados da pendencia_aula para pendencia_diario_bordo

src/SME.SGP.Dados/Mapeamentos/FrequenciaAlunoMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidado.cs
[AB#58989](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58989)
=> Correção do mapeamento e ajuste da query de notas

src/SME.SGP.Dados/Mapeamentos/ConsolidacaoFrequenciaTurmaMap.cs
Correção do mapeamento da consolidacao_frequencia_turma
=> Correção do mapeamento da consolidacao_frequencia_turma

scripts manutencao/script migracao pendencia_aula para pendencia_diario.sql, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs, teste/SME.SGP.Aplicacao.Teste/Queries/Listao/ObterIndicativoPendenciasAulasPorTipoQueryHandlerTeste.cs
[AB#60926](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60926)
=> Feature/60926 - ajuste no script de migração + alteração na pendência dentro do listão

src/SME.SGP.Api/Controllers/PeriodoEscolarController.cs
Removido permissionamento de endpoint comum
=> Removido permissionamento de endpoint comum

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
[AB#61853](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61853)
=> Correção do bug 61853

src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs
Ajuste para cadastrar notas no lançamento
=> BUG 62154 Ajuste para cadastrar notas no lançamento

src/SME.SGP.Aplicacao/Commands/ConsolidacaoNotaAlunoCommand/ConsolidacaoNotaAlunoCommand.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/PersistirParecerConclusivoCommand/PersistirParecerConclusivoCommand.cs, src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaConselhoClasse/AprovarWorkflowAlteracaoNotaConselho/AprovarWorkflowAlteracaoNotaConselhoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesComNotaDeFechamentoOuConselhoPorAluno/ObterComponentesComNotaDeFechamentoOuConselhoQuery.cs, src/SME.SGP.Aplicacao/Queries/FechamentoAcompanhamentoTurmas/ObterComponentesParaFechamentoAcompanhamentoCCAluno/ObterComponentesParaFechamentoAcompanhamentoCCAlunoQuery.cs, src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsolidadoNota.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioComponenteCurricularConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseAlunoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseConsolidadoNota.cs, src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs, src/SME.SGP.Infra/Consts/BimestreConstants.cs, src/SME.SGP.Infra/Dtos/ConsolidacaoNotaAlunoDto.cs, src/SME.SGP.Infra/Dtos/FechamentoAcompanhamentoTurmas/MensagemConsolidacaoConselhoClasseAlunoDto.cs, src/SME.SGP.Infra/Dtos/PersistirParecerConclusivoDto.cs
[AB#62236](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62236)
=> Correção da persistência da aba final

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/ObterAlunosPorTurmaEDataMatricula/ObterAlunosPorTurmaEDataMatriculaQueryHandler.cs
[AB#61995](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61995)
=> Ajuste na listagem de alunos

src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterIndicativoPendenciasAulasPorTipo/ObterIndicativoPendenciasAulasPorTipoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs, teste/SME.SGP.Aplicacao.Teste/Queries/Listao/ObterIndicativoPendenciasAulasPorTipoQueryHandlerTeste.cs
[AB#62258](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62258)
=> 62258 - ajustes para performance da query de pendencia 

src/SME.SGP.Dados/Mapeamentos/AulaMap.cs
[AB#62318](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62318)
=> Criado propriedade nova, porém esquecido de ignorar para persistência

src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs
Ajuste para cadastrar notas no lançamento
=> master <- fix/62154

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs
Ajuste na funcionalidade de etapa concluida do encerramento do plano AEE, removendo uma variável instanciada incorretamente.
=> Bug: 62329

src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaDiarioBordoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PendenciaDiarioBordo/TratarPendenciaDiarioBordoPorTurmaUseCase.cs, src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaDiarioBordo/SalvarPendenciaDiarioBordo/SalvarPendenciaDiarioBordoCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciaDiarioBordo/SalvarPendenciaDiarioBordo/SalvarPendenciaDiarioBordoCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PendenciaDiarioBordo/ITratarPendenciaDiarioBordoPorTurmaUseCase.cs, src/SME.SGP.Aplicacao/Queries/PendenciaDiarioBordo/ObterPendenciasDiarioBordoQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaDiarioBordo/ObterPendenciasDiarioBordoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaDiarioBordo.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaDiarioBordo.cs, src/SME.SGP.Infra/Dtos/Aula/Pendencia/AulaComComponenteDto.cs, src/SME.SGP.Infra/Dtos/Professor/ProfessorEComponenteInfantilDto.cs, src/SME.SGP.Infra/Dtos/Turma/TurmaComComponentesInfantilDto.cs, src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#62320](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62320)
=> Feature/62320 - alteração na gravação da pendencia do diário e busca dos dados.

scripts/V533__CORRECAO_COMPONENTE_CURRICULAR_GRUPO_AREA_ORDENACAO.sql
[AB#62235](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62235)
=> Script de ordenação dos componentes curriculares

src/SME.SGP.Aplicacao/Comandos/ComandosUsuario.cs, src/SME.SGP.Aplicacao/Commands/Autenticacao/AlterarSenhaComTokenRecuperacao/AlterarSenhaComTokenRecuperacaoCommand.cs, src/SME.SGP.Aplicacao/Commands/Autenticacao/AlterarSenhaComTokenRecuperacao/AlterarSenhaComTokenRecuperacaoCommandHandler.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs
=> 612145 Movido endpoint de alteração de senha por token

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
[AB#62417](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62417)
=> Correção da frequência global

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
Foi adicionado uma validação onde ele verifica a SituacaoMatricula é diferente 4 Vinculo indevido, assim como no fechamento
=> Bug 62242: Foi adicionado uma validação onde ele verifica a SituacaoMatricula

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
Foi adicionado uma validação onde ele verifica a SituacaoMatricula é diferente 4 Vinculo indevido, assim como no fechamento
=> fix62242 -> master

src/SME.SGP.Aplicacao/Commands/PendenciaDiarioBordo/SalvarPendenciaDiarioBordo/SalvarPendenciaDiarioBordoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterTurmaDaPendenciaAula/ObterTurmaDaPendenciaAulaQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaDiarioBordo/ObterPendenciasDiarioPorPendenciaIdEProfessor/ObterPendenciasDiarioPorPendenciaIdEProfessorQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaDiarioBordo/ObterPendenciasDiarioPorPendenciaIdEProfessor/ObterPendenciasDiarioPorPendenciaIdEProfessorQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaDiarioBordo/ObterTurmaDaPendenciaDiario/ObterTurmaDaPendenciaDiarioQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaDiarioBordo/ObterTurmaDaPendenciaDiario/ObterTurmaDaPendenciaDiarioQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaDiarioBordoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaDiarioBordoConsulta.cs, src/SME.SGP.Dominio/Entidades/Pendencia.cs, src/SME.SGP.Infra/Dtos/PendenciaDiarioBordo/PendenciaDiarioBordoDescricaoDto.cs
[AB#62600](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62600)
=> ajustes na exibição da pendencia na tela de pendências.

src/SME.SGP.Dados/Repositorios/RepositorioRegistroIndividual.cs
[AB#61793](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61793)
=> Correção do bug 61793

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
Correção no carregamento da frequência do aluno por turma no conselho de classe.
=> Correção do bug 62621

src/SME.SGP.Aplicacao/Queries/Aula/ObterDatasAulasPorProfessorEComponente/ObterDatasAulasPorProfessorEComponenteQueryHandler.cs
[AB#62758](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62758)
=> Correção do bug 62758

src/SME.SGP.Api/Controllers/FiltroRelatorioController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Relatorios/IObterFiltroRelatoriosModalidadesPorUeAbrangenciaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaQuery.cs, src/SME.SGP.Aplicacao/Queries/Relatorios/ObterFiltroRelatoriosModalidadesPorUeAbrangencia/ObterFiltroRelatoriosModalidadesPorUeAbrangenciaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAbrangencia.cs
[AB#62446](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62446)
=> Correção dos filtros da tela de boletim. Bug 62446

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesUseCase.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterAulasCalendarioProfessorPorMes/ObterAulasCalendarioProfessorPorMesQuery.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterAulasCalendarioProfessorPorMes/ObterAulasCalendarioProfessorPorMesQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterAulasCalendarioProfessorPorMesDia/ObterAulasCalendarioProfessorPorMesDiaQuery.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterAulasCalendarioProfessorPorMesDia/ObterAulasCalendarioProfessorPorMesDiaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Evento/ObterEventosCalendarioProfessorPorMesDia/ObterEventosCalendarioProfessorPorMesDiaQuery.cs, src/SME.SGP.Aplicacao/Queries/Evento/ObterEventosCalendarioProfessorPorMesDia/ObterEventosCalendarioProfessorPorMesDiaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEvento.cs
[AB#62591](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62591)
=> fix/62591 - ajuste de lentidão na tela de calendário do professor

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#61798](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61798)
=> Manutenção no método para validar os objetivos em caso de turma EJA.

scripts/V534__NOVA_TABELA_CONSOLIDACAO_FREQUENCIA_ALUNO_MENSAL.sql
[AB#62277](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62277)
=> Nova tabela.

scripts/V534__PARAMETRO_GERACAO_PENDENCIAS.sql, src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaUseCase.cs, src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs
[AB#60909](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60909)
=> feature/60909 - Parâmetro para geração de Pendencia

src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaUseCase.cs
[AB#60915](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60915)
=> feature/60915 - criação de pendencias aula a partir de datainicio (param. sistema)

scripts/V534__INCLUIR_PRIORIDADE_PERFIL.sql
[AB#62987](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62987)
=> Adicionado script para incluir prioridade do perfil.

scripts/V534__INCLUIR_PRIORIDADE_PERFIL.sql, src/SME.SGP.Dominio/Enumerados/PerfilUsuario.cs
[AB#62987](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62987)
[AB#62253](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62253)
=> [NAAPA] Novos perfis - Story -> Release

src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciaIdPorComponenteProfessorBimestre/ObterPendenciaIdPorComponenteProfessorBimestreQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciaIdPorComponenteProfessorBimestre/ObterPendenciaIdPorComponenteProfessorBimestreQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/PendenciaAula/PendenciaAulaFrequenciaUseCaseTeste.cs
[AB#60910](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60910)
=> Feature/60910 - avaliar geração de pendencias aula

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#62626](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62626)
=> Correção do bug 62626

src/SME.SGP.Aplicacao/Commands/PlanoAula/MigrarPlanoAula/MigrarPlanoAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs, src/SME.SGP.Infra/Dtos/Turma/TurmaNaoHistoricaDto.cs
[AB#56683](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/56683)
=> Correção do bug 56683

src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciasGerais/SalvarPendencia/SalvarPendenciaCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciasGerais/SalvarPendencia/SalvarPendenciaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAulaPorId/ObterPendenciasAulaPorIdQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAulasPorPendencia/ObterPendenciasAulasPorPendenciaQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasDreUePorCodigos/ObterTurmasDreUePorCodigosQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasDreUePorCodigos/ObterTurmasDreUePorCodigosQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurmaConsulta.cs, src/SME.SGP.Infra/Dtos/AulaDto.cs, src/SME.SGP.Infra/Dtos/PendenciaAula/PendenciaAulaDto.cs
[AB#60913](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60913)
=> Alteração dos textos das pendências de frequência, diário de bordo, plano de aula e avaliações

src/SME.SGP.Aplicacao/Commands/PendenciaProfessor/ExecutarVerificacaoPendenciaAvaliacaoCP/ExecutarVerificacaoPendenciaAvaliacaoCPCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaProfessor/ExecutarVerificacaoPendenciaAvaliacaoProfessor/ExecutarVerificacaoPendenciaAvaliacaoProfessorCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurmaDisciplina/ObterFechamentoTurmaDisciplinaPorTurmaId/ObterFechamentoTurmaDisciplinaPorTurmaIdQuery.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurmaDisciplina/ObterFechamentoTurmaDisciplinaPorTurmaId/ObterFechamentoTurmaDisciplinaPorTurmaIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoTurmaDisciplinaConsulta.cs, src/SME.SGP.Infra/Dtos/DashboardFechamento/TurmaFechamentoDisciplinaDto.cs
[AB#60914](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60914)
=> Manutenção da pendência Componente sem nenhuma avaliação no bimestre

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaFechamentoComponenteUseCase.cs, src/SME.SGP.Aplicacao/Queries/Professores/ObterProfessoresTitularesPorTurmaId/ObterProfessoresTitularesPorTurmaIdQueryHandler.cs
[AB#63040](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63040)
=> Correção Consolidacao Fechamento Turma

scripts/V537__CREATE_TABLE_CONSELHO_CLASSE_ALUNO_RECOMENDACAO.sql, src/SME.SGP.Dados/Mapeamentos/ConselhoClasseAlunoRecomendacaoMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoRecomendacao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseAlunoRecomendacao.cs, src/SME.SGP.Dominio/Entidades/ConselhoClasseAlunoRecomendacao.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#61269](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61269)
=> feature/61269 - modelagem e registro da entidade conselho_classe_aluno_recomendacao

scripts/V534__NOVA_TABELA_CONSOLIDACAO_FREQUENCIA_ALUNO_MENSAL.sql, src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoFrequenciaAluno/ConsolidarFrequenciaAlunoPorTurmaEMesUseCase.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoFrequenciaAluno/LimparConsolidacaoFrequenciaAlunoPorTurmaEMes/LimparConsolidacaoFrequenciaAlunoPorTurmasEMesesCommand.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoFrequenciaAluno/LimparConsolidacaoFrequenciaAlunoPorTurmaEMes/LimparConsolidacaoFrequenciaAlunoPorTurmasEMesesCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoFrequenciaAluno/RegistrarConsolidacaoFrequenciaAlunoMensal/RegistrarConsolidacaoFrequenciaAlunoMensalCommand.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoFrequenciaAluno/RegistrarConsolidacaoFrequenciaAlunoMensal/RegistrarConsolidacaoFrequenciaAlunoMensalCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/IncluirFilaCalcularFrequenciaPorTurma/IncluirFilaCalcularFrequenciaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConsolidacaoFrequenciaAluno/IConsolidarFrequenciaAlunoPorTurmaEMesUseCase.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaAlunosPorTurmaEMes/ObterFrequenciaAlunosPorTurmaEMesQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaAlunosPorTurmaEMes/ObterFrequenciaAlunosPorTurmaEMesQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaAlunosPorTurmaEMes/ObterFrequenciaAlunosPorTurmaEMesQueryValidator.cs, src/SME.SGP.Aplicacao/SME.SGP.Aplicacao.csproj, src/SME.SGP.Dados/Mapeamentos/ConsolidacaoDashBoardFrequenciaMap.cs, src/SME.SGP.Dados/Mapeamentos/ConsolidacaoFrequenciaAlunoMensalMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaAlunoMensal.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoFrequenciaAlunoMensal.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroFrequenciaAlunoConsulta.cs, src/SME.SGP.Dominio/Entidades/ConsolidacaoFrequenciaAlunoMensal.cs, src/SME.SGP.Infra/Dtos/ConsolidacaoFrequenciaAluno/FiltroConsolidacaoFrequenciaAlunoMensal.cs, src/SME.SGP.Infra/Dtos/ConsolidacaoFrequenciaAluno/RegistroFrequenciaAlunoPorTurmaEMesDto.cs, src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#62275](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62275)
=> Implementado Worker para consolidação da frequencia dos alunos por mês.

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Frequencia/GerarRelatorioFrequenciaMensalUseCase.cs, src/SME.SGP.Infra/Dtos/Relatorios/FrequenciaMensal/FiltroRelatorioFrequenciaMensalDto.cs
[AB#62270](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62270)
=> Removido propriedades não utilizadas e adicionada a propriedade para exibir o histórico como filtro no DTO.

src/SME.SGP.Api/Controllers/ConselhoClasseController.cs, src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterRecomendacoesAlunoFamiliaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConselhoClasse/IObterRecomendacoesAlunoFamiliaUseCase.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseRecomendacao/ObterRecomendacoesAlunoFamilia/ObterRecomendacoesAlunoFamiliaQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseRecomendacao/ObterRecomendacoesAlunoFamilia/ObterRecomendacoesAlunoFamiliaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseRecomendacao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseRecomendacao.cs, src/SME.SGP.Dominio/Entidades/ConselhoClasseRecomendacao.cs, src/SME.SGP.Infra/Dtos/ConselhoClasse/RecomendacoesAlunoFamiliaDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs, teste/SME.SGP.TesteIntegracao/Ao_obter_recomendacoes.cs
[AB#61266](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61266)
=> feature/61266 - Endpoint de recomendações do aluno e da família

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
[AB#62603](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62603)
=> Correção do parecer conclusivo

src/SME.SGP.Api/Controllers/ConselhoClasseController.cs, src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterTotalCompensacoesComponenteNaoLancaNotaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConselhoClasse/IObterTotalCompensacoesComponenteNaoLancaNotaUseCase.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterTotalCompensacoesComponenteNaoLancaNota/ObterTotalCompensacoesComponenteNaoLancaNotaQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterTotalCompensacoesComponenteNaoLancaNota/ObterTotalCompensacoesComponenteNaoLancaNotaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseConsulta.cs, src/SME.SGP.Infra/Dtos/ConselhoClasse/TotalAulasPorAlunoTurmaDto.cs, src/SME.SGP.Infra/Dtos/TotalAulasNaoLancamNotaDto.cs, src/SME.SGP.Infra/Dtos/TotalCompensacoesComponenteNaoLancaNotaDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/ObterTotalAulasNAoLancamNotaUseCaseTeste.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/RetornarTotalCompensacoesNaoLancamNotaTeste.cs
[AB#61262](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61262)
=> Feature/61262 - endpoint obter total de compensações componentes que não lançam nota

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseRecomendacao/ObterRecomendacoesPorAlunoConselho/ObterRecomendacoesPorAlunoConselhoQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseRecomendacao/ObterRecomendacoesPorAlunoConselho/ObterRecomendacoesPorAlunoConselhoQueryHandler.cs, src/SME.SGP.Dados/Mapeamentos/ConselhoClasseAlunoRecomendacaoMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoRecomendacao.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseRecomendacao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseAlunoRecomendacao.cs, src/SME.SGP.Dominio/Entidades/ConselhoClasseAlunoRecomendacao.cs, src/SME.SGP.Infra/Dtos/ConsultasConselhoClasseRecomendacaoConsultaDto.cs, teste/SME.SGP.TesteIntegracao/Ao_obter_recomendacoes.cs
[AB#61267](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61267)
=> Feature/61267 - Manutenção do endpoint de obter recomendações do aluno

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAula/ObterPlanoAulaUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#63222](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63222)
=> Correção do bug 63222

teste/SME.SGP.TesteIntegracao/Ao_calcular_frequencia.cs, teste/SME.SGP.TesteIntegracao/Ao_gerar_pendencia_aula.cs, teste/SME.SGP.TesteIntegracao/Setup/CollectionFixture.cs, teste/SME.SGP.TesteIntegracao/Setup/InMemoryDatabase.cs, teste/SME.SGP.TesteIntegracao/Setup/TestFixture.cs, teste/SME.SGP.TesteIntegracao/TesteBase.cs
Ajuste para usar uma Collection Fixture ao invés de Class Fixture
=> Ajuste para usar uma Collection Fixture ao invés de Class Fixture

src/SME.SGP.Aplicacao/Comandos/ComandosConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasseAlunoRecomendacao/SalvarConselhoClasseAlunoRecomendacao/SalvarConselhoClasseAlunoRecomendacaoCommand.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasseAlunoRecomendacao/SalvarConselhoClasseAlunoRecomendacao/SalvarConselhoClasseAlunoRecomendacaoCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoRecomendacao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseAlunoRecomendacao.cs, src/SME.SGP.Infra/Dtos/ConselhoClasseAlunoAnotacoesDto.cs, teste/SME.SGP.TesteIntegracao/Ao_obter_recomendacoes.cs
[AB#61338](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61338)
=> feature/61388 - ajuste na persistencia ao salvar recomendação do aluno e da família

teste/SME.SGP.TesteIntegracao/Ao_obter_recomendacoes.cs
Correção de Erro no teste Ao_obter_recomendacoes
=> Correção de Erro no teste Ao_obter_recomendacoes 

src/SME.SGP.Api/Controllers/ConselhoClasseController.cs
[AB#63152](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63152)
=> As notas alteradas para (NADA, OU SEJA, VAZIO) não está saindo no boletim impresso 

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasConselhoClasseRecomendacao.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseRecomendacao/ObterRecomendacoesPorAlunoConselho/ObterRecomendacoesPorAlunoConselhoQuery.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoRecomendacao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseAlunoRecomendacao.cs
[AB#62603](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62603)
=> Correção da pesquisa em aba final

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
[AB#63367](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63367)
=> bug 63367 - alteração para trazer se é AulaCJ na geração de pendencias

src/SME.SGP.Aplicacao/Commands/Frequencia/ConciliacaoFrequenciaTurmas/ConciliacaoFrequenciaTurmasCommandHandler.cs
[AB#63459](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63459)
=> Não está processando os meses da data.

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
[AB#60392](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60392)
=> correção da query para total alunos

src/SME.SGP.Aplicacao/Queries/DashboardFechamento/ObterConselhoClasseSituacao/ObterConselhoClasseSituacaoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
[AB#50260](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/50260)
=> Correções do bug 50260

scripts/V541__NOVA_TABELA_FREQUENCIA_TURMA_EVASAO.sql, src/SME.SGP.Dados/Mapeamentos/FrequenciaTurmaEvasaoMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaTurmaEvasao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaTurmaEvasao.cs, src/SME.SGP.Dominio/Entidades/FrequenciaTurmaEvasao.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#63063](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63063)
=> Adicionado script para criação da nova tabela, entidade, repositório, mapeamentos e dependências.

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs
[AB#63167](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63167)
[AB#63180](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63180)
=> Correção do bug 63167 e 63180

src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaProfessor/ExecutarVerificacaoPendenciaAvaliacaoCP/ExecutarVerificacaoPendenciaAvaliacaoCPCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaProfessor/ExecutarVerificacaoPendenciaAvaliacaoProfessor/ExecutarVerificacaoPendenciaAvaliacaoProfessorCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciasGerais/SalvarPendencia/SalvarPendenciaCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciasGerais/SalvarPendencia/SalvarPendenciaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurmaDisciplina/ObterFechamentoTurmaDisciplinaPorTurmaId/ObterFechamentoTurmaDisciplinaPorTurmaIdQuery.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurmaDisciplina/ObterFechamentoTurmaDisciplinaPorTurmaId/ObterFechamentoTurmaDisciplinaPorTurmaIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAulaPorId/ObterPendenciasAulaPorIdQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciasAulasPorPendencia/ObterPendenciasAulasPorPendenciaQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasDreUePorCodigos/ObterTurmasDreUePorCodigosQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasDreUePorCodigos/ObterTurmasDreUePorCodigosQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoTurmaDisciplinaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurmaConsulta.cs, src/SME.SGP.Dominio/Enumerados/TipoPendencia.cs, src/SME.SGP.Infra/Dtos/AulaDto.cs, src/SME.SGP.Infra/Dtos/DashboardFechamento/TurmaFechamentoDisciplinaDto.cs, src/SME.SGP.Infra/Dtos/DashboardFechamento/TurmaFechamentoDisciplinaSituacaoDto.cs, src/SME.SGP.Infra/Dtos/PendenciaAula/PendenciaAulaDto.cs
Liberação da story 62479 - Pendências - Melhorias no texto das pendências - P
=> Story/62479_v2 --> master

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs, src/SME.SGP.Infra/Dtos/ConselhoClasse/TotalAulasPorAlunoTurmaDto.cs
[AB#63549](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63549)
=> Fix/63549 - Conselho melhorias frequência] Dados estão incorretos na tela

src/SME.SGP.Aplicacao/CasosDeUso/Aula/ExcluirAulaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Aulas/ExcluirAulaRecorrente/ExcluirAulaRecorrenteCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Aulas/ExcluirAulaUnica/ExcluirAulaUnicaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/RecalcularFrequenciaPorTurma/RecalcularFrequenciaPorTurmaCommandHandler.cs
[AB#63732](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63732)
[AB#63509](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63509)
=> Implementado para recalcular a frequência ao excluir aulas.

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs
=> Bug: 63180

src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs, src/SME.SGP.Dados/Repositorios/RepositorioAulaPrevistaBimestreConsulta.cs
[AB#63433](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63433)
=> Ajuste na consulta das aulas

src/SME.SGP.Aplicacao/CasosDeUso/Aula/CriacaoAutomatica/CriarAulasInfantilAutomaticamenteUseCase.cs, src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommandHandler.cs
Inclusão do log na rotina de sincronização de aulas do infantil para identificar o erro que etsá ocorrendo no ambiente.
=> Bug: 61292

src/SME.SGP.Aplicacao/Queries/Turma/TurmaEmPeriodoAberto/TurmaEmPeriodoAbertoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolarConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoEscolarConsulta.cs
[AB#63806](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63806)
=> Correção do bug 63806

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs
[AB#63167](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63167)
=> Correção do bug 63167

src/SME.SGP.Api/Controllers/DashboardNaapaController.cs, src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoFrequenciaAluno/ConsolidarFrequenciaAlunoPorTurmaEMesUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoFrequenciaTurmaEvasao/ConsolidarFrequenciaTurmaEvasaoUseCase.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoFrequenciaAluno/RegistrarConsolidacaoFrequenciaAlunoMensal/RegistrarConsolidacaoFrequenciaAlunoMensalCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/FrequenciaTurmaEvasao/LimparFrequenciaTurmaEvasaoPorTurmasEMeses/LimparFrequenciaTurmaEvasaoPorTurmasEMesesCommand.cs, src/SME.SGP.Aplicacao/Commands/FrequenciaTurmaEvasao/LimparFrequenciaTurmaEvasaoPorTurmasEMeses/LimparFrequenciaTurmaEvasaoPorTurmasEMesesCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/FrequenciaTurmaEvasao/RegistrarFrequenciaTurmaEvasao/RegistrarFrequenciaTurmaEvasaoCommand.cs, src/SME.SGP.Aplicacao/Commands/FrequenciaTurmaEvasao/RegistrarFrequenciaTurmaEvasao/RegistrarFrequenciaTurmaEvasaoCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConsolidacaoFrequenciaTurmaEvasao/IConsolidarFrequenciaTurmaEvasaoUseCase.cs, src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterDashboardFrequenciaTurmaEvasaoAbaixo50Porcento/ObterDashboardFrequenciaTurmaEvasaoAbaixo50PorcentoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/DashboardNaapa/ObterDashboardFrequenciaTurmaEvasaoSemPresenca/ObterDashboardFrequenciaTurmaEvasaoSemPresencaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsolidacoesFrequenciaAlunoMensalPorTurmaEMes/ObterConsolidacoesFrequenciaAlunoMensalPorTurmaEMesQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsolidacoesFrequenciaAlunoMensalPorTurmaEMes/ObterConsolidacoesFrequenciaAlunoMensalPorTurmaEMesQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsolidacoesFrequenciaAlunoMensalPorTurmaEMes/ObterConsolidacoesFrequenciaAlunoMensalPorTurmaEMesQueryValidator.cs, src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaAlunoMensal.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaTurmaEvasao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoFrequenciaAlunoMensal.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaTurmaEvasao.cs, src/SME.SGP.Infra/Consts/DashboardConstants.cs, src/SME.SGP.Infra/Dtos/ConsolidacaoFrequenciaAlunoMensal/ConsolidacaoFrequenciaAlunoMensalDto.cs, src/SME.SGP.Infra/Dtos/ConsolidacaoFrequenciaTurmaEvasao/FiltroConsolidacaoFrequenciaTurmaEvasao.cs, src/SME.SGP.Infra/Dtos/ConsolidacaoFrequenciaTurmaEvasao/RegistroFrequenciaTurmaEvasaoPorTurmaEMesDto.cs, src/SME.SGP.Infra/Enumerados/Permissao.cs, src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs, teste/SME.SGP.TesteIntegracao/Ao_obter_frequencia_turma_evasao.cs, teste/SME.SGP.TesteIntegracao/Ao_registrar_frequencia_turma_evasao.cs
[AB#63064](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63064)
=> Feature_63064 -> story_62257

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#63549](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63549)
=> Fix/63549 - Dados estão incorretos na tela

src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterQuestoesPlanoAEEPorVersao/ObterQuestoesPlanoAEEPorVersaoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterUltimaVersaoPlanoAEE/ObterUltimaVersaoPlanoAEEQuery.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEVersao.cs
[AB#63954](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63954)
=> Correção do bug 63954

src/SME.SGP.Api/Controllers/AutenticacaoController.cs
[AB#63191](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63191)
=> Remoção das permissões AS_C que não estão associadas

src/SME.SGP.Aplicacao/CasosDeUso/Notificacao/GerarNotificacaoAlteracaoLimiteDiasUseCase.cs, src/SME.SGP.Dominio.Interfaces/Servicos/IServicoFechamentoTurmaDisciplina.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
[AB#64217](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64217)
=> Correção da rotina de geração de notificação alteração limite

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs
[AB#63849](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63849)
=> Corrigido erro de referencia de Objeto na carga dos Conselhos de Classe

src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs
[AB#64109](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64109)
=> Fix/64109 - Erro ao abrir aba final na tela de fechamento de bimestre.

src/SME.SGP.Aplicacao/Consultas/ConsultasFrequencia.cs
[AB#64109](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64109)
=> Fix/64109 - melhoria fechamento bimestre tratando datas nulas

src/SME.SGP.Aplicacao/CasosDeUso/CompensacaoAusencia/NotificarCompensacaoAusenciaUseCase.cs
[AB#63040](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63040)
=> Correção Contexto de persistencia Compensção Ausencia

src/SME.SGP.Aplicacao/CasosDeUso/Relatorios/Frequencia/GerarRelatorioFrequenciaMensalUseCase.cs, src/SME.SGP.Infra/Dtos/Relatorios/FrequenciaMensal/FiltroRelatorioFrequenciaMensalDto.cs
[AB#62274](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62274)
[AB#62216](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62216)
=> Backend SGP - Story/62274

src/SME.SGP.Aplicacao/Commands/ConselhoClasseAlunoRecomendacao/SalvarConselhoClasseAlunoRecomendacao/SalvarConselhoClasseAlunoRecomendacaoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseRecomendacao/ObterRecomendacoesPorConselhoAlunoId/ObterRecomendacoesPorConselhoAlunoIdQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasseRecomendacao/ObterRecomendacoesPorConselhoAlunoId/ObterRecomendacoesPorConselhoAlunoIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseAlunoRecomendacao.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseAlunoRecomendacao.cs, teste/SME.SGP.TesteIntegracao/Ao_obter_recomendacoes.cs
[AB#63464](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63464)
[AB#63397](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63397)
=> fix/63464 - ajuste para editar as frases de recomendação do aluno

src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMes/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesQueryHandler.cs
[AB#64290](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64290)
=> Calendário do professor - Erro 500 para o Professor CJ

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterIndicativoPendenciasAulasPorTipo/ObterIndicativoPendenciasAulasPorTipoQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterIndicativoPendenciasAulasPorTipo/ObterIndicativoPendenciasAulasPorTipoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs, teste/SME.SGP.Aplicacao.Teste/Queries/Listao/ObterIndicativoPendenciasAulasPorTipoQueryHandlerTeste.cs
[AB#64189](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64189)
=> Fix/64189 - Ícone de pendência aparece OK mesmo quando há pendência

src/SME.SGP.Api/Controllers/NotasConceitosController.cs
[AB#63651](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63651)
=> Correção bug 63651

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, teste/SME.SGP.TesteIntegracao/PendenciaAula/Ao_gerar_pendencia_aula.cs
[AB#64215](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64215)
=> Correção dos testes de integração

src/SME.SGP.Api/Controllers/ConselhoClasseController.cs, src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/ObterTotalAulasNaoLancamNotaUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/ConselhoClasse/IObterTotalAulasNaoLancamNotaUseCase.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterTotalAulasNaoLancamNota/ObterTotalAulasNaoLancamNotaQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterTotalAulasNaoLancamNota/ObterTotalAulasNaoLancamNotaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseConsulta.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/ObterTotalAulasNAoLancamNotaUseCaseTeste.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/RetornarTotalAulasNaoLancamNotaTeste.cs
[AB#64279](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64279)
=> Fix/64279 - Correção aulas exibidas nas abas bimestre para componentes que não lançam nota

src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Dados/Mapeamentos/AnotacaoFechamentoAlunoMap.cs, teste/SME.SGP.TesteIntegracao/Ao_registrar_anotacao_fechamento.cs
[AB#64292](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64292)
=> Fix/64292 - ajustes na tela de fechamento do listão

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#64269](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64269)
=> Fix/64269 - Correção exibição da soma total de aulas bimestre na aba final

src/SME.SGP.Aplicacao/Queries/DashboardDiarioBordo/ObterQuantidadeTotalDeDiariosPreenchidosEPendentesPorAnoTurma/ObterQuantidadeTotalDeDiariosPreenchidosEPendentesPorAnoTurmaQueryHandler.cs
[AB#64319](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64319)
=> Fix/64319 - ajustes de legenda no dash diário de bordo

src/SME.SGP.Dados/Repositorios/RepositorioEventoFechamentoConsulta.cs
[AB#64300](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64300)
=> Correção na validação do período de abertura

src/SME.SGP.Dominio/Enumerados/SituacaoMatriculaAluno.cs
[AB#64190](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64190)
=> Correção do bug 64190

src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterAulaPorIdUseCase.cs
[AB#64366](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64366)
=> Correção do bug 64366

src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaAlunoMensal.cs
[AB#64424](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64424)
=> Ajustada query de exclusão dos registros de frequências consolidados.

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs
[AB#64453](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64453)
=> Ajustada ordenação.

src/SME.SGP.Aplicacao/CasosDeUso/CompensacaoAusencia/NotificarCompensacaoAusenciaUseCase.cs, src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs
[AB#64444](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64444)
=> Correção do bug 64444

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs
[AB#64461](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64461)
=> fix/64484 - ajustes para trazer recomendações e anotações na tela do conselho

src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterAulaPorIdUseCase.cs
[AB#61411](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61411)
=> Erro ao cadastrar aula

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs
[AB#64453](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64453)
=> Ajustada descrição da UE para ser apresentada no dashboard.

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs, src/SME.SGP.Infra/Dtos/TotalCompensacoesComponenteNaoLancaNotaDto.cs
[AB#64413](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64413)
=> Fix/64413 - Correção exibição total aulas compensadas para o componente não lança nota

src/SME.SGP.Aplicacao/Commands/PendenciaDiarioBordo/ExcluirPendenciaDiarioBordoPorIdEComponenteId/ExcluirPendenciaDiarioBordoPorIdEComponenteIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaDiarioBordo/SalvarPendenciaDiarioBordo/SalvarPendenciaDiarioBordoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaUsuario/ObterPendenciasUsuarioPorPendenciaUsuarioId/ObterPendenciasUsuarioPorPendenciaUsuarioIdQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaUsuario/ObterPendenciasUsuarioPorPendenciaUsuarioId/ObterPendenciasUsuarioPorPendenciaUsuarioIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaDiarioBordoConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaUsuarioConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaUsuario.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaUsuarioConsulta.cs, src/SME.SGP.Infra/Dtos/PendenciaDiarioBordo/PendenciaDiarioBordoDescricaoDto.cs, src/SME.SGP.IoC/RegistraDependencias.cs, teste/SME.SGP.TesteIntegracao/PendenciaUsuario/Ao_gerar_pendencia_usuario.cs
[AB#64517](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64517)
=> Correção legenda reposição, pendencia_usuario duplicada, pesquisa inicial de dashboard

src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaCPEncaminhamentoAEE/GerarPendenciaCPEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
[AB#64320](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64320)
=> Correção do bug 64320

src/SME.SGP.Aplicacao/CasosDeUso/Aula/ObterAulaPorIdUseCase.cs
[AB#64383](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64383)
=> fix/64383 - ajustes ao alterar quantidade de aulas no calendário do professor

src/SME.SGP.Aplicacao/CasosDeUso/PendenciaDiarioBordo/TratarPendenciaDiarioBordoPorTurmaAulaComponenteUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PendenciaDiarioBordo/TratarPendenciaDiarioBordoPorTurmaUseCase.cs, src/SME.SGP.Aplicacao/Commands/PendenciaDiarioBordo/SalvarPendenciaDiarioBordo/SalvarPendenciaDiarioBordoCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciaDiarioBordo/SalvarPendenciaDiarioBordo/SalvarPendenciaDiarioBordoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciasGerais/SalvarPendencia/SalvarPendenciaCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PendenciaDiarioBordo/ITratarPendenciaDiarioBordoPorTurmaAulaComponenteUseCase.cs, src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciaPorDescricaoTipo/ObterPendenciaPorDescricaoTipoQuery.cs, src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciaPorDescricaoTipo/ObterPendenciaPorDescricaoTipoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaDiarioBordoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio/Entidades/Turma.cs, src/SME.SGP.Infra/Consts/PendenciaConstants.cs, src/SME.SGP.Infra/Dtos/Aula/FiltroPendenciaDiarioBordoTurmaAulaDto.cs, src/SME.SGP.Infra/Dtos/Pendencia/PendenciaComponenteCurricularDto.cs, src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs, teste/SME.SGP.TesteIntegracao/PendenciaDiarioBordo/Ao_gerar_pendencia_diario_bordo.cs
[AB#64645](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64645)
[AB#64623](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64623)
=> Criação da fila para inserir pendências por aula e criar penência geral

src/SME.SGP.Api/Controllers/DiretoriaRegionalEducacaoController.cs, src/SME.SGP.Api/Controllers/SupervisorController.cs, src/SME.SGP.Api/Controllers/UsuarioEscolaAquiController.cs, src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#63086](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63086)
=> Ajustado ENUM de permissões.

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterDadosAlunos/ObterDadosAlunosQuery.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterDadosAlunos/ObterDadosAlunosQueryHandler.cs
[AB#64493](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64493)
=> fix/64493 - ajuste para trazer dados de alunos conforme a listagem existente da tela do conselho

src/SME.SGP.Api/Controllers/UnidadesEscolaresController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Usuarios/ObterUsuarioFuncionarioUseCase.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/IObterUsuarioFuncionarioUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Aplicacao/Queries/Funcionario/ObterUsuarioFuncionario/ObterUsuarioFuncionarioQuery.cs, src/SME.SGP.Aplicacao/Queries/Funcionario/ObterUsuarioFuncionario/ObterUsuarioFuncionarioQueryHandler.cs, src/SME.SGP.IoC/RegistraDependencias.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs, teste/SME.SGP.TesteIntegracao/UnidadeEscolares/Ao_obter_usuario_funcionario.cs
[AB#61772](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61772)
[AB#64049](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64049)
=> Criar Endpoint Pesquisa de Funcionarios

src/SME.SGP.Api/Controllers/SupervisorController.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasSupervisor.cs, src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSupervisorEscolaDre.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs, src/SME.SGP.Dominio/Enumerados/TipoResponsavelAtribuicao.cs, src/SME.SGP.Infra/Dtos/FiltroObterSupervisorEscolasDto.cs, src/SME.SGP.Infra/Dtos/SupervisorEscolasDreDto.cs, src/SME.SGP.Infra/Dtos/SupervisorEscolasDto.cs
[AB#63096](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63096)
=> Alterar endpoint para de listagem de atribuições

scripts/V543__CREATE_TABLE_SUPORTE_USUARIO.sql, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Mapeamentos/SuporteUsuarioMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioSuporteUsuario.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSuporteUsuario.cs, src/SME.SGP.Dominio/Entidades/SuporteUsuario.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#64066](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64066)
[AB#64006](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64006)
=> Modelagem Suporte Usuario

src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs
[AB#64934](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64934)
=> Correção do bug 64934

src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciaIdPorComponenteProfessorBimestre/ObterPendenciaIdPorComponenteProfessorBimestreQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciaIdPorComponenteProfessorBimestre/ObterPendenciaIdPorComponenteProfessorBimestreQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs, teste/SME.SGP.TesteIntegracao/PendenciaAula/Ao_gerar_pendencia_aula.cs
[AB#64887](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64887)
=> Correção da duplicação de pendências/título das pendências de avaliações

src/SME.SGP.Dados/Repositorios/RepositorioAlunoFoto.cs
[AB#64316](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64316)
=> Correção do bug 64316

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#64987](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64987)
=> fix/64987 - ajuste na validação do endpoint de notas

src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoFrequenciaAluno/ConsolidarFrequenciaAlunoPorTurmaEMesUseCase.cs
[AB#64452](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64452)
[AB#65087](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65087)
=> Fix_64452 -> release

src/SME.SGP.Dados/Mapeamentos/ObjetivoAprendizagemMap.cs
[AB#64356](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64356)
=> fix/64356 - ajuste de coluna para trazer codigo dos objetivos de aprendizagem no listão.

src/SME.SGP.Infra/Dtos/Relatorios/FrequenciaMensal/FiltroRelatorioFrequenciaMensalDto.cs
[AB#65034](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65034) 
[AB#65123](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65123)
=> Erro ao tentar gerar relatorio SE limpar o campo "Apenas crianças com % abaixo de

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
=> Fix/64666 -  Correção do nome exibido nas turmas do listão

scripts/V544__CRIA_TABELA_PENDENCIA_DEVOLUTIVA.sql, src/SME.SGP.Dados/Mapeamentos/PendenciaDevolutivaMap.cs, src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaDevolutiva.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaDevolutiva.cs, src/SME.SGP.Dominio/Entidades/PendenciaDevolutiva.cs, src/SME.SGP.Dominio/Enumerados/TipoPendencia.cs, src/SME.SGP.IoC/RegistraDependencias.cs
[AB#63955](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63955)
=> Modelagem das pendências de devolutivas

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
[AB#65144](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65144) [AB#65150](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65150)
=> fix/65144 - ajustando listagem de alunos inativos na tela do conselho, para obedecer a primeira data do periodo escolar

src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaProfessor.cs, src/SME.SGP.Dominio/Entidades/Pendencia.cs, src/SME.SGP.Infra/Dtos/PendenciaAula/PendenciaAulaDto.cs, src/SME.SGP.Infra/Dtos/PendenciaPerfilUsuario/PendenciaPerfilUsuarioDto.cs, src/SME.SGP.Infra/Dtos/PendenciaProfessor/PendenciaProfessorDto.cs
[AB#65052](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65052)
[AB#64883](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64883)
=> Correção das pendências (geral)

src/SME.SGP.Dados/Repositorios/RepositorioItinerancia.cs, src/SME.SGP.Infra/Dtos/Itinerancia/ItineranciaObjetivosBaseDto.cs
[AB#65155](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65155)
=> Registro de itinerância - Erro 500

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs, src/SME.SGP.Infra/Dtos/Turma/RetornoConsultaListagemTurmaComponenteDto.cs
=> Fix/64666 - Correção para exibir nome dos componentes ao lado da turma na tela do listão

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
=> Fix/64666 - correção lista turmas nome componente

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
=> correção exibir descrição do componente educação infantil

src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciaDiarioBordoPorComponenteTurmaCodigo/ObterPendenciaDiarioBordoPorComponenteProfessorPeriodoEscolarQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterIndicativoPendenciasAulasPorTipo/ObterIndicativoPendenciasAulasPorTipoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaDiarioBordo/ObterIdPendenciaDiarioBordoPorAulaEComponenteId/ObterIdPendenciaDiarioBordoPorAulaEComponenteIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaDiarioBordo/ObterIdPendenciaDiarioBordoPorAulaId/ObterIdPendenciaDiarioBordoPorAulaIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaDiarioBordo/ObterPendenciasDiarioBordo/ObterPendenciasDiarioBordoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaDiarioBordo/ObterTurmaDaPendenciaDiario/ObterTurmaDaPendenciaDiarioQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaDiarioBordo/VerificaSeExistePendenciaDiarioComPendenciaId/VerificaSeExistePendenciaDiarioComPendenciaIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaDiarioBordo.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaDiarioBordoConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaProfessor.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaDiarioBordo.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaDiarioBordoConsulta.cs, teste/SME.SGP.Aplicacao.Teste/Queries/Listao/ObterIndicativoPendenciasAulasPorTipoQueryHandlerTeste.cs
[AB#64883](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64883)
=> Considerar somente pendências ativas (not excluida) e organizando consultas de diário no repositório próprio

src/SME.SGP.Aplicacao/Integracoes/ServicoPerfil.cs
[AB#65372](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65372)
=> fix/65372 - ajuste de validação de perfil ao logar para não trazer perfis fora do existente

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaPreDefinida.cs
[AB#65370](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65370)
=> Correção do bug 65370

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs, src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQueryHandler.cs
[AB#65381](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65381)
=> Correção do bug 65381

src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaDiarioBordoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaDreUeUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaDreUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/Pendencia/IPendenciaAulaDreUeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Aula/Pendencia/IPendenciaAulaDreUseCase.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUesCodigosPorDre/ObterUesCodigosPorDreQuery.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUesCodigosPorDre/ObterUesCodigosPorDreQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUesPorDreCodigo/ObterUesPorDreCodigoQuery.cs, src/SME.SGP.Aplicacao/Queries/UE/ObterUesPorDreCodigo/ObterUesPorDreCodigoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioUeConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioUeConsulta.cs, src/SME.SGP.Infra/Dtos/DreDto.cs, src/SME.SGP.Infra/Dtos/DreUeDto.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgp.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/PendenciaAula/PendenciaAulaFrequenciaUseCaseTeste.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/PendenciaDiarioBordo/PendenciaAulaDiarioBordoUseCaseTeste.cs
=> Pendências duplicadas - separação de filas por dre/ue (frequência, avaliações e plano de aula)

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#65141](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65141)
=> Correção do bug 65141

src/SME.SGP.Aplicacao/CasosDeUso/Devolutiva/InserirDevolutivaUseCase.cs
[AB#65387](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65387)
=> Correção do bug 65387

src/SME.SGP.Aplicacao/Consultas/ConsultasTurma.cs
[AB#65438](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65438)
=> Consulta de alunos pela tabela de normalização

src/SME.SGP.Aplicacao/Integracoes/ServicoPerfil.cs
=> fix/65372 -> master

src/SME.SGP.Aplicacao/CasosDeUso/PendenciaDiarioBordo/TratarPendenciaDiarioBordoPorTurmaAulaComponenteUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PendenciaDiarioBordo/TratarPendenciaDiarioBordoPorTurmaUseCase.cs, src/SME.SGP.Aplicacao/Commands/PendenciaDiarioBordo/SalvarPendenciaDiarioBordo/SalvarPendenciaDiarioBordoCommand.cs, src/SME.SGP.Aplicacao/Commands/PendenciaDiarioBordo/SalvarPendenciaDiarioBordo/SalvarPendenciaDiarioBordoCommandHandler.cs, src/SME.SGP.Infra/Dtos/Aula/FiltroPendenciaDiarioBordoTurmaAulaDto.cs, src/SME.SGP.Infra/Dtos/PendenciaDiarioBordo/AulaProfessorComponenteDto.cs, src/SME.SGP.Infra/Dtos/PendenciaDiarioBordo/PendenciaProfessorComponenteCurricularDto.cs, teste/SME.SGP.TesteIntegracao/PendenciaDiarioBordo/Ao_gerar_pendencia_diario_bordo.cs
=> Tratamento de duplicidade de pendências de diário de bordo

src/SME.SGP.Api/Controllers/SupervisorController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Supervisor/ObterSupervisoresPorDreUseCase.cs, src/SME.SGP.Infra/Dtos/FiltroObterSupervisoresDto.cs, src/SME.SGP.Infra/Dtos/Supervisor/ObterSupervisoresPorDreDto.cs, src/SME.SGP.Infra/Enumerados/Permissao.cs
[AB#65407](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65407)
=> Feature/65407 -> Story/62890

src/SME.SGP.Aplicacao/Queries/Devolutiva/ExistePendenciaDiarioBordo/ExistePendenciaDiarioBordoQuery.cs, src/SME.SGP.Aplicacao/Queries/Devolutiva/ExistePendenciaDiarioBordo/ExistePendenciaDiarioBordoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDiarioBordo.cs, src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoSemDevolutivaDto.cs, teste/SME.SGP.Aplicacao.Teste/Queries/Devolutiva/ExistePendenciaDiarioBordoQueryTest.cs
[AB#63948](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63948)
=> Criação da Query para identificar pendências

scripts manutencao/64328 - Exportação TCM/1-estrutura.sql, scripts manutencao/64328 - Exportação TCM/2-carga.sql, scripts manutencao/64328 - Exportação TCM/3-exportacao.sql
[AB#64328](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64328)
=> Exportação do Relatório para o TCM

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodo.cs
[AB#61305](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61305)
=> fix/61305 - Excluir a frequencia_aluno quando excluir a aula

src/SME.SGP.Aplicacao/CasosDeUso/PendenciaDiarioBordo/TratarPendenciaDiarioBordoPorTurmaUseCase.cs
=> Correção das aulas, professores e componentes curriculares

scripts/V543__CREATE_TABLE_SUPORTE_USUARIO.sql, src/SME.SGP.Api/Controllers/AutenticacaoController.cs, src/SME.SGP.Aplicacao/Comandos/ComandosUsuario.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosUsuario.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/Servicos/IServicoAutenticacao.cs, src/SME.SGP.Aplicacao/Interfaces/Servicos/IServicoTokenJwt.cs, src/SME.SGP.Aplicacao/Servicos/ServicoAutenticacao.cs, src/SME.SGP.Aplicacao/Servicos/ServicoTokenJwt.cs, src/SME.SGP.Dados/Mapeamentos/SuporteUsuarioMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioSuporteUsuario.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSuporteUsuario.cs, src/SME.SGP.Dominio/Entidades/SuporteUsuario.cs, src/SME.SGP.Infra/Enumerados/Permissao.cs, teste/SME.SGP.Aplicacao.Teste/Comandos/ComandosUsuarioTeste.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
[AB#64059](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64059)
[AB#64006](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64006)
=> Alterar Autenticação

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ObterAcompanhamentoAlunoUseCase.cs, src/SME.SGP.Aplicacao/Queries/PeriodoFechamento/ObterPeriodosFechamentoTurmaInfantilCalendarioIdBimestre/ObterPeriodosFechamentoTurmaInfantilCalendarioIdBimestreQuery.cs, src/SME.SGP.Aplicacao/Queries/PeriodoFechamento/ObterPeriodosFechamentoTurmaInfantilCalendarioIdBimestre/ObterPeriodosFechamentoTurmaInfantilCalendarioIdBimestreQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEventoFechamentoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEventoFechamentoConsulta.cs
[AB#65663](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65663)
=> Ajuste na verificação do período fechamento para turmas do infantil

src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs
=> Ajuste Merge

scripts/V546__INCLUIR_PARAMETRO_SISTEMA_GERAR_PENDENCIA_DEVOLUTIVA.sql, src/SME.SGP.Aplicacao/CasosDeUso/Devolutiva/InserirDevolutivaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordoPendenciaDevolutiva/ReprocessarDiarioBordoPendenciaDevolutivaPorComponenteUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordoPendenciaDevolutiva/ReprocessarDiarioBordoPendenciaDevolutivaPorDreUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordoPendenciaDevolutiva/ReprocessarDiarioBordoPendenciaDevolutivaPorTurmaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DiarioBordoPendenciaDevolutiva/ReprocessarDiarioBordoPendenciaDevolutivaPorUeUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DiarioBordoPendenciaDevolutiva/IReprocessarDiarioBordoPendenciaDevolutivaPorComponenteUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DiarioBordoPendenciaDevolutiva/IReprocessarDiarioBordoPendenciaDevolutivaPorDreUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DiarioBordoPendenciaDevolutiva/IReprocessarDiarioBordoPendenciaDevolutivaPorTurmaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DiarioBordoPendenciaDevolutiva/IReprocessarDiarioBordoPendenciaDevolutivaPorUeUseCase.cs, src/SME.SGP.Aplicacao/Queries/Devolutiva/ExistePendenciaDiarioBordo/ExistePendenciaDiarioBordoQuery.cs, src/SME.SGP.Aplicacao/Queries/Devolutiva/ExistePendenciaDiarioBordo/ExistePendenciaDiarioBordoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Devolutiva/ProcessarPendenciaDevolutiva/ProcessarPendenciaDevolutivaQuery.cs, src/SME.SGP.Aplicacao/Queries/Devolutiva/ProcessarPendenciaDevolutiva/ProcessarPendenciaDevolutivaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterCodigosTurmasPorAnoModalidadeUe/ObterCodigosTurmasPorAnoModalidadeUeQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterCodigosTurmasPorAnoModalidadeUe/ObterCodigosTurmasPorAnoModalidadeUeQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaDevolutiva.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioDiarioBordo.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaDevolutiva.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurmaConsulta.cs, src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs, src/SME.SGP.Infra/Dtos/DiarioBordo/FiltroDiarioBordoPendenciaDevolutivaDto.cs, src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs, teste/SME.SGP.Aplicacao.Teste/Queries/Devolutiva/ExistePendenciaDiarioBordoQueryTest.cs, teste/SME.SGP.TesteIntegracao/PendenciaDevolutiva/Ao_gerar_pendencia_devolutiva.cs
[AB#63952](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63952)
=> Criação do worker para notificação de pendência CP - Feature/63952

src/SME.SGP.Aplicacao/Queries/Usuario/ObterPerfilAtual/ObterPerfilAtualQueryHandler.cs, teste/SME.SGP.TesteIntegracao/Responsavel/Ao_obter_lista_tipo_responsavel.cs, teste/SME.SGP.TesteIntegracao/Setup/RegistradorDependencias.cs
[AB#65731](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65731)
[AB#65738](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65738)
=> Ajustado teste de integração.

src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs
[AB#65740](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65740)
=> Correção da consulta de supervisores (EscolaId estava vazio)

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUsuarioECodigoTurma/ObterComponentesCurricularesPorUsuarioECodigoTurmaQueryHandler.cs
[AB#62181](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62181)
=> Ajuste na unificação dos componentes do infantil

src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciaIdPorComponenteProfessorBimestre/ObterPendenciaIdPorComponenteProfessorBimestreQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciaIdPorComponenteProfessorBimestre/ObterPendenciaIdPorComponenteProfessorBimestreQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Infra/Dtos/PendenciaAula/PendenciaAulaProfessorDto.cs, teste/SME.SGP.TesteIntegracao/PendenciaAula/Ao_gerar_pendencia_aula.cs
Fix/61492 merge com Release-R2
=> Fix/61492 merge com Release-R2

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_acessar_tela_conselho_de_classe.cs
[AB#64490](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64490)
=> Fix/64490 - correção para exibir notas dos alunos inativos com notas dentro do periodo de fechamento

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasAutomaticamente/CriarAulasRegenciaAutomaticamenteCommandHandler.cs
[AB#64337](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64337)
=> Correção do bug 64337

src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasSupervisor.cs, src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSupervisorEscolaDre.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
[AB#65740](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65740)
=> Correção de bug ao selecionar filtro

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs, src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs, src/SME.SGP.Infra/Dtos/ComponenteCurricular/ComponenteCurricularSimplesDto.cs
=> Fix/64666 - correcao conflito

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
=> Fix/64666_v2 - correção nome exibido nas turmas do listão

src/SME.SGP.Api/Controllers/AulaController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Aula/ExcluirAulaUseCase.cs, src/SME.SGP.Infra/Dtos/Aula/ExcluirAulaDto.cs
[AB#65788](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65788)
=> Ajuste na consulta de nome do componente curricular

src/SME.SGP.Infra/Dtos/DiarioBordo/DiarioBordoObservacaoNotificacaoUsuarioDto.cs
[AB#65792](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65792)
[AB#63040](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63040)
=> 65792 corrigido processamento quando não existe notificação na base para exclusão

scripts/V547__ADICIONAR_COLUNA_ADMINISTRADOR_TABELA_AUDITORIA.sql
[AB#64058](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64058)
=> Script de alteração da tabela auditoria

src/SME.SGP.Dados/Contexto/SgpContext.cs, src/SME.SGP.Dados/Mapeamentos/AuditoriaMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioBase.cs, src/SME.SGP.Dominio/Entidades/Auditoria.cs, src/SME.SGP.Infra/Contexto/ContextoBase.cs, src/SME.SGP.Infra/Interfaces/IContextoAplicacao.cs, src/SME.SGP.Infra/Interfaces/ISgpContext.cs
[AB#64056](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64056)
=> Alterar a persistência da tabela de auditoria

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
[AB#65569](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65569)
=> Correção do bug 65569

src/SME.SGP.Dados/Mapeamentos/ConsolidacaoDevolutivasMap.cs, src/SME.SGP.Dados/Mapeamentos/ConsolidacaoMatriculaTurmaMap.cs, src/SME.SGP.Dados/Mapeamentos/ConsolidacaoRegistrosPedagogicosMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoMatriculaTurma.cs
[AB#66178](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66178)
[AB#63040](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/63040)
=> 66178 Corrigido inclusão da entidade Consolidação Matricula Turma depois da atualização para o NetCore 5

src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PendenciaDiarioBordo/SalvarPendenciaDiarioBordo/SalvarPendenciaDiarioBordoCommandHandler.cs, src/SME.SGP.Infra/Dtos/PendenciaDiarioBordo/PendenciaProfessorComponenteCurricularDto.cs
[AB#64883](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/64883)
=> Fazer a consulta antes da abertura de transação - remoção de testes

src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AtribuicaoDeResponsaveis/AtribuicaoResponsaveisASPPPorDreUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AtribuicaoDeResponsaveis/AtribuicaoResponsaveisPAAIPorDreUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AtribuicaoDeResponsaveis/AtribuicaoResponsaveisPorDreUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AtribuicaoDeResponsaveis/AtribuicaoResponsaveisSupervisorPorDreUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AtribuicaoDeResponsaveis/IAtribuicaoResponsaveisASPPPorDreUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AtribuicaoDeResponsaveis/IAtribuicaoResponsaveisPAAIPorDreUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AtribuicaoDeResponsaveis/IAtribuicaoResponsaveisPorDreUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/AtribuicaoDeResponsaveis/IAtribuicaoResponsaveisSupervisorPorDreUseCase.cs, src/SME.SGP.Infra/Fila/RotasRabbitSgp.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
[AB#65571](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65571)
=> Feature/65571 - Criar filas por Dre

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs
Ajuste na funcionalidade de copiar arquivo verificando se houve sucesso no teste de regex do arquivo.
=> Bug: 66340

scripts/V548__ADICIONAR_COLUNA_RESPONSAVEL_RENOMEAR_ATUAL_TABELA_PLANOAEE.sql, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterParecerPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/AtribuirResponsavelPlanoAEE/AtribuirResponsavelPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/CadastrarParecerPAAI/CadastrarParecerPAAICommandHandler.cs, src/SME.SGP.Dados/Mapeamentos/PlanoAEEMap.cs, src/SME.SGP.Dominio/Entidades/PlanoAEE.cs
[AB#65297](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65297)
=> Modelagem para incluir campo responsável

src/SME.SGP.Api/Startup.cs, src/SME.SGP.Aplicacao/Commands/Arquivos/MoverArquivosTemporarios/MoverArquivosTemporariosCommandHandler.cs
[AB#66338](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66338)
=> Correção do bug 66338

src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ExecutaConsolidacaoDashBoardFrequenciaPorUeUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ExecutaConsolidacaoDiariaDashBoardFrequenciaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ExecutaConsolidacaoMensalDashBoardFrequenciaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DashboardFrequencia/ExecutaConsolidacaoSemanalDashBoardFrequenciaUseCase.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoFrequenciaDashBoard/InserirConsolidacaoDashBoardFrequencia/InserirConsolidacaoDashBoardFrequenciaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoFrequenciaDashBoard/InserirConsolidacaoMensalDashBoardFrequencia/InserirConsolidacaoMensalDashBoardFrequenciaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoFrequenciaTurma/AlterarConsolidacaoDashboardFrequenciaTurma/AlterarConsolidacaoDashboardFrequenciaTurmaCommand.cs, src/SME.SGP.Aplicacao/Commands/ConsolidacaoFrequenciaTurma/AlterarConsolidacaoDashboardFrequenciaTurma/AlterarConsolidacaoDashboardFrequenciaTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/DashboardFrequencia/IExecutaConsolidacaoDashBoardFrequenciaPorUeUseCase.cs, src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterConsolidacaoExistentePorTurmaIdAnoLetivoTipoPeriodoMes/ObterConsolidacaoExistentePorTurmaIdAnoLetivoTipoPeriodoMesQuery.cs, src/SME.SGP.Aplicacao/Queries/DashboardFrequencia/ObterConsolidacaoExistentePorTurmaIdAnoLetivoTipoPeriodoMes/ObterConsolidacaoExistentePorTurmaIdAnoLetivoTipoPeriodoMesQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaTurma.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConsolidacaoFrequenciaTurma.cs, src/SME.SGP.Infra/Dtos/ConsolidadoDashBoardFrequencia/RetornoConsolidacaoExistenteDto.cs, src/SME.SGP.Infra/Dtos/DashBboardFrequencia/ConsolidacaoPorUeDashBoardFrequencia.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgp.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs, teste/SME.SGP.TesteIntegracao/ConsolidacaoDashboardFrequenciaTurma/Ao_registrar_frequencia_para_uma_turma.cs
[AB#65448](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65448)
=> Feature/65448 - melhoria no processo de consolidação dashboard frequência mensal

scripts/V549__ATRIBUIR_REPONSAVEL_TABELA_PLANO_AEE .sql, src/SME.SGP.Aplicacao/Commands/PlanoAEE/SalvarPlanoAee/SalvarPlanoAeeCommandHandler.cs, teste/SME.SGP.TesteIntegracao/Plano AEE/Ao_gerar_plano_com_responsavel.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
[AB#65302](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65302)
=> Migração dos planos atuais

src/SME.SGP.Aplicacao/CasosDeUso/SincronizacaoInstitucional/Turma/ExecutarSincronizacaoInstitucionalTurmaExcluirTurmaExtintaUseCase.cs, src/SME.SGP.Aplicacao/Commands/SincronizacaoInstituicional/Turmas/TrataSincronizacaoInstitucionalTurma/TrataSincronizacaoInstitucionalTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/SincronizacaoInstitucional/IExecutarSincronizacaoInstitucionalTurmaExcluirTurmaExtintaUseCase.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpInstitucional.cs, src/SME.SGP.IoC/RegistraDependencias.cs, src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs, teste/SME.SGP.TesteIntegracao/ExcluirTurmaExtinta/Excluir_turma_extinta.cs
[AB#65604](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65604)
[AB#65865](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65865)
=> R2 - Story/65604 - Adequação ao nome da fila ao padrão de sequência de processamento

src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs, src/SME.SGP.Dominio/Entidades/Pendencia.cs
[AB#66317](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66317)
=> Correção do bug 66317

scripts/V550__WF_APROVACAO_NOTA_FECHAMENTO_REMOVER_OBRIGATORIEDADE_WF_APROVACAO.sql, src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaFechamento/ExcluirWFAprovacaoNotaFechamentoPorNota/ExcluirWFAprovacaoNotaFechamentoPorNotaCommandHandler.cs, src/SME.SGP.Dados/Mapeamentos/WfAprovacaoNotaFechamentoMap.cs, src/SME.SGP.Dados/Repositorios/RepositorioWfAprovacaoNotaFechamento.cs, src/SME.SGP.Dominio/Entidades/WfAprovacaoNotaFechamento.cs, teste/SME.SGP.TesteIntegracao/WfAprovacaoNotaFechamento/Ao_gerar_wf_aprovacao_nota_fechamento.cs
[AB#62106](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62106)
=> feature/62106 - Modelagem tabela de wf_aprovacao_fechamento_nota e adicionar auditoria

teste/SME.SGP.TesteIntegracao/AuditoriaAdministrador/Ao_gerar_aula_recorrente_pelo_worker_com_auditoria_administrador.cs
=> Correção nome classe de rota

src/SME.SGP.Aplicacao/Consultas/ConsultasUsuario.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasUsuario.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Aplicacao/Servicos/ServicoAutenticacao.cs, src/SME.SGP.Dominio.Servicos/ServicoUsuario.cs, src/SME.SGP.Infra/Dtos/AutenticacaoApiEolDto.cs, src/SME.SGP.Infra/Dtos/PerfisApiEolDto.cs, teste/SME.SGP.Aplicacao.Teste/Servicos/ServicoAutenticacaoTeste.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
=> Alterado autenticação EOL para fazer autenticação e depois carregar os perfis

src/SME.SGP.Aplicacao/CasosDeUso/EscolaAqui/Dashboard/ObterComunicadosParaFiltro/ObterComunicadosParaFiltroDaDashboardUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/ObterComunicadosParaFiltroDaDashboardUseCase/IObterComunicadosParaFiltroDaDashboardUseCase.cs, src/SME.SGP.Aplicacao/Queries/EscolaAqui/ObterComunicadosParaFiltro/ObterComunicadosParaFiltroDaDashboardQuery.cs, src/SME.SGP.Aplicacao/Queries/EscolaAqui/ObterComunicadosParaFiltro/ObterComunicadosParaFiltroDaDashboardQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioComunicado.cs
[AB#66452](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66452)
=> ajuste na query de obter comunicados

src/SME.SGP.Aplicacao/CasosDeUso/DashboardRegistroIndividual/ObterQuantidadeRegistrosIndividuaisPorAnoTurmaUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasUsuario.cs, src/SME.SGP.Aplicacao/Integracoes/ServicoEOL.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasUsuario.cs, src/SME.SGP.Aplicacao/Interfaces/Integracoes/IServicoEOL.cs, src/SME.SGP.Aplicacao/Queries/DashboardRegistroIndividual/ObterQuantidadeRegistrosIndividuaisPorAnoTurma/ObterQuantidadeRegistrosIndividuaisPorAnoTurmaQueryHandler.cs, src/SME.SGP.Aplicacao/Servicos/ServicoAutenticacao.cs, src/SME.SGP.Dominio.Servicos/ServicoUsuario.cs, src/SME.SGP.Infra/Dtos/AutenticacaoApiEolDto.cs, src/SME.SGP.Infra/Dtos/Grafico/RegistroIndividual/QuantidadeRegistrosIndividuaisPorAnoTurmaDTO.cs, src/SME.SGP.Infra/Dtos/PerfisApiEolDto.cs, teste/SME.SGP.Aplicacao.Teste/Servicos/ServicoAutenticacaoTeste.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
[AB#66510](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66510)
=> Ajuste no tratamento de dados nulos de retorno

src/SME.SGP.Api/Controllers/AutenticacaoController.cs
=> correção do merge

src/SME.SGP.Infra/Dtos/OpcaoDropdownDto.cs
[AB#66449](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66449)
=> Correção do bug 66449

src/SME.SGP.Aplicacao/CasosDeUso/DashboardCompensacaoAusencia/ObterDadosDashboardTotalAtividadesCompensacaoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/DashboardFechamento/ObterFechamentoConselhoClasseSituacaoUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#66514](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66514)
=> Ajuste na query do consolidado

src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs, teste/SME.SGP.TesteIntegracao/AuditoriaAdministrador/Ao_gerar_aula_recorrente_pelo_worker_com_auditoria_administrador.cs
Retirando interface do construtor worker
=> Retirando interface do construtor worker

src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaSgp/PublicarFilaSgpCommandHandler.cs, src/SME.SGP.IoC/Extensions/RegistrarRabbit.cs, src/SME.SGP.Worker.Rabbbit/Startup.cs, teste/SME.SGP.TesteIntegracao/AuditoriaAdministrador/Ao_gerar_aula_recorrente_pelo_worker_com_auditoria_administrador.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/WorkerServiceScopeFactoryFake.cs, teste/SME.SGP.TesteIntegracao/TesteBase.cs
=> ajuste teste worker rabbit

src/SME.SGP.Worker.Rabbbit/WorkerRabbitMQ.cs
revertendo modificação interface worker
=> revertendo modificação interface worker

src/SME.SGP.Aplicacao/Queries/EOL/Funcionario/ObterFuncionariosPorDreEol/ObterFuncionariosPorDreEolQueryValidator.cs
[AB#66328](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66328)
=> Plano AEE - Erro na atribuição do PAAI

src/SME.SGP.Fechamento.Worker/Startup.cs, src/SME.SGP.Fechamento.Worker/WorkerRabbitFechamento.cs
fix adicionar IServicoTelemetria
=> fix adicionar IServicoTelemetria

src/SME.SGP.Dados/Mapeamentos/AulaMap.cs
Ajuste da classe de mapeamento de aula.
=> Bug: 66311

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/GerarPendenciaValidadePlanoAEEUseCase.cs, teste/SME.SGP.TesteIntegracao/Plano AEE/Ao_gerar_pendencia_valide_plano.cs
[AB#65313](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65313)
=> Alterar criação de pendência do plano aee

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
[AB#61165](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/61165)
=> Ajuste no percentual de frequência

src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativaDisciplina.cs
[AB#65378](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65378)
=> fix/65378 - ajustando consulta de total de atividades avaliativas 

src/SME.SGP.Api/Controllers/EncaminhamentoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/PesquisaResponsavelPlanoPorDreUEUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/EncaminhamentoAEE/IPesquisaResponsavelPlanoPorDreUEUseCase.cs, src/SME.SGP.Aplicacao/Queries/EOL/Funcionario/ObterFuncionariosPorDreEol/ObterFuncionariosPorDreEolQueryValidator.cs, src/SME.SGP.IoC/RegistraDependencias.cs, teste/SME.SGP.TesteIntegracao/Plano AEE/Ao_pesquisar_responsavel_plano.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/Query/ObterFuncionariosPorDreEolQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/Setup/CollectionFixture.cs, teste/SME.SGP.TesteIntegracao/Setup/RegistraMock.cs
[AB#6661](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/6661)
=> Criar endpond pesquisa responsável

src/SME.SGP.Api/Controllers/EncaminhamentoAEEController.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPAAIPorDreUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/PlanoAEE/IObterPAAIPorDreUseCase.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/ObterPAAIPorDre/ObterPAAIPorDreQuery.cs, src/SME.SGP.Aplicacao/Queries/EncaminhamentoAEE/ObterPAAIPorDre/ObterPAAIPorDreQueryHandler.cs, src/SME.SGP.IoC/RegistraDependencias.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_acessar_controller_obter_paai.cs
[AB#65588](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65588)
=> endpoint para obter os PAAI  na tabela supervisor_escola_dre

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaDiariaAluno.cs
[AB#65249](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65249)
=> Correção na Paginação da Listagem

src/SME.SGP.Api/Controllers/SupervisorController.cs
[AB#66321](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66321)
[AB#66364](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66364)
=> Sem dados em tipo de responsável quando logado com ADM SME

src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaPorCodigo/ObterTurmaPorCodigoQueryHandler.cs
[AB#66638](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66638)
=> Correção do bug 66638

src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/RemoverResponsavelEncaminhamentoAEE/RemoverResponsavelEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Dominio/Enumerados/SituacaoAEE.cs
[AB#65600](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65600)
=> 65600 - Alterar a situação para Aguardando atribuição de PAAI

src/SME.SGP.Aplicacao/CasosDeUso/Nota/NotificarAlteracaoNotaFechamentoAgrupadaTurmaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaFechamento/EnviarNotasFechamentoParaAprovacao/EnviarNotasFechamentoParaAprovacaoCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioWfAprovacaoNotaFechamento.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs, src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs, src/SME.SGP.Infra/Dtos/FechamentoNota/WfAprovacaoNotaFechamentoTurmaDto.cs, teste/SME.SGP.TesteIntegracao/WfAprovacaoNotaFechamento/Ao_gerar_wf_aprovacao_nota_fechamento.cs
[AB#62136](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62136)
=> feature/62136 - ajustes para wf aprovação nota fechamento

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaDiariaAluno.cs
[AB#66714](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66714)
=> Justificativa de ausência não é removida do Acompanhamento de Frequência

src/SME.SGP.Aplicacao/Queries/FrequenciaDiariaAluno/ObterFrequenciaDiariaAlunoQueryHandler.cs
[AB#66712](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66712)
=> Informações de Ausência divergente entre os campos da tela.

src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoDeResponsaveis/RemoverAtribuicaoResponsaveisASPPPorDreUseCase.cs
remoção de um if na consulta ao eol
=> Story/65536 -> Release

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaDevolutiva.cs
[AB#66985](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66985)
=> Ajustado filtro para consulta e execução da atualização das pendências.

src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
[AB#65604](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65604)
=> R2 - story/65604 - Adicionando telemetria para o delete de turmas extintas

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseRecomendacao.cs, src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs
[AB#66605](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66605)
=> Ajuste no tratamento de alunos inativos

src/SME.SGP.Dados/Repositorios/RepositorioTurma.cs
[AB#65604](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65604)
=> R2 - story/65604 - Adequação da informação de telemetria

src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs
[AB#66663](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66663)
=> Correção do bug 66663

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
[AB#66662](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66662)
=> fix/66662 -> master

teste/SME.SGP.TesteIntegracao/Aula/Ao_registrar_aula_unica.cs, teste/SME.SGP.TesteIntegracao/Aula/AulaBuilder.cs, teste/SME.SGP.TesteIntegracao/ItensBasicosBuilder.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoEOLFake.cs
[AB#66717](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66717)
=> teste aula unica

src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoRegistrosPedagogicos.cs
[AB#66855](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66855)
=> Ajuste na query de gerar registro pedagógico

teste/SME.SGP.TesteIntegracao/Aula/Ao_registrar_aula_unica.cs
[AB#66717](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66717)
=> cadastro aula unica

teste/SME.SGP.TesteIntegracao/Aula/Ao_registrar_aula_professor_cj.cs
[AB#66722](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66722)
=> Cadastro de aula fora do período

teste/SME.SGP.TesteIntegracao/Aula/Ao_validar_grade_para_registro_de_aula.cs
[AB#66721](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66721)
=> Cadastro de aula , validando grade

teste/SME.SGP.TesteIntegracao/Aula/Ao_registrar_aula_unica.cs, teste/SME.SGP.TesteIntegracao/Aula/AulaTeste.cs
[AB#66717](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66717)
=> Cadastro de aula Única

src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_alterar_aula_unica.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_validar_grade_para_registro_de_aula.cs, teste/SME.SGP.TesteIntegracao/Aula/AulaTeste.cs
[AB#66726](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66726)
=> Alteração de Aula única

teste/SME.SGP.TesteIntegracao/Aula/Ao_alterar_aula_unica.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_excluir_aula_unica.cs, teste/SME.SGP.TesteIntegracao/Aula/AulaTeste.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/IncluirFilaCalcularFrequenciaPorTurmaCommandHandlerFake.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/IncluirFilaConciliacaoFrequenciaTurmaCommandHandlerFake.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ObterAlunosPorTurmaQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/PublicarFilaEmLoteSgpCommandHandlerFake.cs, teste/SME.SGP.TesteIntegracao/Setup/CollectionFixture.cs, teste/SME.SGP.TesteIntegracao/Setup/RegistraMock.cs
[AB#66729](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66729)
=> Exclusão de aula única

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
[AB#66776](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66776)
=> Correção do bug 66776

src/SME.SGP.Api/Controllers/ProfessorController.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasDisciplina.cs
[AB#66860](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66860)
=> Ajuste na lista de componentes de regência.

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Evento/ObterEventosCalendarioProfessorPorMesDia/ObterEventosCalendarioProfessorPorMesDiaQuery.cs, src/SME.SGP.Aplicacao/Queries/Evento/ObterEventosCalendarioProfessorPorMesDia/ObterEventosCalendarioProfessorPorMesDiaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEvento.cs
[AB#67092](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67092)
=> Correção do bug 67092

src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoDeResponsaveis/RemoverAtribuicaoResponsaveisASPPPorDreUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoDeResponsaveis/RemoverAtribuicaoResponsaveisPAAIPorDreUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoDeResponsaveis/RemoverAtribuicaoResponsaveisSupervisorPorDreUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Responsavel/AtribuirUeResponsavelUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Responsavel/ObterResponsaveisPorDreUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs, src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs, src/SME.SGP.Infra/Dtos/Responsavel/ResponsavelEscolasDto.cs, src/SME.SGP.Infra/Dtos/Supervisor/SupervisorEscolasDreDto.cs
[AB#67348](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67348)
[AB#66803](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66803)
[AB#67356](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67356)
[AB#66806](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66806)
[AB#67357](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67357)
[AB#67057](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67057)
=> Correção bugs 66806, 66803,67057

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurma/ObterNotasFechamentosPorTurmasCodigosBimestre/ObterNotasFechamentosPorTurmasCodigosBimestreQuery.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotaConceitoBimestreConsulta.cs
[AB#66275](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66275)
=> Ajuste na consulta de notas de anos anteriores de alunos transferidos.

src/SME.SGP.Infra/Dtos/AulaPrevistaBimestreQuantidadeDto.cs
[AB#66666](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66666)
=> Correção do bug 66666

src/SME.SGP.Dados/Repositorios/RepositorioComponenteCurricularConsulta.cs, teste/SME.SGP.TesteIntegracao/ComponenteCurricular/Ao_obter_componente_curricular.cs
[AB#67081](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67081)
=> fix/67081 -> master

teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_acessar_tela_conselho_de_classe.cs
Ajustes de testes de integração relacionadas ao ajuste do bug.
=> Bug: 66781

src/SME.SGP.Aplicacao/Queries/TipoCalendario/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDia/ObterAulaEventoAvaliacaoCalendarioProfessorPorMesDiaQueryHandler.cs, src/SME.SGP.Dominio/Entidades/Usuario.cs
[AB#66860](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66860)
=> Complemento ajuste do bug 66860

src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_registrar_aula_reposicao.cs, teste/SME.SGP.TesteIntegracao/Aula/Ao_registrar_aula_unica.cs
[AB#66725](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66725)
=> Cadastro de aula de reposição

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
=> Correção do bug 67426

src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs
[AB#67085](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67085)
=>  ajuste de contagem de aulas dadas e quantidade de frequencias

src/SME.SGP.Aplicacao/Comandos/ComandosUsuario.cs, src/SME.SGP.Infra/Dtos/Usuario/AdministradorSuporteDto.cs, src/SME.SGP.Infra/Dtos/UsuarioAutenticacaoRetornoDto.cs
[AB#66994](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66994)
=> Retorno do Adm suporte no dto

src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs
[AB#67085](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67085)
=> fix/67085 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterAulasEventosProfessorCalendarioPorMesDiaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Aula/ObterPodeCadastrarAulaPorData/ObterPodeCadastrarAulaPorDataQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Turma/TurmaEmPeriodoAberto/TurmaEmPeriodoAbertoQueryHandler.cs
[AB#67472](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67472)
[AB#67637](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67637)
=> Correção do bug: 67472

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#67642](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67642)
=> A turma do estudante na tela de edição do plano está divergente.

src/SME.SGP.Aplicacao/Queries/Aula/ObterPodeCadastrarAulaPorData/ObterPodeCadastrarAulaPorDataQueryHandler.cs, teste/SME.SGP.TesteIntegracao/AuditoriaAdministrador/Ao_gerar_aula_com_auditoria_administrador.cs
[AB#67472](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67472)
=> Ajustado teste de integração

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#67629](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67629)
=> Erro interno ao acessar o plano na situação de "Expirado"

teste/SME.SGP.TesteIntegracao/Avaliacao/Ao_registrar_avaliacao_para_professor_especialista.cs, teste/SME.SGP.TesteIntegracao/Avaliacao/Ao_validar_atividade_avaliacao.cs, teste/SME.SGP.TesteIntegracao/Avaliacao/TesteAvaliacao.cs, teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#66790](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66790)
=> teste atividade

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs, teste/SME.SGP.TesteIntegracao/PendenciaDevolutiva/Ao_obter_pendencias.cs, teste/SME.SGP.TesteIntegracao/Responsavel/Ao_atribuir_ue_responsavel.cs
Removido UnitOfWork que não estava sendo utilizado
=> Removido UnitOfWork que não estava sendo utilizado

src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/AtribuirResponsavelEncaminhamentoAEE/AtribuirResponsavelEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
[AB#66560](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66560)
=> fix/66560 - ajuste na geração de pendencia de encaminhamentoAEE e consulta de pendencias

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#67752](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67752)
=> fix/67752 - ajuste de obter turmas ao salvar/editar planoAEE

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommandHandler.cs
[AB#67729](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67729)
=> Correção do bug 67729

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommandHandler.cs
[AB#67729](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67729)
=> Complemento do bug 67729

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommandHandler.cs
[AB#67729](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67729)
=> Ajuste verifica frequencia 67729

src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/SalvarAtribuicaoCJUseCase.cs
[AB#67871](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67871)
=> Fix/67871 - ajuste para validação de cargo ao atribuir professor CJ

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#67903](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67903)
=> Fix/67903 - ajuste para obtenção de ed. física na tela do conselho de classe EJA 

src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaFechamento/EnviarNotasFechamentoParaAprovacao/EnviarNotasFechamentoParaAprovacaoCommandHandler.cs
[AB#67399](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67399)
=> Ajuste na mensagem de notificação de notasFechamento

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs
[AB#67897](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67897)
=> fix/67897- ajuste para exclusão e limpeza de informações dos campos Observações e Perc. Individual

src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
[AB#67603](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67603)
=> Erro ao inserir data no filtro da tela de cadastro de eventos

src/SME.SGP.Aplicacao/CasosDeUso/Responsavel/AtribuirUeResponsavelUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs, src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSupervisorEscolaDre.cs, src/SME.SGP.Infra/Dtos/ExisteAtribuicaoExcluidaDto.cs
Duplicidade no registro se iniciar atribuição através da listagem
[AB#66854](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66854)
[AB#67932](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67932)
=>  Duplicidade no registro se iniciar atribuição através da listagem

src/SME.SGP.Aplicacao/Commands/Aulas/CriarAulasInfantilAutomaticamente/CriarAulasInfantilAutomaticamenteCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/AtribuirResponsavelEncaminhamentoAEE/AtribuirResponsavelEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
[AB#67797](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67797)
=> Fix/67797 - ajuste na exibição de detalhes da pendência do tipo fechamento

src/SME.SGP.Aplicacao/CasosDeUso/Responsavel/AtribuirUeResponsavelUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs
[AB#67908](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67908)
[AB#67929](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67929) 
[AB#67913](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67913)
[AB#68000](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68000)
=> Correção Bugs Atribuição de responsáveis Erro ao atribuir

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs
Ajuste para logar as informações do plano e identificar o erro de refrência de objeto.
=> Bug: 67636

src/SME.SGP.Aplicacao/Consultas/ConsultasCompensacaoAusencia.cs
[AB#67168](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67168)
=> Correção do bug 67168

src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/SalvarAtribuicaoCJUseCase.cs
[AB#67871](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67871)
=> fix/67871 -> master

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs, src/SME.SGP.Aplicacao/Commands/Arquivos/CopiarArquivo/CopiarArquivoCommandHandler.cs, src/SME.SGP.Dominio/Enumerados/TipoArquivo.cs
[AB#67844](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67844)
=> Correção do bug 67844

src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs
[AB#68200](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68200)
[AB#68213](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68213)
=> Ajustado para validar se o responsável atribuído esta excluído.

src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/EnviarParaAnaliseEncaminhamentoAEE/EnviarParaAnaliseEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaAtribuirResponsavelEncaminhamentoAEE/GerarPendenciaAtribuirResponsavelEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/GerarPendenciaPAEEEncaminhamentoAEE/GerarPendenciaPAEEEncaminhamentoAEECommandHandler.cs
[AB#68167](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68167)
[AB#68181](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68181)
=> Ajustada geração da pendência para o PAAI.

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoCJ/SalvarAtribuicaoCJUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/Commands/Arquivos/CopiarArquivo/CopiarArquivoCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs, src/SME.SGP.Dominio/Enumerados/TipoArquivo.cs
[AB#68177](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68177)
=> Fix/68177 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs
[AB#67897](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67897)
=> fix/67897 - ajuste para exclusão e limpeza de informações dos campos Observações e Perc. Individual

src/SME.SGP.Aplicacao/Queries/Pendencia/ObterPendenciasPorUsuario/ObterPendenciasPorUsuarioQueryHandler.cs
[AB#67797](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67797)
=> fix/67797  - ajuste para exibição de descrição do tipo fechamento

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
[AB#68239](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68239)
=> Correção do bug 68239

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
[AB#68177](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68177)
=> fix/68177 -> release

src/SME.SGP.Api/Controllers/DiretoriaRegionalEducacaoController.cs, src/SME.SGP.Api/Controllers/SupervisorController.cs, src/SME.SGP.Aplicacao/Consultas/ConsultaDres.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultaDres.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasSupervisor.cs, src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioSupervisorEscolaDre.cs, src/SME.SGP.Infra/Dtos/UnidadeEscolarSemAtribuicaolDto.cs
[AB#68091](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68091)
[AB#68092](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68092)
=> UE já atribuída, aparecendo na lista de UEs sem atribuição

src/SME.SGP.Aplicacao/CasosDeUso/Nota/NotificarAlteracaoNotaFechamentoAgrupadaTurmaUseCase.cs
[AB#60380](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60380)
[AB#67399](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67399)
=> bug 67399 Ajuste no envio de notificações das notasFechamento

src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/EnviarParaAnaliseEncaminhamentoAEE/EnviarParaAnaliseEncaminhamentoAEECommandHandler.cs
[AB#68167](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68167)
=> Ajustada validação para geração da pendência do CP.

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#67889](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67889)
=> Fix/67889 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs
[AB#68351](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68351)
[AB#68385](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68385)
=> Filtro "Responsável" só considera o primeiro nome

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
[AB#68337](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68337) [AB#68495](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68495)
=> fix/68337 - corrigindo regra para exibição dos alunos na tela do conselho de classe.

src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs
[AB#68456](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68456)
=> Corrreção Back

src/SME.SGP.Dados/Repositorios/RepositorioAnotacaoFechamentoAluno.cs
[AB#68586](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68586)
=> fix/68586 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Nota/NotificarAlteracaoNotaFechamentoAgrupadaUseCase.cs, src/SME.SGP.Aplicacao/Queries/WorkflowAprovacaoNotaFechamento/ObterWorkflowAprovacaoNotaFechamentoSemAprovacaoId/ObterWorkflowAprovacaoNotaFechamentoSemAprovacaoIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioWfAprovacaoNotaFechamento.cs
[AB#68343](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68343)
[AB#68864](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68864)
=> Fix/68343 to Release

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#68415](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68415)
=> fix/68415 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioAnotacaoFechamentoAluno.cs
[AB#68855](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68855)
=> Fix/68855 - ajuste de datas e dados corretos na anotação do estudante 

src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoFinal.cs, src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaFechamento/EnviarNotasFechamentoParaAprovacao/EnviarNotasFechamentoParaAprovacaoCommandHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
[AB#68745](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68745)
[AB#68867](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68867)
=> fix/68745 to Release.

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioPorIdSemPerfil/ObterUsuarioPorIdSemPerfilQuery.cs, src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioPorIdSemPerfil/ObterUsuarioPorIdSemPerfilQueryHandler.cs
[AB#68595](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68595)
=> Erro para acessar o plano ao atribuir alguns responsáveis ao plano

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs
[AB#68241](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68241)
=> Correção do bug 68241

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
[AB#68337](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68337) [AB#68415](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68415)
=> Fix/68337 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterInformacoesDeFrequenciaAlunoPorSemestreUseCase.cs
[AB#69039](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69039)
=> fix/69039 - correção ao tratar corretamente bimestre e semestre no RAA

src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
[AB#69015](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69015) [AB#69011](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69011)
=> Fix/69011 - ajuste para exibir turmas CEMEI corretas

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterInformacoesDeFrequenciaAlunoPorSemestreUseCase.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
[AB#69115](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69115)
=> Fix/69115 - correção de condição ao apresentar listagem de alunos ativos na tela de frequência

src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs
[AB#69037](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69037)
=> Correção do bug 69037

src/SME.SGP.Aplicacao/CasosDeUso/Nota/NotificarAlteracaoNotaFechamentoAgrupadaTurmaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasNotificacao.cs, src/SME.SGP.Dados/Repositorios/RepositorioWfAprovacaoNotaFechamento.cs, src/SME.SGP.Infra/Dtos/FechamentoNota/WfAprovacaoNotaFechamentoTurmaDto.cs
[AB#68791](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68791)
[AB#68928](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68928)
=> fix/68791 to Release

src/SME.SGP.Aplicacao/CasosDeUso/Nota/NotificarAlteracaoNotaFechamentoAgrupadaTurmaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs
[AB#68386](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68386)
[AB#68336](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68336)
=> Corrigido conflitos bugs 68386 e 68336.

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
[AB#69115](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69115)
=> fix/69115 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
[AB#69011](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69011)
=> Fix/69011 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosPorTurma/ObterAlunosPorTurmaQueryHandler.cs
[AB#69249](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69249)
=> Ajuste na ordenação da listagem de aluno pela data da situação

src/SME.SGP.Aplicacao/CasosDeUso/ListaoAvaliacoes/ObterNotasParaAvaliacoesListaoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs, src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/CriarCacheDeAvaliacaoAvaliativaPorTurmaCommand.cs, src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/CriarCacheDeAvaliacaoAvaliativaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Notas/ObterNotasPorAlunosAtividadesAvaliativas/ObterNotasPorAlunosAtividadesAvaliativasQuery.cs, src/SME.SGP.Aplicacao/Queries/Notas/ObterNotasPorAlunosAtividadesAvaliativas/ObterNotasPorAlunosAtividadesAvaliativasQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioNotasConceitosConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotasConceitosConsulta.cs, src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs
[AB#67837](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67837)
=> feature/67837 -> story/67481

src/SME.SGP.Api/Controllers/NotasConceitosController.cs, src/SME.SGP.Aplicacao/Comandos/ComandosNotasConceitos.cs, src/SME.SGP.Aplicacao/Interfaces/Comandos/IComandosNotasConceitos.cs, src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioPossuiPermissaoNaTurmaEDisciplinaPorTurmasEDatasAvaliacao/ObterUsuarioPossuiPermissaoNaTurmaEDisciplinaPorTurmasEDatasAvaliacaoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioNotasConceitos.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotasConceitos.cs, src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs
[AB#67835](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67835)
=> Bulk Insert no salvamento

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#69256](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69256)
=> Fix/69256 -> master

scripts/V552__ADICIONAR_AULA_ID_NA_TABELA_REGISTRO_FREQUENCIA_ALUNO.sql, src/SME.SGP.Dados/Mapeamentos/RegistroFrequenciaAlunoMap.cs, src/SME.SGP.Dominio/Entidades/RegistroFrequenciaAluno.cs
[AB#68344](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68344)
=> Modelagem Registro Frequencia Aluno

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#69252](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69252)
=> Ajuste no total de aulas

scripts/V553__ADICIONAR_INDICE_TABELA_PERIODO_ESCOLAR.sql, scripts/V554__ADICIONAR_INDICE_TABELA_PARAMETRO_SISTEMA.sql
[AB#68384](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68384)
[AB#68391](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68391)
=> Criar indices no Período Escolar e parâmetro sistema

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#66651](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/66651)
=> fix/66651 -> r2

src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
[AB#69326](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69326)
=> Fix/69326 -> r2

src/SME.SGP.Aplicacao/Comandos/ComandosNotasConceitos.cs, src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/CriarCacheDeAvaliacaoAvaliativaPorTurmaCommand.cs, src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/CriarCacheDeAvaliacaoAvaliativaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Notas/ObterNotasPorAlunosAtividadesAvaliativas/ObterNotasPorAlunosAtividadesAvaliativasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Usuario/ObterUsuarioPossuiPermissaoNaTurmaEDisciplinaPorTurmasEDatasAvaliacao/ObterUsuarioPossuiPermissaoNaTurmaEDisciplinaPorTurmasEDatasAvaliacaoQueryHandler.cs
[AB#67836](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67836)
=> Feature/67836_v2 -> Story/67841

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosPorTurma/ObterAlunosPorTurmaQueryHandler.cs
[AB#69249](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69249)
=> fix/69249 -> master

src/SME.SGP.Aplicacao/CasosDeUso/MigracaoDadosFrequencia/CarregarRegistroFrequenciaAlunosUseCase.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/InserirFrequenciasAula/InserirFrequenciasAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/InserirRegistrosFrequenciasAlunos/InserirRegistrosFrequenciasAlunosCommand.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/InserirRegistrosFrequenciasAlunos/InserirRegistrosFrequenciasAlunosCommandHandler.cs
[AB#68347](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68347)
=> Ajustar inclusão de Registro Frequência Aluno

src/SME.SGP.Aplicacao/Commands/Frequencia/InserirRegistrosFrequenciasAlunos/InserirRegistrosFrequenciasAlunosCommand.cs
[AB#68347](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68347)
=> Correção da mensagens de validação

src/SME.SGP.Aplicacao/CasosDeUso/Nota/NotificarAlteracaoNotaFechamentoAgrupadaTurmaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/WorkflowAprovacaoNotaFechamento/EnviarNotasFechamentoParaAprovacao/EnviarNotasFechamentoParaAprovacaoCommandHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoTurmaDisciplina.cs
[AB#68902](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68902)
[AB#68336](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68336)
[AB#60380](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60380)
=> fix/68902 -> release

src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs, src/SME.SGP.Dominio.Servicos/ServicoWorkflowAprovacao.cs
[AB#69144](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69144)
[AB#69344](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69344)
=> [Notas de Fechamento] Notificação de alteração da nota final

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunosPorTurma/ObterAlunosPorTurmaQueryHandler.cs
[AB#69359](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69359)
=> Fix/69359 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioAcompanhamentoAlunoConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioAula.cs, src/SME.SGP.Dados/Repositorios/RepositorioConsolidacaoFrequenciaTurmaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioDashBoardFrequencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs
Alterar nos repositórios consultas que fazem join de registro_frequencia_aluno até aula para utilizar a nova referencia.
[AB#68348](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68348)
=> Ajustar consulta de Registros Frequência

src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
[AB#69326](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69326)
=> fix/69326 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
[AB#69338](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69338)
=> Bug: 69338 - Ajuste validação ListaFechamentoNotaAprovacao

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#69359](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69359)
=> fix/69359 -> master

src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
[AB#69315](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69315)
=> fix/69315 - ajustes para verificação de abrangência EOL x SGP

src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
[AB#68336](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68336)
[AB#69264](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69264)
=> Fix/68336 to Release

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs
[AB#58667](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58667)
=> fix/58667 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#68595](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68595)
=> Ajuste para obter o nome do usuário cadastrado

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
Não esta mais trazendo alunos inativos antes da data da aula
=> Corrigido listagem de alunos

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaAlunosComAusencia/ObterListaAlunosComAusenciaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#68390](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68390)
=> Alterar consulta de alunos com ausencia

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#68338](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68338)
=> Fix/68338 -> r2

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs
[AB#58667](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58667)
=> fix/58667 -> master

src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
[AB#69315](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69315)
=> Fix/69315 -> master

src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs
[AB#69442](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69442)
[AB#60380](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/60380)
=> fix/69442 -> release

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#68338](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68338)
=> Fix/68338 -> master

src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/AtribuirResponsavelEncaminhamentoAEE/AtribuirResponsavelEncaminhamentoAEECommandHandler.cs
[AB#68612](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/68612)
=> Bug:68612 - Encaminhamento AEE - critério 3

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ObterEncaminhamentoPorIdUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEAno/ObterAlunoPorCodigoEAnoQuery.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEAno/ObterAlunoPorCodigoEAnoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasAlunoPorFiltro/ObterTurmasAlunoPorFiltroQuery.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasAlunoPorFiltro/ObterTurmasAlunoPorFiltroQueryHandler.cs
[AB#69375](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69375)
=> Correção do bug 69375

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs
[AB#62186](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/62186)
=> fix/62186 -> release-r2

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
[AB#65440](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65440)
=> Correção do bug 65440

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasNotasConceitos.cs, src/SME.SGP.Aplicacao/Queries/Notas/ObterNotaBimestrePorCodigosAlunosEIdFechamento/ObterNotaBimestrePorCodigosAlunosIdsFechamentoQuery.cs, src/SME.SGP.Aplicacao/Queries/Notas/ObterNotaBimestrePorCodigosAlunosEIdFechamento/ObterNotaBimestrePorCodigosAlunosIdsFechamentoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoTurmaDisciplinaConsulta.cs, src/SME.SGP.Infra/Dtos/FechamentoNotaDto.cs
[AB#69179](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69179)
=> remover acesso ao repositório de dentro do laço FOR

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/VerificaEstudantePossuiPlanoAEEPorCodigoEAnoQuery/VerificaPlanosAEEPorCodigosAlunosEAnoQuery.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/VerificaEstudantePossuiPlanoAEEPorCodigoEAnoQuery/VerificaPlanosAEEPorCodigosAlunosEAnoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEConsulta.cs, src/SME.SGP.Infra/Dtos/PlanoAEE/PlanoAEEResumoDto.cs
[AB#69181](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69181)
=> Feature/69181 - remoção da consulta do planoAEE de dentro do FOR 

src/SME.SGP.Aplicacao/Comandos/ComandosAulaPrevista.cs, src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/AulaPrevista/CriarCacheAulaPrevistaCommand.cs, src/SME.SGP.Aplicacao/Commands/Cache/CriarCache/AulaPrevista/CriarCacheAulaPrevistaCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs, src/SME.SGP.Aplicacao/Queries/AulasPrevistas/ObterAulasPrevistasPorCodigoUe/ObterAulasPrevistasPorCodigoUeQuery.cs, src/SME.SGP.Aplicacao/Queries/AulasPrevistas/ObterAulasPrevistasPorCodigoUe/ObterAulasPrevistasPorCodigoUeQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAulaPrevistaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioAulaPrevistaConsulta.cs, src/SME.SGP.Dominio/Entidades/AulaPrevista.cs
[AB#69182](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69182)
=> Feature/69182 - Criar cache e incluir consulta ao cache antes de ir ao repositório de Aulas Previstas

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#69667](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69667)
=> Correção do bug 69667

Jenkinsfile, src/SME.SGP.Aplicacao/CasosDeUso/ConsolidacaoDevolutivas/ConsolidarDevolutivasPorTurmaUseCase.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaPorListaDeAlunosDisciplinaData/ObterFrequenciaPorListaDeAlunosDisciplinaDataQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaPorListaDeAlunosDisciplinaData/ObterFrequenciaPorListaDeAlunosDisciplinaDataQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusenciaAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusenciaDisciplinaRegencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusenciaAluno.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusenciaDisciplinaRegencia.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs, src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs
[AB#69364](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69364)
=> Melhorias no processo de compensação de ausência

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs
[AB#70092](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70092)
[AB#70093](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70093)
=> Correção no Alias da tabela na consulta SQL

src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs
[AB#70106](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70106)
=> fix/70106 -> master

src/SME.SGP.Aplicacao/Commands/Frequencia/InserirFrequenciasAula/InserirFrequenciasAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/InserirRegistrosFrequenciasAlunos/InserirRegistrosFrequenciasAlunosCommand.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/InserirRegistrosFrequenciasAlunos/InserirRegistrosFrequenciasAlunosCommandHandler.cs, src/SME.SGP.Aplicacao/SME.SGP.Aplicacao.csproj, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs
[AB#70315](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70315)
[AB#70377](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70377) 
Ajustes na consulta SQL de ObterRegistroAusenciaPorIdRegistro para retornar todos os dados da entidade registro frequencia aluno com o Id da Aula
=> Tela de Frequência do Listão - Persistência dos dados (Apenas em HOM)

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs
Correção d Estrutura do banco de dados e ajuste consulta SQL
[AB#70423](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70423)
[AB#70023](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70023)
=> Erro ao inserir Nota Final

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasPorPeriodoUseCase.cs
[AB#65481](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65481)
=> fix/65481 -> master

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
Ajuste para Salvar notas consolidadas no conselho de classe. erro componente curricular id null
=> fix/69941 -> release-r2

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs
[AB#69471](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69471)
=> fix/69471 -> master

src/SME.SGP.Aplicacao/Queries/EOL/Aluno/ObterAlunosEolPorTurma/ObterAlunosEolPorTurmaQueryHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs
[AB#70526](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70526)
[AB#70527](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70527)
=> Erro ao gravar nota final de ano anterior

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoReabertura.cs
[AB#71000](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71000)
=> Fix/71000 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#69377](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69377)
=> Correção do bug 69377

src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
[AB#70937](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70937)
=> fix/70937 -> release-r2

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
[AB#69941](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69941)
=> fix/69941_v2 -> release-r2

src/SME.SGP.Aplicacao/Cache/ConselhoDeClasseNotaPosConselhoBimestresCache.cs, src/SME.SGP.Aplicacao/Cache/ServicoDeGerenciamentoDeCache.cs, src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/SalvarConselhoClasseAlunoNotaUseCase.cs, src/SME.SGP.Aplicacao/Commands/Cache/SalvarCache/SalvarValorObjet/SalvarCachePorValorObjetQuery.cs, src/SME.SGP.Aplicacao/Commands/Cache/SalvarCache/SalvarValorObjet/SalvarCachePorValorObjetQueryHandler.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasse/GravarConselhoClasse/GravarConselhoClasseCommadHandler.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasse/InserirConselhoClasseNota/InserirConselhoClasseNotaCommadHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterConselhoClasseNotasAluno/ObterConselhoClasseNotasAlunoQueryHandler.cs, src/SME.SGP.Dados/Cache/RepositorioCache.cs
[AB#70811](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70811)
=> cache fechamento e pós conselho

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/ObterAcompanhamentoAlunoUseCase.cs
[AB#71195](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71195)
=> Correção do bug 71195

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ObterPeriodoEscolarPorTurmaUseCase.cs
[AB#71180](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71180)
=> fix/71180 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoReabertura.cs
[AB#71000](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71000)
=> fix/71000 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#71202](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71202)
=> Correção do bug 71202

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoAluno .cs
[AB#71203](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71203)
=> Correção do bug 71203

src/SME.SGP.Api/Startup.cs
[AB#70173](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70173)
=> Remover Static Files

src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaGoogleClassroom/PublicarFilaGoogleClassroomCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaSerapEstudantes/PublicarFilaSerapEstudantesCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaSgp/PublicarFilaEmLoteSgpCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaSgp/PublicarFilaSgpCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/FilaWorker/PublicaFilaWorkerServidorRelatorios/PublicaFilaWorkerServidorRelatoriosCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Log/SalvarLogViaRabbit/SalvarLogViaRabbitCommandHandler.cs, src/SME.SGP.Infra/Servicos/ServicoAuditoria.cs, src/SME.SGP.Infra/Servicos/ServicoMensageria/Interface/IServicoMensageria.cs, src/SME.SGP.Infra/Servicos/ServicoMensageria/ServicoMensageria.cs, src/SME.SGP.IoC/Extensions/RegistrarRabbit.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ServicoMensageriaFake.cs, teste/SME.SGP.TesteIntegracao/Setup/CollectionFixture.cs
Isso porque temos servidores Rabbit distintos e precisamos 2 serviços distintos para que cada um injete a configuração para seu serviço
=> Ajustado ServicoMensageria segregando em Servico para Aplicação e Serviço para Logs

src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoConceitoConselhoClasse/SalvarHistoricoConceitoConselhoClasseCommand.cs, src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs
[AB#70104](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70104)
=> Correção do bug 70104

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#71270](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71270)
=> Correção do bug 71270

src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
[AB#71246](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71246)
=> Correção do bug 71246

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaFrequenciaAulas/ObterListaFrequenciaAulasQueryHandler.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
[AB#71246](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71246)
=> Ajuste para correção do bug

src/SME.SGP.Aplicacao/CasosDeUso/AtribuicaoDeResponsaveis/RemoverAtribuicaoResponsaveisASPPPorDreUseCase.cs
[AB#71233](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71233)
=> Fix/71233 ->  release

src/SME.SGP.Api/Controllers/PendenciasController.cs, src/SME.SGP.Api/Controllers/RelatorioController.cs
[AB#71369](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71369)
=> fix/71369  - Retirando permissionamentos desnecessários para endpoints de pendências.

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#71251](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71251)
=> back - fix: Plano AEE - retornar responsável quando for um novo plano

src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/InserirRegistrosFrequenciasAlunos/InserirRegistrosFrequenciasAlunosCommandHandler.cs
[AB#71358](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71358)
=> fix/71358 -> release

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/PesquisaResponsavelPlanoPorDreUEUseCase.cs
[AB#71406](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71406)
=> fix/71406 -> release

src/SME.SGP.Aplicacao/CasosDeUso/Responsavel/AtribuirUeResponsavelUseCase.cs
[AB#71237](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71237)
=> Ajuste no fluxo de atribuição de responsável

src/SME.SGP.Api/Controllers/SupervisorController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Responsavel/ObterResponsaveisPorDreUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasSupervisor.cs, src/SME.SGP.Infra/Dtos/Responsavel/TipoReponsavelRetornoDto.cs
Ajuste para verificação do tipo de perfil de usuário logado para restringir a lista de tipos de responsável.
Ajuste pontuais para o funcionamento da implementação.
=> Bug: 71164

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaFrequenciaAulas/ObterListaFrequenciaAulasQueryHandler.cs, src/SME.SGP.Infra/Dtos/Aluno/AlunoRegistroFrequenciaDto.cs, src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaAulaDetalheDto.cs
[AB#71246](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71246)
=> Correção da lista de alunos do listão - Bug 71246

src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAluno.cs
[AB#71358](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71358)
=> Fix/71358_v1 -> release

src/SME.SGP.Aplicacao/Comandos/ComandosUsuario.cs, src/SME.SGP.Aplicacao/Servicos/ServicoTokenJwt.cs
[AB#71386](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71386)
=> Ajuste no auterar perfil com os dados do suporte

src/SME.SGP.Api/Controllers/SupervisorController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Responsavel/AtribuirUeResponsavelUseCase.cs
[AB#71237](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71237)
=> Ajuste no atribuir escolas a supervisores

src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs
[AB#70108](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70108)
=> Correção do bug 70108

src/SME.SGP.Aplicacao/Commands/FilaRabbit/PublicarFilaSgp/PublicarFilaSgpCommandHandler.cs
Correção serviço de mensageria na Master.
=> Correção serviço de mensageria na master

src/SME.SGP.Dados/Repositorios/RepositorioOcorrenciaAluno.cs
[AB#71738](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71738)
=> Correção do bug 71738

teste/SME.SGP.TesteIntegracao/Frequencia/Ao_obter_frequencia_geral_de_aluno.cs
=> Bug: 71487

src/SME.SGP.Infra/Dtos/Aluno/AlunoRegistroFrequenciaDto.cs, src/SME.SGP.Infra/Dtos/AlunoDadosBasicosDto.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs, src/SME.SGP.Infra/Dtos/AlunoReduzidoDto.cs, src/SME.SGP.Infra/Dtos/RegistroFrequenciaAlunoDto.cs
[AB#70152](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70152)
=> Utilizar ElasticSearch para alguns itens em substituiçao do EOL

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterUltimoBimestreAlunoTurma/ObterUltimoBimestreAlunoTurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterUltimoBimestreAlunoTurma/ObterUltimoBimestreAlunoTurmaQueryHandler.cs
[AB#71986](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71986)
=> Correção do bug 71986

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#71904](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71904)
=> Correção do bug 71904

src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/SalvarConselhoClasseAlunoNotaUseCase.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasse/AlterarConselhoClasse/AlterarConselhoClasseCommadHandler.cs
[AB#71987](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71987)
=> Correção do bug 71987

src/SME.SGP.Aplicacao/Commands/ConselhoClasse/AlterarConselhoClasse/AlterarConselhoClasseCommadHandler.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasse/InserirAlterarConselhoClasseAbstrato.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasse/InserirConselhoClasseNota/InserirConselhoClasseNotaCommadHandler.cs
[AB#71948](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71948)
=> [69661 - Melhorias conselho de classe] - Não salva nota pós-conselho

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs
[AB#72020](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72020)
=> Correção do bug 72020

src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterUltimoBimestreAlunoTurma/ObterUltimoBimestreAlunoTurmaQueryHandler.cs
[AB#72017](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72017)
=> Erro interno ao acessar a ABA FINAL 

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
Ajuste para sanar o erro de indice ao excluir pendência do fechamento.
Essa alteração é para o worker de fechamento voltar a funcionar.
=> Bug: 71012

src/SME.SGP.Infra/Dtos/Relatorios/FiltroRelatorioConselhoClasseAtaFinalDto.cs
[AB#71545](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71545)
=> Correção do bug 71545

src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs
[AB#71170](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71170)
=> fix/71170 -> release-r2

src/SME.SGP.Dominio/Entidades/TipoCalendario.cs
[AB#72124](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72124)
=> Correção do bug 72124

src/SME.SGP.Aplicacao/Consultas/ConsultasAulaPrevista.cs
[AB#71170](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71170)
=> fix/71170 -> master

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseUseCase.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterConselhoClasseNotasAluno/ObterConselhoClasseNotasAlunoQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterConselhoClasseNotasAluno/ObterConselhoClasseNotasAlunoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/FechamentoNota/ObterPorFechamentoTurmaDisciplinaIdAlunoCodigo/ObterPorFechamentoTurmaDisciplinaIdAlunoCodigoQuery.cs, src/SME.SGP.Aplicacao/Queries/FechamentoNota/ObterPorFechamentoTurmaDisciplinaIdAlunoCodigo/ObterPorFechamentoTurmaDisciplinaIdAlunoCodigoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurma/ObterFechamentoTurmaPorIdTurma/ObterFechamentoTurmaPorIdTurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurma/ObterFechamentoTurmaPorIdTurma/ObterFechamentoTurmaPorIdTurmaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurmaDisciplina/ObterFechamentoTurmaDisciplinaPorTurmaIdDisciplinaBimestre/ObterFechamentoTurmaDisciplinaPorTurmaIdDisciplinaBimestreQuery.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurmaDisciplina/ObterFechamentoTurmaDisciplinaPorTurmaIdDisciplinaBimestre/ObterFechamentoTurmaDisciplinaPorTurmaIdDisciplinaBimestreQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNotaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseNotaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoTurmaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoTurmaDisciplinaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioNotaConceitoBimestreConsulta.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarFechamentoUseCaseRabbitSgp.cs, teste/SME.SGP.Aplicacao.Teste/CasosDeUso/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCaseTeste.cs
[AB#69941](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69941)
=> Fix/69941 -> master

src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
[AB#71902](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71902)
=> Não permite lançar nota final para EJA

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs
Ajuste na obtenção das informações de frequência, incluindo o vínculo correto entre aula e registro_frequencia.
=> Bug: 72270

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfilPlanejamento/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfilPlanejamentoQuery.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#72316](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72316)
=> Correção do bug 72316

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoFrequencia/ObterInformacoesDeFrequenciaAlunosPorBimestreUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Aluno/ObterAlunoPorCodigoEolEAnoLetivoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/AnotacaoFrequenciaAluno/ObterAnotacaoFrequenciaAlunoPorIdUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/CompensacaoAusencia/NotificarCompensacaoAusenciaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/ListaoAvaliacoes/ObterNotasParaAvaliacoesListaoUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/Salvar/SalvarPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasNotasConceitos.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasRecuperacaoParalela.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigo/ObterAlunoPorCodigoEAnoHistoricoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEAno/ObterAlunoPorCodigoEAnoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaFrequenciaAulas/ObterListaFrequenciaAulasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterAlunosSimplesDaTurma/ObterAlunosSimplesDaTurmaQueryHandler.cs, src/SME.SGP.Infra/Dtos/AlunoDadosBasicosDto.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
[AB#72016](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72016)
=> Ajustando o retorno do NumeroAlunoChamada

teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_validar_informacoes_card_aluno.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ObterAlunosAtivosPorTurmaCodigoQueryHandlerFake.cs
[AB#71293](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71293)
=> Card de Detalhes do Estudante

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
[AB#72323](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72323)
=> fix/72323 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
[AB#72323](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72323)
=> fix/72323 -> r2 (pt.2)

scripts/V556__INSERT_PARAMETRO_SISTEMA_2014_ATE_2020_COMPENSACAO_FORA_PERIODO.sql
[AB#72268](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72268)
=> fix/72268 -> master

src/SME.SGP.Aplicacao/Queries/FechamentoTurma/ObterNotasFechamentosPorTurmasCodigosBimestre/ObterNotasFechamentosPorTurmasCodigosBimestreQuery.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs
[AB#72421](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72421)
=> fix/72421 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
[AB#72323](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72323)
=> Fix/72323 -> master

src/SME.SGP.Infra/Dtos/Log/LogMensagem.cs
=> adicionar logmensagem

src/SME.SGP.Infra/Servicos/ServicoMensageria/ServicoMensageria.cs
=> Adicionado ExcecaoInterna

src/SME.SGP.Aplicacao/Commands/Notificacoes/NotificarCriacaoNotificacao/NotificarCriacaoNotificacaoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Notificacoes/NotificarLeituraNotificacao/NotificarLeituraNotificacaoCommand.cs, src/SME.SGP.Aplicacao/Commands/Notificacoes/NotificarLeituraNotificacao/NotificarLeituraNotificacaoCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasNotificacao.cs, src/SME.SGP.Infra/Dtos/Notificacoes/MenagemLeituraNotificacaoDto.cs, src/SME.SGP.Infra/Dtos/Notificacoes/MensagemCriacaoNotificacaoDto.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpNotificacoes.cs
[AB#72367](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72367)
=> 72367 Notificar leitura da notificação

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs
=> Descendo master para R2

src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
[AB#72321](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72321)
=> fix/72321 -> master

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#72551](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72551)
=> Fix/72551 -> r2

src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
[AB#65218](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65218)
=> Fix/65218 -> master

src/SME.SGP.Aplicacao/Commands/AtribuicaoCJ/InserirAtribuicaoCJ/InserirAtribuicaoCJCommandHandler.cs
[AB#72450](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72450)
=> Correção do bug 72450

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasFinaisBimestresAluno/ObterNotasFinaisBimestresAlunoQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasFinaisBimestresAluno/ObterNotasFinaisBimestresAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNotaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseNotaConsulta.cs
[AB#72706](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72706)
=> fix/72706 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasFinaisBimestresAluno/ObterNotasFinaisBimestresAlunoQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasFinaisBimestresAluno/ObterNotasFinaisBimestresAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNotaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseNotaConsulta.cs
[AB#72706](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72706)
=> fix/72706 -> master

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#69328](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69328)
=> Fix/69328 -> release-r2

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#69223](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69223)
=> ajuste fix/69223 -> release-r2

src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs
[AB#72680](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72680)
=> fix/72680 -> r2

src/SME.SGP.Aplicacao/Queries/PeriodoEscolar/ObterPeriodoEscolarIdPorTurmaBimestre/ObterPeriodoEscolarIdPorTurmaBimestreAnoLetivoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPeriodoEscolarConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPeriodoEscolarConsulta.cs
[AB#72062](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72062)
=> corerção tela de notas

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#72806](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72806)
=> fix/72806 -> r2

src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
[AB#72778](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72778)
=> Fix/72778 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaConsulta.cs
This reverts commit c94d455262f5f84aad4b76a7221cef0c4e7e2c71.
=> Revert "Bug: 72270"

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#72551](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72551)
=> fix/72551 -> master

src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
[AB#72778](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72778)
=> fix/72778 -> master

src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseParecerConclusivoConsulta.cs
[AB#70937](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70937)
=> Fix/70937 -> master

src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#72514](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72514)
=>  Fix/72514 -> release-r2

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs
[AB#72618](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72618)
=> Correção do bug 72618

src/SME.SGP.Aplicacao/Comandos/ComandosNotasConceitos.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#72957](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72957)
=> Correção do bug 72957

src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs
[AB#72723](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72723)
=> Erro ao cadastra nota final eja

src/SME.SGP.Aplicacao/CasosDeUso/Responsavel/AtribuirUeResponsavelUseCase.cs
[AB#72358](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72358)
=> Erro ao tentar atribuir um "Supervisor Escolar"

src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
[AB#72786](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72786)
=> Correção do bug 72786

src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs
[AB#72680](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72680)
=> fix/72680 -> master

src/SME.SGP.Dominio.Servicos/ServicoDeNotasConceitos.cs
[AB#72964](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72964)
=> fix/72964 -> master

src/SME.SGP.Aplicacao/Comandos/ComandosConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfilPlanejamento/ObterComponentesCurricularesPorCodigoTurmaLoginEPerfilPlanejamentoQuery.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioFechamentoNota.cs
[AB#72003](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72003)
=> Bug 72003 -> Release

src/SME.SGP.Api/Controllers/ArmazenamentoController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Estudante/ObterEstudanteFotoUseCase.cs, src/SME.SGP.Aplicacao/Commands/Armazenamento/DownloadArquivo/DownloadArquivoCommandHandler.cs, src/SME.SGP.Infra/Servicos/ServicoArmazenamento/ServicoArmazenamento.cs
[AB#72771](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72771)
=> Correção requisição imagem miniIO

src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#72514](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72514)
=> Fix/72514 -> master

src/SME.SGP.Dados/Repositorios/RepositorioDiarioBordo.cs
[AB#72786](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72786)
=> Complemento da correção do bug 72786

src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
tratativa para turmas duplicadas
[AB#72023](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72023)
=> Bug 72023 Tratar turma duplicadas

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/Salvar/SalvarPlanoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/AtualizarTurmaAlunoPlanoAEE/AtualizarTurmaAlunoPlanoAEECommand.cs, src/SME.SGP.Aplicacao/Commands/PlanoAEE/AtualizarTurmaAlunoPlanoAEE/AtualizarTurmaAlunoPlanoAEECommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEAno/ObterAlunoPorCodigoEAnoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEE.cs, src/SME.SGP.Infra/Dtos/AlunoReduzidoDto.cs
[AB#73017](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73017)
=> Fix/73017 -> master

src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/SalvarConselhoClasseAlunoNotaUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/VerificaSePodeEditarNota/VerificaSePodeEditarNotaQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/VerificaSePodeEditarNota/VerificaSePodeEditarNotaQueryHandler.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioFechamentoNota.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_alterar_nota_conceito_pos_conselho_bimestre_final.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_gerar_parecer_conclusivo.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_gravar_conselho_ano_anterior.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_inserir_alterar_nota_conceito_pos_conselho_bimestre_final.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_inserir_alterar_nota_numerica_pos_conselho_bimestre_final.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_inserir_nota_conceito_pos_conselho_bimestre.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_inserir_nota_conceito_pos_conselho_bimestre_final.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_inserir_nota_numerica_pos_conselho_bimestre.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_inserir_nota_numerica_pos_conselho_bimestre_final.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_inserir_nota_pos_conselho_aluno_inativo_durante_periodo_reabertura.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_inserir_nota_pos_conselho_professor_regente_anterior.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_lancar_periodo_abertura_reabertura.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_listar_opcoes_impressao.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_registrar_conselho_classe_aluno_nota.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_validar_situacao_conselho_classe.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_validar_situacao_do_parecer_conclusivo.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Base/ConselhoDeClasseTesteBase.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/ServicosFakes/ObterAlunosInativoDurantePeriodoReaberturaQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/ServicosFakes/ObterAlunosPorTurmaEAnoLetivoQueryHandlerFakeValidarSituacaoConselho.cs
[AB#73103](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73103)
=> Erro ao salvar nota pós conselho

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/Salvar/SalvarPlanoAEEUseCase.cs, teste/SME.SGP.TesteIntegracao/ItensBasicosBuilder.cs, teste/SME.SGP.TesteIntegracao/Plano AEE/Ao_gerar_plano_com_responsavel.cs
=> ajustes de teste prod - plano aee

src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
[AB#73191](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73191)
=> Correção do bug 73191

src/SME.SGP.Aplicacao/Commands/Aulas/ValidarComponentesDoProfessor/ValidarComponentesDoProfessorCommandHandler.cs
[AB#69223](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69223)
=> Correção do bug 69223

src/SME.SGP.Aplicacao/Queries/DashboardFechamento/ObterNotasFinaisFechamento/ObterNotasFinaisFechamentoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseConsulta.cs
[AB#73518](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73518)
=> Correção do bug 73518

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/VerificaFrequenciaRegistradaAlunosInativosUseCase.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/ExcluirRegistroFrequenciaAlunoPorId/ExcluirRegistroFrequenciaAlunoPorIdCommand.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/ExcluirRegistroFrequenciaAlunoPorId/ExcluirRegistroFrequenciaAlunoPorIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/VerificaFrequenciaRegistradaParaAlunosInativos/VerificaFrequenciaRegistradaParaAlunosInativosCommand.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/VerificaFrequenciaRegistradaParaAlunosInativos/VerificaFrequenciaRegistradaParaAlunosInativosCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Frequencia/IVerificaFrequenciaRegistradaAlunosInativosUseCase.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaBimestres/ObterFrequenciaBimestresQuery.cs, src/SME.SGP.Aplicacao/Queries/RegistroFrequenciaAluno/ObterRegistroFrequenciaAlunoPorTurmaEAlunoCodigo/ObterRegistroFrequenciaAlunoPorTurmaEAlunoCodigoQuery.cs, src/SME.SGP.Aplicacao/Queries/RegistroFrequenciaAluno/ObterRegistroFrequenciaAlunoPorTurmaEAlunoCodigo/ObterRegistroFrequenciaAlunoPorTurmaEAlunoCodigoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroFrequenciaAluno.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroFrequenciaAlunoConsulta.cs, src/SME.SGP.Frequencia.Worker/WorkerRabbitFrequencia.cs, src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaAlunoTurmaDto.cs, src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaAulaARecalcularDto.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpFrequencia.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarFrequenciaUseCaseRabbitSgp.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#70007](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70007)
=> Fix/70007 -> r2 (rotina para excluir frequência consolidada após inativação de alunos da turma

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Infra/Dtos/AlunoPorTurmaResposta.cs
[AB#72123](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72123)
=> BUG 72123 - Correção lançar nota pós conselho aluno inativo no ano anterior

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#73139](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73139)
=> Correção do bug 73139

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasAlunoPorFiltro/ObterTurmasAlunoPorFiltroQueryHandler.cs
[AB#73477](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73477)
=> Fix/73477 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Dominio.Servicos/ServicoConselhoClasse.cs
[AB#72516](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72516)
=> fix/72516 -> release-r2

src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasAlunoPorFiltro/ObterTurmasAlunoPorFiltroQuery.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasAlunoPorFiltro/ObterTurmasAlunoPorFiltroQueryHandler.cs
[AB#73645](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73645)
=> bug 73645 -> master

src/SME.SGP.Infra/Utilitarios/UtilData.cs
[AB#69223](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69223)
=> Correção do bug 69223 - Quantidade de aulas restantes.

src/SME.SGP.Aplicacao/Comandos/ComandosConselhoClasseAluno.cs
[AB#73493](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73493)
=> Erro ao salvar a tela de conselho de classe utilizando Ano anterior

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterTurmasAlunoPorFiltro/ObterTurmasAlunoPorFiltroQueryHandler.cs
[AB#73477](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73477)
=> fix/73477 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/VerificaFrequenciaRegistradaAlunosInativosUseCase.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/CalcularFrequenciaPorTurma/CalcularFrequenciaPorTurmaCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/ExcluirRegistroFrequenciaAlunoPorId/ExcluirRegistroFrequenciaAlunoPorIdCommand.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/ExcluirRegistroFrequenciaAlunoPorId/ExcluirRegistroFrequenciaAlunoPorIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/VerificaFrequenciaRegistradaParaAlunosInativos/VerificaFrequenciaRegistradaParaAlunosInativosCommand.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/VerificaFrequenciaRegistradaParaAlunosInativos/VerificaFrequenciaRegistradaParaAlunosInativosCommandHandler.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Frequencia/IVerificaFrequenciaRegistradaAlunosInativosUseCase.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaBimestres/ObterFrequenciaBimestresQuery.cs, src/SME.SGP.Aplicacao/Queries/RegistroFrequenciaAluno/ObterRegistroFrequenciaAlunoPorTurmaEAlunoCodigo/ObterRegistroFrequenciaAlunoPorTurmaEAlunoCodigoQuery.cs, src/SME.SGP.Aplicacao/Queries/RegistroFrequenciaAluno/ObterRegistroFrequenciaAlunoPorTurmaEAlunoCodigo/ObterRegistroFrequenciaAlunoPorTurmaEAlunoCodigoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroFrequenciaAluno.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroFrequenciaAlunoConsulta.cs, src/SME.SGP.Frequencia.Worker/WorkerRabbitFrequencia.cs, src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaAlunoTurmaDto.cs, src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaAulaARecalcularDto.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpFrequencia.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarFrequenciaUseCaseRabbitSgp.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#70007](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70007)
=> Fix/70007 -> master

src/SME.SGP.Aplicacao/Comandos/ComandosConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoReabertura.cs, src/SME.SGP.Aplicacao/Queries/EOL/Professor/ProfessorPodePersistirTurma/ProfessorPodePersistirTurmaQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Turma/TurmaEmPeriodoFechamento/TurmaEmPeriodoFechamentoQueryHandler.cs, src/SME.SGP.Dominio/Entidades/FechamentoReabertura.cs, src/SME.SGP.Dominio/Entidades/TipoCalendario.cs, src/SME.SGP.Infra.Mensageria/RabbitModelPooledObjectPolicy.cs
[AB#73498](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73498)
=> Erro ao salvar conselho de ano anterior para EJA

src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
[AB#72561](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72561)
=> correção validação componentes para gerar o parecer

scripts/V557__INSERT_PARAMETRO_SISTEMA_GERAR_FECHAMENTO_TURMAS_ED_FISICA_2020.sql, scripts/V558__AJUSTE_FUNCTION_F_ATA_FINAL_OBTER_NOTAS_TURMAS_ALUNOS.sql, src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/GerarFechamentoTurmaEdFisica2020AlunosTurmaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/GerarFechamentoTurmaEdFisica2020UseCase.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/GerarFechamentoTurmaEdFisica2020/GerarFechamentoTurmaEdFisica2020Command.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/GerarFechamentoTurmaEdFisica2020/GerarFechamentoTurmaEdFisica2020CommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Fechamento/IGerarFechamentoTurmaEdFisica2020AlunosTurmaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Fechamento/IGerarFechamentoTurmaEdFisica2020UseCase.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterAlunosEdFisica2020/ObterAlunosEdFisica2020Query.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterAlunosEdFisica2020/ObterAlunosEdFisica2020QueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs, src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs, src/SME.SGP.Fechamento.Worker/WorkerRabbitFechamento.cs, src/SME.SGP.Infra/Dtos/DashboardFechamento/TurmaFechamentoDisciplinaSituacaoDto.cs, src/SME.SGP.Infra/Dtos/Fechamento/FechamentoAlunoComponenteDTO.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpFechamento.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarFechamentoUseCaseRabbitSgp.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#72770](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72770)
=> Fix/72770 -> r2

src/SME.SGP.Aplicacao/Comandos/ComandosNotificacao.cs, src/SME.SGP.Dominio/Entidades/Notificacao.cs
[AB#73314](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73314)
=> Inconsistência indevida ao salvar nota conselho de classe

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasse.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurma/ObterFechamentoTurmaComConselhoDeClassePorTurmaCodigoSemestre/ObterFechamentoTurmaComConselhoDeClassePorTurmaCodigoSemestreQuery.cs, src/SME.SGP.Aplicacao/Queries/FechamentoTurma/ObterFechamentoTurmaComConselhoDeClassePorTurmaCodigoSemestre/ObterFechamentoTurmaComConselhoDeClassePorTurmaCodigoSemestreQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFechamentoTurmaConsulta.cs
[AB#73275](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73275)
=> Verificar se o fechamento tem conselho de classe

scripts/V558__ALTERAR_REGISTROS_WF_APROVACAO.sql, scripts/V558__UPDATE_REGISTROS_WF_APROVACAO.sql
[AB#73219](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73219)
=> bug 73219 -> master

src/SME.SGP.Aplicacao/Commands/CompensacaoAusencia/AlterarTotalCompensacoesPorCompensacaoAlunoId/AlterarTotalCompensacoesPorCompensacaoAlunoIdCommand.cs, src/SME.SGP.Aplicacao/Commands/CompensacaoAusencia/AlterarTotalCompensacoesPorCompensacaoAlunoId/AlterarTotalCompensacoesPorCompensacaoAlunoIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/CompensacaoAusencia/ExcluiCompensacaoAlunoPorCompensacaoAlunoId/ExcluiCompensacaoAlunoPorCompensacaoAlunoIdCommand.cs, src/SME.SGP.Aplicacao/Commands/CompensacaoAusencia/ExcluiCompensacaoAlunoPorCompensacaoAlunoId/ExcluiCompensacaoAlunoPorCompensacaoAlunoIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Frequencia/VerificaFrequenciaRegistradaParaAlunosInativos/VerificaFrequenciaRegistradaParaAlunosInativosCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterCompensacoesPorAlunoETurma/ObterCompensacoesPorAlunoETurmaQuery.cs, src/SME.SGP.Aplicacao/Queries/CompensacaoAusencia/ObterCompensacoesPorAlunoETurma/ObterCompensacoesPorAlunoETurmaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusenciaAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioCompensacaoAusenciaAlunoConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusenciaAluno.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioCompensacaoAusenciaAlunoConsulta.cs, src/SME.SGP.Infra/Dtos/CompensacaoAusencia/CompensacaoAlunoBimestreQuantidadeDto.cs, src/SME.SGP.Infra/Dtos/CompensacaoAusencia/TotalCompensacaoAlunoPorCompensacaoIdDto.cs, src/SME.SGP.Infra/Dtos/Frequencia/FrequenciaAlunoTurmaDto.cs
[AB#71245](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71245)
=> Fix/71245 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/AcompanhamentoAluno/SalvarAcompanhamentoAlunoUseCase.cs, src/SME.SGP.Aplicacao/Commands/Arquivos/MoverArquivosTemporarios/MoverArquivosTemporariosCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/DeletarArquivo/DeletarArquivoDeRegistroExcluidoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/DeletarArquivo/RemoverArquivosExcluidosCommandHandler.cs, src/SME.SGP.Dominio/Constantes/ArmazenamentoObjetos.cs
[AB#73909](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73909)
=> 73909 - Arquivos não são removidos do MinIO em algumas telas

src/SME.SGP.Aplicacao/Comandos/ComandosConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasseAluno/SalvarConselhoClasseAluno/SalvarConselhoClasseAlunoCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaConsulta.cs
"Erro" Fechamento da turma não localizado para o bimestre (Mesmo com fechamento iniciado) 
[AB#74067](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74067)
=>  "Erro" Fechamento da turma não localizado para o bimestre (Mesmo com fechamento iniciado) 

src/SME.SGP.Aplicacao/CasosDeUso/ConselhoClasse/SalvarConselhoClasseAlunoNotaUseCase.cs
[AB#73492](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73492)
[AB#73299](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73299)
=> Correção bug 73299.

src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
[AB#74094](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74094)
=> Fix/74094 -> r2

src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs
[AB#73287](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73287)
=> fix/73287 - Adicionando obrigatoriedade da seleção de estudantes para a compensação

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEAno/ObterAlunoPorCodigoEAnoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Aluno/ObterAlunoPorCodigoEol/ObterAlunoPorCodigoEolQueryHandler.cs
[AB#73284](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73284)
=> Correção do bug 73284

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/ObterPlanoAEEPorIdUseCase.cs
[AB#74145](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74145)
=> Complemento para corrigir o bug 74145

scripts/V557__INSERT_PARAMETRO_SISTEMA_GERAR_FECHAMENTO_TURMAS_ED_FISICA_2020.sql, scripts/V558__AJUSTE_FUNCTION_F_ATA_FINAL_OBTER_NOTAS_TURMAS_ALUNOS.sql, src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/GerarFechamentoTurmaEdFisica2020AlunosTurmaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/GerarFechamentoTurmaEdFisica2020UseCase.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/GerarFechamentoTurmaEdFisica2020/GerarFechamentoTurmaEdFisica2020Command.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/GerarFechamentoTurmaEdFisica2020/GerarFechamentoTurmaEdFisica2020CommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Fechamento/IGerarFechamentoTurmaEdFisica2020AlunosTurmaUseCase.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Fechamento/IGerarFechamentoTurmaEdFisica2020UseCase.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterAlunosEdFisica2020/ObterAlunosEdFisica2020Query.cs, src/SME.SGP.Aplicacao/Queries/EOL/Aluno/Turmas/ObterAlunosEdFisica2020/ObterAlunosEdFisica2020QueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaDisciplinaConsulta.cs, src/SME.SGP.Dominio/Enumerados/TipoParametroSistema.cs, src/SME.SGP.Fechamento.Worker/WorkerRabbitFechamento.cs, src/SME.SGP.Infra/Dtos/DashboardFechamento/TurmaFechamentoDisciplinaSituacaoDto.cs, src/SME.SGP.Infra/Dtos/Fechamento/FechamentoAlunoComponenteDTO.cs, src/SME.SGP.Infra/Fila/Rotas/RotasRabbitSgpFechamento.cs, src/SME.SGP.IoC/Extensions/RegistrarCasoDeUsoRabbitSgp/RegistrarFechamentoUseCaseRabbitSgp.cs, src/SME.SGP.IoC/RegistrarDependencias.cs
[AB#72770](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72770)
=> Fix/72770 -> master

src/SME.SGP.Aplicacao/Comandos/ComandosConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Commands/ConselhoClasseAluno/SalvarConselhoClasseAluno/SalvarConselhoClasseAlunoCommandHandler.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioFechamentoNota.cs
Auditoria na tela de conselho incorreta / Erro interno ao trocar de bimestre 
[AB#74163](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74163)
=> Fix/74163 - Auditoria na tela de conselho incorreta / Erro interno ao trocar de bimestre 

teste/SME.SGP.TesteIntegracao/PlanoDeAula/Base/PlanoAulaTesteBase.cs
[AB#72508](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72508)
=> configuração inicial da base

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs
[AB#73482](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73482)
=> fix/73482 -> r2

src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterChaveEValorPorTipoEAno/ObterChaveEValorPorTipoEAnoQuery.cs, src/SME.SGP.Aplicacao/Queries/ParametroSistema/ObterChaveEValorPorTipoEAno/ObterChaveEValorPorTipoEAnoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioParametrosSistemaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioParametrosSistemaConsulta.cs, src/SME.SGP.Dominio.Servicos/ServicoRecuperacaoParalela.cs, src/SME.SGP.Infra/Dtos/ParametrosSistema/ParametroSistemaRetornoDto.cs
[AB#74091](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74091)
=> fix/74091 -> master

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs
[AB#73482](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73482)
=> fix/73482 -> master

src/SME.SGP.Aplicacao/Comandos/ComandosConselhoClasseAluno.cs
[AB#74169](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74169)
=> Erro "Existe(m) componente(s) curriculares sem a nota informada"

src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterQuestoesPlanoAEEPorVersao/ObterQuestoesPlanoAEEPorVersaoQueryHandler.cs
[AB#74204](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74204)
=> fix/74204 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs
[AB#73286](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73286)
=> Correção do bug 73286

teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_cp_diretor.cs, teste/SME.SGP.TesteIntegracao/SME.SGP.TesteIntegracao.csproj
Cadastro do plano de aula pelo CP ou Diretor.
[AB#72502](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72502)
=> Feature/72502 - Cadastro do plano de aula pelo CP ou Diretor.

src/SME.SGP.IoC/RegistrarDependencias.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_cp_diretor.cs, teste/SME.SGP.TesteIntegracao/Setup/CollectionFixture.cs, teste/SME.SGP.TesteIntegracao/Setup/RegistradorDependencias.cs, teste/SME.SGP.TesteIntegracao/TesteBase.cs
Adicionado Validações
[AB#72502](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72502)
=> Feature/72502 - Adicionado Validações

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterIndicativoPendenciasAulasPorTipo/ObterIndicativoPendenciasAulasPorTipoQuery.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterIndicativoPendenciasAulasPorTipo/ObterIndicativoPendenciasAulasPorTipoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPendenciaAulaConsulta.cs, teste/SME.SGP.Aplicacao.Teste/Queries/Listao/ObterIndicativoPendenciasAulasPorTipoQueryHandlerTeste.cs
[AB#72890](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72890)
=> Obtenção de pendências está demorando 7 segundos

teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_professor_cj.cs
[AB#72501](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72501)
=> Feature/72501 - Cadastro plano Aula pelo professor CJ

teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_professor.cs
[AB#72500](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72500)
=> feature/72500 --> story/70263

src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioPlanoAula.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_sem_plano_anual.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Base/FiltroPlanoAula.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Base/PlanoAulaTesteBase.cs
[AB#72504](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72504) - Quando não há plano anual
=> Fix/72504 - Quando não há plano anual

src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoPorConselhoFechamentoAluno/GerarParecerConclusivoPorConselhoFechamentoAlunoQuery.cs
[AB#73103](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73103)
=> Retirado a validação do id do conselho pois não é obrigatório

teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_cp_diretor.cs
[AB#72502](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72502)
=> Validando registros no banco

teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_para_componente_territorio_do_saber.cs, teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#72505](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72505)
=> cadastro de plano de aula para componente do território do saber

teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_cp_diretor.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_professor_cj.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_sem_plano_anual.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Base/FiltroPlanoAula.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Base/PlanoAulaTesteBase.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/ServicosFakes/Ao_registrar_plano_aula_com_atribuicao_abertura_reabertura.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/ServicosFakes/Ao_registrar_plano_aula_com_atribuicao_encerrada.cs
[AB#72503](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72503)
=> Criação de teste para Atribuição encerrado e abertura/reabertura

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciaPorAulaUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoTurmaDisciplina.cs
[AB#74176](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74176)
=> Aluno especifico aparecendo duas vezes na listagem

src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs
[AB#73495](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73495)
=> Correção do bug 73495

src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioPlanoAula.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_cp_diretor.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_professor.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_professor_cj.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_sem_plano_anual.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Base/FiltroPlanoAula.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Base/PlanoAulaTesteBase.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/ServicosFakes/Ao_registrar_plano_aula_com_atribuicao_abertura_reabertura.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/ServicosFakes/Ao_registrar_plano_aula_com_atribuicao_encerrada.cs
[AB#72503](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72503)
=> Conclusão do teste Atribuição encerrado e abertura/reabertura

src/SME.SGP.Api/Controllers/FechamentoTurmaController.cs, src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/InserirFechamentoTurmaDisciplinaUseCase.cs, src/SME.SGP.Aplicacao/CasosDeUso/Fechamento/ListarFechamentoTurmaBimestreUseCase.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommand.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoConceitoFechamento/SalvarHistoricoConceitoFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/HistoricoNota/SalvarHistoricoNotaFechamento/SalvarHistoricoNotaFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs, src/SME.SGP.Aplicacao/Interfaces/CasosDeUso/Fechamento/IInserirFechamentoTurmaDisciplinaUseCase.cs, src/SME.SGP.Infra/Dtos/AuditoriaPersistenciaDto.cs, src/SME.SGP.Infra/Dtos/AuditoriaPersistenciaFechamentoNotaConceitoTurmaDto.cs, src/SME.SGP.Infra/Dtos/FechamentoNota/FechamentoNotaConceitoTurmaDto.cs, src/SME.SGP.Infra/Utilitarios/AuditoriaUtil.cs
[AB#72892](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72892)
=> Alterar fechamento para não consultar tudo após a persistência

src/SME.SGP.Aplicacao/Commands/PlanoAula/MigrarPlanoAula/MigrarPlanoAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasRegularesPorUeModalidadePeriodoAnoLetivo/ObterTurmasRegularesPorUeModalidadePeriodoAnoLetivoQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmasRegularesPorUeModalidadePeriodoAnoLetivo/ObterTurmasRegularesPorUeModalidadePeriodoAnoLetivoQueryHandler.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_cp_diretor.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_para_componente_territorio_do_saber.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_sem_plano_anual.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_copiar_plano_de_aula.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Base/PlanoAulaTesteBase.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/ServicosFakes/ObterPlanejamentoAnualPorAnoEscolaBimestreETurmaQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/ServicosFakes/ObterTurmasRegularesPorUeModalidadePeriodoAnoLetivoQueryHandlerFake.cs
[AB#72507](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72507) - Cópia do plano
=> Feature/72507 - Cópia do plano

teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_alterar_plano_aula.cs
[AB#72506](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72506)
=> testes alterar plano de aula

src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#72516](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72516)
=> Fix/72516 -> r2

src/SME.SGP.Aplicacao/Commands/ParecerConclusivo/GerarParecerConclusivoAluno/GerarParecerConclusivoAlunoCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs
[AB#72516](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72516)
=> Fix/72516 -> master

scripts/V561__ALTERAR_CONSTRAINT_TABELA_SUPERVISOR_ESCOLA_DRE.sql
[AB#73584](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73584)
=> Correção do bug 73584

src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterQuestoesPlanoAEEPorVersao/ObterQuestoesPlanoAEEPorVersaoQueryHandler.cs
[AB#74204](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74204)
=> fix/74204 -> master

src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaFrequenciaTratar/AlterarAulaFrequenciaTratarCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/RegistroFrequenciaAluno/ObterRegistroFrequenciaAlunoPorAulaId/ObterRegistroFrequenciaAlunoPorAulaIdQuery.cs, src/SME.SGP.Aplicacao/Queries/RegistroFrequenciaAluno/ObterRegistroFrequenciaAlunoPorAulaId/ObterRegistroFrequenciaAlunoPorAulaIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/RegistroFrequenciaAluno/ObterRegistroFrequenciaAlunoPorTurmaEAlunoCodigo/ObterRegistroFrequenciaAlunoPorTurmaEAlunoCodigoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroFrequenciaAlunoConsulta.cs, src/SME.SGP.Dominio/Entidades/RegistroFrequenciaAluno.cs
[AB#74311](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74311)
=> Fix/74311 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioPendenciaAulaConsulta.cs
[AB#70267](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/70267)
=> 70267 Correção da query de identificação de pendencia

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#74341](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74341)
=> 74341 - Erro busca notas de bimestre final sem conselho

src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#74202](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74202)
=> fix/74202 -> r2

src/SME.SGP.Aplicacao/Commands/Aulas/AlterarAulaFrequenciaTratar/AlterarAulaFrequenciaTratarCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/RegistroFrequenciaAluno/ObterRegistroFrequenciaAlunoPorAulaId/ObterRegistroFrequenciaAlunoPorAulaIdQuery.cs, src/SME.SGP.Aplicacao/Queries/RegistroFrequenciaAluno/ObterRegistroFrequenciaAlunoPorAulaId/ObterRegistroFrequenciaAlunoPorAulaIdQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/RegistroFrequenciaAluno/ObterRegistroFrequenciaAlunoPorTurmaEAlunoCodigo/ObterRegistroFrequenciaAlunoPorTurmaEAlunoCodigoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioRegistroFrequenciaAlunoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioRegistroFrequenciaAlunoConsulta.cs, src/SME.SGP.Dominio/Entidades/RegistroFrequenciaAluno.cs
[AB#74311](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74311)
=> fix/74311 -> master

src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs
[AB#74420](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74420)
=> Exibir as atividades avaliativas mesmo sem fechamento

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAluno/ObterConsultaFrequenciaGeralAlunoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#73627](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73627)
=> fix/73627 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioAtividadeAvaliativa.cs
[AB#74420](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74420)
=> fix/74420 --> Master

scripts/V562__ADICIONAR_TURMA_ID_NA_TABELA_PENDENCIA.sql
[AB#67524](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/67524)
=> Modelagem Pendencia

src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Base/PlanoAulaTesteBase.cs
[AB#73952](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73952)
=> Alterar chamada para abrangência compacta quando for gestor escolar

src/SME.SGP.Aplicacao/Queries/Notas/VerificaNotasTodosComponentesCurriculares/VerificaNotasTodosComponentesCurricularesQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#74202](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74202)
=> Fix/74202 -> master

src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#74523](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74523)
=> Fix/74523 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs
[AB#74523](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74523)
=> fix/74523 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasDisciplina.cs, src/SME.SGP.Dominio/Entidades/Aula.cs
[AB#65725](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/65725)
=> Correção do bug 65725

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ValidarMediaAlunosAtividadeAvaliativaUseCase.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasAbrangencia.cs, src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterAbrangenciaTurmaComUsuarioQuery/ObterAbrangenciaTurmaComUsuarioQuery.cs, src/SME.SGP.Aplicacao/Queries/Abrangencia/ObterAbrangenciaTurmaComUsuarioQuery/ObterAbrangenciaTurmaComUsuarioQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioNota.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioTurma.cs, src/SME.SGP.Infra/Dtos/AbrangenciaFiltroRetorno.cs
[AB#73958](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73958)
=> Alterar use case ValidarMediaAlunosAtividadeAvaliativaUseCase

src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/ObjetivoAprendizagemAula/ObterObjetivosAprendizagemAulaPorPlanoAulaId/ObterObjetivosAprendizagemAulaPorPlanoAulaIdQuery.cs, src/SME.SGP.Aplicacao/Queries/ObjetivoAprendizagemAula/ObterObjetivosAprendizagemAulaPorPlanoAulaId/ObterObjetivosAprendizagemAulaPorPlanoAulaIdQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioObjetivoAprendizagemAula.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioObjetivoAprendizagemAula.cs, src/SME.SGP.Infra/Dtos/PlanoAula/ObjetivoAprendizagemAulaDto.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_alterar_plano_aula.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_cp_diretor.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_para_componente_territorio_do_saber.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_professor.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_cadastrar_plano_aula_professor_cj.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_copiar_plano_de_aula.cs, teste/SME.SGP.TesteIntegracao/PlanoAula/Ao_registrar_plano_aula_com_atribuicao_abertura_reabertura.cs
[AB#74192](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74192)
=> Ajuste na persistência dos objetivos de aprendizagem

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
[AB#73627](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73627)
=> fix/73627 pt. 2 -> r2

teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_validar_situacao_do_parecer_conclusivo.cs
=> ajuste nos testes de integração envolvendo parecer conclusivo

src/SME.SGP.Dados/Repositorios/RepositorioAulaConsulta.cs
[AB#74628](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74628)
=> Correção do bug 74628

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs
Ajuste no carregamento dos dados do conselho de classe:
- Complementação da verificação de matrículas válidas;
- Ajuste na consulta para obter os registros de frequência desconsiderando registros duplicados indevidamente.
=> Bug: 66653

teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_haver_validacao_da_coordenacao.cs
[AB#71636](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71636)
=> testes validação da coordenação

teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_ocorrer_analise_cefai.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/ServicosFakes/ObterUsuarioLogadoIdQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#71638](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71638)
=> teste ánalise do cefai

src/SME.SGP.Aplicacao/CasosDeUso/Frequencia/ObterFrequenciasPorPeriodoUseCase.cs
[AB#74655](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74655)
=> fix/74655 -> master

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAluno/ObterConsultaFrequenciaGeralAlunoQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterConsultaFrequenciaGeralAlunoPorTurmas/ObterConsultaFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaGeralAlunoPorTurmas/ObterFrequenciaGeralAlunoPorTurmasQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioFrequenciaAlunoDisciplinaPeriodoConsulta.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_gerar_parecer_conclusivo.cs, teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_validar_situacao_do_parecer_conclusivo.cs
[AB#73627](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73627)
=> Fix/73627 -> master

teste/SME.SGP.TesteIntegracao/Listao/Ao_listar_periodos_e_predefinicao.cs, teste/SME.SGP.TesteIntegracao/Listao/Base/FiltroListao.cs, teste/SME.SGP.TesteIntegracao/Listao/Base/ListaoTesteBase.cs, teste/SME.SGP.TesteIntegracao/ServicosFakes/ObterAlunosPorTurmaEDataMatriculaQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#72872](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72872)
=> Criação da base de testes

src/SME.SGP.Aplicacao/Consultas/ConsultasCompensacaoAusencia.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaAlunoPorBimestreTurmaDisciplinaTipo/ObterFrequenciaAlunoPorBimestreTurmaDisciplinaTipoQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaAlunoPorBimestreTurmaDisciplinaTipo/ObterFrequenciaAlunoPorBimestreTurmaDisciplinaTipoQueryHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs
[AB#74836](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74836)
=> Fix/74836 -> r2

src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
[AB#74942](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74942)
=> Fix/74942 -> r2

teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_Enviar_para_analise_encaminhamento_AEE.cs
[AB#71520](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71520)
=> Atribuição do responsável - PAAI

scripts/V555__PARAMETRO_APROVACAO_NOTA_2022.sql
[AB#72310](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72310)
=> Script de criação de parametro de aprovação de nota 2022

src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs
Ajuste de remoção de código fixo.
=> Bug: 72773

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/DevolverEncaminhamentoUseCase.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioEncaminhamentoAee.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_devolver_encaminhamento_cp.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Base/EncaminhamentoAEETesteBase.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/ServicosFake/ExecutaNotificacaoDevolucaoEncaminhamentoAEECommandHandlerFake.cs
[AB#71516](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71516)
=> Devolução de encaminhamento aee

src/SME.SGP.Aplicacao/Commands/Armazenamento/DownloadArquivo/DownloadArquivoCommandHandler.cs
[AB#75015](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75015)
=> 75015 tratamento temporario de download de fotos de alunos

src/SME.SGP.Aplicacao/CasosDeUso/PlanoAEE/EncerrarPlanosAEEEstudantesInativosUseCase.cs, src/SME.SGP.Aplicacao/Queries/Turma/ObterTurmaComUeEDrePorCodigo/ObterTurmaComUeEDrePorCodigoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioEncerramentoAutomaticoPlanoAee.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_atribuir_responsavel_plano_aee.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_editar_plano_aee.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_encerrar_automaticamente.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_pesquisar_aluno_plano_aee.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Ao_realizar_devolucao.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/Base/PlanoAEETesteBase.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/ServicosFakes/ObterAlunoPorCodigoEolQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/PlanoAEE/ServicosFakes/ObterMatriculasAlunoPorCodigoEAnoQueryHandlerFake.cs, teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#71639](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71639) - Encerramento automático
Validar o encerramento automático de planos de alunos que ficaram inativos ou foram transferidos.
=> Feature/71639 - Encerramento automático

src/SME.SGP.Aplicacao/Queries/ParecerConclusivo/ObterParecerConclusivoAluno/ObterParecerConclusivoAlunoQueryHandler.cs
[AB#74942](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74942)
=> fix/74942 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
[AB#74723](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74723)
=> fix/74723 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#69378](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/69378)
=> Fix/69378 -> r2

teste/SME.SGP.TesteIntegracao/Listao/Ao_listar_periodos_e_predefinicao.cs, teste/SME.SGP.TesteIntegracao/Listao/Base/FiltroListao.cs, teste/SME.SGP.TesteIntegracao/Listao/Base/ListaoTesteBase.cs, teste/SME.SGP.TesteIntegracao/Listao/ServicosFake/ObterAlunosPorTurmaEDataMatriculaQueryHandlerFakeListao.cs
[AB#72874](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72874)
=> Períodos e predefinição

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ExcluirEncaminhamentoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/ExcluirQuestaoEncaminhamentoAEEPorSecaoId/ExcluirQuestaoEncaminhamentoAEEPorSecaoIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/ExcluirSecoesEncaminhamentoAEEPorEncaminhamentoId/ExcluirSecoesEncaminhamentoAEEPorEncaminhamentoIdCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/ExcluirPendenciaEncaminhamentoAEE/ExcluirPendenciaEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioEncaminhamentoAee.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_excluir_encaminhamento.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Base/EncaminhamentoAEETesteBase.cs
[AB#71523](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71523)
=> Exclusão de encaminhamento aee

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/DevolverEncaminhamentoUseCase.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioEncaminhamentoAee.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_devolver_encaminhamento_cp.cs
[AB#71516](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71516)
=> Adicionando a regra que somente podem ser devolvidos encaminhamentos quando for gestor da escola

src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/EnviarParaAnaliseEncaminhamentoAEE/EnviarParaAnaliseEncaminhamentoAEECommandHandler.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_Enviar_para_analise_encaminhamento_AEE.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Base/EncaminhamentoAEETesteBase.cs
[AB#71516](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71516)
[AB#71519](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71519)
=> Ajustando nome dos testes

src/SME.SGP.Aplicacao/Queries/Frequencia/ObterListaFrequenciaAulas/ObterListaFrequenciaAulasQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaPreDefinida.cs
[AB#73744](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73744)
=> Correção do bug 73744

src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/EncerrarEncaminhamentoAEE/EncerrarEncaminhamentoAEECommandHandler.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioEncaminhamentoAee.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_Editar_Encaminhamento.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Base/EncaminhamentoAEETesteBase.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAee/Ao_editar_encaminhamento_para_indeferir.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAee/ServicosFake/ExecutaNotificacaoEncerramentoEncaminhamentoAEECommandHandlerFake.cs
[AB#71517](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71517)
=> Validação da coordenação - Indeferir

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
[AB#74999](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74999)
=> fix/74999 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/ConcluirEncaminhamentoAEEUseCase.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioEncaminhamentoAee.cs, src/SME.SGP.Dominio/Entidades/Usuario.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Base/EncaminhamentoAEETesteBase.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAee/Ao_editar_encaminhamento_concluindo_parecer.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAee/ServicosFake/ExecutaNotificacaoConclusaoEncaminhamentoAEECommandHandlerFake.cs
[AB#71521](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71521)
=> Teste integrado concluir encaminhamento aee

src/SME.SGP.Dados/Mapeamentos/RegistrarMapeamentos.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_Editar_Encaminhamento.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_cadastrar_encaminhamento_sim.cs, teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Base/EncaminhamentoAEETesteBase.cs
[AB#71511](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71511)
=> Descrição do encaminhamento - Sim

teste/SME.SGP.TesteIntegracao/EncaminhamentoAEE/Ao_cadastrar_encaminhamento_nao_nao_sei.cs
[AB#71512](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71512)
=> Descrição do encaminhamento - Não e não sei

src/SME.SGP.Aplicacao/CasosDeUso/Nota/ObterNotasParaAvaliacoesUseCase.cs
[AB#74999](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74999)
=> Fix/74999 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
[AB#74723](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74723)
=> fix/74723 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs, src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQueryHandler.cs
[AB#75046](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75046)
=> Fix/75046 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioPendencia.cs
[AB#75147](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75147)
=> Erro na listagem de pendências (perfil ADM SME e Diretor)

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs, src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQueryHandler.cs
=> fix/75046 -> master

src/SME.SGP.Aplicacao/Commands/Frequencia/InserirFrequenciasAula/InserirFrequenciasAulaCommandHandler.cs, teste/SME.SGP.TesteIntegracao/Listao/Ao_alterar_frequencia.cs, teste/SME.SGP.TesteIntegracao/Listao/Base/ListaoTesteBase.cs
[AB#72880](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72880)
=> Feature/72880 - Alteração

teste/SME.SGP.TesteIntegracao/Listao/Ao_validar_apresentacao_dos_alunos.cs, teste/SME.SGP.TesteIntegracao/Listao/Base/ListaoTesteBase.cs, teste/SME.SGP.TesteIntegracao/Listao/ServicosFake/ObterAlunosAtivosPorTurmaCodigoQueryHandlerFakeListao.cs, teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#72881](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72881)
=> Apresentação dos alunos

src/SME.SGP.Aplicacao/Commands/Frequencia/InserirFrequenciasAula/InserirFrequenciasAulaCommandHandler.cs, teste/SME.SGP.TesteIntegracao/Listao/Ao_alterar_frequencia.cs, teste/SME.SGP.TesteIntegracao/Listao/Ao_lancar_frequencia_bimestre_encerrado.cs, teste/SME.SGP.TesteIntegracao/Listao/Ao_lancar_frequencia_cj.cs, teste/SME.SGP.TesteIntegracao/Listao/Ao_lancar_frequencia_componente.cs, teste/SME.SGP.TesteIntegracao/Listao/Ao_lancar_frequencia_professor.cs, teste/SME.SGP.TesteIntegracao/Listao/Ao_lancar_frequencia_professor_com_atribuicao.cs, teste/SME.SGP.TesteIntegracao/Listao/Ao_lancar_frequencia_professor_sem_atribuicao.cs, teste/SME.SGP.TesteIntegracao/Listao/Base/FiltroListao.cs, teste/SME.SGP.TesteIntegracao/Listao/Base/ListaoTesteBase.cs, teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#72879](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/72879)
=> Outros cenários

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
[AB#74961](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74961)
=> Correção do bug 74961

teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
[AB#74961](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74961)
Fix testes automatizados.
=> Fix dos testes conselho de classe.

teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
Correção dos testes conselho de classe.
=> Correção dos testes conselho de classe.

teste/SME.SGP.TesteIntegracao/ConselhoDeClasse/Ao_gerar_parecer_conclusivo.cs, teste/SME.SGP.TesteIntegracao/TesteBaseComuns.cs
Correção dos testes conselho de classe
=> Correção dos testes conselho de classe

src/SME.SGP.Dados/Repositorios/RepositorioFechamentoConsolidado.cs
[AB#75188](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75188)
=> Correção do bug 75188

src/SME.SGP.Aplicacao/Commands/Usuarios/ReiniciarSenha/ReiniciarSenhaCommandHandler.cs
[AB#75036](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75036)
=> Correção do bug 75036

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasConceitosConselhoClassePorTurmasCodigosEBimestre/ObterNotasConceitosConselhoClassePorTurmasCodigosEBimestreQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasFinaisBimestresAluno/ObterNotasFinaisBimestresAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNotaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseNotaConsulta.cs
Conselho de Classe - Nota pós-conselho bimestre não exibida na aba Final
[AB#75086](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75086)
[AB#75189](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75189)
=> Conselho de Classe - Nota pós-conselho bimestre não exibida na aba Final

src/SME.SGP.Aplicacao/CasosDeUso/EncaminhamentoAee/RegistrarEncaminhamentoAEEUseCase.cs, src/SME.SGP.Aplicacao/Commands/EncaminhamentoAEE/Pendencias/ExcluirPendenciasEncaminhamentoAEECP/ExcluirPendenciasEncaminhamentoAEECPCommand.cs
[AB#71619](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71619)
=> Encaminhamento AEE - Parecer do AEE e some a pendência

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#75459](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75459)
=> Fix/75459 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs
=> Bug: 74961

src/SME.SGP.Aplicacao/Comandos/ComandosRelatorioSemestralPAPAluno.cs, src/SME.SGP.Aplicacao/Commands/DeletarArquivo/RemoverArquivosExcluidosCommandHandler.cs
[AB#75318](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75318)
=> 75318 - Ajuste injeção de dependencia IOptions ConfiguracaoArmazenamento

src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaPlanoAulaUseCase.cs, src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/PendenciaAula/ObterPendenciaIdPorComponenteProfessorBimestre/ObterPendenciaIdPorComponenteProfessorBimestreQuery.cs
BUG [AB#74395](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74395)
Sinalizador de pendência não sendo marcado na frequência
=> Sinalizador de pendência não sendo marcado na frequência

src/SME.SGP.Aplicacao/CasosDeUso/DiasLetivos/ObterDiasLetivosPorUeETurnoUseCase.cs, src/SME.SGP.Aplicacao/Queries/DiasLetivos/ObterDiasPorPeriodosEscolaresComEventosLetivosENaoLetivos/ObterDiasPorPeriodosEscolaresComEventosLetivosENaoLetivosQuery.cs, src/SME.SGP.Aplicacao/Queries/DiasLetivos/ObterDiasPorPeriodosEscolaresComEventosLetivosENaoLetivos/ObterDiasPorPeriodosEscolaresComEventosLetivosENaoLetivosQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEvento.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEvento.cs
[AB#75259](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75259)
=> fix/75259 --> Master - Correção dos eventos de integração

src/SME.SGP.Api/Controllers/AbrangenciaController.cs, src/SME.SGP.Aplicacao/Commands/PlanoAula/MigrarPlanoAula/MigrarPlanoAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasAbrangencia.cs
[AB#58211](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58211)
=> Fix/58211 -> r2

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#75459](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75459)
=> fix/75459 -> master

src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs, src/SME.SGP.Aplicacao/Servicos/ServicoAbrangencia.cs
[AB#71173](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/71173)
=> 71173 - Correção de busca/persistencia de abrangencia supervisores

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaGeralUseCase.cs, src/SME.SGP.Aplicacao/Queries/FechamentoAcompanhamentoTurmas/ObterTurmasConsolidacaoFechamentoGeralPorAnoLetivoTiposEscola/ObterTurmasConsolidacaoFechamentoGeralPorAnoLetivoTiposEscolaQuery.cs, src/SME.SGP.Aplicacao/Queries/FechamentoAcompanhamentoTurmas/ObterTurmasConsolidacaoFechamentoGeralPorAnoLetivoTiposEscola/ObterTurmasConsolidacaoFechamentoGeralPorAnoLetivoTiposEscolaQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioTurmaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioTurmaConsulta.cs, src/SME.SGP.Infra/Dtos/FechamentoAcompanhamentoTurmas/FiltroConsolidacaoTurmaDto.cs
Alteração do endpoint de consolidação de fechamento possibilitando a execução de processamento de múltiplas turmas.
=> Bug: 75220

src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoFinal.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/InserirOuAtualizarCacheFechamentoNotaConceito/InserirOuAtualizarCacheFechamentoNotaConceitoCommand.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/InserirOuAtualizarCacheFechamentoNotaConceito/InserirOuAtualizarCacheFechamentoNotaConceitoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/InserirOuAtualizarCacheFechamentoNotaConceito/InserirOuAtualizarCacheFechamentoNotaConceitoCommandValidator.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Infra/Dtos/FechamentoNota/FechamentoNotaConceitoDto.cs
[AB#74426](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74426)
=> [70490 Melhorias no Listão]  Notas do bimestre não refletem na aba final

src/SME.SGP.Aplicacao/Consultas/ConsultasCompensacaoAusencia.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaAlunoPorBimestreTurmaDisciplinaTipo/ObterFrequenciaAlunoPorBimestreTurmaDisciplinaTipoQuery.cs, src/SME.SGP.Aplicacao/Queries/Frequencia/ObterFrequenciaAlunoPorBimestreTurmaDisciplinaTipo/ObterFrequenciaAlunoPorBimestreTurmaDisciplinaTipoQueryHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoCompensacaoAusencia.cs, src/SME.SGP.Dominio/Constantes/MensagensNegocio/MensagemNegocioComuns.cs
[AB#74836](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74836)
=> Fix/74836 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Aula/Pendencia/PendenciaAulaPlanoAulaUseCase.cs, src/SME.SGP.Aplicacao/Commands/PendenciaAula/SalvarPendenciaAulasPorTipo/SalvarPendenciaAulasPorTipoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/Professores/ObterProfessorTitularPorTurmaEComponenteCurricular/ObterProfessorTitularPorTurmaEComponenteCurricularQueryHandler.cs
[AB#74395](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74395)
Adicionado SalvarLogViaRabbitCommand
=> Adicionado SalvarLogViaRabbitCommand

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs, src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQuery.cs, src/SME.SGP.Aplicacao/Queries/Turma/ListagemTurmasComComponente/ObterTurmasComComponentesQueryHandler.cs, src/SME.SGP.Infra/Dtos/Turma/RetornoConsultaListagemTurmaComponenteDto.cs
[AB#75182](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75182)
=> fix/75182 -> r2

src/SME.SGP.Aplicacao/Queries/EncaminhamentoAee/ObterEncaminhamentosAee/ObterEncaminhamentosAEEQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/PlanoAEE/ObterPlanosAEE/ObterPlanosAEEQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioEncaminhamentoAEE.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAEEConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioEncaminhamentoAEE.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioPlanoAEEConsulta.cs
[AB#75231](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75231)
=> Correção do bug 75231

src/SME.SGP.Api/Controllers/AbrangenciaController.cs, src/SME.SGP.Aplicacao/Commands/PlanoAula/MigrarPlanoAula/MigrarPlanoAulaCommandHandler.cs, src/SME.SGP.Aplicacao/Consultas/ConsultasAbrangencia.cs, src/SME.SGP.Aplicacao/Interfaces/Consultas/IConsultasAbrangencia.cs
[AB#58211](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/58211)
=> Fix/58211 -> master

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
[AB#73989](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73989)
=> fix/73989 -> release-r2

teste/SME.SGP.TesteIntegracao/RegistroIndividual/Ao_editar_excluir_e_listar_registro_individual.cs, teste/SME.SGP.TesteIntegracao/RegistroIndividual/Base/RegistroIndividualTesteBase.cs, teste/SME.SGP.TesteIntegracao/RegistroIndividual/ServicosFakes/MoverArquivosTemporariosCommandHandlerFake.cs
[AB#74023](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74023)
=> Criação de teste registro individual

teste/SME.SGP.TesteIntegracao/RegistroIndividual/Ao_criar_registro_deve_permitir.cs, teste/SME.SGP.TesteIntegracao/RegistroIndividual/Base/FiltroRegistroIndividualDto.cs, teste/SME.SGP.TesteIntegracao/RegistroIndividual/Base/RegistroIndividualTesteBase.cs, teste/SME.SGP.TesteIntegracao/RegistroIndividual/ServicosFakes/MoverArquivosTemporariosCommandHandlerFake.cs
[AB#74020](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74020) - Criação do registro - Deve permitir
=> Feature/74020 - Criação do registro - Deve permitir

src/SME.SGP.Api/Controllers/UsuarioEscolaAquiController.cs
[AB#75316](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75316)
=> fix/75316 -> r2

src/SME.SGP.Aplicacao/CasosDeUso/Turma/ListarTurmasComComponentesUseCase.cs
[AB#73989](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/73989)
=> Fix/73989 -> master

src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs
=> Bug: 76052

src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoFinal.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/InserirOuAtualizarCacheFechamentoNotaConceito/InserirOuAtualizarCacheFechamentoNotaConceitoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Infra/Dtos/FechamentoNota/FechamentoNotaConceitoDto.cs
[AB#74426](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74426)
=> Atualização do cache para regência de classe

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasConceitosConselhoClassePorTurmasCodigosEBimestre/ObterNotasConceitosConselhoClassePorTurmasCodigosEBimestreQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasFinaisBimestresAluno/ObterNotasFinaisBimestresAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNotaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseNotaConsulta.cs
[AB#75086](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75086) - Conselho de Classe - Nota pós-conselho bimestre não exibida na aba Final
=> Fix/75086 - Conselho de Classe - Nota pós-conselho bimestre não exibida na aba Final

src/SME.SGP.Aplicacao/Consultas/ConsultasFechamentoFinal.cs
[AB#76001](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76001)
=> fix/76001 -> r2

src/SME.SGP.Aplicacao/Comandos/ComandosFechamentoFinal.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/InserirOuAtualizarCacheFechamentoNotaConceito/InserirOuAtualizarCacheFechamentoNotaConceitoCommand.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/InserirOuAtualizarCacheFechamentoNotaConceito/InserirOuAtualizarCacheFechamentoNotaConceitoCommandHandler.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/InserirOuAtualizarCacheFechamentoNotaConceito/InserirOuAtualizarCacheFechamentoNotaConceitoCommandValidator.cs, src/SME.SGP.Aplicacao/Commands/Fechamento/SalvarFechamento/SalvarFechamentoCommandHandler.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasConceitosFechamentoPorTurmasCodigosEBimestre/ObterNotasConceitosFechamentoPorTurmasCodigosEBimestreQuery.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasConceitosFechamentoPorTurmasCodigosEBimestre/ObterNotasConceitosFechamentoPorTurmasCodigosEBimestreQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/FechamentoNota/ObterPorFechamentosTurma/ObterPorFechamentosTurmaQueryHandler.cs, src/SME.SGP.Dominio.Servicos/ServicoFechamentoFinal.cs, src/SME.SGP.Infra/Dtos/FechamentoNota/FechamentoNotaConceitoDto.cs
=> Notas do bimestre não refletem na aba final

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasConceitosConselhoClassePorTurmasCodigosEBimestre/ObterNotasConceitosConselhoClassePorTurmasCodigosEBimestreQueryHandler.cs, src/SME.SGP.Aplicacao/Queries/ConselhoClasse/ObterNotasFinaisBimestresAluno/ObterNotasFinaisBimestresAlunoQueryHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioConselhoClasseNotaConsulta.cs, src/SME.SGP.Dominio.Interfaces/Repositorios/IRepositorioConselhoClasseNotaConsulta.cs
=> Fix/76105 -> r2

src/SME.SGP.Dados/Repositorios/RepositorioFrequenciaDiariaAluno.cs
=> Correção do bug 74917

src/SME.SGP.Api/Controllers/UsuarioEscolaAquiController.cs
[AB#75316](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75316)
=> fix/75316 -> master

src/SME.SGP.Dados/Repositorios/RepositorioAbrangencia.cs
[AB#76100](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76100)
=> fix/76100 -> master

scripts/V567__CORRECAO_FUNCTION_F_ATA_FINAL_OBTER_NOTAS_TURMAS_ALUNOS.sql
[AB#74923](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74923)
=> Correção do bug 74923

src/SME.SGP.Aplicacao/Consultas/ConsultasConselhoClasseAluno.cs
[AB#76105](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76105)
=> fix/76105 -> master

src/SME.SGP.Aplicacao/Commands/PlanoAula/Salvar/SalvarPlanoAulaCommandHandler.cs, src/SME.SGP.Dados/Repositorios/RepositorioPlanoAula.cs
[AB#76092](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/76092) - Plano de Aula - não salva a exclusão dos itens de objetivos de aprendizagem
=> FIX/76092 - Plano de Aula - não salva a exclusão dos itens de objetivos de aprendizagem

src/SME.SGP.Aplicacao/Queries/ComponentesCurriculares/ObterComponentesCurricularesPorUsuarioECodigoTurma/ObterComponentesCurricularesPorUsuarioECodigoTurmaQueryHandler.cs
[AB#74920](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/74920)
=> Correção do bug 74920

src/SME.SGP.Aplicacao/CasosDeUso/FechamentoAcompanhamentoTurmas/ExecutarConsolidacaoTurmaConselhoClasseAlunoUseCase.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoNotaConsulta.cs, src/SME.SGP.Dados/Repositorios/RepositorioFechamentoTurmaConsulta.cs
Ajustes na consultas de obtenção de notas considerando a disciplina atribuída para nota ao particionar o sequencial dos registros e eleger o último aplicado. Aplicar a funcionalidade de obter último registro de nota atribuída no processo de consolidação para componentes com regência.
=> Bug: 76210

src/SME.SGP.Aplicacao/Consultas/ConsultasSupervisor.cs, src/SME.SGP.Dados/Repositorios/RepositorioSupervisorEscolaDre.cs
[AB#75192](https://dev.azure.com/amcomgov/c1dcf343-60ee-40b6-a30a-3b9c12c6d220/_workitems/edit/75192)
=> Correção do bug 75192
